# Benchmark 1 – Replication of MLP for Antimicrobial Resistance Prediction from MALDI-TOF Spectra

## Objective

In this notebook, we implement the first benchmark model of the project:  
the replication of the **Multi-Layer Perceptron (MLP)** described in:

> Astudillo, C. A., López-Cortés, X. A., Ocque, E., & Manríquez-Troncoso, J. M. (2024).  
> *Multi-label classification to predict antibiotic resistance from raw clinical MALDI-TOF mass spectrometry data*.  
> Scientific Reports, 14, 31283.  
> https://doi.org/10.1038/s41598-024-82697-w


## Background

The referenced study proposes a multi-label classification framework to predict antimicrobial resistance (AMR) from MALDI-TOF mass spectrometry data. The authors benchmarked several machine learning algorithms aming which we find Multi-Layer Perceptron (MLP) achieving competitive and often superior performance in terms of Weighted F1-score (WF1), particularly in multi-label scenarios.

# Imports and Configuration

In [3]:
import sys
import os
import importlib
import pickle
import numpy as np
import pandas as pd
from collections import Counter
from sklearn.model_selection import train_test_split
from sklearn.base import BaseEstimator, ClassifierMixin
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import f1_score, make_scorer
from skopt import BayesSearchCV
from skopt.space import Real, Integer, Categorical
from tqdm.auto import tqdm
from joblib import dump, load
from sklearn.metrics import f1_score
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset
import optuna
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import f1_score
from tqdm.auto import tqdm
import os
import numpy as np
import pandas as pd
import warnings
from sklearn.metrics import f1_score, accuracy_score, hamming_loss

warnings.filterwarnings("ignore")

PROJECT_ROOT = "/export/usuarios01/egarroyo/MALDI_for_AMR_prediction"
if PROJECT_ROOT not in sys.path:
    sys.path.append(PROJECT_ROOT)
import utils.config
importlib.reload(utils.config)
from utils.config import DATASET_ROOT, PICKLE_OUTPUT_DIR, DRIAMS_A_PICKLE
print("Pickle path:", DRIAMS_A_PICKLE)

Pickle path: /export/usuarios01/egarroyo/MALDI_for_AMR_prediction/data/DRIAMS_A_AMR_paper_replication.pkl

# 1. Loading the DRIAMS-A AMR Dataset

We load the previously generated DRIAMS-A pickle file.

The pickle contains:
- Preprocessed MALDI-TOF spectra (`data`)
- Species labels (`label`)
- Metadata (`meta`)
- Antimicrobial resistance matrix (`amr`)
- Antibiotics list (`antibiotics`)

In [4]:
with open(DRIAMS_A_PICKLE, "rb") as f:
    payload = pickle.load(f)

print("Keys in pickle:", payload.keys())

Keys in pickle: dict_keys(['data', 'label', 'meta', 'amr', 'antibiotics'])

In [5]:
X = payload["data"]
y_species = payload["label"]
amr = payload["amr"]
antibiotics = payload["antibiotics"]

print("Spectral data shape:", X.shape)
print("AMR matrix shape:", amr.shape)
print("Number of antibiotics:", len(antibiotics))
print("Antibiotic names:", antibiotics)
print("Unique species:", np.unique(y_species))

Spectral data shape: (14925, 6000)
AMR matrix shape: (14925, 9)
Number of antibiotics: 9
Antibiotic names: ['Oxacillin', 'Clindamycin', 'Fusidic acid', 'Ciprofloxacin', 'Ceftriaxone', 'Piperacillin-Tazobactam', 'Cefepime', 'Imipenem', 'Meropenem']
Unique species: ['Escherichia_Coli' 'Klebsiella_Pneumoniae' 'Pseudomonas_Aeruginosa'
 'Staphylococcus_Aureus']


# 2. Defining Species-Specific Antibiotic Subsets

According to Table 1 of the paper:

- *Staphylococcus aureus* → Oxacillin, Clindamycin, Fusidic acid
- *Escherichia coli* → Ciprofloxacin, Ceftriaxone, Piperacillin-Tazobactam, Cefepime
- *Klebsiella pneumoniae* → Ciprofloxacin, Ceftriaxone, Imipenem, Meropenem
- *Pseudomonas aeruginosa* → Ciprofloxacin, Imipenem, Meropenem

We now:

1. Subset the dataset by species.
2. Select only the relevant antibiotics.
3. Count the number of complete cases (no missing values across required antibiotics).

In [6]:
# Build AMR DataFrame
amr_df = pd.DataFrame(amr, columns=antibiotics)

# Add species column
amr_df["species"] = y_species

amr_df.head()

,Oxacillin,Clindamycin,Fusidic acid,Ciprofloxacin,Ceftriaxone,Piperacillin-Tazobactam,Cefepime,Imipenem,Meropenem,species
0,NaN,NaN,NaN,0.0,NaN,0.0,0.0,0.0,0.0,Pseudomonas_Aeruginosa
1,NaN,NaN,NaN,0.0,NaN,0.0,0.0,0.0,0.0,Pseudomonas_Aeruginosa
2,NaN,NaN,NaN,0.0,NaN,0.0,0.0,0.0,0.0,Pseudomonas_Aeruginosa
3,NaN,NaN,NaN,0.0,NaN,1.0,1.0,NaN,1.0,Pseudomonas_Aeruginosa
4,NaN,NaN,NaN,0.0,NaN,1.0,1.0,NaN,1.0,Pseudomonas_Aeruginosa

In [7]:
species_antibiotics = {
    "Staphylococcus_Aureus": [
        "Oxacillin", "Clindamycin", "Fusidic acid"
    ],
    "Escherichia_Coli": [
        "Ciprofloxacin", "Ceftriaxone",
        "Piperacillin-Tazobactam", "Cefepime"
    ],
    "Klebsiella_Pneumoniae": [
        "Ciprofloxacin", "Ceftriaxone",
        "Imipenem", "Meropenem"
    ],
    "Pseudomonas_Aeruginosa": [
        "Ciprofloxacin", "Imipenem", "Meropenem"
    ]
}

summary = []

for species, ab_list in species_antibiotics.items():
    
    df_species = amr_df[amr_df["species"] == species]
    df_ab = df_species[ab_list]
    
    # Complete cases: all required antibiotics tested
    complete_mask = df_ab.notna().all(axis=1)
    n_complete = complete_mask.sum()
    
    summary.append({
        "Species": species,
        "Total isolates": len(df_species),
        "Complete-case isolates": n_complete
    })

summary_df = pd.DataFrame(summary)
summary_df

                  Species  Total isolates  Complete-case isolates
0   Staphylococcus_Aureus            3791                    3556
1        Escherichia_Coli            4990                    4663
2   Klebsiella_Pneumoniae            2869                    2813
3  Pseudomonas_Aeruginosa            3275                    2262

# 3. Construction of Resistance Patterns (Label Power Set)

Following the methodology described in the paper, we now:

1. Work separately for each bacterial species.
2. Select only complete-case isolates (no missing AMR values).
3. Encode each resistance combination as a single class (Label Power Set).
4. Remove rare resistance patterns (≤ 10 samples).
5. Count the remaining isolates.

In [8]:
species_datasets = {}
summary_patterns = []

for species, ab_list in species_antibiotics.items():
    
    print(f"\nProcessing {species}")
    
    # Subset species
    df_species = amr_df[amr_df["species"] == species].copy()
    
    # Select antibiotics
    df_ab = df_species[ab_list].copy()
    
    # Keep complete cases only
    complete_mask = df_ab.notna().all(axis=1)
    df_ab = df_ab[complete_mask]
    
    print("Complete-case isolates:", len(df_ab))
    
    # Create resistance pattern string (e.g., 0101)
    df_ab["pattern"] = df_ab.astype(int).astype(str).agg("".join, axis=1)
    
    # Count pattern frequencies
    pattern_counts = df_ab["pattern"].value_counts()
    
    print("Number of unique patterns before filtering:", len(pattern_counts))
    
    # Remove rare patterns (≤ 10 samples)
    valid_patterns = pattern_counts[pattern_counts > 10].index
    df_filtered = df_ab[df_ab["pattern"].isin(valid_patterns)]
    
    print("Remaining isolates after removing rare patterns:", len(df_filtered))
    print("Remaining patterns:", df_filtered["pattern"].nunique())
    
    # Store filtered dataset
    species_datasets[species] = df_filtered.copy()
    
    summary_patterns.append({
        "Species": species,
        "Isolates_after_filtering": len(df_filtered),
        "Number_of_patterns": df_filtered["pattern"].nunique()
    })

summary_patterns_df = pd.DataFrame(summary_patterns)
summary_patterns_df

Processing Staphylococcus_Aureus
Complete-case isolates: 3556
Number of unique patterns before filtering: 8
Remaining isolates after removing rare patterns: 3556
Remaining patterns: 8

Processing Escherichia_Coli
Complete-case isolates: 4663
Number of unique patterns before filtering: 13
Remaining isolates after removing rare patterns: 4649
Remaining patterns: 11

Processing Klebsiella_Pneumoniae
Complete-case isolates: 2813
Number of unique patterns before filtering: 9
Remaining isolates after removing rare patterns: 2795
Remaining patterns: 5

Processing Pseudomonas_Aeruginosa
Complete-case isolates: 2262
Number of unique patterns before filtering: 7
Remaining isolates after removing rare patterns: 2257
Remaining patterns: 6

                  Species  Isolates_after_filtering  Number_of_patterns
0   Staphylococcus_Aureus                      3556                   8
1        Escherichia_Coli                      4649                  11
2   Klebsiella_Pneumoniae                      2795                   5
3  Pseudomonas_Aeruginosa                      2257                   6

# 4. Global Stratified Train-Test Split (Based on Resistance Patterns)

To ensure a fair comparison between:

- Multi-label classification (Label Power Set)
- Single-label binary classifiers
- Multiclass classification

we perform a single global train-test split per species.

The split is stratified according to the full resistance pattern,
ensuring that the distribution of resistance combinations is preserved
between train and test sets.

The same split will later be reused for:
- Multi-label training
- All binary antibiotic-specific classifiers
- The multiclass classifier

In [9]:
global_splits = {}

for species in species_datasets.keys():
    
    print(f"\nSplitting {species}")
    
    df_species = species_datasets[species].copy()
    
    # Extract X indices from original dataset
    indices = df_species.index.values
    
    # Pattern for stratification
    y_pattern = df_species["pattern"].values
    
    train_idx, test_idx = train_test_split(
        indices,
        test_size=0.2,
        stratify=y_pattern,
        random_state=42
    )
    
    global_splits[species] = {
        "train_idx": train_idx,
        "test_idx": test_idx
    }
    
    print("Train size:", len(train_idx))
    print("Test size:", len(test_idx))

Splitting Staphylococcus_Aureus
Train size: 2844
Test size: 712

Splitting Escherichia_Coli
Train size: 3719
Test size: 930

Splitting Klebsiella_Pneumoniae
Train size: 2236
Test size: 559

Splitting Pseudomonas_Aeruginosa
Train size: 1805
Test size: 452

In [10]:
balance_summary = []

for species, ab_list in species_antibiotics.items():
    
    df_species = species_datasets[species]
    test_idx = global_splits[species]["test_idx"]
    
    df_test = df_species.loc[test_idx]
    
    for ab in ab_list:
        
        y_test = df_test[ab]
        
        n_total = len(y_test)
        n_resistant = (y_test == 1).sum()
        n_susceptible = (y_test == 0).sum()
        
        balance_summary.append({
            "Species": species,
            "Antibiotic": ab,
            "Test_total": n_total,
            "Resistant": n_resistant,
            "Susceptible": n_susceptible,
            "Resistant_ratio": n_resistant / n_total if n_total > 0 else np.nan
        })

balance_df = pd.DataFrame(balance_summary)
balance_df

,Species,Antibiotic,Test_total,Resistant,Susceptible,Resistant_ratio
0,Staphylococcus_Aureus,Oxacillin,712,143,569,0.200843
1,Staphylococcus_Aureus,Clindamycin,712,102,610,0.143258
2,Staphylococcus_Aureus,Fusidic acid,712,45,667,0.063202
3,Escherichia_Coli,Ciprofloxacin,930,268,662,0.288172
4,Escherichia_Coli,Ceftriaxone,930,190,740,0.204301
5,Escherichia_Coli,Piperacillin-Tazobactam,930,64,866,0.068817
6,Escherichia_Coli,Cefepime,930,156,774,0.167742
7,Klebsiella_Pneumoniae,Ciprofloxacin,559,100,459,0.178891
8,Klebsiella_Pneumoniae,Ceftriaxone,559,81,478,0.144902
9,Klebsiella_Pneumoniae,Imipenem,559,6,553,0.010733
10,Klebsiella_Pneumoniae,Meropenem,559,6,553,0.010733
11,Pseudomonas_Aeruginosa,Ciprofloxacin,452,57,395,0.126106
12,Pseudomonas_Aeruginosa,Imipenem,452,57,395,0.126106
13,Pseudomonas_Aeruginosa,Meropenem,452,48,404,0.106195

In [11]:
pattern_balance_results = []

for species in species_datasets.keys():
    
    df_species = species_datasets[species]
    
    train_idx = global_splits[species]["train_idx"]
    test_idx = global_splits[species]["test_idx"]
    
    df_train = df_species.loc[train_idx]
    df_test = df_species.loc[test_idx]
    
    train_pattern_dist = df_train["pattern"].value_counts(normalize=True)
    test_pattern_dist = df_test["pattern"].value_counts(normalize=True)
    
    # Align indices
    combined = pd.DataFrame({
        "Train_ratio": train_pattern_dist,
        "Test_ratio": test_pattern_dist
    }).fillna(0)
    
    combined["Abs_difference"] = abs(combined["Train_ratio"] - combined["Test_ratio"])
    
    print(f"\n=== {species} ===")
    display(combined.sort_values("Abs_difference", ascending=False))

=== Staphylococcus_Aureus ===

         Train_ratio  Test_ratio  Abs_difference
pattern
000         0.683193    0.683989        0.000796
011         0.004923    0.004213        0.000709
100         0.118847    0.119382        0.000535
010         0.080520    0.080056        0.000464
001         0.031294    0.030899        0.000395
101         0.022152    0.022472        0.000320
110         0.053446    0.053371        0.000075
111         0.005626    0.005618        0.000008

=== Escherichia_Coli ===

         Train_ratio  Test_ratio  Abs_difference
pattern
1111        0.021780    0.022581        0.000801
1101        0.106749    0.107527        0.000778
1010        0.014520    0.015054        0.000534
0000        0.646679    0.646237        0.000443
0101        0.031460    0.031183        0.000277
1100        0.025007    0.024731        0.000276
0010        0.020704    0.020430        0.000274
0100        0.007798    0.007527        0.000271
0111        0.006722    0.006452        0.000271
1110        0.004571    0.004301        0.000270
1000        0.114009    0.113978        0.000031

=== Klebsiella_Pneumoniae ===

         Train_ratio  Test_ratio  Abs_difference
pattern
1100        0.100626    0.100179        0.000447
0100        0.033542    0.033989        0.000447
1111        0.010286    0.010733        0.000447
0000        0.787567    0.787120        0.000447
1000        0.067979    0.067979        0.000000

=== Pseudomonas_Aeruginosa ===

         Train_ratio  Test_ratio  Abs_difference
pattern
011         0.058172    0.059735        0.001563
010         0.012188    0.011062        0.001126
110         0.007756    0.008850        0.001093
000         0.803878    0.803097        0.000781
100         0.071468    0.070796        0.000672
111         0.046537    0.046460        0.000077

In [13]:
binary_balance_results = []

for species, ab_list in species_antibiotics.items():
    
    df_species = species_datasets[species]
    
    train_idx = global_splits[species]["train_idx"]
    test_idx = global_splits[species]["test_idx"]
    
    df_train = df_species.loc[train_idx]
    df_test = df_species.loc[test_idx]
    
    for ab in ab_list:
        
        train_res_ratio = (df_train[ab] == 1).mean()
        test_res_ratio = (df_test[ab] == 1).mean()
        
        binary_balance_results.append({
            "Species": species,
            "Antibiotic": ab,
            "Train_resistant_ratio": train_res_ratio,
            "Test_resistant_ratio": test_res_ratio,
            "Absolute_difference": abs(train_res_ratio - test_res_ratio)
        })

binary_balance_df = pd.DataFrame(binary_balance_results)
binary_balance_df.sort_values("Absolute_difference", ascending=False)

,Species,Antibiotic,Train_resistant_ratio,Test_resistant_ratio,Absolute_difference
3,Escherichia_Coli,Ciprofloxacin,0.286636,0.288172,0.001536
13,Pseudomonas_Aeruginosa,Meropenem,0.104709,0.106195,0.001486
12,Pseudomonas_Aeruginosa,Imipenem,0.124654,0.126106,0.001452
1,Staphylococcus_Aureus,Clindamycin,0.144515,0.143258,0.001256
6,Escherichia_Coli,Cefepime,0.166711,0.167742,0.001030
2,Staphylococcus_Aureus,Fusidic acid,0.063994,0.063202,0.000792
0,Staphylococcus_Aureus,Oxacillin,0.200070,0.200843,0.000772
5,Escherichia_Coli,Piperacillin-Tazobactam,0.068298,0.068817,0.000519
8,Klebsiella_Pneumoniae,Ceftriaxone,0.144454,0.144902,0.000447
10,Klebsiella_Pneumoniae,Meropenem,0.010286,0.010733,0.000447
9,Klebsiella_Pneumoniae,Imipenem,0.010286,0.010733,0.000447
11,Pseudomonas_Aeruginosa,Ciprofloxacin,0.125762,0.126106,0.000344
4,Escherichia_Coli,Ceftriaxone,0.204087,0.204301,0.000214
7,Klebsiella_Pneumoniae,Ciprofloxacin,0.178891,0.178891,0.000000

# 5. Benchmark 1 — Single-label (Binary) Classification per Antibiotic

In this experiment, we replicate the paper’s *single-label* benchmark:

- A separate binary classifier is trained **for each species and each antibiotic**.
- The target is binary: `0 = Susceptible (S)`, `1 = Resistant (R)`.
- Hyperparameters are optimized via **Bayesian optimization (BayesSearchCV)** using **Weighted F1 (WF1)** as the objective.
- We reuse the same global train/test split defined previously (stratified by resistance pattern), so that comparisons across tasks remain fair.

For each (species, antibiotic), we will:
1. Build `X_train`, `X_test` from MALDI-TOF spectra.
2. Build `y_train`, `y_test` from the antibiotic-specific AMR labels.
3. Run Bayesian optimization for an MLP classifier.
4. Evaluate WF1 on the held-out test set.

## 5.1 MLP Hyperparameter Optimization Setup

We define an MLP wrapper to expose hidden-layer sizes as tunable parameters.
We then create a BayesSearchCV object with the same search space used in the paper:

- `activation ∈ {identity, logistic, tanh, relu}`
- `solver ∈ {sgd, adam}`
- `alpha ∈ [1e-6, 1e-2]` (log-uniform)
- `learning_rate ∈ {constant, invscaling, adaptive}`
- `layer1, layer2, layer3 ∈ [10, 1000]`

Optimization metric: **Weighted F1 (WF1)**.

In [14]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)


class Identity(nn.Module):
    def forward(self, x):
        return x


class MLPBinary(nn.Module):
    def __init__(self, input_dim, layer1, layer2, layer3, activation):
        super().__init__()

        activations = {
            "relu": nn.ReLU(),
            "tanh": nn.Tanh(),
            "logistic": nn.Sigmoid(),
            "identity": Identity()
        }

        self.net = nn.Sequential(
            nn.Linear(input_dim, layer1),
            activations[activation],
            nn.Linear(layer1, layer2),
            activations[activation],
            nn.Linear(layer2, layer3),
            activations[activation],
            nn.Linear(layer3, 1)
        )

    def forward(self, x):
        return self.net(x)

Using device: cpu

In [19]:
def optimize_mlp_optuna(X_train, y_train, n_trials=200, n_splits=5):

    input_dim = X_train.shape[1]

    def objective(trial):

        # EXACT ranges from paper
        layer1 = trial.suggest_int("layer1", 10, 500)
        layer2 = trial.suggest_int("layer2", 10, 500)
        layer3 = trial.suggest_int("layer3", 10, 500)

        activation = trial.suggest_categorical(
            "activation", ["identity", "logistic", "tanh", "relu"]
        )

        solver = trial.suggest_categorical("solver", ["adam", "sgd"])

        lr = trial.suggest_float("lr", 1e-6, 1e-2, log=True)

        skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=42)

        fold_scores = []

        for fold, (tr_idx, val_idx) in enumerate(skf.split(X_train, y_train)):

            X_tr = torch.tensor(X_train[tr_idx], dtype=torch.float32).to(device)
            y_tr = torch.tensor(y_train[tr_idx], dtype=torch.float32).view(-1,1).to(device)

            X_val = torch.tensor(X_train[val_idx], dtype=torch.float32).to(device)
            y_val = torch.tensor(y_train[val_idx], dtype=torch.float32).view(-1,1).to(device)

            train_loader = DataLoader(
                TensorDataset(X_tr, y_tr),
                batch_size=128,
                shuffle=True
            )

            model = MLPBinary(
                input_dim,
                layer1,
                layer2,
                layer3,
                activation
            ).to(device)

            if solver == "adam":
                optimizer = torch.optim.Adam(model.parameters(), lr=lr)
            else:
                optimizer = torch.optim.SGD(model.parameters(), lr=lr)

            criterion = nn.BCEWithLogitsLoss()

            best_val_score = -np.inf
            best_state = None
            patience = 20
            patience_counter = 0

            for epoch in range(1200):  # EXACT from paper

                model.train()
                for xb, yb in train_loader:
                    optimizer.zero_grad()
                    logits = model(xb)
                    loss = criterion(logits, yb)
                    loss.backward()
                    optimizer.step()

                model.eval()
                with torch.no_grad():
                    logits_val = model(X_val)
                    preds = (torch.sigmoid(logits_val) > 0.5).cpu().numpy()
                    val_score = f1_score(
                        y_val.cpu().numpy(),
                        preds,
                        average="weighted"
                    )

                if val_score > best_val_score:
                    best_val_score = val_score
                    best_state = model.state_dict()
                    patience_counter = 0
                else:
                    patience_counter += 1

                if patience_counter >= patience:
                    break

            model.load_state_dict(best_state)
            fold_scores.append(best_val_score)

        return np.mean(fold_scores)

    study = optuna.create_study(direction="maximize")

    study.optimize(
        objective,
        n_trials=n_trials,
        show_progress_bar=True
    )

    return study

## 5.2 Running Binary Benchmarks per Species and Antibiotic

We now run the full single-label benchmark.

For each species:
- We use the filtered dataset (`species_datasets[species]`) that already:
  - contains only complete-case isolates,
  - excludes rare resistance patterns (≤10 samples),
  - includes the `pattern` column for stratification.

For each antibiotic in that species:
- We extract `y_train`, `y_test` from the antibiotic column.
- We optimize an MLP using only the training set (CV within train).
- We evaluate WF1 on the held-out test set.

We store:
- test WF1
- train/test sample sizes and class balance
- best hyperparameters

In [20]:
MODEL_DIR = os.path.join(PROJECT_ROOT, "saved_models", "benchmark1_mlp_optuna_exact")
os.makedirs(MODEL_DIR, exist_ok=True)

results = []

total_models = sum(len(v) for v in species_antibiotics.values())

with tqdm(total=total_models, desc="Training Exact MLP (Paper)") as pbar:

    for species, ab_list in species_antibiotics.items():

        df_sp = species_datasets[species]
        train_idx = global_splits[species]["train_idx"]
        test_idx = global_splits[species]["test_idx"]

        X_train = X[train_idx]
        X_test  = X[test_idx]

        for ab in ab_list:

            print(f"\n[Exact Paper MLP] {species} | {ab}")

            y_train = df_sp.loc[train_idx, ab].astype(int).values
            y_test  = df_sp.loc[test_idx, ab].astype(int).values

            model_path = os.path.join(
                MODEL_DIR,
                f"{species}_{ab}_best_model.pt"
            )

            study = optimize_mlp_optuna(
                X_train,
                y_train,
                n_trials=200
            )

            best_params = study.best_params

            # Final training on FULL training set
            model = MLPBinary(
                X_train.shape[1],
                best_params["layer1"],
                best_params["layer2"],
                best_params["layer3"],
                best_params["activation"]
            ).to(device)

            if best_params["solver"] == "adam":
                optimizer = torch.optim.Adam(model.parameters(), lr=best_params["lr"])
            else:
                optimizer = torch.optim.SGD(model.parameters(), lr=best_params["lr"])

            criterion = nn.BCEWithLogitsLoss()

            X_tr = torch.tensor(X_train, dtype=torch.float32).to(device)
            y_tr = torch.tensor(y_train, dtype=torch.float32).view(-1,1).to(device)

            best_state = None
            best_score = -np.inf
            patience = 20
            patience_counter = 0

            for epoch in range(1200):

                model.train()
                optimizer.zero_grad()
                logits = model(X_tr)
                loss = criterion(logits, y_tr)
                loss.backward()
                optimizer.step()

                model.eval()
                with torch.no_grad():
                    preds = (torch.sigmoid(model(X_tr)) > 0.5).cpu().numpy()
                    train_score = f1_score(y_train, preds, average="weighted")

                if train_score > best_score:
                    best_score = train_score
                    best_state = model.state_dict()
                    patience_counter = 0
                else:
                    patience_counter += 1

                if patience_counter >= patience:
                    break

            model.load_state_dict(best_state)

            # Save FINAL trained best model
            torch.save({
                "model_state_dict": model.state_dict(),
                "params": best_params,
                "score": best_score
            }, model_path)

            print("  → Best model saved.")

            # Test evaluation
            model.eval()
            with torch.no_grad():
                X_te = torch.tensor(X_test, dtype=torch.float32).to(device)
                preds = (torch.sigmoid(model(X_te)) > 0.5).cpu().numpy()

            wf1 = f1_score(y_test, preds, average="weighted")

            results.append({
                "Species": species,
                "Antibiotic": ab,
                "WF1_test": wf1
            })

            pbar.update(1)

results_df = pd.DataFrame(results).sort_values(
    ["Species", "WF1_test"],
    ascending=[True, False]
)

results_df

Training Exact MLP (Paper):   0%|          | 0/14 [00:00<?, ?it/s][I 2026-02-20 11:10:48,923] A new study created in memory with name: no-name-ad9a9001-38ff-4c2b-8bd2-9e9779e1672f

[Exact Paper MLP] Staphylococcus_Aureus | Oxacillin

Training Exact MLP (Paper):   0%|          | 0/14 [02:33<?, ?it/s]

[I 2026-02-20 11:13:22,551] Trial 0 finished with value: 0.913588406571271 and parameters: {'layer1': 382, 'layer2': 156, 'layer3': 143, 'activation': 'relu', 'solver': 'adam', 'lr': 2.369886935514959e-05}. Best is trial 0 with value: 0.913588406571271.

Training Exact MLP (Paper):   0%|          | 0/14 [03:02<?, ?it/s]

[I 2026-02-20 11:13:51,026] Trial 1 finished with value: 0.711014531661111 and parameters: {'layer1': 247, 'layer2': 225, 'layer3': 354, 'activation': 'logistic', 'solver': 'sgd', 'lr': 0.003330513398713173}. Best is trial 0 with value: 0.913588406571271.

Training Exact MLP (Paper):   0%|          | 0/14 [03:34<?, ?it/s]

[I 2026-02-20 11:14:22,918] Trial 2 finished with value: 0.4535171213068382 and parameters: {'layer1': 355, 'layer2': 212, 'layer3': 217, 'activation': 'logistic', 'solver': 'sgd', 'lr': 4.480208305711858e-05}. Best is trial 0 with value: 0.913588406571271.

Training Exact MLP (Paper):   0%|          | 0/14 [04:06<?, ?it/s]

[I 2026-02-20 11:14:55,303] Trial 3 finished with value: 0.711014531661111 and parameters: {'layer1': 421, 'layer2': 66, 'layer3': 211, 'activation': 'relu', 'solver': 'sgd', 'lr': 0.0048563406290406674}. Best is trial 0 with value: 0.913588406571271.

Training Exact MLP (Paper):   0%|          | 0/14 [04:56<?, ?it/s]

[I 2026-02-20 11:15:44,874] Trial 4 finished with value: 0.749605187646343 and parameters: {'layer1': 152, 'layer2': 429, 'layer3': 142, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.005483168341049707}. Best is trial 0 with value: 0.913588406571271.

Training Exact MLP (Paper):   0%|          | 0/14 [05:28<?, ?it/s]

[I 2026-02-20 11:16:17,034] Trial 5 finished with value: 0.9042585351836572 and parameters: {'layer1': 99, 'layer2': 452, 'layer3': 84, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0023066565514263566}. Best is trial 0 with value: 0.913588406571271.

Training Exact MLP (Paper):   0%|          | 0/14 [05:53<?, ?it/s]

[I 2026-02-20 11:16:42,289] Trial 6 finished with value: 0.711014531661111 and parameters: {'layer1': 138, 'layer2': 75, 'layer3': 97, 'activation': 'identity', 'solver': 'sgd', 'lr': 0.004860917259717303}. Best is trial 0 with value: 0.913588406571271.

Training Exact MLP (Paper):   0%|          | 0/14 [07:05<?, ?it/s]

[I 2026-02-20 11:17:54,547] Trial 7 finished with value: 0.9085450928167284 and parameters: {'layer1': 309, 'layer2': 338, 'layer3': 99, 'activation': 'identity', 'solver': 'adam', 'lr': 7.596928678215215e-05}. Best is trial 0 with value: 0.913588406571271.

Training Exact MLP (Paper):   0%|          | 0/14 [07:30<?, ?it/s]

[I 2026-02-20 11:18:19,678] Trial 8 finished with value: 0.7128884759701852 and parameters: {'layer1': 83, 'layer2': 310, 'layer3': 369, 'activation': 'identity', 'solver': 'sgd', 'lr': 0.00019036257407242799}. Best is trial 0 with value: 0.913588406571271.

Training Exact MLP (Paper):   0%|          | 0/14 [08:25<?, ?it/s]

[I 2026-02-20 11:19:14,489] Trial 9 finished with value: 0.9092681422912674 and parameters: {'layer1': 327, 'layer2': 94, 'layer3': 292, 'activation': 'relu', 'solver': 'adam', 'lr': 0.002279309007170378}. Best is trial 0 with value: 0.913588406571271.

Training Exact MLP (Paper):   0%|          | 0/14 [09:18<?, ?it/s]

[I 2026-02-20 11:20:06,925] Trial 10 finished with value: 0.7180697215665524 and parameters: {'layer1': 496, 'layer2': 152, 'layer3': 412, 'activation': 'relu', 'solver': 'adam', 'lr': 1.2207389735966022e-06}. Best is trial 0 with value: 0.913588406571271.

Training Exact MLP (Paper):   0%|          | 0/14 [09:58<?, ?it/s]

[I 2026-02-20 11:20:46,897] Trial 11 finished with value: 0.7115590046756355 and parameters: {'layer1': 263, 'layer2': 12, 'layer3': 289, 'activation': 'relu', 'solver': 'adam', 'lr': 9.091428689796131e-06}. Best is trial 0 with value: 0.913588406571271.

Training Exact MLP (Paper):   0%|          | 0/14 [11:10<?, ?it/s]

[I 2026-02-20 11:21:59,571] Trial 12 finished with value: 0.9083369275089795 and parameters: {'layer1': 394, 'layer2': 142, 'layer3': 22, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0004730482877582471}. Best is trial 0 with value: 0.913588406571271.

Training Exact MLP (Paper):   0%|          | 0/14 [14:23<?, ?it/s]

[I 2026-02-20 11:25:12,606] Trial 13 finished with value: 0.91427818746553 and parameters: {'layer1': 470, 'layer2': 150, 'layer3': 291, 'activation': 'relu', 'solver': 'adam', 'lr': 1.2080588571475867e-05}. Best is trial 13 with value: 0.91427818746553.

Training Exact MLP (Paper):   0%|          | 0/14 [17:49<?, ?it/s]

[I 2026-02-20 11:28:37,984] Trial 14 finished with value: 0.9104250387902926 and parameters: {'layer1': 499, 'layer2': 182, 'layer3': 489, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.0270497127999238e-05}. Best is trial 13 with value: 0.91427818746553.

Training Exact MLP (Paper):   0%|          | 0/14 [21:27<?, ?it/s]

[I 2026-02-20 11:32:15,922] Trial 15 finished with value: 0.9137645953947044 and parameters: {'layer1': 434, 'layer2': 285, 'layer3': 184, 'activation': 'relu', 'solver': 'adam', 'lr': 1.0189211582047601e-05}. Best is trial 13 with value: 0.91427818746553.

Training Exact MLP (Paper):   0%|          | 0/14 [22:15<?, ?it/s]

[I 2026-02-20 11:33:04,771] Trial 16 finished with value: 0.7170113716344197 and parameters: {'layer1': 432, 'layer2': 292, 'layer3': 229, 'activation': 'relu', 'solver': 'adam', 'lr': 1.4353829422406933e-06}. Best is trial 13 with value: 0.91427818746553.

Training Exact MLP (Paper):   0%|          | 0/14 [23:05<?, ?it/s]

[I 2026-02-20 11:33:54,831] Trial 17 finished with value: 0.7121481270472199 and parameters: {'layer1': 463, 'layer2': 373, 'layer3': 175, 'activation': 'relu', 'solver': 'adam', 'lr': 4.344446700672532e-06}. Best is trial 13 with value: 0.91427818746553.

Training Exact MLP (Paper):   0%|          | 0/14 [23:37<?, ?it/s]

[I 2026-02-20 11:34:26,225] Trial 18 finished with value: 0.711014531661111 and parameters: {'layer1': 227, 'layer2': 267, 'layer3': 303, 'activation': 'tanh', 'solver': 'adam', 'lr': 3.861067254009586e-06}. Best is trial 13 with value: 0.91427818746553.

Training Exact MLP (Paper):   0%|          | 0/14 [24:34<?, ?it/s]

[I 2026-02-20 11:35:23,447] Trial 19 finished with value: 0.711014531661111 and parameters: {'layer1': 462, 'layer2': 388, 'layer3': 467, 'activation': 'logistic', 'solver': 'adam', 'lr': 2.0265478398122674e-05}. Best is trial 13 with value: 0.91427818746553.

Training Exact MLP (Paper):   0%|          | 0/14 [25:18<?, ?it/s]

[I 2026-02-20 11:36:07,347] Trial 20 finished with value: 0.9051238839781754 and parameters: {'layer1': 11, 'layer2': 238, 'layer3': 348, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0002609470259037568}. Best is trial 13 with value: 0.91427818746553.

Training Exact MLP (Paper):   0%|          | 0/14 [27:41<?, ?it/s]

[I 2026-02-20 11:38:30,636] Trial 21 finished with value: 0.9129646293940988 and parameters: {'layer1': 382, 'layer2': 137, 'layer3': 149, 'activation': 'relu', 'solver': 'adam', 'lr': 2.2048771624963557e-05}. Best is trial 13 with value: 0.91427818746553.

Training Exact MLP (Paper):   0%|          | 0/14 [29:39<?, ?it/s]

[I 2026-02-20 11:40:28,511] Trial 22 finished with value: 0.914732928769391 and parameters: {'layer1': 425, 'layer2': 179, 'layer3': 250, 'activation': 'relu', 'solver': 'adam', 'lr': 3.0370626158439496e-05}. Best is trial 22 with value: 0.914732928769391.

Training Exact MLP (Paper):   0%|          | 0/14 [30:25<?, ?it/s]

[I 2026-02-20 11:41:14,104] Trial 23 finished with value: 0.7159599502105493 and parameters: {'layer1': 438, 'layer2': 210, 'layer3': 259, 'activation': 'relu', 'solver': 'adam', 'lr': 4.398879612975495e-06}. Best is trial 22 with value: 0.914732928769391.

Training Exact MLP (Paper):   0%|          | 0/14 [31:43<?, ?it/s]

[I 2026-02-20 11:42:32,683] Trial 24 finished with value: 0.9131527471368377 and parameters: {'layer1': 305, 'layer2': 499, 'layer3': 263, 'activation': 'relu', 'solver': 'adam', 'lr': 7.861155724915433e-05}. Best is trial 22 with value: 0.914732928769391.

Training Exact MLP (Paper):   0%|          | 0/14 [34:11<?, ?it/s]

[I 2026-02-20 11:45:00,702] Trial 25 finished with value: 0.9134924945378666 and parameters: {'layer1': 350, 'layer2': 264, 'layer3': 191, 'activation': 'relu', 'solver': 'adam', 'lr': 1.0825511382145977e-05}. Best is trial 22 with value: 0.914732928769391.

Training Exact MLP (Paper):   0%|          | 0/14 [34:52<?, ?it/s]

[I 2026-02-20 11:45:41,102] Trial 26 finished with value: 0.5829177154442224 and parameters: {'layer1': 463, 'layer2': 101, 'layer3': 243, 'activation': 'relu', 'solver': 'sgd', 'lr': 4.0511432684732924e-05}. Best is trial 22 with value: 0.914732928769391.

Training Exact MLP (Paper):   0%|          | 0/14 [35:11<?, ?it/s]

[I 2026-02-20 11:46:00,487] Trial 27 finished with value: 0.7233047543761013 and parameters: {'layer1': 399, 'layer2': 14, 'layer3': 325, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.7000289148674766e-06}. Best is trial 22 with value: 0.914732928769391.

Training Exact MLP (Paper):   0%|          | 0/14 [35:45<?, ?it/s]

[I 2026-02-20 11:46:34,819] Trial 28 finished with value: 0.9104700762991775 and parameters: {'layer1': 498, 'layer2': 184, 'layer3': 435, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.000726518302492458}. Best is trial 22 with value: 0.914732928769391.

Training Exact MLP (Paper):   0%|          | 0/14 [36:36<?, ?it/s]

[I 2026-02-20 11:47:25,047] Trial 29 finished with value: 0.9141850689371166 and parameters: {'layer1': 374, 'layer2': 180, 'layer3': 160, 'activation': 'relu', 'solver': 'adam', 'lr': 4.148565825958537e-05}. Best is trial 22 with value: 0.914732928769391.

Training Exact MLP (Paper):   0%|          | 0/14 [37:09<?, ?it/s]

[I 2026-02-20 11:47:58,258] Trial 30 finished with value: 0.9106449911682258 and parameters: {'layer1': 361, 'layer2': 119, 'layer3': 140, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00014038268881653076}. Best is trial 22 with value: 0.914732928769391.

Training Exact MLP (Paper):   0%|          | 0/14 [38:06<?, ?it/s]

[I 2026-02-20 11:48:55,556] Trial 31 finished with value: 0.9132308443791171 and parameters: {'layer1': 417, 'layer2': 178, 'layer3': 171, 'activation': 'relu', 'solver': 'adam', 'lr': 4.389551720573925e-05}. Best is trial 22 with value: 0.914732928769391.

Training Exact MLP (Paper):   0%|          | 0/14 [39:37<?, ?it/s]

[I 2026-02-20 11:50:26,251] Trial 32 finished with value: 0.9127990333705046 and parameters: {'layer1': 454, 'layer2': 217, 'layer3': 65, 'activation': 'relu', 'solver': 'adam', 'lr': 1.6565699172853356e-05}. Best is trial 22 with value: 0.914732928769391.

Training Exact MLP (Paper):   0%|          | 0/14 [40:32<?, ?it/s]

[I 2026-02-20 11:51:21,451] Trial 33 finished with value: 0.9112725534503007 and parameters: {'layer1': 404, 'layer2': 292, 'layer3': 202, 'activation': 'relu', 'solver': 'adam', 'lr': 3.7852495242409774e-05}. Best is trial 22 with value: 0.914732928769391.

Training Exact MLP (Paper):   0%|          | 0/14 [40:47<?, ?it/s]

[I 2026-02-20 11:51:36,167] Trial 34 finished with value: 0.3242071833658614 and parameters: {'layer1': 363, 'layer2': 248, 'layer3': 275, 'activation': 'logistic', 'solver': 'sgd', 'lr': 7.5066423517651395e-06}. Best is trial 22 with value: 0.914732928769391.

Training Exact MLP (Paper):   0%|          | 0/14 [41:41<?, ?it/s]

[I 2026-02-20 11:52:30,426] Trial 35 finished with value: 0.9152281845585296 and parameters: {'layer1': 259, 'layer2': 198, 'layer3': 227, 'activation': 'relu', 'solver': 'adam', 'lr': 2.7072662533375937e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [41:53<?, ?it/s]

[I 2026-02-20 11:52:42,659] Trial 36 finished with value: 0.5817045937201344 and parameters: {'layer1': 201, 'layer2': 190, 'layer3': 222, 'activation': 'relu', 'solver': 'sgd', 'lr': 2.9474090463302847e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [42:30<?, ?it/s]

[I 2026-02-20 11:53:19,407] Trial 37 finished with value: 0.913519303962282 and parameters: {'layer1': 279, 'layer2': 55, 'layer3': 316, 'activation': 'relu', 'solver': 'adam', 'lr': 7.049760582504845e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [43:19<?, ?it/s]

[I 2026-02-20 11:54:08,371] Trial 38 finished with value: 0.9109193218203183 and parameters: {'layer1': 207, 'layer2': 166, 'layer3': 376, 'activation': 'identity', 'solver': 'adam', 'lr': 1.589814524371952e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [43:34<?, ?it/s]

[I 2026-02-20 11:54:23,053] Trial 39 finished with value: 0.711014531661111 and parameters: {'layer1': 329, 'layer2': 203, 'layer3': 237, 'activation': 'logistic', 'solver': 'sgd', 'lr': 0.0001138844643896036}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [44:06<?, ?it/s]

[I 2026-02-20 11:54:55,226] Trial 40 finished with value: 0.9111018274498015 and parameters: {'layer1': 287, 'layer2': 121, 'layer3': 118, 'activation': 'tanh', 'solver': 'adam', 'lr': 5.342679800323444e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [44:29<?, ?it/s]

[I 2026-02-20 11:55:18,589] Trial 41 finished with value: 0.7168038855340118 and parameters: {'layer1': 430, 'layer2': 225, 'layer3': 180, 'activation': 'relu', 'solver': 'adam', 'lr': 6.595363459013113e-06}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [46:02<?, ?it/s]

[I 2026-02-20 11:56:51,683] Trial 42 finished with value: 0.912953182445355 and parameters: {'layer1': 477, 'layer2': 333, 'layer3': 204, 'activation': 'relu', 'solver': 'adam', 'lr': 1.4606064216035393e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [47:04<?, ?it/s]

[I 2026-02-20 11:57:52,870] Trial 43 finished with value: 0.9140679964653333 and parameters: {'layer1': 374, 'layer2': 163, 'layer3': 158, 'activation': 'relu', 'solver': 'adam', 'lr': 3.63052563976378e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [47:42<?, ?it/s]

[I 2026-02-20 11:58:31,714] Trial 44 finished with value: 0.9127036963223876 and parameters: {'layer1': 173, 'layer2': 139, 'layer3': 145, 'activation': 'identity', 'solver': 'adam', 'lr': 2.964729234228982e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [48:11<?, ?it/s]

[I 2026-02-20 11:59:00,028] Trial 45 finished with value: 0.9075043573991939 and parameters: {'layer1': 336, 'layer2': 158, 'layer3': 118, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00022821525530641344}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [48:51<?, ?it/s]

[I 2026-02-20 11:59:40,661] Trial 46 finished with value: 0.9128888371707291 and parameters: {'layer1': 372, 'layer2': 62, 'layer3': 44, 'activation': 'relu', 'solver': 'adam', 'lr': 7.162779896418498e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [49:12<?, ?it/s]

[I 2026-02-20 12:00:01,726] Trial 47 finished with value: 0.7145404947931135 and parameters: {'layer1': 249, 'layer2': 95, 'layer3': 277, 'activation': 'relu', 'solver': 'sgd', 'lr': 2.6876008014811997e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [49:31<?, ?it/s]

[I 2026-02-20 12:00:20,242] Trial 48 finished with value: 0.911125943331213 and parameters: {'layer1': 101, 'layer2': 118, 'layer3': 332, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0001349006675764553}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [50:19<?, ?it/s]

[I 2026-02-20 12:01:07,893] Trial 49 finished with value: 0.9118290996039635 and parameters: {'layer1': 410, 'layer2': 158, 'layer3': 216, 'activation': 'relu', 'solver': 'adam', 'lr': 5.0636860471697334e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [50:47<?, ?it/s]

[I 2026-02-20 12:01:36,501] Trial 50 finished with value: 0.9118451335066171 and parameters: {'layer1': 387, 'layer2': 236, 'layer3': 166, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00041977654344528255}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [51:10<?, ?it/s]

[I 2026-02-20 12:01:59,306] Trial 51 finished with value: 0.7207659857122188 and parameters: {'layer1': 443, 'layer2': 203, 'layer3': 249, 'activation': 'relu', 'solver': 'adam', 'lr': 5.648947989622303e-06}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [52:52<?, ?it/s]

[I 2026-02-20 12:03:41,650] Trial 52 finished with value: 0.9148325587124821 and parameters: {'layer1': 472, 'layer2': 267, 'layer3': 130, 'activation': 'relu', 'solver': 'adam', 'lr': 1.0984083161582249e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [53:19<?, ?it/s]

[I 2026-02-20 12:04:08,449] Trial 53 finished with value: 0.7201262411476929 and parameters: {'layer1': 487, 'layer2': 172, 'layer3': 77, 'activation': 'relu', 'solver': 'adam', 'lr': 2.3589915527448355e-06}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [54:52<?, ?it/s]

[I 2026-02-20 12:05:41,346] Trial 54 finished with value: 0.9135367628429323 and parameters: {'layer1': 415, 'layer2': 195, 'layer3': 117, 'activation': 'relu', 'solver': 'adam', 'lr': 1.641373736451866e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [56:21<?, ?it/s]

[I 2026-02-20 12:07:09,939] Trial 55 finished with value: 0.9106313632132881 and parameters: {'layer1': 478, 'layer2': 226, 'layer3': 98, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.3453992285373979e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [57:40<?, ?it/s]

[I 2026-02-20 12:08:28,849] Trial 56 finished with value: 0.9117139534191502 and parameters: {'layer1': 453, 'layer2': 142, 'layer3': 158, 'activation': 'relu', 'solver': 'adam', 'lr': 2.0853475077238727e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [59:18<?, ?it/s]

[I 2026-02-20 12:10:07,013] Trial 57 finished with value: 0.8739112630469006 and parameters: {'layer1': 386, 'layer2': 250, 'layer3': 132, 'activation': 'relu', 'solver': 'adam', 'lr': 1.0076801393426537e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:00:18<?, ?it/s]

[I 2026-02-20 12:11:07,466] Trial 58 finished with value: 0.9150941759380512 and parameters: {'layer1': 468, 'layer2': 83, 'layer3': 301, 'activation': 'relu', 'solver': 'adam', 'lr': 3.1290604913296266e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:00:45<?, ?it/s]

[I 2026-02-20 12:11:33,898] Trial 59 finished with value: 0.4583373081418637 and parameters: {'layer1': 478, 'layer2': 28, 'layer3': 299, 'activation': 'relu', 'solver': 'sgd', 'lr': 2.3813008244295804e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:01:56<?, ?it/s]

[I 2026-02-20 12:12:45,632] Trial 60 finished with value: 0.9122655720437354 and parameters: {'layer1': 447, 'layer2': 311, 'layer3': 383, 'activation': 'logistic', 'solver': 'adam', 'lr': 6.073743581413898e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:03:01<?, ?it/s]

[I 2026-02-20 12:13:50,283] Trial 61 finished with value: 0.9138999842000739 and parameters: {'layer1': 468, 'layer2': 88, 'layer3': 278, 'activation': 'relu', 'solver': 'adam', 'lr': 2.7246011703264175e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:03:40<?, ?it/s]

[I 2026-02-20 12:14:29,820] Trial 62 finished with value: 0.9113725674089196 and parameters: {'layer1': 430, 'layer2': 276, 'layer3': 344, 'activation': 'relu', 'solver': 'adam', 'lr': 9.262871072697565e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:04:33<?, ?it/s]

[I 2026-02-20 12:15:22,633] Trial 63 finished with value: 0.9124537210609779 and parameters: {'layer1': 309, 'layer2': 47, 'layer3': 312, 'activation': 'relu', 'solver': 'adam', 'lr': 3.3330862945049756e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:04:53<?, ?it/s]

[I 2026-02-20 12:15:42,018] Trial 64 finished with value: 0.7158742466357191 and parameters: {'layer1': 342, 'layer2': 125, 'layer3': 192, 'activation': 'relu', 'solver': 'adam', 'lr': 8.344089840667622e-06}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:05:04<?, ?it/s]

[I 2026-02-20 12:15:53,636] Trial 65 finished with value: 0.7131086805304943 and parameters: {'layer1': 25, 'layer2': 179, 'layer3': 258, 'activation': 'relu', 'solver': 'adam', 'lr': 1.2855893330272414e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:06:06<?, ?it/s]

[I 2026-02-20 12:16:55,607] Trial 66 finished with value: 0.9133340180900149 and parameters: {'layer1': 500, 'layer2': 76, 'layer3': 229, 'activation': 'relu', 'solver': 'adam', 'lr': 4.010714270315054e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:07:02<?, ?it/s]

[I 2026-02-20 12:17:51,780] Trial 67 finished with value: 0.9121270903905077 and parameters: {'layer1': 421, 'layer2': 154, 'layer3': 285, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.0965942933915123e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:08:43<?, ?it/s]

[I 2026-02-20 12:19:31,892] Trial 68 finished with value: 0.8686815065732751 and parameters: {'layer1': 403, 'layer2': 194, 'layer3': 197, 'activation': 'identity', 'solver': 'adam', 'lr': 5.824034143267914e-06}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:09:22<?, ?it/s]

[I 2026-02-20 12:20:11,777] Trial 69 finished with value: 0.9062378104797789 and parameters: {'layer1': 376, 'layer2': 214, 'layer3': 214, 'activation': 'relu', 'solver': 'adam', 'lr': 0.009154624977391305}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:09:38<?, ?it/s]

[I 2026-02-20 12:20:27,838] Trial 70 finished with value: 0.7121171213020192 and parameters: {'layer1': 228, 'layer2': 107, 'layer3': 129, 'activation': 'relu', 'solver': 'adam', 'lr': 2.8483364287854493e-06}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:10:40<?, ?it/s]

[I 2026-02-20 12:21:29,829] Trial 71 finished with value: 0.9128775808707941 and parameters: {'layer1': 472, 'layer2': 84, 'layer3': 292, 'activation': 'relu', 'solver': 'adam', 'lr': 3.230276722887487e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:11:30<?, ?it/s]

[I 2026-02-20 12:22:19,287] Trial 72 finished with value: 0.914066907793852 and parameters: {'layer1': 458, 'layer2': 37, 'layer3': 268, 'activation': 'relu', 'solver': 'adam', 'lr': 5.8459462452142285e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:12:24<?, ?it/s]

[I 2026-02-20 12:23:13,017] Trial 73 finished with value: 0.9118244096562973 and parameters: {'layer1': 460, 'layer2': 31, 'layer3': 263, 'activation': 'relu', 'solver': 'adam', 'lr': 5.569446126081057e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:13:02<?, ?it/s]

[I 2026-02-20 12:23:51,282] Trial 74 finished with value: 0.91109082016771 and parameters: {'layer1': 487, 'layer2': 44, 'layer3': 239, 'activation': 'relu', 'solver': 'adam', 'lr': 9.410949830188661e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:14:00<?, ?it/s]

[I 2026-02-20 12:24:49,288] Trial 75 finished with value: 0.9138543871636445 and parameters: {'layer1': 443, 'layer2': 260, 'layer3': 314, 'activation': 'relu', 'solver': 'adam', 'lr': 4.153049562777603e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:14:30<?, ?it/s]

[I 2026-02-20 12:25:19,478] Trial 76 finished with value: 0.46022379800494706 and parameters: {'layer1': 421, 'layer2': 135, 'layer3': 365, 'activation': 'relu', 'solver': 'sgd', 'lr': 1.8495417695325717e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:14:53<?, ?it/s]

[I 2026-02-20 12:25:42,250] Trial 77 finished with value: 0.711014531661111 and parameters: {'layer1': 434, 'layer2': 168, 'layer3': 159, 'activation': 'logistic', 'solver': 'adam', 'lr': 6.493647534875143e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:15:28<?, ?it/s]

[I 2026-02-20 12:26:17,453] Trial 78 finished with value: 0.9090687713219125 and parameters: {'layer1': 394, 'layer2': 239, 'layer3': 336, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00015628847007588586}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:16:56<?, ?it/s]

[I 2026-02-20 12:27:45,199] Trial 79 finished with value: 0.8710641139518704 and parameters: {'layer1': 455, 'layer2': 106, 'layer3': 302, 'activation': 'relu', 'solver': 'adam', 'lr': 1.0512804476088219e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:17:55<?, ?it/s]

[I 2026-02-20 12:28:44,638] Trial 80 finished with value: 0.9131074637496625 and parameters: {'layer1': 365, 'layer2': 146, 'layer3': 265, 'activation': 'relu', 'solver': 'adam', 'lr': 2.4125840001415505e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:19:08<?, ?it/s]

[I 2026-02-20 12:29:57,061] Trial 81 finished with value: 0.9139130173632172 and parameters: {'layer1': 475, 'layer2': 70, 'layer3': 275, 'activation': 'relu', 'solver': 'adam', 'lr': 2.89340414318903e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:20:10<?, ?it/s]

[I 2026-02-20 12:30:58,915] Trial 82 finished with value: 0.9147090609696654 and parameters: {'layer1': 486, 'layer2': 61, 'layer3': 232, 'activation': 'relu', 'solver': 'adam', 'lr': 3.5893670931865766e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:21:06<?, ?it/s]

[I 2026-02-20 12:31:55,762] Trial 83 finished with value: 0.9144327079947081 and parameters: {'layer1': 491, 'layer2': 30, 'layer3': 229, 'activation': 'relu', 'solver': 'adam', 'lr': 4.6016012932120165e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:22:00<?, ?it/s]

[I 2026-02-20 12:32:49,687] Trial 84 finished with value: 0.910927481886468 and parameters: {'layer1': 500, 'layer2': 54, 'layer3': 228, 'activation': 'relu', 'solver': 'adam', 'lr': 4.853452391426619e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:22:38<?, ?it/s]

[I 2026-02-20 12:33:27,113] Trial 85 finished with value: 0.9118538098731624 and parameters: {'layer1': 286, 'layer2': 205, 'layer3': 184, 'activation': 'identity', 'solver': 'adam', 'lr': 3.796405740158041e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:23:58<?, ?it/s]

[I 2026-02-20 12:34:47,227] Trial 86 finished with value: 0.9109460072150494 and parameters: {'layer1': 319, 'layer2': 27, 'layer3': 242, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.2063574987084436e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:25:45<?, ?it/s]

[I 2026-02-20 12:36:33,890] Trial 87 finished with value: 0.9143789798479439 and parameters: {'layer1': 487, 'layer2': 10, 'layer3': 211, 'activation': 'relu', 'solver': 'adam', 'lr': 1.8502057791795512e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:26:16<?, ?it/s]

[I 2026-02-20 12:37:05,357] Trial 88 finished with value: 0.5869072881988735 and parameters: {'layer1': 488, 'layer2': 21, 'layer3': 209, 'activation': 'relu', 'solver': 'sgd', 'lr': 1.6978136202137218e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:26:38<?, ?it/s]

[I 2026-02-20 12:37:26,927] Trial 89 finished with value: 0.7137428345962183 and parameters: {'layer1': 487, 'layer2': 12, 'layer3': 250, 'activation': 'relu', 'solver': 'adam', 'lr': 6.873216804828977e-06}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:27:18<?, ?it/s]

[I 2026-02-20 12:38:07,006] Trial 90 finished with value: 0.9124555973747409 and parameters: {'layer1': 464, 'layer2': 65, 'layer3': 221, 'activation': 'relu', 'solver': 'adam', 'lr': 8.109408166529438e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:28:50<?, ?it/s]

[I 2026-02-20 12:39:39,055] Trial 91 finished with value: 0.913917864669427 and parameters: {'layer1': 446, 'layer2': 46, 'layer3': 158, 'activation': 'relu', 'solver': 'adam', 'lr': 2.05114479474361e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:29:43<?, ?it/s]

[I 2026-02-20 12:40:32,404] Trial 92 finished with value: 0.9120880604912462 and parameters: {'layer1': 485, 'layer2': 304, 'layer3': 177, 'activation': 'relu', 'solver': 'adam', 'lr': 3.2011996102116287e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:30:27<?, ?it/s]

[I 2026-02-20 12:41:16,032] Trial 93 finished with value: 0.9140419529183939 and parameters: {'layer1': 270, 'layer2': 161, 'layer3': 109, 'activation': 'relu', 'solver': 'adam', 'lr': 4.475068199005326e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:30:55<?, ?it/s]

[I 2026-02-20 12:41:44,651] Trial 94 finished with value: 0.9043750800852205 and parameters: {'layer1': 465, 'layer2': 186, 'layer3': 236, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0015856510009979283}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:31:10<?, ?it/s]

[I 2026-02-20 12:41:59,113] Trial 95 finished with value: 0.711014531661111 and parameters: {'layer1': 149, 'layer2': 10, 'layer3': 201, 'activation': 'logistic', 'solver': 'adam', 'lr': 1.3969391274257871e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:32:29<?, ?it/s]

[I 2026-02-20 12:43:18,259] Trial 96 finished with value: 0.9141818758356699 and parameters: {'layer1': 474, 'layer2': 84, 'layer3': 85, 'activation': 'relu', 'solver': 'adam', 'lr': 2.3825863904645374e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:33:40<?, ?it/s]

[I 2026-02-20 12:44:28,861] Trial 97 finished with value: 0.9139883084825697 and parameters: {'layer1': 492, 'layer2': 81, 'layer3': 47, 'activation': 'relu', 'solver': 'adam', 'lr': 2.527788587824196e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:35:00<?, ?it/s]

[I 2026-02-20 12:45:49,441] Trial 98 finished with value: 0.9132987397048392 and parameters: {'layer1': 476, 'layer2': 92, 'layer3': 255, 'activation': 'relu', 'solver': 'adam', 'lr': 1.8372107808085734e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:35:22<?, ?it/s]

[I 2026-02-20 12:46:11,599] Trial 99 finished with value: 0.7115895816411071 and parameters: {'layer1': 452, 'layer2': 56, 'layer3': 73, 'activation': 'relu', 'solver': 'adam', 'lr': 8.554839680334054e-06}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:35:44<?, ?it/s]

[I 2026-02-20 12:46:33,837] Trial 100 finished with value: 0.7172960607935691 and parameters: {'layer1': 437, 'layer2': 132, 'layer3': 57, 'activation': 'relu', 'solver': 'adam', 'lr': 5.005220560161038e-06}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:36:53<?, ?it/s]

[I 2026-02-20 12:47:42,660] Trial 101 finished with value: 0.9147943942685506 and parameters: {'layer1': 351, 'layer2': 38, 'layer3': 86, 'activation': 'relu', 'solver': 'adam', 'lr': 3.616895339440813e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:38:01<?, ?it/s]

[I 2026-02-20 12:48:50,406] Trial 102 finished with value: 0.9122660000397941 and parameters: {'layer1': 424, 'layer2': 33, 'layer3': 35, 'activation': 'relu', 'solver': 'adam', 'lr': 3.498154652414253e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:39:21<?, ?it/s]

[I 2026-02-20 12:50:09,929] Trial 103 finished with value: 0.9127931938592748 and parameters: {'layer1': 499, 'layer2': 111, 'layer3': 104, 'activation': 'relu', 'solver': 'adam', 'lr': 2.4278248484691784e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:40:17<?, ?it/s]

[I 2026-02-20 12:51:06,367] Trial 104 finished with value: 0.7994245435551445 and parameters: {'layer1': 481, 'layer2': 65, 'layer3': 15, 'activation': 'relu', 'solver': 'adam', 'lr': 1.535738795919787e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:41:05<?, ?it/s]

[I 2026-02-20 12:51:54,613] Trial 105 finished with value: 0.9107523973153789 and parameters: {'layer1': 469, 'layer2': 19, 'layer3': 83, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00011492230651317986}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:41:21<?, ?it/s]

[I 2026-02-20 12:52:10,376] Trial 106 finished with value: 0.7139316328512273 and parameters: {'layer1': 411, 'layer2': 39, 'layer3': 90, 'activation': 'tanh', 'solver': 'sgd', 'lr': 4.673139006363104e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:42:32<?, ?it/s]

[I 2026-02-20 12:53:21,354] Trial 107 finished with value: 0.9102018980484698 and parameters: {'layer1': 349, 'layer2': 428, 'layer3': 139, 'activation': 'identity', 'solver': 'adam', 'lr': 1.128346911109834e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:43:10<?, ?it/s]

[I 2026-02-20 12:53:59,660] Trial 108 finished with value: 0.9119603993229211 and parameters: {'layer1': 447, 'layer2': 274, 'layer3': 128, 'activation': 'relu', 'solver': 'adam', 'lr': 7.757210849550115e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:44:01<?, ?it/s]

[I 2026-02-20 12:54:50,649] Trial 109 finished with value: 0.9114615415972841 and parameters: {'layer1': 119, 'layer2': 76, 'layer3': 223, 'activation': 'relu', 'solver': 'adam', 'lr': 2.7908859368678155e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:45:12<?, ?it/s]

[I 2026-02-20 12:56:01,190] Trial 110 finished with value: 0.9128728951087519 and parameters: {'layer1': 196, 'layer2': 53, 'layer3': 210, 'activation': 'relu', 'solver': 'adam', 'lr': 2.116124356591904e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:46:05<?, ?it/s]

[I 2026-02-20 12:56:54,372] Trial 111 finished with value: 0.9140382566137777 and parameters: {'layer1': 472, 'layer2': 222, 'layer3': 190, 'activation': 'relu', 'solver': 'adam', 'lr': 3.483761677970969e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:46:50<?, ?it/s]

[I 2026-02-20 12:57:39,251] Trial 112 finished with value: 0.9118390501819202 and parameters: {'layer1': 381, 'layer2': 94, 'layer3': 170, 'activation': 'relu', 'solver': 'adam', 'lr': 6.0038623554664124e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:47:40<?, ?it/s]

[I 2026-02-20 12:58:29,303] Trial 113 finished with value: 0.9138041239176683 and parameters: {'layer1': 400, 'layer2': 175, 'layer3': 248, 'activation': 'relu', 'solver': 'adam', 'lr': 3.7667681700039026e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:48:23<?, ?it/s]

[I 2026-02-20 12:59:12,408] Trial 114 finished with value: 0.9118208822421382 and parameters: {'layer1': 355, 'layer2': 197, 'layer3': 286, 'activation': 'relu', 'solver': 'adam', 'lr': 4.912654892568123e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:49:48<?, ?it/s]

[I 2026-02-20 13:00:37,478] Trial 115 finished with value: 0.9121399786077588 and parameters: {'layer1': 459, 'layer2': 148, 'layer3': 88, 'activation': 'relu', 'solver': 'adam', 'lr': 1.8578408508225803e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:50:47<?, ?it/s]

[I 2026-02-20 13:01:36,533] Trial 116 finished with value: 0.9133099724005198 and parameters: {'layer1': 297, 'layer2': 127, 'layer3': 118, 'activation': 'relu', 'solver': 'adam', 'lr': 2.8880616459544898e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:51:08<?, ?it/s]

[I 2026-02-20 13:01:57,577] Trial 117 finished with value: 0.711014531661111 and parameters: {'layer1': 319, 'layer2': 237, 'layer3': 142, 'activation': 'logistic', 'solver': 'adam', 'lr': 1.4527679465377664e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:52:12<?, ?it/s]

[I 2026-02-20 13:03:01,052] Trial 118 finished with value: 0.9143446816137694 and parameters: {'layer1': 236, 'layer2': 167, 'layer3': 323, 'activation': 'relu', 'solver': 'adam', 'lr': 2.3518910376790782e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:52:28<?, ?it/s]

[I 2026-02-20 13:03:16,955] Trial 119 finished with value: 0.7162285294918661 and parameters: {'layer1': 243, 'layer2': 21, 'layer3': 329, 'activation': 'relu', 'solver': 'adam', 'lr': 9.687190732002214e-06}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:53:21<?, ?it/s]

[I 2026-02-20 13:04:09,938] Trial 120 finished with value: 0.9127247193015682 and parameters: {'layer1': 216, 'layer2': 185, 'layer3': 318, 'activation': 'relu', 'solver': 'adam', 'lr': 2.5472974693005014e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:54:03<?, ?it/s]

[I 2026-02-20 13:04:52,356] Trial 121 finished with value: 0.9133457881855028 and parameters: {'layer1': 237, 'layer2': 168, 'layer3': 151, 'activation': 'relu', 'solver': 'adam', 'lr': 4.337371759557857e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:55:05<?, ?it/s]

[I 2026-02-20 13:05:54,365] Trial 122 finished with value: 0.9121237058545487 and parameters: {'layer1': 367, 'layer2': 209, 'layer3': 295, 'activation': 'relu', 'solver': 'adam', 'lr': 2.2668163298846752e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:55:54<?, ?it/s]

[I 2026-02-20 13:06:43,126] Trial 123 finished with value: 0.9139979901208181 and parameters: {'layer1': 267, 'layer2': 159, 'layer3': 234, 'activation': 'relu', 'solver': 'adam', 'lr': 3.29934314799734e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:56:43<?, ?it/s]

[I 2026-02-20 13:07:32,312] Trial 124 finished with value: 0.8320551887756842 and parameters: {'layer1': 253, 'layer2': 39, 'layer3': 357, 'activation': 'relu', 'solver': 'adam', 'lr': 1.712831648829614e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:57:14<?, ?it/s]

[I 2026-02-20 13:08:03,305] Trial 125 finished with value: 0.5823606181344911 and parameters: {'layer1': 478, 'layer2': 117, 'layer3': 64, 'activation': 'relu', 'solver': 'sgd', 'lr': 5.4897451106677566e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:58:47<?, ?it/s]

[I 2026-02-20 13:09:36,623] Trial 126 finished with value: 0.9145799419625721 and parameters: {'layer1': 390, 'layer2': 146, 'layer3': 270, 'activation': 'relu', 'solver': 'adam', 'lr': 1.2705412823979143e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [1:59:11<?, ?it/s]

[I 2026-02-20 13:10:00,454] Trial 127 finished with value: 0.711014531661111 and parameters: {'layer1': 491, 'layer2': 177, 'layer3': 273, 'activation': 'relu', 'solver': 'adam', 'lr': 7.602395265923684e-06}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [2:00:23<?, ?it/s]

[I 2026-02-20 13:11:12,356] Trial 128 finished with value: 0.9119673131044366 and parameters: {'layer1': 427, 'layer2': 150, 'layer3': 310, 'activation': 'identity', 'solver': 'adam', 'lr': 1.2771238971778936e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [2:01:29<?, ?it/s]

[I 2026-02-20 13:12:17,983] Trial 129 finished with value: 0.9121105309351158 and parameters: {'layer1': 187, 'layer2': 98, 'layer3': 261, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.2423651813899978e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [2:02:42<?, ?it/s]

[I 2026-02-20 13:13:31,381] Trial 130 finished with value: 0.9127854364121808 and parameters: {'layer1': 435, 'layer2': 72, 'layer3': 285, 'activation': 'relu', 'solver': 'adam', 'lr': 2.1784673427101518e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [2:03:42<?, ?it/s]

[I 2026-02-20 13:14:31,413] Trial 131 finished with value: 0.9146639688878688 and parameters: {'layer1': 408, 'layer2': 136, 'layer3': 248, 'activation': 'relu', 'solver': 'adam', 'lr': 2.764449285883672e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [2:05:00<?, ?it/s]

[I 2026-02-20 13:15:49,215] Trial 132 finished with value: 0.9142129287780282 and parameters: {'layer1': 393, 'layer2': 136, 'layer3': 243, 'activation': 'relu', 'solver': 'adam', 'lr': 1.6363202423316575e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [2:06:24<?, ?it/s]

[I 2026-02-20 13:17:13,608] Trial 133 finished with value: 0.9129129061431158 and parameters: {'layer1': 391, 'layer2': 141, 'layer3': 245, 'activation': 'relu', 'solver': 'adam', 'lr': 1.5557619017113146e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [2:07:42<?, ?it/s]

[I 2026-02-20 13:18:31,018] Trial 134 finished with value: 0.9124392991834771 and parameters: {'layer1': 382, 'layer2': 154, 'layer3': 254, 'activation': 'relu', 'solver': 'adam', 'lr': 1.762775922153183e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [2:08:23<?, ?it/s]

[I 2026-02-20 13:19:12,836] Trial 135 finished with value: 0.7523097742595235 and parameters: {'layer1': 410, 'layer2': 131, 'layer3': 217, 'activation': 'relu', 'solver': 'adam', 'lr': 8.820111251868934e-06}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [2:09:30<?, ?it/s]

[I 2026-02-20 13:20:19,009] Trial 136 finished with value: 0.9129587698222652 and parameters: {'layer1': 404, 'layer2': 166, 'layer3': 303, 'activation': 'relu', 'solver': 'adam', 'lr': 2.7456585073701122e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [2:11:22<?, ?it/s]

[I 2026-02-20 13:22:11,184] Trial 137 finished with value: 0.9142301734001691 and parameters: {'layer1': 395, 'layer2': 190, 'layer3': 229, 'activation': 'relu', 'solver': 'adam', 'lr': 1.1098290087032362e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [2:12:55<?, ?it/s]

[I 2026-02-20 13:23:44,485] Trial 138 finished with value: 0.8757904790559403 and parameters: {'layer1': 396, 'layer2': 196, 'layer3': 230, 'activation': 'relu', 'solver': 'adam', 'lr': 1.1035261042761455e-05}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [2:13:11<?, ?it/s]

[I 2026-02-20 13:24:00,629] Trial 139 finished with value: 0.7197965498069652 and parameters: {'layer1': 219, 'layer2': 119, 'layer3': 237, 'activation': 'relu', 'solver': 'adam', 'lr': 5.946799754589961e-06}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [2:13:32<?, ?it/s]

[I 2026-02-20 13:24:20,974] Trial 140 finished with value: 0.713179352973361 and parameters: {'layer1': 419, 'layer2': 31, 'layer3': 278, 'activation': 'relu', 'solver': 'adam', 'lr': 9.242733764996779e-06}. Best is trial 35 with value: 0.9152281845585296.

Training Exact MLP (Paper):   0%|          | 0/14 [2:15:10<?, ?it/s]

[I 2026-02-20 13:25:58,914] Trial 141 finished with value: 0.9153806597928582 and parameters: {'layer1': 378, 'layer2': 176, 'layer3': 268, 'activation': 'relu', 'solver': 'adam', 'lr': 1.3526840732097722e-05}. Best is trial 141 with value: 0.9153806597928582.

Training Exact MLP (Paper):   0%|          | 0/14 [2:16:41<?, ?it/s]

[I 2026-02-20 13:27:30,681] Trial 142 finished with value: 0.9136967156264266 and parameters: {'layer1': 372, 'layer2': 139, 'layer3': 267, 'activation': 'relu', 'solver': 'adam', 'lr': 1.2906988302160292e-05}. Best is trial 141 with value: 0.9153806597928582.

Training Exact MLP (Paper):   0%|          | 0/14 [2:18:04<?, ?it/s]

[I 2026-02-20 13:28:53,541] Trial 143 finished with value: 0.9136438045418288 and parameters: {'layer1': 387, 'layer2': 181, 'layer3': 246, 'activation': 'relu', 'solver': 'adam', 'lr': 1.4956440419874666e-05}. Best is trial 141 with value: 0.9153806597928582.

Training Exact MLP (Paper):   0%|          | 0/14 [2:18:57<?, ?it/s]

[I 2026-02-20 13:29:45,883] Trial 144 finished with value: 0.8724848915880352 and parameters: {'layer1': 60, 'layer2': 190, 'layer3': 228, 'activation': 'relu', 'solver': 'adam', 'lr': 1.9436835957557302e-05}. Best is trial 141 with value: 0.9153806597928582.

Training Exact MLP (Paper):   0%|          | 0/14 [2:20:29<?, ?it/s]

[I 2026-02-20 13:31:18,483] Trial 145 finished with value: 0.8739145933780931 and parameters: {'layer1': 361, 'layer2': 167, 'layer3': 255, 'activation': 'relu', 'solver': 'adam', 'lr': 1.0790930565133361e-05}. Best is trial 141 with value: 0.9153806597928582.

Training Exact MLP (Paper):   0%|          | 0/14 [2:20:50<?, ?it/s]

[I 2026-02-20 13:31:39,163] Trial 146 finished with value: 0.711014531661111 and parameters: {'layer1': 399, 'layer2': 48, 'layer3': 293, 'activation': 'logistic', 'solver': 'adam', 'lr': 2.0082731431231465e-05}. Best is trial 141 with value: 0.9153806597928582.

Training Exact MLP (Paper):   0%|          | 0/14 [2:21:09<?, ?it/s]

[I 2026-02-20 13:31:58,339] Trial 147 finished with value: 0.7131232887704935 and parameters: {'layer1': 335, 'layer2': 153, 'layer3': 269, 'activation': 'relu', 'solver': 'adam', 'lr': 6.882436858802746e-06}. Best is trial 141 with value: 0.9153806597928582.

Training Exact MLP (Paper):   0%|          | 0/14 [2:21:54<?, ?it/s]

[I 2026-02-20 13:32:43,066] Trial 148 finished with value: 0.4543916948989186 and parameters: {'layer1': 465, 'layer2': 249, 'layer3': 340, 'activation': 'relu', 'solver': 'sgd', 'lr': 3.8505187996897516e-06}. Best is trial 141 with value: 0.9153806597928582.

Training Exact MLP (Paper):   0%|          | 0/14 [2:23:07<?, ?it/s]

[I 2026-02-20 13:33:56,088] Trial 149 finished with value: 0.9145476464672508 and parameters: {'layer1': 414, 'layer2': 23, 'layer3': 211, 'activation': 'relu', 'solver': 'adam', 'lr': 3.179175983803812e-05}. Best is trial 141 with value: 0.9153806597928582.

Training Exact MLP (Paper):   0%|          | 0/14 [2:24:18<?, ?it/s]

[I 2026-02-20 13:35:07,765] Trial 150 finished with value: 0.9133331644082807 and parameters: {'layer1': 413, 'layer2': 23, 'layer3': 210, 'activation': 'relu', 'solver': 'adam', 'lr': 3.164020103598409e-05}. Best is trial 141 with value: 0.9153806597928582.

Training Exact MLP (Paper):   0%|          | 0/14 [2:25:16<?, ?it/s]

[I 2026-02-20 13:36:05,763] Trial 151 finished with value: 0.9139192315670922 and parameters: {'layer1': 441, 'layer2': 42, 'layer3': 217, 'activation': 'relu', 'solver': 'adam', 'lr': 4.0859608090342514e-05}. Best is trial 141 with value: 0.9153806597928582.

Training Exact MLP (Paper):   0%|          | 0/14 [2:26:39<?, ?it/s]

[I 2026-02-20 13:37:28,583] Trial 152 finished with value: 0.9135189729699299 and parameters: {'layer1': 389, 'layer2': 17, 'layer3': 201, 'activation': 'relu', 'solver': 'adam', 'lr': 2.6047791969686303e-05}. Best is trial 141 with value: 0.9153806597928582.

Training Exact MLP (Paper):   0%|          | 0/14 [2:28:32<?, ?it/s]

[I 2026-02-20 13:39:21,220] Trial 153 finished with value: 0.9127729919081394 and parameters: {'layer1': 407, 'layer2': 57, 'layer3': 239, 'activation': 'relu', 'solver': 'adam', 'lr': 1.629415991864755e-05}. Best is trial 141 with value: 0.9153806597928582.

Training Exact MLP (Paper):   0%|          | 0/14 [2:29:49<?, ?it/s]

[I 2026-02-20 13:40:38,445] Trial 154 finished with value: 0.9131136107244965 and parameters: {'layer1': 424, 'layer2': 13, 'layer3': 321, 'activation': 'relu', 'solver': 'adam', 'lr': 3.113334324961786e-05}. Best is trial 141 with value: 0.9153806597928582.

Training Exact MLP (Paper):   0%|          | 0/14 [2:31:05<?, ?it/s]

[I 2026-02-20 13:41:54,327] Trial 155 finished with value: 0.9138107479108349 and parameters: {'layer1': 490, 'layer2': 31, 'layer3': 227, 'activation': 'relu', 'solver': 'adam', 'lr': 2.219398139329653e-05}. Best is trial 141 with value: 0.9153806597928582.

Training Exact MLP (Paper):   0%|          | 0/14 [2:32:46<?, ?it/s]

[I 2026-02-20 13:43:35,463] Trial 156 finished with value: 0.9144723722532504 and parameters: {'layer1': 453, 'layer2': 202, 'layer3': 256, 'activation': 'relu', 'solver': 'adam', 'lr': 1.3794009148374002e-05}. Best is trial 141 with value: 0.9153806597928582.

Training Exact MLP (Paper):   0%|          | 0/14 [2:33:09<?, ?it/s]

[I 2026-02-20 13:43:57,850] Trial 157 finished with value: 0.711491424871968 and parameters: {'layer1': 451, 'layer2': 225, 'layer3': 285, 'activation': 'relu', 'solver': 'adam', 'lr': 8.179984735742873e-06}. Best is trial 141 with value: 0.9153806597928582.

Training Exact MLP (Paper):   0%|          | 0/14 [2:34:49<?, ?it/s]

[I 2026-02-20 13:45:38,505] Trial 158 finished with value: 0.9135347977462833 and parameters: {'layer1': 456, 'layer2': 214, 'layer3': 259, 'activation': 'relu', 'solver': 'adam', 'lr': 1.2671220479423292e-05}. Best is trial 141 with value: 0.9153806597928582.

Training Exact MLP (Paper):   0%|          | 0/14 [2:35:30<?, ?it/s]

[I 2026-02-20 13:46:19,311] Trial 159 finished with value: 0.9092767506651299 and parameters: {'layer1': 434, 'layer2': 202, 'layer3': 276, 'activation': 'tanh', 'solver': 'adam', 'lr': 3.622152259786269e-05}. Best is trial 141 with value: 0.9153806597928582.

Training Exact MLP (Paper):   0%|          | 0/14 [2:37:02<?, ?it/s]

[I 2026-02-20 13:47:50,900] Trial 160 finished with value: 0.911002264512701 and parameters: {'layer1': 482, 'layer2': 179, 'layer3': 300, 'activation': 'identity', 'solver': 'adam', 'lr': 1.0013269974730812e-05}. Best is trial 141 with value: 0.9153806597928582.

Training Exact MLP (Paper):   0%|          | 0/14 [2:38:27<?, ?it/s]

[I 2026-02-20 13:49:16,397] Trial 161 finished with value: 0.9126953812539341 and parameters: {'layer1': 469, 'layer2': 161, 'layer3': 248, 'activation': 'relu', 'solver': 'adam', 'lr': 1.4556867081150524e-05}. Best is trial 141 with value: 0.9153806597928582.

Training Exact MLP (Paper):   0%|          | 0/14 [2:39:50<?, ?it/s]

[I 2026-02-20 13:50:38,917] Trial 162 finished with value: 0.9130767397235925 and parameters: {'layer1': 382, 'layer2': 187, 'layer3': 238, 'activation': 'relu', 'solver': 'adam', 'lr': 1.7687988470884394e-05}. Best is trial 141 with value: 0.9153806597928582.

Training Exact MLP (Paper):   0%|          | 0/14 [2:40:56<?, ?it/s]

[I 2026-02-20 13:51:44,876] Trial 163 finished with value: 0.9137811794862596 and parameters: {'layer1': 500, 'layer2': 174, 'layer3': 219, 'activation': 'relu', 'solver': 'adam', 'lr': 2.5362909525851747e-05}. Best is trial 141 with value: 0.9153806597928582.

Training Exact MLP (Paper):   0%|          | 0/14 [2:42:07<?, ?it/s]

[I 2026-02-20 13:52:56,315] Trial 164 finished with value: 0.9133290620966659 and parameters: {'layer1': 445, 'layer2': 146, 'layer3': 251, 'activation': 'relu', 'solver': 'adam', 'lr': 1.9534066197495188e-05}. Best is trial 141 with value: 0.9153806597928582.

Training Exact MLP (Paper):   0%|          | 0/14 [2:43:43<?, ?it/s]

[I 2026-02-20 13:54:32,122] Trial 165 finished with value: 0.9150268410167015 and parameters: {'layer1': 418, 'layer2': 271, 'layer3': 263, 'activation': 'relu', 'solver': 'adam', 'lr': 1.1997498982742516e-05}. Best is trial 141 with value: 0.9153806597928582.

Training Exact MLP (Paper):   0%|          | 0/14 [2:45:18<?, ?it/s]

[I 2026-02-20 13:56:07,769] Trial 166 finished with value: 0.9145586466503779 and parameters: {'layer1': 459, 'layer2': 270, 'layer3': 265, 'activation': 'relu', 'solver': 'adam', 'lr': 1.1442845085132066e-05}. Best is trial 141 with value: 0.9153806597928582.

Training Exact MLP (Paper):   0%|          | 0/14 [2:46:08<?, ?it/s]

[I 2026-02-20 13:56:57,649] Trial 167 finished with value: 0.9137982559532623 and parameters: {'layer1': 459, 'layer2': 269, 'layer3': 277, 'activation': 'relu', 'solver': 'adam', 'lr': 4.665133156139276e-05}. Best is trial 141 with value: 0.9153806597928582.

Training Exact MLP (Paper):   0%|          | 0/14 [2:47:41<?, ?it/s]

[I 2026-02-20 13:58:29,899] Trial 168 finished with value: 0.9148780500318617 and parameters: {'layer1': 483, 'layer2': 293, 'layer3': 265, 'activation': 'relu', 'solver': 'adam', 'lr': 1.308030909761331e-05}. Best is trial 141 with value: 0.9153806597928582.

Training Exact MLP (Paper):   0%|          | 0/14 [2:48:39<?, ?it/s]

[I 2026-02-20 13:59:28,579] Trial 169 finished with value: 0.9129646184742258 and parameters: {'layer1': 482, 'layer2': 295, 'layer3': 264, 'activation': 'relu', 'solver': 'adam', 'lr': 2.922603042509605e-05}. Best is trial 141 with value: 0.9153806597928582.

Training Exact MLP (Paper):   0%|          | 0/14 [2:50:09<?, ?it/s]

[I 2026-02-20 14:00:58,454] Trial 170 finished with value: 0.9146708004223347 and parameters: {'layer1': 430, 'layer2': 286, 'layer3': 260, 'activation': 'relu', 'solver': 'adam', 'lr': 1.3686517810877117e-05}. Best is trial 141 with value: 0.9153806597928582.

Training Exact MLP (Paper):   0%|          | 0/14 [2:51:41<?, ?it/s]

[I 2026-02-20 14:02:30,180] Trial 171 finished with value: 0.9136962035903695 and parameters: {'layer1': 430, 'layer2': 316, 'layer3': 257, 'activation': 'relu', 'solver': 'adam', 'lr': 1.2914200717105236e-05}. Best is trial 141 with value: 0.9153806597928582.

Training Exact MLP (Paper):   0%|          | 0/14 [2:52:51<?, ?it/s]

[I 2026-02-20 14:03:40,312] Trial 172 finished with value: 0.7935430177671687 and parameters: {'layer1': 416, 'layer2': 282, 'layer3': 267, 'activation': 'relu', 'solver': 'adam', 'lr': 8.196633500238979e-06}. Best is trial 141 with value: 0.9153806597928582.

Training Exact MLP (Paper):   0%|          | 0/14 [2:54:21<?, ?it/s]

[I 2026-02-20 14:05:10,628] Trial 173 finished with value: 0.9159735464265195 and parameters: {'layer1': 437, 'layer2': 279, 'layer3': 286, 'activation': 'relu', 'solver': 'adam', 'lr': 1.4283640199276648e-05}. Best is trial 173 with value: 0.9159735464265195.

Training Exact MLP (Paper):   0%|          | 0/14 [2:55:43<?, ?it/s]

[I 2026-02-20 14:06:32,130] Trial 174 finished with value: 0.9129068375896934 and parameters: {'layer1': 440, 'layer2': 291, 'layer3': 286, 'activation': 'relu', 'solver': 'adam', 'lr': 1.3819674141158842e-05}. Best is trial 173 with value: 0.9159735464265195.

Training Exact MLP (Paper):   0%|          | 0/14 [2:57:35<?, ?it/s]

[I 2026-02-20 14:08:23,900] Trial 175 finished with value: 0.9140292644844468 and parameters: {'layer1': 451, 'layer2': 261, 'layer3': 269, 'activation': 'relu', 'solver': 'adam', 'lr': 1.0446051390443228e-05}. Best is trial 173 with value: 0.9159735464265195.

Training Exact MLP (Paper):   0%|          | 0/14 [2:58:54<?, ?it/s]

[I 2026-02-20 14:09:43,338] Trial 176 finished with value: 0.9111770661810443 and parameters: {'layer1': 465, 'layer2': 325, 'layer3': 259, 'activation': 'relu', 'solver': 'adam', 'lr': 1.5521695859206797e-05}. Best is trial 173 with value: 0.9159735464265195.

Training Exact MLP (Paper):   0%|          | 0/14 [3:00:22<?, ?it/s]

[I 2026-02-20 14:11:10,987] Trial 177 finished with value: 0.8708796959124208 and parameters: {'layer1': 427, 'layer2': 282, 'layer3': 249, 'activation': 'relu', 'solver': 'adam', 'lr': 9.748769711691932e-06}. Best is trial 173 with value: 0.9159735464265195.

Training Exact MLP (Paper):   0%|          | 0/14 [3:00:44<?, ?it/s]

[I 2026-02-20 14:11:33,826] Trial 178 finished with value: 0.4534956029139794 and parameters: {'layer1': 492, 'layer2': 297, 'layer3': 285, 'activation': 'relu', 'solver': 'sgd', 'lr': 1.8505025907182886e-05}. Best is trial 173 with value: 0.9159735464265195.

Training Exact MLP (Paper):   0%|          | 0/14 [3:01:07<?, ?it/s]

[I 2026-02-20 14:11:56,691] Trial 179 finished with value: 0.711014531661111 and parameters: {'layer1': 471, 'layer2': 272, 'layer3': 275, 'activation': 'logistic', 'solver': 'adam', 'lr': 1.2177131229738638e-05}. Best is trial 173 with value: 0.9159735464265195.

Training Exact MLP (Paper):   0%|          | 0/14 [3:01:30<?, ?it/s]

[I 2026-02-20 14:12:18,978] Trial 180 finished with value: 0.711014531661111 and parameters: {'layer1': 420, 'layer2': 303, 'layer3': 309, 'activation': 'relu', 'solver': 'adam', 'lr': 6.839927347380951e-06}. Best is trial 173 with value: 0.9159735464265195.

Training Exact MLP (Paper):   0%|          | 0/14 [3:02:28<?, ?it/s]

[I 2026-02-20 14:13:17,280] Trial 181 finished with value: 0.9124542389503013 and parameters: {'layer1': 440, 'layer2': 256, 'layer3': 395, 'activation': 'relu', 'solver': 'adam', 'lr': 2.31849166044879e-05}. Best is trial 173 with value: 0.9159735464265195.

Training Exact MLP (Paper):   0%|          | 0/14 [3:03:14<?, ?it/s]

[I 2026-02-20 14:14:03,042] Trial 182 finished with value: 0.914495371421937 and parameters: {'layer1': 238, 'layer2': 286, 'layer3': 488, 'activation': 'relu', 'solver': 'adam', 'lr': 3.7855781960572786e-05}. Best is trial 173 with value: 0.9159735464265195.

Training Exact MLP (Paper):   0%|          | 0/14 [3:04:02<?, ?it/s]

[I 2026-02-20 14:14:51,155] Trial 183 finished with value: 0.9131982732107901 and parameters: {'layer1': 481, 'layer2': 284, 'layer3': 242, 'activation': 'relu', 'solver': 'adam', 'lr': 4.085957922781465e-05}. Best is trial 173 with value: 0.9159735464265195.

Training Exact MLP (Paper):   0%|          | 0/14 [3:04:56<?, ?it/s]

[I 2026-02-20 14:15:45,193] Trial 184 finished with value: 0.9130794209285792 and parameters: {'layer1': 407, 'layer2': 270, 'layer3': 257, 'activation': 'relu', 'solver': 'adam', 'lr': 3.197991725509564e-05}. Best is trial 173 with value: 0.9159735464265195.

Training Exact MLP (Paper):   0%|          | 0/14 [3:05:32<?, ?it/s]

[I 2026-02-20 14:16:21,087] Trial 185 finished with value: 0.9106817977610978 and parameters: {'layer1': 259, 'layer2': 244, 'layer3': 494, 'activation': 'relu', 'solver': 'adam', 'lr': 6.655571412264356e-05}. Best is trial 173 with value: 0.9159735464265195.

Training Exact MLP (Paper):   0%|          | 0/14 [3:06:20<?, ?it/s]

[I 2026-02-20 14:17:09,569] Trial 186 finished with value: 0.9112085070276168 and parameters: {'layer1': 455, 'layer2': 278, 'layer3': 453, 'activation': 'relu', 'solver': 'adam', 'lr': 5.256077190720827e-05}. Best is trial 173 with value: 0.9159735464265195.

Training Exact MLP (Paper):   0%|          | 0/14 [3:07:31<?, ?it/s]

[I 2026-02-20 14:18:20,653] Trial 187 finished with value: 0.9132070859394883 and parameters: {'layer1': 433, 'layer2': 261, 'layer3': 185, 'activation': 'relu', 'solver': 'adam', 'lr': 2.0484032406265987e-05}. Best is trial 173 with value: 0.9159735464265195.

Training Exact MLP (Paper):   0%|          | 0/14 [3:08:21<?, ?it/s]

[I 2026-02-20 14:19:10,523] Trial 188 finished with value: 0.9107115122515346 and parameters: {'layer1': 474, 'layer2': 289, 'layer3': 420, 'activation': 'relu', 'solver': 'adam', 'lr': 3.841147778060725e-05}. Best is trial 173 with value: 0.9159735464265195.

Training Exact MLP (Paper):   0%|          | 0/14 [3:09:17<?, ?it/s]

[I 2026-02-20 14:20:06,550] Trial 189 finished with value: 0.9134764332831224 and parameters: {'layer1': 461, 'layer2': 304, 'layer3': 205, 'activation': 'relu', 'solver': 'adam', 'lr': 2.838516752055358e-05}. Best is trial 173 with value: 0.9159735464265195.

Training Exact MLP (Paper):   0%|          | 0/14 [3:10:56<?, ?it/s]

[I 2026-02-20 14:21:45,071] Trial 190 finished with value: 0.9142595987801754 and parameters: {'layer1': 446, 'layer2': 317, 'layer3': 31, 'activation': 'relu', 'solver': 'adam', 'lr': 1.4231887898160304e-05}. Best is trial 173 with value: 0.9159735464265195.

Training Exact MLP (Paper):   0%|          | 0/14 [3:12:00<?, ?it/s]

[I 2026-02-20 14:22:49,780] Trial 191 finished with value: 0.9152016954252084 and parameters: {'layer1': 233, 'layer2': 269, 'layer3': 266, 'activation': 'relu', 'solver': 'adam', 'lr': 2.274139839407222e-05}. Best is trial 173 with value: 0.9159735464265195.

Training Exact MLP (Paper):   0%|          | 0/14 [3:12:45<?, ?it/s]

[I 2026-02-20 14:23:34,087] Trial 192 finished with value: 0.9115094613636916 and parameters: {'layer1': 222, 'layer2': 267, 'layer3': 484, 'activation': 'relu', 'solver': 'adam', 'lr': 3.457598984462457e-05}. Best is trial 173 with value: 0.9159735464265195.

Training Exact MLP (Paper):   0%|          | 0/14 [3:13:54<?, ?it/s]

[I 2026-02-20 14:24:43,576] Trial 193 finished with value: 0.9151550738996603 and parameters: {'layer1': 238, 'layer2': 285, 'layer3': 267, 'activation': 'relu', 'solver': 'adam', 'lr': 1.6772115708984564e-05}. Best is trial 173 with value: 0.9159735464265195.

Training Exact MLP (Paper):   0%|          | 0/14 [3:15:17<?, ?it/s]

[I 2026-02-20 14:26:06,718] Trial 194 finished with value: 0.9171388023398238 and parameters: {'layer1': 244, 'layer2': 254, 'layer3': 266, 'activation': 'relu', 'solver': 'adam', 'lr': 1.2136683772617763e-05}. Best is trial 194 with value: 0.9171388023398238.

Training Exact MLP (Paper):   0%|          | 0/14 [3:15:34<?, ?it/s]

[I 2026-02-20 14:26:23,549] Trial 195 finished with value: 0.7130530252520793 and parameters: {'layer1': 224, 'layer2': 340, 'layer3': 271, 'activation': 'relu', 'solver': 'adam', 'lr': 9.213463582295564e-06}. Best is trial 194 with value: 0.9171388023398238.

Training Exact MLP (Paper):   0%|          | 0/14 [3:16:38<?, ?it/s]

[I 2026-02-20 14:27:27,436] Trial 196 finished with value: 0.8341370526724047 and parameters: {'layer1': 252, 'layer2': 254, 'layer3': 263, 'activation': 'relu', 'solver': 'adam', 'lr': 1.0630964804919086e-05}. Best is trial 194 with value: 0.9171388023398238.

Training Exact MLP (Paper):   0%|          | 0/14 [3:18:15<?, ?it/s]

[I 2026-02-20 14:29:04,263] Trial 197 finished with value: 0.9130169940382666 and parameters: {'layer1': 235, 'layer2': 278, 'layer3': 276, 'activation': 'relu', 'solver': 'adam', 'lr': 1.176059413412415e-05}. Best is trial 194 with value: 0.9171388023398238.

Training Exact MLP (Paper):   0%|          | 0/14 [3:19:24<?, ?it/s]

[I 2026-02-20 14:30:13,113] Trial 198 finished with value: 0.9118229900229894 and parameters: {'layer1': 244, 'layer2': 299, 'layer3': 253, 'activation': 'relu', 'solver': 'adam', 'lr': 1.5495455603650408e-05}. Best is trial 194 with value: 0.9171388023398238.

Best trial: 194. Best value: 0.917139: 100%|██████████| 200/200 [3:20:22<00:00, 60.11s/it]

[I 2026-02-20 14:31:11,808] Trial 199 finished with value: 0.9110275181718569 and parameters: {'layer1': 236, 'layer2': 282, 'layer3': 289, 'activation': 'identity', 'solver': 'adam', 'lr': 1.3308136749265054e-05}. Best is trial 194 with value: 0.9171388023398238.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:20:23<43:25:09, 12023.84s/it][I 2026-02-20 14:31:12,692] A new study created in memory with name: no-name-d7fbcb8c-15cf-49f9-bc5f-6dbbd72d9d3c

  → Best model saved.

[Exact Paper MLP] Staphylococcus_Aureus | Clindamycin

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:20:57<43:25:09, 12023.84s/it]

[I 2026-02-20 14:31:46,056] Trial 0 finished with value: 0.6370985287632289 and parameters: {'layer1': 201, 'layer2': 183, 'layer3': 459, 'activation': 'relu', 'solver': 'sgd', 'lr': 5.849096769543229e-06}. Best is trial 0 with value: 0.6370985287632289.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:21:20<43:25:09, 12023.84s/it]

[I 2026-02-20 14:32:09,827] Trial 1 finished with value: 0.7891915507360391 and parameters: {'layer1': 294, 'layer2': 185, 'layer3': 345, 'activation': 'relu', 'solver': 'sgd', 'lr': 5.8189514144570215e-05}. Best is trial 1 with value: 0.7891915507360391.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:21:31<43:25:09, 12023.84s/it]

[I 2026-02-20 14:32:20,840] Trial 2 finished with value: 0.7888558471217525 and parameters: {'layer1': 92, 'layer2': 23, 'layer3': 38, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.584860340069959e-05}. Best is trial 1 with value: 0.7891915507360391.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:22:11<43:25:09, 12023.84s/it]

[I 2026-02-20 14:33:00,498] Trial 3 finished with value: 0.7866437208667678 and parameters: {'layer1': 152, 'layer2': 477, 'layer3': 190, 'activation': 'tanh', 'solver': 'sgd', 'lr': 1.5426466685233767e-06}. Best is trial 1 with value: 0.7891915507360391.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:22:35<43:25:09, 12023.84s/it]

[I 2026-02-20 14:33:24,502] Trial 4 finished with value: 0.8527435920873675 and parameters: {'layer1': 192, 'layer2': 455, 'layer3': 384, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0001177617047689339}. Best is trial 4 with value: 0.8527435920873675.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:23:25<43:25:09, 12023.84s/it]

[I 2026-02-20 14:34:14,507] Trial 5 finished with value: 0.8561475831813169 and parameters: {'layer1': 195, 'layer2': 230, 'layer3': 450, 'activation': 'identity', 'solver': 'adam', 'lr': 1.8650961936657895e-05}. Best is trial 5 with value: 0.8561475831813169.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:23:37<43:25:09, 12023.84s/it]

[I 2026-02-20 14:34:26,376] Trial 6 finished with value: 0.7888558471217525 and parameters: {'layer1': 73, 'layer2': 128, 'layer3': 95, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.009542538848416238}. Best is trial 5 with value: 0.8561475831813169.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:24:00<43:25:09, 12023.84s/it]

[I 2026-02-20 14:34:49,521] Trial 7 finished with value: 0.8512136286896274 and parameters: {'layer1': 130, 'layer2': 490, 'layer3': 156, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0009981268576559608}. Best is trial 5 with value: 0.8561475831813169.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:24:18<43:25:09, 12023.84s/it]

[I 2026-02-20 14:35:07,292] Trial 8 finished with value: 0.8046711655166195 and parameters: {'layer1': 56, 'layer2': 448, 'layer3': 496, 'activation': 'identity', 'solver': 'adam', 'lr': 1.4768618616734005e-05}. Best is trial 5 with value: 0.8561475831813169.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:24:31<43:25:09, 12023.84s/it]

[I 2026-02-20 14:35:20,103] Trial 9 finished with value: 0.7888558471217525 and parameters: {'layer1': 259, 'layer2': 441, 'layer3': 111, 'activation': 'relu', 'solver': 'sgd', 'lr': 0.005068864474035993}. Best is trial 5 with value: 0.8561475831813169.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:25:26<43:25:09, 12023.84s/it]

[I 2026-02-20 14:36:15,159] Trial 10 finished with value: 0.8380219477087092 and parameters: {'layer1': 441, 'layer2': 321, 'layer3': 266, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.000191737197525017}. Best is trial 5 with value: 0.8561475831813169.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:25:56<43:25:09, 12023.84s/it]

[I 2026-02-20 14:36:45,261] Trial 11 finished with value: 0.8511395718213819 and parameters: {'layer1': 335, 'layer2': 321, 'layer3': 382, 'activation': 'identity', 'solver': 'adam', 'lr': 0.000145804824118713}. Best is trial 5 with value: 0.8561475831813169.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:26:27<43:25:09, 12023.84s/it]

[I 2026-02-20 14:37:16,820] Trial 12 finished with value: 0.856980338654391 and parameters: {'layer1': 203, 'layer2': 333, 'layer3': 395, 'activation': 'identity', 'solver': 'adam', 'lr': 5.2615665074921666e-05}. Best is trial 12 with value: 0.856980338654391.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:27:11<43:25:09, 12023.84s/it]

[I 2026-02-20 14:38:00,154] Trial 13 finished with value: 0.8564299980742847 and parameters: {'layer1': 339, 'layer2': 327, 'layer3': 312, 'activation': 'identity', 'solver': 'adam', 'lr': 3.180328788111439e-05}. Best is trial 12 with value: 0.856980338654391.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:27:42<43:25:09, 12023.84s/it]

[I 2026-02-20 14:38:30,883] Trial 14 finished with value: 0.8477627731010573 and parameters: {'layer1': 395, 'layer2': 345, 'layer3': 276, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0005069829373840609}. Best is trial 12 with value: 0.856980338654391.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:28:06<43:25:09, 12023.84s/it]

[I 2026-02-20 14:38:55,807] Trial 15 finished with value: 0.7888558471217525 and parameters: {'layer1': 358, 'layer2': 384, 'layer3': 322, 'activation': 'logistic', 'solver': 'adam', 'lr': 1.5247065739205537e-06}. Best is trial 12 with value: 0.856980338654391.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:28:53<43:25:09, 12023.84s/it]

[I 2026-02-20 14:39:42,279] Trial 16 finished with value: 0.8537477305922521 and parameters: {'layer1': 472, 'layer2': 265, 'layer3': 209, 'activation': 'identity', 'solver': 'adam', 'lr': 4.152669501304886e-05}. Best is trial 12 with value: 0.856980338654391.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:29:10<43:25:09, 12023.84s/it]

[I 2026-02-20 14:39:59,670] Trial 17 finished with value: 0.7888558471217525 and parameters: {'layer1': 276, 'layer2': 385, 'layer3': 408, 'activation': 'identity', 'solver': 'adam', 'lr': 4.064639447838055e-06}. Best is trial 12 with value: 0.856980338654391.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:29:24<43:25:09, 12023.84s/it]

[I 2026-02-20 14:40:13,701] Trial 18 finished with value: 0.7889667421572524 and parameters: {'layer1': 330, 'layer2': 282, 'layer3': 312, 'activation': 'identity', 'solver': 'sgd', 'lr': 0.0006373460711554913}. Best is trial 12 with value: 0.856980338654391.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:29:48<43:25:09, 12023.84s/it]

[I 2026-02-20 14:40:37,713] Trial 19 finished with value: 0.7888558471217525 and parameters: {'layer1': 436, 'layer2': 395, 'layer3': 233, 'activation': 'logistic', 'solver': 'adam', 'lr': 4.751101597714115e-05}. Best is trial 12 with value: 0.856980338654391.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:30:11<43:25:09, 12023.84s/it]

[I 2026-02-20 14:41:00,793] Trial 20 finished with value: 0.8520106695214104 and parameters: {'layer1': 230, 'layer2': 102, 'layer3': 354, 'activation': 'identity', 'solver': 'adam', 'lr': 0.00029493044007212305}. Best is trial 12 with value: 0.856980338654391.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:30:22<43:25:09, 12023.84s/it]

[I 2026-02-20 14:41:11,008] Trial 21 finished with value: 0.7888558471217525 and parameters: {'layer1': 16, 'layer2': 218, 'layer3': 436, 'activation': 'identity', 'solver': 'adam', 'lr': 1.9367129560970147e-05}. Best is trial 12 with value: 0.856980338654391.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:30:36<43:25:09, 12023.84s/it]

[I 2026-02-20 14:41:25,491] Trial 22 finished with value: 0.7888558471217525 and parameters: {'layer1': 168, 'layer2': 239, 'layer3': 471, 'activation': 'identity', 'solver': 'adam', 'lr': 7.690759224861685e-06}. Best is trial 12 with value: 0.856980338654391.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:31:11<43:25:09, 12023.84s/it]

[I 2026-02-20 14:42:00,785] Trial 23 finished with value: 0.8525923339236929 and parameters: {'layer1': 221, 'layer2': 288, 'layer3': 423, 'activation': 'identity', 'solver': 'adam', 'lr': 3.188361300489886e-05}. Best is trial 12 with value: 0.856980338654391.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:31:37<43:25:09, 12023.84s/it]

[I 2026-02-20 14:42:25,918] Trial 24 finished with value: 0.8532438954967155 and parameters: {'layer1': 114, 'layer2': 341, 'layer3': 296, 'activation': 'identity', 'solver': 'adam', 'lr': 7.7110304640145e-05}. Best is trial 12 with value: 0.856980338654391.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:31:54<43:25:09, 12023.84s/it]

[I 2026-02-20 14:42:43,298] Trial 25 finished with value: 0.7888558471217525 and parameters: {'layer1': 301, 'layer2': 210, 'layer3': 392, 'activation': 'identity', 'solver': 'adam', 'lr': 3.83681961142624e-06}. Best is trial 12 with value: 0.856980338654391.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:32:22<43:25:09, 12023.84s/it]

[I 2026-02-20 14:43:11,545] Trial 26 finished with value: 0.7904924487930929 and parameters: {'layer1': 387, 'layer2': 137, 'layer3': 351, 'activation': 'identity', 'solver': 'sgd', 'lr': 1.0720848192072373e-05}. Best is trial 12 with value: 0.856980338654391.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:33:02<43:25:09, 12023.84s/it]

[I 2026-02-20 14:43:51,627] Trial 27 finished with value: 0.8532862356778967 and parameters: {'layer1': 242, 'layer2': 294, 'layer3': 450, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.600431676832621e-05}. Best is trial 12 with value: 0.856980338654391.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:33:18<43:25:09, 12023.84s/it]

[I 2026-02-20 14:44:07,546] Trial 28 finished with value: 0.7888558471217525 and parameters: {'layer1': 174, 'layer2': 411, 'layer3': 488, 'activation': 'logistic', 'solver': 'adam', 'lr': 7.798996675925193e-05}. Best is trial 12 with value: 0.856980338654391.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:34:29<43:25:09, 12023.84s/it]

[I 2026-02-20 14:45:18,533] Trial 29 finished with value: 0.6412207226797769 and parameters: {'layer1': 206, 'layer2': 363, 'layer3': 451, 'activation': 'relu', 'solver': 'sgd', 'lr': 5.416114968835437e-06}. Best is trial 12 with value: 0.856980338654391.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:34:47<43:25:09, 12023.84s/it]

[I 2026-02-20 14:45:36,539] Trial 30 finished with value: 0.7888558471217525 and parameters: {'layer1': 318, 'layer2': 240, 'layer3': 332, 'activation': 'identity', 'solver': 'adam', 'lr': 2.8688321505948826e-06}. Best is trial 12 with value: 0.856980338654391.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:35:27<43:25:09, 12023.84s/it]

[I 2026-02-20 14:46:16,637] Trial 31 finished with value: 0.8516341883566276 and parameters: {'layer1': 413, 'layer2': 274, 'layer3': 231, 'activation': 'identity', 'solver': 'adam', 'lr': 5.653274595190024e-05}. Best is trial 12 with value: 0.856980338654391.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:36:14<43:25:09, 12023.84s/it]

[I 2026-02-20 14:47:03,690] Trial 32 finished with value: 0.8549469837796078 and parameters: {'layer1': 466, 'layer2': 197, 'layer3': 205, 'activation': 'identity', 'solver': 'adam', 'lr': 3.7304916977300204e-05}. Best is trial 12 with value: 0.856980338654391.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:36:34<43:25:09, 12023.84s/it]

[I 2026-02-20 14:47:23,527] Trial 33 finished with value: 0.7888558471217525 and parameters: {'layer1': 363, 'layer2': 158, 'layer3': 183, 'activation': 'identity', 'solver': 'adam', 'lr': 1.0499307452324344e-05}. Best is trial 12 with value: 0.856980338654391.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:36:54<43:25:09, 12023.84s/it]

[I 2026-02-20 14:47:42,894] Trial 34 finished with value: 0.7903383332796274 and parameters: {'layer1': 473, 'layer2': 187, 'layer3': 289, 'activation': 'identity', 'solver': 'sgd', 'lr': 3.0531108393594525e-05}. Best is trial 12 with value: 0.856980338654391.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:37:20<43:25:09, 12023.84s/it]

[I 2026-02-20 14:48:09,604] Trial 35 finished with value: 0.8511660499028368 and parameters: {'layer1': 278, 'layer2': 47, 'layer3': 365, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.00021627004514325138}. Best is trial 12 with value: 0.856980338654391.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:37:36<43:25:09, 12023.84s/it]

[I 2026-02-20 14:48:24,984] Trial 36 finished with value: 0.7888558471217525 and parameters: {'layer1': 185, 'layer2': 203, 'layer3': 147, 'activation': 'relu', 'solver': 'adam', 'lr': 1.832819772580735e-05}. Best is trial 12 with value: 0.856980338654391.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:38:13<43:25:09, 12023.84s/it]

[I 2026-02-20 14:49:02,131] Trial 37 finished with value: 0.8509233407485228 and parameters: {'layer1': 494, 'layer2': 313, 'layer3': 428, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0001010461536647243}. Best is trial 12 with value: 0.856980338654391.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:38:26<43:25:09, 12023.84s/it]

[I 2026-02-20 14:49:15,328] Trial 38 finished with value: 0.7888558471217525 and parameters: {'layer1': 133, 'layer2': 98, 'layer3': 52, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.1386384808101864e-05}. Best is trial 12 with value: 0.856980338654391.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:38:46<43:25:09, 12023.84s/it]

[I 2026-02-20 14:49:35,148] Trial 39 finished with value: 0.7916924184594427 and parameters: {'layer1': 148, 'layer2': 237, 'layer3': 249, 'activation': 'identity', 'solver': 'sgd', 'lr': 2.3940799771474546e-05}. Best is trial 12 with value: 0.856980338654391.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:39:29<43:25:09, 12023.84s/it]

[I 2026-02-20 14:50:18,816] Trial 40 finished with value: 0.8545071637766138 and parameters: {'layer1': 256, 'layer2': 169, 'layer3': 402, 'activation': 'relu', 'solver': 'adam', 'lr': 6.11173826311858e-05}. Best is trial 12 with value: 0.856980338654391.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:40:19<43:25:09, 12023.84s/it]

[I 2026-02-20 14:51:08,209] Trial 41 finished with value: 0.8553032292785966 and parameters: {'layer1': 250, 'layer2': 150, 'layer3': 402, 'activation': 'relu', 'solver': 'adam', 'lr': 5.758485345805789e-05}. Best is trial 12 with value: 0.856980338654391.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:40:50<43:25:09, 12023.84s/it]

[I 2026-02-20 14:51:39,044] Trial 42 finished with value: 0.8547083999083199 and parameters: {'layer1': 204, 'layer2': 142, 'layer3': 375, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00013176403883118686}. Best is trial 12 with value: 0.856980338654391.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:41:15<43:25:09, 12023.84s/it]

[I 2026-02-20 14:52:04,041] Trial 43 finished with value: 0.8038031785045332 and parameters: {'layer1': 298, 'layer2': 76, 'layer3': 465, 'activation': 'relu', 'solver': 'adam', 'lr': 3.5891808625643156e-05}. Best is trial 12 with value: 0.856980338654391.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:41:39<43:25:09, 12023.84s/it]

[I 2026-02-20 14:52:28,705] Trial 44 finished with value: 0.8532256193099081 and parameters: {'layer1': 224, 'layer2': 193, 'layer3': 412, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00036004654615798997}. Best is trial 12 with value: 0.856980338654391.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:41:57<43:25:09, 12023.84s/it]

[I 2026-02-20 14:52:46,495] Trial 45 finished with value: 0.7888558471217525 and parameters: {'layer1': 266, 'layer2': 256, 'layer3': 339, 'activation': 'relu', 'solver': 'adam', 'lr': 1.4675305759900723e-05}. Best is trial 12 with value: 0.856980338654391.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:42:11<43:25:09, 12023.84s/it]

[I 2026-02-20 14:53:00,337] Trial 46 finished with value: 0.7888558471217525 and parameters: {'layer1': 108, 'layer2': 166, 'layer3': 151, 'activation': 'logistic', 'solver': 'adam', 'lr': 4.561101727801807e-05}. Best is trial 12 with value: 0.856980338654391.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:42:46<43:25:09, 12023.84s/it]

[I 2026-02-20 14:53:35,564] Trial 47 finished with value: 0.8504907426258626 and parameters: {'layer1': 350, 'layer2': 355, 'layer3': 201, 'activation': 'identity', 'solver': 'adam', 'lr': 0.00281186532137226}. Best is trial 12 with value: 0.856980338654391.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:43:08<43:25:09, 12023.84s/it]

[I 2026-02-20 14:53:56,907] Trial 48 finished with value: 0.8513780457603811 and parameters: {'layer1': 159, 'layer2': 225, 'layer3': 499, 'activation': 'identity', 'solver': 'adam', 'lr': 0.00016425022716483095}. Best is trial 12 with value: 0.856980338654391.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:43:23<43:25:09, 12023.84s/it]

[I 2026-02-20 14:54:11,884] Trial 49 finished with value: 0.7915538581148626 and parameters: {'layer1': 239, 'layer2': 321, 'layer3': 306, 'activation': 'tanh', 'solver': 'sgd', 'lr': 8.542691049583748e-05}. Best is trial 12 with value: 0.856980338654391.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:43:37<43:25:09, 12023.84s/it]

[I 2026-02-20 14:54:26,248] Trial 50 finished with value: 0.7888558471217525 and parameters: {'layer1': 195, 'layer2': 118, 'layer3': 121, 'activation': 'identity', 'solver': 'adam', 'lr': 7.739747204587e-06}. Best is trial 12 with value: 0.856980338654391.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:44:04<43:25:09, 12023.84s/it]

[I 2026-02-20 14:54:53,279] Trial 51 finished with value: 0.8547689352012613 and parameters: {'layer1': 192, 'layer2': 139, 'layer3': 374, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00013179784755502617}. Best is trial 12 with value: 0.856980338654391.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:44:39<43:25:09, 12023.84s/it]

[I 2026-02-20 14:55:27,848] Trial 52 finished with value: 0.854806819179333 and parameters: {'layer1': 208, 'layer2': 161, 'layer3': 388, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00011855146619886625}. Best is trial 12 with value: 0.856980338654391.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:45:07<43:25:09, 12023.84s/it]

[I 2026-02-20 14:55:56,533] Trial 53 finished with value: 0.8517613127363866 and parameters: {'layer1': 214, 'layer2': 177, 'layer3': 437, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00022958116940803762}. Best is trial 12 with value: 0.856980338654391.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:46:09<43:25:09, 12023.84s/it]

[I 2026-02-20 14:56:57,988] Trial 54 finished with value: 0.8562870719860296 and parameters: {'layer1': 438, 'layer2': 419, 'layer3': 390, 'activation': 'relu', 'solver': 'adam', 'lr': 6.934685179114337e-05}. Best is trial 12 with value: 0.856980338654391.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:46:58<43:25:09, 12023.84s/it]

[I 2026-02-20 14:57:47,243] Trial 55 finished with value: 0.8561501879628883 and parameters: {'layer1': 438, 'layer2': 466, 'layer3': 408, 'activation': 'relu', 'solver': 'adam', 'lr': 6.143180528206494e-05}. Best is trial 12 with value: 0.856980338654391.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:47:59<43:25:09, 12023.84s/it]

[I 2026-02-20 14:58:48,617] Trial 56 finished with value: 0.8557200804115193 and parameters: {'layer1': 430, 'layer2': 476, 'layer3': 475, 'activation': 'relu', 'solver': 'adam', 'lr': 5.9170789064481145e-05}. Best is trial 12 with value: 0.856980338654391.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:48:46<43:25:09, 12023.84s/it]

[I 2026-02-20 14:59:35,024] Trial 57 finished with value: 0.8150342275095849 and parameters: {'layer1': 423, 'layer2': 499, 'layer3': 468, 'activation': 'relu', 'solver': 'adam', 'lr': 2.0280124999989606e-05}. Best is trial 12 with value: 0.856980338654391.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:49:34<43:25:09, 12023.84s/it]

[I 2026-02-20 15:00:23,520] Trial 58 finished with value: 0.8566328689612982 and parameters: {'layer1': 398, 'layer2': 468, 'layer3': 478, 'activation': 'relu', 'solver': 'adam', 'lr': 6.225104857550557e-05}. Best is trial 12 with value: 0.856980338654391.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:50:15<43:25:09, 12023.84s/it]

[I 2026-02-20 15:01:04,266] Trial 59 finished with value: 0.8501206783502091 and parameters: {'layer1': 381, 'layer2': 434, 'layer3': 445, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0010832589720021742}. Best is trial 12 with value: 0.856980338654391.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:50:36<43:25:09, 12023.84s/it]

[I 2026-02-20 15:01:24,864] Trial 60 finished with value: 0.638231501939184 and parameters: {'layer1': 451, 'layer2': 466, 'layer3': 417, 'activation': 'logistic', 'solver': 'sgd', 'lr': 1.4314750440334523e-05}. Best is trial 12 with value: 0.856980338654391.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:51:21<43:25:09, 12023.84s/it]

[I 2026-02-20 15:02:10,721] Trial 61 finished with value: 0.855358902692015 and parameters: {'layer1': 404, 'layer2': 476, 'layer3': 472, 'activation': 'relu', 'solver': 'adam', 'lr': 6.886410238454985e-05}. Best is trial 12 with value: 0.856980338654391.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:52:09<43:25:09, 12023.84s/it]

[I 2026-02-20 15:02:58,760] Trial 62 finished with value: 0.8536595041991435 and parameters: {'layer1': 429, 'layer2': 426, 'layer3': 487, 'activation': 'relu', 'solver': 'adam', 'lr': 4.258990998686248e-05}. Best is trial 12 with value: 0.856980338654391.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:52:56<43:25:09, 12023.84s/it]

[I 2026-02-20 15:03:45,235] Trial 63 finished with value: 0.8562589398340614 and parameters: {'layer1': 451, 'layer2': 452, 'layer3': 481, 'activation': 'relu', 'solver': 'adam', 'lr': 9.710234443595261e-05}. Best is trial 12 with value: 0.856980338654391.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:53:44<43:25:09, 12023.84s/it]

[I 2026-02-20 15:04:33,810] Trial 64 finished with value: 0.8540479870535931 and parameters: {'layer1': 492, 'layer2': 452, 'layer3': 434, 'activation': 'relu', 'solver': 'adam', 'lr': 9.602321655295112e-05}. Best is trial 12 with value: 0.856980338654391.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:54:55<43:25:09, 12023.84s/it]

[I 2026-02-20 15:05:43,998] Trial 65 finished with value: 0.859327871148369 and parameters: {'layer1': 448, 'layer2': 411, 'layer3': 453, 'activation': 'relu', 'solver': 'adam', 'lr': 2.6944713351647607e-05}. Best is trial 65 with value: 0.859327871148369.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:56:07<43:25:09, 12023.84s/it]

[I 2026-02-20 15:06:56,501] Trial 66 finished with value: 0.8594929521695608 and parameters: {'layer1': 461, 'layer2': 408, 'layer3': 352, 'activation': 'relu', 'solver': 'adam', 'lr': 2.4233611177457266e-05}. Best is trial 66 with value: 0.8594929521695608.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:57:14<43:25:09, 12023.84s/it]

[I 2026-02-20 15:08:03,767] Trial 67 finished with value: 0.8561225448198909 and parameters: {'layer1': 454, 'layer2': 403, 'layer3': 354, 'activation': 'relu', 'solver': 'adam', 'lr': 2.7402824050676958e-05}. Best is trial 66 with value: 0.8594929521695608.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:58:27<43:25:09, 12023.84s/it]

[I 2026-02-20 15:09:16,444] Trial 68 finished with value: 0.857131216940682 and parameters: {'layer1': 480, 'layer2': 376, 'layer3': 454, 'activation': 'relu', 'solver': 'adam', 'lr': 2.6148381813081254e-05}. Best is trial 66 with value: 0.8594929521695608.

Training Exact MLP (Paper):   7%|▋         | 1/14 [3:59:07<43:25:09, 12023.84s/it]

[I 2026-02-20 15:09:56,366] Trial 69 finished with value: 0.8143130977956229 and parameters: {'layer1': 484, 'layer2': 376, 'layer3': 365, 'activation': 'relu', 'solver': 'adam', 'lr': 2.272151324563628e-05}. Best is trial 66 with value: 0.8594929521695608.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:00:05<43:25:09, 12023.84s/it]

[I 2026-02-20 15:10:54,776] Trial 70 finished with value: 0.8559797574184055 and parameters: {'layer1': 410, 'layer2': 409, 'layer3': 318, 'activation': 'relu', 'solver': 'adam', 'lr': 3.12714611297819e-05}. Best is trial 66 with value: 0.8594929521695608.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:00:29<43:25:09, 12023.84s/it]

[I 2026-02-20 15:11:18,703] Trial 71 finished with value: 0.7888558471217525 and parameters: {'layer1': 464, 'layer2': 420, 'layer3': 457, 'activation': 'relu', 'solver': 'adam', 'lr': 1.040448138953618e-06}. Best is trial 66 with value: 0.8594929521695608.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:01:41<43:25:09, 12023.84s/it]

[I 2026-02-20 15:12:29,972] Trial 72 finished with value: 0.855411935570717 and parameters: {'layer1': 450, 'layer2': 383, 'layer3': 483, 'activation': 'relu', 'solver': 'adam', 'lr': 4.1747389499508674e-05}. Best is trial 66 with value: 0.8594929521695608.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:02:30<43:25:09, 12023.84s/it]

[I 2026-02-20 15:13:19,013] Trial 73 finished with value: 0.8545433106746101 and parameters: {'layer1': 382, 'layer2': 340, 'layer3': 326, 'activation': 'relu', 'solver': 'adam', 'lr': 9.830991122982542e-05}. Best is trial 66 with value: 0.8594929521695608.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:03:25<43:25:09, 12023.84s/it]

[I 2026-02-20 15:14:14,113] Trial 74 finished with value: 0.8577467033248478 and parameters: {'layer1': 480, 'layer2': 444, 'layer3': 424, 'activation': 'relu', 'solver': 'adam', 'lr': 4.912784330490259e-05}. Best is trial 66 with value: 0.8594929521695608.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:03:47<43:25:09, 12023.84s/it]

[I 2026-02-20 15:14:36,705] Trial 75 finished with value: 0.7888558471217525 and parameters: {'layer1': 480, 'layer2': 369, 'layer3': 389, 'activation': 'relu', 'solver': 'adam', 'lr': 1.63384831502618e-05}. Best is trial 66 with value: 0.8594929521695608.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:04:34<43:25:09, 12023.84s/it]

[I 2026-02-20 15:15:23,070] Trial 76 finished with value: 0.8544654682204398 and parameters: {'layer1': 399, 'layer2': 391, 'layer3': 439, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.726724976680357e-05}. Best is trial 66 with value: 0.8594929521695608.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:05:16<43:25:09, 12023.84s/it]

[I 2026-02-20 15:16:05,303] Trial 77 finished with value: 0.7897000194121678 and parameters: {'layer1': 418, 'layer2': 425, 'layer3': 423, 'activation': 'relu', 'solver': 'sgd', 'lr': 5.069512762677056e-05}. Best is trial 66 with value: 0.8594929521695608.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:05:39<43:25:09, 12023.84s/it]

[I 2026-02-20 15:16:28,426] Trial 78 finished with value: 0.7888558471217525 and parameters: {'layer1': 500, 'layer2': 305, 'layer3': 278, 'activation': 'logistic', 'solver': 'adam', 'lr': 1.198839187610746e-05}. Best is trial 66 with value: 0.8594929521695608.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:06:57<43:25:09, 12023.84s/it]

[I 2026-02-20 15:17:46,204] Trial 79 finished with value: 0.8581787067362663 and parameters: {'layer1': 466, 'layer2': 439, 'layer3': 454, 'activation': 'relu', 'solver': 'adam', 'lr': 3.206640835433712e-05}. Best is trial 66 with value: 0.8594929521695608.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:07:19<43:25:09, 12023.84s/it]

[I 2026-02-20 15:18:08,670] Trial 80 finished with value: 0.7888558471217525 and parameters: {'layer1': 466, 'layer2': 354, 'layer3': 453, 'activation': 'relu', 'solver': 'adam', 'lr': 9.359895178859892e-06}. Best is trial 66 with value: 0.8594929521695608.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:08:19<43:25:09, 12023.84s/it]

[I 2026-02-20 15:19:08,236] Trial 81 finished with value: 0.8576049216216957 and parameters: {'layer1': 479, 'layer2': 401, 'layer3': 400, 'activation': 'relu', 'solver': 'adam', 'lr': 3.6380838614654486e-05}. Best is trial 66 with value: 0.8594929521695608.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:09:22<43:25:09, 12023.84s/it]

[I 2026-02-20 15:20:10,976] Trial 82 finished with value: 0.8579986139329309 and parameters: {'layer1': 481, 'layer2': 441, 'layer3': 458, 'activation': 'relu', 'solver': 'adam', 'lr': 3.323208767497453e-05}. Best is trial 66 with value: 0.8594929521695608.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:10:29<43:25:09, 12023.84s/it]

[I 2026-02-20 15:21:18,573] Trial 83 finished with value: 0.8577053541737026 and parameters: {'layer1': 482, 'layer2': 433, 'layer3': 459, 'activation': 'relu', 'solver': 'adam', 'lr': 3.67651563837028e-05}. Best is trial 66 with value: 0.8594929521695608.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:11:31<43:25:09, 12023.84s/it]

[I 2026-02-20 15:22:19,877] Trial 84 finished with value: 0.8307952268413757 and parameters: {'layer1': 477, 'layer2': 398, 'layer3': 457, 'activation': 'relu', 'solver': 'adam', 'lr': 2.226131538531228e-05}. Best is trial 66 with value: 0.8594929521695608.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:12:28<43:25:09, 12023.84s/it]

[I 2026-02-20 15:23:17,718] Trial 85 finished with value: 0.8557540374885892 and parameters: {'layer1': 487, 'layer2': 437, 'layer3': 425, 'activation': 'relu', 'solver': 'adam', 'lr': 3.6954149845192284e-05}. Best is trial 66 with value: 0.8594929521695608.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:12:52<43:25:09, 12023.84s/it]

[I 2026-02-20 15:23:40,864] Trial 86 finished with value: 0.7888558471217525 and parameters: {'layer1': 461, 'layer2': 443, 'layer3': 400, 'activation': 'relu', 'solver': 'adam', 'lr': 1.5948308627918117e-05}. Best is trial 66 with value: 0.8594929521695608.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:13:47<43:25:09, 12023.84s/it]

[I 2026-02-20 15:24:35,851] Trial 87 finished with value: 0.8581927140372223 and parameters: {'layer1': 476, 'layer2': 489, 'layer3': 444, 'activation': 'relu', 'solver': 'adam', 'lr': 4.773052668509457e-05}. Best is trial 66 with value: 0.8594929521695608.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:14:51<43:25:09, 12023.84s/it]

[I 2026-02-20 15:25:40,492] Trial 88 finished with value: 0.8564489214946132 and parameters: {'layer1': 500, 'layer2': 491, 'layer3': 499, 'activation': 'relu', 'solver': 'adam', 'lr': 3.385932715405463e-05}. Best is trial 66 with value: 0.8594929521695608.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:15:58<43:25:09, 12023.84s/it]

[I 2026-02-20 15:26:47,827] Trial 89 finished with value: 0.8578703569640197 and parameters: {'layer1': 473, 'layer2': 486, 'layer3': 446, 'activation': 'relu', 'solver': 'adam', 'lr': 2.5697299961668082e-05}. Best is trial 66 with value: 0.8594929521695608.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:16:49<43:25:09, 12023.84s/it]

[I 2026-02-20 15:27:38,156] Trial 90 finished with value: 0.8552507610494638 and parameters: {'layer1': 469, 'layer2': 461, 'layer3': 441, 'activation': 'relu', 'solver': 'adam', 'lr': 4.8550349054501924e-05}. Best is trial 66 with value: 0.8594929521695608.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:17:24<43:25:09, 12023.84s/it]

[I 2026-02-20 15:28:13,491] Trial 91 finished with value: 0.8004503323790093 and parameters: {'layer1': 483, 'layer2': 487, 'layer3': 463, 'activation': 'relu', 'solver': 'adam', 'lr': 2.0266895544420046e-05}. Best is trial 66 with value: 0.8594929521695608.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:18:25<43:25:09, 12023.84s/it]

[I 2026-02-20 15:29:14,446] Trial 92 finished with value: 0.8582281118504888 and parameters: {'layer1': 444, 'layer2': 435, 'layer3': 417, 'activation': 'relu', 'solver': 'adam', 'lr': 2.8903708680885433e-05}. Best is trial 66 with value: 0.8594929521695608.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:18:47<43:25:09, 12023.84s/it]

[I 2026-02-20 15:29:36,219] Trial 93 finished with value: 0.7888558471217525 and parameters: {'layer1': 445, 'layer2': 434, 'layer3': 421, 'activation': 'relu', 'solver': 'adam', 'lr': 1.3642069216078804e-05}. Best is trial 66 with value: 0.8594929521695608.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:19:45<43:25:09, 12023.84s/it]

[I 2026-02-20 15:30:34,035] Trial 94 finished with value: 0.8578417742474184 and parameters: {'layer1': 457, 'layer2': 451, 'layer3': 410, 'activation': 'relu', 'solver': 'adam', 'lr': 3.6616464333443104e-05}. Best is trial 66 with value: 0.8594929521695608.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:20:07<43:25:09, 12023.84s/it]

[I 2026-02-20 15:30:56,371] Trial 95 finished with value: 0.7888558471217525 and parameters: {'layer1': 459, 'layer2': 485, 'layer3': 430, 'activation': 'relu', 'solver': 'adam', 'lr': 1.7762461571844833e-05}. Best is trial 66 with value: 0.8594929521695608.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:20:30<43:25:09, 12023.84s/it]

[I 2026-02-20 15:31:19,431] Trial 96 finished with value: 0.7888558471217525 and parameters: {'layer1': 436, 'layer2': 446, 'layer3': 443, 'activation': 'relu', 'solver': 'adam', 'lr': 8.422560333508027e-06}. Best is trial 66 with value: 0.8594929521695608.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:21:10<43:25:09, 12023.84s/it]

[I 2026-02-20 15:31:59,017] Trial 97 finished with value: 0.7915553382288799 and parameters: {'layer1': 470, 'layer2': 458, 'layer3': 416, 'activation': 'relu', 'solver': 'sgd', 'lr': 2.9494131847710273e-05}. Best is trial 66 with value: 0.8594929521695608.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:21:33<43:25:09, 12023.84s/it]

[I 2026-02-20 15:32:22,140] Trial 98 finished with value: 0.7888558471217525 and parameters: {'layer1': 424, 'layer2': 499, 'layer3': 379, 'activation': 'relu', 'solver': 'adam', 'lr': 5.5851759549719645e-06}. Best is trial 66 with value: 0.8594929521695608.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:22:31<43:25:09, 12023.84s/it]

[I 2026-02-20 15:33:20,828] Trial 99 finished with value: 0.8556519094819534 and parameters: {'layer1': 446, 'layer2': 414, 'layer3': 465, 'activation': 'relu', 'solver': 'adam', 'lr': 4.707506045882424e-05}. Best is trial 66 with value: 0.8594929521695608.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:23:29<43:25:09, 12023.84s/it]

[I 2026-02-20 15:34:17,848] Trial 100 finished with value: 0.8528885042977434 and parameters: {'layer1': 492, 'layer2': 479, 'layer3': 409, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.2335496199258564e-05}. Best is trial 66 with value: 0.8594929521695608.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:24:42<43:25:09, 12023.84s/it]

[I 2026-02-20 15:35:31,568] Trial 101 finished with value: 0.8587797243615608 and parameters: {'layer1': 477, 'layer2': 429, 'layer3': 447, 'activation': 'relu', 'solver': 'adam', 'lr': 3.9576244419048994e-05}. Best is trial 66 with value: 0.8594929521695608.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:25:31<43:25:09, 12023.84s/it]

[I 2026-02-20 15:36:20,272] Trial 102 finished with value: 0.8552065833108987 and parameters: {'layer1': 459, 'layer2': 431, 'layer3': 449, 'activation': 'relu', 'solver': 'adam', 'lr': 7.953698950527316e-05}. Best is trial 66 with value: 0.8594929521695608.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:26:32<43:25:09, 12023.84s/it]

[I 2026-02-20 15:37:21,015] Trial 103 finished with value: 0.8558179918624702 and parameters: {'layer1': 470, 'layer2': 452, 'layer3': 490, 'activation': 'relu', 'solver': 'adam', 'lr': 3.572052539560334e-05}. Best is trial 66 with value: 0.8594929521695608.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:27:45<43:25:09, 12023.84s/it]

[I 2026-02-20 15:38:34,106] Trial 104 finished with value: 0.8558434824876311 and parameters: {'layer1': 490, 'layer2': 441, 'layer3': 432, 'activation': 'relu', 'solver': 'adam', 'lr': 3.995822167785994e-05}. Best is trial 66 with value: 0.8594929521695608.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:28:52<43:25:09, 12023.84s/it]

[I 2026-02-20 15:39:41,563] Trial 105 finished with value: 0.8586606555019918 and parameters: {'layer1': 437, 'layer2': 473, 'layer3': 447, 'activation': 'relu', 'solver': 'adam', 'lr': 2.8634336814290465e-05}. Best is trial 66 with value: 0.8594929521695608.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:29:56<43:25:09, 12023.84s/it]

[I 2026-02-20 15:40:45,788] Trial 106 finished with value: 0.8578923846225927 and parameters: {'layer1': 413, 'layer2': 471, 'layer3': 445, 'activation': 'relu', 'solver': 'adam', 'lr': 2.612755631896532e-05}. Best is trial 66 with value: 0.8594929521695608.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:30:20<43:25:09, 12023.84s/it]

[I 2026-02-20 15:41:09,148] Trial 107 finished with value: 0.7888558471217525 and parameters: {'layer1': 433, 'layer2': 470, 'layer3': 474, 'activation': 'logistic', 'solver': 'adam', 'lr': 2.4821473150123944e-05}. Best is trial 66 with value: 0.8594929521695608.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:30:42<43:25:09, 12023.84s/it]

[I 2026-02-20 15:41:31,710] Trial 108 finished with value: 0.7888558471217525 and parameters: {'layer1': 443, 'layer2': 460, 'layer3': 443, 'activation': 'relu', 'solver': 'adam', 'lr': 1.2210271421765909e-05}. Best is trial 66 with value: 0.8594929521695608.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:31:06<43:25:09, 12023.84s/it]

[I 2026-02-20 15:41:55,133] Trial 109 finished with value: 0.7888558471217525 and parameters: {'layer1': 413, 'layer2': 479, 'layer3': 468, 'activation': 'relu', 'solver': 'adam', 'lr': 1.8506115863879314e-05}. Best is trial 66 with value: 0.8594929521695608.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:32:46<43:25:09, 12023.84s/it]

[I 2026-02-20 15:43:35,662] Trial 110 finished with value: 0.7894228444202221 and parameters: {'layer1': 458, 'layer2': 487, 'layer3': 410, 'activation': 'relu', 'solver': 'sgd', 'lr': 6.6647731981787634e-06}. Best is trial 66 with value: 0.8594929521695608.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:33:37<43:25:09, 12023.84s/it]

[I 2026-02-20 15:44:26,792] Trial 111 finished with value: 0.8538387772968665 and parameters: {'layer1': 424, 'layer2': 473, 'layer3': 10, 'activation': 'relu', 'solver': 'adam', 'lr': 5.228048773840626e-05}. Best is trial 66 with value: 0.8594929521695608.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:34:38<43:25:09, 12023.84s/it]

[I 2026-02-20 15:45:27,201] Trial 112 finished with value: 0.8576347069170442 and parameters: {'layer1': 452, 'layer2': 447, 'layer3': 430, 'activation': 'relu', 'solver': 'adam', 'lr': 4.2976336253844264e-05}. Best is trial 66 with value: 0.8594929521695608.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:35:54<43:25:09, 12023.84s/it]

[I 2026-02-20 15:46:43,617] Trial 113 finished with value: 0.8582213147753128 and parameters: {'layer1': 474, 'layer2': 417, 'layer3': 451, 'activation': 'relu', 'solver': 'adam', 'lr': 3.0055498845777893e-05}. Best is trial 66 with value: 0.8594929521695608.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:37:06<43:25:09, 12023.84s/it]

[I 2026-02-20 15:47:55,572] Trial 114 finished with value: 0.8582282504506562 and parameters: {'layer1': 440, 'layer2': 412, 'layer3': 447, 'activation': 'relu', 'solver': 'adam', 'lr': 3.005580461497786e-05}. Best is trial 66 with value: 0.8594929521695608.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:38:12<43:25:09, 12023.84s/it]

[I 2026-02-20 15:49:01,602] Trial 115 finished with value: 0.8574399635212403 and parameters: {'layer1': 438, 'layer2': 409, 'layer3': 451, 'activation': 'relu', 'solver': 'adam', 'lr': 2.8716383745010894e-05}. Best is trial 66 with value: 0.8594929521695608.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:38:47<43:25:09, 12023.84s/it]

[I 2026-02-20 15:49:36,244] Trial 116 finished with value: 0.8153137108764881 and parameters: {'layer1': 371, 'layer2': 418, 'layer3': 488, 'activation': 'relu', 'solver': 'adam', 'lr': 2.3324262672743998e-05}. Best is trial 66 with value: 0.8594929521695608.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:39:10<43:25:09, 12023.84s/it]

[I 2026-02-20 15:49:59,632] Trial 117 finished with value: 0.7888558471217525 and parameters: {'layer1': 471, 'layer2': 392, 'layer3': 462, 'activation': 'relu', 'solver': 'adam', 'lr': 1.8594057727002752e-05}. Best is trial 66 with value: 0.8594929521695608.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:39:23<43:25:09, 12023.84s/it]

[I 2026-02-20 15:50:12,046] Trial 118 finished with value: 0.7888558471217525 and parameters: {'layer1': 57, 'layer2': 426, 'layer3': 440, 'activation': 'relu', 'solver': 'adam', 'lr': 2.7923763356131368e-05}. Best is trial 66 with value: 0.8594929521695608.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:40:13<43:25:09, 12023.84s/it]

[I 2026-02-20 15:51:02,595] Trial 119 finished with value: 0.8567756491914487 and parameters: {'layer1': 500, 'layer2': 496, 'layer3': 479, 'activation': 'relu', 'solver': 'adam', 'lr': 6.956854585439605e-05}. Best is trial 66 with value: 0.8594929521695608.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:41:12<43:25:09, 12023.84s/it]

[I 2026-02-20 15:52:01,503] Trial 120 finished with value: 0.8551146313468136 and parameters: {'layer1': 389, 'layer2': 406, 'layer3': 451, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.4217037021723597e-05}. Best is trial 66 with value: 0.8594929521695608.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:42:13<43:25:09, 12023.84s/it]

[I 2026-02-20 15:53:01,878] Trial 121 finished with value: 0.8561232833587209 and parameters: {'layer1': 460, 'layer2': 451, 'layer3': 435, 'activation': 'relu', 'solver': 'adam', 'lr': 3.0994134218886915e-05}. Best is trial 66 with value: 0.8594929521695608.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:43:02<43:25:09, 12023.84s/it]

[I 2026-02-20 15:53:51,260] Trial 122 finished with value: 0.8314997691714661 and parameters: {'layer1': 449, 'layer2': 461, 'layer3': 417, 'activation': 'relu', 'solver': 'adam', 'lr': 2.2795285630887758e-05}. Best is trial 66 with value: 0.8594929521695608.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:44:00<43:25:09, 12023.84s/it]

[I 2026-02-20 15:54:49,187] Trial 123 finished with value: 0.8601440311291931 and parameters: {'layer1': 407, 'layer2': 421, 'layer3': 472, 'activation': 'relu', 'solver': 'adam', 'lr': 3.034411697420872e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:45:11<43:25:09, 12023.84s/it]

[I 2026-02-20 15:55:59,970] Trial 124 finished with value: 0.8559377439034945 and parameters: {'layer1': 412, 'layer2': 420, 'layer3': 468, 'activation': 'relu', 'solver': 'adam', 'lr': 3.248538419270675e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:45:47<43:25:09, 12023.84s/it]

[I 2026-02-20 15:56:36,384] Trial 125 finished with value: 0.8040202105693638 and parameters: {'layer1': 426, 'layer2': 391, 'layer3': 494, 'activation': 'relu', 'solver': 'adam', 'lr': 2.0349334323184867e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:47:14<43:25:09, 12023.84s/it]

[I 2026-02-20 15:58:03,021] Trial 126 finished with value: 0.8572922743007536 and parameters: {'layer1': 439, 'layer2': 437, 'layer3': 478, 'activation': 'relu', 'solver': 'adam', 'lr': 2.61397248263885e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:48:10<43:25:09, 12023.84s/it]

[I 2026-02-20 15:58:58,850] Trial 127 finished with value: 0.8547331054313204 and parameters: {'layer1': 473, 'layer2': 381, 'layer3': 457, 'activation': 'relu', 'solver': 'adam', 'lr': 5.3611959898053586e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:48:32<43:25:09, 12023.84s/it]

[I 2026-02-20 15:59:21,661] Trial 128 finished with value: 0.7888558471217525 and parameters: {'layer1': 418, 'layer2': 425, 'layer3': 443, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.009500820724404072}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:48:56<43:25:09, 12023.84s/it]

[I 2026-02-20 15:59:45,667] Trial 129 finished with value: 0.7888558471217525 and parameters: {'layer1': 490, 'layer2': 411, 'layer3': 471, 'activation': 'relu', 'solver': 'adam', 'lr': 9.87205067940425e-06}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:49:19<43:25:09, 12023.84s/it]

[I 2026-02-20 16:00:08,679] Trial 130 finished with value: 0.7888558471217525 and parameters: {'layer1': 466, 'layer2': 468, 'layer3': 449, 'activation': 'relu', 'solver': 'adam', 'lr': 1.79870373544929e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:49:39<43:25:09, 12023.84s/it]

[I 2026-02-20 16:00:28,206] Trial 131 finished with value: 0.7888558471217525 and parameters: {'layer1': 455, 'layer2': 11, 'layer3': 428, 'activation': 'relu', 'solver': 'adam', 'lr': 3.965635577093868e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:50:39<43:25:09, 12023.84s/it]

[I 2026-02-20 16:01:28,308] Trial 132 finished with value: 0.8564429344133574 and parameters: {'layer1': 404, 'layer2': 483, 'layer3': 460, 'activation': 'relu', 'solver': 'adam', 'lr': 3.31929095205361e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:51:35<43:25:09, 12023.84s/it]

[I 2026-02-20 16:02:24,843] Trial 133 finished with value: 0.8554432684413834 and parameters: {'layer1': 444, 'layer2': 457, 'layer3': 438, 'activation': 'relu', 'solver': 'adam', 'lr': 4.315801361414306e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:52:52<43:25:09, 12023.84s/it]

[I 2026-02-20 16:03:41,054] Trial 134 finished with value: 0.8559571186965587 and parameters: {'layer1': 429, 'layer2': 441, 'layer3': 405, 'activation': 'relu', 'solver': 'adam', 'lr': 2.585605423347209e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:53:11<43:25:09, 12023.84s/it]

[I 2026-02-20 16:04:00,486] Trial 135 finished with value: 0.7888558471217525 and parameters: {'layer1': 313, 'layer2': 429, 'layer3': 418, 'activation': 'relu', 'solver': 'adam', 'lr': 1.613412041006712e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:53:51<43:25:09, 12023.84s/it]

[I 2026-02-20 16:04:40,116] Trial 136 finished with value: 0.7896910713816637 and parameters: {'layer1': 474, 'layer2': 400, 'layer3': 482, 'activation': 'relu', 'solver': 'sgd', 'lr': 5.855868357919267e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:55:05<43:25:09, 12023.84s/it]

[I 2026-02-20 16:05:54,455] Trial 137 finished with value: 0.8566371238385063 and parameters: {'layer1': 463, 'layer2': 474, 'layer3': 394, 'activation': 'relu', 'solver': 'adam', 'lr': 3.0658420514524566e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:56:17<43:25:09, 12023.84s/it]

[I 2026-02-20 16:07:06,493] Trial 138 finished with value: 0.8559403007845475 and parameters: {'layer1': 450, 'layer2': 457, 'layer3': 447, 'activation': 'relu', 'solver': 'adam', 'lr': 3.9251541347363516e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:57:38<43:25:09, 12023.84s/it]

[I 2026-02-20 16:08:27,689] Trial 139 finished with value: 0.8584892771268514 and parameters: {'layer1': 487, 'layer2': 500, 'layer3': 366, 'activation': 'relu', 'solver': 'adam', 'lr': 2.178729114282631e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:58:02<43:25:09, 12023.84s/it]

[I 2026-02-20 16:08:51,329] Trial 140 finished with value: 0.7888558471217525 and parameters: {'layer1': 486, 'layer2': 492, 'layer3': 356, 'activation': 'relu', 'solver': 'adam', 'lr': 1.3264996833891643e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:58:40<43:25:09, 12023.84s/it]

[I 2026-02-20 16:09:29,157] Trial 141 finished with value: 0.8042582391672461 and parameters: {'layer1': 478, 'layer2': 465, 'layer3': 428, 'activation': 'relu', 'solver': 'adam', 'lr': 2.081764450293114e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [4:59:41<43:25:09, 12023.84s/it]

[I 2026-02-20 16:10:29,996] Trial 142 finished with value: 0.8412142255678635 and parameters: {'layer1': 494, 'layer2': 500, 'layer3': 458, 'activation': 'relu', 'solver': 'adam', 'lr': 2.3956944515364635e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [5:00:41<43:25:09, 12023.84s/it]

[I 2026-02-20 16:11:30,587] Trial 143 finished with value: 0.8583757311990119 and parameters: {'layer1': 459, 'layer2': 479, 'layer3': 341, 'activation': 'relu', 'solver': 'adam', 'lr': 3.3003863421304365e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [5:01:55<43:25:09, 12023.84s/it]

[I 2026-02-20 16:12:44,172] Trial 144 finished with value: 0.8588457023102174 and parameters: {'layer1': 436, 'layer2': 486, 'layer3': 336, 'activation': 'relu', 'solver': 'adam', 'lr': 2.9295909768536862e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [5:02:53<43:25:09, 12023.84s/it]

[I 2026-02-20 16:13:42,381] Trial 145 finished with value: 0.8568992520352305 and parameters: {'layer1': 431, 'layer2': 478, 'layer3': 343, 'activation': 'relu', 'solver': 'adam', 'lr': 4.684758069812361e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [5:03:54<43:25:09, 12023.84s/it]

[I 2026-02-20 16:14:43,351] Trial 146 finished with value: 0.8593234420867473 and parameters: {'layer1': 441, 'layer2': 490, 'layer3': 338, 'activation': 'relu', 'solver': 'adam', 'lr': 3.106470267489928e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [5:05:00<43:25:09, 12023.84s/it]

[I 2026-02-20 16:15:49,501] Trial 147 finished with value: 0.8560875487048071 and parameters: {'layer1': 437, 'layer2': 493, 'layer3': 363, 'activation': 'relu', 'solver': 'adam', 'lr': 3.261238658631305e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [5:06:00<43:25:09, 12023.84s/it]

[I 2026-02-20 16:16:49,760] Trial 148 finished with value: 0.8528249268736934 and parameters: {'layer1': 462, 'layer2': 500, 'layer3': 333, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.735101224407383e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [5:06:54<43:25:09, 12023.84s/it]

[I 2026-02-20 16:17:43,094] Trial 149 finished with value: 0.8562997222025783 and parameters: {'layer1': 443, 'layer2': 414, 'layer3': 318, 'activation': 'relu', 'solver': 'adam', 'lr': 7.406684933219227e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [5:08:13<43:25:09, 12023.84s/it]

[I 2026-02-20 16:19:02,380] Trial 150 finished with value: 0.8587259101820752 and parameters: {'layer1': 456, 'layer2': 485, 'layer3': 301, 'activation': 'relu', 'solver': 'adam', 'lr': 3.2902827936752466e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [5:09:19<43:25:09, 12023.84s/it]

[I 2026-02-20 16:20:08,023] Trial 151 finished with value: 0.8555017250850746 and parameters: {'layer1': 453, 'layer2': 481, 'layer3': 309, 'activation': 'relu', 'solver': 'adam', 'lr': 2.9889250481302615e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [5:10:20<43:25:09, 12023.84s/it]

[I 2026-02-20 16:21:09,418] Trial 152 finished with value: 0.8551276798878884 and parameters: {'layer1': 468, 'layer2': 486, 'layer3': 299, 'activation': 'relu', 'solver': 'adam', 'lr': 4.1057370387683784e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [5:10:44<43:25:09, 12023.84s/it]

[I 2026-02-20 16:21:33,310] Trial 153 finished with value: 0.7888558471217525 and parameters: {'layer1': 485, 'layer2': 437, 'layer3': 346, 'activation': 'relu', 'solver': 'adam', 'lr': 2.091550935449182e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [5:11:52<43:25:09, 12023.84s/it]

[I 2026-02-20 16:22:41,359] Trial 154 finished with value: 0.8589993539653002 and parameters: {'layer1': 443, 'layer2': 469, 'layer3': 337, 'activation': 'relu', 'solver': 'adam', 'lr': 5.284549083417933e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [5:12:44<43:25:09, 12023.84s/it]

[I 2026-02-20 16:23:33,197] Trial 155 finished with value: 0.8562656993922074 and parameters: {'layer1': 422, 'layer2': 472, 'layer3': 338, 'activation': 'relu', 'solver': 'adam', 'lr': 5.473256971857521e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [5:13:46<43:25:09, 12023.84s/it]

[I 2026-02-20 16:24:35,730] Trial 156 finished with value: 0.8568164051375659 and parameters: {'layer1': 444, 'layer2': 490, 'layer3': 332, 'activation': 'relu', 'solver': 'adam', 'lr': 4.56985354566149e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [5:14:09<43:25:09, 12023.84s/it]

[I 2026-02-20 16:24:58,316] Trial 157 finished with value: 0.7888558471217525 and parameters: {'layer1': 433, 'layer2': 457, 'layer3': 356, 'activation': 'logistic', 'solver': 'adam', 'lr': 3.609257052227457e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [5:15:00<43:25:09, 12023.84s/it]

[I 2026-02-20 16:25:49,552] Trial 158 finished with value: 0.8562667642201507 and parameters: {'layer1': 457, 'layer2': 479, 'layer3': 324, 'activation': 'relu', 'solver': 'adam', 'lr': 6.469369451385377e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [5:15:42<43:25:09, 12023.84s/it]

[I 2026-02-20 16:26:31,514] Trial 159 finished with value: 0.6419185002069664 and parameters: {'layer1': 451, 'layer2': 465, 'layer3': 285, 'activation': 'relu', 'solver': 'sgd', 'lr': 2.723068201774414e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [5:16:25<43:25:09, 12023.84s/it]

[I 2026-02-20 16:27:14,287] Trial 160 finished with value: 0.8204593839541685 and parameters: {'layer1': 467, 'layer2': 500, 'layer3': 254, 'activation': 'relu', 'solver': 'adam', 'lr': 2.2402464870943186e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [5:17:26<43:25:09, 12023.84s/it]

[I 2026-02-20 16:28:15,649] Trial 161 finished with value: 0.8567253641640974 and parameters: {'layer1': 479, 'layer2': 447, 'layer3': 371, 'activation': 'relu', 'solver': 'adam', 'lr': 3.373425377130909e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [5:18:56<43:25:09, 12023.84s/it]

[I 2026-02-20 16:29:45,262] Trial 162 finished with value: 0.859175124116541 and parameters: {'layer1': 441, 'layer2': 423, 'layer3': 268, 'activation': 'relu', 'solver': 'adam', 'lr': 2.8983795581246858e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [5:19:53<43:25:09, 12023.84s/it]

[I 2026-02-20 16:30:42,630] Trial 163 finished with value: 0.856310678924262 and parameters: {'layer1': 438, 'layer2': 421, 'layer3': 277, 'activation': 'relu', 'solver': 'adam', 'lr': 4.6260584518059843e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [5:21:15<43:25:09, 12023.84s/it]

[I 2026-02-20 16:32:03,949] Trial 164 finished with value: 0.8596620818635529 and parameters: {'layer1': 446, 'layer2': 406, 'layer3': 295, 'activation': 'relu', 'solver': 'adam', 'lr': 2.785139305034152e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [5:22:18<43:25:09, 12023.84s/it]

[I 2026-02-20 16:33:07,373] Trial 165 finished with value: 0.8448113204940295 and parameters: {'layer1': 426, 'layer2': 401, 'layer3': 306, 'activation': 'relu', 'solver': 'adam', 'lr': 2.6614248062553957e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [5:22:40<43:25:09, 12023.84s/it]

[I 2026-02-20 16:33:29,667] Trial 166 finished with value: 0.7888558471217525 and parameters: {'layer1': 446, 'layer2': 392, 'layer3': 266, 'activation': 'relu', 'solver': 'adam', 'lr': 1.6161606639667096e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [5:23:03<43:25:09, 12023.84s/it]

[I 2026-02-20 16:33:52,298] Trial 167 finished with value: 0.7888558471217525 and parameters: {'layer1': 420, 'layer2': 410, 'layer3': 266, 'activation': 'relu', 'solver': 'adam', 'lr': 2.105610081853291e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [5:24:09<43:25:09, 12023.84s/it]

[I 2026-02-20 16:34:58,420] Trial 168 finished with value: 0.857851148850048 and parameters: {'layer1': 403, 'layer2': 431, 'layer3': 240, 'activation': 'relu', 'solver': 'adam', 'lr': 4.1138853916191004e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [5:25:15<43:25:09, 12023.84s/it]

[I 2026-02-20 16:36:03,984] Trial 169 finished with value: 0.8583673707638144 and parameters: {'layer1': 434, 'layer2': 375, 'layer3': 326, 'activation': 'relu', 'solver': 'adam', 'lr': 2.7956283585391563e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [5:26:32<43:25:09, 12023.84s/it]

[I 2026-02-20 16:37:21,172] Trial 170 finished with value: 0.8563089660869775 and parameters: {'layer1': 436, 'layer2': 382, 'layer3': 322, 'activation': 'relu', 'solver': 'adam', 'lr': 2.850955479224971e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [5:27:30<43:25:09, 12023.84s/it]

[I 2026-02-20 16:38:19,649] Trial 171 finished with value: 0.8312128431605018 and parameters: {'layer1': 453, 'layer2': 413, 'layer3': 295, 'activation': 'relu', 'solver': 'adam', 'lr': 2.4594490857851336e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [5:27:42<43:25:09, 12023.84s/it]

[I 2026-02-20 16:38:31,692] Trial 172 finished with value: 0.7888558471217525 and parameters: {'layer1': 25, 'layer2': 401, 'layer3': 344, 'activation': 'relu', 'solver': 'adam', 'lr': 3.605360888273758e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [5:28:05<43:25:09, 12023.84s/it]

[I 2026-02-20 16:38:54,335] Trial 173 finished with value: 0.7888558471217525 and parameters: {'layer1': 430, 'layer2': 418, 'layer3': 329, 'activation': 'relu', 'solver': 'adam', 'lr': 1.8659859603354577e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [5:29:12<43:25:09, 12023.84s/it]

[I 2026-02-20 16:40:01,662] Trial 174 finished with value: 0.859543514320201 and parameters: {'layer1': 444, 'layer2': 488, 'layer3': 314, 'activation': 'relu', 'solver': 'adam', 'lr': 3.1159707039070084e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [5:30:14<43:25:09, 12023.84s/it]

[I 2026-02-20 16:41:03,214] Trial 175 finished with value: 0.8568410838897517 and parameters: {'layer1': 413, 'layer2': 426, 'layer3': 314, 'activation': 'relu', 'solver': 'adam', 'lr': 2.9931671656032863e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [5:30:37<43:25:09, 12023.84s/it]

[I 2026-02-20 16:41:26,571] Trial 176 finished with value: 0.7888558471217525 and parameters: {'layer1': 447, 'layer2': 363, 'layer3': 297, 'activation': 'relu', 'solver': 'adam', 'lr': 2.2945692840327256e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [5:31:35<43:25:09, 12023.84s/it]

[I 2026-02-20 16:42:24,529] Trial 177 finished with value: 0.8570511721425277 and parameters: {'layer1': 440, 'layer2': 473, 'layer3': 350, 'activation': 'relu', 'solver': 'adam', 'lr': 3.688839624615634e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [5:32:55<43:25:09, 12023.84s/it]

[I 2026-02-20 16:43:43,952] Trial 178 finished with value: 0.8587405783636886 and parameters: {'layer1': 461, 'layer2': 373, 'layer3': 288, 'activation': 'relu', 'solver': 'adam', 'lr': 2.919143186961231e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [5:33:58<43:25:09, 12023.84s/it]

[I 2026-02-20 16:44:47,821] Trial 179 finished with value: 0.8566970590776168 and parameters: {'layer1': 460, 'layer2': 370, 'layer3': 286, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.967031942200703e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [5:34:54<43:25:09, 12023.84s/it]

[I 2026-02-20 16:45:43,739] Trial 180 finished with value: 0.8431921051271056 and parameters: {'layer1': 422, 'layer2': 356, 'layer3': 311, 'activation': 'relu', 'solver': 'adam', 'lr': 2.5873731009113716e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [5:36:08<43:25:09, 12023.84s/it]

[I 2026-02-20 16:46:57,741] Trial 181 finished with value: 0.8576421466383636 and parameters: {'layer1': 456, 'layer2': 392, 'layer3': 267, 'activation': 'relu', 'solver': 'adam', 'lr': 3.04198587956177e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [5:37:07<43:25:09, 12023.84s/it]

[I 2026-02-20 16:47:56,421] Trial 182 finished with value: 0.8544493228044521 and parameters: {'layer1': 444, 'layer2': 489, 'layer3': 334, 'activation': 'relu', 'solver': 'adam', 'lr': 3.302207526687686e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [5:37:41<43:25:09, 12023.84s/it]

[I 2026-02-20 16:48:30,074] Trial 183 finished with value: 0.8004892289682282 and parameters: {'layer1': 429, 'layer2': 406, 'layer3': 299, 'activation': 'relu', 'solver': 'adam', 'lr': 2.3954662646364468e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [5:38:36<43:25:09, 12023.84s/it]

[I 2026-02-20 16:49:25,415] Trial 184 finished with value: 0.8565201424004067 and parameters: {'layer1': 464, 'layer2': 480, 'layer3': 364, 'activation': 'relu', 'solver': 'adam', 'lr': 4.092729712042862e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [5:38:59<43:25:09, 12023.84s/it]

[I 2026-02-20 16:49:48,638] Trial 185 finished with value: 0.7888558471217525 and parameters: {'layer1': 447, 'layer2': 376, 'layer3': 326, 'activation': 'relu', 'solver': 'adam', 'lr': 1.5914145794452215e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [5:40:01<43:25:09, 12023.84s/it]

[I 2026-02-20 16:50:50,386] Trial 186 finished with value: 0.8545221545930668 and parameters: {'layer1': 456, 'layer2': 388, 'layer3': 290, 'activation': 'relu', 'solver': 'adam', 'lr': 2.9263981208011594e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [5:40:59<43:25:09, 12023.84s/it]

[I 2026-02-20 16:51:48,654] Trial 187 finished with value: 0.8572167782227051 and parameters: {'layer1': 437, 'layer2': 421, 'layer3': 307, 'activation': 'relu', 'solver': 'adam', 'lr': 5.1632734499606315e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [5:41:35<43:25:09, 12023.84s/it]

[I 2026-02-20 16:52:24,728] Trial 188 finished with value: 0.8043489381548585 and parameters: {'layer1': 472, 'layer2': 333, 'layer3': 343, 'activation': 'relu', 'solver': 'adam', 'lr': 2.1272288836320742e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [5:41:53<43:25:09, 12023.84s/it]

[I 2026-02-20 16:52:42,792] Trial 189 finished with value: 0.638231501939184 and parameters: {'layer1': 432, 'layer2': 465, 'layer3': 318, 'activation': 'logistic', 'solver': 'sgd', 'lr': 3.6916401138970826e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [5:43:03<43:25:09, 12023.84s/it]

[I 2026-02-20 16:53:52,672] Trial 190 finished with value: 0.8567378342879763 and parameters: {'layer1': 394, 'layer2': 399, 'layer3': 380, 'activation': 'relu', 'solver': 'adam', 'lr': 2.9256809313648334e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [5:43:59<43:25:09, 12023.84s/it]

[I 2026-02-20 16:54:48,402] Trial 191 finished with value: 0.8564695948744921 and parameters: {'layer1': 474, 'layer2': 497, 'layer3': 356, 'activation': 'relu', 'solver': 'adam', 'lr': 4.7696629206998426e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [5:44:52<43:25:09, 12023.84s/it]

[I 2026-02-20 16:55:41,552] Trial 192 finished with value: 0.8564714014172384 and parameters: {'layer1': 461, 'layer2': 485, 'layer3': 281, 'activation': 'relu', 'solver': 'adam', 'lr': 5.714026341057199e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [5:45:48<43:25:09, 12023.84s/it]

[I 2026-02-20 16:56:37,616] Trial 193 finished with value: 0.8565216935291413 and parameters: {'layer1': 448, 'layer2': 488, 'layer3': 338, 'activation': 'relu', 'solver': 'adam', 'lr': 4.220011952008618e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [5:47:06<43:25:09, 12023.84s/it]

[I 2026-02-20 16:57:55,367] Trial 194 finished with value: 0.8565673222619161 and parameters: {'layer1': 487, 'layer2': 479, 'layer3': 270, 'activation': 'relu', 'solver': 'adam', 'lr': 2.5183266269055144e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [5:48:14<43:25:09, 12023.84s/it]

[I 2026-02-20 16:59:03,177] Trial 195 finished with value: 0.8575415666114623 and parameters: {'layer1': 467, 'layer2': 432, 'layer3': 324, 'activation': 'relu', 'solver': 'adam', 'lr': 3.335874452306353e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [5:49:10<43:25:09, 12023.84s/it]

[I 2026-02-20 16:59:59,499] Trial 196 finished with value: 0.8573798570260696 and parameters: {'layer1': 453, 'layer2': 491, 'layer3': 304, 'activation': 'relu', 'solver': 'adam', 'lr': 3.714736023896164e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [5:49:34<43:25:09, 12023.84s/it]

[I 2026-02-20 17:00:23,035] Trial 197 finished with value: 0.7888558471217525 and parameters: {'layer1': 476, 'layer2': 470, 'layer3': 348, 'activation': 'relu', 'solver': 'adam', 'lr': 1.8453008209220986e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):   7%|▋         | 1/14 [5:50:47<43:25:09, 12023.84s/it]

[I 2026-02-20 17:01:36,154] Trial 198 finished with value: 0.8559519865935709 and parameters: {'layer1': 440, 'layer2': 450, 'layer3': 335, 'activation': 'relu', 'solver': 'adam', 'lr': 2.7775630248267577e-05}. Best is trial 123 with value: 0.8601440311291931.

Best trial: 123. Best value: 0.860144: 100%|██████████| 200/200 [2:31:21<00:00, 45.41s/it]

[I 2026-02-20 17:02:34,662] Trial 199 finished with value: 0.8561499540266944 and parameters: {'layer1': 415, 'layer2': 407, 'layer3': 318, 'activation': 'relu', 'solver': 'adam', 'lr': 4.691153375948755e-05}. Best is trial 123 with value: 0.8601440311291931.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [5:51:47<34:18:50, 10294.22s/it][I 2026-02-20 17:02:36,171] A new study created in memory with name: no-name-e65adaa2-a04f-44ed-95ca-7a864979300e

  → Best model saved.

[Exact Paper MLP] Staphylococcus_Aureus | Fusidic acid

Training Exact MLP (Paper):  14%|█▍        | 2/14 [5:52:09<34:18:50, 10294.22s/it]

[I 2026-02-20 17:02:58,148] Trial 0 finished with value: 0.9050666137971211 and parameters: {'layer1': 428, 'layer2': 323, 'layer3': 328, 'activation': 'logistic', 'solver': 'adam', 'lr': 3.381078444185878e-05}. Best is trial 0 with value: 0.9050666137971211.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [5:52:19<34:18:50, 10294.22s/it]

[I 2026-02-20 17:03:08,377] Trial 1 finished with value: 0.9050666137971211 and parameters: {'layer1': 95, 'layer2': 328, 'layer3': 420, 'activation': 'logistic', 'solver': 'sgd', 'lr': 0.0008867606657705861}. Best is trial 0 with value: 0.9050666137971211.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [5:52:34<34:18:50, 10294.22s/it]

[I 2026-02-20 17:03:23,323] Trial 2 finished with value: 0.9050666137971211 and parameters: {'layer1': 125, 'layer2': 314, 'layer3': 309, 'activation': 'relu', 'solver': 'adam', 'lr': 5.692284596790387e-06}. Best is trial 0 with value: 0.9050666137971211.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [5:52:49<34:18:50, 10294.22s/it]

[I 2026-02-20 17:03:38,755] Trial 3 finished with value: 0.36710146943692323 and parameters: {'layer1': 431, 'layer2': 40, 'layer3': 270, 'activation': 'logistic', 'solver': 'sgd', 'lr': 7.890593962930276e-06}. Best is trial 0 with value: 0.9050666137971211.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [5:53:26<34:18:50, 10294.22s/it]

[I 2026-02-20 17:04:14,980] Trial 4 finished with value: 0.9252655573889687 and parameters: {'layer1': 378, 'layer2': 83, 'layer3': 333, 'activation': 'tanh', 'solver': 'adam', 'lr': 9.099475696594391e-05}. Best is trial 4 with value: 0.9252655573889687.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [5:53:52<34:18:50, 10294.22s/it]

[I 2026-02-20 17:04:40,890] Trial 5 finished with value: 0.9255850545245039 and parameters: {'layer1': 181, 'layer2': 484, 'layer3': 103, 'activation': 'identity', 'solver': 'adam', 'lr': 0.00010183459068399668}. Best is trial 5 with value: 0.9255850545245039.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [5:54:09<34:18:50, 10294.22s/it]

[I 2026-02-20 17:04:58,481] Trial 6 finished with value: 0.9050666137971211 and parameters: {'layer1': 475, 'layer2': 452, 'layer3': 338, 'activation': 'logistic', 'solver': 'sgd', 'lr': 0.0006221417496901342}. Best is trial 5 with value: 0.9255850545245039.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [5:54:27<34:18:50, 10294.22s/it]

[I 2026-02-20 17:05:16,741] Trial 7 finished with value: 0.905915203115432 and parameters: {'layer1': 457, 'layer2': 147, 'layer3': 455, 'activation': 'relu', 'solver': 'sgd', 'lr': 0.00010738224969811262}. Best is trial 5 with value: 0.9255850545245039.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [5:54:53<34:18:50, 10294.22s/it]

[I 2026-02-20 17:05:42,745] Trial 8 finished with value: 0.9088048743542135 and parameters: {'layer1': 368, 'layer2': 283, 'layer3': 48, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0021743552165108845}. Best is trial 5 with value: 0.9255850545245039.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [5:55:05<34:18:50, 10294.22s/it]

[I 2026-02-20 17:05:54,053] Trial 9 finished with value: 0.9050666137971211 and parameters: {'layer1': 126, 'layer2': 217, 'layer3': 328, 'activation': 'relu', 'solver': 'sgd', 'lr': 0.0007947586094759944}. Best is trial 5 with value: 0.9255850545245039.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [5:55:31<34:18:50, 10294.22s/it]

[I 2026-02-20 17:06:20,251] Trial 10 finished with value: 0.9259902225271152 and parameters: {'layer1': 233, 'layer2': 499, 'layer3': 113, 'activation': 'identity', 'solver': 'adam', 'lr': 0.008190894216037123}. Best is trial 10 with value: 0.9259902225271152.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [5:56:03<34:18:50, 10294.22s/it]

[I 2026-02-20 17:06:52,562] Trial 11 finished with value: 0.9269187180327311 and parameters: {'layer1': 244, 'layer2': 500, 'layer3': 103, 'activation': 'identity', 'solver': 'adam', 'lr': 0.005851041313593952}. Best is trial 11 with value: 0.9269187180327311.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [5:56:33<34:18:50, 10294.22s/it]

[I 2026-02-20 17:07:22,693] Trial 12 finished with value: 0.9258893211869109 and parameters: {'layer1': 260, 'layer2': 402, 'layer3': 173, 'activation': 'identity', 'solver': 'adam', 'lr': 0.008139293616529085}. Best is trial 11 with value: 0.9269187180327311.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [5:57:02<34:18:50, 10294.22s/it]

[I 2026-02-20 17:07:51,721] Trial 13 finished with value: 0.9264139290338026 and parameters: {'layer1': 264, 'layer2': 413, 'layer3': 159, 'activation': 'identity', 'solver': 'adam', 'lr': 0.009145633444453677}. Best is trial 11 with value: 0.9269187180327311.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [5:57:32<34:18:50, 10294.22s/it]

[I 2026-02-20 17:08:20,878] Trial 14 finished with value: 0.9266180265241701 and parameters: {'layer1': 306, 'layer2': 405, 'layer3': 197, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0026425250907384287}. Best is trial 11 with value: 0.9269187180327311.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [5:58:05<34:18:50, 10294.22s/it]

[I 2026-02-20 17:08:54,420] Trial 15 finished with value: 0.9230287130376414 and parameters: {'layer1': 333, 'layer2': 400, 'layer3': 211, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0019203281877722624}. Best is trial 11 with value: 0.9269187180327311.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [5:58:22<34:18:50, 10294.22s/it]

[I 2026-02-20 17:09:10,987] Trial 16 finished with value: 0.9248269544083547 and parameters: {'layer1': 33, 'layer2': 222, 'layer3': 20, 'activation': 'identity', 'solver': 'adam', 'lr': 0.002871276952022924}. Best is trial 11 with value: 0.9269187180327311.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [5:58:52<34:18:50, 10294.22s/it]

[I 2026-02-20 17:09:40,942] Trial 17 finished with value: 0.9249328606763279 and parameters: {'layer1': 328, 'layer2': 376, 'layer3': 105, 'activation': 'identity', 'solver': 'adam', 'lr': 0.00033260195537227003}. Best is trial 11 with value: 0.9269187180327311.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [5:59:08<34:18:50, 10294.22s/it]

[I 2026-02-20 17:09:57,296] Trial 18 finished with value: 0.9050666137971211 and parameters: {'layer1': 203, 'layer2': 450, 'layer3': 223, 'activation': 'identity', 'solver': 'adam', 'lr': 1.1896215555992228e-06}. Best is trial 11 with value: 0.9269187180327311.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [5:59:27<34:18:50, 10294.22s/it]

[I 2026-02-20 17:10:16,610] Trial 19 finished with value: 0.9050666137971211 and parameters: {'layer1': 295, 'layer2': 364, 'layer3': 67, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0036983544627398435}. Best is trial 11 with value: 0.9269187180327311.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [5:59:57<34:18:50, 10294.22s/it]

[I 2026-02-20 17:10:45,891] Trial 20 finished with value: 0.925376921457465 and parameters: {'layer1': 306, 'layer2': 458, 'layer3': 155, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0001708798097017605}. Best is trial 11 with value: 0.9269187180327311.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:00:27<34:18:50, 10294.22s/it]

[I 2026-02-20 17:11:16,324] Trial 21 finished with value: 0.9279611077474481 and parameters: {'layer1': 264, 'layer2': 426, 'layer3': 161, 'activation': 'identity', 'solver': 'adam', 'lr': 0.007277742384442971}. Best is trial 21 with value: 0.9279611077474481.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:00:54<34:18:50, 10294.22s/it]

[I 2026-02-20 17:11:43,293] Trial 22 finished with value: 0.9265391433634133 and parameters: {'layer1': 194, 'layer2': 427, 'layer3': 203, 'activation': 'identity', 'solver': 'adam', 'lr': 0.004036824044536322}. Best is trial 21 with value: 0.9279611077474481.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:01:21<34:18:50, 10294.22s/it]

[I 2026-02-20 17:12:10,271] Trial 23 finished with value: 0.9248046808269159 and parameters: {'layer1': 230, 'layer2': 498, 'layer3': 262, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0017540506952706534}. Best is trial 21 with value: 0.9279611077474481.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:01:52<34:18:50, 10294.22s/it]

[I 2026-02-20 17:12:41,706] Trial 24 finished with value: 0.9227551900156982 and parameters: {'layer1': 369, 'layer2': 448, 'layer3': 134, 'activation': 'identity', 'solver': 'adam', 'lr': 0.005080938978179305}. Best is trial 21 with value: 0.9279611077474481.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:02:20<34:18:50, 10294.22s/it]

[I 2026-02-20 17:13:09,090] Trial 25 finished with value: 0.923639555245256 and parameters: {'layer1': 284, 'layer2': 358, 'layer3': 76, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0011922788719763427}. Best is trial 21 with value: 0.9279611077474481.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:02:31<34:18:50, 10294.22s/it]

[I 2026-02-20 17:13:20,211] Trial 26 finished with value: 0.9057221147930286 and parameters: {'layer1': 168, 'layer2': 228, 'layer3': 184, 'activation': 'identity', 'solver': 'sgd', 'lr': 0.0002471011305894815}. Best is trial 21 with value: 0.9279611077474481.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:02:58<34:18:50, 10294.22s/it]

[I 2026-02-20 17:13:47,222] Trial 27 finished with value: 0.9240686085358506 and parameters: {'layer1': 234, 'layer2': 268, 'layer3': 13, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0004955349951478989}. Best is trial 21 with value: 0.9279611077474481.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:03:17<34:18:50, 10294.22s/it]

[I 2026-02-20 17:14:05,996] Trial 28 finished with value: 0.9050666137971211 and parameters: {'layer1': 333, 'layer2': 150, 'layer3': 240, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.005111226540782299}. Best is trial 21 with value: 0.9279611077474481.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:03:39<34:18:50, 10294.22s/it]

[I 2026-02-20 17:14:28,583] Trial 29 finished with value: 0.9050666137971211 and parameters: {'layer1': 395, 'layer2': 327, 'layer3': 144, 'activation': 'logistic', 'solver': 'adam', 'lr': 2.6154285330042268e-05}. Best is trial 21 with value: 0.9279611077474481.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:03:59<34:18:50, 10294.22s/it]

[I 2026-02-20 17:14:47,915] Trial 30 finished with value: 0.9235284735112949 and parameters: {'layer1': 142, 'layer2': 379, 'layer3': 299, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0012823798641531064}. Best is trial 21 with value: 0.9279611077474481.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:04:28<34:18:50, 10294.22s/it]

[I 2026-02-20 17:15:17,399] Trial 31 finished with value: 0.926838748067882 and parameters: {'layer1': 207, 'layer2': 425, 'layer3': 210, 'activation': 'identity', 'solver': 'adam', 'lr': 0.00398543111244953}. Best is trial 21 with value: 0.9279611077474481.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:04:57<34:18:50, 10294.22s/it]

[I 2026-02-20 17:15:46,104] Trial 32 finished with value: 0.9231901484651116 and parameters: {'layer1': 230, 'layer2': 469, 'layer3': 384, 'activation': 'identity', 'solver': 'adam', 'lr': 0.009626387942361751}. Best is trial 21 with value: 0.9279611077474481.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:05:27<34:18:50, 10294.22s/it]

[I 2026-02-20 17:16:16,607] Trial 33 finished with value: 0.9258655954514872 and parameters: {'layer1': 274, 'layer2': 421, 'layer3': 190, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0026769623457949194}. Best is trial 21 with value: 0.9279611077474481.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:05:38<34:18:50, 10294.22s/it]

[I 2026-02-20 17:16:27,671] Trial 34 finished with value: 0.9050666137971211 and parameters: {'layer1': 85, 'layer2': 346, 'layer3': 238, 'activation': 'logistic', 'solver': 'sgd', 'lr': 0.0051387946668338055}. Best is trial 21 with value: 0.9279611077474481.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:06:04<34:18:50, 10294.22s/it]

[I 2026-02-20 17:16:52,921] Trial 35 finished with value: 0.9226473851120197 and parameters: {'layer1': 208, 'layer2': 292, 'layer3': 270, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0012628122867328452}. Best is trial 21 with value: 0.9279611077474481.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:06:23<34:18:50, 10294.22s/it]

[I 2026-02-20 17:17:12,280] Trial 36 finished with value: 0.9050666137971211 and parameters: {'layer1': 301, 'layer2': 439, 'layer3': 124, 'activation': 'relu', 'solver': 'adam', 'lr': 2.3367610769407636e-05}. Best is trial 21 with value: 0.9279611077474481.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:06:48<34:18:50, 10294.22s/it]

[I 2026-02-20 17:17:37,043] Trial 37 finished with value: 0.9239720403312075 and parameters: {'layer1': 160, 'layer2': 389, 'layer3': 88, 'activation': 'identity', 'solver': 'adam', 'lr': 0.005276609252451257}. Best is trial 21 with value: 0.9279611077474481.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:06:59<34:18:50, 10294.22s/it]

[I 2026-02-20 17:17:48,489] Trial 38 finished with value: 0.9050666137971211 and parameters: {'layer1': 91, 'layer2': 479, 'layer3': 175, 'activation': 'logistic', 'solver': 'sgd', 'lr': 0.0004884919607518572}. Best is trial 21 with value: 0.9279611077474481.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:07:17<34:18:50, 10294.22s/it]

[I 2026-02-20 17:18:06,340] Trial 39 finished with value: 0.9050666137971211 and parameters: {'layer1': 255, 'layer2': 313, 'layer3': 56, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.0814890135290193e-05}. Best is trial 21 with value: 0.9279611077474481.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:07:40<34:18:50, 10294.22s/it]

[I 2026-02-20 17:18:29,229] Trial 40 finished with value: 0.905915203115432 and parameters: {'layer1': 409, 'layer2': 473, 'layer3': 288, 'activation': 'identity', 'solver': 'sgd', 'lr': 6.027775662041723e-05}. Best is trial 21 with value: 0.9279611077474481.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:08:06<34:18:50, 10294.22s/it]

[I 2026-02-20 17:18:54,882] Trial 41 finished with value: 0.9282542404217089 and parameters: {'layer1': 202, 'layer2': 429, 'layer3': 219, 'activation': 'identity', 'solver': 'adam', 'lr': 0.004088522347558321}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:08:33<34:18:50, 10294.22s/it]

[I 2026-02-20 17:19:22,818] Trial 42 finished with value: 0.9233549254420493 and parameters: {'layer1': 181, 'layer2': 431, 'layer3': 228, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0029377291773164086}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:08:59<34:18:50, 10294.22s/it]

[I 2026-02-20 17:19:48,018] Trial 43 finished with value: 0.927127947674645 and parameters: {'layer1': 217, 'layer2': 346, 'layer3': 206, 'activation': 'identity', 'solver': 'adam', 'lr': 0.001761006668838619}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:09:22<34:18:50, 10294.22s/it]

[I 2026-02-20 17:20:11,155] Trial 44 finished with value: 0.9247763820122692 and parameters: {'layer1': 209, 'layer2': 12, 'layer3': 497, 'activation': 'identity', 'solver': 'adam', 'lr': 0.006319866656927802}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:09:43<34:18:50, 10294.22s/it]

[I 2026-02-20 17:20:32,492] Trial 45 finished with value: 0.9262247125632296 and parameters: {'layer1': 136, 'layer2': 338, 'layer3': 159, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0009262312693368617}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:10:11<34:18:50, 10294.22s/it]

[I 2026-02-20 17:21:00,426] Trial 46 finished with value: 0.9247840472727346 and parameters: {'layer1': 249, 'layer2': 498, 'layer3': 356, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0016513704936103007}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:10:36<34:18:50, 10294.22s/it]

[I 2026-02-20 17:21:25,185] Trial 47 finished with value: 0.9274022450378647 and parameters: {'layer1': 158, 'layer2': 308, 'layer3': 242, 'activation': 'identity', 'solver': 'adam', 'lr': 0.006642314049878981}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:10:50<34:18:50, 10294.22s/it]

[I 2026-02-20 17:21:39,704] Trial 48 finished with value: 0.9050666137971211 and parameters: {'layer1': 105, 'layer2': 309, 'layer3': 281, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0076508722937980445}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:11:01<34:18:50, 10294.22s/it]

[I 2026-02-20 17:21:50,002] Trial 49 finished with value: 0.9050666137971211 and parameters: {'layer1': 52, 'layer2': 257, 'layer3': 253, 'activation': 'identity', 'solver': 'sgd', 'lr': 0.0007774856828315859}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:11:15<34:18:50, 10294.22s/it]

[I 2026-02-20 17:22:04,243] Trial 50 finished with value: 0.9050666137971211 and parameters: {'layer1': 154, 'layer2': 157, 'layer3': 95, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.009772866289723129}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:11:41<34:18:50, 10294.22s/it]

[I 2026-02-20 17:22:30,243] Trial 51 finished with value: 0.9246037595909332 and parameters: {'layer1': 180, 'layer2': 396, 'layer3': 211, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0034242159306025217}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:12:08<34:18:50, 10294.22s/it]

[I 2026-02-20 17:22:57,562] Trial 52 finished with value: 0.9249713233107993 and parameters: {'layer1': 229, 'layer2': 359, 'layer3': 165, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0020919377735845435}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:12:29<34:18:50, 10294.22s/it]

[I 2026-02-20 17:23:18,385] Trial 53 finished with value: 0.9276509706319533 and parameters: {'layer1': 112, 'layer2': 294, 'layer3': 218, 'activation': 'identity', 'solver': 'adam', 'lr': 0.004141255192545733}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:12:50<34:18:50, 10294.22s/it]

[I 2026-02-20 17:23:38,851] Trial 54 finished with value: 0.9259459881407999 and parameters: {'layer1': 66, 'layer2': 283, 'layer3': 251, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0066233651246850045}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:13:09<34:18:50, 10294.22s/it]

[I 2026-02-20 17:23:58,378] Trial 55 finished with value: 0.9224115359917151 and parameters: {'layer1': 103, 'layer2': 240, 'layer3': 119, 'activation': 'identity', 'solver': 'adam', 'lr': 0.004057720590357701}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:13:32<34:18:50, 10294.22s/it]

[I 2026-02-20 17:24:20,971] Trial 56 finished with value: 0.9050666137971211 and parameters: {'layer1': 496, 'layer2': 306, 'layer3': 321, 'activation': 'identity', 'solver': 'adam', 'lr': 2.4050596236253435e-06}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:13:53<34:18:50, 10294.22s/it]

[I 2026-02-20 17:24:42,029] Trial 57 finished with value: 0.9271697164493515 and parameters: {'layer1': 122, 'layer2': 333, 'layer3': 144, 'activation': 'identity', 'solver': 'adam', 'lr': 0.002529313804363771}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:14:12<34:18:50, 10294.22s/it]

[I 2026-02-20 17:25:00,932] Trial 58 finished with value: 0.9250746859060819 and parameters: {'layer1': 127, 'layer2': 338, 'layer3': 140, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0022462554553341987}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:14:34<34:18:50, 10294.22s/it]

[I 2026-02-20 17:25:23,810] Trial 59 finished with value: 0.9244518141365466 and parameters: {'layer1': 110, 'layer2': 192, 'layer3': 182, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0016996294641528395}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:14:51<34:18:50, 10294.22s/it]

[I 2026-02-20 17:25:40,503] Trial 60 finished with value: 0.9262721514260438 and parameters: {'layer1': 10, 'layer2': 293, 'layer3': 225, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0031929890692306206}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:15:15<34:18:50, 10294.22s/it]

[I 2026-02-20 17:26:04,434] Trial 61 finished with value: 0.9274769198122803 and parameters: {'layer1': 148, 'layer2': 269, 'layer3': 191, 'activation': 'identity', 'solver': 'adam', 'lr': 0.007222061215927641}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:15:35<34:18:50, 10294.22s/it]

[I 2026-02-20 17:26:24,297] Trial 62 finished with value: 0.9233726675773797 and parameters: {'layer1': 118, 'layer2': 269, 'layer3': 202, 'activation': 'identity', 'solver': 'adam', 'lr': 0.00615740336202975}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:15:59<34:18:50, 10294.22s/it]

[I 2026-02-20 17:26:48,252] Trial 63 finished with value: 0.9252630357441156 and parameters: {'layer1': 152, 'layer2': 375, 'layer3': 189, 'activation': 'identity', 'solver': 'adam', 'lr': 0.004500274772843628}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:16:20<34:18:50, 10294.22s/it]

[I 2026-02-20 17:27:09,641] Trial 64 finished with value: 0.926362698078524 and parameters: {'layer1': 173, 'layer2': 199, 'layer3': 146, 'activation': 'identity', 'solver': 'adam', 'lr': 0.007652833579272755}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:16:48<34:18:50, 10294.22s/it]

[I 2026-02-20 17:27:37,328] Trial 65 finished with value: 0.9235794687660027 and parameters: {'layer1': 196, 'layer2': 238, 'layer3': 221, 'activation': 'identity', 'solver': 'adam', 'lr': 0.002460111308306037}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:17:11<34:18:50, 10294.22s/it]

[I 2026-02-20 17:28:00,367] Trial 66 finished with value: 0.9252460675093828 and parameters: {'layer1': 145, 'layer2': 323, 'layer3': 248, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0034345676299699086}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:17:22<34:18:50, 10294.22s/it]

[I 2026-02-20 17:28:11,522] Trial 67 finished with value: 0.9050666137971211 and parameters: {'layer1': 126, 'layer2': 264, 'layer3': 173, 'activation': 'tanh', 'solver': 'sgd', 'lr': 0.001479946590864189}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:17:47<34:18:50, 10294.22s/it]

[I 2026-02-20 17:28:36,258] Trial 68 finished with value: 0.925719792770963 and parameters: {'layer1': 219, 'layer2': 348, 'layer3': 263, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0009685246423442534}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:18:10<34:18:50, 10294.22s/it]

[I 2026-02-20 17:28:58,886] Trial 69 finished with value: 0.9272145696323635 and parameters: {'layer1': 187, 'layer2': 300, 'layer3': 231, 'activation': 'identity', 'solver': 'adam', 'lr': 0.009505659138043167}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:18:35<34:18:50, 10294.22s/it]

[I 2026-02-20 17:29:24,022] Trial 70 finished with value: 0.9242387118024247 and parameters: {'layer1': 137, 'layer2': 295, 'layer3': 279, 'activation': 'identity', 'solver': 'adam', 'lr': 0.00790302707541934}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:19:04<34:18:50, 10294.22s/it]

[I 2026-02-20 17:29:53,311] Trial 71 finished with value: 0.9273739444018959 and parameters: {'layer1': 190, 'layer2': 278, 'layer3': 235, 'activation': 'identity', 'solver': 'adam', 'lr': 0.006067013261884579}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:19:27<34:18:50, 10294.22s/it]

[I 2026-02-20 17:30:16,407] Trial 72 finished with value: 0.9243044072115051 and parameters: {'layer1': 169, 'layer2': 277, 'layer3': 225, 'activation': 'identity', 'solver': 'adam', 'lr': 0.00951288268144074}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:19:50<34:18:50, 10294.22s/it]

[I 2026-02-20 17:30:39,227] Trial 73 finished with value: 0.9259299285231988 and parameters: {'layer1': 191, 'layer2': 205, 'layer3': 234, 'activation': 'identity', 'solver': 'adam', 'lr': 0.006063563918428349}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:20:08<34:18:50, 10294.22s/it]

[I 2026-02-20 17:30:57,127] Trial 74 finished with value: 0.9242609879463426 and parameters: {'layer1': 79, 'layer2': 244, 'layer3': 193, 'activation': 'identity', 'solver': 'adam', 'lr': 0.004772560976685815}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:20:26<34:18:50, 10294.22s/it]

[I 2026-02-20 17:31:15,279] Trial 75 finished with value: 0.9050666137971211 and parameters: {'layer1': 267, 'layer2': 104, 'layer3': 243, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.007047466009660837}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:20:45<34:18:50, 10294.22s/it]

[I 2026-02-20 17:31:34,427] Trial 76 finished with value: 0.9259171313466078 and parameters: {'layer1': 158, 'layer2': 297, 'layer3': 156, 'activation': 'identity', 'solver': 'adam', 'lr': 0.004090247761544806}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:21:07<34:18:50, 10294.22s/it]

[I 2026-02-20 17:31:56,656] Trial 77 finished with value: 0.9257977191397725 and parameters: {'layer1': 196, 'layer2': 250, 'layer3': 301, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0027599857034620876}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:21:38<34:18:50, 10294.22s/it]

[I 2026-02-20 17:32:27,488] Trial 78 finished with value: 0.9261792189179641 and parameters: {'layer1': 180, 'layer2': 319, 'layer3': 216, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0052705649061714635}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:21:51<34:18:50, 10294.22s/it]

[I 2026-02-20 17:32:40,695] Trial 79 finished with value: 0.9050666137971211 and parameters: {'layer1': 317, 'layer2': 413, 'layer3': 133, 'activation': 'identity', 'solver': 'sgd', 'lr': 0.00969164904825867}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:22:10<34:18:50, 10294.22s/it]

[I 2026-02-20 17:32:58,995] Trial 80 finished with value: 0.9247606641245321 and parameters: {'layer1': 117, 'layer2': 278, 'layer3': 172, 'activation': 'identity', 'solver': 'adam', 'lr': 0.006994821988736827}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:22:34<34:18:50, 10294.22s/it]

[I 2026-02-20 17:33:23,562] Trial 81 finished with value: 0.924166062235671 and parameters: {'layer1': 214, 'layer2': 328, 'layer3': 200, 'activation': 'identity', 'solver': 'adam', 'lr': 0.00352300843285926}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:23:05<34:18:50, 10294.22s/it]

[I 2026-02-20 17:33:54,527] Trial 82 finished with value: 0.9252870033685754 and parameters: {'layer1': 285, 'layer2': 371, 'layer3': 263, 'activation': 'identity', 'solver': 'adam', 'lr': 0.004657199270539376}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:23:29<34:18:50, 10294.22s/it]

[I 2026-02-20 17:34:18,460] Trial 83 finished with value: 0.928038016834021 and parameters: {'layer1': 240, 'layer2': 338, 'layer3': 209, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0019162790620019803}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:23:52<34:18:50, 10294.22s/it]

[I 2026-02-20 17:34:40,959] Trial 84 finished with value: 0.9267789080411892 and parameters: {'layer1': 164, 'layer2': 306, 'layer3': 186, 'activation': 'identity', 'solver': 'adam', 'lr': 0.002323732543136007}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:24:20<34:18:50, 10294.22s/it]

[I 2026-02-20 17:35:09,301] Trial 85 finished with value: 0.9263394314923155 and parameters: {'layer1': 238, 'layer2': 336, 'layer3': 234, 'activation': 'identity', 'solver': 'adam', 'lr': 0.005858029553035876}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:24:50<34:18:50, 10294.22s/it]

[I 2026-02-20 17:35:39,323] Trial 86 finished with value: 0.9267052319048842 and parameters: {'layer1': 246, 'layer2': 257, 'layer3': 216, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.00012344857989282006}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:25:13<34:18:50, 10294.22s/it]

[I 2026-02-20 17:36:02,634] Trial 87 finished with value: 0.9247282761781012 and parameters: {'layer1': 189, 'layer2': 228, 'layer3': 272, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0039569660939504}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:25:45<34:18:50, 10294.22s/it]

[I 2026-02-20 17:36:33,916] Trial 88 finished with value: 0.9219244387586057 and parameters: {'layer1': 278, 'layer2': 384, 'layer3': 152, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0076310298707297644}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:26:15<34:18:50, 10294.22s/it]

[I 2026-02-20 17:37:04,222] Trial 89 finished with value: 0.9232729700931429 and parameters: {'layer1': 142, 'layer2': 286, 'layer3': 200, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0026205496502944106}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:26:37<34:18:50, 10294.22s/it]

[I 2026-02-20 17:37:26,805] Trial 90 finished with value: 0.9275419142533922 and parameters: {'layer1': 220, 'layer2': 303, 'layer3': 241, 'activation': 'identity', 'solver': 'adam', 'lr': 0.00029802385717564016}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:27:10<34:18:50, 10294.22s/it]

[I 2026-02-20 17:37:59,072] Trial 91 finished with value: 0.9256091421337878 and parameters: {'layer1': 223, 'layer2': 303, 'layer3': 248, 'activation': 'identity', 'solver': 'adam', 'lr': 6.259326823139581e-05}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:27:34<34:18:50, 10294.22s/it]

[I 2026-02-20 17:38:23,032] Trial 92 finished with value: 0.9243970713475266 and parameters: {'layer1': 256, 'layer2': 316, 'layer3': 235, 'activation': 'identity', 'solver': 'adam', 'lr': 0.00035372532293546883}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:27:53<34:18:50, 10294.22s/it]

[I 2026-02-20 17:38:42,127] Trial 93 finished with value: 0.9249590158179759 and parameters: {'layer1': 98, 'layer2': 269, 'layer3': 289, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0005449016466639768}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:28:17<34:18:50, 10294.22s/it]

[I 2026-02-20 17:39:06,444] Trial 94 finished with value: 0.927105862010411 and parameters: {'layer1': 208, 'layer2': 355, 'layer3': 212, 'activation': 'identity', 'solver': 'adam', 'lr': 0.00021108331932021321}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:28:48<34:18:50, 10294.22s/it]

[I 2026-02-20 17:39:37,136] Trial 95 finished with value: 0.9230862482020203 and parameters: {'layer1': 173, 'layer2': 445, 'layer3': 172, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0031313057146869173}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:29:10<34:18:50, 10294.22s/it]

[I 2026-02-20 17:39:58,962] Trial 96 finished with value: 0.9257847418138168 and parameters: {'layer1': 74, 'layer2': 331, 'layer3': 259, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0053953517956003855}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:29:22<34:18:50, 10294.22s/it]

[I 2026-02-20 17:40:11,136] Trial 97 finished with value: 0.9050666137971211 and parameters: {'layer1': 198, 'layer2': 285, 'layer3': 182, 'activation': 'relu', 'solver': 'sgd', 'lr': 0.008410830586960873}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:29:41<34:18:50, 10294.22s/it]

[I 2026-02-20 17:40:29,884] Trial 98 finished with value: 0.9243778664197343 and parameters: {'layer1': 130, 'layer2': 409, 'layer3': 163, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0014325623114705417}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:30:05<34:18:50, 10294.22s/it]

[I 2026-02-20 17:40:53,936] Trial 99 finished with value: 0.9246712372318155 and parameters: {'layer1': 242, 'layer2': 462, 'layer3': 227, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0010768144156989292}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:30:36<34:18:50, 10294.22s/it]

[I 2026-02-20 17:41:25,327] Trial 100 finished with value: 0.925204674311526 and parameters: {'layer1': 345, 'layer2': 315, 'layer3': 193, 'activation': 'identity', 'solver': 'adam', 'lr': 0.001874770470636122}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:31:03<34:18:50, 10294.22s/it]

[I 2026-02-20 17:41:52,752] Trial 101 finished with value: 0.9251850008426942 and parameters: {'layer1': 223, 'layer2': 366, 'layer3': 205, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0019267604716009061}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:31:28<34:18:50, 10294.22s/it]

[I 2026-02-20 17:42:17,593] Trial 102 finished with value: 0.9255943939528567 and parameters: {'layer1': 186, 'layer2': 340, 'layer3': 242, 'activation': 'identity', 'solver': 'adam', 'lr': 0.004378316225799334}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:31:56<34:18:50, 10294.22s/it]

[I 2026-02-20 17:42:45,241] Trial 103 finished with value: 0.9225156287109975 and parameters: {'layer1': 232, 'layer2': 349, 'layer3': 206, 'activation': 'identity', 'solver': 'adam', 'lr': 0.006274238973455984}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:32:15<34:18:50, 10294.22s/it]

[I 2026-02-20 17:43:03,933] Trial 104 finished with value: 0.9050666137971211 and parameters: {'layer1': 267, 'layer2': 396, 'layer3': 220, 'activation': 'identity', 'solver': 'adam', 'lr': 1.5243179777913086e-05}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:32:35<34:18:50, 10294.22s/it]

[I 2026-02-20 17:43:24,579] Trial 105 finished with value: 0.9246981027835564 and parameters: {'layer1': 155, 'layer2': 299, 'layer3': 113, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0031519667824701186}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:32:58<34:18:50, 10294.22s/it]

[I 2026-02-20 17:43:47,422] Trial 106 finished with value: 0.9262521175080133 and parameters: {'layer1': 147, 'layer2': 321, 'layer3': 254, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0007111666042376174}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:33:21<34:18:50, 10294.22s/it]

[I 2026-02-20 17:44:10,262] Trial 107 finished with value: 0.9269778628406288 and parameters: {'layer1': 203, 'layer2': 270, 'layer3': 430, 'activation': 'identity', 'solver': 'adam', 'lr': 0.008628809667913651}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:33:39<34:18:50, 10294.22s/it]

[I 2026-02-20 17:44:28,480] Trial 108 finished with value: 0.9228419354161714 and parameters: {'layer1': 114, 'layer2': 290, 'layer3': 230, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0003972920481642708}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:33:51<34:18:50, 10294.22s/it]

[I 2026-02-20 17:44:40,317] Trial 109 finished with value: 0.9050666137971211 and parameters: {'layer1': 177, 'layer2': 306, 'layer3': 135, 'activation': 'logistic', 'solver': 'sgd', 'lr': 0.0022391845345942924}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:34:13<34:18:50, 10294.22s/it]

[I 2026-02-20 17:45:02,530] Trial 110 finished with value: 0.9277261050152414 and parameters: {'layer1': 163, 'layer2': 276, 'layer3': 180, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0036908527538934755}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:34:39<34:18:50, 10294.22s/it]

[I 2026-02-20 17:45:28,721] Trial 111 finished with value: 0.9272768513857985 and parameters: {'layer1': 165, 'layer2': 278, 'layer3': 179, 'activation': 'identity', 'solver': 'adam', 'lr': 0.003780145028403661}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:35:01<34:18:50, 10294.22s/it]

[I 2026-02-20 17:45:50,790] Trial 112 finished with value: 0.9261365303481742 and parameters: {'layer1': 168, 'layer2': 259, 'layer3': 178, 'activation': 'identity', 'solver': 'adam', 'lr': 0.003825183026426738}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:35:23<34:18:50, 10294.22s/it]

[I 2026-02-20 17:46:12,092] Trial 113 finished with value: 0.924245022590827 and parameters: {'layer1': 137, 'layer2': 247, 'layer3': 146, 'activation': 'identity', 'solver': 'adam', 'lr': 0.005248761973329963}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:35:46<34:18:50, 10294.22s/it]

[I 2026-02-20 17:46:35,308] Trial 114 finished with value: 0.9247938274242017 and parameters: {'layer1': 159, 'layer2': 286, 'layer3': 192, 'activation': 'identity', 'solver': 'adam', 'lr': 0.006824460228472251}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:36:07<34:18:50, 10294.22s/it]

[I 2026-02-20 17:46:56,547] Trial 115 finished with value: 0.9265468378814468 and parameters: {'layer1': 187, 'layer2': 233, 'layer3': 160, 'activation': 'identity', 'solver': 'adam', 'lr': 0.004650502668665013}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:36:28<34:18:50, 10294.22s/it]

[I 2026-02-20 17:47:17,271] Trial 116 finished with value: 0.9261139805503339 and parameters: {'layer1': 150, 'layer2': 273, 'layer3': 129, 'activation': 'identity', 'solver': 'adam', 'lr': 0.003663059745891993}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:36:47<34:18:50, 10294.22s/it]

[I 2026-02-20 17:47:36,815] Trial 117 finished with value: 0.9257681480119583 and parameters: {'layer1': 92, 'layer2': 436, 'layer3': 170, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0028180928180674475}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:37:11<34:18:50, 10294.22s/it]

[I 2026-02-20 17:48:00,756] Trial 118 finished with value: 0.9231559804491376 and parameters: {'layer1': 119, 'layer2': 275, 'layer3': 215, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00980894552958226}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:37:38<34:18:50, 10294.22s/it]

[I 2026-02-20 17:48:27,599] Trial 119 finished with value: 0.9258572329725899 and parameters: {'layer1': 167, 'layer2': 222, 'layer3': 183, 'activation': 'identity', 'solver': 'adam', 'lr': 0.005807638148721953}. Best is trial 41 with value: 0.9282542404217089.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:38:04<34:18:50, 10294.22s/it]

[I 2026-02-20 17:48:52,942] Trial 120 finished with value: 0.9290793939345356 and parameters: {'layer1': 131, 'layer2': 262, 'layer3': 197, 'activation': 'identity', 'solver': 'adam', 'lr': 0.006987954067517757}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:38:23<34:18:50, 10294.22s/it]

[I 2026-02-20 17:49:12,469] Trial 121 finished with value: 0.9279027945976235 and parameters: {'layer1': 135, 'layer2': 263, 'layer3': 200, 'activation': 'identity', 'solver': 'adam', 'lr': 0.007566230033593794}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:38:47<34:18:50, 10294.22s/it]

[I 2026-02-20 17:49:36,357] Trial 122 finished with value: 0.926083267430067 and parameters: {'layer1': 132, 'layer2': 254, 'layer3': 197, 'activation': 'identity', 'solver': 'adam', 'lr': 0.007968764858511166}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:39:10<34:18:50, 10294.22s/it]

[I 2026-02-20 17:49:59,401] Trial 123 finished with value: 0.9252152372488046 and parameters: {'layer1': 148, 'layer2': 265, 'layer3': 242, 'activation': 'identity', 'solver': 'adam', 'lr': 0.006910224934917602}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:39:26<34:18:50, 10294.22s/it]

[I 2026-02-20 17:50:15,410] Trial 124 finished with value: 0.9050666137971211 and parameters: {'layer1': 214, 'layer2': 294, 'layer3': 211, 'activation': 'identity', 'solver': 'adam', 'lr': 4.877207379747896e-06}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:39:46<34:18:50, 10294.22s/it]

[I 2026-02-20 17:50:35,560] Trial 125 finished with value: 0.9264495778623992 and parameters: {'layer1': 105, 'layer2': 247, 'layer3': 224, 'activation': 'identity', 'solver': 'adam', 'lr': 0.004908735627957305}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:40:11<34:18:50, 10294.22s/it]

[I 2026-02-20 17:51:00,451] Trial 126 finished with value: 0.9269892041538526 and parameters: {'layer1': 180, 'layer2': 280, 'layer3': 201, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0058097067943118546}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:40:46<34:18:50, 10294.22s/it]

[I 2026-02-20 17:51:35,282] Trial 127 finished with value: 0.925668734297281 and parameters: {'layer1': 291, 'layer2': 257, 'layer3': 269, 'activation': 'identity', 'solver': 'adam', 'lr': 0.007879791318644773}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:41:14<34:18:50, 10294.22s/it]

[I 2026-02-20 17:52:03,723] Trial 128 finished with value: 0.9240841526903549 and parameters: {'layer1': 253, 'layer2': 310, 'layer3': 232, 'activation': 'identity', 'solver': 'adam', 'lr': 0.009758741384205223}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:41:31<34:18:50, 10294.22s/it]

[I 2026-02-20 17:52:20,038] Trial 129 finished with value: 0.9050666137971211 and parameters: {'layer1': 200, 'layer2': 298, 'layer3': 191, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.004185744545930719}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:41:43<34:18:50, 10294.22s/it]

[I 2026-02-20 17:52:32,088] Trial 130 finished with value: 0.9050666137971211 and parameters: {'layer1': 164, 'layer2': 283, 'layer3': 179, 'activation': 'identity', 'solver': 'sgd', 'lr': 0.006940026503424504}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:42:00<34:18:50, 10294.22s/it]

[I 2026-02-20 17:52:49,500] Trial 131 finished with value: 0.9249737639036851 and parameters: {'layer1': 120, 'layer2': 264, 'layer3': 148, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0029895327317264755}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:42:20<34:18:50, 10294.22s/it]

[I 2026-02-20 17:53:09,617] Trial 132 finished with value: 0.9269375010175868 and parameters: {'layer1': 133, 'layer2': 325, 'layer3': 163, 'activation': 'identity', 'solver': 'adam', 'lr': 0.003585374471601944}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:42:44<34:18:50, 10294.22s/it]

[I 2026-02-20 17:53:33,143] Trial 133 finished with value: 0.9260960309303596 and parameters: {'layer1': 145, 'layer2': 302, 'layer3': 218, 'activation': 'identity', 'solver': 'adam', 'lr': 0.00484704277814827}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:43:06<34:18:50, 10294.22s/it]

[I 2026-02-20 17:53:55,561] Trial 134 finished with value: 0.9280561237287834 and parameters: {'layer1': 158, 'layer2': 237, 'layer3': 248, 'activation': 'identity', 'solver': 'adam', 'lr': 0.00589625550487066}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:43:31<34:18:50, 10294.22s/it]

[I 2026-02-20 17:54:20,172] Trial 135 finished with value: 0.9251045640579433 and parameters: {'layer1': 158, 'layer2': 216, 'layer3': 256, 'activation': 'identity', 'solver': 'adam', 'lr': 0.005970390669001894}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:43:53<34:18:50, 10294.22s/it]

[I 2026-02-20 17:54:42,469] Trial 136 finished with value: 0.922539909134606 and parameters: {'layer1': 175, 'layer2': 485, 'layer3': 246, 'activation': 'identity', 'solver': 'adam', 'lr': 0.008152284519112093}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:44:18<34:18:50, 10294.22s/it]

[I 2026-02-20 17:55:07,595] Trial 137 finished with value: 0.9253327715663545 and parameters: {'layer1': 189, 'layer2': 207, 'layer3': 210, 'activation': 'identity', 'solver': 'adam', 'lr': 0.00640120159523787}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:44:59<34:18:50, 10294.22s/it]

[I 2026-02-20 17:55:48,782] Trial 138 finished with value: 0.9219573464283031 and parameters: {'layer1': 221, 'layer2': 240, 'layer3': 235, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.004176352778056977}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:45:24<34:18:50, 10294.22s/it]

[I 2026-02-20 17:56:13,552] Trial 139 finished with value: 0.9270865737104004 and parameters: {'layer1': 142, 'layer2': 289, 'layer3': 277, 'activation': 'identity', 'solver': 'adam', 'lr': 0.005261736610787566}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:45:51<34:18:50, 10294.22s/it]

[I 2026-02-20 17:56:40,603] Trial 140 finished with value: 0.9231289087818887 and parameters: {'layer1': 202, 'layer2': 420, 'layer3': 224, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0084204647481544}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:46:10<34:18:50, 10294.22s/it]

[I 2026-02-20 17:56:59,625] Trial 141 finished with value: 0.9242241263645019 and parameters: {'layer1': 129, 'layer2': 275, 'layer3': 188, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0025175239474675743}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:46:30<34:18:50, 10294.22s/it]

[I 2026-02-20 17:57:19,084] Trial 142 finished with value: 0.924862599226236 and parameters: {'layer1': 110, 'layer2': 310, 'layer3': 201, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0032254866750450624}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:46:51<34:18:50, 10294.22s/it]

[I 2026-02-20 17:57:40,607] Trial 143 finished with value: 0.9267052558901069 and parameters: {'layer1': 124, 'layer2': 262, 'layer3': 241, 'activation': 'identity', 'solver': 'adam', 'lr': 0.004406106024308454}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:47:21<34:18:50, 10294.22s/it]

[I 2026-02-20 17:58:10,728] Trial 144 finished with value: 0.925121692222192 and parameters: {'layer1': 156, 'layer2': 251, 'layer3': 168, 'activation': 'identity', 'solver': 'adam', 'lr': 7.117349640571679e-05}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:47:51<34:18:50, 10294.22s/it]

[I 2026-02-20 17:58:40,416] Trial 145 finished with value: 0.9249524421332336 and parameters: {'layer1': 238, 'layer2': 280, 'layer3': 207, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0001422826133484917}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:48:36<34:18:50, 10294.22s/it]

[I 2026-02-20 17:59:25,099] Trial 146 finished with value: 0.9219191826959993 and parameters: {'layer1': 456, 'layer2': 236, 'layer3': 222, 'activation': 'identity', 'solver': 'adam', 'lr': 3.399869529402887e-05}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:49:02<34:18:50, 10294.22s/it]

[I 2026-02-20 17:59:51,317] Trial 147 finished with value: 0.9253183726690393 and parameters: {'layer1': 173, 'layer2': 332, 'layer3': 261, 'activation': 'identity', 'solver': 'adam', 'lr': 0.007028956602404619}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:49:20<34:18:50, 10294.22s/it]

[I 2026-02-20 18:00:09,315] Trial 148 finished with value: 0.9257704083730995 and parameters: {'layer1': 99, 'layer2': 187, 'layer3': 153, 'activation': 'identity', 'solver': 'adam', 'lr': 0.00545446706179594}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:49:43<34:18:50, 10294.22s/it]

[I 2026-02-20 18:00:32,056] Trial 149 finished with value: 0.9219374087448653 and parameters: {'layer1': 139, 'layer2': 295, 'layer3': 183, 'activation': 'identity', 'solver': 'adam', 'lr': 0.009948271994719513}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:50:04<34:18:50, 10294.22s/it]

[I 2026-02-20 18:00:53,827] Trial 150 finished with value: 0.9248460912403879 and parameters: {'layer1': 85, 'layer2': 318, 'layer3': 248, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00025692337617402833}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:50:28<34:18:50, 10294.22s/it]

[I 2026-02-20 18:01:17,240] Trial 151 finished with value: 0.9252167741879621 and parameters: {'layer1': 208, 'layer2': 346, 'layer3': 196, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0016474319387883352}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:50:49<34:18:50, 10294.22s/it]

[I 2026-02-20 18:01:38,376] Trial 152 finished with value: 0.9260768488990238 and parameters: {'layer1': 191, 'layer2': 266, 'layer3': 234, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0019668837323503097}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:51:17<34:18:50, 10294.22s/it]

[I 2026-02-20 18:02:06,378] Trial 153 finished with value: 0.9275181856117538 and parameters: {'layer1': 224, 'layer2': 359, 'layer3': 212, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0024360909242038924}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:51:40<34:18:50, 10294.22s/it]

[I 2026-02-20 18:02:29,828] Trial 154 finished with value: 0.9273689975354896 and parameters: {'layer1': 228, 'layer2': 359, 'layer3': 216, 'activation': 'identity', 'solver': 'adam', 'lr': 0.002326471494987201}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:52:09<34:18:50, 10294.22s/it]

[I 2026-02-20 18:02:58,424] Trial 155 finished with value: 0.9263534966656024 and parameters: {'layer1': 234, 'layer2': 388, 'layer3': 219, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0032952080700056363}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:52:34<34:18:50, 10294.22s/it]

[I 2026-02-20 18:03:23,031] Trial 156 finished with value: 0.9266162367316463 and parameters: {'layer1': 221, 'layer2': 373, 'layer3': 209, 'activation': 'identity', 'solver': 'adam', 'lr': 0.003877488885679967}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:52:46<34:18:50, 10294.22s/it]

[I 2026-02-20 18:03:35,743] Trial 157 finished with value: 0.9050666137971211 and parameters: {'layer1': 259, 'layer2': 405, 'layer3': 229, 'activation': 'identity', 'solver': 'sgd', 'lr': 0.006878744464848083}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:53:11<34:18:50, 10294.22s/it]

[I 2026-02-20 18:04:00,328] Trial 158 finished with value: 0.9234130315576277 and parameters: {'layer1': 244, 'layer2': 363, 'layer3': 196, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0012447707943322802}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:53:41<34:18:50, 10294.22s/it]

[I 2026-02-20 18:04:29,863] Trial 159 finished with value: 0.9168371898384267 and parameters: {'layer1': 227, 'layer2': 353, 'layer3': 216, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0023364352175136655}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:54:08<34:18:50, 10294.22s/it]

[I 2026-02-20 18:04:56,971] Trial 160 finished with value: 0.925626438431799 and parameters: {'layer1': 180, 'layer2': 276, 'layer3': 177, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0047306509624093895}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:54:34<34:18:50, 10294.22s/it]

[I 2026-02-20 18:05:23,540] Trial 161 finished with value: 0.9258529533728425 and parameters: {'layer1': 213, 'layer2': 335, 'layer3': 241, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0027048108124493836}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:55:05<34:18:50, 10294.22s/it]

[I 2026-02-20 18:05:54,136] Trial 162 finished with value: 0.9254667333893561 and parameters: {'layer1': 269, 'layer2': 290, 'layer3': 204, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0056724857968895185}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:55:24<34:18:50, 10294.22s/it]

[I 2026-02-20 18:06:13,281] Trial 163 finished with value: 0.9272730125612109 and parameters: {'layer1': 150, 'layer2': 323, 'layer3': 189, 'activation': 'identity', 'solver': 'adam', 'lr': 0.003598823986254458}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:55:47<34:18:50, 10294.22s/it]

[I 2026-02-20 18:06:36,753] Trial 164 finished with value: 0.9257576924219464 and parameters: {'layer1': 158, 'layer2': 453, 'layer3': 190, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0037919523601750186}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:56:12<34:18:50, 10294.22s/it]

[I 2026-02-20 18:07:01,574] Trial 165 finished with value: 0.9237272344078112 and parameters: {'layer1': 164, 'layer2': 314, 'layer3': 228, 'activation': 'identity', 'solver': 'adam', 'lr': 0.007582219768052976}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:56:34<34:18:50, 10294.22s/it]

[I 2026-02-20 18:07:22,971] Trial 166 finished with value: 0.9262390787692478 and parameters: {'layer1': 149, 'layer2': 327, 'layer3': 213, 'activation': 'identity', 'solver': 'adam', 'lr': 0.004773154186807925}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:56:58<34:18:50, 10294.22s/it]

[I 2026-02-20 18:07:47,604] Trial 167 finished with value: 0.9273679895472131 and parameters: {'layer1': 195, 'layer2': 300, 'layer3': 172, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0029585439215649204}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:57:28<34:18:50, 10294.22s/it]

[I 2026-02-20 18:08:17,502] Trial 168 finished with value: 0.922684689640794 and parameters: {'layer1': 198, 'layer2': 432, 'layer3': 173, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0021291838139591308}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:57:51<34:18:50, 10294.22s/it]

[I 2026-02-20 18:08:40,648] Trial 169 finished with value: 0.9253986806439671 and parameters: {'layer1': 169, 'layer2': 301, 'layer3': 181, 'activation': 'identity', 'solver': 'adam', 'lr': 0.002972133109501872}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:58:17<34:18:50, 10294.22s/it]

[I 2026-02-20 18:09:06,571] Trial 170 finished with value: 0.9263320269074363 and parameters: {'layer1': 252, 'layer2': 343, 'layer3': 159, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0034173541998472525}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:58:44<34:18:50, 10294.22s/it]

[I 2026-02-20 18:09:33,056] Trial 171 finished with value: 0.9248665864587157 and parameters: {'layer1': 186, 'layer2': 306, 'layer3': 199, 'activation': 'identity', 'solver': 'adam', 'lr': 0.005912460612417392}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:59:11<34:18:50, 10294.22s/it]

[I 2026-02-20 18:09:59,856] Trial 172 finished with value: 0.9276637381862557 and parameters: {'layer1': 213, 'layer2': 284, 'layer3': 252, 'activation': 'identity', 'solver': 'adam', 'lr': 0.008613197099560821}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [6:59:36<34:18:50, 10294.22s/it]

[I 2026-02-20 18:10:25,620] Trial 173 finished with value: 0.9251501423273988 and parameters: {'layer1': 215, 'layer2': 287, 'layer3': 253, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0014890125405695913}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [7:00:01<34:18:50, 10294.22s/it]

[I 2026-02-20 18:10:50,301] Trial 174 finished with value: 0.9263040481786702 and parameters: {'layer1': 231, 'layer2': 273, 'layer3': 29, 'activation': 'identity', 'solver': 'adam', 'lr': 0.004171592862497591}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [7:00:25<34:18:50, 10294.22s/it]

[I 2026-02-20 18:11:14,568] Trial 175 finished with value: 0.9272319202028191 and parameters: {'layer1': 203, 'layer2': 253, 'layer3': 167, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0066794408650288324}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [7:00:55<34:18:50, 10294.22s/it]

[I 2026-02-20 18:11:43,912] Trial 176 finished with value: 0.925061278517194 and parameters: {'layer1': 210, 'layer2': 264, 'layer3': 262, 'activation': 'identity', 'solver': 'adam', 'lr': 0.002709276244045982}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [7:01:25<34:18:50, 10294.22s/it]

[I 2026-02-20 18:12:14,491] Trial 177 finished with value: 0.9217982754849346 and parameters: {'layer1': 241, 'layer2': 284, 'layer3': 187, 'activation': 'identity', 'solver': 'adam', 'lr': 0.008252098976343259}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [7:01:51<34:18:50, 10294.22s/it]

[I 2026-02-20 18:12:40,246] Trial 178 finished with value: 0.9233064373236688 and parameters: {'layer1': 151, 'layer2': 244, 'layer3': 207, 'activation': 'identity', 'solver': 'adam', 'lr': 0.005035595377324385}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [7:02:07<34:18:50, 10294.22s/it]

[I 2026-02-20 18:12:56,793] Trial 179 finished with value: 0.9267357789908302 and parameters: {'layer1': 134, 'layer2': 77, 'layer3': 219, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0036947750265185846}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [7:02:25<34:18:50, 10294.22s/it]

[I 2026-02-20 18:13:14,628] Trial 180 finished with value: 0.9050666137971211 and parameters: {'layer1': 227, 'layer2': 322, 'layer3': 287, 'activation': 'identity', 'solver': 'adam', 'lr': 1.1089223301693168e-06}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [7:02:50<34:18:50, 10294.22s/it]

[I 2026-02-20 18:13:38,974] Trial 181 finished with value: 0.9239987442824693 and parameters: {'layer1': 199, 'layer2': 252, 'layer3': 165, 'activation': 'identity', 'solver': 'adam', 'lr': 0.006543758899194687}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [7:03:13<34:18:50, 10294.22s/it]

[I 2026-02-20 18:14:02,349] Trial 182 finished with value: 0.9258693657559363 and parameters: {'layer1': 206, 'layer2': 259, 'layer3': 172, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0061841362531196205}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [7:03:40<34:18:50, 10294.22s/it]

[I 2026-02-20 18:14:29,146] Trial 183 finished with value: 0.9250062957243316 and parameters: {'layer1': 177, 'layer2': 227, 'layer3': 188, 'activation': 'identity', 'solver': 'adam', 'lr': 0.007701813283022663}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [7:04:04<34:18:50, 10294.22s/it]

[I 2026-02-20 18:14:53,412] Trial 184 finished with value: 0.924293550217335 and parameters: {'layer1': 193, 'layer2': 272, 'layer3': 239, 'activation': 'relu', 'solver': 'adam', 'lr': 0.005090585218415449}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [7:04:30<34:18:50, 10294.22s/it]

[I 2026-02-20 18:15:19,052] Trial 185 finished with value: 0.9253208231746404 and parameters: {'layer1': 219, 'layer2': 313, 'layer3': 196, 'activation': 'identity', 'solver': 'adam', 'lr': 0.004386535676443966}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [7:05:02<34:18:50, 10294.22s/it]

[I 2026-02-20 18:15:51,840] Trial 186 finished with value: 0.9249031001336036 and parameters: {'layer1': 161, 'layer2': 295, 'layer3': 178, 'activation': 'identity', 'solver': 'adam', 'lr': 0.00839641531236207}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [7:05:15<34:18:50, 10294.22s/it]

[I 2026-02-20 18:16:04,093] Trial 187 finished with value: 0.9050666137971211 and parameters: {'layer1': 246, 'layer2': 279, 'layer3': 164, 'activation': 'identity', 'solver': 'sgd', 'lr': 0.006072335443858731}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [7:05:40<34:18:50, 10294.22s/it]

[I 2026-02-20 18:16:29,304] Trial 188 finished with value: 0.9262079026861461 and parameters: {'layer1': 143, 'layer2': 421, 'layer3': 249, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0023773986041067214}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [7:06:04<34:18:50, 10294.22s/it]

[I 2026-02-20 18:16:53,077] Trial 189 finished with value: 0.9249904547283133 and parameters: {'layer1': 183, 'layer2': 254, 'layer3': 226, 'activation': 'identity', 'solver': 'adam', 'lr': 0.003192610594020557}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [7:06:34<34:18:50, 10294.22s/it]

[I 2026-02-20 18:17:23,360] Trial 190 finished with value: 0.9261954765370609 and parameters: {'layer1': 202, 'layer2': 236, 'layer3': 207, 'activation': 'identity', 'solver': 'adam', 'lr': 0.007110820611026601}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [7:06:59<34:18:50, 10294.22s/it]

[I 2026-02-20 18:17:48,070] Trial 191 finished with value: 0.9267989213524839 and parameters: {'layer1': 167, 'layer2': 300, 'layer3': 232, 'activation': 'identity', 'solver': 'adam', 'lr': 0.009270150030720351}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [7:07:24<34:18:50, 10294.22s/it]

[I 2026-02-20 18:18:13,385] Trial 192 finished with value: 0.9242576853359299 and parameters: {'layer1': 184, 'layer2': 291, 'layer3': 218, 'activation': 'identity', 'solver': 'adam', 'lr': 0.00990554545494881}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [7:07:56<34:18:50, 10294.22s/it]

[I 2026-02-20 18:18:44,851] Trial 193 finished with value: 0.9268065006743175 and parameters: {'layer1': 192, 'layer2': 305, 'layer3': 236, 'activation': 'identity', 'solver': 'adam', 'lr': 0.007389043975100903}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [7:08:20<34:18:50, 10294.22s/it]

[I 2026-02-20 18:19:09,786] Trial 194 finished with value: 0.9244984373296816 and parameters: {'layer1': 218, 'layer2': 269, 'layer3': 195, 'activation': 'identity', 'solver': 'adam', 'lr': 0.005273191344013197}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [7:08:50<34:18:50, 10294.22s/it]

[I 2026-02-20 18:19:39,152] Trial 195 finished with value: 0.9257651608151551 and parameters: {'layer1': 174, 'layer2': 279, 'layer3': 268, 'activation': 'identity', 'solver': 'adam', 'lr': 0.006028948424257648}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [7:09:06<34:18:50, 10294.22s/it]

[I 2026-02-20 18:19:55,338] Trial 196 finished with value: 0.9050666137971211 and parameters: {'layer1': 208, 'layer2': 319, 'layer3': 151, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.004354417231495845}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [7:09:29<34:18:50, 10294.22s/it]

[I 2026-02-20 18:20:18,347] Trial 197 finished with value: 0.9260782562643296 and parameters: {'layer1': 154, 'layer2': 358, 'layer3': 183, 'activation': 'identity', 'solver': 'adam', 'lr': 0.006861475565694767}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  14%|█▍        | 2/14 [7:09:52<34:18:50, 10294.22s/it]

[I 2026-02-20 18:20:41,126] Trial 198 finished with value: 0.9243621820788382 and parameters: {'layer1': 124, 'layer2': 286, 'layer3': 248, 'activation': 'identity', 'solver': 'adam', 'lr': 0.003642973282707581}. Best is trial 120 with value: 0.9290793939345356.

Best trial: 120. Best value: 0.929079: 100%|██████████| 200/200 [1:18:41<00:00, 23.61s/it]

[I 2026-02-20 18:21:17,733] Trial 199 finished with value: 0.9244991617157243 and parameters: {'layer1': 275, 'layer2': 301, 'layer3': 500, 'activation': 'identity', 'solver': 'adam', 'lr': 0.008545965013412144}. Best is trial 120 with value: 0.9290793939345356.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:10:30<23:40:53, 7750.29s/it] [I 2026-02-20 18:21:19,275] A new study created in memory with name: no-name-89861a4e-7906-4d76-a88b-074eb196b0a8

  → Best model saved.

[Exact Paper MLP] Escherichia_Coli | Ciprofloxacin

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:11:06<23:40:53, 7750.29s/it]

[I 2026-02-20 18:21:54,849] Trial 0 finished with value: 0.7857414062966209 and parameters: {'layer1': 15, 'layer2': 215, 'layer3': 234, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.4875195870289977e-05}. Best is trial 0 with value: 0.7857414062966209.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:11:32<23:40:53, 7750.29s/it]

[I 2026-02-20 18:22:21,198] Trial 1 finished with value: 0.5945172904007522 and parameters: {'layer1': 374, 'layer2': 226, 'layer3': 200, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.9388291924994468e-06}. Best is trial 0 with value: 0.7857414062966209.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:11:51<23:40:53, 7750.29s/it]

[I 2026-02-20 18:22:40,225] Trial 2 finished with value: 0.6035469943239532 and parameters: {'layer1': 51, 'layer2': 385, 'layer3': 186, 'activation': 'relu', 'solver': 'sgd', 'lr': 8.086356912805024e-05}. Best is trial 0 with value: 0.7857414062966209.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:12:23<23:40:53, 7750.29s/it]

[I 2026-02-20 18:23:11,930] Trial 3 finished with value: 0.5098324764772701 and parameters: {'layer1': 295, 'layer2': 106, 'layer3': 242, 'activation': 'relu', 'solver': 'sgd', 'lr': 1.1825734535631772e-06}. Best is trial 0 with value: 0.7857414062966209.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:12:43<23:40:53, 7750.29s/it]

[I 2026-02-20 18:23:32,250] Trial 4 finished with value: 0.6326220135678239 and parameters: {'layer1': 30, 'layer2': 258, 'layer3': 82, 'activation': 'identity', 'solver': 'sgd', 'lr': 0.004777936822530602}. Best is trial 0 with value: 0.7857414062966209.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:13:25<23:40:53, 7750.29s/it]

[I 2026-02-20 18:24:14,547] Trial 5 finished with value: 0.7823350787903195 and parameters: {'layer1': 313, 'layer2': 132, 'layer3': 390, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0026176089185672782}. Best is trial 0 with value: 0.7857414062966209.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:14:31<23:40:53, 7750.29s/it]

[I 2026-02-20 18:25:20,062] Trial 6 finished with value: 0.7481676293876649 and parameters: {'layer1': 481, 'layer2': 419, 'layer3': 176, 'activation': 'identity', 'solver': 'sgd', 'lr': 0.00815380996613427}. Best is trial 0 with value: 0.7857414062966209.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:15:43<23:40:53, 7750.29s/it]

[I 2026-02-20 18:26:32,677] Trial 7 finished with value: 0.41358124306936245 and parameters: {'layer1': 28, 'layer2': 298, 'layer3': 380, 'activation': 'tanh', 'solver': 'sgd', 'lr': 1.3173456586098081e-06}. Best is trial 0 with value: 0.7857414062966209.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:16:03<23:40:53, 7750.29s/it]

[I 2026-02-20 18:26:51,862] Trial 8 finished with value: 0.6005249049786896 and parameters: {'layer1': 352, 'layer2': 293, 'layer3': 193, 'activation': 'tanh', 'solver': 'sgd', 'lr': 0.000471286562935607}. Best is trial 0 with value: 0.7857414062966209.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:16:21<23:40:53, 7750.29s/it]

[I 2026-02-20 18:27:10,689] Trial 9 finished with value: 0.6040019700173391 and parameters: {'layer1': 253, 'layer2': 411, 'layer3': 246, 'activation': 'tanh', 'solver': 'sgd', 'lr': 0.00018782003315949216}. Best is trial 0 with value: 0.7857414062966209.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:16:41<23:40:53, 7750.29s/it]

[I 2026-02-20 18:27:30,236] Trial 10 finished with value: 0.5940221219711511 and parameters: {'layer1': 169, 'layer2': 44, 'layer3': 492, 'activation': 'logistic', 'solver': 'adam', 'lr': 1.6168572770818888e-05}. Best is trial 0 with value: 0.7857414062966209.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:17:16<23:40:53, 7750.29s/it]

[I 2026-02-20 18:28:05,363] Trial 11 finished with value: 0.7862801313812449 and parameters: {'layer1': 137, 'layer2': 142, 'layer3': 359, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.4584117343186214e-05}. Best is trial 11 with value: 0.7862801313812449.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:17:35<23:40:53, 7750.29s/it]

[I 2026-02-20 18:28:24,325] Trial 12 finished with value: 0.5940221219711511 and parameters: {'layer1': 135, 'layer2': 173, 'layer3': 361, 'activation': 'logistic', 'solver': 'adam', 'lr': 1.7669565704783808e-05}. Best is trial 11 with value: 0.7862801313812449.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:18:24<23:40:53, 7750.29s/it]

[I 2026-02-20 18:29:13,174] Trial 13 finished with value: 0.7878709761358327 and parameters: {'layer1': 129, 'layer2': 33, 'layer3': 321, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.8878105968064155e-05}. Best is trial 13 with value: 0.7878709761358327.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:18:41<23:40:53, 7750.29s/it]

[I 2026-02-20 18:29:30,797] Trial 14 finished with value: 0.5940221219711511 and parameters: {'layer1': 177, 'layer2': 23, 'layer3': 305, 'activation': 'tanh', 'solver': 'adam', 'lr': 6.787003243564527e-06}. Best is trial 13 with value: 0.7878709761358327.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:19:03<23:40:53, 7750.29s/it]

[I 2026-02-20 18:29:52,218] Trial 15 finished with value: 0.7841730790328313 and parameters: {'layer1': 106, 'layer2': 85, 'layer3': 458, 'activation': 'tanh', 'solver': 'adam', 'lr': 9.211116712805471e-05}. Best is trial 13 with value: 0.7878709761358327.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:19:50<23:40:53, 7750.29s/it]

[I 2026-02-20 18:30:39,457] Trial 16 finished with value: 0.6680764717797261 and parameters: {'layer1': 231, 'layer2': 495, 'layer3': 315, 'activation': 'logistic', 'solver': 'adam', 'lr': 3.8650339152462385e-05}. Best is trial 13 with value: 0.7878709761358327.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:20:07<23:40:53, 7750.29s/it]

[I 2026-02-20 18:30:56,039] Trial 17 finished with value: 0.778189123986037 and parameters: {'layer1': 102, 'layer2': 12, 'layer3': 425, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0005122726471501206}. Best is trial 13 with value: 0.7878709761358327.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:20:26<23:40:53, 7750.29s/it]

[I 2026-02-20 18:31:15,732] Trial 18 finished with value: 0.5963077424419436 and parameters: {'layer1': 208, 'layer2': 156, 'layer3': 312, 'activation': 'relu', 'solver': 'adam', 'lr': 6.9493284055162125e-06}. Best is trial 13 with value: 0.7878709761358327.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:20:43<23:40:53, 7750.29s/it]

[I 2026-02-20 18:31:31,878] Trial 19 finished with value: 0.5940221219711511 and parameters: {'layer1': 83, 'layer2': 80, 'layer3': 90, 'activation': 'tanh', 'solver': 'adam', 'lr': 6.225060966719024e-06}. Best is trial 13 with value: 0.7878709761358327.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:21:07<23:40:53, 7750.29s/it]

[I 2026-02-20 18:31:56,215] Trial 20 finished with value: 0.7814029231378681 and parameters: {'layer1': 149, 'layer2': 64, 'layer3': 339, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.00027274184904012267}. Best is trial 13 with value: 0.7878709761358327.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:21:45<23:40:53, 7750.29s/it]

[I 2026-02-20 18:32:34,460] Trial 21 finished with value: 0.7496633045479661 and parameters: {'layer1': 15, 'layer2': 211, 'layer3': 10, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.156279636386409e-05}. Best is trial 13 with value: 0.7878709761358327.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:22:15<23:40:53, 7750.29s/it]

[I 2026-02-20 18:33:03,859] Trial 22 finished with value: 0.7866725539342048 and parameters: {'layer1': 72, 'layer2': 171, 'layer3': 276, 'activation': 'tanh', 'solver': 'adam', 'lr': 3.7271224428113134e-05}. Best is trial 13 with value: 0.7878709761358327.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:22:40<23:40:53, 7750.29s/it]

[I 2026-02-20 18:33:28,952] Trial 23 finished with value: 0.7853178335229689 and parameters: {'layer1': 78, 'layer2': 140, 'layer3': 280, 'activation': 'tanh', 'solver': 'adam', 'lr': 5.3416357631071755e-05}. Best is trial 13 with value: 0.7878709761358327.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:23:04<23:40:53, 7750.29s/it]

[I 2026-02-20 18:33:53,567] Trial 24 finished with value: 0.781177846403274 and parameters: {'layer1': 195, 'layer2': 110, 'layer3': 424, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.00015463685872950936}. Best is trial 13 with value: 0.7878709761358327.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:23:58<23:40:53, 7750.29s/it]

[I 2026-02-20 18:34:47,224] Trial 25 finished with value: 0.7866472285541652 and parameters: {'layer1': 132, 'layer2': 179, 'layer3': 288, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.0186501276100022e-05}. Best is trial 13 with value: 0.7878709761358327.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:24:16<23:40:53, 7750.29s/it]

[I 2026-02-20 18:35:05,482] Trial 26 finished with value: 0.5981634648584528 and parameters: {'layer1': 115, 'layer2': 187, 'layer3': 271, 'activation': 'relu', 'solver': 'adam', 'lr': 3.2827576466017136e-06}. Best is trial 13 with value: 0.7878709761358327.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:25:18<23:40:53, 7750.29s/it]

[I 2026-02-20 18:36:07,087] Trial 27 finished with value: 0.7902305670021997 and parameters: {'layer1': 67, 'layer2': 327, 'layer3': 137, 'activation': 'identity', 'solver': 'adam', 'lr': 1.0516441621626139e-05}. Best is trial 27 with value: 0.7902305670021997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:25:34<23:40:53, 7750.29s/it]

[I 2026-02-20 18:36:23,109] Trial 28 finished with value: 0.6001171442403365 and parameters: {'layer1': 62, 'layer2': 335, 'layer3': 129, 'activation': 'identity', 'solver': 'adam', 'lr': 3.905101196541459e-06}. Best is trial 27 with value: 0.7902305670021997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:26:03<23:40:53, 7750.29s/it]

[I 2026-02-20 18:36:51,915] Trial 29 finished with value: 0.7850971387102215 and parameters: {'layer1': 53, 'layer2': 349, 'layer3': 142, 'activation': 'identity', 'solver': 'adam', 'lr': 4.3620394695073695e-05}. Best is trial 27 with value: 0.7902305670021997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:26:31<23:40:53, 7750.29s/it]

[I 2026-02-20 18:37:20,165] Trial 30 finished with value: 0.7862102746274552 and parameters: {'layer1': 85, 'layer2': 277, 'layer3': 220, 'activation': 'identity', 'solver': 'adam', 'lr': 4.05465969602961e-05}. Best is trial 27 with value: 0.7902305670021997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:27:31<23:40:53, 7750.29s/it]

[I 2026-02-20 18:38:20,655] Trial 31 finished with value: 0.787477410639674 and parameters: {'layer1': 129, 'layer2': 229, 'layer3': 278, 'activation': 'identity', 'solver': 'adam', 'lr': 9.89687978088908e-06}. Best is trial 27 with value: 0.7902305670021997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:28:23<23:40:53, 7750.29s/it]

[I 2026-02-20 18:39:12,046] Trial 32 finished with value: 0.7879995479858172 and parameters: {'layer1': 175, 'layer2': 216, 'layer3': 226, 'activation': 'identity', 'solver': 'adam', 'lr': 1.184330472293191e-05}. Best is trial 27 with value: 0.7902305670021997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:29:17<23:40:53, 7750.29s/it]

[I 2026-02-20 18:40:06,030] Trial 33 finished with value: 0.7895020060301466 and parameters: {'layer1': 166, 'layer2': 212, 'layer3': 143, 'activation': 'identity', 'solver': 'adam', 'lr': 1.2617333832045762e-05}. Best is trial 27 with value: 0.7902305670021997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:29:38<23:40:53, 7750.29s/it]

[I 2026-02-20 18:40:27,257] Trial 34 finished with value: 0.5953593484161797 and parameters: {'layer1': 209, 'layer2': 325, 'layer3': 156, 'activation': 'identity', 'solver': 'adam', 'lr': 1.6870802357408217e-06}. Best is trial 27 with value: 0.7902305670021997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:30:00<23:40:53, 7750.29s/it]

[I 2026-02-20 18:40:49,274] Trial 35 finished with value: 0.5989291483617638 and parameters: {'layer1': 245, 'layer2': 240, 'layer3': 75, 'activation': 'identity', 'solver': 'adam', 'lr': 2.2643559775878114e-06}. Best is trial 27 with value: 0.7902305670021997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:30:55<23:40:53, 7750.29s/it]

[I 2026-02-20 18:41:44,367] Trial 36 finished with value: 0.7891230970354912 and parameters: {'layer1': 298, 'layer2': 370, 'layer3': 220, 'activation': 'identity', 'solver': 'adam', 'lr': 1.3943242289664814e-05}. Best is trial 27 with value: 0.7902305670021997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:31:34<23:40:53, 7750.29s/it]

[I 2026-02-20 18:42:23,175] Trial 37 finished with value: 0.6084440645843747 and parameters: {'layer1': 290, 'layer2': 377, 'layer3': 112, 'activation': 'identity', 'solver': 'sgd', 'lr': 1.1226494290564183e-05}. Best is trial 27 with value: 0.7902305670021997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:33:21<23:40:53, 7750.29s/it]

[I 2026-02-20 18:44:10,369] Trial 38 finished with value: 0.787369030524968 and parameters: {'layer1': 401, 'layer2': 483, 'layer3': 225, 'activation': 'identity', 'solver': 'adam', 'lr': 5.047366229756431e-06}. Best is trial 27 with value: 0.7902305670021997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:34:38<23:40:53, 7750.29s/it]

[I 2026-02-20 18:45:27,748] Trial 39 finished with value: 0.6101985436142348 and parameters: {'layer1': 282, 'layer2': 253, 'layer3': 175, 'activation': 'identity', 'solver': 'sgd', 'lr': 2.659522460491621e-06}. Best is trial 27 with value: 0.7902305670021997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:35:08<23:40:53, 7750.29s/it]

[I 2026-02-20 18:45:57,648] Trial 40 finished with value: 0.7815323376633483 and parameters: {'layer1': 336, 'layer2': 425, 'layer3': 41, 'activation': 'identity', 'solver': 'adam', 'lr': 8.253929962087191e-05}. Best is trial 27 with value: 0.7902305670021997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:36:07<23:40:53, 7750.29s/it]

[I 2026-02-20 18:46:56,299] Trial 41 finished with value: 0.7873717982128081 and parameters: {'layer1': 393, 'layer2': 369, 'layer3': 203, 'activation': 'identity', 'solver': 'adam', 'lr': 1.3856207223231033e-05}. Best is trial 27 with value: 0.7902305670021997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:36:43<23:40:53, 7750.29s/it]

[I 2026-02-20 18:47:32,822] Trial 42 finished with value: 0.7857962578918365 and parameters: {'layer1': 169, 'layer2': 312, 'layer3': 252, 'activation': 'identity', 'solver': 'adam', 'lr': 2.3462890954574186e-05}. Best is trial 27 with value: 0.7902305670021997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:37:07<23:40:53, 7750.29s/it]

[I 2026-02-20 18:47:56,373] Trial 43 finished with value: 0.5945172904007523 and parameters: {'layer1': 273, 'layer2': 280, 'layer3': 163, 'activation': 'relu', 'solver': 'adam', 'lr': 7.613524813424661e-06}. Best is trial 27 with value: 0.7902305670021997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:38:12<23:40:53, 7750.29s/it]

[I 2026-02-20 18:49:00,893] Trial 44 finished with value: 0.6150542909759056 and parameters: {'layer1': 324, 'layer2': 452, 'layer3': 205, 'activation': 'identity', 'solver': 'sgd', 'lr': 4.521934386558496e-06}. Best is trial 27 with value: 0.7902305670021997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:38:34<23:40:53, 7750.29s/it]

[I 2026-02-20 18:49:23,822] Trial 45 finished with value: 0.5940221219711511 and parameters: {'layer1': 160, 'layer2': 398, 'layer3': 233, 'activation': 'logistic', 'solver': 'adam', 'lr': 1.0239152815447298e-06}. Best is trial 27 with value: 0.7902305670021997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:39:41<23:40:53, 7750.29s/it]

[I 2026-02-20 18:50:30,517] Trial 46 finished with value: 0.7893627159298899 and parameters: {'layer1': 459, 'layer2': 204, 'layer3': 115, 'activation': 'identity', 'solver': 'adam', 'lr': 1.4376723277689849e-05}. Best is trial 27 with value: 0.7902305670021997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:40:21<23:40:53, 7750.29s/it]

[I 2026-02-20 18:51:10,070] Trial 47 finished with value: 0.7846455153370785 and parameters: {'layer1': 480, 'layer2': 206, 'layer3': 108, 'activation': 'identity', 'solver': 'adam', 'lr': 5.68988617562795e-05}. Best is trial 27 with value: 0.7902305670021997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:40:41<23:40:53, 7750.29s/it]

[I 2026-02-20 18:51:30,740] Trial 48 finished with value: 0.597210966345602 and parameters: {'layer1': 457, 'layer2': 264, 'layer3': 61, 'activation': 'identity', 'solver': 'sgd', 'lr': 0.0013840030488900187}. Best is trial 27 with value: 0.7902305670021997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:41:28<23:40:53, 7750.29s/it]

[I 2026-02-20 18:52:17,667] Trial 49 finished with value: 0.7836622570030694 and parameters: {'layer1': 440, 'layer2': 205, 'layer3': 136, 'activation': 'identity', 'solver': 'adam', 'lr': 2.8403745345120803e-05}. Best is trial 27 with value: 0.7902305670021997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:42:26<23:40:53, 7750.29s/it]

[I 2026-02-20 18:53:15,841] Trial 50 finished with value: 0.7875842642385824 and parameters: {'layer1': 377, 'layer2': 300, 'layer3': 115, 'activation': 'identity', 'solver': 'adam', 'lr': 1.608226900566513e-05}. Best is trial 27 with value: 0.7902305670021997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:43:20<23:40:53, 7750.29s/it]

[I 2026-02-20 18:54:09,384] Trial 51 finished with value: 0.785820850515371 and parameters: {'layer1': 197, 'layer2': 355, 'layer3': 173, 'activation': 'identity', 'solver': 'adam', 'lr': 1.236349332483461e-05}. Best is trial 27 with value: 0.7902305670021997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:43:42<23:40:53, 7750.29s/it]

[I 2026-02-20 18:54:31,313] Trial 52 finished with value: 0.5940221219711511 and parameters: {'layer1': 222, 'layer2': 232, 'layer3': 192, 'activation': 'logistic', 'solver': 'adam', 'lr': 8.916694747801473e-06}. Best is trial 27 with value: 0.7902305670021997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:44:18<23:40:53, 7750.29s/it]

[I 2026-02-20 18:55:06,922] Trial 53 finished with value: 0.7838348602781049 and parameters: {'layer1': 38, 'layer2': 121, 'layer3': 341, 'activation': 'identity', 'solver': 'adam', 'lr': 2.9025699944928458e-05}. Best is trial 27 with value: 0.7902305670021997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:45:16<23:40:53, 7750.29s/it]

[I 2026-02-20 18:56:05,562] Trial 54 finished with value: 0.7485815946840005 and parameters: {'layer1': 105, 'layer2': 36, 'layer3': 86, 'activation': 'relu', 'solver': 'adam', 'lr': 1.6945909040963412e-05}. Best is trial 27 with value: 0.7902305670021997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:46:06<23:40:53, 7750.29s/it]

[I 2026-02-20 18:56:55,127] Trial 55 finished with value: 0.6689456689907585 and parameters: {'layer1': 179, 'layer2': 159, 'layer3': 152, 'activation': 'identity', 'solver': 'adam', 'lr': 5.845189546726069e-06}. Best is trial 27 with value: 0.7902305670021997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:46:29<23:40:53, 7750.29s/it]

[I 2026-02-20 18:57:18,355] Trial 56 finished with value: 0.7823252778230235 and parameters: {'layer1': 146, 'layer2': 193, 'layer3': 212, 'activation': 'identity', 'solver': 'adam', 'lr': 0.00014939998682159393}. Best is trial 27 with value: 0.7902305670021997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:47:24<23:40:53, 7750.29s/it]

[I 2026-02-20 18:58:13,209] Trial 57 finished with value: 0.7498035796248754 and parameters: {'layer1': 239, 'layer2': 249, 'layer3': 245, 'activation': 'logistic', 'solver': 'adam', 'lr': 6.582147047188387e-05}. Best is trial 27 with value: 0.7902305670021997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:48:04<23:40:53, 7750.29s/it]

[I 2026-02-20 18:58:53,218] Trial 58 finished with value: 0.6017523227148973 and parameters: {'layer1': 429, 'layer2': 271, 'layer3': 50, 'activation': 'identity', 'solver': 'sgd', 'lr': 2.063577509577285e-05}. Best is trial 27 with value: 0.7902305670021997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:50:02<23:40:53, 7750.29s/it]

[I 2026-02-20 19:00:51,581] Trial 59 finished with value: 0.7485857434782432 and parameters: {'layer1': 500, 'layer2': 92, 'layer3': 300, 'activation': 'relu', 'solver': 'adam', 'lr': 8.275099690843508e-06}. Best is trial 27 with value: 0.7902305670021997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:50:40<23:40:53, 7750.29s/it]

[I 2026-02-20 19:01:29,136] Trial 60 finished with value: 0.7831056949394729 and parameters: {'layer1': 260, 'layer2': 444, 'layer3': 328, 'activation': 'identity', 'solver': 'adam', 'lr': 3.012727269496156e-05}. Best is trial 27 with value: 0.7902305670021997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:51:37<23:40:53, 7750.29s/it]

[I 2026-02-20 19:02:26,447] Trial 61 finished with value: 0.7885017453966979 and parameters: {'layer1': 371, 'layer2': 301, 'layer3': 112, 'activation': 'identity', 'solver': 'adam', 'lr': 1.5280741037122157e-05}. Best is trial 27 with value: 0.7902305670021997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:52:39<23:40:53, 7750.29s/it]

[I 2026-02-20 19:03:28,619] Trial 62 finished with value: 0.786275439620658 and parameters: {'layer1': 351, 'layer2': 319, 'layer3': 98, 'activation': 'identity', 'solver': 'adam', 'lr': 1.351654970732913e-05}. Best is trial 27 with value: 0.7902305670021997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:53:29<23:40:53, 7750.29s/it]

[I 2026-02-20 19:04:18,021] Trial 63 finished with value: 0.7885365246324518 and parameters: {'layer1': 370, 'layer2': 292, 'layer3': 130, 'activation': 'identity', 'solver': 'adam', 'lr': 1.977004550750977e-05}. Best is trial 27 with value: 0.7902305670021997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:53:53<23:40:53, 7750.29s/it]

[I 2026-02-20 19:04:42,146] Trial 64 finished with value: 0.5945172904007522 and parameters: {'layer1': 311, 'layer2': 293, 'layer3': 128, 'activation': 'identity', 'solver': 'adam', 'lr': 3.7218766068851545e-06}. Best is trial 27 with value: 0.7902305670021997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:55:27<23:40:53, 7750.29s/it]

[I 2026-02-20 19:06:16,778] Trial 65 finished with value: 0.7879096849282339 and parameters: {'layer1': 413, 'layer2': 344, 'layer3': 184, 'activation': 'identity', 'solver': 'adam', 'lr': 6.198526390421138e-06}. Best is trial 27 with value: 0.7902305670021997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:56:31<23:40:53, 7750.29s/it]

[I 2026-02-20 19:07:20,409] Trial 66 finished with value: 0.7869471561631316 and parameters: {'layer1': 307, 'layer2': 221, 'layer3': 149, 'activation': 'identity', 'solver': 'adam', 'lr': 1.0566348929227077e-05}. Best is trial 27 with value: 0.7902305670021997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:57:23<23:40:53, 7750.29s/it]

[I 2026-02-20 19:08:12,838] Trial 67 finished with value: 0.7879952242266117 and parameters: {'layer1': 368, 'layer2': 304, 'layer3': 122, 'activation': 'identity', 'solver': 'adam', 'lr': 2.0950958309909374e-05}. Best is trial 27 with value: 0.7902305670021997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:58:02<23:40:53, 7750.29s/it]

[I 2026-02-20 19:08:51,727] Trial 68 finished with value: 0.786527314935048 and parameters: {'layer1': 346, 'layer2': 284, 'layer3': 21, 'activation': 'identity', 'solver': 'adam', 'lr': 3.263472098745097e-05}. Best is trial 27 with value: 0.7902305670021997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:58:31<23:40:53, 7750.29s/it]

[I 2026-02-20 19:09:20,104] Trial 69 finished with value: 0.5946505687442157 and parameters: {'layer1': 439, 'layer2': 366, 'layer3': 172, 'activation': 'identity', 'solver': 'adam', 'lr': 1.8951469492936757e-06}. Best is trial 27 with value: 0.7902305670021997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [7:59:29<23:40:53, 7750.29s/it]

[I 2026-02-20 19:10:18,186] Trial 70 finished with value: 0.7887721265401773 and parameters: {'layer1': 378, 'layer2': 332, 'layer3': 75, 'activation': 'identity', 'solver': 'adam', 'lr': 1.4602197242050624e-05}. Best is trial 27 with value: 0.7902305670021997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [8:00:26<23:40:53, 7750.29s/it]

[I 2026-02-20 19:11:15,109] Trial 71 finished with value: 0.786962022464625 and parameters: {'layer1': 369, 'layer2': 336, 'layer3': 71, 'activation': 'identity', 'solver': 'adam', 'lr': 1.612394018465326e-05}. Best is trial 27 with value: 0.7902305670021997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [8:01:31<23:40:53, 7750.29s/it]

[I 2026-02-20 19:12:20,052] Trial 72 finished with value: 0.7870669426996795 and parameters: {'layer1': 394, 'layer2': 394, 'layer3': 96, 'activation': 'identity', 'solver': 'adam', 'lr': 1.2275767772714568e-05}. Best is trial 27 with value: 0.7902305670021997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [8:02:59<23:40:53, 7750.29s/it]

[I 2026-02-20 19:13:47,912] Trial 73 finished with value: 0.7887680559920145 and parameters: {'layer1': 413, 'layer2': 333, 'layer3': 138, 'activation': 'identity', 'solver': 'adam', 'lr': 7.841220099846394e-06}. Best is trial 27 with value: 0.7902305670021997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [8:04:46<23:40:53, 7750.29s/it]

[I 2026-02-20 19:15:35,371] Trial 74 finished with value: 0.7888440075010392 and parameters: {'layer1': 412, 'layer2': 360, 'layer3': 107, 'activation': 'identity', 'solver': 'adam', 'lr': 4.784779119869312e-06}. Best is trial 27 with value: 0.7902305670021997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [8:05:15<23:40:53, 7750.29s/it]

[I 2026-02-20 19:16:04,335] Trial 75 finished with value: 0.5940221219711511 and parameters: {'layer1': 466, 'layer2': 364, 'layer3': 140, 'activation': 'identity', 'solver': 'adam', 'lr': 2.8682787058401176e-06}. Best is trial 27 with value: 0.7902305670021997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [8:06:42<23:40:53, 7750.29s/it]

[I 2026-02-20 19:17:31,453] Trial 76 finished with value: 0.7869749828917808 and parameters: {'layer1': 419, 'layer2': 326, 'layer3': 38, 'activation': 'identity', 'solver': 'adam', 'lr': 7.901217992290192e-06}. Best is trial 27 with value: 0.7902305670021997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [8:08:54<23:40:53, 7750.29s/it]

[I 2026-02-20 19:19:43,353] Trial 77 finished with value: 0.7519679727443845 and parameters: {'layer1': 451, 'layer2': 393, 'layer3': 100, 'activation': 'identity', 'solver': 'adam', 'lr': 4.08513520956119e-06}. Best is trial 27 with value: 0.7902305670021997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [8:10:12<23:40:53, 7750.29s/it]

[I 2026-02-20 19:21:01,678] Trial 78 finished with value: 0.6071100084115197 and parameters: {'layer1': 407, 'layer2': 383, 'layer3': 68, 'activation': 'identity', 'solver': 'sgd', 'lr': 5.0621386795203455e-06}. Best is trial 27 with value: 0.7902305670021997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [8:10:42<23:40:53, 7750.29s/it]

[I 2026-02-20 19:21:31,201] Trial 79 finished with value: 0.5940221219711511 and parameters: {'layer1': 387, 'layer2': 414, 'layer3': 81, 'activation': 'logistic', 'solver': 'adam', 'lr': 6.451840867785116e-06}. Best is trial 27 with value: 0.7902305670021997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [8:12:07<23:40:53, 7750.29s/it]

[I 2026-02-20 19:22:56,083] Trial 80 finished with value: 0.7881523626761353 and parameters: {'layer1': 428, 'layer2': 337, 'layer3': 53, 'activation': 'identity', 'solver': 'adam', 'lr': 9.26710779831767e-06}. Best is trial 27 with value: 0.7902305670021997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [8:12:53<23:40:53, 7750.29s/it]

[I 2026-02-20 19:23:42,133] Trial 81 finished with value: 0.786480705452418 and parameters: {'layer1': 362, 'layer2': 318, 'layer3': 120, 'activation': 'identity', 'solver': 'adam', 'lr': 2.5050451878272257e-05}. Best is trial 27 with value: 0.7902305670021997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [8:13:48<23:40:53, 7750.29s/it]

[I 2026-02-20 19:24:37,091] Trial 82 finished with value: 0.7853660396418916 and parameters: {'layer1': 359, 'layer2': 358, 'layer3': 160, 'activation': 'identity', 'solver': 'adam', 'lr': 1.4773546499637682e-05}. Best is trial 27 with value: 0.7902305670021997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [8:14:23<23:40:53, 7750.29s/it]

[I 2026-02-20 19:25:12,210] Trial 83 finished with value: 0.7841034944359232 and parameters: {'layer1': 335, 'layer2': 290, 'layer3': 139, 'activation': 'identity', 'solver': 'adam', 'lr': 4.837544332172948e-05}. Best is trial 27 with value: 0.7902305670021997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [8:15:18<23:40:53, 7750.29s/it]

[I 2026-02-20 19:26:07,714] Trial 84 finished with value: 0.7868734938908817 and parameters: {'layer1': 470, 'layer2': 344, 'layer3': 108, 'activation': 'identity', 'solver': 'adam', 'lr': 1.9421589166676294e-05}. Best is trial 27 with value: 0.7902305670021997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [8:17:22<23:40:53, 7750.29s/it]

[I 2026-02-20 19:28:11,358] Trial 85 finished with value: 0.7908174974607911 and parameters: {'layer1': 385, 'layer2': 307, 'layer3': 85, 'activation': 'identity', 'solver': 'adam', 'lr': 5.0493565767179234e-06}. Best is trial 85 with value: 0.7908174974607911.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [8:17:49<23:40:53, 7750.29s/it]

[I 2026-02-20 19:28:38,241] Trial 86 finished with value: 0.5955115732170008 and parameters: {'layer1': 385, 'layer2': 262, 'layer3': 83, 'activation': 'relu', 'solver': 'adam', 'lr': 3.424551901652001e-06}. Best is trial 85 with value: 0.7908174974607911.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [8:19:56<23:40:53, 7750.29s/it]

[I 2026-02-20 19:30:45,107] Trial 87 finished with value: 0.7901923080785047 and parameters: {'layer1': 421, 'layer2': 311, 'layer3': 128, 'activation': 'identity', 'solver': 'adam', 'lr': 4.8355797823442414e-06}. Best is trial 85 with value: 0.7908174974607911.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [8:20:22<23:40:53, 7750.29s/it]

[I 2026-02-20 19:31:11,715] Trial 88 finished with value: 0.597080122322235 and parameters: {'layer1': 494, 'layer2': 311, 'layer3': 30, 'activation': 'identity', 'solver': 'adam', 'lr': 1.4101964890563704e-06}. Best is trial 85 with value: 0.7908174974607911.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [8:20:45<23:40:53, 7750.29s/it]

[I 2026-02-20 19:31:34,337] Trial 89 finished with value: 0.60404465577006 and parameters: {'layer1': 418, 'layer2': 330, 'layer3': 61, 'activation': 'identity', 'solver': 'sgd', 'lr': 4.967321163747992e-06}. Best is trial 85 with value: 0.7908174974607911.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [8:22:32<23:40:53, 7750.29s/it]

[I 2026-02-20 19:33:20,985] Trial 90 finished with value: 0.788439773339115 and parameters: {'layer1': 439, 'layer2': 351, 'layer3': 94, 'activation': 'identity', 'solver': 'adam', 'lr': 7.060727159651076e-06}. Best is trial 85 with value: 0.7908174974607911.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [8:22:58<23:40:53, 7750.29s/it]

[I 2026-02-20 19:33:47,352] Trial 91 finished with value: 0.5942504671054438 and parameters: {'layer1': 395, 'layer2': 376, 'layer3': 132, 'activation': 'identity', 'solver': 'adam', 'lr': 2.5936976974366902e-06}. Best is trial 85 with value: 0.7908174974607911.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [8:24:16<23:40:53, 7750.29s/it]

[I 2026-02-20 19:35:05,535] Trial 92 finished with value: 0.7868603132839999 and parameters: {'layer1': 408, 'layer2': 247, 'layer3': 164, 'activation': 'identity', 'solver': 'adam', 'lr': 9.578976797717856e-06}. Best is trial 85 with value: 0.7908174974607911.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [8:26:07<23:40:53, 7750.29s/it]

[I 2026-02-20 19:36:56,559] Trial 93 finished with value: 0.7887915094794996 and parameters: {'layer1': 380, 'layer2': 310, 'layer3': 149, 'activation': 'identity', 'solver': 'adam', 'lr': 5.4135729567161374e-06}. Best is trial 85 with value: 0.7908174974607911.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [8:27:54<23:40:53, 7750.29s/it]

[I 2026-02-20 19:38:43,242] Trial 94 finished with value: 0.7896430209131063 and parameters: {'layer1': 422, 'layer2': 270, 'layer3': 145, 'activation': 'identity', 'solver': 'adam', 'lr': 5.675059687999399e-06}. Best is trial 85 with value: 0.7908174974607911.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [8:28:22<23:40:53, 7750.29s/it]

[I 2026-02-20 19:39:11,702] Trial 95 finished with value: 0.5943838294593131 and parameters: {'layer1': 451, 'layer2': 271, 'layer3': 149, 'activation': 'identity', 'solver': 'adam', 'lr': 2.115465336366376e-06}. Best is trial 85 with value: 0.7908174974607911.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [8:30:21<23:40:53, 7750.29s/it]

[I 2026-02-20 19:41:10,159] Trial 96 finished with value: 0.7883723417694988 and parameters: {'layer1': 427, 'layer2': 196, 'layer3': 121, 'activation': 'identity', 'solver': 'adam', 'lr': 5.3717259662737375e-06}. Best is trial 85 with value: 0.7908174974607911.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [8:30:51<23:40:53, 7750.29s/it]

[I 2026-02-20 19:41:40,808] Trial 97 finished with value: 0.5940221219711511 and parameters: {'layer1': 382, 'layer2': 233, 'layer3': 186, 'activation': 'logistic', 'solver': 'adam', 'lr': 4.355195421668343e-06}. Best is trial 85 with value: 0.7908174974607911.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [8:31:20<23:40:53, 7750.29s/it]

[I 2026-02-20 19:42:09,468] Trial 98 finished with value: 0.5940221219711511 and parameters: {'layer1': 480, 'layer2': 308, 'layer3': 107, 'activation': 'identity', 'solver': 'adam', 'lr': 2.9096253611676876e-06}. Best is trial 85 with value: 0.7908174974607911.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [8:31:47<23:40:53, 7750.29s/it]

[I 2026-02-20 19:42:36,754] Trial 99 finished with value: 0.5940221219711511 and parameters: {'layer1': 400, 'layer2': 319, 'layer3': 149, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.00861774297846752}. Best is trial 85 with value: 0.7908174974607911.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [8:32:12<23:40:53, 7750.29s/it]

[I 2026-02-20 19:43:00,920] Trial 100 finished with value: 0.5940221219711511 and parameters: {'layer1': 328, 'layer2': 275, 'layer3': 87, 'activation': 'relu', 'solver': 'adam', 'lr': 3.6718461810590465e-06}. Best is trial 85 with value: 0.7908174974607911.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [8:33:35<23:40:53, 7750.29s/it]

[I 2026-02-20 19:44:24,064] Trial 101 finished with value: 0.7871775129301893 and parameters: {'layer1': 421, 'layer2': 330, 'layer3': 166, 'activation': 'identity', 'solver': 'adam', 'lr': 7.3617367752729075e-06}. Best is trial 85 with value: 0.7908174974607911.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [8:33:49<23:40:53, 7750.29s/it]

[I 2026-02-20 19:44:38,134] Trial 102 finished with value: 0.5989133430521099 and parameters: {'layer1': 10, 'layer2': 348, 'layer3': 124, 'activation': 'identity', 'solver': 'adam', 'lr': 5.849238522734323e-06}. Best is trial 85 with value: 0.7908174974607911.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [8:34:56<23:40:53, 7750.29s/it]

[I 2026-02-20 19:45:45,020] Trial 103 finished with value: 0.7878057973857133 and parameters: {'layer1': 404, 'layer2': 372, 'layer3': 102, 'activation': 'identity', 'solver': 'adam', 'lr': 1.0965311246319536e-05}. Best is trial 85 with value: 0.7908174974607911.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [8:36:25<23:40:53, 7750.29s/it]

[I 2026-02-20 19:47:14,471] Trial 104 finished with value: 0.7893530134178622 and parameters: {'layer1': 443, 'layer2': 167, 'layer3': 138, 'activation': 'identity', 'solver': 'adam', 'lr': 8.52323058199548e-06}. Best is trial 85 with value: 0.7908174974607911.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [8:36:57<23:40:53, 7750.29s/it]

[I 2026-02-20 19:47:46,263] Trial 105 finished with value: 0.7696166098889416 and parameters: {'layer1': 459, 'layer2': 164, 'layer3': 266, 'activation': 'identity', 'solver': 'adam', 'lr': 0.001067171069681055}. Best is trial 85 with value: 0.7908174974607911.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [8:38:42<23:40:53, 7750.29s/it]

[I 2026-02-20 19:49:31,177] Trial 106 finished with value: 0.7482400619766585 and parameters: {'layer1': 433, 'layer2': 180, 'layer3': 117, 'activation': 'identity', 'solver': 'adam', 'lr': 4.71689902374733e-06}. Best is trial 85 with value: 0.7908174974607911.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [8:39:46<23:40:53, 7750.29s/it]

[I 2026-02-20 19:50:35,435] Trial 107 finished with value: 0.7870669069923986 and parameters: {'layer1': 443, 'layer2': 132, 'layer3': 195, 'activation': 'identity', 'solver': 'adam', 'lr': 1.270993758712232e-05}. Best is trial 85 with value: 0.7908174974607911.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [8:40:18<23:40:53, 7750.29s/it]

[I 2026-02-20 19:51:07,742] Trial 108 finished with value: 0.5079783420176047 and parameters: {'layer1': 26, 'layer2': 214, 'layer3': 178, 'activation': 'identity', 'solver': 'sgd', 'lr': 8.618683319358072e-06}. Best is trial 85 with value: 0.7908174974607911.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [8:40:46<23:40:53, 7750.29s/it]

[I 2026-02-20 19:51:35,314] Trial 109 finished with value: 0.5964119580414027 and parameters: {'layer1': 465, 'layer2': 200, 'layer3': 76, 'activation': 'identity', 'solver': 'adam', 'lr': 2.441554042770778e-06}. Best is trial 85 with value: 0.7908174974607911.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [8:41:05<23:40:53, 7750.29s/it]

[I 2026-02-20 19:51:54,828] Trial 110 finished with value: 0.7692302239615101 and parameters: {'layer1': 118, 'layer2': 241, 'layer3': 147, 'activation': 'identity', 'solver': 'adam', 'lr': 0.004782403106542511}. Best is trial 85 with value: 0.7908174974607911.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [8:42:31<23:40:53, 7750.29s/it]

[I 2026-02-20 19:53:20,606] Trial 111 finished with value: 0.7884202689418452 and parameters: {'layer1': 450, 'layer2': 337, 'layer3': 135, 'activation': 'identity', 'solver': 'adam', 'lr': 7.403541688744816e-06}. Best is trial 85 with value: 0.7908174974607911.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [8:44:20<23:40:53, 7750.29s/it]

[I 2026-02-20 19:55:08,975] Trial 112 finished with value: 0.7884442431037126 and parameters: {'layer1': 412, 'layer2': 152, 'layer3': 155, 'activation': 'identity', 'solver': 'adam', 'lr': 6.307935216674785e-06}. Best is trial 85 with value: 0.7908174974607911.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [8:44:45<23:40:53, 7750.29s/it]

[I 2026-02-20 19:55:34,353] Trial 113 finished with value: 0.5940221219711511 and parameters: {'layer1': 381, 'layer2': 287, 'layer3': 141, 'activation': 'identity', 'solver': 'adam', 'lr': 3.268734147460577e-06}. Best is trial 85 with value: 0.7908174974607911.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [8:45:46<23:40:53, 7750.29s/it]

[I 2026-02-20 19:56:35,489] Trial 114 finished with value: 0.7890625681064248 and parameters: {'layer1': 263, 'layer2': 319, 'layer3': 213, 'activation': 'identity', 'solver': 'adam', 'lr': 9.398448824013173e-06}. Best is trial 85 with value: 0.7908174974607911.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [8:46:48<23:40:53, 7750.29s/it]

[I 2026-02-20 19:57:37,042] Trial 115 finished with value: 0.7870630411916973 and parameters: {'layer1': 274, 'layer2': 184, 'layer3': 220, 'activation': 'identity', 'solver': 'adam', 'lr': 1.0974472274895032e-05}. Best is trial 85 with value: 0.7908174974607911.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [8:47:51<23:40:53, 7750.29s/it]

[I 2026-02-20 19:58:40,831] Trial 116 finished with value: 0.7877804350913153 and parameters: {'layer1': 250, 'layer2': 299, 'layer3': 237, 'activation': 'identity', 'solver': 'adam', 'lr': 9.68550149895023e-06}. Best is trial 85 with value: 0.7908174974607911.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [8:48:48<23:40:53, 7750.29s/it]

[I 2026-02-20 19:59:37,058] Trial 117 finished with value: 0.7867344350864787 and parameters: {'layer1': 259, 'layer2': 317, 'layer3': 205, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.4099789326012453e-05}. Best is trial 85 with value: 0.7908174974607911.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [8:49:29<23:40:53, 7750.29s/it]

[I 2026-02-20 20:00:18,116] Trial 118 finished with value: 0.786970049214595 and parameters: {'layer1': 227, 'layer2': 259, 'layer3': 112, 'activation': 'identity', 'solver': 'adam', 'lr': 2.456057893246775e-05}. Best is trial 85 with value: 0.7908174974607911.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [8:51:08<23:40:53, 7750.29s/it]

[I 2026-02-20 20:01:57,382] Trial 119 finished with value: 0.789123118744541 and parameters: {'layer1': 299, 'layer2': 360, 'layer3': 91, 'activation': 'identity', 'solver': 'adam', 'lr': 5.6427878262552755e-06}. Best is trial 85 with value: 0.7908174974607911.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [8:51:39<23:40:53, 7750.29s/it]

[I 2026-02-20 20:02:28,815] Trial 120 finished with value: 0.5940221219711511 and parameters: {'layer1': 268, 'layer2': 401, 'layer3': 95, 'activation': 'logistic', 'solver': 'adam', 'lr': 3.932486142086622e-06}. Best is trial 85 with value: 0.7908174974607911.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [8:53:01<23:40:53, 7750.29s/it]

[I 2026-02-20 20:03:50,633] Trial 121 finished with value: 0.7502772039220831 and parameters: {'layer1': 287, 'layer2': 359, 'layer3': 64, 'activation': 'identity', 'solver': 'adam', 'lr': 5.330565789038426e-06}. Best is trial 85 with value: 0.7908174974607911.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [8:54:36<23:40:53, 7750.29s/it]

[I 2026-02-20 20:05:25,286] Trial 122 finished with value: 0.7889946593791427 and parameters: {'layer1': 322, 'layer2': 384, 'layer3': 91, 'activation': 'identity', 'solver': 'adam', 'lr': 6.511703801691288e-06}. Best is trial 85 with value: 0.7908174974607911.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [8:56:07<23:40:53, 7750.29s/it]

[I 2026-02-20 20:06:56,791] Trial 123 finished with value: 0.788679724417212 and parameters: {'layer1': 293, 'layer2': 386, 'layer3': 117, 'activation': 'identity', 'solver': 'adam', 'lr': 6.621193850553499e-06}. Best is trial 85 with value: 0.7908174974607911.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [8:57:11<23:40:53, 7750.29s/it]

[I 2026-02-20 20:08:00,395] Trial 124 finished with value: 0.7093289770205333 and parameters: {'layer1': 306, 'layer2': 405, 'layer3': 259, 'activation': 'identity', 'solver': 'adam', 'lr': 4.198860211910171e-06}. Best is trial 85 with value: 0.7908174974607911.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [8:58:48<23:40:53, 7750.29s/it]

[I 2026-02-20 20:09:37,649] Trial 125 finished with value: 0.7888107178687046 and parameters: {'layer1': 318, 'layer2': 365, 'layer3': 499, 'activation': 'identity', 'solver': 'adam', 'lr': 5.674605973269082e-06}. Best is trial 85 with value: 0.7908174974607911.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [9:00:01<23:40:53, 7750.29s/it]

[I 2026-02-20 20:10:50,039] Trial 126 finished with value: 0.7891334399330641 and parameters: {'layer1': 304, 'layer2': 379, 'layer3': 90, 'activation': 'identity', 'solver': 'adam', 'lr': 8.650975642668379e-06}. Best is trial 85 with value: 0.7908174974607911.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [9:01:12<23:40:53, 7750.29s/it]

[I 2026-02-20 20:12:01,511] Trial 127 finished with value: 0.7874243891958049 and parameters: {'layer1': 302, 'layer2': 423, 'layer3': 104, 'activation': 'identity', 'solver': 'adam', 'lr': 8.658323114939999e-06}. Best is trial 85 with value: 0.7908174974607911.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [9:01:43<23:40:53, 7750.29s/it]

[I 2026-02-20 20:12:31,981] Trial 128 finished with value: 0.5019039824423934 and parameters: {'layer1': 277, 'layer2': 432, 'layer3': 89, 'activation': 'relu', 'solver': 'sgd', 'lr': 1.7149994503791392e-05}. Best is trial 85 with value: 0.7908174974607911.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [9:02:51<23:40:53, 7750.29s/it]

[I 2026-02-20 20:13:40,295] Trial 129 finished with value: 0.7883942600913343 and parameters: {'layer1': 300, 'layer2': 373, 'layer3': 54, 'activation': 'identity', 'solver': 'adam', 'lr': 1.1078305286953914e-05}. Best is trial 85 with value: 0.7908174974607911.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [9:03:07<23:40:53, 7750.29s/it]

[I 2026-02-20 20:13:55,944] Trial 130 finished with value: 0.5940221219711511 and parameters: {'layer1': 90, 'layer2': 171, 'layer3': 126, 'activation': 'identity', 'solver': 'adam', 'lr': 3.278878192971763e-06}. Best is trial 85 with value: 0.7908174974607911.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [9:04:22<23:40:53, 7750.29s/it]

[I 2026-02-20 20:15:11,543] Trial 131 finished with value: 0.7882499557398579 and parameters: {'layer1': 320, 'layer2': 387, 'layer3': 480, 'activation': 'identity', 'solver': 'adam', 'lr': 6.40527706225612e-06}. Best is trial 85 with value: 0.7908174974607911.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [9:05:29<23:40:53, 7750.29s/it]

[I 2026-02-20 20:16:18,588] Trial 132 finished with value: 0.7894427848338215 and parameters: {'layer1': 341, 'layer2': 364, 'layer3': 419, 'activation': 'identity', 'solver': 'adam', 'lr': 8.155086020639675e-06}. Best is trial 85 with value: 0.7908174974607911.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [9:06:40<23:40:53, 7750.29s/it]

[I 2026-02-20 20:17:29,441] Trial 133 finished with value: 0.7880655137198691 and parameters: {'layer1': 333, 'layer2': 354, 'layer3': 430, 'activation': 'identity', 'solver': 'adam', 'lr': 8.014371617343853e-06}. Best is trial 85 with value: 0.7908174974607911.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [9:07:42<23:40:53, 7750.29s/it]

[I 2026-02-20 20:18:31,059] Trial 134 finished with value: 0.7866538513622574 and parameters: {'layer1': 348, 'layer2': 380, 'layer3': 385, 'activation': 'identity', 'solver': 'adam', 'lr': 9.585722837262863e-06}. Best is trial 85 with value: 0.7908174974607911.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [9:09:20<23:40:53, 7750.29s/it]

[I 2026-02-20 20:20:09,162] Trial 135 finished with value: 0.7493208541862018 and parameters: {'layer1': 339, 'layer2': 348, 'layer3': 82, 'activation': 'identity', 'solver': 'adam', 'lr': 4.640192031213405e-06}. Best is trial 85 with value: 0.7908174974607911.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [9:10:10<23:40:53, 7750.29s/it]

[I 2026-02-20 20:20:59,697] Trial 136 finished with value: 0.7882446992306381 and parameters: {'layer1': 239, 'layer2': 393, 'layer3': 295, 'activation': 'identity', 'solver': 'adam', 'lr': 1.2296272228546778e-05}. Best is trial 85 with value: 0.7908174974607911.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [9:11:25<23:40:53, 7750.29s/it]

[I 2026-02-20 20:22:14,547] Trial 137 finished with value: 0.7865125923574221 and parameters: {'layer1': 311, 'layer2': 366, 'layer3': 98, 'activation': 'identity', 'solver': 'adam', 'lr': 7.782849074102755e-06}. Best is trial 85 with value: 0.7908174974607911.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [9:12:38<23:40:53, 7750.29s/it]

[I 2026-02-20 20:23:27,528] Trial 138 finished with value: 0.7849370082405478 and parameters: {'layer1': 291, 'layer2': 342, 'layer3': 399, 'activation': 'identity', 'solver': 'adam', 'lr': 6.659745135201773e-06}. Best is trial 85 with value: 0.7908174974607911.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [9:13:20<23:40:53, 7750.29s/it]

[I 2026-02-20 20:24:09,828] Trial 139 finished with value: 0.7850492032103098 and parameters: {'layer1': 67, 'layer2': 406, 'layer3': 113, 'activation': 'identity', 'solver': 'adam', 'lr': 1.8025523580933252e-05}. Best is trial 85 with value: 0.7908174974607911.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [9:14:26<23:40:53, 7750.29s/it]

[I 2026-02-20 20:25:15,522] Trial 140 finished with value: 0.7888879148624961 and parameters: {'layer1': 267, 'layer2': 360, 'layer3': 130, 'activation': 'identity', 'solver': 'adam', 'lr': 9.67117624874011e-06}. Best is trial 85 with value: 0.7908174974607911.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [9:15:34<23:40:53, 7750.29s/it]

[I 2026-02-20 20:26:23,397] Trial 141 finished with value: 0.7915712790577161 and parameters: {'layer1': 265, 'layer2': 382, 'layer3': 128, 'activation': 'identity', 'solver': 'adam', 'lr': 9.77803888504039e-06}. Best is trial 141 with value: 0.7915712790577161.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [9:16:40<23:40:53, 7750.29s/it]

[I 2026-02-20 20:27:28,932] Trial 142 finished with value: 0.7883092574653492 and parameters: {'layer1': 265, 'layer2': 378, 'layer3': 131, 'activation': 'identity', 'solver': 'adam', 'lr': 9.985141635764901e-06}. Best is trial 141 with value: 0.7915712790577161.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [9:17:38<23:40:53, 7750.29s/it]

[I 2026-02-20 20:28:27,047] Trial 143 finished with value: 0.7878612759481306 and parameters: {'layer1': 282, 'layer2': 389, 'layer3': 160, 'activation': 'identity', 'solver': 'adam', 'lr': 1.2871182672479732e-05}. Best is trial 141 with value: 0.7915712790577161.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [9:18:44<23:40:53, 7750.29s/it]

[I 2026-02-20 20:29:33,796] Trial 144 finished with value: 0.7856888149338876 and parameters: {'layer1': 210, 'layer2': 356, 'layer3': 92, 'activation': 'identity', 'solver': 'adam', 'lr': 8.737864600162396e-06}. Best is trial 141 with value: 0.7915712790577161.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [9:19:38<23:40:53, 7750.29s/it]

[I 2026-02-20 20:30:27,660] Trial 145 finished with value: 0.7862438269441382 and parameters: {'layer1': 298, 'layer2': 324, 'layer3': 125, 'activation': 'identity', 'solver': 'adam', 'lr': 1.3950600050662072e-05}. Best is trial 141 with value: 0.7915712790577161.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [9:20:46<23:40:53, 7750.29s/it]

[I 2026-02-20 20:31:34,849] Trial 146 finished with value: 0.7888340527529019 and parameters: {'layer1': 252, 'layer2': 145, 'layer3': 171, 'activation': 'identity', 'solver': 'adam', 'lr': 1.1543157898529263e-05}. Best is trial 141 with value: 0.7915712790577161.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [9:22:05<23:40:53, 7750.29s/it]

[I 2026-02-20 20:32:53,975] Trial 147 finished with value: 0.7890729434251427 and parameters: {'layer1': 280, 'layer2': 372, 'layer3': 140, 'activation': 'tanh', 'solver': 'adam', 'lr': 7.278976357862417e-06}. Best is trial 141 with value: 0.7915712790577161.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [9:23:17<23:40:53, 7750.29s/it]

[I 2026-02-20 20:34:05,957] Trial 148 finished with value: 0.7897143200437158 and parameters: {'layer1': 282, 'layer2': 375, 'layer3': 355, 'activation': 'tanh', 'solver': 'adam', 'lr': 7.541126083636904e-06}. Best is trial 141 with value: 0.7915712790577161.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [9:23:44<23:40:53, 7750.29s/it]

[I 2026-02-20 20:34:33,253] Trial 149 finished with value: 0.7841271442631301 and parameters: {'layer1': 272, 'layer2': 223, 'layer3': 453, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.00012561992462140786}. Best is trial 141 with value: 0.7915712790577161.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [9:24:13<23:40:53, 7750.29s/it]

[I 2026-02-20 20:35:02,782] Trial 150 finished with value: 0.6157364312073316 and parameters: {'layer1': 237, 'layer2': 373, 'layer3': 399, 'activation': 'tanh', 'solver': 'sgd', 'lr': 7.833182412227636e-06}. Best is trial 141 with value: 0.7915712790577161.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [9:24:41<23:40:53, 7750.29s/it]

[I 2026-02-20 20:35:30,102] Trial 151 finished with value: 0.7792457016264264 and parameters: {'layer1': 289, 'layer2': 412, 'layer3': 370, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0003916018958482092}. Best is trial 141 with value: 0.7915712790577161.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [9:26:02<23:40:53, 7750.29s/it]

[I 2026-02-20 20:36:51,610] Trial 152 finished with value: 0.7895287360726033 and parameters: {'layer1': 324, 'layer2': 395, 'layer3': 440, 'activation': 'tanh', 'solver': 'adam', 'lr': 5.79747338756785e-06}. Best is trial 141 with value: 0.7915712790577161.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [9:27:23<23:40:53, 7750.29s/it]

[I 2026-02-20 20:38:12,772] Trial 153 finished with value: 0.7892376513890749 and parameters: {'layer1': 284, 'layer2': 402, 'layer3': 458, 'activation': 'tanh', 'solver': 'adam', 'lr': 5.6444890848495416e-06}. Best is trial 141 with value: 0.7915712790577161.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [9:28:49<23:40:53, 7750.29s/it]

[I 2026-02-20 20:39:38,112] Trial 154 finished with value: 0.7887146262235072 and parameters: {'layer1': 282, 'layer2': 394, 'layer3': 433, 'activation': 'tanh', 'solver': 'adam', 'lr': 5.434914125419538e-06}. Best is trial 141 with value: 0.7915712790577161.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [9:30:29<23:40:53, 7750.29s/it]

[I 2026-02-20 20:41:18,842] Trial 155 finished with value: 0.7505761378571115 and parameters: {'layer1': 310, 'layer2': 402, 'layer3': 449, 'activation': 'tanh', 'solver': 'adam', 'lr': 3.9735989474341536e-06}. Best is trial 141 with value: 0.7915712790577161.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [9:30:46<23:40:53, 7750.29s/it]

[I 2026-02-20 20:41:35,695] Trial 156 finished with value: 0.5972887075778852 and parameters: {'layer1': 50, 'layer2': 414, 'layer3': 345, 'activation': 'tanh', 'solver': 'adam', 'lr': 4.820021447082977e-06}. Best is trial 141 with value: 0.7915712790577161.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [9:32:05<23:40:53, 7750.29s/it]

[I 2026-02-20 20:42:54,281] Trial 157 finished with value: 0.7866760914399306 and parameters: {'layer1': 296, 'layer2': 426, 'layer3': 474, 'activation': 'tanh', 'solver': 'adam', 'lr': 7.167762750682807e-06}. Best is trial 141 with value: 0.7915712790577161.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [9:33:34<23:40:53, 7750.29s/it]

[I 2026-02-20 20:44:22,969] Trial 158 finished with value: 0.7873327657839659 and parameters: {'layer1': 278, 'layer2': 447, 'layer3': 433, 'activation': 'tanh', 'solver': 'adam', 'lr': 5.843500842980575e-06}. Best is trial 141 with value: 0.7915712790577161.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [9:34:16<23:40:53, 7750.29s/it]

[I 2026-02-20 20:45:05,087] Trial 159 finished with value: 0.6341853206083773 and parameters: {'layer1': 315, 'layer2': 370, 'layer3': 412, 'activation': 'tanh', 'solver': 'adam', 'lr': 3.4440497735530617e-06}. Best is trial 141 with value: 0.7915712790577161.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [9:36:01<23:40:53, 7750.29s/it]

[I 2026-02-20 20:46:50,026] Trial 160 finished with value: 0.7891045210044705 and parameters: {'layer1': 328, 'layer2': 381, 'layer3': 468, 'activation': 'tanh', 'solver': 'adam', 'lr': 4.470962231070537e-06}. Best is trial 141 with value: 0.7915712790577161.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [9:37:45<23:40:53, 7750.29s/it]

[I 2026-02-20 20:48:34,623] Trial 161 finished with value: 0.7894959773434775 and parameters: {'layer1': 341, 'layer2': 379, 'layer3': 464, 'activation': 'tanh', 'solver': 'adam', 'lr': 4.980368812195319e-06}. Best is trial 141 with value: 0.7915712790577161.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [9:39:27<23:40:53, 7750.29s/it]

[I 2026-02-20 20:50:15,913] Trial 162 finished with value: 0.7871516356975715 and parameters: {'layer1': 340, 'layer2': 383, 'layer3': 465, 'activation': 'tanh', 'solver': 'adam', 'lr': 4.22222237329232e-06}. Best is trial 141 with value: 0.7915712790577161.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [9:39:53<23:40:53, 7750.29s/it]

[I 2026-02-20 20:50:42,413] Trial 163 finished with value: 0.5940221219711511 and parameters: {'layer1': 358, 'layer2': 402, 'layer3': 464, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.8601347676442435e-06}. Best is trial 141 with value: 0.7915712790577161.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [9:41:21<23:40:53, 7750.29s/it]

[I 2026-02-20 20:52:10,737] Trial 164 finished with value: 0.7866357556477341 and parameters: {'layer1': 328, 'layer2': 394, 'layer3': 450, 'activation': 'tanh', 'solver': 'adam', 'lr': 5.499101978417687e-06}. Best is trial 141 with value: 0.7915712790577161.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [9:42:28<23:40:53, 7750.29s/it]

[I 2026-02-20 20:53:17,766] Trial 165 finished with value: 0.6699579846241284 and parameters: {'layer1': 326, 'layer2': 377, 'layer3': 470, 'activation': 'tanh', 'solver': 'adam', 'lr': 3.7925221225170277e-06}. Best is trial 141 with value: 0.7915712790577161.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [9:44:12<23:40:53, 7750.29s/it]

[I 2026-02-20 20:55:01,434] Trial 166 finished with value: 0.7880530768459311 and parameters: {'layer1': 349, 'layer2': 364, 'layer3': 490, 'activation': 'tanh', 'solver': 'adam', 'lr': 4.856105781588111e-06}. Best is trial 141 with value: 0.7915712790577161.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [9:45:31<23:40:53, 7750.29s/it]

[I 2026-02-20 20:56:19,936] Trial 167 finished with value: 0.7885172910545533 and parameters: {'layer1': 299, 'layer2': 415, 'layer3': 442, 'activation': 'tanh', 'solver': 'adam', 'lr': 6.055565869127053e-06}. Best is trial 141 with value: 0.7915712790577161.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [9:46:36<23:40:53, 7750.29s/it]

[I 2026-02-20 20:57:25,119] Trial 168 finished with value: 0.788504148697575 and parameters: {'layer1': 313, 'layer2': 436, 'layer3': 478, 'activation': 'tanh', 'solver': 'adam', 'lr': 8.63494303023812e-06}. Best is trial 141 with value: 0.7915712790577161.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [9:47:04<23:40:53, 7750.29s/it]

[I 2026-02-20 20:57:53,338] Trial 169 finished with value: 0.5940221219711511 and parameters: {'layer1': 443, 'layer2': 348, 'layer3': 418, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.108800299009834e-06}. Best is trial 141 with value: 0.7915712790577161.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [9:47:29<23:40:53, 7750.29s/it]

[I 2026-02-20 20:58:18,744] Trial 170 finished with value: 0.5940221219711511 and parameters: {'layer1': 340, 'layer2': 384, 'layer3': 441, 'activation': 'logistic', 'solver': 'adam', 'lr': 1.1271381167128743e-05}. Best is trial 141 with value: 0.7915712790577161.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [9:48:44<23:40:53, 7750.29s/it]

[I 2026-02-20 20:59:32,939] Trial 171 finished with value: 0.7882216471685347 and parameters: {'layer1': 304, 'layer2': 370, 'layer3': 459, 'activation': 'tanh', 'solver': 'adam', 'lr': 7.243754374297418e-06}. Best is trial 141 with value: 0.7915712790577161.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [9:49:07<23:40:53, 7750.29s/it]

[I 2026-02-20 20:59:56,325] Trial 172 finished with value: 0.5943838294593131 and parameters: {'layer1': 283, 'layer2': 207, 'layer3': 141, 'activation': 'tanh', 'solver': 'adam', 'lr': 4.616368427487506e-06}. Best is trial 141 with value: 0.7915712790577161.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [9:50:22<23:40:53, 7750.29s/it]

[I 2026-02-20 21:01:11,330] Trial 173 finished with value: 0.7883719874470845 and parameters: {'layer1': 319, 'layer2': 396, 'layer3': 326, 'activation': 'tanh', 'solver': 'adam', 'lr': 6.875950793642307e-06}. Best is trial 141 with value: 0.7915712790577161.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [9:51:40<23:40:53, 7750.29s/it]

[I 2026-02-20 21:02:29,078] Trial 174 finished with value: 0.7853376108835437 and parameters: {'layer1': 433, 'layer2': 377, 'layer3': 459, 'activation': 'tanh', 'solver': 'adam', 'lr': 7.920667060839766e-06}. Best is trial 141 with value: 0.7915712790577161.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [9:52:27<23:40:53, 7750.29s/it]

[I 2026-02-20 21:03:16,277] Trial 175 finished with value: 0.788647171370281 and parameters: {'layer1': 256, 'layer2': 354, 'layer3': 481, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.5365867099540992e-05}. Best is trial 141 with value: 0.7915712790577161.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [9:53:53<23:40:53, 7750.29s/it]

[I 2026-02-20 21:04:42,200] Trial 176 finished with value: 0.7875045709070392 and parameters: {'layer1': 145, 'layer2': 390, 'layer3': 489, 'activation': 'tanh', 'solver': 'adam', 'lr': 5.38849031018468e-06}. Best is trial 141 with value: 0.7915712790577161.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [9:55:36<23:40:53, 7750.29s/it]

[I 2026-02-20 21:06:25,258] Trial 177 finished with value: 0.7894946625592933 and parameters: {'layer1': 360, 'layer2': 364, 'layer3': 155, 'activation': 'relu', 'solver': 'adam', 'lr': 1.0187660407551088e-05}. Best is trial 141 with value: 0.7915712790577161.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [9:57:09<23:40:53, 7750.29s/it]

[I 2026-02-20 21:07:58,535] Trial 178 finished with value: 0.7925009994512398 and parameters: {'layer1': 357, 'layer2': 462, 'layer3': 152, 'activation': 'relu', 'solver': 'adam', 'lr': 1.0825823998370467e-05}. Best is trial 178 with value: 0.7925009994512398.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [9:58:38<23:40:53, 7750.29s/it]

[I 2026-02-20 21:09:27,257] Trial 179 finished with value: 0.5209121728891483 and parameters: {'layer1': 355, 'layer2': 342, 'layer3': 161, 'activation': 'relu', 'solver': 'sgd', 'lr': 1.0598581426289966e-05}. Best is trial 178 with value: 0.7925009994512398.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [9:59:55<23:40:53, 7750.29s/it]

[I 2026-02-20 21:10:44,028] Trial 180 finished with value: 0.7903258394033108 and parameters: {'layer1': 368, 'layer2': 192, 'layer3': 152, 'activation': 'relu', 'solver': 'adam', 'lr': 1.3864346403811707e-05}. Best is trial 178 with value: 0.7925009994512398.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [10:01:21<23:40:53, 7750.29s/it]

[I 2026-02-20 21:12:09,953] Trial 181 finished with value: 0.7929404679289039 and parameters: {'layer1': 359, 'layer2': 491, 'layer3': 154, 'activation': 'relu', 'solver': 'adam', 'lr': 1.2956314088969173e-05}. Best is trial 181 with value: 0.7929404679289039.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [10:02:33<23:40:53, 7750.29s/it]

[I 2026-02-20 21:13:21,918] Trial 182 finished with value: 0.7925409379917363 and parameters: {'layer1': 368, 'layer2': 474, 'layer3': 152, 'activation': 'relu', 'solver': 'adam', 'lr': 1.270140373212425e-05}. Best is trial 181 with value: 0.7929404679289039.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [10:03:56<23:40:53, 7750.29s/it]

[I 2026-02-20 21:14:45,813] Trial 183 finished with value: 0.7965151084628997 and parameters: {'layer1': 359, 'layer2': 468, 'layer3': 153, 'activation': 'relu', 'solver': 'adam', 'lr': 1.305762000493721e-05}. Best is trial 183 with value: 0.7965151084628997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [10:05:05<23:40:53, 7750.29s/it]

[I 2026-02-20 21:15:54,611] Trial 184 finished with value: 0.7928734511705967 and parameters: {'layer1': 367, 'layer2': 474, 'layer3': 153, 'activation': 'relu', 'solver': 'adam', 'lr': 1.8794707183817575e-05}. Best is trial 183 with value: 0.7965151084628997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [10:06:08<23:40:53, 7750.29s/it]

[I 2026-02-20 21:16:57,788] Trial 185 finished with value: 0.7892199281062589 and parameters: {'layer1': 370, 'layer2': 473, 'layer3': 150, 'activation': 'relu', 'solver': 'adam', 'lr': 1.8993217205027133e-05}. Best is trial 183 with value: 0.7965151084628997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [10:07:15<23:40:53, 7750.29s/it]

[I 2026-02-20 21:18:04,777] Trial 186 finished with value: 0.7921246898131826 and parameters: {'layer1': 365, 'layer2': 495, 'layer3': 177, 'activation': 'relu', 'solver': 'adam', 'lr': 1.4757266320117216e-05}. Best is trial 183 with value: 0.7965151084628997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [10:08:37<23:40:53, 7750.29s/it]

[I 2026-02-20 21:19:26,283] Trial 187 finished with value: 0.791462111413713 and parameters: {'layer1': 363, 'layer2': 495, 'layer3': 179, 'activation': 'relu', 'solver': 'adam', 'lr': 1.5455997519499277e-05}. Best is trial 183 with value: 0.7965151084628997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [10:09:37<23:40:53, 7750.29s/it]

[I 2026-02-20 21:20:26,184] Trial 188 finished with value: 0.791918299545335 and parameters: {'layer1': 363, 'layer2': 492, 'layer3': 166, 'activation': 'relu', 'solver': 'adam', 'lr': 2.15882643211866e-05}. Best is trial 183 with value: 0.7965151084628997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [10:10:34<23:40:53, 7750.29s/it]

[I 2026-02-20 21:21:23,347] Trial 189 finished with value: 0.7892569340360216 and parameters: {'layer1': 364, 'layer2': 500, 'layer3': 184, 'activation': 'relu', 'solver': 'adam', 'lr': 2.2264617505975036e-05}. Best is trial 183 with value: 0.7965151084628997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [10:11:40<23:40:53, 7750.29s/it]

[I 2026-02-20 21:22:29,636] Trial 190 finished with value: 0.7904469054948172 and parameters: {'layer1': 376, 'layer2': 484, 'layer3': 179, 'activation': 'relu', 'solver': 'adam', 'lr': 1.7102646191121452e-05}. Best is trial 183 with value: 0.7965151084628997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [10:12:57<23:40:53, 7750.29s/it]

[I 2026-02-20 21:23:46,350] Trial 191 finished with value: 0.7917422863956876 and parameters: {'layer1': 389, 'layer2': 484, 'layer3': 176, 'activation': 'relu', 'solver': 'adam', 'lr': 1.8546950035927076e-05}. Best is trial 183 with value: 0.7965151084628997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [10:13:48<23:40:53, 7750.29s/it]

[I 2026-02-20 21:24:37,415] Trial 192 finished with value: 0.791565820132474 and parameters: {'layer1': 391, 'layer2': 483, 'layer3': 179, 'activation': 'relu', 'solver': 'adam', 'lr': 3.4711595265319824e-05}. Best is trial 183 with value: 0.7965151084628997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [10:14:46<23:40:53, 7750.29s/it]

[I 2026-02-20 21:25:35,366] Trial 193 finished with value: 0.791225355274012 and parameters: {'layer1': 386, 'layer2': 484, 'layer3': 176, 'activation': 'relu', 'solver': 'adam', 'lr': 2.7413023722329815e-05}. Best is trial 183 with value: 0.7965151084628997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [10:15:42<23:40:53, 7750.29s/it]

[I 2026-02-20 21:26:30,976] Trial 194 finished with value: 0.7909200815455375 and parameters: {'layer1': 392, 'layer2': 486, 'layer3': 181, 'activation': 'relu', 'solver': 'adam', 'lr': 3.5424051492164534e-05}. Best is trial 183 with value: 0.7965151084628997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [10:16:39<23:40:53, 7750.29s/it]

[I 2026-02-20 21:27:27,887] Trial 195 finished with value: 0.7892664597071912 and parameters: {'layer1': 387, 'layer2': 479, 'layer3': 172, 'activation': 'relu', 'solver': 'adam', 'lr': 3.955519875678023e-05}. Best is trial 183 with value: 0.7965151084628997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [10:17:50<23:40:53, 7750.29s/it]

[I 2026-02-20 21:28:39,394] Trial 196 finished with value: 0.7902609097410347 and parameters: {'layer1': 373, 'layer2': 465, 'layer3': 184, 'activation': 'relu', 'solver': 'adam', 'lr': 3.029713024315131e-05}. Best is trial 183 with value: 0.7965151084628997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [10:18:50<23:40:53, 7750.29s/it]

[I 2026-02-20 21:29:39,631] Trial 197 finished with value: 0.7904146671103017 and parameters: {'layer1': 394, 'layer2': 464, 'layer3': 188, 'activation': 'relu', 'solver': 'adam', 'lr': 3.213427829377375e-05}. Best is trial 183 with value: 0.7965151084628997.

Training Exact MLP (Paper):  21%|██▏       | 3/14 [10:20:00<23:40:53, 7750.29s/it]

[I 2026-02-20 21:30:49,154] Trial 198 finished with value: 0.7923411885251607 and parameters: {'layer1': 394, 'layer2': 465, 'layer3': 186, 'activation': 'relu', 'solver': 'adam', 'lr': 3.140918955567814e-05}. Best is trial 183 with value: 0.7965151084628997.

Best trial: 183. Best value: 0.796515: 100%|██████████| 200/200 [3:10:32<00:00, 57.16s/it]

[I 2026-02-20 21:31:51,728] Trial 199 finished with value: 0.7879897528837446 and parameters: {'layer1': 392, 'layer2': 465, 'layer3': 190, 'activation': 'relu', 'solver': 'adam', 'lr': 3.237791011456533e-05}. Best is trial 183 with value: 0.7965151084628997.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:21:05<25:34:10, 9205.02s/it][I 2026-02-20 21:31:54,316] A new study created in memory with name: no-name-0e2f04e4-97da-4f8c-8316-b5a257e6cfd7

  → Best model saved.

[Exact Paper MLP] Escherichia_Coli | Ceftriaxone

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:21:35<25:34:10, 9205.02s/it]

[I 2026-02-20 21:32:24,468] Trial 0 finished with value: 0.7135921496990285 and parameters: {'layer1': 305, 'layer2': 354, 'layer3': 247, 'activation': 'identity', 'solver': 'sgd', 'lr': 2.0409488610595422e-05}. Best is trial 0 with value: 0.7135921496990285.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:21:53<25:34:10, 9205.02s/it]

[I 2026-02-20 21:32:41,849] Trial 1 finished with value: 0.7054659072688098 and parameters: {'layer1': 48, 'layer2': 252, 'layer3': 443, 'activation': 'logistic', 'solver': 'adam', 'lr': 1.1885952686817544e-05}. Best is trial 0 with value: 0.7135921496990285.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:22:38<25:34:10, 9205.02s/it]

[I 2026-02-20 21:33:27,354] Trial 2 finished with value: 0.4523990487530063 and parameters: {'layer1': 443, 'layer2': 499, 'layer3': 34, 'activation': 'tanh', 'solver': 'sgd', 'lr': 8.739882273707104e-06}. Best is trial 0 with value: 0.7135921496990285.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:22:58<25:34:10, 9205.02s/it]

[I 2026-02-20 21:33:47,247] Trial 3 finished with value: 0.7054772582802332 and parameters: {'layer1': 469, 'layer2': 249, 'layer3': 408, 'activation': 'identity', 'solver': 'sgd', 'lr': 0.00018660356282339122}. Best is trial 0 with value: 0.7135921496990285.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:23:16<25:34:10, 9205.02s/it]

[I 2026-02-20 21:34:05,726] Trial 4 finished with value: 0.7054659072688098 and parameters: {'layer1': 407, 'layer2': 113, 'layer3': 460, 'activation': 'identity', 'solver': 'sgd', 'lr': 0.002349900446571255}. Best is trial 0 with value: 0.7135921496990285.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:23:37<25:34:10, 9205.02s/it]

[I 2026-02-20 21:34:25,943] Trial 5 finished with value: 0.7054659072688098 and parameters: {'layer1': 459, 'layer2': 407, 'layer3': 426, 'activation': 'tanh', 'solver': 'sgd', 'lr': 0.0008789939053543916}. Best is trial 0 with value: 0.7135921496990285.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:24:11<25:34:10, 9205.02s/it]

[I 2026-02-20 21:35:00,400] Trial 6 finished with value: 0.8808597613971518 and parameters: {'layer1': 220, 'layer2': 198, 'layer3': 146, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0005439157662834187}. Best is trial 6 with value: 0.8808597613971518.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:24:30<25:34:10, 9205.02s/it]

[I 2026-02-20 21:35:19,333] Trial 7 finished with value: 0.7133520964285459 and parameters: {'layer1': 124, 'layer2': 479, 'layer3': 183, 'activation': 'relu', 'solver': 'adam', 'lr': 4.497734384335628e-06}. Best is trial 6 with value: 0.8808597613971518.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:24:46<25:34:10, 9205.02s/it]

[I 2026-02-20 21:35:34,860] Trial 8 finished with value: 0.7094916993871914 and parameters: {'layer1': 91, 'layer2': 81, 'layer3': 468, 'activation': 'relu', 'solver': 'sgd', 'lr': 0.000113887682859945}. Best is trial 6 with value: 0.8808597613971518.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:25:05<25:34:10, 9205.02s/it]

[I 2026-02-20 21:35:54,699] Trial 9 finished with value: 0.7074016995499329 and parameters: {'layer1': 260, 'layer2': 424, 'layer3': 326, 'activation': 'tanh', 'solver': 'sgd', 'lr': 0.00010149816578310313}. Best is trial 6 with value: 0.8808597613971518.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:25:29<25:34:10, 9205.02s/it]

[I 2026-02-20 21:36:18,534] Trial 10 finished with value: 0.7379583987281724 and parameters: {'layer1': 172, 'layer2': 155, 'layer3': 92, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.009787494849045125}. Best is trial 6 with value: 0.8808597613971518.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:26:02<25:34:10, 9205.02s/it]

[I 2026-02-20 21:36:50,877] Trial 11 finished with value: 0.7746236609231548 and parameters: {'layer1': 180, 'layer2': 167, 'layer3': 84, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.007776107225105863}. Best is trial 6 with value: 0.8808597613971518.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:26:33<25:34:10, 9205.02s/it]

[I 2026-02-20 21:37:22,629] Trial 12 finished with value: 0.8828153299255541 and parameters: {'layer1': 202, 'layer2': 25, 'layer3': 155, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0009566129843747916}. Best is trial 12 with value: 0.8828153299255541.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:27:14<25:34:10, 9205.02s/it]

[I 2026-02-20 21:38:03,148] Trial 13 finished with value: 0.880639734789922 and parameters: {'layer1': 324, 'layer2': 38, 'layer3': 176, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0005028909330407669}. Best is trial 12 with value: 0.8828153299255541.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:27:34<25:34:10, 9205.02s/it]

[I 2026-02-20 21:38:23,391] Trial 14 finished with value: 0.5782951336087565 and parameters: {'layer1': 214, 'layer2': 11, 'layer3': 166, 'activation': 'logistic', 'solver': 'adam', 'lr': 1.3244521113570223e-06}. Best is trial 12 with value: 0.8828153299255541.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:28:11<25:34:10, 9205.02s/it]

[I 2026-02-20 21:39:00,767] Trial 15 finished with value: 0.8845943290040804 and parameters: {'layer1': 333, 'layer2': 319, 'layer3': 271, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.001635279313310095}. Best is trial 15 with value: 0.8845943290040804.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:28:51<25:34:10, 9205.02s/it]

[I 2026-02-20 21:39:40,700] Trial 16 finished with value: 0.8826399053985924 and parameters: {'layer1': 365, 'layer2': 361, 'layer3': 290, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0013021537856659228}. Best is trial 15 with value: 0.8845943290040804.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:29:33<25:34:10, 9205.02s/it]

[I 2026-02-20 21:40:22,446] Trial 17 finished with value: 0.8825445848023422 and parameters: {'layer1': 302, 'layer2': 319, 'layer3': 244, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0031335986031925255}. Best is trial 15 with value: 0.8845943290040804.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:30:08<25:34:10, 9205.02s/it]

[I 2026-02-20 21:40:57,699] Trial 18 finished with value: 0.8775795860046169 and parameters: {'layer1': 363, 'layer2': 306, 'layer3': 351, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0002748879437141753}. Best is trial 15 with value: 0.8845943290040804.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:30:47<25:34:10, 9205.02s/it]

[I 2026-02-20 21:41:36,785] Trial 19 finished with value: 0.8817414761272928 and parameters: {'layer1': 257, 'layer2': 281, 'layer3': 212, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0032540106885911263}. Best is trial 15 with value: 0.8845943290040804.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:31:03<25:34:10, 9205.02s/it]

[I 2026-02-20 21:41:52,103] Trial 20 finished with value: 0.7054659072688098 and parameters: {'layer1': 16, 'layer2': 213, 'layer3': 349, 'activation': 'logistic', 'solver': 'adam', 'lr': 3.891723162866194e-05}. Best is trial 15 with value: 0.8845943290040804.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:31:53<25:34:10, 9205.02s/it]

[I 2026-02-20 21:42:42,616] Trial 21 finished with value: 0.8806242251721887 and parameters: {'layer1': 371, 'layer2': 369, 'layer3': 300, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0013893187559391436}. Best is trial 15 with value: 0.8845943290040804.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:32:36<25:34:10, 9205.02s/it]

[I 2026-02-20 21:43:25,725] Trial 22 finished with value: 0.8827665372879668 and parameters: {'layer1': 358, 'layer2': 379, 'layer3': 287, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0016199104224635798}. Best is trial 15 with value: 0.8845943290040804.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:33:38<25:34:10, 9205.02s/it]

[I 2026-02-20 21:44:27,586] Trial 23 finished with value: 0.882818762647602 and parameters: {'layer1': 409, 'layer2': 424, 'layer3': 111, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.004631297170320628}. Best is trial 15 with value: 0.8845943290040804.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:34:29<25:34:10, 9205.02s/it]

[I 2026-02-20 21:45:18,152] Trial 24 finished with value: 0.8808767319093418 and parameters: {'layer1': 408, 'layer2': 443, 'layer3': 102, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.005219965203816817}. Best is trial 15 with value: 0.8845943290040804.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:35:14<25:34:10, 9205.02s/it]

[I 2026-02-20 21:46:03,088] Trial 25 finished with value: 0.8841411659512994 and parameters: {'layer1': 412, 'layer2': 312, 'layer3': 25, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0005517177324481635}. Best is trial 15 with value: 0.8845943290040804.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:35:55<25:34:10, 9205.02s/it]

[I 2026-02-20 21:46:44,367] Trial 26 finished with value: 0.8851661295597095 and parameters: {'layer1': 417, 'layer2': 310, 'layer3': 17, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.00037981444683191643}. Best is trial 26 with value: 0.8851661295597095.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:36:30<25:34:10, 9205.02s/it]

[I 2026-02-20 21:47:18,990] Trial 27 finished with value: 0.8824034818994073 and parameters: {'layer1': 434, 'layer2': 323, 'layer3': 14, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0002989056361717131}. Best is trial 26 with value: 0.8851661295597095.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:37:23<25:34:10, 9205.02s/it]

[I 2026-02-20 21:48:12,126] Trial 28 finished with value: 0.88069523229485 and parameters: {'layer1': 483, 'layer2': 284, 'layer3': 51, 'activation': 'tanh', 'solver': 'adam', 'lr': 3.2652301396470896e-05}. Best is trial 26 with value: 0.8851661295597095.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:37:53<25:34:10, 9205.02s/it]

[I 2026-02-20 21:48:42,362] Trial 29 finished with value: 0.8702886121314324 and parameters: {'layer1': 287, 'layer2': 343, 'layer3': 59, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0005259506879881667}. Best is trial 26 with value: 0.8851661295597095.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:38:35<25:34:10, 9205.02s/it]

[I 2026-02-20 21:49:24,394] Trial 30 finished with value: 0.8782244950071096 and parameters: {'layer1': 496, 'layer2': 218, 'layer3': 228, 'activation': 'tanh', 'solver': 'adam', 'lr': 6.216712689453927e-05}. Best is trial 26 with value: 0.8851661295597095.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:39:03<25:34:10, 9205.02s/it]

[I 2026-02-20 21:49:52,452] Trial 31 finished with value: 0.7420655544596649 and parameters: {'layer1': 329, 'layer2': 398, 'layer3': 128, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.00457059444957443}. Best is trial 26 with value: 0.8851661295597095.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:39:45<25:34:10, 9205.02s/it]

[I 2026-02-20 21:50:34,222] Trial 32 finished with value: 0.8766072920124846 and parameters: {'layer1': 422, 'layer2': 453, 'layer3': 23, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00019475306057517534}. Best is trial 26 with value: 0.8851661295597095.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:40:22<25:34:10, 9205.02s/it]

[I 2026-02-20 21:51:10,929] Trial 33 finished with value: 0.8750834841048212 and parameters: {'layer1': 387, 'layer2': 268, 'layer3': 66, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0006494956211205271}. Best is trial 26 with value: 0.8851661295597095.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:40:59<25:34:10, 9205.02s/it]

[I 2026-02-20 21:51:48,469] Trial 34 finished with value: 0.8815978797948985 and parameters: {'layer1': 336, 'layer2': 344, 'layer3': 118, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0019543023959798524}. Best is trial 26 with value: 0.8851661295597095.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:41:19<25:34:10, 9205.02s/it]

[I 2026-02-20 21:52:08,350] Trial 35 finished with value: 0.7061056712183476 and parameters: {'layer1': 446, 'layer2': 244, 'layer3': 11, 'activation': 'tanh', 'solver': 'sgd', 'lr': 0.0003669971407324635}. Best is trial 26 with value: 0.8851661295597095.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:41:52<25:34:10, 9205.02s/it]

[I 2026-02-20 21:52:41,544] Trial 36 finished with value: 0.8753185832013168 and parameters: {'layer1': 399, 'layer2': 301, 'layer3': 51, 'activation': 'identity', 'solver': 'adam', 'lr': 0.00018183424558278148}. Best is trial 26 with value: 0.8851661295597095.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:42:14<25:34:10, 9205.02s/it]

[I 2026-02-20 21:53:03,422] Trial 37 finished with value: 0.7054659072688098 and parameters: {'layer1': 457, 'layer2': 396, 'layer3': 40, 'activation': 'logistic', 'solver': 'sgd', 'lr': 0.0009147087039246136}. Best is trial 26 with value: 0.8851661295597095.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:42:46<25:34:10, 9205.02s/it]

[I 2026-02-20 21:53:35,406] Trial 38 finished with value: 0.7433574081112588 and parameters: {'layer1': 424, 'layer2': 498, 'layer3': 387, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0028533950141435074}. Best is trial 26 with value: 0.8851661295597095.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:43:04<25:34:10, 9205.02s/it]

[I 2026-02-20 21:53:53,054] Trial 39 finished with value: 0.7054659072688098 and parameters: {'layer1': 289, 'layer2': 235, 'layer3': 198, 'activation': 'logistic', 'solver': 'sgd', 'lr': 0.00509658986973408}. Best is trial 26 with value: 0.8851661295597095.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:43:44<25:34:10, 9205.02s/it]

[I 2026-02-20 21:54:33,222] Trial 40 finished with value: 0.8802780039954605 and parameters: {'layer1': 388, 'layer2': 430, 'layer3': 493, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00015539930130631472}. Best is trial 26 with value: 0.8851661295597095.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:44:18<25:34:10, 9205.02s/it]

[I 2026-02-20 21:55:06,962] Trial 41 finished with value: 0.8815153024682688 and parameters: {'layer1': 209, 'layer2': 180, 'layer3': 146, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.000939042943501316}. Best is trial 26 with value: 0.8851661295597095.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:44:42<25:34:10, 9205.02s/it]

[I 2026-02-20 21:55:31,228] Trial 42 finished with value: 0.8789103326070012 and parameters: {'layer1': 114, 'layer2': 134, 'layer3': 76, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0012180261934672983}. Best is trial 26 with value: 0.8851661295597095.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:45:12<25:34:10, 9205.02s/it]

[I 2026-02-20 21:56:01,755] Trial 43 finished with value: 0.8819759335319081 and parameters: {'layer1': 166, 'layer2': 326, 'layer3': 257, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0020448085719387463}. Best is trial 26 with value: 0.8851661295597095.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:45:50<25:34:10, 9205.02s/it]

[I 2026-02-20 21:56:39,633] Trial 44 finished with value: 0.880803775597605 and parameters: {'layer1': 343, 'layer2': 278, 'layer3': 116, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0006326734731673333}. Best is trial 26 with value: 0.8851661295597095.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:46:36<25:34:10, 9205.02s/it]

[I 2026-02-20 21:57:25,476] Trial 45 finished with value: 0.8818995573671252 and parameters: {'layer1': 477, 'layer2': 86, 'layer3': 141, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.00042039651315376966}. Best is trial 26 with value: 0.8851661295597095.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:46:53<25:34:10, 9205.02s/it]

[I 2026-02-20 21:57:41,967] Trial 46 finished with value: 0.7054659072688098 and parameters: {'layer1': 234, 'layer2': 461, 'layer3': 97, 'activation': 'tanh', 'solver': 'sgd', 'lr': 0.007174752812440791}. Best is trial 26 with value: 0.8851661295597095.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:47:22<25:34:10, 9205.02s/it]

[I 2026-02-20 21:58:11,322] Trial 47 finished with value: 0.8718603398053315 and parameters: {'layer1': 315, 'layer2': 344, 'layer3': 170, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0007248731554053423}. Best is trial 26 with value: 0.8851661295597095.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:47:53<25:34:10, 9205.02s/it]

[I 2026-02-20 21:58:42,587] Trial 48 finished with value: 0.7054659072688098 and parameters: {'layer1': 407, 'layer2': 300, 'layer3': 263, 'activation': 'logistic', 'solver': 'adam', 'lr': 1.4077412104390912e-05}. Best is trial 26 with value: 0.8851661295597095.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:48:29<25:34:10, 9205.02s/it]

[I 2026-02-20 21:59:18,035] Trial 49 finished with value: 0.8807570737571698 and parameters: {'layer1': 270, 'layer2': 415, 'layer3': 35, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0036298660631079063}. Best is trial 26 with value: 0.8851661295597095.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:48:59<25:34:10, 9205.02s/it]

[I 2026-02-20 21:59:48,565] Trial 50 finished with value: 0.5824465452613741 and parameters: {'layer1': 456, 'layer2': 254, 'layer3': 195, 'activation': 'relu', 'solver': 'sgd', 'lr': 7.597324876447805e-05}. Best is trial 26 with value: 0.8851661295597095.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:49:42<25:34:10, 9205.02s/it]

[I 2026-02-20 22:00:31,375] Trial 51 finished with value: 0.8813678941345386 and parameters: {'layer1': 355, 'layer2': 385, 'layer3': 292, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0014431382960071813}. Best is trial 26 with value: 0.8851661295597095.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:50:24<25:34:10, 9205.02s/it]

[I 2026-02-20 22:01:13,602] Trial 52 finished with value: 0.8806176062907927 and parameters: {'layer1': 375, 'layer2': 379, 'layer3': 319, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0020610332142678802}. Best is trial 26 with value: 0.8851661295597095.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:50:55<25:34:10, 9205.02s/it]

[I 2026-02-20 22:01:44,518] Trial 53 finished with value: 0.8774017162851745 and parameters: {'layer1': 196, 'layer2': 364, 'layer3': 278, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0010674492826338435}. Best is trial 26 with value: 0.8851661295597095.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:51:27<25:34:10, 9205.02s/it]

[I 2026-02-20 22:02:16,622] Trial 54 finished with value: 0.8827168597120245 and parameters: {'layer1': 136, 'layer2': 328, 'layer3': 321, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0002801670702647997}. Best is trial 26 with value: 0.8851661295597095.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:52:10<25:34:10, 9205.02s/it]

[I 2026-02-20 22:02:59,245] Trial 55 finished with value: 0.8840885980171574 and parameters: {'layer1': 351, 'layer2': 308, 'layer3': 231, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.001658649543542112}. Best is trial 26 with value: 0.8851661295597095.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:52:42<25:34:10, 9205.02s/it]

[I 2026-02-20 22:03:31,033] Trial 56 finished with value: 0.7054659072688098 and parameters: {'layer1': 421, 'layer2': 296, 'layer3': 212, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.00988856466942333}. Best is trial 26 with value: 0.8851661295597095.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:53:11<25:34:10, 9205.02s/it]

[I 2026-02-20 22:04:00,664] Trial 57 finished with value: 0.7054659072688098 and parameters: {'layer1': 389, 'layer2': 261, 'layer3': 160, 'activation': 'logistic', 'solver': 'adam', 'lr': 4.539126045774304e-06}. Best is trial 26 with value: 0.8851661295597095.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:53:38<25:34:10, 9205.02s/it]

[I 2026-02-20 22:04:27,650] Trial 58 finished with value: 0.8134150591052016 and parameters: {'layer1': 239, 'layer2': 62, 'layer3': 234, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.002533177618290715}. Best is trial 26 with value: 0.8851661295597095.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:54:11<25:34:10, 9205.02s/it]

[I 2026-02-20 22:05:00,629] Trial 59 finished with value: 0.7736496553184875 and parameters: {'layer1': 313, 'layer2': 227, 'layer3': 78, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.006183320865152641}. Best is trial 26 with value: 0.8851661295597095.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:54:57<25:34:10, 9205.02s/it]

[I 2026-02-20 22:05:46,547] Trial 60 finished with value: 0.8817205053979729 and parameters: {'layer1': 345, 'layer2': 184, 'layer3': 103, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.004203183134051429}. Best is trial 26 with value: 0.8851661295597095.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:55:41<25:34:10, 9205.02s/it]

[I 2026-02-20 22:06:30,529] Trial 61 finished with value: 0.8814947001516378 and parameters: {'layer1': 435, 'layer2': 313, 'layer3': 343, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0014619488042570976}. Best is trial 26 with value: 0.8851661295597095.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:56:19<25:34:10, 9205.02s/it]

[I 2026-02-20 22:07:08,813] Trial 62 finished with value: 0.8838033055060313 and parameters: {'layer1': 367, 'layer2': 344, 'layer3': 280, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.001692183035660143}. Best is trial 26 with value: 0.8851661295597095.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:57:01<25:34:10, 9205.02s/it]

[I 2026-02-20 22:07:50,819] Trial 63 finished with value: 0.8790712807412941 and parameters: {'layer1': 374, 'layer2': 351, 'layer3': 265, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0008708992454176677}. Best is trial 26 with value: 0.8851661295597095.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:57:44<25:34:10, 9205.02s/it]

[I 2026-02-20 22:08:33,325] Trial 64 finished with value: 0.8825900248185787 and parameters: {'layer1': 400, 'layer2': 288, 'layer3': 227, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0026063882541267186}. Best is trial 26 with value: 0.8851661295597095.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:58:22<25:34:10, 9205.02s/it]

[I 2026-02-20 22:09:11,617] Trial 65 finished with value: 0.8766921433055082 and parameters: {'layer1': 290, 'layer2': 328, 'layer3': 306, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.00044459644951858204}. Best is trial 26 with value: 0.8851661295597095.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:59:15<25:34:10, 9205.02s/it]

[I 2026-02-20 22:10:04,179] Trial 66 finished with value: 0.8813012455838647 and parameters: {'layer1': 357, 'layer2': 273, 'layer3': 187, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0019680051295108097}. Best is trial 26 with value: 0.8851661295597095.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [10:59:39<25:34:10, 9205.02s/it]

[I 2026-02-20 22:10:28,781] Trial 67 finished with value: 0.8757729319984489 and parameters: {'layer1': 153, 'layer2': 359, 'layer3': 374, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0007293829555788955}. Best is trial 26 with value: 0.8851661295597095.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:00:20<25:34:10, 9205.02s/it]

[I 2026-02-20 22:11:09,519] Trial 68 finished with value: 0.8736111299416314 and parameters: {'layer1': 379, 'layer2': 314, 'layer3': 240, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00356872955886614}. Best is trial 26 with value: 0.8851661295597095.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:00:39<25:34:10, 9205.02s/it]

[I 2026-02-20 22:11:28,158] Trial 69 finished with value: 0.7054659072688098 and parameters: {'layer1': 420, 'layer2': 336, 'layer3': 26, 'activation': 'logistic', 'solver': 'sgd', 'lr': 0.0011347660143825676}. Best is trial 26 with value: 0.8851661295597095.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:01:07<25:34:10, 9205.02s/it]

[I 2026-02-20 22:11:56,324] Trial 70 finished with value: 0.8785889131522449 and parameters: {'layer1': 271, 'layer2': 400, 'layer3': 273, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0003377082880214891}. Best is trial 26 with value: 0.8851661295597095.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:01:49<25:34:10, 9205.02s/it]

[I 2026-02-20 22:12:38,382] Trial 71 finished with value: 0.8814574293231751 and parameters: {'layer1': 351, 'layer2': 376, 'layer3': 211, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0014980964088847641}. Best is trial 26 with value: 0.8851661295597095.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:02:32<25:34:10, 9205.02s/it]

[I 2026-02-20 22:13:21,474] Trial 72 finished with value: 0.8799769572806945 and parameters: {'layer1': 334, 'layer2': 434, 'layer3': 304, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.00021671786211206786}. Best is trial 26 with value: 0.8851661295597095.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:03:29<25:34:10, 9205.02s/it]

[I 2026-02-20 22:14:18,392] Trial 73 finished with value: 0.8845942177198267 and parameters: {'layer1': 445, 'layer2': 412, 'layer3': 282, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0017371214771054301}. Best is trial 26 with value: 0.8851661295597095.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:04:20<25:34:10, 9205.02s/it]

[I 2026-02-20 22:15:09,612] Trial 74 finished with value: 0.8836304324689014 and parameters: {'layer1': 447, 'layer2': 465, 'layer3': 250, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0017890448979495947}. Best is trial 26 with value: 0.8851661295597095.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:05:09<25:34:10, 9205.02s/it]

[I 2026-02-20 22:15:57,928] Trial 75 finished with value: 0.8815445328539264 and parameters: {'layer1': 496, 'layer2': 466, 'layer3': 248, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0017183775560044396}. Best is trial 26 with value: 0.8851661295597095.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:05:57<25:34:10, 9205.02s/it]

[I 2026-02-20 22:16:45,919] Trial 76 finished with value: 0.8098971822954015 and parameters: {'layer1': 446, 'layer2': 448, 'layer3': 340, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.006136078013185126}. Best is trial 26 with value: 0.8851661295597095.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:06:46<25:34:10, 9205.02s/it]

[I 2026-02-20 22:17:35,555] Trial 77 finished with value: 0.8818604813880864 and parameters: {'layer1': 465, 'layer2': 494, 'layer3': 277, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.002841424144983866}. Best is trial 26 with value: 0.8851661295597095.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:07:47<25:34:10, 9205.02s/it]

[I 2026-02-20 22:18:35,944] Trial 78 finished with value: 0.8797746424178905 and parameters: {'layer1': 439, 'layer2': 418, 'layer3': 366, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.00013295081636486466}. Best is trial 26 with value: 0.8851661295597095.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:08:24<25:34:10, 9205.02s/it]

[I 2026-02-20 22:19:13,615] Trial 79 finished with value: 0.8796274187426107 and parameters: {'layer1': 412, 'layer2': 483, 'layer3': 48, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0005609778305028222}. Best is trial 26 with value: 0.8851661295597095.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:09:05<25:34:10, 9205.02s/it]

[I 2026-02-20 22:19:54,467] Trial 80 finished with value: 0.8686737970475956 and parameters: {'layer1': 477, 'layer2': 475, 'layer3': 251, 'activation': 'identity', 'solver': 'adam', 'lr': 0.004482853896633646}. Best is trial 26 with value: 0.8851661295597095.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:09:50<25:34:10, 9205.02s/it]

[I 2026-02-20 22:20:39,657] Trial 81 finished with value: 0.8808609156056144 and parameters: {'layer1': 399, 'layer2': 11, 'layer3': 215, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0008244844671877764}. Best is trial 26 with value: 0.8851661295597095.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:10:36<25:34:10, 9205.02s/it]

[I 2026-02-20 22:21:24,865] Trial 82 finished with value: 0.8817262631004494 and parameters: {'layer1': 432, 'layer2': 407, 'layer3': 135, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0011232960585813147}. Best is trial 26 with value: 0.8851661295597095.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:11:21<25:34:10, 9205.02s/it]

[I 2026-02-20 22:22:10,568] Trial 83 finished with value: 0.8819820939467025 and parameters: {'layer1': 452, 'layer2': 307, 'layer3': 161, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0021665158258162456}. Best is trial 26 with value: 0.8851661295597095.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:12:04<25:34:10, 9205.02s/it]

[I 2026-02-20 22:22:53,660] Trial 84 finished with value: 0.8819098337916694 and parameters: {'layer1': 389, 'layer2': 387, 'layer3': 64, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0017442471306223955}. Best is trial 26 with value: 0.8851661295597095.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:12:26<25:34:10, 9205.02s/it]

[I 2026-02-20 22:23:15,469] Trial 85 finished with value: 0.7054659072688098 and parameters: {'layer1': 468, 'layer2': 355, 'layer3': 286, 'activation': 'logistic', 'solver': 'sgd', 'lr': 0.0005368905847374269}. Best is trial 26 with value: 0.8851661295597095.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:13:08<25:34:10, 9205.02s/it]

[I 2026-02-20 22:23:57,217] Trial 86 finished with value: 0.877180127874307 and parameters: {'layer1': 416, 'layer2': 432, 'layer3': 15, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0010231461454587112}. Best is trial 26 with value: 0.8851661295597095.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:13:35<25:34:10, 9205.02s/it]

[I 2026-02-20 22:24:23,849] Trial 87 finished with value: 0.8490836879576269 and parameters: {'layer1': 190, 'layer2': 290, 'layer3': 263, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0032179302174026475}. Best is trial 26 with value: 0.8851661295597095.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:14:15<25:34:10, 9205.02s/it]

[I 2026-02-20 22:25:04,382] Trial 88 finished with value: 0.8842329154702814 and parameters: {'layer1': 368, 'layer2': 447, 'layer3': 226, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.001284205152317219}. Best is trial 26 with value: 0.8851661295597095.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:14:57<25:34:10, 9205.02s/it]

[I 2026-02-20 22:25:46,790] Trial 89 finished with value: 0.8823529992886765 and parameters: {'layer1': 365, 'layer2': 458, 'layer3': 311, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0012594989247914211}. Best is trial 26 with value: 0.8851661295597095.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:15:44<25:34:10, 9205.02s/it]

[I 2026-02-20 22:26:33,568] Trial 90 finished with value: 0.8832361300334229 and parameters: {'layer1': 404, 'layer2': 444, 'layer3': 292, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0022949970008063064}. Best is trial 26 with value: 0.8851661295597095.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:16:35<25:34:10, 9205.02s/it]

[I 2026-02-20 22:27:24,738] Trial 91 finished with value: 0.8816553397635236 and parameters: {'layer1': 428, 'layer2': 442, 'layer3': 331, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.003887981534230898}. Best is trial 26 with value: 0.8851661295597095.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:17:15<25:34:10, 9205.02s/it]

[I 2026-02-20 22:28:04,305] Trial 92 finished with value: 0.8854567176169477 and parameters: {'layer1': 401, 'layer2': 475, 'layer3': 295, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0024547194449095187}. Best is trial 92 with value: 0.8854567176169477.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:17:54<25:34:10, 9205.02s/it]

[I 2026-02-20 22:28:43,370] Trial 93 finished with value: 0.8851812941762951 and parameters: {'layer1': 400, 'layer2': 472, 'layer3': 296, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0021571631713335764}. Best is trial 92 with value: 0.8854567176169477.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:18:38<25:34:10, 9205.02s/it]

[I 2026-02-20 22:29:27,719] Trial 94 finished with value: 0.880805971211658 and parameters: {'layer1': 383, 'layer2': 476, 'layer3': 405, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0016358197890114063}. Best is trial 92 with value: 0.8854567176169477.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:19:17<25:34:10, 9205.02s/it]

[I 2026-02-20 22:30:06,329] Trial 95 finished with value: 0.8818970556738034 and parameters: {'layer1': 324, 'layer2': 465, 'layer3': 436, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0007344708411828264}. Best is trial 92 with value: 0.8854567176169477.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:19:43<25:34:10, 9205.02s/it]

[I 2026-02-20 22:30:32,630] Trial 96 finished with value: 0.7057588388440288 and parameters: {'layer1': 368, 'layer2': 488, 'layer3': 224, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.357156659228181e-06}. Best is trial 92 with value: 0.8854567176169477.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:20:29<25:34:10, 9205.02s/it]

[I 2026-02-20 22:31:18,706] Trial 97 finished with value: 0.883951043363815 and parameters: {'layer1': 343, 'layer2': 476, 'layer3': 272, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0025109032924707773}. Best is trial 92 with value: 0.8854567176169477.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:21:20<25:34:10, 9205.02s/it]

[I 2026-02-20 22:32:08,980] Trial 98 finished with value: 0.8833705306928469 and parameters: {'layer1': 343, 'layer2': 498, 'layer3': 297, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.002704327210293046}. Best is trial 92 with value: 0.8854567176169477.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:21:38<25:34:10, 9205.02s/it]

[I 2026-02-20 22:32:27,294] Trial 99 finished with value: 0.7054659072688098 and parameters: {'layer1': 305, 'layer2': 477, 'layer3': 282, 'activation': 'logistic', 'solver': 'sgd', 'lr': 0.0013467519705141415}. Best is trial 92 with value: 0.8854567176169477.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:22:26<25:34:10, 9205.02s/it]

[I 2026-02-20 22:33:14,918] Trial 100 finished with value: 0.8819531315398773 and parameters: {'layer1': 393, 'layer2': 453, 'layer3': 311, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.002304949250046429}. Best is trial 92 with value: 0.8854567176169477.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:23:08<25:34:10, 9205.02s/it]

[I 2026-02-20 22:33:57,815] Trial 101 finished with value: 0.8837179046362447 and parameters: {'layer1': 377, 'layer2': 470, 'layer3': 271, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0018346689364890053}. Best is trial 92 with value: 0.8854567176169477.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:23:51<25:34:10, 9205.02s/it]

[I 2026-02-20 22:34:40,712] Trial 102 finished with value: 0.8815168804560815 and parameters: {'layer1': 366, 'layer2': 336, 'layer3': 271, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0029716213204381368}. Best is trial 92 with value: 0.8854567176169477.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:24:29<25:34:10, 9205.02s/it]

[I 2026-02-20 22:35:18,823] Trial 103 finished with value: 0.8810204937971067 and parameters: {'layer1': 336, 'layer2': 472, 'layer3': 263, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0012764543776017832}. Best is trial 92 with value: 0.8854567176169477.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:25:10<25:34:10, 9205.02s/it]

[I 2026-02-20 22:35:59,089] Trial 104 finished with value: 0.8804240579040983 and parameters: {'layer1': 378, 'layer2': 487, 'layer3': 237, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0008752159567130495}. Best is trial 92 with value: 0.8854567176169477.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:25:52<25:34:10, 9205.02s/it]

[I 2026-02-20 22:36:40,972] Trial 105 finished with value: 0.8724622818584435 and parameters: {'layer1': 354, 'layer2': 424, 'layer3': 331, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0034456436247366417}. Best is trial 92 with value: 0.8854567176169477.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:26:36<25:34:10, 9205.02s/it]

[I 2026-02-20 22:37:25,365] Trial 106 finished with value: 0.8489734837057199 and parameters: {'layer1': 319, 'layer2': 412, 'layer3': 297, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0058474122317330665}. Best is trial 92 with value: 0.8854567176169477.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:27:29<25:34:10, 9205.02s/it]

[I 2026-02-20 22:38:18,090] Trial 107 finished with value: 0.8814671864998325 and parameters: {'layer1': 394, 'layer2': 319, 'layer3': 317, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0021933234378446512}. Best is trial 92 with value: 0.8854567176169477.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:28:05<25:34:10, 9205.02s/it]

[I 2026-02-20 22:38:54,641] Trial 108 finished with value: 0.8783989300759913 and parameters: {'layer1': 412, 'layer2': 244, 'layer3': 256, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00165461700438306}. Best is trial 92 with value: 0.8854567176169477.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:28:44<25:34:10, 9205.02s/it]

[I 2026-02-20 22:39:33,418] Trial 109 finished with value: 0.8828550076733164 and parameters: {'layer1': 347, 'layer2': 435, 'layer3': 284, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0004385194935647739}. Best is trial 92 with value: 0.8854567176169477.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:29:25<25:34:10, 9205.02s/it]

[I 2026-02-20 22:40:14,395] Trial 110 finished with value: 0.8818246025984686 and parameters: {'layer1': 374, 'layer2': 304, 'layer3': 271, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0006777133284319108}. Best is trial 92 with value: 0.8854567176169477.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:30:09<25:34:10, 9205.02s/it]

[I 2026-02-20 22:40:58,598] Trial 111 finished with value: 0.8824335945118393 and parameters: {'layer1': 429, 'layer2': 466, 'layer3': 247, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0018167000885667345}. Best is trial 92 with value: 0.8854567176169477.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:30:49<25:34:10, 9205.02s/it]

[I 2026-02-20 22:41:37,909] Trial 112 finished with value: 0.8818044353653546 and parameters: {'layer1': 399, 'layer2': 488, 'layer3': 221, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0010106606830632013}. Best is trial 92 with value: 0.8854567176169477.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:31:31<25:34:10, 9205.02s/it]

[I 2026-02-20 22:42:20,661] Trial 113 finished with value: 0.8816819122672497 and parameters: {'layer1': 445, 'layer2': 453, 'layer3': 238, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0024774577233518703}. Best is trial 92 with value: 0.8854567176169477.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:32:10<25:34:10, 9205.02s/it]

[I 2026-02-20 22:42:59,105] Trial 114 finished with value: 0.8827522056952327 and parameters: {'layer1': 384, 'layer2': 438, 'layer3': 202, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.001933455471387111}. Best is trial 92 with value: 0.8854567176169477.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:32:52<25:34:10, 9205.02s/it]

[I 2026-02-20 22:43:41,592] Trial 115 finished with value: 0.8808472254332591 and parameters: {'layer1': 358, 'layer2': 264, 'layer3': 257, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0014785451386106927}. Best is trial 92 with value: 0.8854567176169477.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:33:32<25:34:10, 9205.02s/it]

[I 2026-02-20 22:44:20,928] Trial 116 finished with value: 0.7383186778979152 and parameters: {'layer1': 483, 'layer2': 458, 'layer3': 300, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.008262171191215702}. Best is trial 92 with value: 0.8854567176169477.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:34:14<25:34:10, 9205.02s/it]

[I 2026-02-20 22:45:03,616] Trial 117 finished with value: 0.8833113998752609 and parameters: {'layer1': 409, 'layer2': 499, 'layer3': 461, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.001258104373532724}. Best is trial 92 with value: 0.8854567176169477.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:34:36<25:34:10, 9205.02s/it]

[I 2026-02-20 22:45:25,301] Trial 118 finished with value: 0.7054659072688098 and parameters: {'layer1': 459, 'layer2': 471, 'layer3': 277, 'activation': 'tanh', 'solver': 'sgd', 'lr': 0.003061212548486105}. Best is trial 92 with value: 0.8854567176169477.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:35:32<25:34:10, 9205.02s/it]

[I 2026-02-20 22:46:21,739] Trial 119 finished with value: 0.8801245408220593 and parameters: {'layer1': 331, 'layer2': 369, 'layer3': 246, 'activation': 'logistic', 'solver': 'adam', 'lr': 8.791380352744992e-05}. Best is trial 92 with value: 0.8854567176169477.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:35:46<25:34:10, 9205.02s/it]

[I 2026-02-20 22:46:35,467] Trial 120 finished with value: 0.7054659072688098 and parameters: {'layer1': 48, 'layer2': 294, 'layer3': 26, 'activation': 'logistic', 'solver': 'adam', 'lr': 5.32425429527534e-05}. Best is trial 92 with value: 0.8854567176169477.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:36:31<25:34:10, 9205.02s/it]

[I 2026-02-20 22:47:20,618] Trial 121 finished with value: 0.8833744719441569 and parameters: {'layer1': 346, 'layer2': 480, 'layer3': 296, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0027384337585088093}. Best is trial 92 with value: 0.8854567176169477.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:37:14<25:34:10, 9205.02s/it]

[I 2026-02-20 22:48:03,845] Trial 122 finished with value: 0.8811307399151171 and parameters: {'layer1': 362, 'layer2': 280, 'layer3': 286, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.004108267137850221}. Best is trial 92 with value: 0.8854567176169477.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:37:55<25:34:10, 9205.02s/it]

[I 2026-02-20 22:48:44,392] Trial 123 finished with value: 0.8807772727329393 and parameters: {'layer1': 300, 'layer2': 450, 'layer3': 270, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0019023427469464914}. Best is trial 92 with value: 0.8854567176169477.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:38:33<25:34:10, 9205.02s/it]

[I 2026-02-20 22:49:21,943] Trial 124 finished with value: 0.8794497530527703 and parameters: {'layer1': 420, 'layer2': 477, 'layer3': 306, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0025489945212904793}. Best is trial 92 with value: 0.8854567176169477.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:39:17<25:34:10, 9205.02s/it]

[I 2026-02-20 22:50:05,989] Trial 125 finished with value: 0.883645941767852 and parameters: {'layer1': 342, 'layer2': 486, 'layer3': 258, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0015481000186389822}. Best is trial 92 with value: 0.8854567176169477.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:39:53<25:34:10, 9205.02s/it]

[I 2026-02-20 22:50:42,288] Trial 126 finished with value: 0.8800663500754196 and parameters: {'layer1': 384, 'layer2': 334, 'layer3': 231, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0011392098722869748}. Best is trial 92 with value: 0.8854567176169477.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:40:29<25:34:10, 9205.02s/it]

[I 2026-02-20 22:51:17,852] Trial 127 finished with value: 0.8730360001935994 and parameters: {'layer1': 439, 'layer2': 462, 'layer3': 255, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0015577957411790789}. Best is trial 92 with value: 0.8854567176169477.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:41:05<25:34:10, 9205.02s/it]

[I 2026-02-20 22:51:54,248] Trial 128 finished with value: 0.8813198634828645 and parameters: {'layer1': 371, 'layer2': 345, 'layer3': 180, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0008225110825484923}. Best is trial 92 with value: 0.8854567176169477.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:41:44<25:34:10, 9205.02s/it]

[I 2026-02-20 22:52:33,835] Trial 129 finished with value: 0.8820360049356969 and parameters: {'layer1': 401, 'layer2': 491, 'layer3': 263, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00021827038174719246}. Best is trial 92 with value: 0.8854567176169477.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:42:38<25:34:10, 9205.02s/it]

[I 2026-02-20 22:53:27,084] Trial 130 finished with value: 0.883581765541542 and parameters: {'layer1': 452, 'layer2': 320, 'layer3': 40, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.005001842937220638}. Best is trial 92 with value: 0.8854567176169477.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:43:22<25:34:10, 9205.02s/it]

[I 2026-02-20 22:54:11,352] Trial 131 finished with value: 0.8148970125301298 and parameters: {'layer1': 429, 'layer2': 309, 'layer3': 14, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0021796814294183856}. Best is trial 92 with value: 0.8854567176169477.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:44:15<25:34:10, 9205.02s/it]

[I 2026-02-20 22:55:04,762] Trial 132 finished with value: 0.8819957757813096 and parameters: {'layer1': 445, 'layer2': 331, 'layer3': 281, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.004904403563990461}. Best is trial 92 with value: 0.8854567176169477.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:44:59<25:34:10, 9205.02s/it]

[I 2026-02-20 22:55:47,850] Trial 133 finished with value: 0.8842796350905701 and parameters: {'layer1': 459, 'layer2': 314, 'layer3': 34, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0034224677984741277}. Best is trial 92 with value: 0.8854567176169477.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:45:42<25:34:10, 9205.02s/it]

[I 2026-02-20 22:56:31,787] Trial 134 finished with value: 0.8496536124651055 and parameters: {'layer1': 477, 'layer2': 299, 'layer3': 34, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0034343513814201073}. Best is trial 92 with value: 0.8854567176169477.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:46:20<25:34:10, 9205.02s/it]

[I 2026-02-20 22:57:09,802] Trial 135 finished with value: 0.8834223478388935 and parameters: {'layer1': 327, 'layer2': 466, 'layer3': 54, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0015237225317572705}. Best is trial 92 with value: 0.8854567176169477.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:47:05<25:34:10, 9205.02s/it]

[I 2026-02-20 22:57:54,059] Trial 136 finished with value: 0.8799241117577792 and parameters: {'layer1': 417, 'layer2': 447, 'layer3': 243, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0018690107187242008}. Best is trial 92 with value: 0.8854567176169477.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:47:49<25:34:10, 9205.02s/it]

[I 2026-02-20 22:58:38,179] Trial 137 finished with value: 0.7713363355270009 and parameters: {'layer1': 462, 'layer2': 285, 'layer3': 21, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.001307763895451624}. Best is trial 92 with value: 0.8854567176169477.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:48:27<25:34:10, 9205.02s/it]

[I 2026-02-20 22:59:16,346] Trial 138 finished with value: 0.8805761471710698 and parameters: {'layer1': 340, 'layer2': 500, 'layer3': 291, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0009601483905756955}. Best is trial 92 with value: 0.8854567176169477.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:48:47<25:34:10, 9205.02s/it]

[I 2026-02-20 22:59:36,524] Trial 139 finished with value: 0.7054659072688098 and parameters: {'layer1': 392, 'layer2': 481, 'layer3': 500, 'activation': 'logistic', 'solver': 'sgd', 'lr': 0.0024898053746970307}. Best is trial 92 with value: 0.8854567176169477.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:49:25<25:34:10, 9205.02s/it]

[I 2026-02-20 23:00:14,542] Trial 140 finished with value: 0.881086124044778 and parameters: {'layer1': 311, 'layer2': 350, 'layer3': 318, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0031464767644173567}. Best is trial 92 with value: 0.8854567176169477.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:50:08<25:34:10, 9205.02s/it]

[I 2026-02-20 23:00:57,695] Trial 141 finished with value: 0.8392343455124642 and parameters: {'layer1': 453, 'layer2': 322, 'layer3': 43, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.005037914637209274}. Best is trial 92 with value: 0.8854567176169477.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:50:59<25:34:10, 9205.02s/it]

[I 2026-02-20 23:01:48,741] Trial 142 finished with value: 0.8794973910045585 and parameters: {'layer1': 471, 'layer2': 314, 'layer3': 32, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.00204265967975535}. Best is trial 92 with value: 0.8854567176169477.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:51:45<25:34:10, 9205.02s/it]

[I 2026-02-20 23:02:34,732] Trial 143 finished with value: 0.8826876209803973 and parameters: {'layer1': 425, 'layer2': 323, 'layer3': 75, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.003947180856978137}. Best is trial 92 with value: 0.8854567176169477.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:52:14<25:34:10, 9205.02s/it]

[I 2026-02-20 23:03:02,877] Trial 144 finished with value: 0.7054659072688098 and parameters: {'layer1': 355, 'layer2': 338, 'layer3': 11, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.007173520479415677}. Best is trial 92 with value: 0.8854567176169477.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:52:54<25:34:10, 9205.02s/it]

[I 2026-02-20 23:03:43,315] Trial 145 finished with value: 0.8836821436215576 and parameters: {'layer1': 437, 'layer2': 423, 'layer3': 43, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0017268491811313774}. Best is trial 92 with value: 0.8854567176169477.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:53:36<25:34:10, 9205.02s/it]

[I 2026-02-20 23:04:25,669] Trial 146 finished with value: 0.8808455185111314 and parameters: {'layer1': 438, 'layer2': 419, 'layer3': 89, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0017021228416985424}. Best is trial 92 with value: 0.8854567176169477.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:54:12<25:34:10, 9205.02s/it]

[I 2026-02-20 23:05:00,860] Trial 147 finished with value: 0.8806677459986293 and parameters: {'layer1': 377, 'layer2': 430, 'layer3': 270, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0011262507558685104}. Best is trial 92 with value: 0.8854567176169477.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:54:56<25:34:10, 9205.02s/it]

[I 2026-02-20 23:05:44,990] Trial 148 finished with value: 0.8828503555986407 and parameters: {'layer1': 407, 'layer2': 457, 'layer3': 57, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0014055561396489928}. Best is trial 92 with value: 0.8854567176169477.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:55:42<25:34:10, 9205.02s/it]

[I 2026-02-20 23:06:31,185] Trial 149 finished with value: 0.8880113567527056 and parameters: {'layer1': 490, 'layer2': 392, 'layer3': 281, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.002237116959981246}. Best is trial 149 with value: 0.8880113567527056.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:56:28<25:34:10, 9205.02s/it]

[I 2026-02-20 23:07:17,841] Trial 150 finished with value: 0.8823451971755796 and parameters: {'layer1': 359, 'layer2': 396, 'layer3': 276, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0022456273597004825}. Best is trial 149 with value: 0.8880113567527056.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:57:16<25:34:10, 9205.02s/it]

[I 2026-02-20 23:08:04,892] Trial 151 finished with value: 0.8833712682359245 and parameters: {'layer1': 487, 'layer2': 423, 'layer3': 260, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.001668078763067006}. Best is trial 149 with value: 0.8880113567527056.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:58:15<25:34:10, 9205.02s/it]

[I 2026-02-20 23:09:03,944] Trial 152 finished with value: 0.8834181633641525 and parameters: {'layer1': 434, 'layer2': 388, 'layer3': 289, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.002911413688604655}. Best is trial 149 with value: 0.8880113567527056.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [11:59:06<25:34:10, 9205.02s/it]

[I 2026-02-20 23:09:55,018] Trial 153 finished with value: 0.8830985779161459 and parameters: {'layer1': 417, 'layer2': 436, 'layer3': 247, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0020278770633503354}. Best is trial 149 with value: 0.8880113567527056.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [12:00:03<25:34:10, 9205.02s/it]

[I 2026-02-20 23:10:51,991] Trial 154 finished with value: 0.8858919398316308 and parameters: {'layer1': 498, 'layer2': 407, 'layer3': 308, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.002361302484744467}. Best is trial 149 with value: 0.8880113567527056.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [12:00:52<25:34:10, 9205.02s/it]

[I 2026-02-20 23:11:41,529] Trial 155 finished with value: 0.8821051023202215 and parameters: {'layer1': 500, 'layer2': 413, 'layer3': 310, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.002325018673168159}. Best is trial 149 with value: 0.8880113567527056.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [12:01:48<25:34:10, 9205.02s/it]

[I 2026-02-20 23:12:37,575] Trial 156 finished with value: 0.8825280609377758 and parameters: {'layer1': 493, 'layer2': 408, 'layer3': 332, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.003817960062555274}. Best is trial 149 with value: 0.8880113567527056.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [12:02:23<25:34:10, 9205.02s/it]

[I 2026-02-20 23:13:12,758] Trial 157 finished with value: 0.8758688401242907 and parameters: {'layer1': 489, 'layer2': 403, 'layer3': 298, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0003526733249694318}. Best is trial 149 with value: 0.8880113567527056.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [12:03:09<25:34:10, 9205.02s/it]

[I 2026-02-20 23:13:58,684] Trial 158 finished with value: 0.8472540314613722 and parameters: {'layer1': 463, 'layer2': 382, 'layer3': 25, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0027984979236258794}. Best is trial 149 with value: 0.8880113567527056.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [12:03:54<25:34:10, 9205.02s/it]

[I 2026-02-20 23:14:42,946] Trial 159 finished with value: 0.8826593958056904 and parameters: {'layer1': 476, 'layer2': 366, 'layer3': 281, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.001253136441857356}. Best is trial 149 with value: 0.8880113567527056.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [12:04:39<25:34:10, 9205.02s/it]

[I 2026-02-20 23:15:28,618] Trial 160 finished with value: 0.8785291754064211 and parameters: {'layer1': 368, 'layer2': 392, 'layer3': 268, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00164571169361158}. Best is trial 149 with value: 0.8880113567527056.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [12:05:36<25:34:10, 9205.02s/it]

[I 2026-02-20 23:16:25,813] Trial 161 finished with value: 0.8780450618257853 and parameters: {'layer1': 446, 'layer2': 444, 'layer3': 254, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0018590350324191932}. Best is trial 149 with value: 0.8880113567527056.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [12:06:18<25:34:10, 9205.02s/it]

[I 2026-02-20 23:17:07,216] Trial 162 finished with value: 0.8850260705861744 and parameters: {'layer1': 392, 'layer2': 469, 'layer3': 289, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0024790816380779418}. Best is trial 149 with value: 0.8880113567527056.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [12:07:00<25:34:10, 9205.02s/it]

[I 2026-02-20 23:17:49,313] Trial 163 finished with value: 0.88202051169235 and parameters: {'layer1': 386, 'layer2': 472, 'layer3': 306, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.002449920329400371}. Best is trial 149 with value: 0.8880113567527056.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [12:07:40<25:34:10, 9205.02s/it]

[I 2026-02-20 23:18:29,088] Trial 164 finished with value: 0.880619667574023 and parameters: {'layer1': 406, 'layer2': 486, 'layer3': 287, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.003388315467374926}. Best is trial 149 with value: 0.8880113567527056.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [12:08:17<25:34:10, 9205.02s/it]

[I 2026-02-20 23:19:06,691] Trial 165 finished with value: 0.8800896612132408 and parameters: {'layer1': 392, 'layer2': 307, 'layer3': 316, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.001383914580130685}. Best is trial 149 with value: 0.8880113567527056.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [12:08:59<25:34:10, 9205.02s/it]

[I 2026-02-20 23:19:48,202] Trial 166 finished with value: 0.883135218524709 and parameters: {'layer1': 347, 'layer2': 426, 'layer3': 325, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0020562681789079522}. Best is trial 149 with value: 0.8880113567527056.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [12:09:17<25:34:10, 9205.02s/it]

[I 2026-02-20 23:20:06,751] Trial 167 finished with value: 0.7054659072688098 and parameters: {'layer1': 376, 'layer2': 273, 'layer3': 299, 'activation': 'tanh', 'solver': 'sgd', 'lr': 0.0010092400878089817}. Best is trial 149 with value: 0.8880113567527056.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [12:10:25<25:34:10, 9205.02s/it]

[I 2026-02-20 23:21:14,411] Trial 168 finished with value: 0.8868074026479587 and parameters: {'layer1': 394, 'layer2': 456, 'layer3': 275, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.003012715769059627}. Best is trial 149 with value: 0.8880113567527056.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [12:11:22<25:34:10, 9205.02s/it]

[I 2026-02-20 23:22:11,622] Trial 169 finished with value: 0.8836202475659002 and parameters: {'layer1': 398, 'layer2': 450, 'layer3': 273, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0029723481672672574}. Best is trial 149 with value: 0.8880113567527056.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [12:12:20<25:34:10, 9205.02s/it]

[I 2026-02-20 23:23:08,892] Trial 170 finished with value: 0.8831935172524277 and parameters: {'layer1': 409, 'layer2': 295, 'layer3': 353, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0026848317825836376}. Best is trial 149 with value: 0.8880113567527056.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [12:13:02<25:34:10, 9205.02s/it]

[I 2026-02-20 23:23:51,433] Trial 171 finished with value: 0.8812457763077413 and parameters: {'layer1': 365, 'layer2': 458, 'layer3': 281, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0022617634768824653}. Best is trial 149 with value: 0.8880113567527056.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [12:13:55<25:34:10, 9205.02s/it]

[I 2026-02-20 23:24:43,859] Trial 172 finished with value: 0.8834963252817669 and parameters: {'layer1': 384, 'layer2': 473, 'layer3': 291, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0034412223219387026}. Best is trial 149 with value: 0.8880113567527056.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [12:14:35<25:34:10, 9205.02s/it]

[I 2026-02-20 23:25:24,271] Trial 173 finished with value: 0.8811918173986312 and parameters: {'layer1': 333, 'layer2': 483, 'layer3': 264, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0015055375583888325}. Best is trial 149 with value: 0.8880113567527056.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [12:15:31<25:34:10, 9205.02s/it]

[I 2026-02-20 23:26:20,181] Trial 174 finished with value: 0.8827920762629151 and parameters: {'layer1': 396, 'layer2': 445, 'layer3': 276, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0018769108429006933}. Best is trial 149 with value: 0.8880113567527056.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [12:16:19<25:34:10, 9205.02s/it]

[I 2026-02-20 23:27:07,933] Trial 175 finished with value: 0.8851224597151983 and parameters: {'layer1': 423, 'layer2': 469, 'layer3': 301, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.002577594807099855}. Best is trial 149 with value: 0.8880113567527056.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [12:17:20<25:34:10, 9205.02s/it]

[I 2026-02-20 23:28:09,051] Trial 176 finished with value: 0.882964194719837 and parameters: {'layer1': 428, 'layer2': 464, 'layer3': 309, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.00389523520548058}. Best is trial 149 with value: 0.8880113567527056.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [12:18:09<25:34:10, 9205.02s/it]

[I 2026-02-20 23:28:58,052] Trial 177 finished with value: 0.8852503143778577 and parameters: {'layer1': 417, 'layer2': 441, 'layer3': 301, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0027145040254379043}. Best is trial 149 with value: 0.8880113567527056.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [12:18:52<25:34:10, 9205.02s/it]

[I 2026-02-20 23:29:41,068] Trial 178 finished with value: 0.8818178715174986 and parameters: {'layer1': 417, 'layer2': 455, 'layer3': 301, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0025922179157755825}. Best is trial 149 with value: 0.8880113567527056.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [12:19:50<25:34:10, 9205.02s/it]

[I 2026-02-20 23:30:39,015] Trial 179 finished with value: 0.887086357079761 and parameters: {'layer1': 403, 'layer2': 464, 'layer3': 293, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.004199104323759832}. Best is trial 149 with value: 0.8880113567527056.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [12:20:36<25:34:10, 9205.02s/it]

[I 2026-02-20 23:31:25,708] Trial 180 finished with value: 0.8830368276935744 and parameters: {'layer1': 403, 'layer2': 437, 'layer3': 323, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.004206550958158881}. Best is trial 149 with value: 0.8880113567527056.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [12:21:06<25:34:10, 9205.02s/it]

[I 2026-02-20 23:31:55,031] Trial 181 finished with value: 0.7054659072688098 and parameters: {'layer1': 422, 'layer2': 468, 'layer3': 290, 'activation': 'logistic', 'solver': 'adam', 'lr': 2.228943614009622e-05}. Best is trial 149 with value: 0.8880113567527056.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [12:22:03<25:34:10, 9205.02s/it]

[I 2026-02-20 23:32:52,077] Trial 182 finished with value: 0.8828161026157911 and parameters: {'layer1': 412, 'layer2': 460, 'layer3': 297, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0031645737423263705}. Best is trial 149 with value: 0.8880113567527056.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [12:22:52<25:34:10, 9205.02s/it]

[I 2026-02-20 23:33:41,627] Trial 183 finished with value: 0.8816380392429396 and parameters: {'layer1': 390, 'layer2': 475, 'layer3': 304, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.004457740424414798}. Best is trial 149 with value: 0.8880113567527056.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [12:23:35<25:34:10, 9205.02s/it]

[I 2026-02-20 23:34:24,193] Trial 184 finished with value: 0.8819463675689505 and parameters: {'layer1': 378, 'layer2': 309, 'layer3': 281, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.002438730968994055}. Best is trial 149 with value: 0.8880113567527056.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [12:24:24<25:34:10, 9205.02s/it]

[I 2026-02-20 23:35:12,859] Trial 185 finished with value: 0.840745651231608 and parameters: {'layer1': 401, 'layer2': 449, 'layer3': 289, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.006042876001527688}. Best is trial 149 with value: 0.8880113567527056.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [12:25:02<25:34:10, 9205.02s/it]

[I 2026-02-20 23:35:51,391] Trial 186 finished with value: 0.740304961174919 and parameters: {'layer1': 411, 'layer2': 467, 'layer3': 269, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.003213328014560397}. Best is trial 149 with value: 0.8880113567527056.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [12:25:52<25:34:10, 9205.02s/it]

[I 2026-02-20 23:36:41,680] Trial 187 finished with value: 0.8846458268637342 and parameters: {'layer1': 424, 'layer2': 376, 'layer3': 315, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0026390449866789084}. Best is trial 149 with value: 0.8880113567527056.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [12:26:57<25:34:10, 9205.02s/it]

[I 2026-02-20 23:37:45,952] Trial 188 finished with value: 0.8892474277511695 and parameters: {'layer1': 430, 'layer2': 370, 'layer3': 343, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.002801090402923063}. Best is trial 188 with value: 0.8892474277511695.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [12:27:41<25:34:10, 9205.02s/it]

[I 2026-02-20 23:38:30,831] Trial 189 finished with value: 0.8791077635352306 and parameters: {'layer1': 426, 'layer2': 379, 'layer3': 353, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0038078914377043323}. Best is trial 188 with value: 0.8892474277511695.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [12:28:22<25:34:10, 9205.02s/it]

[I 2026-02-20 23:39:11,115] Trial 190 finished with value: 0.8839221365289014 and parameters: {'layer1': 433, 'layer2': 403, 'layer3': 337, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0027537932062949816}. Best is trial 188 with value: 0.8892474277511695.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [12:29:01<25:34:10, 9205.02s/it]

[I 2026-02-20 23:39:50,423] Trial 191 finished with value: 0.8831986953184258 and parameters: {'layer1': 435, 'layer2': 401, 'layer3': 336, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0028510049749768977}. Best is trial 188 with value: 0.8892474277511695.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [12:29:48<25:34:10, 9205.02s/it]

[I 2026-02-20 23:40:37,440] Trial 192 finished with value: 0.8827224493659042 and parameters: {'layer1': 419, 'layer2': 400, 'layer3': 348, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0023561221487561437}. Best is trial 188 with value: 0.8892474277511695.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [12:30:35<25:34:10, 9205.02s/it]

[I 2026-02-20 23:41:24,347] Trial 193 finished with value: 0.883349845039222 and parameters: {'layer1': 442, 'layer2': 373, 'layer3': 322, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.003357219940343093}. Best is trial 188 with value: 0.8892474277511695.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [12:31:38<25:34:10, 9205.02s/it]

[I 2026-02-20 23:42:27,271] Trial 194 finished with value: 0.8811538889476276 and parameters: {'layer1': 425, 'layer2': 413, 'layer3': 363, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.004888147334745024}. Best is trial 188 with value: 0.8892474277511695.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [12:32:18<25:34:10, 9205.02s/it]

[I 2026-02-20 23:43:06,922] Trial 195 finished with value: 0.8844647776644008 and parameters: {'layer1': 453, 'layer2': 367, 'layer3': 320, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0021384987782916043}. Best is trial 188 with value: 0.8892474277511695.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [12:33:03<25:34:10, 9205.02s/it]

[I 2026-02-20 23:43:52,821] Trial 196 finished with value: 0.8823410405287582 and parameters: {'layer1': 455, 'layer2': 351, 'layer3': 316, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0020449276625023583}. Best is trial 188 with value: 0.8892474277511695.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [12:33:42<25:34:10, 9205.02s/it]

[I 2026-02-20 23:44:31,734] Trial 197 finished with value: 0.871494622888893 and parameters: {'layer1': 464, 'layer2': 364, 'layer3': 309, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0022353488884068132}. Best is trial 188 with value: 0.8892474277511695.

Training Exact MLP (Paper):  29%|██▊       | 4/14 [12:34:03<25:34:10, 9205.02s/it]

[I 2026-02-20 23:44:52,820] Trial 198 finished with value: 0.7054772582802332 and parameters: {'layer1': 412, 'layer2': 358, 'layer3': 326, 'activation': 'relu', 'solver': 'sgd', 'lr': 0.002916427344044163}. Best is trial 188 with value: 0.8892474277511695.

Best trial: 188. Best value: 0.889247: 100%|██████████| 200/200 [2:13:56<00:00, 40.18s/it]

[I 2026-02-20 23:45:50,554] Trial 199 finished with value: 0.8825298271783643 and parameters: {'layer1': 472, 'layer2': 374, 'layer3': 300, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.004052909524187149}. Best is trial 188 with value: 0.8892474277511695.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [12:35:03<21:57:37, 8784.18s/it][I 2026-02-20 23:45:52,290] A new study created in memory with name: no-name-4204a34f-2c28-4020-bdc7-514a70a85155

  → Best model saved.

[Exact Paper MLP] Escherichia_Coli | Piperacillin-Tazobactam

Training Exact MLP (Paper):  36%|███▌      | 5/14 [12:36:11<21:57:37, 8784.18s/it]

[I 2026-02-20 23:47:00,307] Trial 0 finished with value: 0.9000475203593272 and parameters: {'layer1': 106, 'layer2': 378, 'layer3': 494, 'activation': 'tanh', 'solver': 'sgd', 'lr': 2.540637630326899e-06}. Best is trial 0 with value: 0.9000475203593272.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [12:36:27<21:57:37, 8784.18s/it]

[I 2026-02-20 23:47:16,800] Trial 1 finished with value: 0.8987609528846084 and parameters: {'layer1': 224, 'layer2': 468, 'layer3': 352, 'activation': 'identity', 'solver': 'sgd', 'lr': 0.0006737928246172818}. Best is trial 0 with value: 0.9000475203593272.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [12:37:10<21:57:37, 8784.18s/it]

[I 2026-02-20 23:47:59,425] Trial 2 finished with value: 0.9112381037104521 and parameters: {'layer1': 365, 'layer2': 486, 'layer3': 370, 'activation': 'relu', 'solver': 'adam', 'lr': 0.004427673842797121}. Best is trial 2 with value: 0.9112381037104521.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [12:37:51<21:57:37, 8784.18s/it]

[I 2026-02-20 23:48:40,120] Trial 3 finished with value: 0.9114812228281487 and parameters: {'layer1': 316, 'layer2': 322, 'layer3': 221, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00030324871806514635}. Best is trial 3 with value: 0.9114812228281487.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [12:38:09<21:57:37, 8784.18s/it]

[I 2026-02-20 23:48:58,008] Trial 4 finished with value: 0.8987609528846084 and parameters: {'layer1': 323, 'layer2': 197, 'layer3': 454, 'activation': 'identity', 'solver': 'sgd', 'lr': 0.00012741883943351892}. Best is trial 3 with value: 0.9114812228281487.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [12:38:48<21:57:37, 8784.18s/it]

[I 2026-02-20 23:49:36,887] Trial 5 finished with value: 0.8991249774377013 and parameters: {'layer1': 301, 'layer2': 182, 'layer3': 338, 'activation': 'tanh', 'solver': 'sgd', 'lr': 2.1011899164854064e-05}. Best is trial 3 with value: 0.9114812228281487.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [12:39:03<21:57:37, 8784.18s/it]

[I 2026-02-20 23:49:52,340] Trial 6 finished with value: 0.8987609528846084 and parameters: {'layer1': 62, 'layer2': 149, 'layer3': 487, 'activation': 'identity', 'solver': 'adam', 'lr': 8.855525096767033e-06}. Best is trial 3 with value: 0.9114812228281487.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [12:39:46<21:57:37, 8784.18s/it]

[I 2026-02-20 23:50:35,554] Trial 7 finished with value: 0.8993642562498401 and parameters: {'layer1': 25, 'layer2': 341, 'layer3': 333, 'activation': 'identity', 'solver': 'sgd', 'lr': 3.4909242994845232e-06}. Best is trial 3 with value: 0.9114812228281487.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [12:40:19<21:57:37, 8784.18s/it]

[I 2026-02-20 23:51:08,307] Trial 8 finished with value: 0.9124495073646619 and parameters: {'layer1': 277, 'layer2': 323, 'layer3': 456, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.00010034541673427002}. Best is trial 8 with value: 0.9124495073646619.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [12:40:48<21:57:37, 8784.18s/it]

[I 2026-02-20 23:51:37,244] Trial 9 finished with value: 0.9101390068413899 and parameters: {'layer1': 39, 'layer2': 457, 'layer3': 496, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0005545046027566956}. Best is trial 8 with value: 0.9124495073646619.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [12:41:19<21:57:37, 8784.18s/it]

[I 2026-02-20 23:52:08,474] Trial 10 finished with value: 0.8987609528846084 and parameters: {'layer1': 492, 'layer2': 40, 'layer3': 75, 'activation': 'logistic', 'solver': 'adam', 'lr': 3.727948069184617e-05}. Best is trial 8 with value: 0.9124495073646619.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [12:41:55<21:57:37, 8784.18s/it]

[I 2026-02-20 23:52:44,163] Trial 11 finished with value: 0.9107986494852037 and parameters: {'layer1': 196, 'layer2': 306, 'layer3': 183, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00021196714117812065}. Best is trial 8 with value: 0.9124495073646619.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [12:42:51<21:57:37, 8784.18s/it]

[I 2026-02-20 23:53:40,582] Trial 12 finished with value: 0.9113923562020352 and parameters: {'layer1': 415, 'layer2': 284, 'layer3': 205, 'activation': 'relu', 'solver': 'adam', 'lr': 0.002279668059346516}. Best is trial 8 with value: 0.9124495073646619.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [12:43:11<21:57:37, 8784.18s/it]

[I 2026-02-20 23:54:00,575] Trial 13 finished with value: 0.8987609528846084 and parameters: {'layer1': 169, 'layer2': 385, 'layer3': 110, 'activation': 'logistic', 'solver': 'adam', 'lr': 5.8357986177801195e-05}. Best is trial 8 with value: 0.9124495073646619.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [12:43:33<21:57:37, 8784.18s/it]

[I 2026-02-20 23:54:22,410] Trial 14 finished with value: 0.8987609528846084 and parameters: {'layer1': 275, 'layer2': 263, 'layer3': 11, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.00047504619042887386}. Best is trial 8 with value: 0.9124495073646619.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [12:44:18<21:57:37, 8784.18s/it]

[I 2026-02-20 23:55:07,109] Trial 15 finished with value: 0.9130471516296395 and parameters: {'layer1': 382, 'layer2': 399, 'layer3': 258, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0015779223786777804}. Best is trial 15 with value: 0.9130471516296395.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [12:45:08<21:57:37, 8784.18s/it]

[I 2026-02-20 23:55:56,937] Trial 16 finished with value: 0.9112460018212596 and parameters: {'layer1': 416, 'layer2': 406, 'layer3': 272, 'activation': 'relu', 'solver': 'adam', 'lr': 0.008265068965852534}. Best is trial 15 with value: 0.9130471516296395.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [12:45:58<21:57:37, 8784.18s/it]

[I 2026-02-20 23:56:47,246] Trial 17 finished with value: 0.9102332540919704 and parameters: {'layer1': 500, 'layer2': 225, 'layer3': 412, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0013402122599750763}. Best is trial 15 with value: 0.9130471516296395.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [12:46:23<21:57:37, 8784.18s/it]

[I 2026-02-20 23:57:12,703] Trial 18 finished with value: 0.8987609528846084 and parameters: {'layer1': 385, 'layer2': 94, 'layer3': 282, 'activation': 'logistic', 'solver': 'adam', 'lr': 1.731801500220726e-05}. Best is trial 15 with value: 0.9130471516296395.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [12:47:03<21:57:37, 8784.18s/it]

[I 2026-02-20 23:57:52,155] Trial 19 finished with value: 0.9101511178635198 and parameters: {'layer1': 248, 'layer2': 422, 'layer3': 155, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.001453067182657018}. Best is trial 15 with value: 0.9130471516296395.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [12:47:39<21:57:37, 8784.18s/it]

[I 2026-02-20 23:58:28,706] Trial 20 finished with value: 0.9103497474024174 and parameters: {'layer1': 160, 'layer2': 355, 'layer3': 421, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00011060414125828477}. Best is trial 15 with value: 0.9130471516296395.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [12:48:24<21:57:37, 8784.18s/it]

[I 2026-02-20 23:59:13,542] Trial 21 finished with value: 0.9108734651315233 and parameters: {'layer1': 332, 'layer2': 316, 'layer3': 235, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00021187277311386535}. Best is trial 15 with value: 0.9130471516296395.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [12:49:06<21:57:37, 8784.18s/it]

[I 2026-02-20 23:59:55,295] Trial 22 finished with value: 0.9112787443079986 and parameters: {'layer1': 357, 'layer2': 422, 'layer3': 135, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00032113843036735997}. Best is trial 15 with value: 0.9130471516296395.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [12:49:56<21:57:37, 8784.18s/it]

[I 2026-02-21 00:00:44,962] Trial 23 finished with value: 0.9108329241955593 and parameters: {'layer1': 452, 'layer2': 338, 'layer3': 246, 'activation': 'relu', 'solver': 'adam', 'lr': 0.000993572335160618}. Best is trial 15 with value: 0.9130471516296395.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [12:50:49<21:57:37, 8784.18s/it]

[I 2026-02-21 00:01:38,478] Trial 24 finished with value: 0.9107248212220114 and parameters: {'layer1': 283, 'layer2': 247, 'layer3': 308, 'activation': 'relu', 'solver': 'adam', 'lr': 5.49780818559854e-05}. Best is trial 15 with value: 0.9130471516296395.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [12:51:12<21:57:37, 8784.18s/it]

[I 2026-02-21 00:02:01,090] Trial 25 finished with value: 0.8987609528846084 and parameters: {'layer1': 224, 'layer2': 285, 'layer3': 200, 'activation': 'relu', 'solver': 'adam', 'lr': 1.0497688558732415e-06}. Best is trial 15 with value: 0.9130471516296395.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [12:51:31<21:57:37, 8784.18s/it]

[I 2026-02-21 00:02:20,705] Trial 26 finished with value: 0.8987609528846084 and parameters: {'layer1': 407, 'layer2': 372, 'layer3': 402, 'activation': 'tanh', 'solver': 'sgd', 'lr': 0.003092746248589038}. Best is trial 15 with value: 0.9130471516296395.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [12:52:01<21:57:37, 8784.18s/it]

[I 2026-02-21 00:02:50,666] Trial 27 finished with value: 0.8987609528846084 and parameters: {'layer1': 338, 'layer2': 445, 'layer3': 78, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.00903517465598408}. Best is trial 15 with value: 0.9130471516296395.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [12:52:36<21:57:37, 8784.18s/it]

[I 2026-02-21 00:03:24,914] Trial 28 finished with value: 0.910812107371683 and parameters: {'layer1': 304, 'layer2': 315, 'layer3': 300, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0002477752799884276}. Best is trial 15 with value: 0.9130471516296395.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [12:52:54<21:57:37, 8784.18s/it]

[I 2026-02-21 00:03:43,153] Trial 29 finished with value: 0.899414222371008 and parameters: {'layer1': 114, 'layer2': 389, 'layer3': 225, 'activation': 'tanh', 'solver': 'sgd', 'lr': 8.738771730461112e-05}. Best is trial 15 with value: 0.9130471516296395.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [12:53:33<21:57:37, 8784.18s/it]

[I 2026-02-21 00:04:22,745] Trial 30 finished with value: 0.9115440985078145 and parameters: {'layer1': 266, 'layer2': 237, 'layer3': 164, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.000705956704189596}. Best is trial 15 with value: 0.9130471516296395.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [12:54:09<21:57:37, 8784.18s/it]

[I 2026-02-21 00:04:58,506] Trial 31 finished with value: 0.9111277426873267 and parameters: {'layer1': 276, 'layer2': 231, 'layer3': 162, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0007842175959482206}. Best is trial 15 with value: 0.9130471516296395.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [12:54:39<21:57:37, 8784.18s/it]

[I 2026-02-21 00:05:27,902] Trial 32 finished with value: 0.9098907218934678 and parameters: {'layer1': 233, 'layer2': 146, 'layer3': 116, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0004135377473581083}. Best is trial 15 with value: 0.9130471516296395.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [12:55:04<21:57:37, 8784.18s/it]

[I 2026-02-21 00:05:53,287] Trial 33 finished with value: 0.8987609528846084 and parameters: {'layer1': 370, 'layer2': 278, 'layer3': 376, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0022434334038536874}. Best is trial 15 with value: 0.9130471516296395.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [12:55:18<21:57:37, 8784.18s/it]

[I 2026-02-21 00:06:07,327] Trial 34 finished with value: 0.8987609528846084 and parameters: {'layer1': 191, 'layer2': 201, 'layer3': 38, 'activation': 'identity', 'solver': 'sgd', 'lr': 0.00015718310523852552}. Best is trial 15 with value: 0.9130471516296395.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [12:56:03<21:57:37, 8784.18s/it]

[I 2026-02-21 00:06:51,863] Trial 35 finished with value: 0.9110260493181446 and parameters: {'layer1': 312, 'layer2': 482, 'layer3': 177, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0009235807943026423}. Best is trial 15 with value: 0.9130471516296395.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [12:56:37<21:57:37, 8784.18s/it]

[I 2026-02-21 00:07:26,491] Trial 36 finished with value: 0.9125268875789754 and parameters: {'layer1': 259, 'layer2': 359, 'layer3': 226, 'activation': 'relu', 'solver': 'adam', 'lr': 0.005390106006715471}. Best is trial 15 with value: 0.9130471516296395.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [12:57:00<21:57:37, 8784.18s/it]

[I 2026-02-21 00:07:49,674] Trial 37 finished with value: 0.8987609528846084 and parameters: {'layer1': 255, 'layer2': 360, 'layer3': 462, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.005403849880978074}. Best is trial 15 with value: 0.9130471516296395.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [12:57:16<21:57:37, 8784.18s/it]

[I 2026-02-21 00:08:05,386] Trial 38 finished with value: 0.8987609528846084 and parameters: {'layer1': 210, 'layer2': 437, 'layer3': 256, 'activation': 'identity', 'solver': 'sgd', 'lr': 0.004166534544612309}. Best is trial 15 with value: 0.9130471516296395.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [12:57:46<21:57:37, 8784.18s/it]

[I 2026-02-21 00:08:35,145] Trial 39 finished with value: 0.911551919543248 and parameters: {'layer1': 141, 'layer2': 339, 'layer3': 362, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0016917675105655571}. Best is trial 15 with value: 0.9130471516296395.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [12:58:01<21:57:37, 8784.18s/it]

[I 2026-02-21 00:08:49,937] Trial 40 finished with value: 0.8987609528846084 and parameters: {'layer1': 136, 'layer2': 400, 'layer3': 355, 'activation': 'relu', 'solver': 'sgd', 'lr': 0.0017491552439650776}. Best is trial 15 with value: 0.9130471516296395.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [12:58:33<21:57:37, 8784.18s/it]

[I 2026-02-21 00:09:22,356] Trial 41 finished with value: 0.9113189045884942 and parameters: {'layer1': 285, 'layer2': 339, 'layer3': 440, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0055694049417864214}. Best is trial 15 with value: 0.9130471516296395.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [12:59:21<21:57:37, 8784.18s/it]

[I 2026-02-21 00:10:10,463] Trial 42 finished with value: 0.9119245062480422 and parameters: {'layer1': 246, 'layer2': 297, 'layer3': 389, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0030504660478660934}. Best is trial 15 with value: 0.9130471516296395.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [12:59:55<21:57:37, 8784.18s/it]

[I 2026-02-21 00:10:44,836] Trial 43 finished with value: 0.913529064377642 and parameters: {'layer1': 133, 'layer2': 297, 'layer3': 376, 'activation': 'relu', 'solver': 'adam', 'lr': 0.003323766192207716}. Best is trial 43 with value: 0.913529064377642.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:00:23<21:57:37, 8784.18s/it]

[I 2026-02-21 00:11:12,735] Trial 44 finished with value: 0.9123978649065825 and parameters: {'layer1': 93, 'layer2': 301, 'layer3': 390, 'activation': 'relu', 'solver': 'adam', 'lr': 0.003109885754225289}. Best is trial 43 with value: 0.913529064377642.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:00:52<21:57:37, 8784.18s/it]

[I 2026-02-21 00:11:40,896] Trial 45 finished with value: 0.9096084896422099 and parameters: {'layer1': 62, 'layer2': 268, 'layer3': 456, 'activation': 'relu', 'solver': 'adam', 'lr': 0.006884140412949993}. Best is trial 43 with value: 0.913529064377642.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:01:20<21:57:37, 8784.18s/it]

[I 2026-02-21 00:12:09,060] Trial 46 finished with value: 0.9129155354278113 and parameters: {'layer1': 69, 'layer2': 367, 'layer3': 336, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0034415555272823716}. Best is trial 43 with value: 0.913529064377642.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:01:37<21:57:37, 8784.18s/it]

[I 2026-02-21 00:12:26,337] Trial 47 finished with value: 0.8987609528846084 and parameters: {'layer1': 65, 'layer2': 496, 'layer3': 310, 'activation': 'relu', 'solver': 'adam', 'lr': 8.333385471616669e-06}. Best is trial 43 with value: 0.913529064377642.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:01:59<21:57:37, 8784.18s/it]

[I 2026-02-21 00:12:47,890] Trial 48 finished with value: 0.9108659815260112 and parameters: {'layer1': 26, 'layer2': 371, 'layer3': 341, 'activation': 'relu', 'solver': 'adam', 'lr': 0.004191516460521577}. Best is trial 43 with value: 0.913529064377642.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:02:24<21:57:37, 8784.18s/it]

[I 2026-02-21 00:13:13,657] Trial 49 finished with value: 0.9088980064372663 and parameters: {'layer1': 99, 'layer2': 469, 'layer3': 324, 'activation': 'identity', 'solver': 'adam', 'lr': 0.002655260674815803}. Best is trial 43 with value: 0.913529064377642.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:02:47<21:57:37, 8784.18s/it]

[I 2026-02-21 00:13:35,947] Trial 50 finished with value: 0.8987609528846084 and parameters: {'layer1': 179, 'layer2': 353, 'layer3': 288, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.009882329298328996}. Best is trial 43 with value: 0.913529064377642.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:03:12<21:57:37, 8784.18s/it]

[I 2026-02-21 00:14:01,070] Trial 51 finished with value: 0.9133597370391213 and parameters: {'layer1': 90, 'layer2': 328, 'layer3': 484, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0039825060021771485}. Best is trial 43 with value: 0.913529064377642.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:03:51<21:57:37, 8784.18s/it]

[I 2026-02-21 00:14:40,240] Trial 52 finished with value: 0.9116331062845358 and parameters: {'layer1': 76, 'layer2': 324, 'layer3': 482, 'activation': 'relu', 'solver': 'adam', 'lr': 0.004435197245475942}. Best is trial 43 with value: 0.913529064377642.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:04:14<21:57:37, 8784.18s/it]

[I 2026-02-21 00:15:03,220] Trial 53 finished with value: 0.9097805701178538 and parameters: {'layer1': 15, 'layer2': 411, 'layer3': 439, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0010989464589784797}. Best is trial 43 with value: 0.913529064377642.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:04:50<21:57:37, 8784.18s/it]

[I 2026-02-21 00:15:38,958] Trial 54 finished with value: 0.9131711497760024 and parameters: {'layer1': 124, 'layer2': 385, 'layer3': 261, 'activation': 'relu', 'solver': 'adam', 'lr': 0.006431857321379858}. Best is trial 43 with value: 0.913529064377642.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:05:16<21:57:37, 8784.18s/it]

[I 2026-02-21 00:16:05,298] Trial 55 finished with value: 0.9120278686029106 and parameters: {'layer1': 124, 'layer2': 389, 'layer3': 213, 'activation': 'relu', 'solver': 'adam', 'lr': 0.006859901198929576}. Best is trial 43 with value: 0.913529064377642.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:05:42<21:57:37, 8784.18s/it]

[I 2026-02-21 00:16:31,314] Trial 56 finished with value: 0.911082182475106 and parameters: {'layer1': 92, 'layer2': 374, 'layer3': 259, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0021037749004139345}. Best is trial 43 with value: 0.913529064377642.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:06:11<21:57:37, 8784.18s/it]

[I 2026-02-21 00:17:00,752] Trial 57 finished with value: 0.910282100617733 and parameters: {'layer1': 52, 'layer2': 423, 'layer3': 272, 'activation': 'relu', 'solver': 'adam', 'lr': 0.003919606056093256}. Best is trial 43 with value: 0.913529064377642.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:06:42<21:57:37, 8784.18s/it]

[I 2026-02-21 00:17:31,413] Trial 58 finished with value: 0.9118503767875504 and parameters: {'layer1': 146, 'layer2': 355, 'layer3': 236, 'activation': 'relu', 'solver': 'adam', 'lr': 0.005979206486824643}. Best is trial 43 with value: 0.913529064377642.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:07:01<21:57:37, 8784.18s/it]

[I 2026-02-21 00:17:50,471] Trial 59 finished with value: 0.8987609528846084 and parameters: {'layer1': 464, 'layer2': 19, 'layer3': 198, 'activation': 'relu', 'solver': 'sgd', 'lr': 0.0017428463587825036}. Best is trial 43 with value: 0.913529064377642.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:07:29<21:57:37, 8784.18s/it]

[I 2026-02-21 00:18:18,335] Trial 60 finished with value: 0.9119588861561502 and parameters: {'layer1': 80, 'layer2': 399, 'layer3': 327, 'activation': 'relu', 'solver': 'adam', 'lr': 0.001150433442524514}. Best is trial 43 with value: 0.913529064377642.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:07:46<21:57:37, 8784.18s/it]

[I 2026-02-21 00:18:35,096] Trial 61 finished with value: 0.8987609528846084 and parameters: {'layer1': 117, 'layer2': 326, 'layer3': 426, 'activation': 'relu', 'solver': 'adam', 'lr': 2.1007636802443805e-05}. Best is trial 43 with value: 0.913529064377642.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:08:08<21:57:37, 8784.18s/it]

[I 2026-02-21 00:18:57,605] Trial 62 finished with value: 0.8996053433331032 and parameters: {'layer1': 160, 'layer2': 289, 'layer3': 481, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0031640427489496286}. Best is trial 43 with value: 0.913529064377642.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:08:30<21:57:37, 8784.18s/it]

[I 2026-02-21 00:19:19,055] Trial 63 finished with value: 0.9100894950934404 and parameters: {'layer1': 41, 'layer2': 313, 'layer3': 491, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00781993255578008}. Best is trial 43 with value: 0.913529064377642.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:09:06<21:57:37, 8784.18s/it]

[I 2026-02-21 00:19:54,949] Trial 64 finished with value: 0.910681323677902 and parameters: {'layer1': 192, 'layer2': 362, 'layer3': 467, 'activation': 'relu', 'solver': 'adam', 'lr': 0.005404471023479238}. Best is trial 43 with value: 0.913529064377642.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:09:40<21:57:37, 8784.18s/it]

[I 2026-02-21 00:20:29,836] Trial 65 finished with value: 0.9113080319391955 and parameters: {'layer1': 210, 'layer2': 332, 'layer3': 500, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0022743565110469703}. Best is trial 43 with value: 0.913529064377642.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:10:32<21:57:37, 8784.18s/it]

[I 2026-02-21 00:21:21,061] Trial 66 finished with value: 0.9112511811464789 and parameters: {'layer1': 352, 'layer2': 256, 'layer3': 376, 'activation': 'identity', 'solver': 'adam', 'lr': 4.011790614660813e-05}. Best is trial 43 with value: 0.913529064377642.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:11:10<21:57:37, 8784.18s/it]

[I 2026-02-21 00:21:59,307] Trial 67 finished with value: 0.9102636724570561 and parameters: {'layer1': 293, 'layer2': 384, 'layer3': 291, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0005376104429956675}. Best is trial 43 with value: 0.913529064377642.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:11:38<21:57:37, 8784.18s/it]

[I 2026-02-21 00:22:27,019] Trial 68 finished with value: 0.8987609528846084 and parameters: {'layer1': 395, 'layer2': 450, 'layer3': 269, 'activation': 'relu', 'solver': 'adam', 'lr': 9.374129762861784e-06}. Best is trial 43 with value: 0.913529064377642.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:12:07<21:57:37, 8784.18s/it]

[I 2026-02-21 00:22:56,835] Trial 69 finished with value: 0.9086965856593432 and parameters: {'layer1': 128, 'layer2': 346, 'layer3': 414, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0014303912053487214}. Best is trial 43 with value: 0.913529064377642.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:12:25<21:57:37, 8784.18s/it]

[I 2026-02-21 00:23:14,201] Trial 70 finished with value: 0.8987609528846084 and parameters: {'layer1': 324, 'layer2': 418, 'layer3': 440, 'activation': 'relu', 'solver': 'sgd', 'lr': 0.009568630095855797}. Best is trial 43 with value: 0.913529064377642.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:12:52<21:57:37, 8784.18s/it]

[I 2026-02-21 00:23:41,311] Trial 71 finished with value: 0.9142184474981179 and parameters: {'layer1': 89, 'layer2': 306, 'layer3': 393, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0034001030424952038}. Best is trial 71 with value: 0.9142184474981179.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:13:27<21:57:37, 8784.18s/it]

[I 2026-02-21 00:24:16,070] Trial 72 finished with value: 0.9115100388644031 and parameters: {'layer1': 107, 'layer2': 303, 'layer3': 345, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0038869007537649892}. Best is trial 71 with value: 0.9142184474981179.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:14:05<21:57:37, 8784.18s/it]

[I 2026-02-21 00:24:54,455] Trial 73 finished with value: 0.9124163678698232 and parameters: {'layer1': 73, 'layer2': 268, 'layer3': 403, 'activation': 'relu', 'solver': 'adam', 'lr': 0.005058922018390831}. Best is trial 71 with value: 0.9142184474981179.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:14:31<21:57:37, 8784.18s/it]

[I 2026-02-21 00:25:20,748] Trial 74 finished with value: 0.910918456915201 and parameters: {'layer1': 47, 'layer2': 315, 'layer3': 471, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0026115242887592635}. Best is trial 71 with value: 0.9142184474981179.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:14:51<21:57:37, 8784.18s/it]

[I 2026-02-21 00:25:40,346] Trial 75 finished with value: 0.8987609528846084 and parameters: {'layer1': 159, 'layer2': 366, 'layer3': 230, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.007267902032439403}. Best is trial 71 with value: 0.9142184474981179.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:15:17<21:57:37, 8784.18s/it]

[I 2026-02-21 00:26:06,611] Trial 76 finished with value: 0.9114545092856907 and parameters: {'layer1': 89, 'layer2': 278, 'layer3': 316, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0034650512518415713}. Best is trial 71 with value: 0.9142184474981179.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:15:42<21:57:37, 8784.18s/it]

[I 2026-02-21 00:26:31,106] Trial 77 finished with value: 0.8987609528846084 and parameters: {'layer1': 233, 'layer2': 329, 'layer3': 423, 'activation': 'relu', 'solver': 'adam', 'lr': 1.3143307325043308e-06}. Best is trial 71 with value: 0.9142184474981179.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:16:11<21:57:37, 8784.18s/it]

[I 2026-02-21 00:26:59,895] Trial 78 finished with value: 0.9092836503947197 and parameters: {'layer1': 176, 'layer2': 348, 'layer3': 389, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0018405018258401732}. Best is trial 71 with value: 0.9142184474981179.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:16:46<21:57:37, 8784.18s/it]

[I 2026-02-21 00:27:35,612] Trial 79 finished with value: 0.9097608272151373 and parameters: {'layer1': 263, 'layer2': 396, 'layer3': 246, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0013727902749616518}. Best is trial 71 with value: 0.9142184474981179.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:17:38<21:57:37, 8784.18s/it]

[I 2026-02-21 00:28:27,502] Trial 80 finished with value: 0.9119642290316323 and parameters: {'layer1': 436, 'layer2': 434, 'layer3': 449, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0026614639292627073}. Best is trial 71 with value: 0.9142184474981179.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:18:03<21:57:37, 8784.18s/it]

[I 2026-02-21 00:28:52,618] Trial 81 finished with value: 0.910435114542301 and parameters: {'layer1': 78, 'layer2': 269, 'layer3': 405, 'activation': 'relu', 'solver': 'adam', 'lr': 0.005060957220008833}. Best is trial 71 with value: 0.9142184474981179.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:18:34<21:57:37, 8784.18s/it]

[I 2026-02-21 00:29:23,489] Trial 82 finished with value: 0.9126771273166732 and parameters: {'layer1': 107, 'layer2': 249, 'layer3': 354, 'activation': 'relu', 'solver': 'adam', 'lr': 0.006490776781876554}. Best is trial 71 with value: 0.9142184474981179.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:19:01<21:57:37, 8784.18s/it]

[I 2026-02-21 00:29:50,205] Trial 83 finished with value: 0.9114460903986913 and parameters: {'layer1': 108, 'layer2': 249, 'layer3': 301, 'activation': 'relu', 'solver': 'adam', 'lr': 0.006393819459466693}. Best is trial 71 with value: 0.9142184474981179.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:19:27<21:57:37, 8784.18s/it]

[I 2026-02-21 00:30:16,277] Trial 84 finished with value: 0.912526464156936 and parameters: {'layer1': 101, 'layer2': 218, 'layer3': 363, 'activation': 'relu', 'solver': 'adam', 'lr': 0.004371526413530437}. Best is trial 71 with value: 0.9142184474981179.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:19:54<21:57:37, 8784.18s/it]

[I 2026-02-21 00:30:42,891] Trial 85 finished with value: 0.9112729999553941 and parameters: {'layer1': 29, 'layer2': 199, 'layer3': 365, 'activation': 'relu', 'solver': 'adam', 'lr': 0.004537800720002299}. Best is trial 71 with value: 0.9142184474981179.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:20:20<21:57:37, 8784.18s/it]

[I 2026-02-21 00:31:09,640] Trial 86 finished with value: 0.9122303517682748 and parameters: {'layer1': 56, 'layer2': 210, 'layer3': 352, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0077123934664305276}. Best is trial 71 with value: 0.9142184474981179.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:20:34<21:57:37, 8784.18s/it]

[I 2026-02-21 00:31:23,818] Trial 87 finished with value: 0.8987609528846084 and parameters: {'layer1': 143, 'layer2': 176, 'layer3': 334, 'activation': 'relu', 'solver': 'sgd', 'lr': 0.003851029657754962}. Best is trial 71 with value: 0.9142184474981179.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:21:04<21:57:37, 8784.18s/it]

[I 2026-02-21 00:31:53,808] Trial 88 finished with value: 0.9126524703358319 and parameters: {'layer1': 104, 'layer2': 220, 'layer3': 377, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00285049606702696}. Best is trial 71 with value: 0.9142184474981179.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:21:36<21:57:37, 8784.18s/it]

[I 2026-02-21 00:32:25,747] Trial 89 finished with value: 0.9116578961602121 and parameters: {'layer1': 127, 'layer2': 295, 'layer3': 390, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0008168033041720827}. Best is trial 71 with value: 0.9142184474981179.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:22:02<21:57:37, 8784.18s/it]

[I 2026-02-21 00:32:51,733] Trial 90 finished with value: 0.9105955467891237 and parameters: {'layer1': 87, 'layer2': 235, 'layer3': 190, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0026410921513665823}. Best is trial 71 with value: 0.9142184474981179.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:22:32<21:57:37, 8784.18s/it]

[I 2026-02-21 00:33:21,766] Trial 91 finished with value: 0.9126411670171413 and parameters: {'layer1': 107, 'layer2': 213, 'layer3': 372, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0033812622118800807}. Best is trial 71 with value: 0.9142184474981179.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:23:07<21:57:37, 8784.18s/it]

[I 2026-02-21 00:33:55,940] Trial 92 finished with value: 0.9119302426916036 and parameters: {'layer1': 119, 'layer2': 246, 'layer3': 379, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0021294059657452507}. Best is trial 71 with value: 0.9142184474981179.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:23:36<21:57:37, 8784.18s/it]

[I 2026-02-21 00:34:25,096] Trial 93 finished with value: 0.9125049684344917 and parameters: {'layer1': 69, 'layer2': 176, 'layer3': 346, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0033024397107969524}. Best is trial 71 with value: 0.9142184474981179.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:24:12<21:57:37, 8784.18s/it]

[I 2026-02-21 00:35:01,212] Trial 94 finished with value: 0.9147625023827569 and parameters: {'layer1': 133, 'layer2': 379, 'layer3': 369, 'activation': 'relu', 'solver': 'adam', 'lr': 0.005172395966805525}. Best is trial 94 with value: 0.9147625023827569.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:24:36<21:57:37, 8784.18s/it]

[I 2026-02-21 00:35:25,488] Trial 95 finished with value: 0.9109843799799382 and parameters: {'layer1': 132, 'layer2': 188, 'layer3': 370, 'activation': 'relu', 'solver': 'adam', 'lr': 0.006324938020538836}. Best is trial 94 with value: 0.9147625023827569.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:25:12<21:57:37, 8784.18s/it]

[I 2026-02-21 00:36:01,033] Trial 96 finished with value: 0.9116376496918572 and parameters: {'layer1': 149, 'layer2': 214, 'layer3': 320, 'activation': 'relu', 'solver': 'adam', 'lr': 0.008765820778132637}. Best is trial 94 with value: 0.9147625023827569.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:25:48<21:57:37, 8784.18s/it]

[I 2026-02-21 00:36:37,628] Trial 97 finished with value: 0.9110549677840716 and parameters: {'layer1': 104, 'layer2': 373, 'layer3': 382, 'activation': 'relu', 'solver': 'adam', 'lr': 0.002847259888077199}. Best is trial 94 with value: 0.9147625023827569.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:26:22<21:57:37, 8784.18s/it]

[I 2026-02-21 00:37:11,453] Trial 98 finished with value: 0.9093070423311781 and parameters: {'layer1': 111, 'layer2': 151, 'layer3': 357, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0018191231869441613}. Best is trial 94 with value: 0.9147625023827569.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:26:55<21:57:37, 8784.18s/it]

[I 2026-02-21 00:37:44,547] Trial 99 finished with value: 0.9133730157899776 and parameters: {'layer1': 95, 'layer2': 226, 'layer3': 334, 'activation': 'relu', 'solver': 'adam', 'lr': 0.003406808292377574}. Best is trial 94 with value: 0.9147625023827569.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:27:09<21:57:37, 8784.18s/it]

[I 2026-02-21 00:37:58,218] Trial 100 finished with value: 0.8987609528846084 and parameters: {'layer1': 87, 'layer2': 226, 'layer3': 304, 'activation': 'relu', 'solver': 'sgd', 'lr': 0.0022439632655042825}. Best is trial 94 with value: 0.9147625023827569.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:27:35<21:57:37, 8784.18s/it]

[I 2026-02-21 00:38:24,429] Trial 101 finished with value: 0.9101236513142993 and parameters: {'layer1': 64, 'layer2': 240, 'layer3': 397, 'activation': 'relu', 'solver': 'adam', 'lr': 0.003471650794335963}. Best is trial 94 with value: 0.9147625023827569.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:28:06<21:57:37, 8784.18s/it]

[I 2026-02-21 00:38:55,440] Trial 102 finished with value: 0.9137292542774904 and parameters: {'layer1': 156, 'layer2': 258, 'layer3': 334, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0057818801142697565}. Best is trial 94 with value: 0.9147625023827569.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:28:35<21:57:37, 8784.18s/it]

[I 2026-02-21 00:39:24,118] Trial 103 finished with value: 0.9115956384939782 and parameters: {'layer1': 152, 'layer2': 280, 'layer3': 336, 'activation': 'relu', 'solver': 'adam', 'lr': 0.004857767934291729}. Best is trial 94 with value: 0.9147625023827569.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:29:08<21:57:37, 8784.18s/it]

[I 2026-02-21 00:39:57,327] Trial 104 finished with value: 0.9124114637627303 and parameters: {'layer1': 135, 'layer2': 263, 'layer3': 328, 'activation': 'relu', 'solver': 'adam', 'lr': 0.005823847005746244}. Best is trial 94 with value: 0.9147625023827569.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:29:45<21:57:37, 8784.18s/it]

[I 2026-02-21 00:40:34,739] Trial 105 finished with value: 0.9108247192033303 and parameters: {'layer1': 171, 'layer2': 308, 'layer3': 292, 'activation': 'relu', 'solver': 'adam', 'lr': 0.008073312987786229}. Best is trial 94 with value: 0.9147625023827569.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:30:24<21:57:37, 8784.18s/it]

[I 2026-02-21 00:41:13,672] Trial 106 finished with value: 0.9131326393790085 and parameters: {'layer1': 97, 'layer2': 407, 'layer3': 343, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0039949279530161275}. Best is trial 94 with value: 0.9147625023827569.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:30:55<21:57:37, 8784.18s/it]

[I 2026-02-21 00:41:43,924] Trial 107 finished with value: 0.909564642792866 and parameters: {'layer1': 120, 'layer2': 380, 'layer3': 348, 'activation': 'identity', 'solver': 'adam', 'lr': 0.006455859343362799}. Best is trial 94 with value: 0.9147625023827569.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:31:20<21:57:37, 8784.18s/it]

[I 2026-02-21 00:42:09,691] Trial 108 finished with value: 0.9103155978127007 and parameters: {'layer1': 82, 'layer2': 430, 'layer3': 314, 'activation': 'relu', 'solver': 'adam', 'lr': 0.004142873619754884}. Best is trial 94 with value: 0.9147625023827569.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:31:55<21:57:37, 8784.18s/it]

[I 2026-02-21 00:42:44,388] Trial 109 finished with value: 0.9114378630627508 and parameters: {'layer1': 95, 'layer2': 410, 'layer3': 275, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00963711911423586}. Best is trial 94 with value: 0.9147625023827569.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:32:21<21:57:37, 8784.18s/it]

[I 2026-02-21 00:43:09,881] Trial 110 finished with value: 0.908477403108899 and parameters: {'layer1': 41, 'layer2': 395, 'layer3': 334, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0011804683270949456}. Best is trial 94 with value: 0.9147625023827569.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:32:54<21:57:37, 8784.18s/it]

[I 2026-02-21 00:43:43,163] Trial 111 finished with value: 0.9158966965508787 and parameters: {'layer1': 98, 'layer2': 255, 'layer3': 357, 'activation': 'relu', 'solver': 'adam', 'lr': 0.004922213762594606}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:33:20<21:57:37, 8784.18s/it]

[I 2026-02-21 00:44:09,803] Trial 112 finished with value: 0.9116693344855673 and parameters: {'layer1': 56, 'layer2': 85, 'layer3': 344, 'activation': 'relu', 'solver': 'adam', 'lr': 0.004948647580345914}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:33:54<21:57:37, 8784.18s/it]

[I 2026-02-21 00:44:43,694] Trial 113 finished with value: 0.9129110750636616 and parameters: {'layer1': 117, 'layer2': 255, 'layer3': 356, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0036906175035687334}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:34:33<21:57:37, 8784.18s/it]

[I 2026-02-21 00:45:22,331] Trial 114 finished with value: 0.9137927828354255 and parameters: {'layer1': 161, 'layer2': 288, 'layer3': 362, 'activation': 'relu', 'solver': 'adam', 'lr': 0.003694739334873522}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:35:09<21:57:37, 8784.18s/it]

[I 2026-02-21 00:45:58,225] Trial 115 finished with value: 0.9110418005707253 and parameters: {'layer1': 165, 'layer2': 289, 'layer3': 413, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0015567586332241553}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:35:44<21:57:37, 8784.18s/it]

[I 2026-02-21 00:46:33,226] Trial 116 finished with value: 0.9100991818205421 and parameters: {'layer1': 130, 'layer2': 408, 'layer3': 322, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0019792943827166825}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:36:19<21:57:37, 8784.18s/it]

[I 2026-02-21 00:47:08,053] Trial 117 finished with value: 0.9110543357565822 and parameters: {'layer1': 72, 'layer2': 334, 'layer3': 263, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0025102533299711}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:37:00<21:57:37, 8784.18s/it]

[I 2026-02-21 00:47:49,153] Trial 118 finished with value: 0.9120117283562138 and parameters: {'layer1': 157, 'layer2': 388, 'layer3': 296, 'activation': 'relu', 'solver': 'adam', 'lr': 0.005200542744983789}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:37:32<21:57:37, 8784.18s/it]

[I 2026-02-21 00:48:21,663] Trial 119 finished with value: 0.913024366510854 and parameters: {'layer1': 140, 'layer2': 317, 'layer3': 280, 'activation': 'relu', 'solver': 'adam', 'lr': 0.007507584956042002}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:37:48<21:57:37, 8784.18s/it]

[I 2026-02-21 00:48:37,230] Trial 120 finished with value: 0.8987609528846084 and parameters: {'layer1': 181, 'layer2': 298, 'layer3': 240, 'activation': 'relu', 'solver': 'sgd', 'lr': 0.00767808262110494}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:38:22<21:57:37, 8784.18s/it]

[I 2026-02-21 00:49:11,171] Trial 121 finished with value: 0.9123700307749688 and parameters: {'layer1': 144, 'layer2': 321, 'layer3': 282, 'activation': 'relu', 'solver': 'adam', 'lr': 0.004572263983121088}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:38:47<21:57:37, 8784.18s/it]

[I 2026-02-21 00:49:36,262] Trial 122 finished with value: 0.9119817731412565 and parameters: {'layer1': 97, 'layer2': 345, 'layer3': 282, 'activation': 'relu', 'solver': 'adam', 'lr': 0.003816644202836297}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:39:23<21:57:37, 8784.18s/it]

[I 2026-02-21 00:50:12,512] Trial 123 finished with value: 0.9133585668448478 and parameters: {'layer1': 136, 'layer2': 274, 'layer3': 250, 'activation': 'relu', 'solver': 'adam', 'lr': 0.005890007069241448}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:39:57<21:57:37, 8784.18s/it]

[I 2026-02-21 00:50:46,648] Trial 124 finished with value: 0.9124495979434684 and parameters: {'layer1': 201, 'layer2': 278, 'layer3': 249, 'activation': 'relu', 'solver': 'adam', 'lr': 0.005836306368383668}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:40:32<21:57:37, 8784.18s/it]

[I 2026-02-21 00:51:21,233] Trial 125 finished with value: 0.9112787733923435 and parameters: {'layer1': 139, 'layer2': 291, 'layer3': 257, 'activation': 'relu', 'solver': 'adam', 'lr': 0.009918112340388642}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:41:05<21:57:37, 8784.18s/it]

[I 2026-02-21 00:51:54,048] Trial 126 finished with value: 0.912626742450299 and parameters: {'layer1': 124, 'layer2': 272, 'layer3': 223, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0071785647145881735}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:41:34<21:57:37, 8784.18s/it]

[I 2026-02-21 00:52:23,757] Trial 127 finished with value: 0.9127615102957349 and parameters: {'layer1': 138, 'layer2': 260, 'layer3': 310, 'activation': 'relu', 'solver': 'adam', 'lr': 0.005711064280132182}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:42:10<21:57:37, 8784.18s/it]

[I 2026-02-21 00:52:58,878] Trial 128 finished with value: 0.9098746428706989 and parameters: {'layer1': 186, 'layer2': 316, 'layer3': 213, 'activation': 'identity', 'solver': 'adam', 'lr': 0.00801245285440749}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:42:50<21:57:37, 8784.18s/it]

[I 2026-02-21 00:53:39,164] Trial 129 finished with value: 0.9114539393374992 and parameters: {'layer1': 167, 'layer2': 305, 'layer3': 267, 'activation': 'relu', 'solver': 'adam', 'lr': 7.937336666627189e-05}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:43:19<21:57:37, 8784.18s/it]

[I 2026-02-21 00:54:07,936] Trial 130 finished with value: 0.9126488798243798 and parameters: {'layer1': 115, 'layer2': 283, 'layer3': 368, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0030103372726164616}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:43:53<21:57:37, 8784.18s/it]

[I 2026-02-21 00:54:42,670] Trial 131 finished with value: 0.9133482063850364 and parameters: {'layer1': 81, 'layer2': 363, 'layer3': 343, 'activation': 'relu', 'solver': 'adam', 'lr': 0.004179667477138324}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:44:26<21:57:37, 8784.18s/it]

[I 2026-02-21 00:55:15,306] Trial 132 finished with value: 0.9125907903614168 and parameters: {'layer1': 95, 'layer2': 356, 'layer3': 388, 'activation': 'relu', 'solver': 'adam', 'lr': 0.004239275615241006}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:44:52<21:57:37, 8784.18s/it]

[I 2026-02-21 00:55:41,142] Trial 133 finished with value: 0.9128539174122766 and parameters: {'layer1': 83, 'layer2': 379, 'layer3': 359, 'activation': 'relu', 'solver': 'adam', 'lr': 0.004873508537106261}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:45:33<21:57:37, 8784.18s/it]

[I 2026-02-21 00:56:22,427] Trial 134 finished with value: 0.9115438949671901 and parameters: {'layer1': 154, 'layer2': 419, 'layer3': 340, 'activation': 'relu', 'solver': 'adam', 'lr': 0.006547672578343256}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:46:03<21:57:37, 8784.18s/it]

[I 2026-02-21 00:56:52,770] Trial 135 finished with value: 0.9123845251441551 and parameters: {'layer1': 129, 'layer2': 306, 'layer3': 248, 'activation': 'relu', 'solver': 'adam', 'lr': 0.003183964380028195}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:46:36<21:57:37, 8784.18s/it]

[I 2026-02-21 00:57:25,647] Trial 136 finished with value: 0.9132322937141263 and parameters: {'layer1': 112, 'layer2': 401, 'layer3': 395, 'activation': 'relu', 'solver': 'adam', 'lr': 0.002343641874353612}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:47:17<21:57:37, 8784.18s/it]

[I 2026-02-21 00:58:06,053] Trial 137 finished with value: 0.9137272689400315 and parameters: {'layer1': 113, 'layer2': 401, 'layer3': 367, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0022252718815795364}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:47:46<21:57:37, 8784.18s/it]

[I 2026-02-21 00:58:35,469] Trial 138 finished with value: 0.912802724524235 and parameters: {'layer1': 112, 'layer2': 405, 'layer3': 394, 'activation': 'relu', 'solver': 'adam', 'lr': 0.002291510246357863}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:48:11<21:57:37, 8784.18s/it]

[I 2026-02-21 00:59:00,193] Trial 139 finished with value: 0.9109850974242546 and parameters: {'layer1': 97, 'layer2': 393, 'layer3': 428, 'activation': 'relu', 'solver': 'adam', 'lr': 0.003664035890912871}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:48:36<21:57:37, 8784.18s/it]

[I 2026-02-21 00:59:25,845] Trial 140 finished with value: 0.9111715759877551 and parameters: {'layer1': 79, 'layer2': 446, 'layer3': 369, 'activation': 'relu', 'solver': 'adam', 'lr': 0.002409482218162103}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:49:07<21:57:37, 8784.18s/it]

[I 2026-02-21 00:59:56,689] Trial 141 finished with value: 0.9126535940077825 and parameters: {'layer1': 122, 'layer2': 401, 'layer3': 404, 'activation': 'relu', 'solver': 'adam', 'lr': 0.002775761846771603}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:49:55<21:57:37, 8784.18s/it]

[I 2026-02-21 01:00:44,096] Trial 142 finished with value: 0.9131225473211633 and parameters: {'layer1': 486, 'layer2': 383, 'layer3': 379, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0019579841047408356}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:50:23<21:57:37, 8784.18s/it]

[I 2026-02-21 01:01:12,779] Trial 143 finished with value: 0.9107468969933048 and parameters: {'layer1': 89, 'layer2': 368, 'layer3': 383, 'activation': 'relu', 'solver': 'adam', 'lr': 0.004215540963080441}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:50:48<21:57:37, 8784.18s/it]

[I 2026-02-21 01:01:37,542] Trial 144 finished with value: 0.9123220965228128 and parameters: {'layer1': 114, 'layer2': 384, 'layer3': 363, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0032148384457707825}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:51:29<21:57:37, 8784.18s/it]

[I 2026-02-21 01:02:17,916] Trial 145 finished with value: 0.9129576431707662 and parameters: {'layer1': 100, 'layer2': 417, 'layer3': 380, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0018938276816564997}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:52:08<21:57:37, 8784.18s/it]

[I 2026-02-21 01:02:57,155] Trial 146 finished with value: 0.9101907458165774 and parameters: {'layer1': 147, 'layer2': 376, 'layer3': 348, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00517895561656308}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:53:02<21:57:37, 8784.18s/it]

[I 2026-02-21 01:03:51,223] Trial 147 finished with value: 0.9107794414053678 and parameters: {'layer1': 482, 'layer2': 430, 'layer3': 400, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0015461107342067209}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:53:18<21:57:37, 8784.18s/it]

[I 2026-02-21 01:04:07,798] Trial 148 finished with value: 0.8987609528846084 and parameters: {'layer1': 128, 'layer2': 242, 'layer3': 327, 'activation': 'relu', 'solver': 'sgd', 'lr': 0.00035725842496608093}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:53:50<21:57:37, 8784.18s/it]

[I 2026-02-21 01:04:39,610] Trial 149 finished with value: 0.9119353885594321 and parameters: {'layer1': 65, 'layer2': 230, 'layer3': 372, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00376152729771474}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:54:16<21:57:37, 8784.18s/it]

[I 2026-02-21 01:05:05,062] Trial 150 finished with value: 0.9123121180765017 and parameters: {'layer1': 78, 'layer2': 362, 'layer3': 411, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0026856601471166117}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:55:07<21:57:37, 8784.18s/it]

[I 2026-02-21 01:05:56,737] Trial 151 finished with value: 0.9124753739027709 and parameters: {'layer1': 427, 'layer2': 392, 'layer3': 359, 'activation': 'relu', 'solver': 'adam', 'lr': 0.004359088887638504}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:55:31<21:57:37, 8784.18s/it]

[I 2026-02-21 01:06:20,552] Trial 152 finished with value: 0.9117111729345837 and parameters: {'layer1': 111, 'layer2': 407, 'layer3': 348, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0012241852212504574}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:56:21<21:57:37, 8784.18s/it]

[I 2026-02-21 01:07:09,906] Trial 153 finished with value: 0.9124692086816919 and parameters: {'layer1': 362, 'layer2': 272, 'layer3': 384, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0020954760333578154}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:57:17<21:57:37, 8784.18s/it]

[I 2026-02-21 01:08:06,447] Trial 154 finished with value: 0.9108997922210147 and parameters: {'layer1': 500, 'layer2': 464, 'layer3': 341, 'activation': 'relu', 'solver': 'adam', 'lr': 0.003203661675410196}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:57:47<21:57:37, 8784.18s/it]

[I 2026-02-21 01:08:35,898] Trial 155 finished with value: 0.8987609528846084 and parameters: {'layer1': 487, 'layer2': 256, 'layer3': 374, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.005704790738396031}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:58:35<21:57:37, 8784.18s/it]

[I 2026-02-21 01:09:24,630] Trial 156 finished with value: 0.9123417763479882 and parameters: {'layer1': 394, 'layer2': 381, 'layer3': 354, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0016492675999072715}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:59:22<21:57:37, 8784.18s/it]

[I 2026-02-21 01:10:11,804] Trial 157 finished with value: 0.9115431537759356 and parameters: {'layer1': 458, 'layer2': 396, 'layer3': 331, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0009735042900028271}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [13:59:48<21:57:37, 8784.18s/it]

[I 2026-02-21 01:10:37,708] Trial 158 finished with value: 0.9110173222534657 and parameters: {'layer1': 87, 'layer2': 350, 'layer3': 431, 'activation': 'identity', 'solver': 'adam', 'lr': 0.002391637768470374}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [14:00:14<21:57:37, 8784.18s/it]

[I 2026-02-21 01:11:03,446] Trial 159 finished with value: 0.9123824861992251 and parameters: {'layer1': 105, 'layer2': 425, 'layer3': 368, 'activation': 'relu', 'solver': 'adam', 'lr': 0.004582622537282106}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [14:01:04<21:57:37, 8784.18s/it]

[I 2026-02-21 01:11:53,345] Trial 160 finished with value: 0.9134728703217126 and parameters: {'layer1': 471, 'layer2': 291, 'layer3': 398, 'activation': 'relu', 'solver': 'adam', 'lr': 0.003535105373069216}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [14:01:57<21:57:37, 8784.18s/it]

[I 2026-02-21 01:12:46,792] Trial 161 finished with value: 0.9127471191543579 and parameters: {'layer1': 483, 'layer2': 292, 'layer3': 391, 'activation': 'relu', 'solver': 'adam', 'lr': 0.003537583000614117}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [14:02:32<21:57:37, 8784.18s/it]

[I 2026-02-21 01:13:21,268] Trial 162 finished with value: 0.9119381094610205 and parameters: {'layer1': 135, 'layer2': 298, 'layer3': 413, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0028939829854098026}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [14:03:30<21:57:37, 8784.18s/it]

[I 2026-02-21 01:14:19,717] Trial 163 finished with value: 0.9134884007534028 and parameters: {'layer1': 476, 'layer2': 266, 'layer3': 363, 'activation': 'relu', 'solver': 'adam', 'lr': 0.003911943786123461}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [14:04:23<21:57:37, 8784.18s/it]

[I 2026-02-21 01:15:12,329] Trial 164 finished with value: 0.9125729572261655 and parameters: {'layer1': 470, 'layer2': 283, 'layer3': 398, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0001695573188539013}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [14:05:11<21:57:37, 8784.18s/it]

[I 2026-02-21 01:16:00,639] Trial 165 finished with value: 0.9129608428462065 and parameters: {'layer1': 476, 'layer2': 262, 'layer3': 360, 'activation': 'relu', 'solver': 'adam', 'lr': 0.005653880804176232}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [14:06:02<21:57:37, 8784.18s/it]

[I 2026-02-21 01:16:51,101] Trial 166 finished with value: 0.914301797984546 and parameters: {'layer1': 463, 'layer2': 277, 'layer3': 378, 'activation': 'relu', 'solver': 'adam', 'lr': 0.004042513566176579}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [14:06:51<21:57:37, 8784.18s/it]

[I 2026-02-21 01:17:40,321] Trial 167 finished with value: 0.9131669834975179 and parameters: {'layer1': 443, 'layer2': 270, 'layer3': 352, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0042069227222501174}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [14:07:45<21:57:37, 8784.18s/it]

[I 2026-02-21 01:18:34,654] Trial 168 finished with value: 0.9124212773906881 and parameters: {'layer1': 465, 'layer2': 269, 'layer3': 369, 'activation': 'relu', 'solver': 'adam', 'lr': 0.006537886644493678}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [14:08:43<21:57:37, 8784.18s/it]

[I 2026-02-21 01:19:31,995] Trial 169 finished with value: 0.9137731963629114 and parameters: {'layer1': 474, 'layer2': 276, 'layer3': 353, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00475298688083357}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [14:09:04<21:57:37, 8784.18s/it]

[I 2026-02-21 01:19:52,959] Trial 170 finished with value: 0.8987609528846084 and parameters: {'layer1': 473, 'layer2': 250, 'layer3': 140, 'activation': 'relu', 'solver': 'sgd', 'lr': 0.005074626923857105}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [14:09:51<21:57:37, 8784.18s/it]

[I 2026-02-21 01:20:39,883] Trial 171 finished with value: 0.9130301646290013 and parameters: {'layer1': 447, 'layer2': 276, 'layer3': 354, 'activation': 'relu', 'solver': 'adam', 'lr': 0.004322476432289925}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [14:10:36<21:57:37, 8784.18s/it]

[I 2026-02-21 01:21:25,053] Trial 172 finished with value: 0.9126856548189242 and parameters: {'layer1': 449, 'layer2': 288, 'layer3': 386, 'activation': 'relu', 'solver': 'adam', 'lr': 0.003587214833062115}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [14:11:32<21:57:37, 8784.18s/it]

[I 2026-02-21 01:22:21,070] Trial 173 finished with value: 0.9158851931908188 and parameters: {'layer1': 440, 'layer2': 265, 'layer3': 337, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0050307967756565925}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [14:12:38<21:57:37, 8784.18s/it]

[I 2026-02-21 01:23:26,897] Trial 174 finished with value: 0.9128666969111163 and parameters: {'layer1': 455, 'layer2': 257, 'layer3': 318, 'activation': 'relu', 'solver': 'adam', 'lr': 0.006222594008589583}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [14:13:30<21:57:37, 8784.18s/it]

[I 2026-02-21 01:24:19,736] Trial 175 finished with value: 0.911927291333188 and parameters: {'layer1': 494, 'layer2': 237, 'layer3': 341, 'activation': 'relu', 'solver': 'adam', 'lr': 0.005215573210704819}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [14:14:10<21:57:37, 8784.18s/it]

[I 2026-02-21 01:24:59,770] Trial 176 finished with value: 0.9105236832530418 and parameters: {'layer1': 431, 'layer2': 286, 'layer3': 362, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00846801664018928}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [14:15:06<21:57:37, 8784.18s/it]

[I 2026-02-21 01:25:55,403] Trial 177 finished with value: 0.9141901068491183 and parameters: {'layer1': 460, 'layer2': 295, 'layer3': 334, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0029174854454330637}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [14:16:01<21:57:37, 8784.18s/it]

[I 2026-02-21 01:26:50,596] Trial 178 finished with value: 0.9134223432753228 and parameters: {'layer1': 460, 'layer2': 302, 'layer3': 334, 'activation': 'relu', 'solver': 'adam', 'lr': 0.002981758762173828}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [14:16:56<21:57:37, 8784.18s/it]

[I 2026-02-21 01:27:44,936] Trial 179 finished with value: 0.9089261490942793 and parameters: {'layer1': 416, 'layer2': 303, 'layer3': 331, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0030749110860067872}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [14:17:57<21:57:37, 8784.18s/it]

[I 2026-02-21 01:28:45,928] Trial 180 finished with value: 0.9134079839266777 and parameters: {'layer1': 460, 'layer2': 296, 'layer3': 325, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0036682606467502016}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [14:18:40<21:57:37, 8784.18s/it]

[I 2026-02-21 01:29:29,673] Trial 181 finished with value: 0.9146013090952074 and parameters: {'layer1': 466, 'layer2': 296, 'layer3': 332, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0036822471030792383}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [14:19:29<21:57:37, 8784.18s/it]

[I 2026-02-21 01:30:18,445] Trial 182 finished with value: 0.9122904449416817 and parameters: {'layer1': 465, 'layer2': 311, 'layer3': 318, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0034538855830281274}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [14:20:14<21:57:37, 8784.18s/it]

[I 2026-02-21 01:31:03,627] Trial 183 finished with value: 0.9144824982614252 and parameters: {'layer1': 455, 'layer2': 297, 'layer3': 326, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0026697978580795707}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [14:21:14<21:57:37, 8784.18s/it]

[I 2026-02-21 01:32:03,622] Trial 184 finished with value: 0.9126026360927563 and parameters: {'layer1': 459, 'layer2': 297, 'layer3': 307, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0028141145582855575}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [14:22:16<21:57:37, 8784.18s/it]

[I 2026-02-21 01:33:05,205] Trial 185 finished with value: 0.9128948710299539 and parameters: {'layer1': 474, 'layer2': 321, 'layer3': 333, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0027132469230792947}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [14:23:05<21:57:37, 8784.18s/it]

[I 2026-02-21 01:33:54,453] Trial 186 finished with value: 0.9136100801809164 and parameters: {'layer1': 444, 'layer2': 282, 'layer3': 325, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0035999718719608997}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [14:23:51<21:57:37, 8784.18s/it]

[I 2026-02-21 01:34:40,464] Trial 187 finished with value: 0.9124941164541831 and parameters: {'layer1': 445, 'layer2': 284, 'layer3': 325, 'activation': 'relu', 'solver': 'adam', 'lr': 0.003340754879492812}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [14:24:32<21:57:37, 8784.18s/it]

[I 2026-02-21 01:35:21,839] Trial 188 finished with value: 0.9114209396586961 and parameters: {'layer1': 437, 'layer2': 295, 'layer3': 313, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0036113624965015217}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [14:25:02<21:57:37, 8784.18s/it]

[I 2026-02-21 01:35:51,587] Trial 189 finished with value: 0.8987609528846084 and parameters: {'layer1': 455, 'layer2': 306, 'layer3': 323, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.004598650320298413}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [14:25:54<21:57:37, 8784.18s/it]

[I 2026-02-21 01:36:43,618] Trial 190 finished with value: 0.9127390809438497 and parameters: {'layer1': 424, 'layer2': 264, 'layer3': 341, 'activation': 'relu', 'solver': 'adam', 'lr': 0.002656328952945649}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [14:26:37<21:57:37, 8784.18s/it]

[I 2026-02-21 01:37:25,983] Trial 191 finished with value: 0.9145120702895302 and parameters: {'layer1': 468, 'layer2': 279, 'layer3': 334, 'activation': 'relu', 'solver': 'adam', 'lr': 0.004137493606671491}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [14:27:38<21:57:37, 8784.18s/it]

[I 2026-02-21 01:38:27,144] Trial 192 finished with value: 0.9120845802796188 and parameters: {'layer1': 466, 'layer2': 280, 'layer3': 332, 'activation': 'relu', 'solver': 'adam', 'lr': 0.003864318585394976}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [14:28:38<21:57:37, 8784.18s/it]

[I 2026-02-21 01:39:27,149] Trial 193 finished with value: 0.9124879494517328 and parameters: {'layer1': 481, 'layer2': 290, 'layer3': 303, 'activation': 'relu', 'solver': 'adam', 'lr': 0.003076396738386523}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [14:29:35<21:57:37, 8784.18s/it]

[I 2026-02-21 01:40:24,387] Trial 194 finished with value: 0.9119870637573069 and parameters: {'layer1': 458, 'layer2': 277, 'layer3': 351, 'activation': 'relu', 'solver': 'adam', 'lr': 0.005082400910727839}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [14:30:38<21:57:37, 8784.18s/it]

[I 2026-02-21 01:41:27,769] Trial 195 finished with value: 0.9120436915480725 and parameters: {'layer1': 440, 'layer2': 294, 'layer3': 333, 'activation': 'relu', 'solver': 'adam', 'lr': 0.004592837222459591}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [14:31:07<21:57:37, 8784.18s/it]

[I 2026-02-21 01:41:56,645] Trial 196 finished with value: 0.8987609528846084 and parameters: {'layer1': 472, 'layer2': 263, 'layer3': 323, 'activation': 'relu', 'solver': 'adam', 'lr': 3.334990108568727e-06}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [14:32:01<21:57:37, 8784.18s/it]

[I 2026-02-21 01:42:50,022] Trial 197 finished with value: 0.9140913318086511 and parameters: {'layer1': 451, 'layer2': 310, 'layer3': 364, 'activation': 'relu', 'solver': 'adam', 'lr': 0.003855660063271897}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  36%|███▌      | 5/14 [14:32:49<21:57:37, 8784.18s/it]

[I 2026-02-21 01:43:38,385] Trial 198 finished with value: 0.9132609949675338 and parameters: {'layer1': 448, 'layer2': 311, 'layer3': 362, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0022161995898478557}. Best is trial 111 with value: 0.9158966965508787.

Best trial: 111. Best value: 0.915897: 100%|██████████| 200/200 [1:58:30<00:00, 35.55s/it]

[I 2026-02-21 01:44:22,474] Trial 199 finished with value: 0.9119152741921746 and parameters: {'layer1': 466, 'layer2': 302, 'layer3': 375, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0041588980938691645}. Best is trial 111 with value: 0.9158966965508787.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [14:33:38<18:15:33, 8216.64s/it][I 2026-02-21 01:44:27,241] A new study created in memory with name: no-name-9bb86384-fbab-4efe-9195-900aa926ab39

  → Best model saved.

[Exact Paper MLP] Escherichia_Coli | Cefepime

Training Exact MLP (Paper):  43%|████▎     | 6/14 [14:33:52<18:15:33, 8216.64s/it]

[I 2026-02-21 01:44:40,980] Trial 0 finished with value: 0.7575127299461911 and parameters: {'layer1': 106, 'layer2': 140, 'layer3': 394, 'activation': 'logistic', 'solver': 'sgd', 'lr': 0.0064833069598771095}. Best is trial 0 with value: 0.7575127299461911.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [14:34:21<18:15:33, 8216.64s/it]

[I 2026-02-21 01:45:10,139] Trial 1 finished with value: 0.7575127299461911 and parameters: {'layer1': 429, 'layer2': 280, 'layer3': 219, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.8817526608908177e-06}. Best is trial 0 with value: 0.7575127299461911.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [14:34:42<18:15:33, 8216.64s/it]

[I 2026-02-21 01:45:31,320] Trial 2 finished with value: 0.759928182703358 and parameters: {'layer1': 452, 'layer2': 190, 'layer3': 45, 'activation': 'relu', 'solver': 'sgd', 'lr': 0.0002448437428745728}. Best is trial 2 with value: 0.759928182703358.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [14:36:26<18:15:33, 8216.64s/it]

[I 2026-02-21 01:47:15,113] Trial 3 finished with value: 0.8921721347208036 and parameters: {'layer1': 438, 'layer2': 347, 'layer3': 177, 'activation': 'tanh', 'solver': 'adam', 'lr': 8.068160285267057e-06}. Best is trial 3 with value: 0.8921721347208036.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [14:36:39<18:15:33, 8216.64s/it]

[I 2026-02-21 01:47:28,757] Trial 4 finished with value: 0.18963420722864108 and parameters: {'layer1': 80, 'layer2': 363, 'layer3': 98, 'activation': 'logistic', 'solver': 'sgd', 'lr': 1.0688693674703897e-05}. Best is trial 3 with value: 0.8921721347208036.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [14:36:53<18:15:33, 8216.64s/it]

[I 2026-02-21 01:47:42,578] Trial 5 finished with value: 0.7596816873511887 and parameters: {'layer1': 35, 'layer2': 326, 'layer3': 81, 'activation': 'tanh', 'solver': 'sgd', 'lr': 0.0002480356863809345}. Best is trial 3 with value: 0.8921721347208036.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [14:37:31<18:15:33, 8216.64s/it]

[I 2026-02-21 01:48:20,387] Trial 6 finished with value: 0.76527439855265 and parameters: {'layer1': 33, 'layer2': 126, 'layer3': 301, 'activation': 'identity', 'solver': 'sgd', 'lr': 7.17074883944124e-06}. Best is trial 3 with value: 0.8921721347208036.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [14:37:55<18:15:33, 8216.64s/it]

[I 2026-02-21 01:48:44,354] Trial 7 finished with value: 0.7575127299461911 and parameters: {'layer1': 451, 'layer2': 355, 'layer3': 203, 'activation': 'tanh', 'solver': 'sgd', 'lr': 0.0002144655013149507}. Best is trial 3 with value: 0.8921721347208036.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [14:38:27<18:15:33, 8216.64s/it]

[I 2026-02-21 01:49:16,534] Trial 8 finished with value: 0.8894704519532756 and parameters: {'layer1': 155, 'layer2': 220, 'layer3': 333, 'activation': 'relu', 'solver': 'adam', 'lr': 9.866858572164711e-05}. Best is trial 3 with value: 0.8921721347208036.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [14:39:07<18:15:33, 8216.64s/it]

[I 2026-02-21 01:49:56,300] Trial 9 finished with value: 0.7586640778748694 and parameters: {'layer1': 377, 'layer2': 338, 'layer3': 277, 'activation': 'logistic', 'solver': 'adam', 'lr': 1.965402316761501e-06}. Best is trial 3 with value: 0.8921721347208036.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [14:39:51<18:15:33, 8216.64s/it]

[I 2026-02-21 01:50:40,173] Trial 10 finished with value: 0.8900705360833147 and parameters: {'layer1': 307, 'layer2': 488, 'layer3': 450, 'activation': 'identity', 'solver': 'adam', 'lr': 2.7591743342359333e-05}. Best is trial 3 with value: 0.8921721347208036.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [14:40:37<18:15:33, 8216.64s/it]

[I 2026-02-21 01:51:26,503] Trial 11 finished with value: 0.8872888740437311 and parameters: {'layer1': 301, 'layer2': 487, 'layer3': 495, 'activation': 'identity', 'solver': 'adam', 'lr': 2.7663607907300873e-05}. Best is trial 3 with value: 0.8921721347208036.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [14:41:14<18:15:33, 8216.64s/it]

[I 2026-02-21 01:52:03,698] Trial 12 finished with value: 0.8902464933994414 and parameters: {'layer1': 242, 'layer2': 484, 'layer3': 163, 'activation': 'identity', 'solver': 'adam', 'lr': 3.4916730909238626e-05}. Best is trial 3 with value: 0.8921721347208036.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [14:41:39<18:15:33, 8216.64s/it]

[I 2026-02-21 01:52:28,156] Trial 13 finished with value: 0.8815726735854653 and parameters: {'layer1': 202, 'layer2': 16, 'layer3': 159, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0013926779353599604}. Best is trial 3 with value: 0.8921721347208036.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [14:42:14<18:15:33, 8216.64s/it]

[I 2026-02-21 01:53:03,294] Trial 14 finished with value: 0.8912362747243197 and parameters: {'layer1': 253, 'layer2': 420, 'layer3': 152, 'activation': 'tanh', 'solver': 'adam', 'lr': 4.489722699278437e-05}. Best is trial 3 with value: 0.8921721347208036.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [14:42:42<18:15:33, 8216.64s/it]

[I 2026-02-21 01:53:31,287] Trial 15 finished with value: 0.7575127299461911 and parameters: {'layer1': 375, 'layer2': 420, 'layer3': 129, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.0234550492377424e-06}. Best is trial 3 with value: 0.8921721347208036.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [14:43:04<18:15:33, 8216.64s/it]

[I 2026-02-21 01:53:53,640] Trial 16 finished with value: 0.7575127299461911 and parameters: {'layer1': 306, 'layer2': 417, 'layer3': 35, 'activation': 'tanh', 'solver': 'adam', 'lr': 5.825428715976329e-06}. Best is trial 3 with value: 0.8921721347208036.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [14:43:51<18:15:33, 8216.64s/it]

[I 2026-02-21 01:54:40,378] Trial 17 finished with value: 0.8880966956087647 and parameters: {'layer1': 370, 'layer2': 414, 'layer3': 232, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0016614640361133546}. Best is trial 3 with value: 0.8921721347208036.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [14:44:19<18:15:33, 8216.64s/it]

[I 2026-02-21 01:55:08,137] Trial 18 finished with value: 0.8885306785942795 and parameters: {'layer1': 204, 'layer2': 285, 'layer3': 357, 'activation': 'tanh', 'solver': 'adam', 'lr': 5.905437695818373e-05}. Best is trial 3 with value: 0.8921721347208036.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [14:45:33<18:15:33, 8216.64s/it]

[I 2026-02-21 01:56:22,609] Trial 19 finished with value: 0.8894764153117197 and parameters: {'layer1': 487, 'layer2': 396, 'layer3': 190, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.1248063769908785e-05}. Best is trial 3 with value: 0.8921721347208036.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [14:46:02<18:15:33, 8216.64s/it]

[I 2026-02-21 01:56:51,608] Trial 20 finished with value: 0.8877354741042671 and parameters: {'layer1': 255, 'layer2': 244, 'layer3': 114, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0008619652054917781}. Best is trial 3 with value: 0.8921721347208036.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [14:46:41<18:15:33, 8216.64s/it]

[I 2026-02-21 01:57:30,185] Trial 21 finished with value: 0.8899464347408863 and parameters: {'layer1': 259, 'layer2': 459, 'layer3': 166, 'activation': 'identity', 'solver': 'adam', 'lr': 3.060372716597779e-05}. Best is trial 3 with value: 0.8921721347208036.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [14:47:14<18:15:33, 8216.64s/it]

[I 2026-02-21 01:58:03,743] Trial 22 finished with value: 0.8905734430432029 and parameters: {'layer1': 212, 'layer2': 451, 'layer3': 249, 'activation': 'identity', 'solver': 'adam', 'lr': 4.301116935152517e-05}. Best is trial 3 with value: 0.8921721347208036.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [14:47:42<18:15:33, 8216.64s/it]

[I 2026-02-21 01:58:31,842] Trial 23 finished with value: 0.8858604172067622 and parameters: {'layer1': 156, 'layer2': 441, 'layer3': 262, 'activation': 'tanh', 'solver': 'adam', 'lr': 9.5164074436209e-05}. Best is trial 3 with value: 0.8921721347208036.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [14:48:30<18:15:33, 8216.64s/it]

[I 2026-02-21 01:59:19,319] Trial 24 finished with value: 0.8905754901353005 and parameters: {'layer1': 186, 'layer2': 381, 'layer3': 263, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.5519213592882308e-05}. Best is trial 3 with value: 0.8921721347208036.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [14:49:20<18:15:33, 8216.64s/it]

[I 2026-02-21 02:00:08,927] Trial 25 finished with value: 0.8926426411564824 and parameters: {'layer1': 143, 'layer2': 305, 'layer3': 285, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.4080017159765116e-05}. Best is trial 25 with value: 0.8926426411564824.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [14:49:38<18:15:33, 8216.64s/it]

[I 2026-02-21 02:00:27,674] Trial 26 finished with value: 0.7575127299461911 and parameters: {'layer1': 137, 'layer2': 306, 'layer3': 314, 'activation': 'tanh', 'solver': 'adam', 'lr': 4.731791815969221e-06}. Best is trial 25 with value: 0.8926426411564824.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [14:50:36<18:15:33, 8216.64s/it]

[I 2026-02-21 02:01:24,855] Trial 27 finished with value: 0.8916042321475395 and parameters: {'layer1': 340, 'layer2': 318, 'layer3': 141, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.622305042369845e-05}. Best is trial 25 with value: 0.8926426411564824.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [14:51:02<18:15:33, 8216.64s/it]

[I 2026-02-21 02:01:51,210] Trial 28 finished with value: 0.7575127299461911 and parameters: {'layer1': 420, 'layer2': 251, 'layer3': 10, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.932608374206027e-06}. Best is trial 25 with value: 0.8926426411564824.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [14:51:20<18:15:33, 8216.64s/it]

[I 2026-02-21 02:02:08,970] Trial 29 finished with value: 0.7575127299461911 and parameters: {'layer1': 343, 'layer2': 178, 'layer3': 379, 'activation': 'logistic', 'solver': 'sgd', 'lr': 0.008455240738355156}. Best is trial 25 with value: 0.8926426411564824.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [14:52:46<18:15:33, 8216.64s/it]

[I 2026-02-21 02:03:34,871] Trial 30 finished with value: 0.8932617821782196 and parameters: {'layer1': 491, 'layer2': 105, 'layer3': 70, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.2809275808633445e-05}. Best is trial 30 with value: 0.8932617821782196.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [14:53:49<18:15:33, 8216.64s/it]

[I 2026-02-21 02:04:37,899] Trial 31 finished with value: 0.8926817803660674 and parameters: {'layer1': 499, 'layer2': 96, 'layer3': 75, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.89150401648739e-05}. Best is trial 30 with value: 0.8932617821782196.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [14:54:17<18:15:33, 8216.64s/it]

[I 2026-02-21 02:05:06,047] Trial 32 finished with value: 0.7580195815543643 and parameters: {'layer1': 491, 'layer2': 69, 'layer3': 72, 'activation': 'tanh', 'solver': 'adam', 'lr': 3.6715004838127257e-06}. Best is trial 30 with value: 0.8932617821782196.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [14:55:01<18:15:33, 8216.64s/it]

[I 2026-02-21 02:05:50,752] Trial 33 finished with value: 0.7817096285092869 and parameters: {'layer1': 423, 'layer2': 109, 'layer3': 57, 'activation': 'tanh', 'solver': 'adam', 'lr': 8.21587546608072e-06}. Best is trial 30 with value: 0.8932617821782196.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [14:56:40<18:15:33, 8216.64s/it]

[I 2026-02-21 02:07:29,810] Trial 34 finished with value: 0.8924627096003682 and parameters: {'layer1': 498, 'layer2': 76, 'layer3': 95, 'activation': 'relu', 'solver': 'adam', 'lr': 1.7284133983872444e-05}. Best is trial 30 with value: 0.8932617821782196.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [14:58:11<18:15:33, 8216.64s/it]

[I 2026-02-21 02:09:00,161] Trial 35 finished with value: 0.8925567660752212 and parameters: {'layer1': 472, 'layer2': 85, 'layer3': 33, 'activation': 'relu', 'solver': 'adam', 'lr': 1.936060136472904e-05}. Best is trial 30 with value: 0.8932617821782196.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:00:48<18:15:33, 8216.64s/it]

[I 2026-02-21 02:11:37,399] Trial 36 finished with value: 0.47587083563730026 and parameters: {'layer1': 463, 'layer2': 176, 'layer3': 14, 'activation': 'relu', 'solver': 'sgd', 'lr': 1.8500826809693652e-06}. Best is trial 30 with value: 0.8932617821782196.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:01:33<18:15:33, 8216.64s/it]

[I 2026-02-21 02:12:22,034] Trial 37 finished with value: 0.8903305661439258 and parameters: {'layer1': 81, 'layer2': 21, 'layer3': 51, 'activation': 'relu', 'solver': 'adam', 'lr': 6.184621868493369e-05}. Best is trial 30 with value: 0.8932617821782196.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:02:05<18:15:33, 8216.64s/it]

[I 2026-02-21 02:12:54,433] Trial 38 finished with value: 0.7585263037710438 and parameters: {'layer1': 408, 'layer2': 56, 'layer3': 90, 'activation': 'relu', 'solver': 'sgd', 'lr': 0.00020829356111230586}. Best is trial 30 with value: 0.8932617821782196.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:02:35<18:15:33, 8216.64s/it]

[I 2026-02-21 02:13:24,237] Trial 39 finished with value: 0.7575127299461911 and parameters: {'layer1': 468, 'layer2': 144, 'layer3': 217, 'activation': 'logistic', 'solver': 'adam', 'lr': 1.1911208969397232e-05}. Best is trial 30 with value: 0.8932617821782196.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:03:11<18:15:33, 8216.64s/it]

[I 2026-02-21 02:14:00,662] Trial 40 finished with value: 0.33262265260679236 and parameters: {'layer1': 468, 'layer2': 95, 'layer3': 116, 'activation': 'relu', 'solver': 'sgd', 'lr': 1.924864953647777e-05}. Best is trial 30 with value: 0.8932617821782196.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:04:48<18:15:33, 8216.64s/it]

[I 2026-02-21 02:15:37,212] Trial 41 finished with value: 0.8918438576405642 and parameters: {'layer1': 489, 'layer2': 56, 'layer3': 36, 'activation': 'relu', 'solver': 'adam', 'lr': 2.0100171182962476e-05}. Best is trial 30 with value: 0.8932617821782196.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:05:19<18:15:33, 8216.64s/it]

[I 2026-02-21 02:16:07,859] Trial 42 finished with value: 0.7575127299461911 and parameters: {'layer1': 499, 'layer2': 155, 'layer3': 71, 'activation': 'relu', 'solver': 'adam', 'lr': 7.911408130765286e-06}. Best is trial 30 with value: 0.8932617821782196.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:06:01<18:15:33, 8216.64s/it]

[I 2026-02-21 02:16:50,837] Trial 43 finished with value: 0.8901873848315882 and parameters: {'layer1': 454, 'layer2': 95, 'layer3': 103, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00013338825417514037}. Best is trial 30 with value: 0.8932617821782196.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:06:31<18:15:33, 8216.64s/it]

[I 2026-02-21 02:17:20,481] Trial 44 finished with value: 0.7588384694100553 and parameters: {'layer1': 442, 'layer2': 216, 'layer3': 86, 'activation': 'relu', 'solver': 'adam', 'lr': 4.363019075255141e-06}. Best is trial 30 with value: 0.8932617821782196.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:06:57<18:15:33, 8216.64s/it]

[I 2026-02-21 02:17:45,999] Trial 45 finished with value: 0.7575127299461911 and parameters: {'layer1': 392, 'layer2': 123, 'layer3': 297, 'activation': 'logistic', 'solver': 'adam', 'lr': 2.1454260685880412e-05}. Best is trial 30 with value: 0.8932617821782196.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:07:10<18:15:33, 8216.64s/it]

[I 2026-02-21 02:17:59,654] Trial 46 finished with value: 0.7584053748773685 and parameters: {'layer1': 64, 'layer2': 76, 'layer3': 32, 'activation': 'relu', 'solver': 'adam', 'lr': 1.0809258228048939e-05}. Best is trial 30 with value: 0.8932617821782196.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:07:51<18:15:33, 8216.64s/it]

[I 2026-02-21 02:18:40,310] Trial 47 finished with value: 0.8896294370824563 and parameters: {'layer1': 475, 'layer2': 32, 'layer3': 428, 'activation': 'tanh', 'solver': 'adam', 'lr': 5.593894518326418e-05}. Best is trial 30 with value: 0.8932617821782196.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:08:19<18:15:33, 8216.64s/it]

[I 2026-02-21 02:19:08,369] Trial 48 finished with value: 0.4727084322188884 and parameters: {'layer1': 15, 'layer2': 203, 'layer3': 54, 'activation': 'relu', 'solver': 'sgd', 'lr': 2.1099420099702366e-06}. Best is trial 30 with value: 0.8932617821782196.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:08:47<18:15:33, 8216.64s/it]

[I 2026-02-21 02:19:36,017] Trial 49 finished with value: 0.7575127299461911 and parameters: {'layer1': 429, 'layer2': 130, 'layer3': 134, 'activation': 'tanh', 'solver': 'adam', 'lr': 6.1242054450349426e-06}. Best is trial 30 with value: 0.8932617821782196.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:09:29<18:15:33, 8216.64s/it]

[I 2026-02-21 02:20:18,092] Trial 50 finished with value: 0.8919042272267582 and parameters: {'layer1': 402, 'layer2': 44, 'layer3': 71, 'activation': 'tanh', 'solver': 'adam', 'lr': 8.116005559665962e-05}. Best is trial 30 with value: 0.8932617821782196.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:10:21<18:15:33, 8216.64s/it]

[I 2026-02-21 02:21:10,519] Trial 51 finished with value: 0.8895060707147359 and parameters: {'layer1': 444, 'layer2': 352, 'layer3': 175, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.5681855722462433e-05}. Best is trial 30 with value: 0.8932617821782196.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:11:58<18:15:33, 8216.64s/it]

[I 2026-02-21 02:22:47,027] Trial 52 finished with value: 0.8910542893635143 and parameters: {'layer1': 481, 'layer2': 283, 'layer3': 105, 'activation': 'tanh', 'solver': 'adam', 'lr': 8.066548840304713e-06}. Best is trial 30 with value: 0.8932617821782196.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:13:18<18:15:33, 8216.64s/it]

[I 2026-02-21 02:24:07,102] Trial 53 finished with value: 0.8922395690838172 and parameters: {'layer1': 447, 'layer2': 81, 'layer3': 199, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.2242168346972626e-05}. Best is trial 30 with value: 0.8932617821782196.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:14:32<18:15:33, 8216.64s/it]

[I 2026-02-21 02:25:21,765] Trial 54 finished with value: 0.8914177905547209 and parameters: {'layer1': 449, 'layer2': 106, 'layer3': 288, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.3541173549819247e-05}. Best is trial 30 with value: 0.8932617821782196.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:15:16<18:15:33, 8216.64s/it]

[I 2026-02-21 02:26:05,697] Trial 55 finished with value: 0.8898970222180159 and parameters: {'layer1': 500, 'layer2': 74, 'layer3': 204, 'activation': 'tanh', 'solver': 'adam', 'lr': 4.5264426860700174e-05}. Best is trial 30 with value: 0.8932617821782196.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:15:39<18:15:33, 8216.64s/it]

[I 2026-02-21 02:26:28,411] Trial 56 finished with value: 0.7575127299461911 and parameters: {'layer1': 279, 'layer2': 160, 'layer3': 328, 'activation': 'logistic', 'solver': 'adam', 'lr': 3.9589139846058334e-05}. Best is trial 30 with value: 0.8932617821782196.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:16:32<18:15:33, 8216.64s/it]

[I 2026-02-21 02:27:21,752] Trial 57 finished with value: 0.8903987147910893 and parameters: {'layer1': 466, 'layer2': 87, 'layer3': 239, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.8504732683696598e-05}. Best is trial 30 with value: 0.8932617821782196.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:18:12<18:15:33, 8216.64s/it]

[I 2026-02-21 02:29:00,878] Trial 58 finished with value: 0.8925036088675926 and parameters: {'layer1': 435, 'layer2': 115, 'layer3': 190, 'activation': 'relu', 'solver': 'adam', 'lr': 1.4370630591053629e-05}. Best is trial 30 with value: 0.8932617821782196.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:18:32<18:15:33, 8216.64s/it]

[I 2026-02-21 02:29:20,953] Trial 59 finished with value: 0.8869488766764002 and parameters: {'layer1': 125, 'layer2': 116, 'layer3': 28, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0005762641511419537}. Best is trial 30 with value: 0.8932617821782196.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:19:16<18:15:33, 8216.64s/it]

[I 2026-02-21 02:30:04,877] Trial 60 finished with value: 0.8858230443452234 and parameters: {'layer1': 479, 'layer2': 11, 'layer3': 116, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0033548970560897174}. Best is trial 30 with value: 0.8932617821782196.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:20:07<18:15:33, 8216.64s/it]

[I 2026-02-21 02:30:56,275] Trial 61 finished with value: 0.8090650107215651 and parameters: {'layer1': 433, 'layer2': 53, 'layer3': 221, 'activation': 'relu', 'solver': 'adam', 'lr': 1.539774519255805e-05}. Best is trial 30 with value: 0.8932617821782196.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:20:33<18:15:33, 8216.64s/it]

[I 2026-02-21 02:31:21,917] Trial 62 finished with value: 0.7581572262666962 and parameters: {'layer1': 355, 'layer2': 84, 'layer3': 150, 'activation': 'relu', 'solver': 'adam', 'lr': 9.262109889554642e-06}. Best is trial 30 with value: 0.8932617821782196.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:21:01<18:15:33, 8216.64s/it]

[I 2026-02-21 02:31:49,912] Trial 63 finished with value: 0.7575127299461911 and parameters: {'layer1': 457, 'layer2': 137, 'layer3': 199, 'activation': 'tanh', 'solver': 'adam', 'lr': 5.739542307680226e-06}. Best is trial 30 with value: 0.8932617821782196.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:21:58<18:15:33, 8216.64s/it]

[I 2026-02-21 02:32:47,574] Trial 64 finished with value: 0.8900246263899998 and parameters: {'layer1': 500, 'layer2': 100, 'layer3': 180, 'activation': 'identity', 'solver': 'adam', 'lr': 2.1272252825137805e-05}. Best is trial 30 with value: 0.8932617821782196.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:23:03<18:15:33, 8216.64s/it]

[I 2026-02-21 02:33:52,209] Trial 65 finished with value: 0.8664502417932052 and parameters: {'layer1': 387, 'layer2': 36, 'layer3': 277, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.4241087456109613e-05}. Best is trial 30 with value: 0.8932617821782196.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:24:05<18:15:33, 8216.64s/it]

[I 2026-02-21 02:34:54,453] Trial 66 finished with value: 0.8923335380623598 and parameters: {'layer1': 411, 'layer2': 148, 'layer3': 63, 'activation': 'relu', 'solver': 'adam', 'lr': 3.5879271328307105e-05}. Best is trial 30 with value: 0.8932617821782196.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:24:26<18:15:33, 8216.64s/it]

[I 2026-02-21 02:35:15,049] Trial 67 finished with value: 0.4735300459635072 and parameters: {'layer1': 411, 'layer2': 304, 'layer3': 65, 'activation': 'relu', 'solver': 'sgd', 'lr': 3.3688630117990494e-05}. Best is trial 30 with value: 0.8932617821782196.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:25:08<18:15:33, 8216.64s/it]

[I 2026-02-21 02:35:57,085] Trial 68 finished with value: 0.892402648304477 and parameters: {'layer1': 227, 'layer2': 234, 'layer3': 45, 'activation': 'relu', 'solver': 'adam', 'lr': 6.0825508945434795e-05}. Best is trial 30 with value: 0.8932617821782196.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:25:40<18:15:33, 8216.64s/it]

[I 2026-02-21 02:36:29,449] Trial 69 finished with value: 0.891965321380449 and parameters: {'layer1': 178, 'layer2': 260, 'layer3': 44, 'activation': 'relu', 'solver': 'adam', 'lr': 7.067384069454075e-05}. Best is trial 30 with value: 0.8932617821782196.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:26:41<18:15:33, 8216.64s/it]

[I 2026-02-21 02:37:30,288] Trial 70 finished with value: 0.8927453631370694 and parameters: {'layer1': 240, 'layer2': 378, 'layer3': 20, 'activation': 'relu', 'solver': 'adam', 'lr': 2.6257548810464494e-05}. Best is trial 30 with value: 0.8932617821782196.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:27:16<18:15:33, 8216.64s/it]

[I 2026-02-21 02:38:05,078] Trial 71 finished with value: 0.8889718993321634 and parameters: {'layer1': 281, 'layer2': 336, 'layer3': 15, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00013549057475907802}. Best is trial 30 with value: 0.8932617821782196.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:28:16<18:15:33, 8216.64s/it]

[I 2026-02-21 02:39:05,374] Trial 72 finished with value: 0.890649439345481 and parameters: {'layer1': 220, 'layer2': 370, 'layer3': 91, 'activation': 'relu', 'solver': 'adam', 'lr': 1.850888479361781e-05}. Best is trial 30 with value: 0.8932617821782196.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:28:58<18:15:33, 8216.64s/it]

[I 2026-02-21 02:39:47,542] Trial 73 finished with value: 0.8930344468806892 and parameters: {'layer1': 222, 'layer2': 399, 'layer3': 41, 'activation': 'relu', 'solver': 'adam', 'lr': 5.033244817337801e-05}. Best is trial 30 with value: 0.8932617821782196.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:29:49<18:15:33, 8216.64s/it]

[I 2026-02-21 02:40:38,501] Trial 74 finished with value: 0.8939566788842669 and parameters: {'layer1': 161, 'layer2': 375, 'layer3': 17, 'activation': 'relu', 'solver': 'adam', 'lr': 2.6923370698006948e-05}. Best is trial 74 with value: 0.8939566788842669.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:30:40<18:15:33, 8216.64s/it]

[I 2026-02-21 02:41:29,047] Trial 75 finished with value: 0.8915551934014777 and parameters: {'layer1': 164, 'layer2': 402, 'layer3': 26, 'activation': 'relu', 'solver': 'adam', 'lr': 2.684741563045734e-05}. Best is trial 74 with value: 0.8939566788842669.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:31:18<18:15:33, 8216.64s/it]

[I 2026-02-21 02:42:07,509] Trial 76 finished with value: 0.8914012750485891 and parameters: {'layer1': 186, 'layer2': 388, 'layer3': 22, 'activation': 'identity', 'solver': 'adam', 'lr': 2.401750714887555e-05}. Best is trial 74 with value: 0.8939566788842669.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:32:01<18:15:33, 8216.64s/it]

[I 2026-02-21 02:42:50,096] Trial 77 finished with value: 0.8900586530942766 and parameters: {'layer1': 135, 'layer2': 435, 'layer3': 10, 'activation': 'relu', 'solver': 'adam', 'lr': 4.3634365706725844e-05}. Best is trial 74 with value: 0.8939566788842669.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:32:48<18:15:33, 8216.64s/it]

[I 2026-02-21 02:43:37,499] Trial 78 finished with value: 0.615387992370243 and parameters: {'layer1': 320, 'layer2': 368, 'layer3': 81, 'activation': 'relu', 'solver': 'sgd', 'lr': 1.0254210399124984e-05}. Best is trial 74 with value: 0.8939566788842669.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:33:14<18:15:33, 8216.64s/it]

[I 2026-02-21 02:44:03,317] Trial 79 finished with value: 0.8128894366897812 and parameters: {'layer1': 114, 'layer2': 471, 'layer3': 44, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.00013339756570820903}. Best is trial 74 with value: 0.8939566788842669.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:33:37<18:15:33, 8216.64s/it]

[I 2026-02-21 02:44:25,962] Trial 80 finished with value: 0.7575127299461911 and parameters: {'layer1': 242, 'layer2': 321, 'layer3': 344, 'activation': 'relu', 'solver': 'adam', 'lr': 6.537680498770792e-06}. Best is trial 74 with value: 0.8939566788842669.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:34:26<18:15:33, 8216.64s/it]

[I 2026-02-21 02:45:15,390] Trial 81 finished with value: 0.8383440481307302 and parameters: {'layer1': 148, 'layer2': 404, 'layer3': 79, 'activation': 'relu', 'solver': 'adam', 'lr': 1.6812269007152248e-05}. Best is trial 74 with value: 0.8939566788842669.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:35:07<18:15:33, 8216.64s/it]

[I 2026-02-21 02:45:55,995] Trial 82 finished with value: 0.8375865383380787 and parameters: {'layer1': 102, 'layer2': 63, 'layer3': 56, 'activation': 'relu', 'solver': 'adam', 'lr': 3.152992693554802e-05}. Best is trial 74 with value: 0.8939566788842669.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:35:44<18:15:33, 8216.64s/it]

[I 2026-02-21 02:46:33,429] Trial 83 finished with value: 0.8919978807668463 and parameters: {'layer1': 171, 'layer2': 377, 'layer3': 31, 'activation': 'relu', 'solver': 'adam', 'lr': 4.8824498697503945e-05}. Best is trial 74 with value: 0.8939566788842669.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:37:09<18:15:33, 8216.64s/it]

[I 2026-02-21 02:47:58,539] Trial 84 finished with value: 0.8667061197627948 and parameters: {'layer1': 484, 'layer2': 430, 'layer3': 41, 'activation': 'relu', 'solver': 'adam', 'lr': 1.2766438255079397e-05}. Best is trial 74 with value: 0.8939566788842669.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:38:22<18:15:33, 8216.64s/it]

[I 2026-02-21 02:49:11,444] Trial 85 finished with value: 0.8923505132925694 and parameters: {'layer1': 270, 'layer2': 344, 'layer3': 98, 'activation': 'relu', 'solver': 'adam', 'lr': 1.7951136905095467e-05}. Best is trial 74 with value: 0.8939566788842669.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:39:17<18:15:33, 8216.64s/it]

[I 2026-02-21 02:50:05,928] Trial 86 finished with value: 0.8899303541547491 and parameters: {'layer1': 189, 'layer2': 296, 'layer3': 128, 'activation': 'relu', 'solver': 'adam', 'lr': 2.340603340515627e-05}. Best is trial 74 with value: 0.8939566788842669.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:40:27<18:15:33, 8216.64s/it]

[I 2026-02-21 02:51:16,507] Trial 87 finished with value: 0.8900015188017683 and parameters: {'layer1': 233, 'layer2': 361, 'layer3': 57, 'activation': 'identity', 'solver': 'adam', 'lr': 1.0172211797270484e-05}. Best is trial 74 with value: 0.8939566788842669.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:40:50<18:15:33, 8216.64s/it]

[I 2026-02-21 02:51:39,151] Trial 88 finished with value: 0.7587934202136655 and parameters: {'layer1': 207, 'layer2': 389, 'layer3': 73, 'activation': 'relu', 'solver': 'adam', 'lr': 4.7006656161139415e-06}. Best is trial 74 with value: 0.8939566788842669.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:41:07<18:15:33, 8216.64s/it]

[I 2026-02-21 02:51:55,954] Trial 89 finished with value: 0.7663910648105275 and parameters: {'layer1': 94, 'layer2': 269, 'layer3': 37, 'activation': 'tanh', 'solver': 'sgd', 'lr': 7.978214586807846e-05}. Best is trial 74 with value: 0.8939566788842669.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:42:15<18:15:33, 8216.64s/it]

[I 2026-02-21 02:53:04,635] Trial 90 finished with value: 0.8913535758838581 and parameters: {'layer1': 476, 'layer2': 120, 'layer3': 17, 'activation': 'relu', 'solver': 'adam', 'lr': 3.632539089165559e-05}. Best is trial 74 with value: 0.8939566788842669.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:42:57<18:15:33, 8216.64s/it]

[I 2026-02-21 02:53:46,700] Trial 91 finished with value: 0.8927955113811379 and parameters: {'layer1': 223, 'layer2': 111, 'layer3': 39, 'activation': 'relu', 'solver': 'adam', 'lr': 4.993116773755847e-05}. Best is trial 74 with value: 0.8939566788842669.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:43:32<18:15:33, 8216.64s/it]

[I 2026-02-21 02:54:21,190] Trial 92 finished with value: 0.8899044162459667 and parameters: {'layer1': 241, 'layer2': 93, 'layer3': 24, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00010202670208804794}. Best is trial 74 with value: 0.8939566788842669.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:44:18<18:15:33, 8216.64s/it]

[I 2026-02-21 02:55:06,944] Trial 93 finished with value: 0.8927324752964234 and parameters: {'layer1': 200, 'layer2': 64, 'layer3': 52, 'activation': 'relu', 'solver': 'adam', 'lr': 5.377328439013455e-05}. Best is trial 74 with value: 0.8939566788842669.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:44:57<18:15:33, 8216.64s/it]

[I 2026-02-21 02:55:46,127] Trial 94 finished with value: 0.890519448391348 and parameters: {'layer1': 196, 'layer2': 111, 'layer3': 313, 'activation': 'relu', 'solver': 'adam', 'lr': 5.705066398526936e-05}. Best is trial 74 with value: 0.8939566788842669.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:45:19<18:15:33, 8216.64s/it]

[I 2026-02-21 02:56:08,347] Trial 95 finished with value: 0.7575127299461911 and parameters: {'layer1': 218, 'layer2': 166, 'layer3': 49, 'activation': 'logistic', 'solver': 'adam', 'lr': 9.952665215741982e-05}. Best is trial 74 with value: 0.8939566788842669.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:45:56<18:15:33, 8216.64s/it]

[I 2026-02-21 02:56:45,631] Trial 96 finished with value: 0.8912065052813494 and parameters: {'layer1': 259, 'layer2': 131, 'layer3': 64, 'activation': 'tanh', 'solver': 'adam', 'lr': 5.1854090638146716e-05}. Best is trial 74 with value: 0.8939566788842669.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:46:28<18:15:33, 8216.64s/it]

[I 2026-02-21 02:57:17,332] Trial 97 finished with value: 0.8104835168307882 and parameters: {'layer1': 157, 'layer2': 45, 'layer3': 31, 'activation': 'relu', 'solver': 'adam', 'lr': 2.8237424324247154e-05}. Best is trial 74 with value: 0.8939566788842669.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:47:01<18:15:33, 8216.64s/it]

[I 2026-02-21 02:57:49,855] Trial 98 finished with value: 0.890950593629346 and parameters: {'layer1': 147, 'layer2': 330, 'layer3': 267, 'activation': 'tanh', 'solver': 'adam', 'lr': 4.034537442197227e-05}. Best is trial 74 with value: 0.8939566788842669.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:47:19<18:15:33, 8216.64s/it]

[I 2026-02-21 02:58:08,460] Trial 99 finished with value: 0.7579614801745553 and parameters: {'layer1': 201, 'layer2': 63, 'layer3': 10, 'activation': 'relu', 'solver': 'adam', 'lr': 2.1750927478711552e-05}. Best is trial 74 with value: 0.8939566788842669.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:47:52<18:15:33, 8216.64s/it]

[I 2026-02-21 02:58:40,870] Trial 100 finished with value: 0.8879020110317251 and parameters: {'layer1': 179, 'layer2': 417, 'layer3': 83, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00019414415755626788}. Best is trial 74 with value: 0.8939566788842669.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:49:22<18:15:33, 8216.64s/it]

[I 2026-02-21 03:00:10,967] Trial 101 finished with value: 0.8662880922228815 and parameters: {'layer1': 491, 'layer2': 101, 'layer3': 109, 'activation': 'relu', 'solver': 'adam', 'lr': 1.4355711543312383e-05}. Best is trial 74 with value: 0.8939566788842669.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:50:44<18:15:33, 8216.64s/it]

[I 2026-02-21 03:01:33,402] Trial 102 finished with value: 0.8659568788628164 and parameters: {'layer1': 464, 'layer2': 72, 'layer3': 58, 'activation': 'relu', 'solver': 'adam', 'lr': 1.7281962397886986e-05}. Best is trial 74 with value: 0.8939566788842669.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:51:05<18:15:33, 8216.64s/it]

[I 2026-02-21 03:01:54,079] Trial 103 finished with value: 0.7586965794413754 and parameters: {'layer1': 251, 'layer2': 26, 'layer3': 96, 'activation': 'relu', 'solver': 'adam', 'lr': 9.006413629753915e-06}. Best is trial 74 with value: 0.8939566788842669.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:52:00<18:15:33, 8216.64s/it]

[I 2026-02-21 03:02:49,142] Trial 104 finished with value: 0.8941149083580362 and parameters: {'layer1': 217, 'layer2': 94, 'layer3': 37, 'activation': 'relu', 'solver': 'adam', 'lr': 2.8986539452000563e-05}. Best is trial 104 with value: 0.8941149083580362.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:52:32<18:15:33, 8216.64s/it]

[I 2026-02-21 03:03:21,119] Trial 105 finished with value: 0.8905979680156708 and parameters: {'layer1': 226, 'layer2': 119, 'layer3': 39, 'activation': 'tanh', 'solver': 'adam', 'lr': 6.941859685567398e-05}. Best is trial 104 with value: 0.8941149083580362.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:53:25<18:15:33, 8216.64s/it]

[I 2026-02-21 03:04:14,216] Trial 106 finished with value: 0.891844190406952 and parameters: {'layer1': 211, 'layer2': 91, 'layer3': 48, 'activation': 'relu', 'solver': 'adam', 'lr': 3.2255267875495625e-05}. Best is trial 104 with value: 0.8941149083580362.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:54:33<18:15:33, 8216.64s/it]

[I 2026-02-21 03:05:22,333] Trial 107 finished with value: 0.8920591809192576 and parameters: {'layer1': 271, 'layer2': 111, 'layer3': 20, 'activation': 'relu', 'solver': 'adam', 'lr': 2.57795703641898e-05}. Best is trial 104 with value: 0.8941149083580362.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:55:20<18:15:33, 8216.64s/it]

[I 2026-02-21 03:06:09,405] Trial 108 finished with value: 0.8357393534994498 and parameters: {'layer1': 164, 'layer2': 137, 'layer3': 73, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.238225364539834e-05}. Best is trial 104 with value: 0.8941149083580362.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:55:59<18:15:33, 8216.64s/it]

[I 2026-02-21 03:06:48,070] Trial 109 finished with value: 0.6183890744622416 and parameters: {'layer1': 236, 'layer2': 82, 'layer3': 27, 'activation': 'identity', 'solver': 'sgd', 'lr': 7.480815450745967e-06}. Best is trial 104 with value: 0.8941149083580362.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:57:01<18:15:33, 8216.64s/it]

[I 2026-02-21 03:07:50,498] Trial 110 finished with value: 0.893451934083916 and parameters: {'layer1': 218, 'layer2': 201, 'layer3': 252, 'activation': 'relu', 'solver': 'adam', 'lr': 2.0735945881546672e-05}. Best is trial 104 with value: 0.8941149083580362.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:58:00<18:15:33, 8216.64s/it]

[I 2026-02-21 03:08:49,280] Trial 111 finished with value: 0.8931646322678197 and parameters: {'layer1': 194, 'layer2': 184, 'layer3': 247, 'activation': 'relu', 'solver': 'adam', 'lr': 2.183820810471227e-05}. Best is trial 104 with value: 0.8941149083580362.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:58:51<18:15:33, 8216.64s/it]

[I 2026-02-21 03:09:40,281] Trial 112 finished with value: 0.8930500858833437 and parameters: {'layer1': 194, 'layer2': 195, 'layer3': 487, 'activation': 'relu', 'solver': 'adam', 'lr': 2.1127098351296443e-05}. Best is trial 104 with value: 0.8941149083580362.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [15:59:39<18:15:33, 8216.64s/it]

[I 2026-02-21 03:10:27,981] Trial 113 finished with value: 0.8905544430188591 and parameters: {'layer1': 200, 'layer2': 230, 'layer3': 452, 'activation': 'relu', 'solver': 'adam', 'lr': 3.784102395352118e-05}. Best is trial 104 with value: 0.8941149083580362.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:00:31<18:15:33, 8216.64s/it]

[I 2026-02-21 03:11:20,366] Trial 114 finished with value: 0.8922334336638688 and parameters: {'layer1': 218, 'layer2': 185, 'layer3': 499, 'activation': 'relu', 'solver': 'adam', 'lr': 2.1826656151813856e-05}. Best is trial 104 with value: 0.8941149083580362.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:01:12<18:15:33, 8216.64s/it]

[I 2026-02-21 03:12:01,482] Trial 115 finished with value: 0.8923689007347949 and parameters: {'layer1': 187, 'layer2': 201, 'layer3': 373, 'activation': 'relu', 'solver': 'adam', 'lr': 4.496365461006911e-05}. Best is trial 104 with value: 0.8941149083580362.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:02:00<18:15:33, 8216.64s/it]

[I 2026-02-21 03:12:49,019] Trial 116 finished with value: 0.8914675994422083 and parameters: {'layer1': 195, 'layer2': 168, 'layer3': 426, 'activation': 'relu', 'solver': 'adam', 'lr': 2.5584256048373782e-05}. Best is trial 104 with value: 0.8941149083580362.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:02:35<18:15:33, 8216.64s/it]

[I 2026-02-21 03:13:24,750] Trial 117 finished with value: 0.888730365351144 and parameters: {'layer1': 175, 'layer2': 199, 'layer3': 257, 'activation': 'tanh', 'solver': 'adam', 'lr': 3.1244092838426834e-05}. Best is trial 104 with value: 0.8941149083580362.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:03:37<18:15:33, 8216.64s/it]

[I 2026-02-21 03:14:25,868] Trial 118 finished with value: 0.8910903614468169 and parameters: {'layer1': 253, 'layer2': 498, 'layer3': 244, 'activation': 'relu', 'solver': 'adam', 'lr': 1.8704869414491913e-05}. Best is trial 104 with value: 0.8941149083580362.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:04:00<18:15:33, 8216.64s/it]

[I 2026-02-21 03:14:49,223] Trial 119 finished with value: 0.7575127299461911 and parameters: {'layer1': 293, 'layer2': 208, 'layer3': 400, 'activation': 'logistic', 'solver': 'adam', 'lr': 5.220410081976593e-05}. Best is trial 104 with value: 0.8941149083580362.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:04:35<18:15:33, 8216.64s/it]

[I 2026-02-21 03:15:24,123] Trial 120 finished with value: 0.8919319995325814 and parameters: {'layer1': 211, 'layer2': 188, 'layer3': 488, 'activation': 'relu', 'solver': 'adam', 'lr': 8.334888993242757e-05}. Best is trial 104 with value: 0.8941149083580362.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:05:36<18:15:33, 8216.64s/it]

[I 2026-02-21 03:16:25,412] Trial 121 finished with value: 0.8912834730035121 and parameters: {'layer1': 223, 'layer2': 222, 'layer3': 38, 'activation': 'relu', 'solver': 'adam', 'lr': 2.1680850841763414e-05}. Best is trial 104 with value: 0.8941149083580362.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:06:21<18:15:33, 8216.64s/it]

[I 2026-02-21 03:17:10,378] Trial 122 finished with value: 0.892044122850483 and parameters: {'layer1': 136, 'layer2': 247, 'layer3': 232, 'activation': 'relu', 'solver': 'adam', 'lr': 2.9899691026085203e-05}. Best is trial 104 with value: 0.8941149083580362.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:07:10<18:15:33, 8216.64s/it]

[I 2026-02-21 03:17:59,627] Trial 123 finished with value: 0.8919165863865544 and parameters: {'layer1': 235, 'layer2': 179, 'layer3': 285, 'activation': 'relu', 'solver': 'adam', 'lr': 3.778517055982838e-05}. Best is trial 104 with value: 0.8941149083580362.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:08:11<18:15:33, 8216.64s/it]

[I 2026-02-21 03:19:00,359] Trial 124 finished with value: 0.8650718149155253 and parameters: {'layer1': 210, 'layer2': 153, 'layer3': 478, 'activation': 'relu', 'solver': 'adam', 'lr': 1.5074794259823615e-05}. Best is trial 104 with value: 0.8941149083580362.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:08:29<18:15:33, 8216.64s/it]

[I 2026-02-21 03:19:18,659] Trial 125 finished with value: 0.7575127299461911 and parameters: {'layer1': 168, 'layer2': 64, 'layer3': 64, 'activation': 'relu', 'solver': 'adam', 'lr': 1.2312689512401287e-05}. Best is trial 104 with value: 0.8941149083580362.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:09:21<18:15:33, 8216.64s/it]

[I 2026-02-21 03:20:10,106] Trial 126 finished with value: 0.8928811588574623 and parameters: {'layer1': 247, 'layer2': 405, 'layer3': 20, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.9736892345802734e-05}. Best is trial 104 with value: 0.8941149083580362.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:10:37<18:15:33, 8216.64s/it]

[I 2026-02-21 03:21:26,708] Trial 127 finished with value: 0.891504771103827 and parameters: {'layer1': 265, 'layer2': 397, 'layer3': 50, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.0847099208736535e-05}. Best is trial 104 with value: 0.8941149083580362.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:11:22<18:15:33, 8216.64s/it]

[I 2026-02-21 03:22:11,662] Trial 128 finished with value: 0.8930500283517302 and parameters: {'layer1': 248, 'layer2': 411, 'layer3': 20, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.4223547244041025e-05}. Best is trial 104 with value: 0.8941149083580362.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:11:52<18:15:33, 8216.64s/it]

[I 2026-02-21 03:22:41,662] Trial 129 finished with value: 0.8919623922877221 and parameters: {'layer1': 244, 'layer2': 408, 'layer3': 21, 'activation': 'tanh', 'solver': 'adam', 'lr': 6.913899752301128e-05}. Best is trial 104 with value: 0.8941149083580362.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:12:32<18:15:33, 8216.64s/it]

[I 2026-02-21 03:23:21,686] Trial 130 finished with value: 0.894816033001681 and parameters: {'layer1': 227, 'layer2': 455, 'layer3': 32, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.610807331050404e-05}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:13:16<18:15:33, 8216.64s/it]

[I 2026-02-21 03:24:05,411] Trial 131 finished with value: 0.8931316252262619 and parameters: {'layer1': 229, 'layer2': 450, 'layer3': 31, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.4908347787121374e-05}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:14:02<18:15:33, 8216.64s/it]

[I 2026-02-21 03:24:50,916] Trial 132 finished with value: 0.8926009678517277 and parameters: {'layer1': 229, 'layer2': 453, 'layer3': 31, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.3829565389079282e-05}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:14:46<18:15:33, 8216.64s/it]

[I 2026-02-21 03:25:35,437] Trial 133 finished with value: 0.8943969172581239 and parameters: {'layer1': 250, 'layer2': 462, 'layer3': 10, 'activation': 'tanh', 'solver': 'adam', 'lr': 3.371936270514514e-05}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:15:22<18:15:33, 8216.64s/it]

[I 2026-02-21 03:26:11,719] Trial 134 finished with value: 0.8647548535409666 and parameters: {'layer1': 250, 'layer2': 439, 'layer3': 13, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.9567838390067626e-05}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:15:59<18:15:33, 8216.64s/it]

[I 2026-02-21 03:26:48,841] Trial 135 finished with value: 0.8928203947777826 and parameters: {'layer1': 261, 'layer2': 453, 'layer3': 22, 'activation': 'tanh', 'solver': 'adam', 'lr': 4.331478764094657e-05}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:16:43<18:15:33, 8216.64s/it]

[I 2026-02-21 03:27:32,663] Trial 136 finished with value: 0.894574988637509 and parameters: {'layer1': 286, 'layer2': 468, 'layer3': 11, 'activation': 'tanh', 'solver': 'adam', 'lr': 4.3412681581278915e-05}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:17:04<18:15:33, 8216.64s/it]

[I 2026-02-21 03:27:53,276] Trial 137 finished with value: 0.7599425182495855 and parameters: {'layer1': 289, 'layer2': 472, 'layer3': 22, 'activation': 'tanh', 'solver': 'sgd', 'lr': 3.6725050817692703e-05}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:17:45<18:15:33, 8216.64s/it]

[I 2026-02-21 03:28:34,637] Trial 138 finished with value: 0.8930748761159958 and parameters: {'layer1': 261, 'layer2': 476, 'layer3': 12, 'activation': 'tanh', 'solver': 'adam', 'lr': 4.28916161015726e-05}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:18:33<18:15:33, 8216.64s/it]

[I 2026-02-21 03:29:21,965] Trial 139 finished with value: 0.8638481970652295 and parameters: {'layer1': 281, 'layer2': 475, 'layer3': 12, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.0162538953295422e-05}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:19:37<18:15:33, 8216.64s/it]

[I 2026-02-21 03:30:26,165] Trial 140 finished with value: 0.8926249083531819 and parameters: {'layer1': 324, 'layer2': 425, 'layer3': 34, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.6379163237193243e-05}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:20:16<18:15:33, 8216.64s/it]

[I 2026-02-21 03:31:05,171] Trial 141 finished with value: 0.8932826346388124 and parameters: {'layer1': 263, 'layer2': 463, 'layer3': 25, 'activation': 'tanh', 'solver': 'adam', 'lr': 4.028455146707088e-05}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:20:56<18:15:33, 8216.64s/it]

[I 2026-02-21 03:31:44,864] Trial 142 finished with value: 0.8669555036307267 and parameters: {'layer1': 271, 'layer2': 467, 'layer3': 10, 'activation': 'tanh', 'solver': 'adam', 'lr': 3.2257094588606865e-05}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:21:38<18:15:33, 8216.64s/it]

[I 2026-02-21 03:32:27,748] Trial 143 finished with value: 0.8911476452083911 and parameters: {'layer1': 248, 'layer2': 487, 'layer3': 31, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.5275614265884995e-05}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:22:11<18:15:33, 8216.64s/it]

[I 2026-02-21 03:33:00,244] Trial 144 finished with value: 0.8890283148846725 and parameters: {'layer1': 234, 'layer2': 448, 'layer3': 44, 'activation': 'tanh', 'solver': 'adam', 'lr': 4.3461264387022654e-05}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:22:51<18:15:33, 8216.64s/it]

[I 2026-02-21 03:33:40,448] Trial 145 finished with value: 0.8930613583243543 and parameters: {'layer1': 261, 'layer2': 499, 'layer3': 24, 'activation': 'tanh', 'solver': 'adam', 'lr': 3.253345314129279e-05}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:23:28<18:15:33, 8216.64s/it]

[I 2026-02-21 03:34:17,529] Trial 146 finished with value: 0.8381883119377035 and parameters: {'layer1': 303, 'layer2': 500, 'layer3': 10, 'activation': 'tanh', 'solver': 'adam', 'lr': 3.3839012662883836e-05}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:24:01<18:15:33, 8216.64s/it]

[I 2026-02-21 03:34:50,614] Trial 147 finished with value: 0.891593320981366 and parameters: {'layer1': 261, 'layer2': 481, 'layer3': 28, 'activation': 'tanh', 'solver': 'adam', 'lr': 5.99665089470824e-05}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:24:35<18:15:33, 8216.64s/it]

[I 2026-02-21 03:35:24,597] Trial 148 finished with value: 0.8917591128027901 and parameters: {'layer1': 51, 'layer2': 463, 'layer3': 41, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.8171519659782235e-05}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:25:15<18:15:33, 8216.64s/it]

[I 2026-02-21 03:36:04,664] Trial 149 finished with value: 0.8900455261653043 and parameters: {'layer1': 215, 'layer2': 443, 'layer3': 56, 'activation': 'tanh', 'solver': 'adam', 'lr': 3.687156358431323e-05}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:25:51<18:15:33, 8216.64s/it]

[I 2026-02-21 03:36:40,680] Trial 150 finished with value: 0.891933093423364 and parameters: {'layer1': 273, 'layer2': 491, 'layer3': 28, 'activation': 'tanh', 'solver': 'adam', 'lr': 4.761530329556224e-05}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:26:45<18:15:33, 8216.64s/it]

[I 2026-02-21 03:37:34,275] Trial 151 finished with value: 0.8937586093907676 and parameters: {'layer1': 245, 'layer2': 458, 'layer3': 20, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.0319498090649167e-05}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:27:33<18:15:33, 8216.64s/it]

[I 2026-02-21 03:38:22,460] Trial 152 finished with value: 0.8927077866070668 and parameters: {'layer1': 231, 'layer2': 460, 'layer3': 18, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.2472539518358816e-05}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:28:13<18:15:33, 8216.64s/it]

[I 2026-02-21 03:39:02,232] Trial 153 finished with value: 0.8905049471080411 and parameters: {'layer1': 258, 'layer2': 480, 'layer3': 271, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.735057745452664e-05}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:29:03<18:15:33, 8216.64s/it]

[I 2026-02-21 03:39:51,936] Trial 154 finished with value: 0.8921829268919238 and parameters: {'layer1': 286, 'layer2': 428, 'layer3': 40, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.653315354456308e-05}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:29:41<18:15:33, 8216.64s/it]

[I 2026-02-21 03:40:30,020] Trial 155 finished with value: 0.8928037530415761 and parameters: {'layer1': 240, 'layer2': 463, 'layer3': 32, 'activation': 'tanh', 'solver': 'adam', 'lr': 3.2572105174082326e-05}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:30:32<18:15:33, 8216.64s/it]

[I 2026-02-21 03:41:21,493] Trial 156 finished with value: 0.8929814049073744 and parameters: {'layer1': 221, 'layer2': 490, 'layer3': 49, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.9311436771083035e-05}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:31:05<18:15:33, 8216.64s/it]

[I 2026-02-21 03:41:54,681] Trial 157 finished with value: 0.8914423269429175 and parameters: {'layer1': 193, 'layer2': 451, 'layer3': 21, 'activation': 'tanh', 'solver': 'adam', 'lr': 4.1581316542009314e-05}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:31:50<18:15:33, 8216.64s/it]

[I 2026-02-21 03:42:38,882] Trial 158 finished with value: 0.8924097386768166 and parameters: {'layer1': 253, 'layer2': 437, 'layer3': 34, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.5403648694721007e-05}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:32:23<18:15:33, 8216.64s/it]

[I 2026-02-21 03:43:12,636] Trial 159 finished with value: 0.7602851357098421 and parameters: {'layer1': 207, 'layer2': 416, 'layer3': 11, 'activation': 'tanh', 'solver': 'sgd', 'lr': 1.5690977902077495e-05}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:33:10<18:15:33, 8216.64s/it]

[I 2026-02-21 03:43:59,754] Trial 160 finished with value: 0.8904780648483767 and parameters: {'layer1': 294, 'layer2': 474, 'layer3': 251, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.276769522718421e-05}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:34:06<18:15:33, 8216.64s/it]

[I 2026-02-21 03:44:55,228] Trial 161 finished with value: 0.892965044199584 and parameters: {'layer1': 228, 'layer2': 489, 'layer3': 51, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.8751932559674425e-05}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:34:47<18:15:33, 8216.64s/it]

[I 2026-02-21 03:45:36,724] Trial 162 finished with value: 0.8896354499511396 and parameters: {'layer1': 221, 'layer2': 482, 'layer3': 221, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.879533697463134e-05}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:35:30<18:15:33, 8216.64s/it]

[I 2026-02-21 03:46:19,651] Trial 163 finished with value: 0.8912302659575 and parameters: {'layer1': 240, 'layer2': 466, 'layer3': 43, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.04616368351048e-05}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:36:30<18:15:33, 8216.64s/it]

[I 2026-02-21 03:47:19,140] Trial 164 finished with value: 0.8914954783506553 and parameters: {'layer1': 184, 'layer2': 494, 'layer3': 64, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.3870645355059971e-05}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:37:08<18:15:33, 8216.64s/it]

[I 2026-02-21 03:47:57,403] Trial 165 finished with value: 0.8932202581499252 and parameters: {'layer1': 215, 'layer2': 457, 'layer3': 24, 'activation': 'tanh', 'solver': 'adam', 'lr': 3.60233455699067e-05}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:37:40<18:15:33, 8216.64s/it]

[I 2026-02-21 03:48:29,326] Trial 166 finished with value: 0.8906314849660534 and parameters: {'layer1': 205, 'layer2': 453, 'layer3': 25, 'activation': 'identity', 'solver': 'adam', 'lr': 3.578806253236557e-05}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:38:15<18:15:33, 8216.64s/it]

[I 2026-02-21 03:49:04,573] Trial 167 finished with value: 0.8932881829850491 and parameters: {'layer1': 274, 'layer2': 446, 'layer3': 17, 'activation': 'tanh', 'solver': 'adam', 'lr': 6.0321303254373165e-05}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:38:48<18:15:33, 8216.64s/it]

[I 2026-02-21 03:49:37,119] Trial 168 finished with value: 0.8922670308731785 and parameters: {'layer1': 274, 'layer2': 457, 'layer3': 18, 'activation': 'tanh', 'solver': 'adam', 'lr': 6.313130935404257e-05}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:39:25<18:15:33, 8216.64s/it]

[I 2026-02-21 03:50:13,851] Trial 169 finished with value: 0.8938081132458912 and parameters: {'layer1': 261, 'layer2': 440, 'layer3': 10, 'activation': 'tanh', 'solver': 'adam', 'lr': 5.2919321569021796e-05}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:40:00<18:15:33, 8216.64s/it]

[I 2026-02-21 03:50:49,323] Trial 170 finished with value: 0.8932311738884001 and parameters: {'layer1': 268, 'layer2': 444, 'layer3': 31, 'activation': 'tanh', 'solver': 'adam', 'lr': 5.528560693328713e-05}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:40:30<18:15:33, 8216.64s/it]

[I 2026-02-21 03:51:19,045] Trial 171 finished with value: 0.8922012194544344 and parameters: {'layer1': 264, 'layer2': 442, 'layer3': 27, 'activation': 'tanh', 'solver': 'adam', 'lr': 8.408176529812532e-05}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:41:02<18:15:33, 8216.64s/it]

[I 2026-02-21 03:51:51,531] Trial 172 finished with value: 0.8665608949060586 and parameters: {'layer1': 278, 'layer2': 435, 'layer3': 11, 'activation': 'tanh', 'solver': 'adam', 'lr': 5.6851412527341485e-05}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:41:39<18:15:33, 8216.64s/it]

[I 2026-02-21 03:52:28,450] Trial 173 finished with value: 0.8934118162055205 and parameters: {'layer1': 267, 'layer2': 445, 'layer3': 35, 'activation': 'tanh', 'solver': 'adam', 'lr': 4.36448921472061e-05}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:42:17<18:15:33, 8216.64s/it]

[I 2026-02-21 03:53:06,784] Trial 174 finished with value: 0.889866700256114 and parameters: {'layer1': 311, 'layer2': 448, 'layer3': 34, 'activation': 'tanh', 'solver': 'adam', 'lr': 4.388801247530444e-05}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:42:50<18:15:33, 8216.64s/it]

[I 2026-02-21 03:53:39,133] Trial 175 finished with value: 0.8908926347886494 and parameters: {'layer1': 262, 'layer2': 467, 'layer3': 27, 'activation': 'tanh', 'solver': 'adam', 'lr': 5.273099470621689e-05}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:43:21<18:15:33, 8216.64s/it]

[I 2026-02-21 03:54:10,041] Trial 176 finished with value: 0.8416462660119063 and parameters: {'layer1': 298, 'layer2': 427, 'layer3': 11, 'activation': 'tanh', 'solver': 'adam', 'lr': 7.170635389145307e-05}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:44:01<18:15:33, 8216.64s/it]

[I 2026-02-21 03:54:49,958] Trial 177 finished with value: 0.8918466872983343 and parameters: {'layer1': 283, 'layer2': 475, 'layer3': 37, 'activation': 'tanh', 'solver': 'adam', 'lr': 4.0814335100799044e-05}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:44:40<18:15:33, 8216.64s/it]

[I 2026-02-21 03:55:29,820] Trial 178 finished with value: 0.8919113883500713 and parameters: {'layer1': 269, 'layer2': 460, 'layer3': 21, 'activation': 'tanh', 'solver': 'adam', 'lr': 3.468389314604594e-05}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:45:13<18:15:33, 8216.64s/it]

[I 2026-02-21 03:56:02,263] Trial 179 finished with value: 0.8646785934355474 and parameters: {'layer1': 253, 'layer2': 440, 'layer3': 10, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.00010019144712290006}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:45:53<18:15:33, 8216.64s/it]

[I 2026-02-21 03:56:42,156] Trial 180 finished with value: 0.8930009013348214 and parameters: {'layer1': 356, 'layer2': 458, 'layer3': 50, 'activation': 'tanh', 'solver': 'adam', 'lr': 6.64788852290024e-05}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:46:27<18:15:33, 8216.64s/it]

[I 2026-02-21 03:57:15,990] Trial 181 finished with value: 0.8909884017032024 and parameters: {'layer1': 237, 'layer2': 445, 'layer3': 28, 'activation': 'tanh', 'solver': 'adam', 'lr': 4.7228655648408086e-05}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:47:07<18:15:33, 8216.64s/it]

[I 2026-02-21 03:57:56,653] Trial 182 finished with value: 0.894245302693025 and parameters: {'layer1': 265, 'layer2': 424, 'layer3': 20, 'activation': 'tanh', 'solver': 'adam', 'lr': 3.144414845095211e-05}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:47:48<18:15:33, 8216.64s/it]

[I 2026-02-21 03:58:37,455] Trial 183 finished with value: 0.8939380841548044 and parameters: {'layer1': 265, 'layer2': 424, 'layer3': 20, 'activation': 'tanh', 'solver': 'adam', 'lr': 3.114010993051122e-05}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:48:28<18:15:33, 8216.64s/it]

[I 2026-02-21 03:59:17,489] Trial 184 finished with value: 0.8924960467514509 and parameters: {'layer1': 279, 'layer2': 430, 'layer3': 38, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.932893097741941e-05}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:48:50<18:15:33, 8216.64s/it]

[I 2026-02-21 03:59:39,466] Trial 185 finished with value: 0.7575127299461911 and parameters: {'layer1': 268, 'layer2': 417, 'layer3': 20, 'activation': 'logistic', 'solver': 'adam', 'lr': 3.702170403802915e-05}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:49:30<18:15:33, 8216.64s/it]

[I 2026-02-21 04:00:18,858] Trial 186 finished with value: 0.8917847994490558 and parameters: {'layer1': 244, 'layer2': 449, 'layer3': 32, 'activation': 'tanh', 'solver': 'adam', 'lr': 4.22119440243789e-05}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:50:08<18:15:33, 8216.64s/it]

[I 2026-02-21 04:00:57,682] Trial 187 finished with value: 0.8913982518174965 and parameters: {'layer1': 288, 'layer2': 432, 'layer3': 19, 'activation': 'tanh', 'solver': 'adam', 'lr': 5.586363818202008e-05}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:50:39<18:15:33, 8216.64s/it]

[I 2026-02-21 04:01:28,677] Trial 188 finished with value: 0.8406733337617519 and parameters: {'layer1': 259, 'layer2': 420, 'layer3': 10, 'activation': 'tanh', 'solver': 'adam', 'lr': 5.00577463477823e-05}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:51:21<18:15:33, 8216.64s/it]

[I 2026-02-21 04:02:09,945] Trial 189 finished with value: 0.8917639865129006 and parameters: {'layer1': 252, 'layer2': 444, 'layer3': 46, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.8396432915650004e-05}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:51:39<18:15:33, 8216.64s/it]

[I 2026-02-21 04:02:27,928] Trial 190 finished with value: 0.758599109407373 and parameters: {'layer1': 233, 'layer2': 470, 'layer3': 37, 'activation': 'tanh', 'solver': 'sgd', 'lr': 3.930638730189253e-05}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:52:17<18:15:33, 8216.64s/it]

[I 2026-02-21 04:03:06,802] Trial 191 finished with value: 0.8930555267804312 and parameters: {'layer1': 267, 'layer2': 481, 'layer3': 25, 'activation': 'tanh', 'solver': 'adam', 'lr': 3.3420007077655385e-05}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:52:56<18:15:33, 8216.64s/it]

[I 2026-02-21 04:03:45,725] Trial 192 finished with value: 0.8917125475248857 and parameters: {'layer1': 258, 'layer2': 460, 'layer3': 22, 'activation': 'tanh', 'solver': 'adam', 'lr': 3.197584188417237e-05}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:53:18<18:15:33, 8216.64s/it]

[I 2026-02-21 04:04:07,383] Trial 193 finished with value: 0.7575127299461911 and parameters: {'layer1': 274, 'layer2': 453, 'layer3': 31, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0037741835420387875}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:53:48<18:15:33, 8216.64s/it]

[I 2026-02-21 04:04:37,791] Trial 194 finished with value: 0.8903639406797563 and parameters: {'layer1': 243, 'layer2': 471, 'layer3': 19, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0005673094695682072}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:54:31<18:15:33, 8216.64s/it]

[I 2026-02-21 04:05:20,589] Trial 195 finished with value: 0.8912519788210691 and parameters: {'layer1': 258, 'layer2': 439, 'layer3': 43, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.3907570751262922e-05}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:55:11<18:15:33, 8216.64s/it]

[I 2026-02-21 04:06:00,534] Trial 196 finished with value: 0.8641334893357392 and parameters: {'layer1': 280, 'layer2': 462, 'layer3': 10, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.8922038017150373e-05}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:55:43<18:15:33, 8216.64s/it]

[I 2026-02-21 04:06:32,399] Trial 197 finished with value: 0.8903024375547973 and parameters: {'layer1': 214, 'layer2': 478, 'layer3': 29, 'activation': 'tanh', 'solver': 'adam', 'lr': 4.47559982318064e-05}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  43%|████▎     | 6/14 [16:56:15<18:15:33, 8216.64s/it]

[I 2026-02-21 04:07:04,456] Trial 198 finished with value: 0.8932066037234483 and parameters: {'layer1': 250, 'layer2': 447, 'layer3': 19, 'activation': 'tanh', 'solver': 'adam', 'lr': 7.769561926537355e-05}. Best is trial 130 with value: 0.894816033001681.

Best trial: 130. Best value: 0.894816: 100%|██████████| 200/200 [2:23:03<00:00, 42.92s/it]

[I 2026-02-21 04:07:31,234] Trial 199 finished with value: 0.8910702305002728 and parameters: {'layer1': 123, 'layer2': 422, 'layer3': 59, 'activation': 'tanh', 'solver': 'adam', 'lr': 6.557584061625271e-05}. Best is trial 130 with value: 0.894816033001681.

Training Exact MLP (Paper):  50%|█████     | 7/14 [16:56:43<16:12:39, 8337.13s/it][I 2026-02-21 04:07:32,480] A new study created in memory with name: no-name-6d195c00-e7de-45ac-8c1a-b4803cd988b6

  → Best model saved.

[Exact Paper MLP] Klebsiella_Pneumoniae | Ciprofloxacin

Training Exact MLP (Paper):  50%|█████     | 7/14 [16:57:00<16:12:39, 8337.13s/it]

[I 2026-02-21 04:07:49,003] Trial 0 finished with value: 0.8401955655450607 and parameters: {'layer1': 214, 'layer2': 155, 'layer3': 267, 'activation': 'identity', 'solver': 'adam', 'lr': 0.00033932310089378214}. Best is trial 0 with value: 0.8401955655450607.

Training Exact MLP (Paper):  50%|█████     | 7/14 [16:57:10<16:12:39, 8337.13s/it]

[I 2026-02-21 04:07:59,504] Trial 1 finished with value: 0.7404498827712407 and parameters: {'layer1': 266, 'layer2': 244, 'layer3': 390, 'activation': 'tanh', 'solver': 'sgd', 'lr': 0.0023857006184823094}. Best is trial 0 with value: 0.8401955655450607.

Training Exact MLP (Paper):  50%|█████     | 7/14 [16:57:23<16:12:39, 8337.13s/it]

[I 2026-02-21 04:08:12,242] Trial 2 finished with value: 0.7464687037823833 and parameters: {'layer1': 422, 'layer2': 50, 'layer3': 241, 'activation': 'tanh', 'solver': 'sgd', 'lr': 0.0001848963555889917}. Best is trial 0 with value: 0.8401955655450607.

Training Exact MLP (Paper):  50%|█████     | 7/14 [16:58:01<16:12:39, 8337.13s/it]

[I 2026-02-21 04:08:49,994] Trial 3 finished with value: 0.8034152103746586 and parameters: {'layer1': 418, 'layer2': 334, 'layer3': 381, 'activation': 'identity', 'solver': 'adam', 'lr': 1.3086560846244915e-05}. Best is trial 0 with value: 0.8401955655450607.

Training Exact MLP (Paper):  50%|█████     | 7/14 [16:58:16<16:12:39, 8337.13s/it]

[I 2026-02-21 04:09:05,754] Trial 4 finished with value: 0.8382648750159346 and parameters: {'layer1': 59, 'layer2': 161, 'layer3': 79, 'activation': 'relu', 'solver': 'adam', 'lr': 0.005379131516103885}. Best is trial 0 with value: 0.8401955655450607.

Training Exact MLP (Paper):  50%|█████     | 7/14 [16:58:28<16:12:39, 8337.13s/it]

[I 2026-02-21 04:09:16,895] Trial 5 finished with value: 0.7410502226757251 and parameters: {'layer1': 97, 'layer2': 349, 'layer3': 378, 'activation': 'identity', 'solver': 'adam', 'lr': 1.0237823945705744e-06}. Best is trial 0 with value: 0.8401955655450607.

Training Exact MLP (Paper):  50%|█████     | 7/14 [16:58:39<16:12:39, 8337.13s/it]

[I 2026-02-21 04:09:28,024] Trial 6 finished with value: 0.7424598707907294 and parameters: {'layer1': 345, 'layer2': 30, 'layer3': 243, 'activation': 'tanh', 'solver': 'sgd', 'lr': 0.0002499786471682224}. Best is trial 0 with value: 0.8401955655450607.

Training Exact MLP (Paper):  50%|█████     | 7/14 [16:58:53<16:12:39, 8337.13s/it]

[I 2026-02-21 04:09:42,021] Trial 7 finished with value: 0.741050222675725 and parameters: {'layer1': 282, 'layer2': 250, 'layer3': 340, 'activation': 'tanh', 'solver': 'adam', 'lr': 3.643818112951413e-06}. Best is trial 0 with value: 0.8401955655450607.

Training Exact MLP (Paper):  50%|█████     | 7/14 [16:59:09<16:12:39, 8337.13s/it]

[I 2026-02-21 04:09:58,647] Trial 8 finished with value: 0.7482988830641144 and parameters: {'layer1': 193, 'layer2': 373, 'layer3': 465, 'activation': 'identity', 'solver': 'sgd', 'lr': 1.4703941931744694e-05}. Best is trial 0 with value: 0.8401955655450607.

Training Exact MLP (Paper):  50%|█████     | 7/14 [16:59:20<16:12:39, 8337.13s/it]

[I 2026-02-21 04:10:08,945] Trial 9 finished with value: 0.46604918578353105 and parameters: {'layer1': 282, 'layer2': 135, 'layer3': 249, 'activation': 'logistic', 'solver': 'sgd', 'lr': 1.5594481498694494e-06}. Best is trial 0 with value: 0.8401955655450607.

Training Exact MLP (Paper):  50%|█████     | 7/14 [16:59:40<16:12:39, 8337.13s/it]

[I 2026-02-21 04:10:29,069] Trial 10 finished with value: 0.8373206006072532 and parameters: {'layer1': 153, 'layer2': 461, 'layer3': 111, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0009087016044032551}. Best is trial 0 with value: 0.8401955655450607.

Training Exact MLP (Paper):  50%|█████     | 7/14 [16:59:52<16:12:39, 8337.13s/it]

[I 2026-02-21 04:10:41,695] Trial 11 finished with value: 0.8355182136567446 and parameters: {'layer1': 19, 'layer2': 131, 'layer3': 40, 'activation': 'relu', 'solver': 'adam', 'lr': 0.007952569731369935}. Best is trial 0 with value: 0.8401955655450607.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:00:08<16:12:39, 8337.13s/it]

[I 2026-02-21 04:10:57,072] Trial 12 finished with value: 0.8386088879921351 and parameters: {'layer1': 33, 'layer2': 143, 'layer3': 117, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0015511975400291588}. Best is trial 0 with value: 0.8401955655450607.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:00:33<16:12:39, 8337.13s/it]

[I 2026-02-21 04:11:22,425] Trial 13 finished with value: 0.8401782077453088 and parameters: {'layer1': 167, 'layer2': 193, 'layer3': 156, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0006529212067120485}. Best is trial 0 with value: 0.8401955655450607.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:00:45<16:12:39, 8337.13s/it]

[I 2026-02-21 04:11:34,025] Trial 14 finished with value: 0.7404498827712407 and parameters: {'layer1': 168, 'layer2': 199, 'layer3': 169, 'activation': 'logistic', 'solver': 'adam', 'lr': 5.366561738682958e-05}. Best is trial 0 with value: 0.8401955655450607.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:01:10<16:12:39, 8337.13s/it]

[I 2026-02-21 04:11:59,042] Trial 15 finished with value: 0.8197448256622233 and parameters: {'layer1': 205, 'layer2': 68, 'layer3': 172, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0004354549054518391}. Best is trial 0 with value: 0.8401955655450607.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:01:33<16:12:39, 8337.13s/it]

[I 2026-02-21 04:12:22,650] Trial 16 finished with value: 0.8409241643873878 and parameters: {'layer1': 96, 'layer2': 290, 'layer3': 313, 'activation': 'identity', 'solver': 'adam', 'lr': 5.5106066070501525e-05}. Best is trial 16 with value: 0.8409241643873878.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:01:53<16:12:39, 8337.13s/it]

[I 2026-02-21 04:12:42,007] Trial 17 finished with value: 0.8407110053566823 and parameters: {'layer1': 103, 'layer2': 300, 'layer3': 302, 'activation': 'identity', 'solver': 'adam', 'lr': 6.805209275482828e-05}. Best is trial 16 with value: 0.8409241643873878.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:02:15<16:12:39, 8337.13s/it]

[I 2026-02-21 04:13:04,279] Trial 18 finished with value: 0.8452793367811248 and parameters: {'layer1': 103, 'layer2': 310, 'layer3': 320, 'activation': 'identity', 'solver': 'adam', 'lr': 4.736590187384346e-05}. Best is trial 18 with value: 0.8452793367811248.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:02:40<16:12:39, 8337.13s/it]

[I 2026-02-21 04:13:28,982] Trial 19 finished with value: 0.8449788754453122 and parameters: {'layer1': 118, 'layer2': 469, 'layer3': 465, 'activation': 'identity', 'solver': 'adam', 'lr': 3.3481762357929274e-05}. Best is trial 18 with value: 0.8452793367811248.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:03:20<16:12:39, 8337.13s/it]

[I 2026-02-21 04:14:09,637] Trial 20 finished with value: 0.8451911725136245 and parameters: {'layer1': 343, 'layer2': 496, 'layer3': 497, 'activation': 'identity', 'solver': 'adam', 'lr': 1.758097398559503e-05}. Best is trial 18 with value: 0.8452793367811248.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:03:56<16:12:39, 8337.13s/it]

[I 2026-02-21 04:14:45,214] Trial 21 finished with value: 0.8441175101109561 and parameters: {'layer1': 373, 'layer2': 486, 'layer3': 499, 'activation': 'identity', 'solver': 'adam', 'lr': 2.244797951195843e-05}. Best is trial 18 with value: 0.8452793367811248.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:04:11<16:12:39, 8337.13s/it]

[I 2026-02-21 04:14:59,915] Trial 22 finished with value: 0.7404498827712407 and parameters: {'layer1': 335, 'layer2': 425, 'layer3': 448, 'activation': 'identity', 'solver': 'adam', 'lr': 5.517030256867438e-06}. Best is trial 18 with value: 0.8452793367811248.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:04:35<16:12:39, 8337.13s/it]

[I 2026-02-21 04:15:24,283] Trial 23 finished with value: 0.8436356147741947 and parameters: {'layer1': 132, 'layer2': 422, 'layer3': 431, 'activation': 'identity', 'solver': 'adam', 'lr': 2.6851951218745492e-05}. Best is trial 18 with value: 0.8452793367811248.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:04:58<16:12:39, 8337.13s/it]

[I 2026-02-21 04:15:47,256] Trial 24 finished with value: 0.847249570104921 and parameters: {'layer1': 243, 'layer2': 495, 'layer3': 481, 'activation': 'identity', 'solver': 'adam', 'lr': 0.00011023901252910842}. Best is trial 24 with value: 0.847249570104921.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:05:24<16:12:39, 8337.13s/it]

[I 2026-02-21 04:16:13,576] Trial 25 finished with value: 0.8416367318715835 and parameters: {'layer1': 461, 'layer2': 395, 'layer3': 496, 'activation': 'identity', 'solver': 'adam', 'lr': 9.891494107995392e-05}. Best is trial 24 with value: 0.847249570104921.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:05:52<16:12:39, 8337.13s/it]

[I 2026-02-21 04:16:41,187] Trial 26 finished with value: 0.6133337452261344 and parameters: {'layer1': 315, 'layer2': 496, 'layer3': 411, 'activation': 'identity', 'solver': 'sgd', 'lr': 6.953802307134993e-06}. Best is trial 24 with value: 0.847249570104921.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:06:11<16:12:39, 8337.13s/it]

[I 2026-02-21 04:17:00,788] Trial 27 finished with value: 0.8390744157605727 and parameters: {'layer1': 239, 'layer2': 437, 'layer3': 353, 'activation': 'identity', 'solver': 'adam', 'lr': 0.00013196502737377195}. Best is trial 24 with value: 0.847249570104921.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:06:33<16:12:39, 8337.13s/it]

[I 2026-02-21 04:17:22,375] Trial 28 finished with value: 0.7583297233008054 and parameters: {'layer1': 377, 'layer2': 391, 'layer3': 435, 'activation': 'identity', 'solver': 'adam', 'lr': 1.1400786029424953e-05}. Best is trial 24 with value: 0.847249570104921.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:06:47<16:12:39, 8337.13s/it]

[I 2026-02-21 04:17:35,894] Trial 29 finished with value: 0.7404498827712407 and parameters: {'layer1': 235, 'layer2': 452, 'layer3': 298, 'activation': 'identity', 'solver': 'adam', 'lr': 3.5056796923903913e-06}. Best is trial 24 with value: 0.847249570104921.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:07:05<16:12:39, 8337.13s/it]

[I 2026-02-21 04:17:54,595] Trial 30 finished with value: 0.8360888656802518 and parameters: {'layer1': 311, 'layer2': 321, 'layer3': 213, 'activation': 'identity', 'solver': 'adam', 'lr': 0.00033436856900474424}. Best is trial 24 with value: 0.847249570104921.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:07:30<16:12:39, 8337.13s/it]

[I 2026-02-21 04:18:18,944] Trial 31 finished with value: 0.8437956289032418 and parameters: {'layer1': 57, 'layer2': 474, 'layer3': 471, 'activation': 'identity', 'solver': 'adam', 'lr': 3.2595661979413054e-05}. Best is trial 24 with value: 0.847249570104921.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:07:51<16:12:39, 8337.13s/it]

[I 2026-02-21 04:18:40,106] Trial 32 finished with value: 0.841483974074022 and parameters: {'layer1': 128, 'layer2': 497, 'layer3': 410, 'activation': 'identity', 'solver': 'adam', 'lr': 4.5159094172845465e-05}. Best is trial 24 with value: 0.847249570104921.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:08:07<16:12:39, 8337.13s/it]

[I 2026-02-21 04:18:56,002] Trial 33 finished with value: 0.8442006002981417 and parameters: {'layer1': 68, 'layer2': 420, 'layer3': 471, 'activation': 'identity', 'solver': 'adam', 'lr': 0.00010697752505035426}. Best is trial 24 with value: 0.847249570104921.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:08:18<16:12:39, 8337.13s/it]

[I 2026-02-21 04:19:07,573] Trial 34 finished with value: 0.740583435973923 and parameters: {'layer1': 254, 'layer2': 457, 'layer3': 406, 'activation': 'tanh', 'solver': 'sgd', 'lr': 0.00016277682807423603}. Best is trial 24 with value: 0.847249570104921.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:09:01<16:12:39, 8337.13s/it]

[I 2026-02-21 04:19:50,553] Trial 35 finished with value: 0.8415674062196272 and parameters: {'layer1': 481, 'layer2': 373, 'layer3': 493, 'activation': 'identity', 'solver': 'adam', 'lr': 1.7684300255185927e-05}. Best is trial 24 with value: 0.847249570104921.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:09:17<16:12:39, 8337.13s/it]

[I 2026-02-21 04:20:06,778] Trial 36 finished with value: 0.7404498827712407 and parameters: {'layer1': 408, 'layer2': 500, 'layer3': 364, 'activation': 'identity', 'solver': 'adam', 'lr': 1.0348175102512942e-05}. Best is trial 24 with value: 0.847249570104921.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:09:33<16:12:39, 8337.13s/it]

[I 2026-02-21 04:20:22,203] Trial 37 finished with value: 0.7454217293015566 and parameters: {'layer1': 183, 'layer2': 401, 'layer3': 447, 'activation': 'tanh', 'solver': 'sgd', 'lr': 3.286778161944402e-05}. Best is trial 24 with value: 0.847249570104921.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:09:50<16:12:39, 8337.13s/it]

[I 2026-02-21 04:20:38,909] Trial 38 finished with value: 0.8428894218477503 and parameters: {'layer1': 76, 'layer2': 276, 'layer3': 329, 'activation': 'identity', 'solver': 'adam', 'lr': 7.35872160741494e-05}. Best is trial 24 with value: 0.847249570104921.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:10:09<16:12:39, 8337.13s/it]

[I 2026-02-21 04:20:58,193] Trial 39 finished with value: 0.8407535113340747 and parameters: {'layer1': 132, 'layer2': 349, 'layer3': 280, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0002383118057822645}. Best is trial 24 with value: 0.847249570104921.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:10:38<16:12:39, 8337.13s/it]

[I 2026-02-21 04:21:27,058] Trial 40 finished with value: 0.7425858314188544 and parameters: {'layer1': 223, 'layer2': 225, 'layer3': 385, 'activation': 'identity', 'solver': 'sgd', 'lr': 7.009126095749849e-06}. Best is trial 24 with value: 0.847249570104921.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:10:54<16:12:39, 8337.13s/it]

[I 2026-02-21 04:21:43,689] Trial 41 finished with value: 0.8415683164931238 and parameters: {'layer1': 46, 'layer2': 438, 'layer3': 471, 'activation': 'identity', 'solver': 'adam', 'lr': 0.00011066191329778803}. Best is trial 24 with value: 0.847249570104921.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:11:17<16:12:39, 8337.13s/it]

[I 2026-02-21 04:22:05,959] Trial 42 finished with value: 0.8420110160458749 and parameters: {'layer1': 81, 'layer2': 463, 'layer3': 470, 'activation': 'identity', 'solver': 'adam', 'lr': 3.875210612348602e-05}. Best is trial 24 with value: 0.847249570104921.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:11:33<16:12:39, 8337.13s/it]

[I 2026-02-21 04:22:21,879] Trial 43 finished with value: 0.840504877575183 and parameters: {'layer1': 106, 'layer2': 408, 'layer3': 453, 'activation': 'identity', 'solver': 'adam', 'lr': 8.767111050628088e-05}. Best is trial 24 with value: 0.847249570104921.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:11:47<16:12:39, 8337.13s/it]

[I 2026-02-21 04:22:36,386] Trial 44 finished with value: 0.8348931011257857 and parameters: {'layer1': 24, 'layer2': 476, 'layer3': 424, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.00018427507437576148}. Best is trial 24 with value: 0.847249570104921.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:12:23<16:12:39, 8337.13s/it]

[I 2026-02-21 04:23:12,002] Trial 45 finished with value: 0.8425908643891911 and parameters: {'layer1': 284, 'layer2': 359, 'layer3': 397, 'activation': 'identity', 'solver': 'adam', 'lr': 1.7882809734700385e-05}. Best is trial 24 with value: 0.847249570104921.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:12:41<16:12:39, 8337.13s/it]

[I 2026-02-21 04:23:30,541] Trial 46 finished with value: 0.8371243225797697 and parameters: {'layer1': 75, 'layer2': 322, 'layer3': 486, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.000447725817705859}. Best is trial 24 with value: 0.847249570104921.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:12:52<16:12:39, 8337.13s/it]

[I 2026-02-21 04:23:41,652] Trial 47 finished with value: 0.7404498827712407 and parameters: {'layer1': 122, 'layer2': 448, 'layer3': 378, 'activation': 'relu', 'solver': 'adam', 'lr': 2.280960174764198e-05}. Best is trial 24 with value: 0.847249570104921.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:13:05<16:12:39, 8337.13s/it]

[I 2026-02-21 04:23:53,963] Trial 48 finished with value: 0.7451059905441719 and parameters: {'layer1': 149, 'layer2': 479, 'layer3': 474, 'activation': 'identity', 'solver': 'adam', 'lr': 2.1459661327358796e-06}. Best is trial 24 with value: 0.847249570104921.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:13:16<16:12:39, 8337.13s/it]

[I 2026-02-21 04:24:05,144] Trial 49 finished with value: 0.7511272904696283 and parameters: {'layer1': 11, 'layer2': 414, 'layer3': 209, 'activation': 'identity', 'solver': 'sgd', 'lr': 5.76437445437978e-05}. Best is trial 24 with value: 0.847249570104921.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:13:36<16:12:39, 8337.13s/it]

[I 2026-02-21 04:24:25,122] Trial 50 finished with value: 0.8373772743436184 and parameters: {'layer1': 40, 'layer2': 377, 'layer3': 453, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0029891553801583504}. Best is trial 24 with value: 0.847249570104921.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:14:11<16:12:39, 8337.13s/it]

[I 2026-02-21 04:24:59,867] Trial 51 finished with value: 0.8458594830401438 and parameters: {'layer1': 368, 'layer2': 478, 'layer3': 498, 'activation': 'identity', 'solver': 'adam', 'lr': 2.689498132949929e-05}. Best is trial 24 with value: 0.847249570104921.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:15:05<16:12:39, 8337.13s/it]

[I 2026-02-21 04:25:54,538] Trial 52 finished with value: 0.8437199973768819 and parameters: {'layer1': 366, 'layer2': 461, 'layer3': 498, 'activation': 'identity', 'solver': 'adam', 'lr': 1.2204135188117777e-05}. Best is trial 24 with value: 0.847249570104921.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:15:35<16:12:39, 8337.13s/it]

[I 2026-02-21 04:26:24,125] Trial 53 finished with value: 0.8433409837496788 and parameters: {'layer1': 412, 'layer2': 430, 'layer3': 428, 'activation': 'identity', 'solver': 'adam', 'lr': 4.009337987917395e-05}. Best is trial 24 with value: 0.847249570104921.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:16:04<16:12:39, 8337.13s/it]

[I 2026-02-21 04:26:53,142] Trial 54 finished with value: 0.8420320763901428 and parameters: {'layer1': 433, 'layer2': 481, 'layer3': 457, 'activation': 'identity', 'solver': 'adam', 'lr': 8.431329133184922e-05}. Best is trial 24 with value: 0.847249570104921.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:16:41<16:12:39, 8337.13s/it]

[I 2026-02-21 04:27:30,251] Trial 55 finished with value: 0.8439298797184129 and parameters: {'layer1': 392, 'layer2': 112, 'layer3': 481, 'activation': 'identity', 'solver': 'adam', 'lr': 2.7334858444542667e-05}. Best is trial 24 with value: 0.847249570104921.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:17:10<16:12:39, 8337.13s/it]

[I 2026-02-21 04:27:59,706] Trial 56 finished with value: 0.8404401054891153 and parameters: {'layer1': 346, 'layer2': 439, 'layer3': 439, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00014215628239287937}. Best is trial 24 with value: 0.847249570104921.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:17:29<16:12:39, 8337.13s/it]

[I 2026-02-21 04:28:18,609] Trial 57 finished with value: 0.8399850529199752 and parameters: {'layer1': 300, 'layer2': 466, 'layer3': 476, 'activation': 'identity', 'solver': 'adam', 'lr': 0.00024309217502590895}. Best is trial 24 with value: 0.847249570104921.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:18:06<16:12:39, 8337.13s/it]

[I 2026-02-21 04:28:55,845] Trial 58 finished with value: 0.8430103947445804 and parameters: {'layer1': 344, 'layer2': 492, 'layer3': 500, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.8601677076916293e-05}. Best is trial 24 with value: 0.847249570104921.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:18:18<16:12:39, 8337.13s/it]

[I 2026-02-21 04:29:07,455] Trial 59 finished with value: 0.7404498827712407 and parameters: {'layer1': 193, 'layer2': 416, 'layer3': 424, 'activation': 'identity', 'solver': 'adam', 'lr': 7.94033080249533e-06}. Best is trial 24 with value: 0.847249570104921.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:19:21<16:12:39, 8337.13s/it]

[I 2026-02-21 04:30:10,574] Trial 60 finished with value: 0.7445380943955164 and parameters: {'layer1': 435, 'layer2': 263, 'layer3': 56, 'activation': 'identity', 'solver': 'sgd', 'lr': 4.389027232896193e-06}. Best is trial 24 with value: 0.847249570104921.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:19:53<16:12:39, 8337.13s/it]

[I 2026-02-21 04:30:41,958] Trial 61 finished with value: 0.8409907401295275 and parameters: {'layer1': 386, 'layer2': 486, 'layer3': 500, 'activation': 'identity', 'solver': 'adam', 'lr': 5.195452427503992e-05}. Best is trial 24 with value: 0.847249570104921.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:20:27<16:12:39, 8337.13s/it]

[I 2026-02-21 04:31:16,685] Trial 62 finished with value: 0.84164033218195 and parameters: {'layer1': 360, 'layer2': 454, 'layer3': 461, 'activation': 'identity', 'solver': 'adam', 'lr': 2.255372990007469e-05}. Best is trial 24 with value: 0.847249570104921.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:21:15<16:12:39, 8337.13s/it]

[I 2026-02-21 04:32:04,225] Trial 63 finished with value: 0.8404839112699605 and parameters: {'layer1': 327, 'layer2': 475, 'layer3': 481, 'activation': 'identity', 'solver': 'adam', 'lr': 1.4602345042763152e-05}. Best is trial 24 with value: 0.847249570104921.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:21:37<16:12:39, 8337.13s/it]

[I 2026-02-21 04:32:25,941] Trial 64 finished with value: 0.8421619441422896 and parameters: {'layer1': 255, 'layer2': 445, 'layer3': 441, 'activation': 'identity', 'solver': 'adam', 'lr': 7.015006685357607e-05}. Best is trial 24 with value: 0.847249570104921.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:21:49<16:12:39, 8337.13s/it]

[I 2026-02-21 04:32:38,811] Trial 65 finished with value: 0.7404498827712407 and parameters: {'layer1': 153, 'layer2': 498, 'layer3': 485, 'activation': 'logistic', 'solver': 'adam', 'lr': 3.12337726359395e-05}. Best is trial 24 with value: 0.847249570104921.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:22:17<16:12:39, 8337.13s/it]

[I 2026-02-21 04:33:06,658] Trial 66 finished with value: 0.8405616651778886 and parameters: {'layer1': 457, 'layer2': 424, 'layer3': 461, 'activation': 'identity', 'solver': 'adam', 'lr': 0.00011988224540495713}. Best is trial 24 with value: 0.847249570104921.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:22:42<16:12:39, 8337.13s/it]

[I 2026-02-21 04:33:30,858] Trial 67 finished with value: 0.842588635719409 and parameters: {'layer1': 86, 'layer2': 224, 'layer3': 122, 'activation': 'identity', 'solver': 'adam', 'lr': 4.820998229131152e-05}. Best is trial 24 with value: 0.847249570104921.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:23:15<16:12:39, 8337.13s/it]

[I 2026-02-21 04:34:04,230] Trial 68 finished with value: 0.8445316546082632 and parameters: {'layer1': 274, 'layer2': 385, 'layer3': 358, 'activation': 'identity', 'solver': 'adam', 'lr': 2.2098371135454137e-05}. Best is trial 24 with value: 0.847249570104921.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:23:29<16:12:39, 8337.13s/it]

[I 2026-02-21 04:34:18,690] Trial 69 finished with value: 0.7404498827712407 and parameters: {'layer1': 294, 'layer2': 385, 'layer3': 335, 'activation': 'identity', 'solver': 'adam', 'lr': 9.422459941674e-06}. Best is trial 24 with value: 0.847249570104921.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:23:57<16:12:39, 8337.13s/it]

[I 2026-02-21 04:34:46,818] Trial 70 finished with value: 0.839352029090168 and parameters: {'layer1': 270, 'layer2': 333, 'layer3': 354, 'activation': 'relu', 'solver': 'adam', 'lr': 6.070198931690858e-05}. Best is trial 24 with value: 0.847249570104921.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:24:34<16:12:39, 8337.13s/it]

[I 2026-02-21 04:35:23,676] Trial 71 finished with value: 0.8438881066682612 and parameters: {'layer1': 321, 'layer2': 469, 'layer3': 268, 'activation': 'identity', 'solver': 'adam', 'lr': 2.6173981177628374e-05}. Best is trial 24 with value: 0.847249570104921.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:25:17<16:12:39, 8337.13s/it]

[I 2026-02-21 04:36:06,654] Trial 72 finished with value: 0.841786452224561 and parameters: {'layer1': 354, 'layer2': 484, 'layer3': 406, 'activation': 'identity', 'solver': 'adam', 'lr': 2.0045479221174562e-05}. Best is trial 24 with value: 0.847249570104921.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:25:41<16:12:39, 8337.13s/it]

[I 2026-02-21 04:36:29,865] Trial 73 finished with value: 0.7585256775039146 and parameters: {'layer1': 395, 'layer2': 294, 'layer3': 230, 'activation': 'identity', 'solver': 'adam', 'lr': 1.2858226181662857e-05}. Best is trial 24 with value: 0.847249570104921.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:26:17<16:12:39, 8337.13s/it]

[I 2026-02-21 04:37:06,336] Trial 74 finished with value: 0.8235717443374456 and parameters: {'layer1': 211, 'layer2': 401, 'layer3': 300, 'activation': 'identity', 'solver': 'adam', 'lr': 1.6435857516485203e-05}. Best is trial 24 with value: 0.847249570104921.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:26:45<16:12:39, 8337.13s/it]

[I 2026-02-21 04:37:34,257] Trial 75 finished with value: 0.8419135897770923 and parameters: {'layer1': 58, 'layer2': 450, 'layer3': 317, 'activation': 'identity', 'solver': 'adam', 'lr': 3.7695382549253096e-05}. Best is trial 24 with value: 0.847249570104921.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:27:03<16:12:39, 8337.13s/it]

[I 2026-02-21 04:37:52,721] Trial 76 finished with value: 0.8397937825757962 and parameters: {'layer1': 107, 'layer2': 431, 'layer3': 489, 'activation': 'tanh', 'solver': 'adam', 'lr': 8.613653789743788e-05}. Best is trial 24 with value: 0.847249570104921.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:27:22<16:12:39, 8337.13s/it]

[I 2026-02-21 04:38:11,139] Trial 77 finished with value: 0.7412831624638632 and parameters: {'layer1': 378, 'layer2': 313, 'layer3': 415, 'activation': 'identity', 'solver': 'sgd', 'lr': 4.167588183561362e-05}. Best is trial 24 with value: 0.847249570104921.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:27:56<16:12:39, 8337.13s/it]

[I 2026-02-21 04:38:45,050] Trial 78 finished with value: 0.8450772996705161 and parameters: {'layer1': 304, 'layer2': 500, 'layer3': 361, 'activation': 'identity', 'solver': 'adam', 'lr': 2.897300404663017e-05}. Best is trial 24 with value: 0.847249570104921.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:28:18<16:12:39, 8337.13s/it]

[I 2026-02-21 04:39:07,379] Trial 79 finished with value: 0.8409793431056787 and parameters: {'layer1': 308, 'layer2': 355, 'layer3': 370, 'activation': 'identity', 'solver': 'adam', 'lr': 0.00011037729345333684}. Best is trial 24 with value: 0.847249570104921.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:28:55<16:12:39, 8337.13s/it]

[I 2026-02-21 04:39:44,390] Trial 80 finished with value: 0.8445177733931015 and parameters: {'layer1': 271, 'layer2': 498, 'layer3': 283, 'activation': 'identity', 'solver': 'adam', 'lr': 2.8569516115417907e-05}. Best is trial 24 with value: 0.847249570104921.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:29:26<16:12:39, 8337.13s/it]

[I 2026-02-21 04:40:14,966] Trial 81 finished with value: 0.8443473716980886 and parameters: {'layer1': 266, 'layer2': 496, 'layer3': 286, 'activation': 'identity', 'solver': 'adam', 'lr': 2.8120036118655997e-05}. Best is trial 24 with value: 0.847249570104921.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:29:59<16:12:39, 8337.13s/it]

[I 2026-02-21 04:40:48,769] Trial 82 finished with value: 0.8480129925505899 and parameters: {'layer1': 271, 'layer2': 499, 'layer3': 286, 'activation': 'identity', 'solver': 'adam', 'lr': 3.104690275607411e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:30:25<16:12:39, 8337.13s/it]

[I 2026-02-21 04:41:14,767] Trial 83 finished with value: 0.8426139937220875 and parameters: {'layer1': 240, 'layer2': 500, 'layer3': 258, 'activation': 'identity', 'solver': 'adam', 'lr': 3.24804913820088e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:31:05<16:12:39, 8337.13s/it]

[I 2026-02-21 04:41:54,090] Trial 84 finished with value: 0.8255025468920245 and parameters: {'layer1': 284, 'layer2': 467, 'layer3': 319, 'activation': 'identity', 'solver': 'adam', 'lr': 1.5005300008648381e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:31:20<16:12:39, 8337.13s/it]

[I 2026-02-21 04:42:09,817] Trial 85 finished with value: 0.7404498827712407 and parameters: {'layer1': 226, 'layer2': 484, 'layer3': 347, 'activation': 'logistic', 'solver': 'adam', 'lr': 8.878111825135937e-06}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:31:53<16:12:39, 8337.13s/it]

[I 2026-02-21 04:42:42,209] Trial 86 finished with value: 0.843040908890927 and parameters: {'layer1': 252, 'layer2': 473, 'layer3': 280, 'activation': 'identity', 'solver': 'adam', 'lr': 2.3668013020199205e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:32:19<16:12:39, 8337.13s/it]

[I 2026-02-21 04:43:08,723] Trial 87 finished with value: 0.8424306194803389 and parameters: {'layer1': 332, 'layer2': 461, 'layer3': 327, 'activation': 'identity', 'solver': 'adam', 'lr': 4.7861534580405524e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:32:41<16:12:39, 8337.13s/it]

[I 2026-02-21 04:43:29,923] Trial 88 finished with value: 0.8434389635490479 and parameters: {'layer1': 270, 'layer2': 489, 'layer3': 305, 'activation': 'identity', 'solver': 'adam', 'lr': 7.253026194351606e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:33:12<16:12:39, 8337.13s/it]

[I 2026-02-21 04:44:01,039] Trial 89 finished with value: 0.8426809326011785 and parameters: {'layer1': 294, 'layer2': 446, 'layer3': 227, 'activation': 'identity', 'solver': 'adam', 'lr': 3.4557161617448884e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:33:29<16:12:39, 8337.13s/it]

[I 2026-02-21 04:44:18,642] Trial 90 finished with value: 0.7446429430426806 and parameters: {'layer1': 315, 'layer2': 500, 'layer3': 266, 'activation': 'relu', 'solver': 'sgd', 'lr': 5.6715633181260734e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:34:02<16:12:39, 8337.13s/it]

[I 2026-02-21 04:44:51,338] Trial 91 finished with value: 0.8406811346905719 and parameters: {'layer1': 262, 'layer2': 488, 'layer3': 246, 'activation': 'identity', 'solver': 'adam', 'lr': 2.8859180207795903e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:34:41<16:12:39, 8337.13s/it]

[I 2026-02-21 04:45:30,625] Trial 92 finished with value: 0.841584310915706 and parameters: {'layer1': 275, 'layer2': 473, 'layer3': 289, 'activation': 'identity', 'solver': 'adam', 'lr': 1.9631002336884106e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:35:07<16:12:39, 8337.13s/it]

[I 2026-02-21 04:45:56,826] Trial 93 finished with value: 0.8432238086929779 and parameters: {'layer1': 244, 'layer2': 458, 'layer3': 282, 'activation': 'identity', 'solver': 'adam', 'lr': 4.09607623130832e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:35:22<16:12:39, 8337.13s/it]

[I 2026-02-21 04:46:11,520] Trial 94 finished with value: 0.7404498827712407 and parameters: {'layer1': 303, 'layer2': 489, 'layer3': 309, 'activation': 'identity', 'solver': 'adam', 'lr': 1.1766673176025057e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:35:54<16:12:39, 8337.13s/it]

[I 2026-02-21 04:46:42,943] Trial 95 finished with value: 0.8451222097077787 and parameters: {'layer1': 223, 'layer2': 477, 'layer3': 361, 'activation': 'identity', 'solver': 'adam', 'lr': 2.3552087401804145e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:36:23<16:12:39, 8337.13s/it]

[I 2026-02-21 04:47:11,974] Trial 96 finished with value: 0.8437830042667823 and parameters: {'layer1': 170, 'layer2': 170, 'layer3': 396, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.23240440884084e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:36:44<16:12:39, 8337.13s/it]

[I 2026-02-21 04:47:33,315] Trial 97 finished with value: 0.7804779501046953 and parameters: {'layer1': 198, 'layer2': 478, 'layer3': 365, 'activation': 'identity', 'solver': 'adam', 'lr': 1.488571810577975e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:36:57<16:12:39, 8337.13s/it]

[I 2026-02-21 04:47:46,592] Trial 98 finished with value: 0.7404498827712407 and parameters: {'layer1': 231, 'layer2': 436, 'layer3': 354, 'activation': 'identity', 'solver': 'adam', 'lr': 6.466624146603388e-06}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:37:37<16:12:39, 8337.13s/it]

[I 2026-02-21 04:48:26,492] Trial 99 finished with value: 0.8431655163219179 and parameters: {'layer1': 283, 'layer2': 464, 'layer3': 340, 'activation': 'identity', 'solver': 'adam', 'lr': 1.787589473183259e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:38:02<16:12:39, 8337.13s/it]

[I 2026-02-21 04:48:51,650] Trial 100 finished with value: 0.8421651200693832 and parameters: {'layer1': 340, 'layer2': 450, 'layer3': 389, 'activation': 'identity', 'solver': 'adam', 'lr': 6.234932294219539e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:38:30<16:12:39, 8337.13s/it]

[I 2026-02-21 04:49:19,497] Trial 101 finished with value: 0.8443709929289183 and parameters: {'layer1': 214, 'layer2': 500, 'layer3': 327, 'activation': 'identity', 'solver': 'adam', 'lr': 2.7850190145893875e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:38:59<16:12:39, 8337.13s/it]

[I 2026-02-21 04:49:48,268] Trial 102 finished with value: 0.843723454924165 and parameters: {'layer1': 180, 'layer2': 475, 'layer3': 334, 'activation': 'identity', 'solver': 'adam', 'lr': 2.657454562029052e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:39:28<16:12:39, 8337.13s/it]

[I 2026-02-21 04:50:17,142] Trial 103 finished with value: 0.8443884131451795 and parameters: {'layer1': 216, 'layer2': 485, 'layer3': 376, 'activation': 'identity', 'solver': 'adam', 'lr': 3.3264039472430626e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:39:51<16:12:39, 8337.13s/it]

[I 2026-02-21 04:50:40,688] Trial 104 finished with value: 0.8414550146555175 and parameters: {'layer1': 220, 'layer2': 488, 'layer3': 379, 'activation': 'identity', 'solver': 'adam', 'lr': 4.687601828093919e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:40:28<16:12:39, 8337.13s/it]

[I 2026-02-21 04:51:17,245] Trial 105 finished with value: 0.8403682176051005 and parameters: {'layer1': 253, 'layer2': 275, 'layer3': 344, 'activation': 'identity', 'solver': 'adam', 'lr': 2.1391133985588167e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:40:44<16:12:39, 8337.13s/it]

[I 2026-02-21 04:51:33,090] Trial 106 finished with value: 0.7404498827712407 and parameters: {'layer1': 295, 'layer2': 465, 'layer3': 367, 'activation': 'logistic', 'solver': 'adam', 'lr': 3.3472370786344364e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:41:13<16:12:39, 8337.13s/it]

[I 2026-02-21 04:52:02,792] Trial 107 finished with value: 0.7465527964038415 and parameters: {'layer1': 240, 'layer2': 365, 'layer3': 320, 'activation': 'identity', 'solver': 'sgd', 'lr': 1.044560362230089e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:41:47<16:12:39, 8337.13s/it]

[I 2026-02-21 04:52:35,888] Trial 108 finished with value: 0.8404282352008934 and parameters: {'layer1': 353, 'layer2': 16, 'layer3': 293, 'activation': 'identity', 'solver': 'adam', 'lr': 3.8477533832246594e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:42:07<16:12:39, 8337.13s/it]

[I 2026-02-21 04:52:56,504] Trial 109 finished with value: 0.8374439888572173 and parameters: {'layer1': 278, 'layer2': 481, 'layer3': 447, 'activation': 'identity', 'solver': 'adam', 'lr': 0.00014706652663475567}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:42:32<16:12:39, 8337.13s/it]

[I 2026-02-21 04:53:21,176] Trial 110 finished with value: 0.8396390158560237 and parameters: {'layer1': 140, 'layer2': 455, 'layer3': 356, 'activation': 'relu', 'solver': 'adam', 'lr': 8.835315425567061e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:43:00<16:12:39, 8337.13s/it]

[I 2026-02-21 04:53:49,817] Trial 111 finished with value: 0.8425708597622366 and parameters: {'layer1': 216, 'layer2': 490, 'layer3': 324, 'activation': 'identity', 'solver': 'adam', 'lr': 2.6896328957085887e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:43:32<16:12:39, 8337.13s/it]

[I 2026-02-21 04:54:21,008] Trial 112 finished with value: 0.8046185689371533 and parameters: {'layer1': 207, 'layer2': 499, 'layer3': 375, 'activation': 'identity', 'solver': 'adam', 'lr': 1.4111579096286497e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:44:07<16:12:39, 8337.13s/it]

[I 2026-02-21 04:54:56,084] Trial 113 finished with value: 0.84354578924167 and parameters: {'layer1': 184, 'layer2': 479, 'layer3': 467, 'activation': 'identity', 'solver': 'adam', 'lr': 1.6684735608755974e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:44:35<16:12:39, 8337.13s/it]

[I 2026-02-21 04:55:24,617] Trial 114 finished with value: 0.8436378551952404 and parameters: {'layer1': 114, 'layer2': 441, 'layer3': 487, 'activation': 'identity', 'solver': 'adam', 'lr': 2.345752071293584e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:45:05<16:12:39, 8337.13s/it]

[I 2026-02-21 04:55:54,412] Trial 115 finished with value: 0.8426896503654383 and parameters: {'layer1': 259, 'layer2': 492, 'layer3': 307, 'activation': 'identity', 'solver': 'adam', 'lr': 3.2423054012207526e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:45:30<16:12:39, 8337.13s/it]

[I 2026-02-21 04:56:19,177] Trial 116 finished with value: 0.8416634178715106 and parameters: {'layer1': 247, 'layer2': 342, 'layer3': 272, 'activation': 'identity', 'solver': 'adam', 'lr': 4.735832467859498e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:46:08<16:12:39, 8337.13s/it]

[I 2026-02-21 04:56:57,037] Trial 117 finished with value: 0.8422167916500524 and parameters: {'layer1': 230, 'layer2': 467, 'layer3': 334, 'activation': 'identity', 'solver': 'adam', 'lr': 2.028359103413147e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:46:31<16:12:39, 8337.13s/it]

[I 2026-02-21 04:57:20,180] Trial 118 finished with value: 0.834292609581358 and parameters: {'layer1': 326, 'layer2': 242, 'layer3': 361, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.000197759608500729}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:47:01<16:12:39, 8337.13s/it]

[I 2026-02-21 04:57:50,734] Trial 119 finished with value: 0.8436437821281993 and parameters: {'layer1': 313, 'layer2': 481, 'layer3': 295, 'activation': 'identity', 'solver': 'adam', 'lr': 3.810645262355655e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:47:27<16:12:39, 8337.13s/it]

[I 2026-02-21 04:58:16,660] Trial 120 finished with value: 0.8440642355435829 and parameters: {'layer1': 199, 'layer2': 456, 'layer3': 313, 'activation': 'identity', 'solver': 'adam', 'lr': 5.6371043029931716e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:48:02<16:12:39, 8337.13s/it]

[I 2026-02-21 04:58:51,592] Trial 121 finished with value: 0.8439762973496302 and parameters: {'layer1': 265, 'layer2': 495, 'layer3': 10, 'activation': 'identity', 'solver': 'adam', 'lr': 2.8326103129560074e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:48:39<16:12:39, 8337.13s/it]

[I 2026-02-21 04:59:28,408] Trial 122 finished with value: 0.8421821362391041 and parameters: {'layer1': 289, 'layer2': 499, 'layer3': 260, 'activation': 'identity', 'solver': 'adam', 'lr': 2.969039539360798e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:49:11<16:12:39, 8337.13s/it]

[I 2026-02-21 05:00:00,491] Trial 123 finished with value: 0.8458238689541338 and parameters: {'layer1': 271, 'layer2': 500, 'layer3': 283, 'activation': 'identity', 'solver': 'adam', 'lr': 2.5783342574209028e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:49:41<16:12:39, 8337.13s/it]

[I 2026-02-21 05:00:30,636] Trial 124 finished with value: 0.7992375587726037 and parameters: {'layer1': 273, 'layer2': 473, 'layer3': 478, 'activation': 'identity', 'solver': 'adam', 'lr': 1.2654440045416407e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:50:18<16:12:39, 8337.13s/it]

[I 2026-02-21 05:01:07,075] Trial 125 finished with value: 0.844450796990618 and parameters: {'layer1': 369, 'layer2': 487, 'layer3': 345, 'activation': 'identity', 'solver': 'adam', 'lr': 2.4227816554726928e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:50:58<16:12:39, 8337.13s/it]

[I 2026-02-21 05:01:46,992] Trial 126 finished with value: 0.8440615706476879 and parameters: {'layer1': 370, 'layer2': 483, 'layer3': 385, 'activation': 'identity', 'solver': 'adam', 'lr': 1.7449653411798337e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:51:15<16:12:39, 8337.13s/it]

[I 2026-02-21 05:02:04,284] Trial 127 finished with value: 0.747617027333151 and parameters: {'layer1': 87, 'layer2': 468, 'layer3': 348, 'activation': 'identity', 'solver': 'sgd', 'lr': 2.4014243956630505e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:51:33<16:12:39, 8337.13s/it]

[I 2026-02-21 05:02:22,548] Trial 128 finished with value: 0.7404498827712407 and parameters: {'layer1': 388, 'layer2': 485, 'layer3': 277, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.00775843908294859}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:51:59<16:12:39, 8337.13s/it]

[I 2026-02-21 05:02:48,337] Trial 129 finished with value: 0.8417433358089074 and parameters: {'layer1': 334, 'layer2': 460, 'layer3': 493, 'activation': 'identity', 'solver': 'adam', 'lr': 4.4067616021323806e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:52:24<16:12:39, 8337.13s/it]

[I 2026-02-21 05:03:13,258] Trial 130 finished with value: 0.8418920704955474 and parameters: {'layer1': 360, 'layer2': 411, 'layer3': 238, 'activation': 'identity', 'solver': 'adam', 'lr': 7.107457326425393e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:52:51<16:12:39, 8337.13s/it]

[I 2026-02-21 05:03:40,581] Trial 131 finished with value: 0.8416586305241699 and parameters: {'layer1': 235, 'layer2': 500, 'layer3': 340, 'activation': 'identity', 'solver': 'adam', 'lr': 3.474371951064668e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:53:31<16:12:39, 8337.13s/it]

[I 2026-02-21 05:04:20,604] Trial 132 finished with value: 0.8421811317506643 and parameters: {'layer1': 399, 'layer2': 490, 'layer3': 323, 'activation': 'identity', 'solver': 'adam', 'lr': 2.0741131436117304e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:53:46<16:12:39, 8337.13s/it]

[I 2026-02-21 05:04:34,915] Trial 133 finished with value: 0.7598896992486115 and parameters: {'layer1': 96, 'layer2': 474, 'layer3': 402, 'activation': 'identity', 'solver': 'adam', 'lr': 1.6572119373090717e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:54:24<16:12:39, 8337.13s/it]

[I 2026-02-21 05:05:13,767] Trial 134 finished with value: 0.8424164255971508 and parameters: {'layer1': 376, 'layer2': 98, 'layer3': 301, 'activation': 'identity', 'solver': 'adam', 'lr': 2.692244626224387e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:54:45<16:12:39, 8337.13s/it]

[I 2026-02-21 05:05:34,394] Trial 135 finished with value: 0.8396961040353755 and parameters: {'layer1': 247, 'layer2': 489, 'layer3': 358, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0010058233009588014}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:55:16<16:12:39, 8337.13s/it]

[I 2026-02-21 05:06:05,811] Trial 136 finished with value: 0.845319818973746 and parameters: {'layer1': 218, 'layer2': 475, 'layer3': 330, 'activation': 'identity', 'solver': 'adam', 'lr': 3.4525923095820714e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:55:48<16:12:39, 8337.13s/it]

[I 2026-02-21 05:06:37,679] Trial 137 finished with value: 0.845430647522849 and parameters: {'layer1': 304, 'layer2': 445, 'layer3': 312, 'activation': 'identity', 'solver': 'adam', 'lr': 5.293407681666675e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:56:25<16:12:39, 8337.13s/it]

[I 2026-02-21 05:07:14,101] Trial 138 finished with value: 0.8417965199091999 and parameters: {'layer1': 305, 'layer2': 443, 'layer3': 313, 'activation': 'relu', 'solver': 'adam', 'lr': 6.440552545950996e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:56:55<16:12:39, 8337.13s/it]

[I 2026-02-21 05:07:44,254] Trial 139 finished with value: 0.8435851825109969 and parameters: {'layer1': 319, 'layer2': 309, 'layer3': 287, 'activation': 'identity', 'solver': 'adam', 'lr': 5.178674388270872e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:57:22<16:12:39, 8337.13s/it]

[I 2026-02-21 05:08:11,168] Trial 140 finished with value: 0.8417998665923807 and parameters: {'layer1': 283, 'layer2': 452, 'layer3': 251, 'activation': 'identity', 'solver': 'adam', 'lr': 4.153801624038735e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:57:52<16:12:39, 8337.13s/it]

[I 2026-02-21 05:08:41,113] Trial 141 finished with value: 0.8469675785516341 and parameters: {'layer1': 258, 'layer2': 473, 'layer3': 349, 'activation': 'identity', 'solver': 'adam', 'lr': 3.6869382138894776e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:58:23<16:12:39, 8337.13s/it]

[I 2026-02-21 05:09:12,738] Trial 142 finished with value: 0.8430704499864866 and parameters: {'layer1': 260, 'layer2': 430, 'layer3': 344, 'activation': 'identity', 'solver': 'adam', 'lr': 3.7298240580392557e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:58:49<16:12:39, 8337.13s/it]

[I 2026-02-21 05:09:38,064] Trial 143 finished with value: 0.839699804506108 and parameters: {'layer1': 295, 'layer2': 471, 'layer3': 308, 'activation': 'identity', 'solver': 'adam', 'lr': 9.613378529973595e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:59:25<16:12:39, 8337.13s/it]

[I 2026-02-21 05:10:14,216] Trial 144 finished with value: 0.8410034090282694 and parameters: {'layer1': 352, 'layer2': 478, 'layer3': 296, 'activation': 'identity', 'solver': 'adam', 'lr': 2.347606840771044e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [17:59:49<16:12:39, 8337.13s/it]

[I 2026-02-21 05:10:38,493] Trial 145 finished with value: 0.8399291855204403 and parameters: {'layer1': 275, 'layer2': 461, 'layer3': 335, 'activation': 'identity', 'solver': 'adam', 'lr': 5.2849346622017826e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [18:00:26<16:12:39, 8337.13s/it]

[I 2026-02-21 05:11:15,495] Trial 146 finished with value: 0.844003158424808 and parameters: {'layer1': 266, 'layer2': 468, 'layer3': 184, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.9203625861574228e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [18:00:55<16:12:39, 8337.13s/it]

[I 2026-02-21 05:11:44,629] Trial 147 finished with value: 0.8419106673192347 and parameters: {'layer1': 253, 'layer2': 480, 'layer3': 465, 'activation': 'identity', 'solver': 'adam', 'lr': 4.314638811491851e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [18:01:17<16:12:39, 8337.13s/it]

[I 2026-02-21 05:12:06,506] Trial 148 finished with value: 0.842655062754786 and parameters: {'layer1': 303, 'layer2': 391, 'layer3': 500, 'activation': 'identity', 'solver': 'adam', 'lr': 7.667973284523036e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [18:01:44<16:12:39, 8337.13s/it]

[I 2026-02-21 05:12:33,529] Trial 149 finished with value: 0.8447197549480314 and parameters: {'layer1': 116, 'layer2': 449, 'layer3': 269, 'activation': 'identity', 'solver': 'adam', 'lr': 3.2604118190488316e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [18:01:58<16:12:39, 8337.13s/it]

[I 2026-02-21 05:12:47,220] Trial 150 finished with value: 0.7434946536882665 and parameters: {'layer1': 146, 'layer2': 440, 'layer3': 275, 'activation': 'identity', 'solver': 'sgd', 'lr': 3.12926018116474e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [18:02:36<16:12:39, 8337.13s/it]

[I 2026-02-21 05:13:25,146] Trial 151 finished with value: 0.8418121803102709 and parameters: {'layer1': 288, 'layer2': 453, 'layer3': 258, 'activation': 'identity', 'solver': 'adam', 'lr': 2.4391760281366906e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [18:03:04<16:12:39, 8337.13s/it]

[I 2026-02-21 05:13:52,864] Trial 152 finished with value: 0.8444156772877524 and parameters: {'layer1': 110, 'layer2': 491, 'layer3': 291, 'activation': 'identity', 'solver': 'adam', 'lr': 3.329650981863679e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [18:03:46<16:12:39, 8337.13s/it]

[I 2026-02-21 05:14:35,394] Trial 153 finished with value: 0.846206161904022 and parameters: {'layer1': 344, 'layer2': 475, 'layer3': 486, 'activation': 'identity', 'solver': 'adam', 'lr': 2.0241493420060105e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [18:04:03<16:12:39, 8337.13s/it]

[I 2026-02-21 05:14:52,020] Trial 154 finished with value: 0.7586150786083412 and parameters: {'layer1': 117, 'layer2': 465, 'layer3': 481, 'activation': 'identity', 'solver': 'adam', 'lr': 1.4124784752992856e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [18:04:33<16:12:39, 8337.13s/it]

[I 2026-02-21 05:15:22,250] Trial 155 finished with value: 0.8429545062137361 and parameters: {'layer1': 132, 'layer2': 430, 'layer3': 474, 'activation': 'identity', 'solver': 'adam', 'lr': 2.0071481206591035e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [18:05:00<16:12:39, 8337.13s/it]

[I 2026-02-21 05:15:49,678] Trial 156 finished with value: 0.8446245644259891 and parameters: {'layer1': 101, 'layer2': 418, 'layer3': 493, 'activation': 'identity', 'solver': 'adam', 'lr': 3.8555520021598895e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [18:05:22<16:12:39, 8337.13s/it]

[I 2026-02-21 05:16:10,991] Trial 157 finished with value: 0.8428866597039744 and parameters: {'layer1': 101, 'layer2': 420, 'layer3': 486, 'activation': 'identity', 'solver': 'adam', 'lr': 4.042293092156381e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [18:05:33<16:12:39, 8337.13s/it]

[I 2026-02-21 05:16:22,261] Trial 158 finished with value: 0.7404498827712407 and parameters: {'layer1': 124, 'layer2': 400, 'layer3': 456, 'activation': 'logistic', 'solver': 'adam', 'lr': 5.039853814002718e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [18:05:52<16:12:39, 8337.13s/it]

[I 2026-02-21 05:16:41,355] Trial 159 finished with value: 0.8463072247018569 and parameters: {'layer1': 81, 'layer2': 444, 'layer3': 467, 'activation': 'identity', 'solver': 'adam', 'lr': 6.033454958882626e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [18:06:12<16:12:39, 8337.13s/it]

[I 2026-02-21 05:17:01,750] Trial 160 finished with value: 0.8463569434783021 and parameters: {'layer1': 49, 'layer2': 446, 'layer3': 491, 'activation': 'identity', 'solver': 'adam', 'lr': 6.144193441519848e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [18:06:35<16:12:39, 8337.13s/it]

[I 2026-02-21 05:17:24,315] Trial 161 finished with value: 0.8420359411559302 and parameters: {'layer1': 63, 'layer2': 442, 'layer3': 492, 'activation': 'identity', 'solver': 'adam', 'lr': 6.588105531343362e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [18:06:53<16:12:39, 8337.13s/it]

[I 2026-02-21 05:17:42,684] Trial 162 finished with value: 0.8430870646145913 and parameters: {'layer1': 45, 'layer2': 448, 'layer3': 471, 'activation': 'identity', 'solver': 'adam', 'lr': 5.668869934317187e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [18:07:10<16:12:39, 8337.13s/it]

[I 2026-02-21 05:17:58,883] Trial 163 finished with value: 0.8422376081908636 and parameters: {'layer1': 71, 'layer2': 423, 'layer3': 491, 'activation': 'identity', 'solver': 'adam', 'lr': 0.00011612273970761123}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [18:07:27<16:12:39, 8337.13s/it]

[I 2026-02-21 05:18:16,040] Trial 164 finished with value: 0.840942695876967 and parameters: {'layer1': 33, 'layer2': 457, 'layer3': 444, 'activation': 'identity', 'solver': 'adam', 'lr': 8.375776170523882e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [18:07:53<16:12:39, 8337.13s/it]

[I 2026-02-21 05:18:42,096] Trial 165 finished with value: 0.8443635567441474 and parameters: {'layer1': 88, 'layer2': 199, 'layer3': 483, 'activation': 'identity', 'solver': 'adam', 'lr': 4.41499789835647e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [18:08:16<16:12:39, 8337.13s/it]

[I 2026-02-21 05:19:05,175] Trial 166 finished with value: 0.8425610935942336 and parameters: {'layer1': 55, 'layer2': 435, 'layer3': 459, 'activation': 'identity', 'solver': 'adam', 'lr': 3.571311010262438e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [18:08:27<16:12:39, 8337.13s/it]

[I 2026-02-21 05:19:16,504] Trial 167 finished with value: 0.743221303406506 and parameters: {'layer1': 82, 'layer2': 471, 'layer3': 477, 'activation': 'identity', 'solver': 'adam', 'lr': 1.145447932445048e-06}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [18:08:51<16:12:39, 8337.13s/it]

[I 2026-02-21 05:19:39,880] Trial 168 finished with value: 0.8436579650883844 and parameters: {'layer1': 21, 'layer2': 451, 'layer3': 495, 'activation': 'identity', 'solver': 'adam', 'lr': 6.064450194868301e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [18:09:23<16:12:39, 8337.13s/it]

[I 2026-02-21 05:20:11,917] Trial 169 finished with value: 0.8458459481901197 and parameters: {'layer1': 343, 'layer2': 478, 'layer3': 470, 'activation': 'relu', 'solver': 'adam', 'lr': 9.627263671207083e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [18:09:56<16:12:39, 8337.13s/it]

[I 2026-02-21 05:20:45,337] Trial 170 finished with value: 0.8436388840458033 and parameters: {'layer1': 343, 'layer2': 477, 'layer3': 434, 'activation': 'relu', 'solver': 'adam', 'lr': 9.383878558355123e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [18:10:18<16:12:39, 8337.13s/it]

[I 2026-02-21 05:21:07,533] Trial 171 finished with value: 0.8415383280758804 and parameters: {'layer1': 94, 'layer2': 462, 'layer3': 465, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00012241973810116124}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [18:10:43<16:12:39, 8337.13s/it]

[I 2026-02-21 05:21:32,711] Trial 172 finished with value: 0.8429534407937475 and parameters: {'layer1': 328, 'layer2': 481, 'layer3': 499, 'activation': 'identity', 'solver': 'adam', 'lr': 7.697664147778157e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [18:11:15<16:12:39, 8337.13s/it]

[I 2026-02-21 05:22:04,570] Trial 173 finished with value: 0.8418590403734815 and parameters: {'layer1': 360, 'layer2': 471, 'layer3': 480, 'activation': 'relu', 'solver': 'adam', 'lr': 5.099932740056532e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [18:11:56<16:12:39, 8337.13s/it]

[I 2026-02-21 05:22:45,297] Trial 174 finished with value: 0.8410912089576514 and parameters: {'layer1': 319, 'layer2': 492, 'layer3': 454, 'activation': 'relu', 'solver': 'adam', 'lr': 3.0651228781276504e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [18:12:30<16:12:39, 8337.13s/it]

[I 2026-02-21 05:23:19,281] Trial 175 finished with value: 0.8417867377502244 and parameters: {'layer1': 341, 'layer2': 459, 'layer3': 466, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00017778237762992586}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [18:12:51<16:12:39, 8337.13s/it]

[I 2026-02-21 05:23:39,988] Trial 176 finished with value: 0.8406479848883519 and parameters: {'layer1': 105, 'layer2': 447, 'layer3': 487, 'activation': 'identity', 'solver': 'adam', 'lr': 4.021414644540645e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [18:13:07<16:12:39, 8337.13s/it]

[I 2026-02-21 05:23:56,432] Trial 177 finished with value: 0.8426191442023369 and parameters: {'layer1': 114, 'layer2': 483, 'layer3': 417, 'activation': 'identity', 'solver': 'adam', 'lr': 9.862040106630484e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [18:13:18<16:12:39, 8337.13s/it]

[I 2026-02-21 05:24:07,620] Trial 178 finished with value: 0.745306643735605 and parameters: {'layer1': 72, 'layer2': 471, 'layer3': 472, 'activation': 'tanh', 'solver': 'sgd', 'lr': 6.558817436330568e-05}. Best is trial 82 with value: 0.8480129925505899.

Training Exact MLP (Paper):  50%|█████     | 7/14 [18:13:51<16:12:39, 8337.13s/it]

[I 2026-02-21 05:24:40,517] Trial 179 finished with value: 0.8481836026243854 and parameters: {'layer1': 351, 'layer2': 492, 'layer3': 485, 'activation': 'identity', 'solver': 'adam', 'lr': 3.456723803065467e-05}. Best is trial 179 with value: 0.8481836026243854.

Training Exact MLP (Paper):  50%|█████     | 7/14 [18:14:25<16:12:39, 8337.13s/it]

[I 2026-02-21 05:25:13,865] Trial 180 finished with value: 0.8420115479744845 and parameters: {'layer1': 347, 'layer2': 52, 'layer3': 447, 'activation': 'identity', 'solver': 'adam', 'lr': 2.7820122521719666e-05}. Best is trial 179 with value: 0.8481836026243854.

Training Exact MLP (Paper):  50%|█████     | 7/14 [18:14:51<16:12:39, 8337.13s/it]

[I 2026-02-21 05:25:40,438] Trial 181 finished with value: 0.8434553756365956 and parameters: {'layer1': 335, 'layer2': 499, 'layer3': 489, 'activation': 'identity', 'solver': 'adam', 'lr': 4.7696132384026523e-05}. Best is trial 179 with value: 0.8481836026243854.

Training Exact MLP (Paper):  50%|█████     | 7/14 [18:15:23<16:12:39, 8337.13s/it]

[I 2026-02-21 05:26:11,862] Trial 182 finished with value: 0.8443942331488223 and parameters: {'layer1': 364, 'layer2': 490, 'layer3': 475, 'activation': 'identity', 'solver': 'adam', 'lr': 3.5569603328155825e-05}. Best is trial 179 with value: 0.8481836026243854.

Training Exact MLP (Paper):  50%|█████     | 7/14 [18:15:58<16:12:39, 8337.13s/it]

[I 2026-02-21 05:26:46,882] Trial 183 finished with value: 0.8439553314288653 and parameters: {'layer1': 380, 'layer2': 478, 'layer3': 499, 'activation': 'identity', 'solver': 'adam', 'lr': 3.102823239321093e-05}. Best is trial 179 with value: 0.8481836026243854.

Training Exact MLP (Paper):  50%|█████     | 7/14 [18:16:32<16:12:39, 8337.13s/it]

[I 2026-02-21 05:27:20,940] Trial 184 finished with value: 0.8446478116270436 and parameters: {'layer1': 354, 'layer2': 462, 'layer3': 482, 'activation': 'identity', 'solver': 'adam', 'lr': 2.482564511986255e-05}. Best is trial 179 with value: 0.8481836026243854.

Training Exact MLP (Paper):  50%|█████     | 7/14 [18:17:13<16:12:39, 8337.13s/it]

[I 2026-02-21 05:28:01,894] Trial 185 finished with value: 0.8424705611982997 and parameters: {'layer1': 349, 'layer2': 460, 'layer3': 481, 'activation': 'identity', 'solver': 'adam', 'lr': 1.772220995089524e-05}. Best is trial 179 with value: 0.8481836026243854.

Training Exact MLP (Paper):  50%|█████     | 7/14 [18:17:46<16:12:39, 8337.13s/it]

[I 2026-02-21 05:28:34,972] Trial 186 finished with value: 0.8428907418818214 and parameters: {'layer1': 357, 'layer2': 486, 'layer3': 266, 'activation': 'identity', 'solver': 'adam', 'lr': 2.3216746829914828e-05}. Best is trial 179 with value: 0.8481836026243854.

Training Exact MLP (Paper):  50%|█████     | 7/14 [18:18:16<16:12:39, 8337.13s/it]

[I 2026-02-21 05:29:05,057] Trial 187 finished with value: 0.8428486126027741 and parameters: {'layer1': 163, 'layer2': 473, 'layer3': 461, 'activation': 'identity', 'solver': 'adam', 'lr': 2.5184025264025692e-05}. Best is trial 179 with value: 0.8481836026243854.

Training Exact MLP (Paper):  50%|█████     | 7/14 [18:18:54<16:12:39, 8337.13s/it]

[I 2026-02-21 05:29:43,350] Trial 188 finished with value: 0.8420064655522157 and parameters: {'layer1': 327, 'layer2': 494, 'layer3': 471, 'activation': 'identity', 'solver': 'adam', 'lr': 2.0375334848291534e-05}. Best is trial 179 with value: 0.8481836026243854.

Training Exact MLP (Paper):  50%|█████     | 7/14 [18:19:23<16:12:39, 8337.13s/it]

[I 2026-02-21 05:30:12,722] Trial 189 finished with value: 0.8408692555754378 and parameters: {'layer1': 238, 'layer2': 465, 'layer3': 485, 'activation': 'identity', 'solver': 'adam', 'lr': 2.836239964397816e-05}. Best is trial 179 with value: 0.8481836026243854.

Training Exact MLP (Paper):  50%|█████     | 7/14 [18:19:43<16:12:39, 8337.13s/it]

[I 2026-02-21 05:30:32,174] Trial 190 finished with value: 0.8393913653068864 and parameters: {'layer1': 226, 'layer2': 482, 'layer3': 457, 'activation': 'identity', 'solver': 'adam', 'lr': 0.00013891238274180156}. Best is trial 179 with value: 0.8481836026243854.

Training Exact MLP (Paper):  50%|█████     | 7/14 [18:20:16<16:12:39, 8337.13s/it]

[I 2026-02-21 05:31:05,027] Trial 191 finished with value: 0.8399577603609985 and parameters: {'layer1': 338, 'layer2': 500, 'layer3': 491, 'activation': 'identity', 'solver': 'adam', 'lr': 3.804601402160941e-05}. Best is trial 179 with value: 0.8481836026243854.

Training Exact MLP (Paper):  50%|█████     | 7/14 [18:20:46<16:12:39, 8337.13s/it]

[I 2026-02-21 05:31:35,324] Trial 192 finished with value: 0.8453702897628526 and parameters: {'layer1': 370, 'layer2': 437, 'layer3': 498, 'activation': 'identity', 'solver': 'adam', 'lr': 4.837796070390917e-05}. Best is trial 179 with value: 0.8481836026243854.

Training Exact MLP (Paper):  50%|█████     | 7/14 [18:21:14<16:12:39, 8337.13s/it]

[I 2026-02-21 05:32:03,575] Trial 193 finished with value: 0.8401750154727162 and parameters: {'layer1': 371, 'layer2': 439, 'layer3': 480, 'activation': 'identity', 'solver': 'adam', 'lr': 4.9090744014438376e-05}. Best is trial 179 with value: 0.8481836026243854.

Training Exact MLP (Paper):  50%|█████     | 7/14 [18:21:45<16:12:39, 8337.13s/it]

[I 2026-02-21 05:32:34,604] Trial 194 finished with value: 0.844549450072875 and parameters: {'layer1': 404, 'layer2': 453, 'layer3': 499, 'activation': 'identity', 'solver': 'adam', 'lr': 3.4453328072555454e-05}. Best is trial 179 with value: 0.8481836026243854.

Training Exact MLP (Paper):  50%|█████     | 7/14 [18:22:14<16:12:39, 8337.13s/it]

[I 2026-02-21 05:33:03,350] Trial 195 finished with value: 0.8406703589348709 and parameters: {'layer1': 384, 'layer2': 478, 'layer3': 469, 'activation': 'identity', 'solver': 'adam', 'lr': 7.15452053646191e-05}. Best is trial 179 with value: 0.8481836026243854.

Training Exact MLP (Paper):  50%|█████     | 7/14 [18:22:30<16:12:39, 8337.13s/it]

[I 2026-02-21 05:33:19,331] Trial 196 finished with value: 0.7404498827712407 and parameters: {'layer1': 362, 'layer2': 466, 'layer3': 319, 'activation': 'logistic', 'solver': 'adam', 'lr': 4.1773354830930014e-05}. Best is trial 179 with value: 0.8481836026243854.

Training Exact MLP (Paper):  50%|█████     | 7/14 [18:22:58<16:12:39, 8337.13s/it]

[I 2026-02-21 05:33:47,366] Trial 197 finished with value: 0.8408616024718979 and parameters: {'layer1': 369, 'layer2': 491, 'layer3': 500, 'activation': 'identity', 'solver': 'adam', 'lr': 6.160739313206707e-05}. Best is trial 179 with value: 0.8481836026243854.

Training Exact MLP (Paper):  50%|█████     | 7/14 [18:23:35<16:12:39, 8337.13s/it]

[I 2026-02-21 05:34:24,053] Trial 198 finished with value: 0.8440843154534502 and parameters: {'layer1': 353, 'layer2': 216, 'layer3': 330, 'activation': 'identity', 'solver': 'adam', 'lr': 3.0006439311986732e-05}. Best is trial 179 with value: 0.8481836026243854.

Best trial: 179. Best value: 0.848184: 100%|██████████| 200/200 [1:27:34<00:00, 26.27s/it]

[I 2026-02-21 05:35:06,807] Trial 199 finished with value: 0.8437339208812856 and parameters: {'layer1': 345, 'layer2': 447, 'layer3': 484, 'activation': 'identity', 'solver': 'adam', 'lr': 1.636856797321241e-05}. Best is trial 179 with value: 0.8481836026243854.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:24:19<12:15:36, 7356.10s/it][I 2026-02-21 05:35:07,975] A new study created in memory with name: no-name-ed5e08fd-137b-4748-90f8-9809600378db

  → Best model saved.

[Exact Paper MLP] Klebsiella_Pneumoniae | Ceftriaxone

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:24:39<12:15:36, 7356.10s/it]

[I 2026-02-21 05:35:28,170] Trial 0 finished with value: 0.9021460548179527 and parameters: {'layer1': 204, 'layer2': 476, 'layer3': 315, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0003192339412909528}. Best is trial 0 with value: 0.9021460548179527.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:24:56<12:15:36, 7356.10s/it]

[I 2026-02-21 05:35:45,396] Trial 1 finished with value: 0.7889420666920989 and parameters: {'layer1': 426, 'layer2': 392, 'layer3': 370, 'activation': 'tanh', 'solver': 'adam', 'lr': 3.447106479574737e-06}. Best is trial 0 with value: 0.9021460548179527.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:25:07<12:15:36, 7356.10s/it]

[I 2026-02-21 05:35:56,037] Trial 2 finished with value: 0.7914780219871618 and parameters: {'layer1': 225, 'layer2': 154, 'layer3': 30, 'activation': 'identity', 'solver': 'sgd', 'lr': 7.558639307148785e-05}. Best is trial 0 with value: 0.9021460548179527.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:25:25<12:15:36, 7356.10s/it]

[I 2026-02-21 05:36:14,634] Trial 3 finished with value: 0.7889420666920989 and parameters: {'layer1': 498, 'layer2': 123, 'layer3': 448, 'activation': 'identity', 'solver': 'adam', 'lr': 2.36325436111368e-06}. Best is trial 0 with value: 0.9021460548179527.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:25:44<12:15:36, 7356.10s/it]

[I 2026-02-21 05:36:33,467] Trial 4 finished with value: 0.9039166523769951 and parameters: {'layer1': 253, 'layer2': 173, 'layer3': 377, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0001242081671567929}. Best is trial 4 with value: 0.9039166523769951.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:26:14<12:15:36, 7356.10s/it]

[I 2026-02-21 05:37:03,138] Trial 5 finished with value: 0.895789971674373 and parameters: {'layer1': 478, 'layer2': 215, 'layer3': 55, 'activation': 'relu', 'solver': 'adam', 'lr': 0.005485369589945781}. Best is trial 4 with value: 0.9039166523769951.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:26:40<12:15:36, 7356.10s/it]

[I 2026-02-21 05:37:29,225] Trial 6 finished with value: 0.7945915952804702 and parameters: {'layer1': 245, 'layer2': 414, 'layer3': 485, 'activation': 'identity', 'solver': 'sgd', 'lr': 1.112762501955547e-05}. Best is trial 4 with value: 0.9039166523769951.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:26:48<12:15:36, 7356.10s/it]

[I 2026-02-21 05:37:37,527] Trial 7 finished with value: 0.7889420666920989 and parameters: {'layer1': 117, 'layer2': 133, 'layer3': 196, 'activation': 'identity', 'solver': 'sgd', 'lr': 0.004047537191436428}. Best is trial 4 with value: 0.9039166523769951.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:27:00<12:15:36, 7356.10s/it]

[I 2026-02-21 05:37:49,545] Trial 8 finished with value: 0.7889420666920989 and parameters: {'layer1': 492, 'layer2': 44, 'layer3': 476, 'activation': 'identity', 'solver': 'sgd', 'lr': 0.00458884788265393}. Best is trial 4 with value: 0.9039166523769951.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:27:08<12:15:36, 7356.10s/it]

[I 2026-02-21 05:37:57,723] Trial 9 finished with value: 0.7889420666920989 and parameters: {'layer1': 25, 'layer2': 216, 'layer3': 246, 'activation': 'tanh', 'solver': 'sgd', 'lr': 0.002652150533390221}. Best is trial 4 with value: 0.9039166523769951.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:27:28<12:15:36, 7356.10s/it]

[I 2026-02-21 05:38:17,370] Trial 10 finished with value: 0.810116272937232 and parameters: {'layer1': 360, 'layer2': 328, 'layer3': 155, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0001508620425546247}. Best is trial 4 with value: 0.9039166523769951.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:27:44<12:15:36, 7356.10s/it]

[I 2026-02-21 05:38:33,422] Trial 11 finished with value: 0.9036832202827428 and parameters: {'layer1': 164, 'layer2': 475, 'layer3': 339, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0003361786570204185}. Best is trial 4 with value: 0.9039166523769951.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:28:02<12:15:36, 7356.10s/it]

[I 2026-02-21 05:38:51,503] Trial 12 finished with value: 0.8987300098315393 and parameters: {'layer1': 326, 'layer2': 296, 'layer3': 362, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0005724517747719893}. Best is trial 4 with value: 0.9039166523769951.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:28:22<12:15:36, 7356.10s/it]

[I 2026-02-21 05:39:11,087] Trial 13 finished with value: 0.9034367487844515 and parameters: {'layer1': 144, 'layer2': 485, 'layer3': 394, 'activation': 'tanh', 'solver': 'adam', 'lr': 4.250962625962524e-05}. Best is trial 4 with value: 0.9039166523769951.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:28:47<12:15:36, 7356.10s/it]

[I 2026-02-21 05:39:36,808] Trial 14 finished with value: 0.8986749567547877 and parameters: {'layer1': 314, 'layer2': 30, 'layer3': 310, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0009381591977019866}. Best is trial 4 with value: 0.9039166523769951.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:29:23<12:15:36, 7356.10s/it]

[I 2026-02-21 05:40:12,740] Trial 15 finished with value: 0.9063688082103974 and parameters: {'layer1': 162, 'layer2': 348, 'layer3': 297, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.516723450289198e-05}. Best is trial 15 with value: 0.9063688082103974.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:29:52<12:15:36, 7356.10s/it]

[I 2026-02-21 05:40:41,775] Trial 16 finished with value: 0.9060509593558159 and parameters: {'layer1': 63, 'layer2': 347, 'layer3': 255, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.246406591126076e-05}. Best is trial 15 with value: 0.9063688082103974.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:30:02<12:15:36, 7356.10s/it]

[I 2026-02-21 05:40:51,345] Trial 17 finished with value: 0.7905625101859003 and parameters: {'layer1': 52, 'layer2': 361, 'layer3': 141, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.5450786064385257e-05}. Best is trial 15 with value: 0.9063688082103974.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:30:12<12:15:36, 7356.10s/it]

[I 2026-02-21 05:41:01,608] Trial 18 finished with value: 0.7903151975336831 and parameters: {'layer1': 84, 'layer2': 299, 'layer3': 248, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.0291296281594955e-05}. Best is trial 15 with value: 0.9063688082103974.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:30:24<12:15:36, 7356.10s/it]

[I 2026-02-21 05:41:12,858] Trial 19 finished with value: 0.7901407239529306 and parameters: {'layer1': 83, 'layer2': 421, 'layer3': 273, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.1341990588612505e-06}. Best is trial 15 with value: 0.9063688082103974.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:30:52<12:15:36, 7356.10s/it]

[I 2026-02-21 05:41:41,454] Trial 20 finished with value: 0.9071530022508787 and parameters: {'layer1': 169, 'layer2': 246, 'layer3': 196, 'activation': 'tanh', 'solver': 'adam', 'lr': 3.612087957529278e-05}. Best is trial 20 with value: 0.9071530022508787.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:31:22<12:15:36, 7356.10s/it]

[I 2026-02-21 05:42:11,729] Trial 21 finished with value: 0.9074778141258338 and parameters: {'layer1': 179, 'layer2': 255, 'layer3': 201, 'activation': 'tanh', 'solver': 'adam', 'lr': 3.3201354489609355e-05}. Best is trial 21 with value: 0.9074778141258338.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:31:49<12:15:36, 7356.10s/it]

[I 2026-02-21 05:42:38,630] Trial 22 finished with value: 0.909723623918263 and parameters: {'layer1': 176, 'layer2': 253, 'layer3': 189, 'activation': 'tanh', 'solver': 'adam', 'lr': 3.7195010487107614e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:32:15<12:15:36, 7356.10s/it]

[I 2026-02-21 05:43:04,233] Trial 23 finished with value: 0.9064030254397023 and parameters: {'layer1': 187, 'layer2': 246, 'layer3': 193, 'activation': 'tanh', 'solver': 'adam', 'lr': 4.350125932718777e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:32:32<12:15:36, 7356.10s/it]

[I 2026-02-21 05:43:21,330] Trial 24 finished with value: 0.7889420666920989 and parameters: {'layer1': 292, 'layer2': 276, 'layer3': 156, 'activation': 'logistic', 'solver': 'adam', 'lr': 6.190070350654108e-06}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:32:57<12:15:36, 7356.10s/it]

[I 2026-02-21 05:43:46,504] Trial 25 finished with value: 0.9056580420977595 and parameters: {'layer1': 112, 'layer2': 224, 'layer3': 93, 'activation': 'tanh', 'solver': 'adam', 'lr': 3.758497076310272e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:33:10<12:15:36, 7356.10s/it]

[I 2026-02-21 05:43:59,599] Trial 26 finished with value: 0.7914058966574158 and parameters: {'layer1': 207, 'layer2': 257, 'layer3': 209, 'activation': 'tanh', 'solver': 'sgd', 'lr': 7.728826436713556e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:33:26<12:15:36, 7356.10s/it]

[I 2026-02-21 05:44:15,508] Trial 27 finished with value: 0.9051529631852346 and parameters: {'layer1': 136, 'layer2': 191, 'layer3': 102, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0001978697571791352}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:34:01<12:15:36, 7356.10s/it]

[I 2026-02-21 05:44:50,224] Trial 28 finished with value: 0.9072394718486049 and parameters: {'layer1': 266, 'layer2': 77, 'layer3': 211, 'activation': 'tanh', 'solver': 'adam', 'lr': 3.214068876588908e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:34:17<12:15:36, 7356.10s/it]

[I 2026-02-21 05:45:06,235] Trial 29 finished with value: 0.7889420666920989 and parameters: {'layer1': 275, 'layer2': 83, 'layer3': 118, 'activation': 'logistic', 'solver': 'adam', 'lr': 5.991455718087892e-06}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:34:40<12:15:36, 7356.10s/it]

[I 2026-02-21 05:45:29,693] Trial 30 finished with value: 0.9017526132101196 and parameters: {'layer1': 354, 'layer2': 113, 'layer3': 215, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0002603862655876164}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:35:14<12:15:36, 7356.10s/it]

[I 2026-02-21 05:46:02,990] Trial 31 finished with value: 0.9086638464261141 and parameters: {'layer1': 193, 'layer2': 71, 'layer3': 181, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.7946214599388376e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:35:41<12:15:36, 7356.10s/it]

[I 2026-02-21 05:46:30,468] Trial 32 finished with value: 0.8579220563181892 and parameters: {'layer1': 212, 'layer2': 68, 'layer3': 174, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.3817170153964482e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:36:10<12:15:36, 7356.10s/it]

[I 2026-02-21 05:46:58,956] Trial 33 finished with value: 0.9062626864261805 and parameters: {'layer1': 229, 'layer2': 12, 'layer3': 239, 'activation': 'tanh', 'solver': 'adam', 'lr': 7.613428696007605e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:36:21<12:15:36, 7356.10s/it]

[I 2026-02-21 05:47:10,372] Trial 34 finished with value: 0.789069413496474 and parameters: {'layer1': 199, 'layer2': 96, 'layer3': 125, 'activation': 'tanh', 'solver': 'adam', 'lr': 4.513590709204815e-06}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:36:46<12:15:36, 7356.10s/it]

[I 2026-02-21 05:47:35,444] Trial 35 finished with value: 0.9071115476028332 and parameters: {'layer1': 275, 'layer2': 152, 'layer3': 74, 'activation': 'tanh', 'solver': 'adam', 'lr': 5.327418779370531e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:36:59<12:15:36, 7356.10s/it]

[I 2026-02-21 05:47:48,426] Trial 36 finished with value: 0.7898182787872465 and parameters: {'layer1': 231, 'layer2': 58, 'layer3': 275, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.6021567508468566e-06}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:37:16<12:15:36, 7356.10s/it]

[I 2026-02-21 05:48:05,284] Trial 37 finished with value: 0.7889420666920989 and parameters: {'layer1': 407, 'layer2': 163, 'layer3': 11, 'activation': 'tanh', 'solver': 'sgd', 'lr': 0.00012465551070367858}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:37:29<12:15:36, 7356.10s/it]

[I 2026-02-21 05:48:18,371] Trial 38 finished with value: 0.7889420666920989 and parameters: {'layer1': 261, 'layer2': 199, 'layer3': 225, 'activation': 'identity', 'solver': 'adam', 'lr': 1.0794246055388621e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:37:44<12:15:36, 7356.10s/it]

[I 2026-02-21 05:48:33,414] Trial 39 finished with value: 0.6422788103894257 and parameters: {'layer1': 192, 'layer2': 119, 'layer3': 173, 'activation': 'tanh', 'solver': 'sgd', 'lr': 2.7019351082309343e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:38:07<12:15:36, 7356.10s/it]

[I 2026-02-21 05:48:56,636] Trial 40 finished with value: 0.9045334304311842 and parameters: {'layer1': 115, 'layer2': 142, 'layer3': 176, 'activation': 'relu', 'solver': 'adam', 'lr': 6.499907652401498e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:38:39<12:15:36, 7356.10s/it]

[I 2026-02-21 05:49:28,117] Trial 41 finished with value: 0.9055980505571327 and parameters: {'layer1': 157, 'layer2': 252, 'layer3': 191, 'activation': 'tanh', 'solver': 'adam', 'lr': 3.1007524382186324e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:38:58<12:15:36, 7356.10s/it]

[I 2026-02-21 05:49:46,924] Trial 42 finished with value: 0.904593042192665 and parameters: {'layer1': 175, 'layer2': 314, 'layer3': 216, 'activation': 'tanh', 'solver': 'adam', 'lr': 9.728223788005975e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:39:15<12:15:36, 7356.10s/it]

[I 2026-02-21 05:50:04,314] Trial 43 finished with value: 0.810269972046169 and parameters: {'layer1': 133, 'layer2': 184, 'layer3': 143, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.646009371883173e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:39:28<12:15:36, 7356.10s/it]

[I 2026-02-21 05:50:16,916] Trial 44 finished with value: 0.7889420666920989 and parameters: {'layer1': 235, 'layer2': 221, 'layer3': 274, 'activation': 'identity', 'solver': 'adam', 'lr': 8.72689719218153e-06}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:40:01<12:15:36, 7356.10s/it]

[I 2026-02-21 05:50:50,846] Trial 45 finished with value: 0.9052218114343276 and parameters: {'layer1': 254, 'layer2': 277, 'layer3': 231, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.349078226707616e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:40:15<12:15:36, 7356.10s/it]

[I 2026-02-21 05:51:04,696] Trial 46 finished with value: 0.7916563563937009 and parameters: {'layer1': 179, 'layer2': 379, 'layer3': 161, 'activation': 'tanh', 'solver': 'sgd', 'lr': 5.3692237593625614e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:40:28<12:15:36, 7356.10s/it]

[I 2026-02-21 05:51:17,476] Trial 47 finished with value: 0.7889420666920989 and parameters: {'layer1': 219, 'layer2': 99, 'layer3': 196, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.00011054754650745683}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:40:39<12:15:36, 7356.10s/it]

[I 2026-02-21 05:51:28,030] Trial 48 finished with value: 0.7889420666920989 and parameters: {'layer1': 155, 'layer2': 43, 'layer3': 50, 'activation': 'identity', 'solver': 'adam', 'lr': 1.7137940652777274e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:40:53<12:15:36, 7356.10s/it]

[I 2026-02-21 05:51:42,684] Trial 49 finished with value: 0.8975144939145536 and parameters: {'layer1': 92, 'layer2': 430, 'layer3': 129, 'activation': 'relu', 'solver': 'adam', 'lr': 0.009460468238396398}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:41:05<12:15:36, 7356.10s/it]

[I 2026-02-21 05:51:53,868] Trial 50 finished with value: 0.7910774563319297 and parameters: {'layer1': 307, 'layer2': 233, 'layer3': 417, 'activation': 'tanh', 'solver': 'sgd', 'lr': 0.00016463769411993672}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:41:33<12:15:36, 7356.10s/it]

[I 2026-02-21 05:52:22,760] Trial 51 finished with value: 0.9055579111817048 and parameters: {'layer1': 277, 'layer2': 147, 'layer3': 77, 'activation': 'tanh', 'solver': 'adam', 'lr': 5.079452496184053e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:42:09<12:15:36, 7356.10s/it]

[I 2026-02-21 05:52:57,889] Trial 52 finished with value: 0.909140324238695 and parameters: {'layer1': 348, 'layer2': 273, 'layer3': 68, 'activation': 'tanh', 'solver': 'adam', 'lr': 3.483283615398675e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:42:43<12:15:36, 7356.10s/it]

[I 2026-02-21 05:53:31,935] Trial 53 finished with value: 0.9059195311305599 and parameters: {'layer1': 350, 'layer2': 280, 'layer3': 326, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.745203893823144e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:43:13<12:15:36, 7356.10s/it]

[I 2026-02-21 05:54:02,660] Trial 54 finished with value: 0.9052234264895119 and parameters: {'layer1': 406, 'layer2': 317, 'layer3': 294, 'activation': 'tanh', 'solver': 'adam', 'lr': 3.686063483274676e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:44:03<12:15:36, 7356.10s/it]

[I 2026-02-21 05:54:51,924] Trial 55 finished with value: 0.9066799254612091 and parameters: {'layer1': 385, 'layer2': 205, 'layer3': 201, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.8128925649755013e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:44:39<12:15:36, 7356.10s/it]

[I 2026-02-21 05:55:28,291] Trial 56 finished with value: 0.8565220241482446 and parameters: {'layer1': 329, 'layer2': 262, 'layer3': 258, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.326502168605976e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:44:51<12:15:36, 7356.10s/it]

[I 2026-02-21 05:55:40,640] Trial 57 finished with value: 0.7889420666920989 and parameters: {'layer1': 174, 'layer2': 297, 'layer3': 110, 'activation': 'tanh', 'solver': 'adam', 'lr': 7.6055232526928165e-06}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:45:03<12:15:36, 7356.10s/it]

[I 2026-02-21 05:55:51,902] Trial 58 finished with value: 0.7889420666920989 and parameters: {'layer1': 131, 'layer2': 243, 'layer3': 183, 'activation': 'logistic', 'solver': 'adam', 'lr': 7.526027321877927e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:45:17<12:15:36, 7356.10s/it]

[I 2026-02-21 05:56:06,264] Trial 59 finished with value: 0.9026856944176703 and parameters: {'layer1': 101, 'layer2': 339, 'layer3': 163, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0005334520794977475}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:45:42<12:15:36, 7356.10s/it]

[I 2026-02-21 05:56:31,760] Trial 60 finished with value: 0.9054859409445154 and parameters: {'layer1': 202, 'layer2': 176, 'layer3': 142, 'activation': 'tanh', 'solver': 'adam', 'lr': 3.758739926224088e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:45:55<12:15:36, 7356.10s/it]

[I 2026-02-21 05:56:44,604] Trial 61 finished with value: 0.7889420666920989 and parameters: {'layer1': 283, 'layer2': 11, 'layer3': 67, 'activation': 'tanh', 'solver': 'adam', 'lr': 5.490111187485772e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:46:24<12:15:36, 7356.10s/it]

[I 2026-02-21 05:57:13,505] Trial 62 finished with value: 0.9055595854132139 and parameters: {'layer1': 253, 'layer2': 73, 'layer3': 40, 'activation': 'tanh', 'solver': 'adam', 'lr': 4.233112700456388e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:47:06<12:15:36, 7356.10s/it]

[I 2026-02-21 05:57:55,467] Trial 63 finished with value: 0.9058408125408419 and parameters: {'layer1': 439, 'layer2': 130, 'layer3': 69, 'activation': 'tanh', 'solver': 'adam', 'lr': 3.0109705729503783e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:47:30<12:15:36, 7356.10s/it]

[I 2026-02-21 05:58:19,443] Trial 64 finished with value: 0.9054740880496578 and parameters: {'layer1': 244, 'layer2': 37, 'layer3': 89, 'activation': 'tanh', 'solver': 'adam', 'lr': 9.280602528420342e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:47:53<12:15:36, 7356.10s/it]

[I 2026-02-21 05:58:42,274] Trial 65 finished with value: 0.8394033083164258 and parameters: {'layer1': 331, 'layer2': 161, 'layer3': 22, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.035385598286476e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:48:21<12:15:36, 7356.10s/it]

[I 2026-02-21 05:59:10,374] Trial 66 finished with value: 0.90599887370379 and parameters: {'layer1': 216, 'layer2': 234, 'layer3': 225, 'activation': 'relu', 'solver': 'adam', 'lr': 6.134394832774138e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:49:15<12:15:36, 7356.10s/it]

[I 2026-02-21 06:00:04,331] Trial 67 finished with value: 0.9067843847135821 and parameters: {'layer1': 454, 'layer2': 268, 'layer3': 205, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.2940862556412309e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:49:39<12:15:36, 7356.10s/it]

[I 2026-02-21 06:00:28,024] Trial 68 finished with value: 0.7901393067630483 and parameters: {'layer1': 297, 'layer2': 102, 'layer3': 133, 'activation': 'tanh', 'solver': 'sgd', 'lr': 3.260593634799988e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:49:51<12:15:36, 7356.10s/it]

[I 2026-02-21 06:00:39,851] Trial 69 finished with value: 0.7890764067266088 and parameters: {'layer1': 147, 'layer2': 210, 'layer3': 100, 'activation': 'logistic', 'solver': 'adam', 'lr': 4.936547167986686e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:50:03<12:15:36, 7356.10s/it]

[I 2026-02-21 06:00:52,833] Trial 70 finished with value: 0.901111990836575 and parameters: {'layer1': 187, 'layer2': 55, 'layer3': 260, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0016317947051732457}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:51:05<12:15:36, 7356.10s/it]

[I 2026-02-21 06:01:54,077] Trial 71 finished with value: 0.9065452330042421 and parameters: {'layer1': 439, 'layer2': 266, 'layer3': 203, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.3821252965905303e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:51:27<12:15:36, 7356.10s/it]

[I 2026-02-21 06:02:16,213] Trial 72 finished with value: 0.8096995988069325 and parameters: {'layer1': 265, 'layer2': 292, 'layer3': 218, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.2834519391634248e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:52:10<12:15:36, 7356.10s/it]

[I 2026-02-21 06:02:58,907] Trial 73 finished with value: 0.9072818457156959 and parameters: {'layer1': 452, 'layer2': 237, 'layer3': 186, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.2471578895682183e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:52:55<12:15:36, 7356.10s/it]

[I 2026-02-21 06:03:43,851] Trial 74 finished with value: 0.9069785504064056 and parameters: {'layer1': 467, 'layer2': 242, 'layer3': 242, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.0742358462426302e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:53:12<12:15:36, 7356.10s/it]

[I 2026-02-21 06:04:01,193] Trial 75 finished with value: 0.9038868347339213 and parameters: {'layer1': 170, 'layer2': 309, 'layer3': 184, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.00014204381255927522}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:53:36<12:15:36, 7356.10s/it]

[I 2026-02-21 06:04:24,942] Trial 76 finished with value: 0.9052286976536978 and parameters: {'layer1': 383, 'layer2': 225, 'layer3': 166, 'activation': 'tanh', 'solver': 'adam', 'lr': 8.046272571178924e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:54:05<12:15:36, 7356.10s/it]

[I 2026-02-21 06:04:53,875] Trial 77 finished with value: 0.9059288627722261 and parameters: {'layer1': 370, 'layer2': 189, 'layer3': 231, 'activation': 'tanh', 'solver': 'adam', 'lr': 4.235552284390809e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:54:37<12:15:36, 7356.10s/it]

[I 2026-02-21 06:05:26,683] Trial 78 finished with value: 0.9066380042227629 and parameters: {'layer1': 236, 'layer2': 83, 'layer3': 151, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.563443587594284e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:55:29<12:15:36, 7356.10s/it]

[I 2026-02-21 06:06:18,348] Trial 79 finished with value: 0.6408123340791425 and parameters: {'layer1': 194, 'layer2': 281, 'layer3': 189, 'activation': 'relu', 'solver': 'sgd', 'lr': 4.5959163944266914e-06}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:56:06<12:15:36, 7356.10s/it]

[I 2026-02-21 06:06:55,677] Trial 80 finished with value: 0.9061537414375147 and parameters: {'layer1': 480, 'layer2': 252, 'layer3': 117, 'activation': 'tanh', 'solver': 'adam', 'lr': 3.3179784422219056e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:56:50<12:15:36, 7356.10s/it]

[I 2026-02-21 06:07:39,553] Trial 81 finished with value: 0.9073594622618728 and parameters: {'layer1': 462, 'layer2': 250, 'layer3': 240, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.0589116065293558e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:57:07<12:15:36, 7356.10s/it]

[I 2026-02-21 06:07:56,346] Trial 82 finished with value: 0.7889420666920989 and parameters: {'layer1': 404, 'layer2': 290, 'layer3': 286, 'activation': 'tanh', 'solver': 'adam', 'lr': 8.364337617591258e-06}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:57:48<12:15:36, 7356.10s/it]

[I 2026-02-21 06:08:37,737] Trial 83 finished with value: 0.9079258625782897 and parameters: {'layer1': 500, 'layer2': 215, 'layer3': 237, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.2799869297031344e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:58:33<12:15:36, 7356.10s/it]

[I 2026-02-21 06:09:22,015] Trial 84 finished with value: 0.9066665338244515 and parameters: {'layer1': 498, 'layer2': 216, 'layer3': 245, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.9945995915340708e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:59:12<12:15:36, 7356.10s/it]

[I 2026-02-21 06:10:00,940] Trial 85 finished with value: 0.9070558733435062 and parameters: {'layer1': 460, 'layer2': 236, 'layer3': 214, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.5834664330738414e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [18:59:57<12:15:36, 7356.10s/it]

[I 2026-02-21 06:10:46,205] Trial 86 finished with value: 0.905805640751891 and parameters: {'layer1': 480, 'layer2': 199, 'layer3': 260, 'activation': 'identity', 'solver': 'adam', 'lr': 2.0955181076022186e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:00:15<12:15:36, 7356.10s/it]

[I 2026-02-21 06:11:04,486] Trial 87 finished with value: 0.7889420666920989 and parameters: {'layer1': 486, 'layer2': 258, 'layer3': 172, 'activation': 'tanh', 'solver': 'adam', 'lr': 9.626021847048556e-06}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:00:32<12:15:36, 7356.10s/it]

[I 2026-02-21 06:11:21,284] Trial 88 finished with value: 0.7889420666920989 and parameters: {'layer1': 500, 'layer2': 26, 'layer3': 357, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.532105160983568e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:01:01<12:15:36, 7356.10s/it]

[I 2026-02-21 06:11:50,677] Trial 89 finished with value: 0.9045746613432474 and parameters: {'layer1': 424, 'layer2': 277, 'layer3': 230, 'activation': 'tanh', 'solver': 'adam', 'lr': 6.523701556805505e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:01:19<12:15:36, 7356.10s/it]

[I 2026-02-21 06:12:08,527] Trial 90 finished with value: 0.7889420666920989 and parameters: {'layer1': 442, 'layer2': 306, 'layer3': 149, 'activation': 'logistic', 'solver': 'adam', 'lr': 4.2702241406870783e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:01:56<12:15:36, 7356.10s/it]

[I 2026-02-21 06:12:45,756] Trial 91 finished with value: 0.9080928038206011 and parameters: {'layer1': 465, 'layer2': 226, 'layer3': 196, 'activation': 'tanh', 'solver': 'adam', 'lr': 3.26174771917366e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:02:30<12:15:36, 7356.10s/it]

[I 2026-02-21 06:13:19,157] Trial 92 finished with value: 0.9063430424390966 and parameters: {'layer1': 466, 'layer2': 227, 'layer3': 195, 'activation': 'tanh', 'solver': 'adam', 'lr': 3.399858489263841e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:03:08<12:15:36, 7356.10s/it]

[I 2026-02-21 06:13:56,943] Trial 93 finished with value: 0.9069448399328615 and parameters: {'layer1': 424, 'layer2': 325, 'layer3': 181, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.6716679772700236e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:03:55<12:15:36, 7356.10s/it]

[I 2026-02-21 06:14:44,829] Trial 94 finished with value: 0.9078496402832286 and parameters: {'layer1': 449, 'layer2': 247, 'layer3': 212, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.744148603855821e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:04:13<12:15:36, 7356.10s/it]

[I 2026-02-21 06:15:02,111] Trial 95 finished with value: 0.7889420666920989 and parameters: {'layer1': 473, 'layer2': 246, 'layer3': 212, 'activation': 'tanh', 'solver': 'adam', 'lr': 6.382466722402501e-06}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:05:00<12:15:36, 7356.10s/it]

[I 2026-02-21 06:15:49,344] Trial 96 finished with value: 0.9070954637924882 and parameters: {'layer1': 455, 'layer2': 270, 'layer3': 248, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.5992824084794635e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:05:47<12:15:36, 7356.10s/it]

[I 2026-02-21 06:16:36,315] Trial 97 finished with value: 0.7904226431845405 and parameters: {'layer1': 489, 'layer2': 214, 'layer3': 235, 'activation': 'tanh', 'solver': 'sgd', 'lr': 1.1849918320074958e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:06:35<12:15:36, 7356.10s/it]

[I 2026-02-21 06:17:24,014] Trial 98 finished with value: 0.9064344737062177 and parameters: {'layer1': 451, 'layer2': 254, 'layer3': 271, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.791445944704747e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:07:30<12:15:36, 7356.10s/it]

[I 2026-02-21 06:18:18,981] Trial 99 finished with value: 0.9088783551365471 and parameters: {'layer1': 391, 'layer2': 458, 'layer3': 496, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.0623342737528403e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:08:12<12:15:36, 7356.10s/it]

[I 2026-02-21 06:19:01,004] Trial 100 finished with value: 0.8570616141774391 and parameters: {'layer1': 416, 'layer2': 382, 'layer3': 494, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.0087582628709696e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:08:45<12:15:36, 7356.10s/it]

[I 2026-02-21 06:19:34,806] Trial 101 finished with value: 0.9046202273946153 and parameters: {'layer1': 437, 'layer2': 356, 'layer3': 414, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.533140075695067e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:09:02<12:15:36, 7356.10s/it]

[I 2026-02-21 06:19:51,627] Trial 102 finished with value: 0.7889420666920989 and parameters: {'layer1': 396, 'layer2': 447, 'layer3': 307, 'activation': 'tanh', 'solver': 'adam', 'lr': 7.344900966706953e-06}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:09:19<12:15:36, 7356.10s/it]

[I 2026-02-21 06:20:08,532] Trial 103 finished with value: 0.7889420666920989 and parameters: {'layer1': 339, 'layer2': 442, 'layer3': 220, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.1406406322953398e-06}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:10:05<12:15:36, 7356.10s/it]

[I 2026-02-21 06:20:54,761] Trial 104 finished with value: 0.9066629938750361 and parameters: {'layer1': 446, 'layer2': 201, 'layer3': 207, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.2376414746949916e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:10:24<12:15:36, 7356.10s/it]

[I 2026-02-21 06:21:13,495] Trial 105 finished with value: 0.7889420666920989 and parameters: {'layer1': 466, 'layer2': 494, 'layer3': 192, 'activation': 'relu', 'solver': 'adam', 'lr': 4.782894987172345e-06}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:10:54<12:15:36, 7356.10s/it]

[I 2026-02-21 06:21:43,385] Trial 106 finished with value: 0.9060696468386977 and parameters: {'layer1': 367, 'layer2': 177, 'layer3': 476, 'activation': 'tanh', 'solver': 'adam', 'lr': 3.867746531597879e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:11:21<12:15:36, 7356.10s/it]

[I 2026-02-21 06:22:10,688] Trial 107 finished with value: 0.9057691639099248 and parameters: {'layer1': 432, 'layer2': 236, 'layer3': 444, 'activation': 'tanh', 'solver': 'adam', 'lr': 5.002373399870242e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:11:55<12:15:36, 7356.10s/it]

[I 2026-02-21 06:22:44,429] Trial 108 finished with value: 0.9052886277279976 and parameters: {'layer1': 417, 'layer2': 409, 'layer3': 171, 'activation': 'identity', 'solver': 'adam', 'lr': 3.032377095996179e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:12:09<12:15:36, 7356.10s/it]

[I 2026-02-21 06:22:58,050] Trial 109 finished with value: 0.7889420666920989 and parameters: {'layer1': 315, 'layer2': 109, 'layer3': 249, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.1507293679841413e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:12:35<12:15:36, 7356.10s/it]

[I 2026-02-21 06:23:24,426] Trial 110 finished with value: 0.9052958042087846 and parameters: {'layer1': 392, 'layer2': 285, 'layer3': 222, 'activation': 'tanh', 'solver': 'adam', 'lr': 6.268658822878925e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:12:54<12:15:36, 7356.10s/it]

[I 2026-02-21 06:23:42,888] Trial 111 finished with value: 0.8104918877145201 and parameters: {'layer1': 146, 'layer2': 223, 'layer3': 204, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.7382044122424573e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:13:22<12:15:36, 7356.10s/it]

[I 2026-02-21 06:24:11,599] Trial 112 finished with value: 0.9062464395838304 and parameters: {'layer1': 163, 'layer2': 246, 'layer3': 181, 'activation': 'tanh', 'solver': 'adam', 'lr': 3.139857945531769e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:13:44<12:15:36, 7356.10s/it]

[I 2026-02-21 06:24:33,162] Trial 113 finished with value: 0.906918989191617 and parameters: {'layer1': 184, 'layer2': 264, 'layer3': 160, 'activation': 'tanh', 'solver': 'adam', 'lr': 4.681368433898454e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:14:13<12:15:36, 7356.10s/it]

[I 2026-02-21 06:25:02,350] Trial 114 finished with value: 0.9063583914221873 and parameters: {'layer1': 123, 'layer2': 232, 'layer3': 238, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.2506592532955455e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:14:24<12:15:36, 7356.10s/it]

[I 2026-02-21 06:25:12,906] Trial 115 finished with value: 0.1867223768669323 and parameters: {'layer1': 209, 'layer2': 465, 'layer3': 198, 'activation': 'logistic', 'solver': 'sgd', 'lr': 1.4337455239585275e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:15:04<12:15:36, 7356.10s/it]

[I 2026-02-21 06:25:53,082] Trial 116 finished with value: 0.9076898788792604 and parameters: {'layer1': 475, 'layer2': 63, 'layer3': 269, 'activation': 'tanh', 'solver': 'adam', 'lr': 3.326277656261264e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:15:42<12:15:36, 7356.10s/it]

[I 2026-02-21 06:26:31,136] Trial 117 finished with value: 0.9071981475640939 and parameters: {'layer1': 485, 'layer2': 56, 'layer3': 265, 'activation': 'tanh', 'solver': 'adam', 'lr': 3.5794796339906794e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:16:30<12:15:36, 7356.10s/it]

[I 2026-02-21 06:27:19,443] Trial 118 finished with value: 0.9078807890499638 and parameters: {'layer1': 460, 'layer2': 68, 'layer3': 374, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.797461320064641e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:17:19<12:15:36, 7356.10s/it]

[I 2026-02-21 06:28:08,049] Trial 119 finished with value: 0.9061691184506886 and parameters: {'layer1': 472, 'layer2': 67, 'layer3': 327, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.8269595503882538e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:17:57<12:15:36, 7356.10s/it]

[I 2026-02-21 06:28:46,471] Trial 120 finished with value: 0.9083486709729346 and parameters: {'layer1': 491, 'layer2': 83, 'layer3': 364, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.720118503668765e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:18:38<12:15:36, 7356.10s/it]

[I 2026-02-21 06:29:27,280] Trial 121 finished with value: 0.9052336643323846 and parameters: {'layer1': 491, 'layer2': 85, 'layer3': 344, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.658865748861816e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:19:21<12:15:36, 7356.10s/it]

[I 2026-02-21 06:30:10,049] Trial 122 finished with value: 0.9075556388063276 and parameters: {'layer1': 455, 'layer2': 49, 'layer3': 375, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.0947914343333924e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:19:46<12:15:36, 7356.10s/it]

[I 2026-02-21 06:30:35,014] Trial 123 finished with value: 0.8105101722840505 and parameters: {'layer1': 475, 'layer2': 38, 'layer3': 375, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.5028093379753849e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:20:02<12:15:36, 7356.10s/it]

[I 2026-02-21 06:30:50,989] Trial 124 finished with value: 0.7889420666920989 and parameters: {'layer1': 461, 'layer2': 48, 'layer3': 386, 'activation': 'tanh', 'solver': 'adam', 'lr': 9.45357353796191e-06}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:20:34<12:15:36, 7356.10s/it]

[I 2026-02-21 06:31:23,340] Trial 125 finished with value: 0.9055158387441047 and parameters: {'layer1': 482, 'layer2': 27, 'layer3': 418, 'activation': 'tanh', 'solver': 'adam', 'lr': 3.973563586404669e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:21:19<12:15:36, 7356.10s/it]

[I 2026-02-21 06:32:08,378] Trial 126 finished with value: 0.9062492827214473 and parameters: {'layer1': 499, 'layer2': 86, 'layer3': 403, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.945723110977839e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:21:52<12:15:36, 7356.10s/it]

[I 2026-02-21 06:32:40,875] Trial 127 finished with value: 0.9067272457878588 and parameters: {'layer1': 431, 'layer2': 126, 'layer3': 455, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.912492161010079e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:22:08<12:15:36, 7356.10s/it]

[I 2026-02-21 06:32:57,145] Trial 128 finished with value: 0.7889420666920989 and parameters: {'layer1': 446, 'layer2': 69, 'layer3': 287, 'activation': 'relu', 'solver': 'adam', 'lr': 1.128150848157516e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:22:49<12:15:36, 7356.10s/it]

[I 2026-02-21 06:33:37,849] Trial 129 finished with value: 0.9068248738470034 and parameters: {'layer1': 459, 'layer2': 58, 'layer3': 342, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.3192003143228334e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:23:17<12:15:36, 7356.10s/it]

[I 2026-02-21 06:34:06,157] Trial 130 finished with value: 0.9073397661414779 and parameters: {'layer1': 472, 'layer2': 137, 'layer3': 356, 'activation': 'tanh', 'solver': 'adam', 'lr': 5.832094519749282e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:23:49<12:15:36, 7356.10s/it]

[I 2026-02-21 06:34:38,263] Trial 131 finished with value: 0.9066408825600929 and parameters: {'layer1': 475, 'layer2': 90, 'layer3': 358, 'activation': 'tanh', 'solver': 'adam', 'lr': 4.868100060393156e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:24:19<12:15:36, 7356.10s/it]

[I 2026-02-21 06:35:08,123] Trial 132 finished with value: 0.905907824622834 and parameters: {'layer1': 491, 'layer2': 115, 'layer3': 385, 'activation': 'tanh', 'solver': 'adam', 'lr': 5.8270970169450394e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:24:51<12:15:36, 7356.10s/it]

[I 2026-02-21 06:35:40,193] Trial 133 finished with value: 0.9071060759907793 and parameters: {'layer1': 468, 'layer2': 141, 'layer3': 372, 'activation': 'tanh', 'solver': 'adam', 'lr': 3.5087579003312273e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:25:26<12:15:36, 7356.10s/it]

[I 2026-02-21 06:36:14,987] Trial 134 finished with value: 0.9060672175768179 and parameters: {'layer1': 458, 'layer2': 21, 'layer3': 321, 'activation': 'tanh', 'solver': 'adam', 'lr': 4.2218857772886304e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:25:54<12:15:36, 7356.10s/it]

[I 2026-02-21 06:36:42,893] Trial 135 finished with value: 0.9061616004541045 and parameters: {'layer1': 483, 'layer2': 76, 'layer3': 401, 'activation': 'tanh', 'solver': 'adam', 'lr': 8.074026971820024e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:26:34<12:15:36, 7356.10s/it]

[I 2026-02-21 06:37:23,036] Trial 136 finished with value: 0.9059022836796604 and parameters: {'layer1': 446, 'layer2': 69, 'layer3': 351, 'activation': 'identity', 'solver': 'adam', 'lr': 2.895410834389564e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:27:04<12:15:36, 7356.10s/it]

[I 2026-02-21 06:37:53,027] Trial 137 finished with value: 0.789069413496474 and parameters: {'layer1': 417, 'layer2': 103, 'layer3': 437, 'activation': 'tanh', 'solver': 'sgd', 'lr': 1.6796917011738387e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:27:13<12:15:36, 7356.10s/it]

[I 2026-02-21 06:38:02,112] Trial 138 finished with value: 0.7900112849595142 and parameters: {'layer1': 29, 'layer2': 51, 'layer3': 333, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.3657905490984935e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:27:43<12:15:36, 7356.10s/it]

[I 2026-02-21 06:38:32,187] Trial 139 finished with value: 0.9059169343987016 and parameters: {'layer1': 494, 'layer2': 210, 'layer3': 312, 'activation': 'tanh', 'solver': 'adam', 'lr': 6.81045504442719e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:28:00<12:15:36, 7356.10s/it]

[I 2026-02-21 06:38:49,631] Trial 140 finished with value: 0.7889420666920989 and parameters: {'layer1': 475, 'layer2': 39, 'layer3': 364, 'activation': 'logistic', 'solver': 'adam', 'lr': 2.114073751757726e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:28:41<12:15:36, 7356.10s/it]

[I 2026-02-21 06:39:29,981] Trial 141 finished with value: 0.908017238261692 and parameters: {'layer1': 452, 'layer2': 62, 'layer3': 384, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.362856760440571e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:29:22<12:15:36, 7356.10s/it]

[I 2026-02-21 06:40:11,323] Trial 142 finished with value: 0.9074794343518612 and parameters: {'layer1': 452, 'layer2': 63, 'layer3': 387, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.5918884682317158e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:29:59<12:15:36, 7356.10s/it]

[I 2026-02-21 06:40:47,891] Trial 143 finished with value: 0.9078990319658592 and parameters: {'layer1': 432, 'layer2': 62, 'layer3': 393, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.5216072627085814e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:30:38<12:15:36, 7356.10s/it]

[I 2026-02-21 06:41:27,177] Trial 144 finished with value: 0.9067611347858326 and parameters: {'layer1': 430, 'layer2': 65, 'layer3': 401, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.7143755773266528e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:31:17<12:15:36, 7356.10s/it]

[I 2026-02-21 06:42:05,899] Trial 145 finished with value: 0.90645460024842 and parameters: {'layer1': 450, 'layer2': 59, 'layer3': 386, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.409757263916272e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:31:57<12:15:36, 7356.10s/it]

[I 2026-02-21 06:42:46,106] Trial 146 finished with value: 0.9068706457868296 and parameters: {'layer1': 436, 'layer2': 45, 'layer3': 381, 'activation': 'tanh', 'solver': 'adam', 'lr': 3.2723536569754345e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:32:33<12:15:36, 7356.10s/it]

[I 2026-02-21 06:43:22,753] Trial 147 finished with value: 0.8570923271090625 and parameters: {'layer1': 407, 'layer2': 34, 'layer3': 427, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.8861297449734214e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:33:09<12:15:36, 7356.10s/it]

[I 2026-02-21 06:43:58,515] Trial 148 finished with value: 0.857336373399703 and parameters: {'layer1': 379, 'layer2': 77, 'layer3': 367, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.5823986634739045e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:33:43<12:15:36, 7356.10s/it]

[I 2026-02-21 06:44:32,551] Trial 149 finished with value: 0.9081110368556404 and parameters: {'layer1': 423, 'layer2': 93, 'layer3': 467, 'activation': 'tanh', 'solver': 'adam', 'lr': 3.7721568274337404e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:34:12<12:15:36, 7356.10s/it]

[I 2026-02-21 06:45:01,598] Trial 150 finished with value: 0.9072333429126649 and parameters: {'layer1': 423, 'layer2': 95, 'layer3': 484, 'activation': 'tanh', 'solver': 'adam', 'lr': 3.9275218446240635e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:34:48<12:15:36, 7356.10s/it]

[I 2026-02-21 06:45:37,061] Trial 151 finished with value: 0.9089389665791066 and parameters: {'layer1': 441, 'layer2': 80, 'layer3': 499, 'activation': 'tanh', 'solver': 'adam', 'lr': 3.022246362385281e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:35:26<12:15:36, 7356.10s/it]

[I 2026-02-21 06:46:15,819] Trial 152 finished with value: 0.9068126525106257 and parameters: {'layer1': 440, 'layer2': 78, 'layer3': 499, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.8121122167481122e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:36:07<12:15:36, 7356.10s/it]

[I 2026-02-21 06:46:56,254] Trial 153 finished with value: 0.9091226699083972 and parameters: {'layer1': 454, 'layer2': 91, 'layer3': 470, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.44053166709477e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:36:42<12:15:36, 7356.10s/it]

[I 2026-02-21 06:47:31,449] Trial 154 finished with value: 0.9035973603041347 and parameters: {'layer1': 416, 'layer2': 96, 'layer3': 462, 'activation': 'tanh', 'solver': 'adam', 'lr': 3.366896393996275e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:37:13<12:15:36, 7356.10s/it]

[I 2026-02-21 06:48:02,045] Trial 155 finished with value: 0.9068270345523656 and parameters: {'layer1': 460, 'layer2': 106, 'layer3': 469, 'activation': 'tanh', 'solver': 'adam', 'lr': 4.519743115050259e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:37:59<12:15:36, 7356.10s/it]

[I 2026-02-21 06:48:48,354] Trial 156 finished with value: 0.9074102589490171 and parameters: {'layer1': 429, 'layer2': 50, 'layer3': 476, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.102513066457741e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:38:24<12:15:36, 7356.10s/it]

[I 2026-02-21 06:49:13,448] Trial 157 finished with value: 0.8104918877145201 and parameters: {'layer1': 443, 'layer2': 87, 'layer3': 493, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.2339426106376339e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:39:06<12:15:36, 7356.10s/it]

[I 2026-02-21 06:49:55,094] Trial 158 finished with value: 0.9070458752424526 and parameters: {'layer1': 403, 'layer2': 79, 'layer3': 485, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.8039399705535005e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:39:51<12:15:36, 7356.10s/it]

[I 2026-02-21 06:50:40,438] Trial 159 finished with value: 0.8854696532626587 and parameters: {'layer1': 468, 'layer2': 120, 'layer3': 453, 'activation': 'relu', 'solver': 'adam', 'lr': 2.4037225848516254e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:40:30<12:15:36, 7356.10s/it]

[I 2026-02-21 06:51:19,029] Trial 160 finished with value: 0.9064558276162547 and parameters: {'layer1': 486, 'layer2': 91, 'layer3': 489, 'activation': 'tanh', 'solver': 'adam', 'lr': 3.793212036204424e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:41:13<12:15:36, 7356.10s/it]

[I 2026-02-21 06:52:02,373] Trial 161 finished with value: 0.9090745292625941 and parameters: {'layer1': 454, 'layer2': 63, 'layer3': 391, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.5542776284244108e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:41:49<12:15:36, 7356.10s/it]

[I 2026-02-21 06:52:38,581] Trial 162 finished with value: 0.9065959118798897 and parameters: {'layer1': 449, 'layer2': 72, 'layer3': 466, 'activation': 'tanh', 'solver': 'adam', 'lr': 3.068221559591222e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:42:41<12:15:36, 7356.10s/it]

[I 2026-02-21 06:53:30,657] Trial 163 finished with value: 0.9093969953482945 and parameters: {'layer1': 457, 'layer2': 59, 'layer3': 476, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.558065009502256e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:43:38<12:15:36, 7356.10s/it]

[I 2026-02-21 06:54:27,103] Trial 164 finished with value: 0.9094463717387145 and parameters: {'layer1': 461, 'layer2': 61, 'layer3': 475, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.54717149897868e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:43:53<12:15:36, 7356.10s/it]

[I 2026-02-21 06:54:42,389] Trial 165 finished with value: 0.7889420666920989 and parameters: {'layer1': 436, 'layer2': 19, 'layer3': 475, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.3825428819746257e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:44:36<12:15:36, 7356.10s/it]

[I 2026-02-21 06:55:25,051] Trial 166 finished with value: 0.7924607060774873 and parameters: {'layer1': 463, 'layer2': 79, 'layer3': 440, 'activation': 'tanh', 'solver': 'sgd', 'lr': 1.0788013518687869e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:45:07<12:15:36, 7356.10s/it]

[I 2026-02-21 06:55:55,862] Trial 167 finished with value: 0.8326339958759599 and parameters: {'layer1': 349, 'layer2': 62, 'layer3': 499, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.4441052444541685e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:45:22<12:15:36, 7356.10s/it]

[I 2026-02-21 06:56:11,504] Trial 168 finished with value: 0.7889420666920989 and parameters: {'layer1': 425, 'layer2': 96, 'layer3': 480, 'activation': 'identity', 'solver': 'adam', 'lr': 8.509901019811212e-06}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:45:57<12:15:36, 7356.10s/it]

[I 2026-02-21 06:56:46,209] Trial 169 finished with value: 0.8562627786807984 and parameters: {'layer1': 441, 'layer2': 54, 'layer3': 428, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.7096823163371295e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:46:38<12:15:36, 7356.10s/it]

[I 2026-02-21 06:57:27,042] Trial 170 finished with value: 0.9068776438016182 and parameters: {'layer1': 396, 'layer2': 40, 'layer3': 467, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.1896093763641594e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:47:18<12:15:36, 7356.10s/it]

[I 2026-02-21 06:58:07,424] Trial 171 finished with value: 0.9076696550830118 and parameters: {'layer1': 473, 'layer2': 71, 'layer3': 460, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.6364388751728793e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:47:55<12:15:36, 7356.10s/it]

[I 2026-02-21 06:58:44,558] Trial 172 finished with value: 0.9070164949145761 and parameters: {'layer1': 455, 'layer2': 61, 'layer3': 491, 'activation': 'tanh', 'solver': 'adam', 'lr': 3.118159922282385e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:48:40<12:15:36, 7356.10s/it]

[I 2026-02-21 06:59:28,922] Trial 173 finished with value: 0.9079267972871612 and parameters: {'layer1': 465, 'layer2': 83, 'layer3': 451, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.8013767243588366e-05}. Best is trial 22 with value: 0.909723623918263.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:49:26<12:15:36, 7356.10s/it]

[I 2026-02-21 07:00:15,202] Trial 174 finished with value: 0.9097268823380917 and parameters: {'layer1': 500, 'layer2': 404, 'layer3': 477, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.6700959479842555e-05}. Best is trial 174 with value: 0.9097268823380917.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:49:45<12:15:36, 7356.10s/it]

[I 2026-02-21 07:00:34,280] Trial 175 finished with value: 0.7889420666920989 and parameters: {'layer1': 497, 'layer2': 404, 'layer3': 473, 'activation': 'tanh', 'solver': 'adam', 'lr': 7.082562961195053e-06}. Best is trial 174 with value: 0.9097268823380917.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:50:42<12:15:36, 7356.10s/it]

[I 2026-02-21 07:01:31,604] Trial 176 finished with value: 0.9076637773020074 and parameters: {'layer1': 484, 'layer2': 366, 'layer3': 481, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.2538609520540512e-05}. Best is trial 174 with value: 0.9097268823380917.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:51:29<12:15:36, 7356.10s/it]

[I 2026-02-21 07:02:18,648] Trial 177 finished with value: 0.907810601844371 and parameters: {'layer1': 466, 'layer2': 82, 'layer3': 452, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.6122711626201013e-05}. Best is trial 174 with value: 0.9097268823380917.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:52:12<12:15:36, 7356.10s/it]

[I 2026-02-21 07:03:01,084] Trial 178 finished with value: 0.9062344655726333 and parameters: {'layer1': 499, 'layer2': 453, 'layer3': 458, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.9563791101318015e-05}. Best is trial 174 with value: 0.9097268823380917.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:52:52<12:15:36, 7356.10s/it]

[I 2026-02-21 07:03:41,835] Trial 179 finished with value: 0.9062834006305183 and parameters: {'layer1': 489, 'layer2': 499, 'layer3': 447, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.406592823118479e-05}. Best is trial 174 with value: 0.9097268823380917.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:53:11<12:15:36, 7356.10s/it]

[I 2026-02-21 07:04:00,468] Trial 180 finished with value: 0.7889420666920989 and parameters: {'layer1': 461, 'layer2': 163, 'layer3': 395, 'activation': 'logistic', 'solver': 'adam', 'lr': 1.0578427409697103e-05}. Best is trial 174 with value: 0.9097268823380917.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:53:57<12:15:36, 7356.10s/it]

[I 2026-02-21 07:04:46,431] Trial 181 finished with value: 0.9067796765425991 and parameters: {'layer1': 452, 'layer2': 394, 'layer3': 488, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.6575794577565033e-05}. Best is trial 174 with value: 0.9097268823380917.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:54:40<12:15:36, 7356.10s/it]

[I 2026-02-21 07:05:29,528] Trial 182 finished with value: 0.9069967587198967 and parameters: {'layer1': 443, 'layer2': 430, 'layer3': 476, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.9112174089647113e-05}. Best is trial 174 with value: 0.9097268823380917.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:55:19<12:15:36, 7356.10s/it]

[I 2026-02-21 07:06:08,339] Trial 183 finished with value: 0.9074341418965286 and parameters: {'layer1': 482, 'layer2': 86, 'layer3': 467, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.478975676511159e-05}. Best is trial 174 with value: 0.9097268823380917.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:56:05<12:15:36, 7356.10s/it]

[I 2026-02-21 07:06:54,431] Trial 184 finished with value: 0.9052215423201844 and parameters: {'layer1': 413, 'layer2': 466, 'layer3': 410, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.5038911554778812e-05}. Best is trial 174 with value: 0.9097268823380917.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:56:37<12:15:36, 7356.10s/it]

[I 2026-02-21 07:07:26,597] Trial 185 finished with value: 0.906751878773429 and parameters: {'layer1': 427, 'layer2': 340, 'layer3': 485, 'activation': 'tanh', 'solver': 'adam', 'lr': 3.0278062257682117e-05}. Best is trial 174 with value: 0.9097268823380917.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:57:14<12:15:36, 7356.10s/it]

[I 2026-02-21 07:08:02,952] Trial 186 finished with value: 0.8326537354384922 and parameters: {'layer1': 468, 'layer2': 111, 'layer3': 494, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.273098676992588e-05}. Best is trial 174 with value: 0.9097268823380917.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:57:55<12:15:36, 7356.10s/it]

[I 2026-02-21 07:08:44,341] Trial 187 finished with value: 0.9068261018094914 and parameters: {'layer1': 478, 'layer2': 70, 'layer3': 434, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.094234940038763e-05}. Best is trial 174 with value: 0.9097268823380917.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:58:27<12:15:36, 7356.10s/it]

[I 2026-02-21 07:09:16,446] Trial 188 finished with value: 0.9047078717101362 and parameters: {'layer1': 449, 'layer2': 476, 'layer3': 500, 'activation': 'tanh', 'solver': 'adam', 'lr': 3.9209512361226596e-05}. Best is trial 174 with value: 0.9097268823380917.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:59:05<12:15:36, 7356.10s/it]

[I 2026-02-21 07:09:54,017] Trial 189 finished with value: 0.9063162683177561 and parameters: {'layer1': 462, 'layer2': 56, 'layer3': 462, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.713444848504923e-05}. Best is trial 174 with value: 0.9097268823380917.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [19:59:33<12:15:36, 7356.10s/it]

[I 2026-02-21 07:10:22,688] Trial 190 finished with value: 0.9049079827420131 and parameters: {'layer1': 436, 'layer2': 101, 'layer3': 394, 'activation': 'tanh', 'solver': 'adam', 'lr': 4.841525795388331e-05}. Best is trial 174 with value: 0.9097268823380917.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [20:00:17<12:15:36, 7356.10s/it]

[I 2026-02-21 07:11:06,280] Trial 191 finished with value: 0.9076624134853329 and parameters: {'layer1': 464, 'layer2': 82, 'layer3': 445, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.7364841832780065e-05}. Best is trial 174 with value: 0.9097268823380917.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [20:01:05<12:15:36, 7356.10s/it]

[I 2026-02-21 07:11:54,551] Trial 192 finished with value: 0.9085406478290908 and parameters: {'layer1': 473, 'layer2': 88, 'layer3': 458, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.5375702378505845e-05}. Best is trial 174 with value: 0.9097268823380917.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [20:01:22<12:15:36, 7356.10s/it]

[I 2026-02-21 07:12:11,788] Trial 193 finished with value: 0.7889420666920989 and parameters: {'layer1': 490, 'layer2': 91, 'layer3': 474, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.0007547635989537e-05}. Best is trial 174 with value: 0.9097268823380917.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [20:02:04<12:15:36, 7356.10s/it]

[I 2026-02-21 07:12:53,343] Trial 194 finished with value: 0.8569313332830347 and parameters: {'layer1': 475, 'layer2': 72, 'layer3': 423, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.3931221638639048e-05}. Best is trial 174 with value: 0.9097268823380917.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [20:02:48<12:15:36, 7356.10s/it]

[I 2026-02-21 07:13:37,401] Trial 195 finished with value: 0.9081171797597497 and parameters: {'layer1': 452, 'layer2': 47, 'layer3': 455, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.0292858907891714e-05}. Best is trial 174 with value: 0.9097268823380917.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [20:03:14<12:15:36, 7356.10s/it]

[I 2026-02-21 07:14:03,828] Trial 196 finished with value: 0.810892420435866 and parameters: {'layer1': 453, 'layer2': 45, 'layer3': 455, 'activation': 'relu', 'solver': 'adam', 'lr': 2.264403438587659e-05}. Best is trial 174 with value: 0.9097268823380917.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [20:03:32<12:15:36, 7356.10s/it]

[I 2026-02-21 07:14:20,856] Trial 197 finished with value: 0.7927007882984368 and parameters: {'layer1': 500, 'layer2': 53, 'layer3': 448, 'activation': 'tanh', 'solver': 'sgd', 'lr': 3.547759788423099e-05}. Best is trial 174 with value: 0.9097268823380917.

Training Exact MLP (Paper):  57%|█████▋    | 8/14 [20:04:13<12:15:36, 7356.10s/it]

[I 2026-02-21 07:15:02,837] Trial 198 finished with value: 0.9077573257327274 and parameters: {'layer1': 481, 'layer2': 69, 'layer3': 468, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.4422722483845988e-05}. Best is trial 174 with value: 0.9097268823380917.

Best trial: 174. Best value: 0.909727: 100%|██████████| 200/200 [1:40:22<00:00, 30.11s/it]

[I 2026-02-21 07:15:30,020] Trial 199 finished with value: 0.8341499954330065 and parameters: {'layer1': 444, 'layer2': 29, 'layer3': 458, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.922102609040448e-05}. Best is trial 174 with value: 0.9097268823380917.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:04:42<9:38:17, 6939.53s/it] [I 2026-02-21 07:15:31,541] A new study created in memory with name: no-name-27992aed-f6a7-4387-95d4-925cc35d890b

  → Best model saved.

[Exact Paper MLP] Klebsiella_Pneumoniae | Imipenem

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:05:13<9:38:17, 6939.53s/it]

[I 2026-02-21 07:16:02,367] Trial 0 finished with value: 0.9884764126703607 and parameters: {'layer1': 450, 'layer2': 341, 'layer3': 285, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0009694691494334295}. Best is trial 0 with value: 0.9884764126703607.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:05:26<9:38:17, 6939.53s/it]

[I 2026-02-21 07:16:15,290] Trial 1 finished with value: 0.9845981377851871 and parameters: {'layer1': 185, 'layer2': 474, 'layer3': 234, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0004900934196037811}. Best is trial 0 with value: 0.9884764126703607.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:05:38<9:38:17, 6939.53s/it]

[I 2026-02-21 07:16:27,129] Trial 2 finished with value: 0.7879970454928468 and parameters: {'layer1': 406, 'layer2': 225, 'layer3': 401, 'activation': 'logistic', 'solver': 'sgd', 'lr': 2.6295140806804625e-06}. Best is trial 0 with value: 0.9884764126703607.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:05:51<9:38:17, 6939.53s/it]

[I 2026-02-21 07:16:40,336] Trial 3 finished with value: 0.9880920438844049 and parameters: {'layer1': 162, 'layer2': 200, 'layer3': 324, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0009356297854874672}. Best is trial 0 with value: 0.9884764126703607.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:06:04<9:38:17, 6939.53s/it]

[I 2026-02-21 07:16:53,310] Trial 4 finished with value: 0.9845981377851871 and parameters: {'layer1': 168, 'layer2': 362, 'layer3': 329, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.005569640373262855}. Best is trial 0 with value: 0.9884764126703607.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:06:13<9:38:17, 6939.53s/it]

[I 2026-02-21 07:17:02,089] Trial 5 finished with value: 0.9845981377851871 and parameters: {'layer1': 46, 'layer2': 32, 'layer3': 499, 'activation': 'identity', 'solver': 'adam', 'lr': 6.356191230830388e-06}. Best is trial 0 with value: 0.9884764126703607.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:06:25<9:38:17, 6939.53s/it]

[I 2026-02-21 07:17:14,785] Trial 6 finished with value: 0.9845981377851871 and parameters: {'layer1': 408, 'layer2': 82, 'layer3': 212, 'activation': 'relu', 'solver': 'sgd', 'lr': 0.0016237141314862514}. Best is trial 0 with value: 0.9884764126703607.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:06:51<9:38:17, 6939.53s/it]

[I 2026-02-21 07:17:40,238] Trial 7 finished with value: 0.9845981377851871 and parameters: {'layer1': 221, 'layer2': 317, 'layer3': 113, 'activation': 'identity', 'solver': 'sgd', 'lr': 1.38921589555787e-05}. Best is trial 0 with value: 0.9884764126703607.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:07:02<9:38:17, 6939.53s/it]

[I 2026-02-21 07:17:51,207] Trial 8 finished with value: 0.9845981377851871 and parameters: {'layer1': 166, 'layer2': 34, 'layer3': 154, 'activation': 'relu', 'solver': 'adam', 'lr': 1.2820962982789158e-05}. Best is trial 0 with value: 0.9884764126703607.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:07:16<9:38:17, 6939.53s/it]

[I 2026-02-21 07:18:05,042] Trial 9 finished with value: 0.9845981377851871 and parameters: {'layer1': 451, 'layer2': 480, 'layer3': 280, 'activation': 'logistic', 'solver': 'sgd', 'lr': 0.0008085478579210511}. Best is trial 0 with value: 0.9884764126703607.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:07:31<9:38:17, 6939.53s/it]

[I 2026-02-21 07:18:20,709] Trial 10 finished with value: 0.9845981377851871 and parameters: {'layer1': 325, 'layer2': 382, 'layer3': 58, 'activation': 'tanh', 'solver': 'adam', 'lr': 8.870084505912252e-05}. Best is trial 0 with value: 0.9884764126703607.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:07:45<9:38:17, 6939.53s/it]

[I 2026-02-21 07:18:34,842] Trial 11 finished with value: 0.9871270321656478 and parameters: {'layer1': 68, 'layer2': 194, 'layer3': 357, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.00018808722296363822}. Best is trial 0 with value: 0.9884764126703607.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:08:05<9:38:17, 6939.53s/it]

[I 2026-02-21 07:18:54,828] Trial 12 finished with value: 0.9886803174790864 and parameters: {'layer1': 298, 'layer2': 145, 'layer3': 444, 'activation': 'identity', 'solver': 'adam', 'lr': 0.007364527017237939}. Best is trial 12 with value: 0.9886803174790864.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:08:20<9:38:17, 6939.53s/it]

[I 2026-02-21 07:19:09,756] Trial 13 finished with value: 0.9845981377851871 and parameters: {'layer1': 324, 'layer2': 129, 'layer3': 483, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.006986421951861143}. Best is trial 12 with value: 0.9886803174790864.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:08:49<9:38:17, 6939.53s/it]

[I 2026-02-21 07:19:38,598] Trial 14 finished with value: 0.9880920438844049 and parameters: {'layer1': 486, 'layer2': 288, 'layer3': 405, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0032007580161138604}. Best is trial 12 with value: 0.9886803174790864.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:09:03<9:38:17, 6939.53s/it]

[I 2026-02-21 07:19:52,512] Trial 15 finished with value: 0.9845981377851871 and parameters: {'layer1': 307, 'layer2': 143, 'layer3': 433, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.009678025677026697}. Best is trial 12 with value: 0.9886803174790864.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:09:18<9:38:17, 6939.53s/it]

[I 2026-02-21 07:20:07,545] Trial 16 finished with value: 0.9845981377851871 and parameters: {'layer1': 385, 'layer2': 404, 'layer3': 23, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0001832670572548805}. Best is trial 12 with value: 0.9886803174790864.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:09:38<9:38:17, 6939.53s/it]

[I 2026-02-21 07:20:26,990] Trial 17 finished with value: 0.9880920438844049 and parameters: {'layer1': 267, 'layer2': 256, 'layer3': 180, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0024645893492655576}. Best is trial 12 with value: 0.9886803174790864.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:10:10<9:38:17, 6939.53s/it]

[I 2026-02-21 07:20:59,583] Trial 18 finished with value: 0.787310426229376 and parameters: {'layer1': 486, 'layer2': 327, 'layer3': 254, 'activation': 'relu', 'solver': 'sgd', 'lr': 6.515129792240854e-05}. Best is trial 12 with value: 0.9886803174790864.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:10:32<9:38:17, 6939.53s/it]

[I 2026-02-21 07:21:21,834] Trial 19 finished with value: 0.9880920438844049 and parameters: {'layer1': 379, 'layer2': 144, 'layer3': 445, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.00036305011569884603}. Best is trial 12 with value: 0.9886803174790864.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:10:46<9:38:17, 6939.53s/it]

[I 2026-02-21 07:21:34,926] Trial 20 finished with value: 0.9880920438844049 and parameters: {'layer1': 103, 'layer2': 424, 'layer3': 362, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0017881936389389024}. Best is trial 12 with value: 0.9886803174790864.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:11:02<9:38:17, 6939.53s/it]

[I 2026-02-21 07:21:51,158] Trial 21 finished with value: 0.9881140908847623 and parameters: {'layer1': 251, 'layer2': 194, 'layer3': 304, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0010882579368666119}. Best is trial 12 with value: 0.9886803174790864.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:11:22<9:38:17, 6939.53s/it]

[I 2026-02-21 07:22:11,533] Trial 22 finished with value: 0.9891899250887081 and parameters: {'layer1': 260, 'layer2': 264, 'layer3': 295, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0035090818903716734}. Best is trial 22 with value: 0.9891899250887081.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:11:44<9:38:17, 6939.53s/it]

[I 2026-02-21 07:22:33,481] Trial 23 finished with value: 0.9880920438844049 and parameters: {'layer1': 279, 'layer2': 270, 'layer3': 288, 'activation': 'identity', 'solver': 'adam', 'lr': 0.003857665442796721}. Best is trial 22 with value: 0.9891899250887081.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:12:03<9:38:17, 6939.53s/it]

[I 2026-02-21 07:22:52,441] Trial 24 finished with value: 0.9884353208550666 and parameters: {'layer1': 354, 'layer2': 330, 'layer3': 383, 'activation': 'identity', 'solver': 'adam', 'lr': 0.009870052356328055}. Best is trial 22 with value: 0.9891899250887081.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:12:20<9:38:17, 6939.53s/it]

[I 2026-02-21 07:23:08,962] Trial 25 finished with value: 0.9880920438844049 and parameters: {'layer1': 231, 'layer2': 231, 'layer3': 185, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0026821931136637245}. Best is trial 22 with value: 0.9891899250887081.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:12:31<9:38:17, 6939.53s/it]

[I 2026-02-21 07:23:20,355] Trial 26 finished with value: 0.9845981377851871 and parameters: {'layer1': 427, 'layer2': 96, 'layer3': 455, 'activation': 'tanh', 'solver': 'sgd', 'lr': 0.00047392827917661605}. Best is trial 22 with value: 0.9891899250887081.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:12:47<9:38:17, 6939.53s/it]

[I 2026-02-21 07:23:35,981] Trial 27 finished with value: 0.9845981377851871 and parameters: {'layer1': 349, 'layer2': 299, 'layer3': 115, 'activation': 'relu', 'solver': 'adam', 'lr': 4.545371555901579e-05}. Best is trial 22 with value: 0.9891899250887081.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:12:59<9:38:17, 6939.53s/it]

[I 2026-02-21 07:23:48,794] Trial 28 finished with value: 0.9884353208550666 and parameters: {'layer1': 127, 'layer2': 175, 'layer3': 256, 'activation': 'identity', 'solver': 'adam', 'lr': 0.003945891260072634}. Best is trial 22 with value: 0.9891899250887081.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:13:13<9:38:17, 6939.53s/it]

[I 2026-02-21 07:24:02,556] Trial 29 finished with value: 0.9845981377851871 and parameters: {'layer1': 213, 'layer2': 350, 'layer3': 235, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0003853091837342499}. Best is trial 22 with value: 0.9891899250887081.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:13:34<9:38:17, 6939.53s/it]

[I 2026-02-21 07:24:23,612] Trial 30 finished with value: 0.9893731611697072 and parameters: {'layer1': 291, 'layer2': 439, 'layer3': 350, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.00107495641834021}. Best is trial 30 with value: 0.9893731611697072.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:13:56<9:38:17, 6939.53s/it]

[I 2026-02-21 07:24:45,699] Trial 31 finished with value: 0.9888686951184038 and parameters: {'layer1': 294, 'layer2': 445, 'layer3': 341, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0008595537465927884}. Best is trial 30 with value: 0.9893731611697072.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:14:14<9:38:17, 6939.53s/it]

[I 2026-02-21 07:25:03,740] Trial 32 finished with value: 0.9874703091363095 and parameters: {'layer1': 290, 'layer2': 436, 'layer3': 354, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.001483664744785545}. Best is trial 30 with value: 0.9893731611697072.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:14:33<9:38:17, 6939.53s/it]

[I 2026-02-21 07:25:22,308] Trial 33 finished with value: 0.9890298841990456 and parameters: {'layer1': 249, 'layer2': 496, 'layer3': 411, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0007839053882963538}. Best is trial 30 with value: 0.9893731611697072.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:14:52<9:38:17, 6939.53s/it]

[I 2026-02-21 07:25:40,973] Trial 34 finished with value: 0.9880920438844049 and parameters: {'layer1': 200, 'layer2': 456, 'layer3': 400, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.00022397464389918768}. Best is trial 30 with value: 0.9893731611697072.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:15:15<9:38:17, 6939.53s/it]

[I 2026-02-21 07:26:04,484] Trial 35 finished with value: 0.990880689195178 and parameters: {'layer1': 244, 'layer2': 491, 'layer3': 320, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0007965612347331581}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:15:30<9:38:17, 6939.53s/it]

[I 2026-02-21 07:26:19,576] Trial 36 finished with value: 0.9845981377851871 and parameters: {'layer1': 244, 'layer2': 478, 'layer3': 317, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.148291138478218e-06}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:15:40<9:38:17, 6939.53s/it]

[I 2026-02-21 07:26:29,310] Trial 37 finished with value: 0.9845981377851871 and parameters: {'layer1': 184, 'layer2': 490, 'layer3': 383, 'activation': 'tanh', 'solver': 'sgd', 'lr': 0.0006828628645230628}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:15:58<9:38:17, 6939.53s/it]

[I 2026-02-21 07:26:47,323] Trial 38 finished with value: 0.98776229051088 and parameters: {'layer1': 136, 'layer2': 396, 'layer3': 288, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0002652652871674603}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:16:19<9:38:17, 6939.53s/it]

[I 2026-02-21 07:27:08,706] Trial 39 finished with value: 0.9871270321656478 and parameters: {'layer1': 257, 'layer2': 493, 'layer3': 420, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0014679940221606835}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:16:29<9:38:17, 6939.53s/it]

[I 2026-02-21 07:27:18,637] Trial 40 finished with value: 0.9845981377851871 and parameters: {'layer1': 186, 'layer2': 462, 'layer3': 383, 'activation': 'tanh', 'solver': 'sgd', 'lr': 0.0006012999995784977}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:16:52<9:38:17, 6939.53s/it]

[I 2026-02-21 07:27:41,520] Trial 41 finished with value: 0.9897431830776504 and parameters: {'layer1': 275, 'layer2': 428, 'layer3': 328, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0009978071698507136}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:17:11<9:38:17, 6939.53s/it]

[I 2026-02-21 07:28:00,378] Trial 42 finished with value: 0.986532468821669 and parameters: {'layer1': 233, 'layer2': 421, 'layer3': 329, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0021653938281149744}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:17:26<9:38:17, 6939.53s/it]

[I 2026-02-21 07:28:15,780] Trial 43 finished with value: 0.9845981377851871 and parameters: {'layer1': 328, 'layer2': 374, 'layer3': 309, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.00483534738022318}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:17:51<9:38:17, 6939.53s/it]

[I 2026-02-21 07:28:40,513] Trial 44 finished with value: 0.9897431830776504 and parameters: {'layer1': 272, 'layer2': 498, 'layer3': 255, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0011743060150636486}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:18:10<9:38:17, 6939.53s/it]

[I 2026-02-21 07:28:59,010] Trial 45 finished with value: 0.9874703091363095 and parameters: {'layer1': 278, 'layer2': 457, 'layer3': 269, 'activation': 'relu', 'solver': 'adam', 'lr': 0.001217128117673396}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:18:23<9:38:17, 6939.53s/it]

[I 2026-02-21 07:29:11,982] Trial 46 finished with value: 0.9845981377851871 and parameters: {'layer1': 218, 'layer2': 409, 'layer3': 212, 'activation': 'tanh', 'solver': 'adam', 'lr': 3.1491533524637434e-05}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:18:37<9:38:17, 6939.53s/it]

[I 2026-02-21 07:29:26,789] Trial 47 finished with value: 0.9845981377851871 and parameters: {'layer1': 311, 'layer2': 433, 'layer3': 234, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.00014846912469911193}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:18:50<9:38:17, 6939.53s/it]

[I 2026-02-21 07:29:39,636] Trial 48 finished with value: 0.9852348116796092 and parameters: {'layer1': 345, 'layer2': 385, 'layer3': 299, 'activation': 'tanh', 'solver': 'sgd', 'lr': 0.0001245209263023959}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:19:00<9:38:17, 6939.53s/it]

[I 2026-02-21 07:29:48,865] Trial 49 finished with value: 0.9845981377851871 and parameters: {'layer1': 19, 'layer2': 472, 'layer3': 335, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.005774129967529307}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:19:20<9:38:17, 6939.53s/it]

[I 2026-02-21 07:30:09,275] Trial 50 finished with value: 0.9880920438844049 and parameters: {'layer1': 268, 'layer2': 358, 'layer3': 262, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.00029825678599365005}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:19:40<9:38:17, 6939.53s/it]

[I 2026-02-21 07:30:28,862] Trial 51 finished with value: 0.988948436537872 and parameters: {'layer1': 244, 'layer2': 499, 'layer3': 362, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.00056496759951851}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:20:00<9:38:17, 6939.53s/it]

[I 2026-02-21 07:30:49,428] Trial 52 finished with value: 0.9901277654033487 and parameters: {'layer1': 202, 'layer2': 499, 'layer3': 344, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0009830674110980488}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:20:23<9:38:17, 6939.53s/it]

[I 2026-02-21 07:31:11,957] Trial 53 finished with value: 0.9890247891237702 and parameters: {'layer1': 202, 'layer2': 473, 'layer3': 319, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.001218660438375983}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:20:37<9:38:17, 6939.53s/it]

[I 2026-02-21 07:31:26,474] Trial 54 finished with value: 0.9851927011291661 and parameters: {'layer1': 151, 'layer2': 448, 'layer3': 347, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.002243768757698164}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:20:56<9:38:17, 6939.53s/it]

[I 2026-02-21 07:31:45,585] Trial 55 finished with value: 0.9880916120329098 and parameters: {'layer1': 314, 'layer2': 407, 'layer3': 277, 'activation': 'relu', 'solver': 'adam', 'lr': 0.003385799060462643}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:21:11<9:38:17, 6939.53s/it]

[I 2026-02-21 07:32:00,768] Trial 56 finished with value: 0.9845981377851871 and parameters: {'layer1': 274, 'layer2': 472, 'layer3': 218, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.001937714360837323}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:21:28<9:38:17, 6939.53s/it]

[I 2026-02-21 07:32:17,749] Trial 57 finished with value: 0.9880920438844049 and parameters: {'layer1': 179, 'layer2': 52, 'layer3': 374, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0004737536007403088}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:21:44<9:38:17, 6939.53s/it]

[I 2026-02-21 07:32:33,813] Trial 58 finished with value: 0.9845981377851871 and parameters: {'layer1': 375, 'layer2': 430, 'layer3': 296, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0009949198971250812}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:21:54<9:38:17, 6939.53s/it]

[I 2026-02-21 07:32:43,310] Trial 59 finished with value: 0.9845981377851871 and parameters: {'layer1': 225, 'layer2': 221, 'layer3': 244, 'activation': 'identity', 'solver': 'sgd', 'lr': 0.001430146715485806}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:22:09<9:38:17, 6939.53s/it]

[I 2026-02-21 07:32:58,307] Trial 60 finished with value: 0.9845981377851871 and parameters: {'layer1': 331, 'layer2': 305, 'layer3': 330, 'activation': 'tanh', 'solver': 'adam', 'lr': 4.861072515955551e-06}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:22:28<9:38:17, 6939.53s/it]

[I 2026-02-21 07:33:17,663] Trial 61 finished with value: 0.9884353208550666 and parameters: {'layer1': 256, 'layer2': 497, 'layer3': 405, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.000702718715912366}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:22:52<9:38:17, 6939.53s/it]

[I 2026-02-21 07:33:41,458] Trial 62 finished with value: 0.9897431830776504 and parameters: {'layer1': 292, 'layer2': 479, 'layer3': 479, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0008545872199004615}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:23:08<9:38:17, 6939.53s/it]

[I 2026-02-21 07:33:56,960] Trial 63 finished with value: 0.9845981377851871 and parameters: {'layer1': 292, 'layer2': 460, 'layer3': 487, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0028919699081488715}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:23:31<9:38:17, 6939.53s/it]

[I 2026-02-21 07:34:20,205] Trial 64 finished with value: 0.9893731611697072 and parameters: {'layer1': 296, 'layer2': 482, 'layer3': 193, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.00040540140114559965}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:23:55<9:38:17, 6939.53s/it]

[I 2026-02-21 07:34:44,261] Trial 65 finished with value: 0.9886866072283839 and parameters: {'layer1': 302, 'layer2': 479, 'layer3': 172, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.00032731162555931686}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:24:16<9:38:17, 6939.53s/it]

[I 2026-02-21 07:35:04,930] Trial 66 finished with value: 0.9880920438844049 and parameters: {'layer1': 285, 'layer2': 444, 'layer3': 219, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.00047872555530583684}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:24:41<9:38:17, 6939.53s/it]

[I 2026-02-21 07:35:30,252] Trial 67 finished with value: 0.9890298841990456 and parameters: {'layer1': 359, 'layer2': 420, 'layer3': 142, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0010041680716968348}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:24:59<9:38:17, 6939.53s/it]

[I 2026-02-21 07:35:48,527] Trial 68 finished with value: 0.9890298841990456 and parameters: {'layer1': 202, 'layer2': 483, 'layer3': 464, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0004095528804409937}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:25:12<9:38:17, 6939.53s/it]

[I 2026-02-21 07:36:01,705] Trial 69 finished with value: 0.9845981377851871 and parameters: {'layer1': 236, 'layer2': 466, 'layer3': 80, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.00022155724311360346}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:25:30<9:38:17, 6939.53s/it]

[I 2026-02-21 07:36:19,115] Trial 70 finished with value: 0.985565303303428 and parameters: {'layer1': 316, 'layer2': 447, 'layer3': 204, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0017689615287601475}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:25:47<9:38:17, 6939.53s/it]

[I 2026-02-21 07:36:36,558] Trial 71 finished with value: 0.9884353208550666 and parameters: {'layer1': 260, 'layer2': 500, 'layer3': 275, 'activation': 'identity', 'solver': 'adam', 'lr': 0.000800637080986216}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:26:08<9:38:17, 6939.53s/it]

[I 2026-02-21 07:36:57,094] Trial 72 finished with value: 0.9884353208550666 and parameters: {'layer1': 269, 'layer2': 479, 'layer3': 313, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0011015666862367476}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:26:24<9:38:17, 6939.53s/it]

[I 2026-02-21 07:37:13,345] Trial 73 finished with value: 0.9871270321656478 and parameters: {'layer1': 337, 'layer2': 11, 'layer3': 198, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0005719475799394396}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:26:43<9:38:17, 6939.53s/it]

[I 2026-02-21 07:37:32,337] Trial 74 finished with value: 0.9855359780998277 and parameters: {'layer1': 298, 'layer2': 166, 'layer3': 370, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0026373385998037817}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:26:54<9:38:17, 6939.53s/it]

[I 2026-02-21 07:37:43,013] Trial 75 finished with value: 0.9845981377851871 and parameters: {'layer1': 242, 'layer2': 487, 'layer3': 348, 'activation': 'tanh', 'solver': 'sgd', 'lr': 0.0016401678297559084}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:27:09<9:38:17, 6939.53s/it]

[I 2026-02-21 07:37:58,011] Trial 76 finished with value: 0.9845981377851871 and parameters: {'layer1': 281, 'layer2': 458, 'layer3': 157, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.00444090016692654}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:27:30<9:38:17, 6939.53s/it]

[I 2026-02-21 07:38:19,297] Trial 77 finished with value: 0.9891899250887081 and parameters: {'layer1': 213, 'layer2': 439, 'layer3': 297, 'activation': 'identity', 'solver': 'adam', 'lr': 0.006555261892297592}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:27:53<9:38:17, 6939.53s/it]

[I 2026-02-21 07:38:41,849] Trial 78 finished with value: 0.9890519311994028 and parameters: {'layer1': 307, 'layer2': 397, 'layer3': 250, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0008335891873854247}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:28:09<9:38:17, 6939.53s/it]

[I 2026-02-21 07:38:58,045] Trial 79 finished with value: 0.9851927011291661 and parameters: {'layer1': 264, 'layer2': 275, 'layer3': 395, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0012943494064356206}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:28:26<9:38:17, 6939.53s/it]

[I 2026-02-21 07:39:15,277] Trial 80 finished with value: 0.9881055674815415 and parameters: {'layer1': 228, 'layer2': 374, 'layer3': 287, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0006944112473085295}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:28:43<9:38:17, 6939.53s/it]

[I 2026-02-21 07:39:32,508] Trial 81 finished with value: 0.9885144760524156 and parameters: {'layer1': 163, 'layer2': 439, 'layer3': 324, 'activation': 'identity', 'solver': 'adam', 'lr': 0.005965366718460601}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:29:06<9:38:17, 6939.53s/it]

[I 2026-02-21 07:39:55,022] Trial 82 finished with value: 0.9880920438844049 and parameters: {'layer1': 204, 'layer2': 452, 'layer3': 294, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0034131441342604377}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:29:21<9:38:17, 6939.53s/it]

[I 2026-02-21 07:40:10,229] Trial 83 finished with value: 0.9890910371258105 and parameters: {'layer1': 189, 'layer2': 418, 'layer3': 430, 'activation': 'identity', 'solver': 'adam', 'lr': 0.007824539515173765}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:29:38<9:38:17, 6939.53s/it]

[I 2026-02-21 07:40:27,451] Trial 84 finished with value: 0.9888449676762343 and parameters: {'layer1': 216, 'layer2': 464, 'layer3': 305, 'activation': 'identity', 'solver': 'adam', 'lr': 0.00833375045124453}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:29:56<9:38:17, 6939.53s/it]

[I 2026-02-21 07:40:45,557] Trial 85 finished with value: 0.9884353208550666 and parameters: {'layer1': 253, 'layer2': 487, 'layer3': 343, 'activation': 'identity', 'solver': 'adam', 'lr': 0.002026290004575723}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:30:16<9:38:17, 6939.53s/it]

[I 2026-02-21 07:41:05,407] Trial 86 finished with value: 0.9881141339986348 and parameters: {'layer1': 288, 'layer2': 109, 'layer3': 270, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0009579303219535307}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:30:28<9:38:17, 6939.53s/it]

[I 2026-02-21 07:41:16,933] Trial 87 finished with value: 0.9845981377851871 and parameters: {'layer1': 323, 'layer2': 335, 'layer3': 261, 'activation': 'relu', 'solver': 'sgd', 'lr': 0.002457517422292607}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:30:49<9:38:17, 6939.53s/it]

[I 2026-02-21 07:41:38,356] Trial 88 finished with value: 0.9892158128650534 and parameters: {'layer1': 240, 'layer2': 438, 'layer3': 500, 'activation': 'identity', 'solver': 'adam', 'lr': 0.004917800082868347}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:31:13<9:38:17, 6939.53s/it]

[I 2026-02-21 07:42:02,284] Trial 89 finished with value: 0.9880920438844049 and parameters: {'layer1': 277, 'layer2': 470, 'layer3': 474, 'activation': 'tanh', 'solver': 'adam', 'lr': 9.234982401113058e-05}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:31:27<9:38:17, 6939.53s/it]

[I 2026-02-21 07:42:16,566] Trial 90 finished with value: 0.9845981377851871 and parameters: {'layer1': 245, 'layer2': 430, 'layer3': 497, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0050420992831096524}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:31:44<9:38:17, 6939.53s/it]

[I 2026-02-21 07:42:33,712] Trial 91 finished with value: 0.9884353208550666 and parameters: {'layer1': 219, 'layer2': 412, 'layer3': 463, 'activation': 'identity', 'solver': 'adam', 'lr': 0.006278914315850798}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:32:06<9:38:17, 6939.53s/it]

[I 2026-02-21 07:42:55,389] Trial 92 finished with value: 0.9877615522605862 and parameters: {'layer1': 236, 'layer2': 439, 'layer3': 311, 'activation': 'identity', 'solver': 'adam', 'lr': 0.004423387741171325}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:32:23<9:38:17, 6939.53s/it]

[I 2026-02-21 07:43:11,933] Trial 93 finished with value: 0.9884353208550666 and parameters: {'layer1': 267, 'layer2': 390, 'layer3': 359, 'activation': 'identity', 'solver': 'adam', 'lr': 0.001460641225519224}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:32:47<9:38:17, 6939.53s/it]

[I 2026-02-21 07:43:36,107] Trial 94 finished with value: 0.9897701700600443 and parameters: {'layer1': 208, 'layer2': 487, 'layer3': 484, 'activation': 'identity', 'solver': 'adam', 'lr': 0.003742749378457505}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:33:03<9:38:17, 6939.53s/it]

[I 2026-02-21 07:43:52,314] Trial 95 finished with value: 0.9881140908847623 and parameters: {'layer1': 149, 'layer2': 486, 'layer3': 449, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0034929384345547135}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:33:19<9:38:17, 6939.53s/it]

[I 2026-02-21 07:44:08,375] Trial 96 finished with value: 0.9883370405084246 and parameters: {'layer1': 173, 'layer2': 498, 'layer3': 486, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0005872286401959307}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:33:34<9:38:17, 6939.53s/it]

[I 2026-02-21 07:44:22,996] Trial 97 finished with value: 0.9845981377851871 and parameters: {'layer1': 254, 'layer2': 474, 'layer3': 493, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.00040310057619059685}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:33:49<9:38:17, 6939.53s/it]

[I 2026-02-21 07:44:38,569] Trial 98 finished with value: 0.9845981377851871 and parameters: {'layer1': 298, 'layer2': 455, 'layer3': 441, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0029478328491781033}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:34:03<9:38:17, 6939.53s/it]

[I 2026-02-21 07:44:52,200] Trial 99 finished with value: 0.9884628890732239 and parameters: {'layer1': 83, 'layer2': 487, 'layer3': 465, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0012469412804216105}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:34:12<9:38:17, 6939.53s/it]

[I 2026-02-21 07:45:01,530] Trial 100 finished with value: 0.9845981377851871 and parameters: {'layer1': 194, 'layer2': 470, 'layer3': 427, 'activation': 'tanh', 'solver': 'sgd', 'lr': 0.001784370995997157}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:34:24<9:38:17, 6939.53s/it]

[I 2026-02-21 07:45:13,796] Trial 101 finished with value: 0.9845981377851871 and parameters: {'layer1': 211, 'layer2': 241, 'layer3': 476, 'activation': 'identity', 'solver': 'adam', 'lr': 1.9423567178570583e-05}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:34:42<9:38:17, 6939.53s/it]

[I 2026-02-21 07:45:30,919] Trial 102 finished with value: 0.9880920438844049 and parameters: {'layer1': 228, 'layer2': 430, 'layer3': 332, 'activation': 'identity', 'solver': 'adam', 'lr': 0.009571470632213886}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:34:59<9:38:17, 6939.53s/it]

[I 2026-02-21 07:45:47,898] Trial 103 finished with value: 0.9886803174790864 and parameters: {'layer1': 275, 'layer2': 448, 'layer3': 323, 'activation': 'identity', 'solver': 'adam', 'lr': 0.007139955334338516}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:35:15<9:38:17, 6939.53s/it]

[I 2026-02-21 07:46:04,829] Trial 104 finished with value: 0.9865031436180687 and parameters: {'layer1': 209, 'layer2': 466, 'layer3': 241, 'activation': 'identity', 'solver': 'adam', 'lr': 6.561613846873809e-05}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:35:33<9:38:17, 6939.53s/it]

[I 2026-02-21 07:46:22,278] Trial 105 finished with value: 0.9880920438844049 and parameters: {'layer1': 240, 'layer2': 482, 'layer3': 128, 'activation': 'identity', 'solver': 'adam', 'lr': 0.002216251955620897}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:35:48<9:38:17, 6939.53s/it]

[I 2026-02-21 07:46:37,422] Trial 106 finished with value: 0.9845981377851871 and parameters: {'layer1': 286, 'layer2': 492, 'layer3': 230, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.004094524297673419}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:36:11<9:38:17, 6939.53s/it]

[I 2026-02-21 07:47:00,245] Trial 107 finished with value: 0.9893731611697072 and parameters: {'layer1': 320, 'layer2': 458, 'layer3': 500, 'activation': 'relu', 'solver': 'adam', 'lr': 0.005321402293238288}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:36:32<9:38:17, 6939.53s/it]

[I 2026-02-21 07:47:21,122] Trial 108 finished with value: 0.9884353208550666 and parameters: {'layer1': 340, 'layer2': 207, 'layer3': 472, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0009022656806822097}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:36:59<9:38:17, 6939.53s/it]

[I 2026-02-21 07:47:48,454] Trial 109 finished with value: 0.9897660533588836 and parameters: {'layer1': 365, 'layer2': 478, 'layer3': 500, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0051270714644204044}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:37:23<9:38:17, 6939.53s/it]

[I 2026-02-21 07:48:12,563] Trial 110 finished with value: 0.9884353208550666 and parameters: {'layer1': 397, 'layer2': 459, 'layer3': 497, 'activation': 'relu', 'solver': 'adam', 'lr': 0.005349638948073168}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:37:49<9:38:17, 6939.53s/it]

[I 2026-02-21 07:48:38,308] Trial 111 finished with value: 0.9881268762316051 and parameters: {'layer1': 459, 'layer2': 478, 'layer3': 454, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0006842617714369065}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:38:13<9:38:17, 6939.53s/it]

[I 2026-02-21 07:49:01,914] Trial 112 finished with value: 0.9887201919369915 and parameters: {'layer1': 320, 'layer2': 492, 'layer3': 480, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0011080317202612434}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:38:32<9:38:17, 6939.53s/it]

[I 2026-02-21 07:49:21,307] Trial 113 finished with value: 0.9884353208550666 and parameters: {'layer1': 303, 'layer2': 465, 'layer3': 484, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0037830689556206595}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:38:57<9:38:17, 6939.53s/it]

[I 2026-02-21 07:49:45,928] Trial 114 finished with value: 0.9901545103406303 and parameters: {'layer1': 375, 'layer2': 452, 'layer3': 492, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0030258637158854153}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:39:17<9:38:17, 6939.53s/it]

[I 2026-02-21 07:50:06,762] Trial 115 finished with value: 0.9884756744200669 and parameters: {'layer1': 365, 'layer2': 452, 'layer3': 499, 'activation': 'relu', 'solver': 'adam', 'lr': 0.002685048073160138}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:39:40<9:38:17, 6939.53s/it]

[I 2026-02-21 07:50:29,814] Trial 116 finished with value: 0.9881140908847623 and parameters: {'layer1': 389, 'layer2': 422, 'layer3': 466, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0005407359886139671}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:40:02<9:38:17, 6939.53s/it]

[I 2026-02-21 07:50:51,104] Trial 117 finished with value: 0.9874703091363095 and parameters: {'layer1': 421, 'layer2': 500, 'layer3': 491, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0016441784323556583}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:40:20<9:38:17, 6939.53s/it]

[I 2026-02-21 07:51:09,014] Trial 118 finished with value: 0.9865031436180687 and parameters: {'layer1': 354, 'layer2': 476, 'layer3': 500, 'activation': 'relu', 'solver': 'adam', 'lr': 0.004989696689551295}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:40:42<9:38:17, 6939.53s/it]

[I 2026-02-21 07:51:31,067] Trial 119 finished with value: 0.9884841559065782 and parameters: {'layer1': 363, 'layer2': 442, 'layer3': 437, 'activation': 'relu', 'solver': 'adam', 'lr': 0.003096679562839582}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:40:56<9:38:17, 6939.53s/it]

[I 2026-02-21 07:51:45,022] Trial 120 finished with value: 0.9845981377851871 and parameters: {'layer1': 413, 'layer2': 460, 'layer3': 459, 'activation': 'relu', 'solver': 'sgd', 'lr': 0.0008066641569103199}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:41:20<9:38:17, 6939.53s/it]

[I 2026-02-21 07:52:09,347] Trial 121 finished with value: 0.9884353208550666 and parameters: {'layer1': 333, 'layer2': 485, 'layer3': 338, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.001375984073343148}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:41:38<9:38:17, 6939.53s/it]

[I 2026-02-21 07:52:26,864] Trial 122 finished with value: 0.9845981377851871 and parameters: {'layer1': 375, 'layer2': 474, 'layer3': 485, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.003961316056408132}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:41:59<9:38:17, 6939.53s/it]

[I 2026-02-21 07:52:48,487] Trial 123 finished with value: 0.9897844884326871 and parameters: {'layer1': 261, 'layer2': 403, 'layer3': 475, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00563269792185504}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:42:18<9:38:17, 6939.53s/it]

[I 2026-02-21 07:53:07,208] Trial 124 finished with value: 0.9888053427630099 and parameters: {'layer1': 263, 'layer2': 398, 'layer3': 472, 'activation': 'relu', 'solver': 'adam', 'lr': 0.005696084911721572}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:42:39<9:38:17, 6939.53s/it]

[I 2026-02-21 07:53:28,517] Trial 125 finished with value: 0.9888466481180463 and parameters: {'layer1': 311, 'layer2': 434, 'layer3': 416, 'activation': 'relu', 'solver': 'adam', 'lr': 0.008975856376062085}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:42:58<9:38:17, 6939.53s/it]

[I 2026-02-21 07:53:47,533] Trial 126 finished with value: 0.9880920438844049 and parameters: {'layer1': 294, 'layer2': 450, 'layer3': 451, 'activation': 'relu', 'solver': 'adam', 'lr': 0.001995641309929997}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:43:20<9:38:17, 6939.53s/it]

[I 2026-02-21 07:54:09,711] Trial 127 finished with value: 0.9880920438844049 and parameters: {'layer1': 278, 'layer2': 417, 'layer3': 479, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0002874259813716678}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:43:34<9:38:17, 6939.53s/it]

[I 2026-02-21 07:54:23,434] Trial 128 finished with value: 0.9845981377851871 and parameters: {'layer1': 256, 'layer2': 406, 'layer3': 373, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.007270055462692094}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:43:53<9:38:17, 6939.53s/it]

[I 2026-02-21 07:54:42,054] Trial 129 finished with value: 0.9871270321656478 and parameters: {'layer1': 250, 'layer2': 500, 'layer3': 487, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0007264210192253835}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:44:07<9:38:17, 6939.53s/it]

[I 2026-02-21 07:54:56,554] Trial 130 finished with value: 0.9845981377851871 and parameters: {'layer1': 284, 'layer2': 428, 'layer3': 93, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.004818704959854888}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:44:27<9:38:17, 6939.53s/it]

[I 2026-02-21 07:55:16,331] Trial 131 finished with value: 0.9861577128479231 and parameters: {'layer1': 269, 'layer2': 466, 'layer3': 351, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0023863767662834013}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:44:48<9:38:17, 6939.53s/it]

[I 2026-02-21 07:55:37,390] Trial 132 finished with value: 0.9897844884326871 and parameters: {'layer1': 225, 'layer2': 482, 'layer3': 183, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0009982662152363913}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:45:07<9:38:17, 6939.53s/it]

[I 2026-02-21 07:55:56,130] Trial 133 finished with value: 0.9886803174790864 and parameters: {'layer1': 228, 'layer2': 480, 'layer3': 193, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0010555383619224427}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:45:28<9:38:17, 6939.53s/it]

[I 2026-02-21 07:56:16,888] Trial 134 finished with value: 0.9891315191999712 and parameters: {'layer1': 193, 'layer2': 490, 'layer3': 184, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.00092826790209576}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:45:54<9:38:17, 6939.53s/it]

[I 2026-02-21 07:56:42,982] Trial 135 finished with value: 0.9887086542287411 and parameters: {'layer1': 346, 'layer2': 455, 'layer3': 158, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.00046161072998322436}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:46:14<9:38:17, 6939.53s/it]

[I 2026-02-21 07:57:02,899] Trial 136 finished with value: 0.9871270321656478 and parameters: {'layer1': 236, 'layer2': 469, 'layer3': 169, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0011910946372547225}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:46:33<9:38:17, 6939.53s/it]

[I 2026-02-21 07:57:22,151] Trial 137 finished with value: 0.9893731611697072 and parameters: {'layer1': 221, 'layer2': 446, 'layer3': 470, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0006231945980128303}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:46:53<9:38:17, 6939.53s/it]

[I 2026-02-21 07:57:42,813] Trial 138 finished with value: 0.9903727620273683 and parameters: {'layer1': 220, 'layer2': 483, 'layer3': 445, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0006141676134066318}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:47:12<9:38:17, 6939.53s/it]

[I 2026-02-21 07:58:01,116] Trial 139 finished with value: 0.9893731611697072 and parameters: {'layer1': 177, 'layer2': 490, 'layer3': 458, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.000494158610826242}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:47:33<9:38:17, 6939.53s/it]

[I 2026-02-21 07:58:22,776] Trial 140 finished with value: 0.9897844884326871 and parameters: {'layer1': 292, 'layer2': 481, 'layer3': 443, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.000831445431378159}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:47:55<9:38:17, 6939.53s/it]

[I 2026-02-21 07:58:43,873] Trial 141 finished with value: 0.9901140282664695 and parameters: {'layer1': 304, 'layer2': 479, 'layer3': 395, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0008369086132622164}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:48:16<9:38:17, 6939.53s/it]

[I 2026-02-21 07:59:05,119] Trial 142 finished with value: 0.9888274328772397 and parameters: {'layer1': 296, 'layer2': 481, 'layer3': 397, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0008166126471444666}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:48:39<9:38:17, 6939.53s/it]

[I 2026-02-21 07:59:28,058] Trial 143 finished with value: 0.9893952081700645 and parameters: {'layer1': 308, 'layer2': 491, 'layer3': 437, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.001006820720117439}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:49:00<9:38:17, 6939.53s/it]

[I 2026-02-21 07:59:49,829] Trial 144 finished with value: 0.9881140908847623 and parameters: {'layer1': 313, 'layer2': 493, 'layer3': 418, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0009879023825122824}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:49:29<9:38:17, 6939.53s/it]

[I 2026-02-21 08:00:18,755] Trial 145 finished with value: 0.9899428488805375 and parameters: {'layer1': 306, 'layer2': 473, 'layer3': 444, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0013704556872544142}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:49:51<9:38:17, 6939.53s/it]

[I 2026-02-21 08:00:39,972] Trial 146 finished with value: 0.9874703091363095 and parameters: {'layer1': 275, 'layer2': 474, 'layer3': 429, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0013805095817633532}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:50:11<9:38:17, 6939.53s/it]

[I 2026-02-21 08:01:00,524] Trial 147 finished with value: 0.9865031436180687 and parameters: {'layer1': 307, 'layer2': 499, 'layer3': 438, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0016518331224646449}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:50:29<9:38:17, 6939.53s/it]

[I 2026-02-21 08:01:18,823] Trial 148 finished with value: 0.98776229051088 and parameters: {'layer1': 203, 'layer2': 484, 'layer3': 390, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0006732975871498642}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:50:41<9:38:17, 6939.53s/it]

[I 2026-02-21 08:01:30,576] Trial 149 finished with value: 0.9845981377851871 and parameters: {'layer1': 329, 'layer2': 472, 'layer3': 447, 'activation': 'tanh', 'solver': 'sgd', 'lr': 0.001248371252934336}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:51:09<9:38:17, 6939.53s/it]

[I 2026-02-21 08:01:57,877] Trial 150 finished with value: 0.9896181577937269 and parameters: {'layer1': 442, 'layer2': 490, 'layer3': 450, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0008912290051538427}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:51:33<9:38:17, 6939.53s/it]

[I 2026-02-21 08:02:22,482] Trial 151 finished with value: 0.9874703091363095 and parameters: {'layer1': 474, 'layer2': 490, 'layer3': 410, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0007927668213531301}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:51:59<9:38:17, 6939.53s/it]

[I 2026-02-21 08:02:48,830] Trial 152 finished with value: 0.988730744342971 and parameters: {'layer1': 467, 'layer2': 466, 'layer3': 450, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0009079322560716876}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:52:20<9:38:17, 6939.53s/it]

[I 2026-02-21 08:03:09,711] Trial 153 finished with value: 0.986530315022185 and parameters: {'layer1': 450, 'layer2': 483, 'layer3': 441, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0011448713899287091}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:52:43<9:38:17, 6939.53s/it]

[I 2026-02-21 08:03:32,360] Trial 154 finished with value: 0.990149812403706 and parameters: {'layer1': 287, 'layer2': 498, 'layer3': 461, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0005475684641143309}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:53:09<9:38:17, 6939.53s/it]

[I 2026-02-21 08:03:58,425] Trial 155 finished with value: 0.9893731611697072 and parameters: {'layer1': 500, 'layer2': 478, 'layer3': 461, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.00036053387753079555}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:53:33<9:38:17, 6939.53s/it]

[I 2026-02-21 08:04:22,838] Trial 156 finished with value: 0.9887001308255206 and parameters: {'layer1': 428, 'layer2': 499, 'layer3': 423, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0006867061797564926}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:53:52<9:38:17, 6939.53s/it]

[I 2026-02-21 08:04:41,257] Trial 157 finished with value: 0.98776229051088 and parameters: {'layer1': 286, 'layer2': 469, 'layer3': 477, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0005635853444829035}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:54:13<9:38:17, 6939.53s/it]

[I 2026-02-21 08:05:02,526] Trial 158 finished with value: 0.985565303303428 and parameters: {'layer1': 435, 'layer2': 481, 'layer3': 467, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.001600600715632528}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:54:31<9:38:17, 6939.53s/it]

[I 2026-02-21 08:05:20,768] Trial 159 finished with value: 0.9897828079908748 and parameters: {'layer1': 222, 'layer2': 462, 'layer3': 448, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.000792085875503605}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:54:49<9:38:17, 6939.53s/it]

[I 2026-02-21 08:05:38,085] Trial 160 finished with value: 0.9888053427630099 and parameters: {'layer1': 246, 'layer2': 460, 'layer3': 479, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0005794833358404124}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:55:15<9:38:17, 6939.53s/it]

[I 2026-02-21 08:06:04,509] Trial 161 finished with value: 0.9905374122245163 and parameters: {'layer1': 402, 'layer2': 490, 'layer3': 455, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.000743256553958863}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:55:43<9:38:17, 6939.53s/it]

[I 2026-02-21 08:06:31,939] Trial 162 finished with value: 0.9901545103406303 and parameters: {'layer1': 393, 'layer2': 475, 'layer3': 454, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0007690895099289909}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:56:07<9:38:17, 6939.53s/it]

[I 2026-02-21 08:06:56,191] Trial 163 finished with value: 0.989188244646896 and parameters: {'layer1': 397, 'layer2': 465, 'layer3': 456, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0004735478013342968}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:56:31<9:38:17, 6939.53s/it]

[I 2026-02-21 08:07:20,293] Trial 164 finished with value: 0.9888061660438856 and parameters: {'layer1': 407, 'layer2': 500, 'layer3': 426, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0007568790754537741}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:56:56<9:38:17, 6939.53s/it]

[I 2026-02-21 08:07:45,101] Trial 165 finished with value: 0.9888053427630099 and parameters: {'layer1': 378, 'layer2': 451, 'layer3': 441, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0006553686284859711}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:57:21<9:38:17, 6939.53s/it]

[I 2026-02-21 08:08:10,764] Trial 166 finished with value: 0.9890916447420661 and parameters: {'layer1': 383, 'layer2': 475, 'layer3': 463, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0010247667490968612}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:57:49<9:38:17, 6939.53s/it]

[I 2026-02-21 08:08:38,262] Trial 167 finished with value: 0.9897440063585263 and parameters: {'layer1': 397, 'layer2': 487, 'layer3': 488, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0007801869296893189}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:58:04<9:38:17, 6939.53s/it]

[I 2026-02-21 08:08:53,196] Trial 168 finished with value: 0.9845981377851871 and parameters: {'layer1': 389, 'layer2': 462, 'layer3': 11, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0005375787940522845}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:58:26<9:38:17, 6939.53s/it]

[I 2026-02-21 08:09:15,241] Trial 169 finished with value: 0.9881140908847623 and parameters: {'layer1': 372, 'layer2': 474, 'layer3': 469, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0003372195291666614}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:58:44<9:38:17, 6939.53s/it]

[I 2026-02-21 08:09:32,924] Trial 170 finished with value: 0.9845981377851871 and parameters: {'layer1': 405, 'layer2': 483, 'layer3': 490, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.00040930101428567035}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:59:04<9:38:17, 6939.53s/it]

[I 2026-02-21 08:09:53,613] Trial 171 finished with value: 0.9893731611697072 and parameters: {'layer1': 223, 'layer2': 500, 'layer3': 457, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0007682378574060863}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:59:23<9:38:17, 6939.53s/it]

[I 2026-02-21 08:10:11,868] Trial 172 finished with value: 0.9845981377851871 and parameters: {'layer1': 418, 'layer2': 489, 'layer3': 486, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0013134941307406114}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [20:59:40<9:38:17, 6939.53s/it]

[I 2026-02-21 08:10:29,419] Trial 173 finished with value: 0.9883370405084246 and parameters: {'layer1': 212, 'layer2': 490, 'layer3': 406, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0006447225034187556}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [21:00:01<9:38:17, 6939.53s/it]

[I 2026-02-21 08:10:50,489] Trial 174 finished with value: 0.9880648724802885 and parameters: {'layer1': 265, 'layer2': 472, 'layer3': 445, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0011266617107381146}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [21:00:19<9:38:17, 6939.53s/it]

[I 2026-02-21 08:11:08,778] Trial 175 finished with value: 0.9890298841990456 and parameters: {'layer1': 188, 'layer2': 456, 'layer3': 474, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.000952726096496335}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [21:00:43<9:38:17, 6939.53s/it]

[I 2026-02-21 08:11:32,304] Trial 176 finished with value: 0.9874681553368256 and parameters: {'layer1': 398, 'layer2': 480, 'layer3': 430, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0007870016383753957}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [21:02:52<9:38:17, 6939.53s/it]

[I 2026-02-21 08:13:40,893] Trial 177 finished with value: 0.9819065744019279 and parameters: {'layer1': 391, 'layer2': 491, 'layer3': 488, 'activation': 'tanh', 'solver': 'sgd', 'lr': 1.842925571946557e-06}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [21:03:08<9:38:17, 6939.53s/it]

[I 2026-02-21 08:13:56,999] Trial 178 finished with value: 0.9845981377851871 and parameters: {'layer1': 369, 'layer2': 465, 'layer3': 58, 'activation': 'tanh', 'solver': 'adam', 'lr': 7.567489238996359e-06}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [21:03:33<9:38:17, 6939.53s/it]

[I 2026-02-21 08:14:21,889] Trial 179 finished with value: 0.9904977873112919 and parameters: {'layer1': 234, 'layer2': 316, 'layer3': 367, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0013935196987002116}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [21:03:51<9:38:17, 6939.53s/it]

[I 2026-02-21 08:14:39,854] Trial 180 finished with value: 0.986754429991386 and parameters: {'layer1': 233, 'layer2': 290, 'layer3': 376, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.001923439450134399}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [21:04:06<9:38:17, 6939.53s/it]

[I 2026-02-21 08:14:55,270] Trial 181 finished with value: 0.9865031436180687 and parameters: {'layer1': 200, 'layer2': 483, 'layer3': 354, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0014291593245384265}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [21:04:27<9:38:17, 6939.53s/it]

[I 2026-02-21 08:15:15,981] Trial 182 finished with value: 0.987124878366164 and parameters: {'layer1': 221, 'layer2': 499, 'layer3': 317, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0011569553935232742}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [21:04:45<9:38:17, 6939.53s/it]

[I 2026-02-21 08:15:34,396] Trial 183 finished with value: 0.9884628890732239 and parameters: {'layer1': 255, 'layer2': 446, 'layer3': 338, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0009073684192358708}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [21:05:04<9:38:17, 6939.53s/it]

[I 2026-02-21 08:15:53,733] Trial 184 finished with value: 0.9890298841990456 and parameters: {'layer1': 232, 'layer2': 312, 'layer3': 369, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0006365530404076272}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [21:05:24<9:38:17, 6939.53s/it]

[I 2026-02-21 08:16:12,954] Trial 185 finished with value: 0.9865031436180687 and parameters: {'layer1': 242, 'layer2': 477, 'layer3': 360, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0015720998248040655}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [21:05:48<9:38:17, 6939.53s/it]

[I 2026-02-21 08:16:37,754] Trial 186 finished with value: 0.9884353208550666 and parameters: {'layer1': 406, 'layer2': 489, 'layer3': 390, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0012282249936798376}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [21:06:08<9:38:17, 6939.53s/it]

[I 2026-02-21 08:16:57,508] Trial 187 finished with value: 0.9893731611697072 and parameters: {'layer1': 218, 'layer2': 471, 'layer3': 470, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.000809176639649478}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [21:06:26<9:38:17, 6939.53s/it]

[I 2026-02-21 08:17:15,372] Trial 188 finished with value: 0.9886866072283839 and parameters: {'layer1': 210, 'layer2': 456, 'layer3': 455, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.000516385446492638}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [21:06:41<9:38:17, 6939.53s/it]

[I 2026-02-21 08:17:30,843] Trial 189 finished with value: 0.9845981377851871 and parameters: {'layer1': 263, 'layer2': 485, 'layer3': 478, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.003205698426842626}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [21:06:59<9:38:17, 6939.53s/it]

[I 2026-02-21 08:17:48,709] Trial 190 finished with value: 0.9880920438844049 and parameters: {'layer1': 248, 'layer2': 325, 'layer3': 433, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0009983087188919363}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [21:07:24<9:38:17, 6939.53s/it]

[I 2026-02-21 08:18:13,153] Trial 191 finished with value: 0.9903727620273683 and parameters: {'layer1': 299, 'layer2': 476, 'layer3': 493, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0008318899180084676}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [21:07:43<9:38:17, 6939.53s/it]

[I 2026-02-21 08:18:32,197] Trial 192 finished with value: 0.9884353208550666 and parameters: {'layer1': 275, 'layer2': 378, 'layer3': 490, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0006728703380727072}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [21:08:05<9:38:17, 6939.53s/it]

[I 2026-02-21 08:18:54,452] Trial 193 finished with value: 0.9901277654033487 and parameters: {'layer1': 283, 'layer2': 500, 'layer3': 500, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0008650376921311513}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [21:08:25<9:38:17, 6939.53s/it]

[I 2026-02-21 08:19:14,123] Trial 194 finished with value: 0.9884574109692965 and parameters: {'layer1': 299, 'layer2': 467, 'layer3': 498, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0008235500882662843}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [21:08:45<9:38:17, 6939.53s/it]

[I 2026-02-21 08:19:34,026] Trial 195 finished with value: 0.9890298841990456 and parameters: {'layer1': 287, 'layer2': 491, 'layer3': 482, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.000755548927586975}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [21:09:10<9:38:17, 6939.53s/it]

[I 2026-02-21 08:19:58,991] Trial 196 finished with value: 0.9884353208550666 and parameters: {'layer1': 384, 'layer2': 476, 'layer3': 492, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0010758202466780804}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [21:09:27<9:38:17, 6939.53s/it]

[I 2026-02-21 08:20:16,166] Trial 197 finished with value: 0.9880920438844049 and parameters: {'layer1': 197, 'layer2': 483, 'layer3': 465, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0005687637817841522}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  64%|██████▍   | 9/14 [21:09:51<9:38:17, 6939.53s/it]

[I 2026-02-21 08:20:40,693] Trial 198 finished with value: 0.9890519311994028 and parameters: {'layer1': 353, 'layer2': 257, 'layer3': 483, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0008445348076103112}. Best is trial 35 with value: 0.990880689195178.

Best trial: 35. Best value: 0.990881: 100%|██████████| 200/200 [1:05:24<00:00, 19.62s/it]

[I 2026-02-21 08:20:56,066] Trial 199 finished with value: 0.9845981377851871 and parameters: {'layer1': 280, 'layer2': 461, 'layer3': 500, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.00046845589041451816}. Best is trial 35 with value: 0.990880689195178.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:10:08<6:40:36, 6009.00s/it][I 2026-02-21 08:20:56,936] A new study created in memory with name: no-name-d9c79ef6-8458-4b12-9935-5767d2264700

  → Best model saved.

[Exact Paper MLP] Klebsiella_Pneumoniae | Meropenem

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:10:16<6:40:36, 6009.00s/it]

[I 2026-02-21 08:21:05,574] Trial 0 finished with value: 0.9845981377851871 and parameters: {'layer1': 144, 'layer2': 422, 'layer3': 421, 'activation': 'identity', 'solver': 'sgd', 'lr': 0.0007035549376850167}. Best is trial 0 with value: 0.9845981377851871.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:10:34<6:40:36, 6009.00s/it]

[I 2026-02-21 08:21:23,127] Trial 1 finished with value: 0.9884353208550666 and parameters: {'layer1': 201, 'layer2': 428, 'layer3': 147, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0007363086153525217}. Best is trial 1 with value: 0.9884353208550666.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:10:48<6:40:36, 6009.00s/it]

[I 2026-02-21 08:21:37,415] Trial 2 finished with value: 0.9845981377851871 and parameters: {'layer1': 329, 'layer2': 288, 'layer3': 195, 'activation': 'relu', 'solver': 'sgd', 'lr': 0.00010251094238733061}. Best is trial 1 with value: 0.9884353208550666.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:10:57<6:40:36, 6009.00s/it]

[I 2026-02-21 08:21:46,429] Trial 3 finished with value: 0.9845981377851871 and parameters: {'layer1': 188, 'layer2': 211, 'layer3': 309, 'activation': 'identity', 'solver': 'sgd', 'lr': 0.0012997406341654564}. Best is trial 1 with value: 0.9884353208550666.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:11:08<6:40:36, 6009.00s/it]

[I 2026-02-21 08:21:57,202] Trial 4 finished with value: 0.9845981377851871 and parameters: {'layer1': 21, 'layer2': 110, 'layer3': 438, 'activation': 'relu', 'solver': 'adam', 'lr': 2.2279055183514147e-06}. Best is trial 1 with value: 0.9884353208550666.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:11:28<6:40:36, 6009.00s/it]

[I 2026-02-21 08:22:16,864] Trial 5 finished with value: 0.787310426229376 and parameters: {'layer1': 467, 'layer2': 237, 'layer3': 33, 'activation': 'tanh', 'solver': 'sgd', 'lr': 9.282539400868274e-06}. Best is trial 1 with value: 0.9884353208550666.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:11:43<6:40:36, 6009.00s/it]

[I 2026-02-21 08:22:32,298] Trial 6 finished with value: 0.9845981377851871 and parameters: {'layer1': 403, 'layer2': 421, 'layer3': 426, 'activation': 'identity', 'solver': 'adam', 'lr': 7.036015557747245e-06}. Best is trial 1 with value: 0.9884353208550666.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:12:00<6:40:36, 6009.00s/it]

[I 2026-02-21 08:22:49,775] Trial 7 finished with value: 0.9845981377851871 and parameters: {'layer1': 487, 'layer2': 61, 'layer3': 272, 'activation': 'logistic', 'solver': 'adam', 'lr': 2.8093775034614845e-05}. Best is trial 1 with value: 0.9884353208550666.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:12:09<6:40:36, 6009.00s/it]

[I 2026-02-21 08:22:58,076] Trial 8 finished with value: 0.9845981377851871 and parameters: {'layer1': 150, 'layer2': 58, 'layer3': 378, 'activation': 'relu', 'solver': 'sgd', 'lr': 0.008026326683187333}. Best is trial 1 with value: 0.9884353208550666.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:12:31<6:40:36, 6009.00s/it]

[I 2026-02-21 08:23:20,806] Trial 9 finished with value: 0.9845981377851871 and parameters: {'layer1': 470, 'layer2': 473, 'layer3': 326, 'activation': 'relu', 'solver': 'sgd', 'lr': 9.458623032885441e-05}. Best is trial 1 with value: 0.9884353208550666.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:12:46<6:40:36, 6009.00s/it]

[I 2026-02-21 08:23:35,416] Trial 10 finished with value: 0.9845981377851871 and parameters: {'layer1': 271, 'layer2': 338, 'layer3': 152, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.00092232401048082}. Best is trial 1 with value: 0.9884353208550666.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:12:59<6:40:36, 6009.00s/it]

[I 2026-02-21 08:23:48,442] Trial 11 finished with value: 0.9884573678554238 and parameters: {'layer1': 92, 'layer2': 379, 'layer3': 94, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0007693902517454663}. Best is trial 11 with value: 0.9884573678554238.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:13:09<6:40:36, 6009.00s/it]

[I 2026-02-21 08:23:57,876] Trial 12 finished with value: 0.9845981377851871 and parameters: {'layer1': 29, 'layer2': 369, 'layer3': 90, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.008398936285277896}. Best is trial 11 with value: 0.9884573678554238.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:13:22<6:40:36, 6009.00s/it]

[I 2026-02-21 08:24:11,464] Trial 13 finished with value: 0.9880920438844049 and parameters: {'layer1': 100, 'layer2': 496, 'layer3': 169, 'activation': 'identity', 'solver': 'adam', 'lr': 0.00030972512691514474}. Best is trial 11 with value: 0.9884573678554238.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:13:37<6:40:36, 6009.00s/it]

[I 2026-02-21 08:24:26,106] Trial 14 finished with value: 0.9861305414438066 and parameters: {'layer1': 210, 'layer2': 354, 'layer3': 12, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0016932661046307963}. Best is trial 11 with value: 0.9884573678554238.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:13:50<6:40:36, 6009.00s/it]

[I 2026-02-21 08:24:39,483] Trial 15 finished with value: 0.9871270321656478 and parameters: {'layer1': 83, 'layer2': 426, 'layer3': 91, 'activation': 'identity', 'solver': 'adam', 'lr': 0.00021812383453591747}. Best is trial 11 with value: 0.9884573678554238.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:14:05<6:40:36, 6009.00s/it]

[I 2026-02-21 08:24:53,966] Trial 16 finished with value: 0.9845981377851871 and parameters: {'layer1': 272, 'layer2': 294, 'layer3': 92, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.003010026102210621}. Best is trial 11 with value: 0.9884573678554238.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:14:20<6:40:36, 6009.00s/it]

[I 2026-02-21 08:25:09,530] Trial 17 finished with value: 0.9845981377851871 and parameters: {'layer1': 322, 'layer2': 185, 'layer3': 207, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0003611377600390262}. Best is trial 11 with value: 0.9884573678554238.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:14:33<6:40:36, 6009.00s/it]

[I 2026-02-21 08:25:22,505] Trial 18 finished with value: 0.9884081494509502 and parameters: {'layer1': 86, 'layer2': 393, 'layer3': 131, 'activation': 'relu', 'solver': 'adam', 'lr': 0.003163450817816509}. Best is trial 11 with value: 0.9884573678554238.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:14:52<6:40:36, 6009.00s/it]

[I 2026-02-21 08:25:41,544] Trial 19 finished with value: 0.9874703091363095 and parameters: {'layer1': 216, 'layer2': 314, 'layer3': 237, 'activation': 'identity', 'solver': 'adam', 'lr': 7.352004543303952e-05}. Best is trial 11 with value: 0.9884573678554238.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:15:04<6:40:36, 6009.00s/it]

[I 2026-02-21 08:25:53,416] Trial 20 finished with value: 0.9845981377851871 and parameters: {'layer1': 133, 'layer2': 458, 'layer3': 499, 'activation': 'relu', 'solver': 'adam', 'lr': 3.2748354168889954e-05}. Best is trial 11 with value: 0.9884573678554238.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:15:18<6:40:36, 6009.00s/it]

[I 2026-02-21 08:26:07,119] Trial 21 finished with value: 0.9883370405084246 and parameters: {'layer1': 87, 'layer2': 387, 'layer3': 127, 'activation': 'relu', 'solver': 'adam', 'lr': 0.003817151751988926}. Best is trial 11 with value: 0.9884573678554238.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:15:32<6:40:36, 6009.00s/it]

[I 2026-02-21 08:26:20,920] Trial 22 finished with value: 0.988728252310335 and parameters: {'layer1': 50, 'layer2': 391, 'layer3': 56, 'activation': 'relu', 'solver': 'adam', 'lr': 0.002855018126188639}. Best is trial 22 with value: 0.988728252310335.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:15:44<6:40:36, 6009.00s/it]

[I 2026-02-21 08:26:33,170] Trial 23 finished with value: 0.9865303150221851 and parameters: {'layer1': 34, 'layer2': 438, 'layer3': 76, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0006563893913926666}. Best is trial 22 with value: 0.988728252310335.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:16:01<6:40:36, 6009.00s/it]

[I 2026-02-21 08:26:49,884] Trial 24 finished with value: 0.9881140908847623 and parameters: {'layer1': 175, 'layer2': 269, 'layer3': 48, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0021254949060147714}. Best is trial 22 with value: 0.988728252310335.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:16:13<6:40:36, 6009.00s/it]

[I 2026-02-21 08:27:02,598] Trial 25 finished with value: 0.9880920438844049 and parameters: {'layer1': 60, 'layer2': 339, 'layer3': 54, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0004459448091792058}. Best is trial 22 with value: 0.988728252310335.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:16:34<6:40:36, 6009.00s/it]

[I 2026-02-21 08:27:23,075] Trial 26 finished with value: 0.9871270321656478 and parameters: {'layer1': 240, 'layer2': 393, 'layer3': 119, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.00015812393228767672}. Best is trial 22 with value: 0.988728252310335.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:16:46<6:40:36, 6009.00s/it]

[I 2026-02-21 08:27:34,922] Trial 27 finished with value: 0.9845981377851871 and parameters: {'layer1': 117, 'layer2': 490, 'layer3': 187, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.005327690485050958}. Best is trial 22 with value: 0.988728252310335.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:16:58<6:40:36, 6009.00s/it]

[I 2026-02-21 08:27:47,801] Trial 28 finished with value: 0.9884353208550666 and parameters: {'layer1': 53, 'layer2': 153, 'layer3': 235, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0012864779406202684}. Best is trial 22 with value: 0.988728252310335.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:17:07<6:40:36, 6009.00s/it]

[I 2026-02-21 08:27:56,300] Trial 29 finished with value: 0.9845981377851871 and parameters: {'layer1': 153, 'layer2': 434, 'layer3': 14, 'activation': 'identity', 'solver': 'sgd', 'lr': 0.0006445939188811416}. Best is trial 22 with value: 0.988728252310335.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:17:26<6:40:36, 6009.00s/it]

[I 2026-02-21 08:28:15,086] Trial 30 finished with value: 0.9884353208550666 and parameters: {'layer1': 307, 'layer2': 407, 'layer3': 146, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0008322040239415358}. Best is trial 22 with value: 0.988728252310335.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:17:40<6:40:36, 6009.00s/it]

[I 2026-02-21 08:28:29,058] Trial 31 finished with value: 0.9884628890732239 and parameters: {'layer1': 56, 'layer2': 127, 'layer3': 270, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0014604842839809448}. Best is trial 22 with value: 0.988728252310335.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:17:51<6:40:36, 6009.00s/it]

[I 2026-02-21 08:28:40,518] Trial 32 finished with value: 0.9886866072283839 and parameters: {'layer1': 10, 'layer2': 16, 'layer3': 264, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0019987119535567434}. Best is trial 22 with value: 0.988728252310335.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:18:03<6:40:36, 6009.00s/it]

[I 2026-02-21 08:28:52,001] Trial 33 finished with value: 0.9867965405418291 and parameters: {'layer1': 13, 'layer2': 19, 'layer3': 277, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00211889033300037}. Best is trial 22 with value: 0.988728252310335.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:18:16<6:40:36, 6009.00s/it]

[I 2026-02-21 08:29:05,736] Trial 34 finished with value: 0.9888053427630099 and parameters: {'layer1': 54, 'layer2': 150, 'layer3': 312, 'activation': 'relu', 'solver': 'adam', 'lr': 0.009801952578121956}. Best is trial 34 with value: 0.9888053427630099.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:18:24<6:40:36, 6009.00s/it]

[I 2026-02-21 08:29:13,576] Trial 35 finished with value: 0.9845981377851871 and parameters: {'layer1': 53, 'layer2': 123, 'layer3': 335, 'activation': 'relu', 'solver': 'sgd', 'lr': 0.009662386337064175}. Best is trial 34 with value: 0.9888053427630099.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:18:35<6:40:36, 6009.00s/it]

[I 2026-02-21 08:29:24,549] Trial 36 finished with value: 0.988728252310335 and parameters: {'layer1': 12, 'layer2': 116, 'layer3': 362, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0044555448171424514}. Best is trial 34 with value: 0.9888053427630099.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:18:45<6:40:36, 6009.00s/it]

[I 2026-02-21 08:29:34,636] Trial 37 finished with value: 0.9884353208550666 and parameters: {'layer1': 13, 'layer2': 14, 'layer3': 363, 'activation': 'relu', 'solver': 'adam', 'lr': 0.004647334731314249}. Best is trial 34 with value: 0.9888053427630099.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:18:56<6:40:36, 6009.00s/it]

[I 2026-02-21 08:29:45,754] Trial 38 finished with value: 0.9845981377851871 and parameters: {'layer1': 410, 'layer2': 85, 'layer3': 382, 'activation': 'relu', 'solver': 'sgd', 'lr': 0.005740253636824055}. Best is trial 34 with value: 0.9888053427630099.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:19:11<6:40:36, 6009.00s/it]

[I 2026-02-21 08:30:00,500] Trial 39 finished with value: 0.9845981377851871 and parameters: {'layer1': 117, 'layer2': 216, 'layer3': 305, 'activation': 'relu', 'solver': 'adam', 'lr': 1.1154511872004836e-06}. Best is trial 34 with value: 0.9888053427630099.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:19:18<6:40:36, 6009.00s/it]

[I 2026-02-21 08:30:07,797] Trial 40 finished with value: 0.9845981377851871 and parameters: {'layer1': 40, 'layer2': 165, 'layer3': 404, 'activation': 'relu', 'solver': 'sgd', 'lr': 0.003048716919222235}. Best is trial 34 with value: 0.9888053427630099.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:19:31<6:40:36, 6009.00s/it]

[I 2026-02-21 08:30:20,183] Trial 41 finished with value: 0.987801883947051 and parameters: {'layer1': 62, 'layer2': 132, 'layer3': 296, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0014509186036928132}. Best is trial 34 with value: 0.9888053427630099.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:19:42<6:40:36, 6009.00s/it]

[I 2026-02-21 08:30:31,084] Trial 42 finished with value: 0.9890426695458885 and parameters: {'layer1': 10, 'layer2': 88, 'layer3': 245, 'activation': 'relu', 'solver': 'adam', 'lr': 0.005889879515252965}. Best is trial 42 with value: 0.9890426695458885.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:19:52<6:40:36, 6009.00s/it]

[I 2026-02-21 08:30:41,766] Trial 43 finished with value: 0.9905634058126103 and parameters: {'layer1': 19, 'layer2': 83, 'layer3': 455, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0063708249195887825}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:20:04<6:40:36, 6009.00s/it]

[I 2026-02-21 08:30:53,030] Trial 44 finished with value: 0.9888449676762343 and parameters: {'layer1': 33, 'layer2': 90, 'layer3': 469, 'activation': 'relu', 'solver': 'adam', 'lr': 0.006414953751189193}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:20:18<6:40:36, 6009.00s/it]

[I 2026-02-21 08:31:06,957] Trial 45 finished with value: 0.9897828079908748 and parameters: {'layer1': 75, 'layer2': 90, 'layer3': 462, 'activation': 'relu', 'solver': 'adam', 'lr': 0.006900375804464948}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:20:31<6:40:36, 6009.00s/it]

[I 2026-02-21 08:31:20,350] Trial 46 finished with value: 0.9901260849615365 and parameters: {'layer1': 73, 'layer2': 83, 'layer3': 460, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00979443899824435}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:20:41<6:40:36, 6009.00s/it]

[I 2026-02-21 08:31:30,070] Trial 47 finished with value: 0.9845981377851871 and parameters: {'layer1': 113, 'layer2': 83, 'layer3': 460, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.008215242882776362}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:20:50<6:40:36, 6009.00s/it]

[I 2026-02-21 08:31:39,657] Trial 48 finished with value: 0.9845981377851871 and parameters: {'layer1': 74, 'layer2': 39, 'layer3': 456, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.006134229154076902}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:20:59<6:40:36, 6009.00s/it]

[I 2026-02-21 08:31:48,557] Trial 49 finished with value: 0.9845981377851871 and parameters: {'layer1': 167, 'layer2': 89, 'layer3': 482, 'activation': 'relu', 'solver': 'sgd', 'lr': 0.007024879101730406}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:21:10<6:40:36, 6009.00s/it]

[I 2026-02-21 08:31:58,980] Trial 50 finished with value: 0.9888449676762343 and parameters: {'layer1': 31, 'layer2': 55, 'layer3': 417, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0041898480940835555}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:21:22<6:40:36, 6009.00s/it]

[I 2026-02-21 08:32:11,138] Trial 51 finished with value: 0.9904033649229476 and parameters: {'layer1': 32, 'layer2': 63, 'layer3': 428, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0044122944708538895}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:21:34<6:40:36, 6009.00s/it]

[I 2026-02-21 08:32:23,775] Trial 52 finished with value: 0.9888053427630099 and parameters: {'layer1': 30, 'layer2': 97, 'layer3': 439, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00637166342090395}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:21:48<6:40:36, 6009.00s/it]

[I 2026-02-21 08:32:37,555] Trial 53 finished with value: 0.9890566291363271 and parameters: {'layer1': 76, 'layer2': 70, 'layer3': 472, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00280426225163893}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:21:59<6:40:36, 6009.00s/it]

[I 2026-02-21 08:32:48,043] Trial 54 finished with value: 0.9845981377851871 and parameters: {'layer1': 75, 'layer2': 60, 'layer3': 441, 'activation': 'relu', 'solver': 'adam', 'lr': 7.27293886866522e-06}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:22:12<6:40:36, 6009.00s/it]

[I 2026-02-21 08:33:00,991] Trial 55 finished with value: 0.9884353208550666 and parameters: {'layer1': 100, 'layer2': 75, 'layer3': 500, 'activation': 'relu', 'solver': 'adam', 'lr': 0.002664065034479916}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:22:21<6:40:36, 6009.00s/it]

[I 2026-02-21 08:33:10,843] Trial 56 finished with value: 0.9845981377851871 and parameters: {'layer1': 141, 'layer2': 40, 'layer3': 405, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.003942127126919278}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:22:31<6:40:36, 6009.00s/it]

[I 2026-02-21 08:33:20,749] Trial 57 finished with value: 0.9845981377851871 and parameters: {'layer1': 77, 'layer2': 188, 'layer3': 480, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0010500879876542506}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:22:50<6:40:36, 6009.00s/it]

[I 2026-02-21 08:33:38,992] Trial 58 finished with value: 0.9880920438844049 and parameters: {'layer1': 367, 'layer2': 39, 'layer3': 448, 'activation': 'relu', 'solver': 'adam', 'lr': 0.002169613095449547}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:23:03<6:40:36, 6009.00s/it]

[I 2026-02-21 08:33:52,390] Trial 59 finished with value: 0.9898112333699686 and parameters: {'layer1': 101, 'layer2': 105, 'layer3': 427, 'activation': 'relu', 'solver': 'adam', 'lr': 0.009903397605775646}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:23:17<6:40:36, 6009.00s/it]

[I 2026-02-21 08:34:06,475] Trial 60 finished with value: 0.9901539291048668 and parameters: {'layer1': 132, 'layer2': 109, 'layer3': 425, 'activation': 'relu', 'solver': 'adam', 'lr': 0.009426248274046145}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:23:29<6:40:36, 6009.00s/it]

[I 2026-02-21 08:34:17,851] Trial 61 finished with value: 0.9880648724802885 and parameters: {'layer1': 103, 'layer2': 104, 'layer3': 414, 'activation': 'relu', 'solver': 'adam', 'lr': 0.007614534903169343}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:23:41<6:40:36, 6009.00s/it]

[I 2026-02-21 08:34:30,832] Trial 62 finished with value: 0.9897828079908748 and parameters: {'layer1': 123, 'layer2': 140, 'layer3': 388, 'activation': 'relu', 'solver': 'adam', 'lr': 0.003712224954074935}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:23:55<6:40:36, 6009.00s/it]

[I 2026-02-21 08:34:44,659] Trial 63 finished with value: 0.9893993248712253 and parameters: {'layer1': 128, 'layer2': 149, 'layer3': 389, 'activation': 'relu', 'solver': 'adam', 'lr': 0.009426849488006355}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:24:10<6:40:36, 6009.00s/it]

[I 2026-02-21 08:34:59,285] Trial 64 finished with value: 0.9884353208550666 and parameters: {'layer1': 187, 'layer2': 110, 'layer3': 428, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0040562833910384516}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:24:20<6:40:36, 6009.00s/it]

[I 2026-02-21 08:35:09,752] Trial 65 finished with value: 0.9845981377851871 and parameters: {'layer1': 159, 'layer2': 135, 'layer3': 429, 'activation': 'relu', 'solver': 'adam', 'lr': 4.768117300637764e-05}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:24:33<6:40:36, 6009.00s/it]

[I 2026-02-21 08:35:22,653] Trial 66 finished with value: 0.9884573678554238 and parameters: {'layer1': 100, 'layer2': 186, 'layer3': 396, 'activation': 'relu', 'solver': 'adam', 'lr': 0.003551910547429988}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:24:43<6:40:36, 6009.00s/it]

[I 2026-02-21 08:35:32,282] Trial 67 finished with value: 0.9845981377851871 and parameters: {'layer1': 128, 'layer2': 49, 'layer3': 364, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.009992626719438541}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:24:55<6:40:36, 6009.00s/it]

[I 2026-02-21 08:35:44,742] Trial 68 finished with value: 0.9845981377851871 and parameters: {'layer1': 198, 'layer2': 69, 'layer3': 342, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.005181883060271571}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:25:19<6:40:36, 6009.00s/it]

[I 2026-02-21 08:36:08,393] Trial 69 finished with value: 0.7875409377665192 and parameters: {'layer1': 43, 'layer2': 171, 'layer3': 490, 'activation': 'relu', 'solver': 'sgd', 'lr': 1.2474847159244003e-05}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:25:37<6:40:36, 6009.00s/it]

[I 2026-02-21 08:36:26,725] Trial 70 finished with value: 0.9890902138449347 and parameters: {'layer1': 147, 'layer2': 244, 'layer3': 461, 'activation': 'relu', 'solver': 'adam', 'lr': 0.007368586487615162}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:25:50<6:40:36, 6009.00s/it]

[I 2026-02-21 08:36:39,695] Trial 71 finished with value: 0.988702900649392 and parameters: {'layer1': 92, 'layer2': 152, 'layer3': 398, 'activation': 'relu', 'solver': 'adam', 'lr': 0.004968147605139837}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:26:05<6:40:36, 6009.00s/it]

[I 2026-02-21 08:36:54,666] Trial 72 finished with value: 0.9892882023398567 and parameters: {'layer1': 136, 'layer2': 106, 'layer3': 383, 'activation': 'relu', 'solver': 'adam', 'lr': 0.009774713898658392}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:26:19<6:40:36, 6009.00s/it]

[I 2026-02-21 08:37:08,059] Trial 73 finished with value: 0.989188244646896 and parameters: {'layer1': 127, 'layer2': 140, 'layer3': 427, 'activation': 'relu', 'solver': 'adam', 'lr': 0.007791117812969113}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:26:30<6:40:36, 6009.00s/it]

[I 2026-02-21 08:37:19,725] Trial 74 finished with value: 0.9884620657923483 and parameters: {'layer1': 67, 'layer2': 121, 'layer3': 448, 'activation': 'relu', 'solver': 'adam', 'lr': 0.003404143148239898}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:26:44<6:40:36, 6009.00s/it]

[I 2026-02-21 08:37:32,881] Trial 75 finished with value: 0.9880788266860672 and parameters: {'layer1': 113, 'layer2': 28, 'layer3': 350, 'activation': 'relu', 'solver': 'adam', 'lr': 0.002411387466548719}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:27:01<6:40:36, 6009.00s/it]

[I 2026-02-21 08:37:50,727] Trial 76 finished with value: 0.9898088015789688 and parameters: {'layer1': 235, 'layer2': 211, 'layer3': 390, 'activation': 'identity', 'solver': 'adam', 'lr': 0.004974062139190659}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:27:17<6:40:36, 6009.00s/it]

[I 2026-02-21 08:38:06,554] Trial 77 finished with value: 0.9880920438844049 and parameters: {'layer1': 251, 'layer2': 280, 'layer3': 409, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0016101502770558094}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:27:40<6:40:36, 6009.00s/it]

[I 2026-02-21 08:38:29,130] Trial 78 finished with value: 0.9897828079908748 and parameters: {'layer1': 300, 'layer2': 197, 'layer3': 434, 'activation': 'identity', 'solver': 'adam', 'lr': 0.004940095798764879}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:28:02<6:40:36, 6009.00s/it]

[I 2026-02-21 08:38:51,686] Trial 79 finished with value: 0.9894731157288208 and parameters: {'layer1': 353, 'layer2': 170, 'layer3': 373, 'activation': 'identity', 'solver': 'adam', 'lr': 0.006958970914674225}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:29:12<6:40:36, 6009.00s/it]

[I 2026-02-21 08:40:00,967] Trial 80 finished with value: 0.984374179293512 and parameters: {'layer1': 235, 'layer2': 234, 'layer3': 453, 'activation': 'identity', 'solver': 'sgd', 'lr': 3.504595796801002e-06}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:29:31<6:40:36, 6009.00s/it]

[I 2026-02-21 08:40:20,426] Trial 81 finished with value: 0.9884353208550666 and parameters: {'layer1': 310, 'layer2': 216, 'layer3': 438, 'activation': 'identity', 'solver': 'adam', 'lr': 0.004849240664090046}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:29:52<6:40:36, 6009.00s/it]

[I 2026-02-21 08:40:41,075] Trial 82 finished with value: 0.9880920438844049 and parameters: {'layer1': 270, 'layer2': 193, 'layer3': 420, 'activation': 'identity', 'solver': 'adam', 'lr': 0.003487460288128058}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:30:12<6:40:36, 6009.00s/it]

[I 2026-02-21 08:41:01,613] Trial 83 finished with value: 0.9880920438844049 and parameters: {'layer1': 329, 'layer2': 205, 'layer3': 467, 'activation': 'identity', 'solver': 'adam', 'lr': 0.005543710174240353}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:30:29<6:40:36, 6009.00s/it]

[I 2026-02-21 08:41:17,963] Trial 84 finished with value: 0.9880920438844049 and parameters: {'layer1': 295, 'layer2': 75, 'layer3': 485, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0019273129714462414}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:30:40<6:40:36, 6009.00s/it]

[I 2026-02-21 08:41:29,088] Trial 85 finished with value: 0.9886866072283839 and parameters: {'layer1': 45, 'layer2': 100, 'layer3': 428, 'activation': 'identity', 'solver': 'adam', 'lr': 0.007808594667415734}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:31:03<6:40:36, 6009.00s/it]

[I 2026-02-21 08:41:52,723] Trial 86 finished with value: 0.9890298841990456 and parameters: {'layer1': 350, 'layer2': 124, 'layer3': 441, 'activation': 'identity', 'solver': 'adam', 'lr': 0.004683567907538546}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:31:18<6:40:36, 6009.00s/it]

[I 2026-02-21 08:42:06,889] Trial 87 finished with value: 0.9845981377851871 and parameters: {'layer1': 284, 'layer2': 162, 'layer3': 475, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.006166223814292809}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:31:34<6:40:36, 6009.00s/it]

[I 2026-02-21 08:42:22,899] Trial 88 finished with value: 0.9883696392017018 and parameters: {'layer1': 218, 'layer2': 52, 'layer3': 392, 'activation': 'relu', 'solver': 'adam', 'lr': 0.003035823864719351}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:31:44<6:40:36, 6009.00s/it]

[I 2026-02-21 08:42:33,128] Trial 89 finished with value: 0.9845981377851871 and parameters: {'layer1': 84, 'layer2': 203, 'layer3': 416, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.004151753956287302}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:31:56<6:40:36, 6009.00s/it]

[I 2026-02-21 08:42:45,427] Trial 90 finished with value: 0.9871270321656478 and parameters: {'layer1': 65, 'layer2': 111, 'layer3': 461, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0002282946875489527}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:32:19<6:40:36, 6009.00s/it]

[I 2026-02-21 08:43:08,588] Trial 91 finished with value: 0.9896211094531921 and parameters: {'layer1': 397, 'layer2': 174, 'layer3': 367, 'activation': 'identity', 'solver': 'adam', 'lr': 0.007518429242852337}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:32:40<6:40:36, 6009.00s/it]

[I 2026-02-21 08:43:29,502] Trial 92 finished with value: 0.9877823516223507 and parameters: {'layer1': 445, 'layer2': 232, 'layer3': 406, 'activation': 'identity', 'solver': 'adam', 'lr': 0.008620512332112695}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:33:11<6:40:36, 6009.00s/it]

[I 2026-02-21 08:44:00,791] Trial 93 finished with value: 0.9901260849615365 and parameters: {'layer1': 385, 'layer2': 144, 'layer3': 374, 'activation': 'identity', 'solver': 'adam', 'lr': 0.006310286098044946}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:33:45<6:40:36, 6009.00s/it]

[I 2026-02-21 08:44:33,866] Trial 94 finished with value: 0.9903613614465352 and parameters: {'layer1': 447, 'layer2': 141, 'layer3': 352, 'activation': 'identity', 'solver': 'adam', 'lr': 0.005890736759856096}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:34:10<6:40:36, 6009.00s/it]

[I 2026-02-21 08:44:59,676] Trial 95 finished with value: 0.9884353208550666 and parameters: {'layer1': 477, 'layer2': 140, 'layer3': 377, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00609685146840258}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:34:33<6:40:36, 6009.00s/it]

[I 2026-02-21 08:45:22,623] Trial 96 finished with value: 0.9893731611697072 and parameters: {'layer1': 436, 'layer2': 79, 'layer3': 352, 'activation': 'relu', 'solver': 'adam', 'lr': 0.002480415311864105}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:34:41<6:40:36, 6009.00s/it]

[I 2026-02-21 08:45:29,906] Trial 97 finished with value: 0.9845981377851871 and parameters: {'layer1': 22, 'layer2': 93, 'layer3': 323, 'activation': 'identity', 'solver': 'sgd', 'lr': 0.0038556305313567703}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:35:03<6:40:36, 6009.00s/it]

[I 2026-02-21 08:45:52,635] Trial 98 finished with value: 0.9884628890732239 and parameters: {'layer1': 452, 'layer2': 117, 'layer3': 386, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00678870519345553}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:35:30<6:40:36, 6009.00s/it]

[I 2026-02-21 08:46:19,529] Trial 99 finished with value: 0.9901260849615365 and parameters: {'layer1': 410, 'layer2': 61, 'layer3': 490, 'activation': 'relu', 'solver': 'adam', 'lr': 0.008435545514377266}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:35:53<6:40:36, 6009.00s/it]

[I 2026-02-21 08:46:42,776] Trial 100 finished with value: 0.989188244646896 and parameters: {'layer1': 413, 'layer2': 67, 'layer3': 491, 'activation': 'relu', 'solver': 'adam', 'lr': 0.009982999859654866}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:36:15<6:40:36, 6009.00s/it]

[I 2026-02-21 08:47:04,285] Trial 101 finished with value: 0.9871270321656478 and parameters: {'layer1': 421, 'layer2': 131, 'layer3': 472, 'activation': 'relu', 'solver': 'adam', 'lr': 0.005786181259028028}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:36:34<6:40:36, 6009.00s/it]

[I 2026-02-21 08:47:23,220] Trial 102 finished with value: 0.9880920438844049 and parameters: {'layer1': 382, 'layer2': 63, 'layer3': 449, 'activation': 'relu', 'solver': 'adam', 'lr': 0.008100044435398756}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:36:58<6:40:36, 6009.00s/it]

[I 2026-02-21 08:47:47,739] Trial 103 finished with value: 0.9887001308255206 and parameters: {'layer1': 459, 'layer2': 102, 'layer3': 419, 'activation': 'relu', 'solver': 'adam', 'lr': 0.005282436477641857}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:37:22<6:40:36, 6009.00s/it]

[I 2026-02-21 08:48:11,426] Trial 104 finished with value: 0.9883904385634665 and parameters: {'layer1': 399, 'layer2': 85, 'layer3': 495, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0033960499820804074}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:37:46<6:40:36, 6009.00s/it]

[I 2026-02-21 08:48:34,974] Trial 105 finished with value: 0.9888053427630099 and parameters: {'layer1': 438, 'layer2': 27, 'layer3': 400, 'activation': 'relu', 'solver': 'adam', 'lr': 0.008462247111797166}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:37:59<6:40:36, 6009.00s/it]

[I 2026-02-21 08:48:48,396] Trial 106 finished with value: 0.9884353208550666 and parameters: {'layer1': 103, 'layer2': 307, 'layer3': 462, 'activation': 'relu', 'solver': 'adam', 'lr': 0.001204302443280241}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:38:17<6:40:36, 6009.00s/it]

[I 2026-02-21 08:49:06,384] Trial 107 finished with value: 0.9845981377851871 and parameters: {'layer1': 496, 'layer2': 142, 'layer3': 445, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.004255634063426651}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:38:33<6:40:36, 6009.00s/it]

[I 2026-02-21 08:49:22,398] Trial 108 finished with value: 0.9888053427630099 and parameters: {'layer1': 178, 'layer2': 93, 'layer3': 478, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0066066669037086025}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:38:47<6:40:36, 6009.00s/it]

[I 2026-02-21 08:49:36,671] Trial 109 finished with value: 0.9845981377851871 and parameters: {'layer1': 386, 'layer2': 43, 'layer3': 409, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0004889063841856422}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:38:58<6:40:36, 6009.00s/it]

[I 2026-02-21 08:49:46,969] Trial 110 finished with value: 0.9880920438844049 and parameters: {'layer1': 21, 'layer2': 118, 'layer3': 207, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0028096634117702893}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:39:19<6:40:36, 6009.00s/it]

[I 2026-02-21 08:50:08,243] Trial 111 finished with value: 0.9884353208550666 and parameters: {'layer1': 347, 'layer2': 152, 'layer3': 436, 'activation': 'identity', 'solver': 'adam', 'lr': 0.004774172514139679}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:39:32<6:40:36, 6009.00s/it]

[I 2026-02-21 08:50:20,855] Trial 112 finished with value: 0.9893952081700645 and parameters: {'layer1': 37, 'layer2': 161, 'layer3': 434, 'activation': 'identity', 'solver': 'adam', 'lr': 0.005335549994374105}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:39:45<6:40:36, 6009.00s/it]

[I 2026-02-21 08:50:34,130] Trial 113 finished with value: 0.9884353208550666 and parameters: {'layer1': 119, 'layer2': 224, 'layer3': 453, 'activation': 'identity', 'solver': 'adam', 'lr': 0.008865987393931438}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:40:04<6:40:36, 6009.00s/it]

[I 2026-02-21 08:50:53,637] Trial 114 finished with value: 0.9880920438844049 and parameters: {'layer1': 424, 'layer2': 255, 'layer3': 424, 'activation': 'identity', 'solver': 'adam', 'lr': 0.006915950010585675}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:40:26<6:40:36, 6009.00s/it]

[I 2026-02-21 08:51:15,049] Trial 115 finished with value: 0.9880920438844049 and parameters: {'layer1': 470, 'layer2': 57, 'layer3': 355, 'activation': 'relu', 'solver': 'adam', 'lr': 0.004386893171615693}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:40:33<6:40:36, 6009.00s/it]

[I 2026-02-21 08:51:22,557] Trial 116 finished with value: 0.9845981377851871 and parameters: {'layer1': 56, 'layer2': 178, 'layer3': 376, 'activation': 'identity', 'solver': 'sgd', 'lr': 0.005998996593440008}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:40:47<6:40:36, 6009.00s/it]

[I 2026-02-21 08:51:36,706] Trial 117 finished with value: 0.9888686951184038 and parameters: {'layer1': 91, 'layer2': 128, 'layer3': 337, 'activation': 'relu', 'solver': 'adam', 'lr': 0.009903604214886995}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:40:59<6:40:36, 6009.00s/it]

[I 2026-02-21 08:51:48,382] Trial 118 finished with value: 0.9884353208550666 and parameters: {'layer1': 79, 'layer2': 74, 'layer3': 388, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0017943287549960275}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:41:22<6:40:36, 6009.00s/it]

[I 2026-02-21 08:52:11,035] Trial 119 finished with value: 0.9894268930893828 and parameters: {'layer1': 370, 'layer2': 107, 'layer3': 468, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0075599326553997225}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:41:35<6:40:36, 6009.00s/it]

[I 2026-02-21 08:52:24,643] Trial 120 finished with value: 0.9882132112100308 and parameters: {'layer1': 155, 'layer2': 97, 'layer3': 286, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0036121954112431306}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:42:04<6:40:36, 6009.00s/it]

[I 2026-02-21 08:52:53,695] Trial 121 finished with value: 0.9894007293878646 and parameters: {'layer1': 401, 'layer2': 182, 'layer3': 368, 'activation': 'identity', 'solver': 'adam', 'lr': 0.007165893493778595}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:42:31<6:40:36, 6009.00s/it]

[I 2026-02-21 08:53:20,341] Trial 122 finished with value: 0.9895590898357151 and parameters: {'layer1': 425, 'layer2': 192, 'layer3': 398, 'activation': 'identity', 'solver': 'adam', 'lr': 0.005149363870371102}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:42:50<6:40:36, 6009.00s/it]

[I 2026-02-21 08:53:39,192] Trial 123 finished with value: 0.9880920438844049 and parameters: {'layer1': 389, 'layer2': 171, 'layer3': 484, 'activation': 'identity', 'solver': 'adam', 'lr': 0.008091436627305736}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:43:09<6:40:36, 6009.00s/it]

[I 2026-02-21 08:53:58,820] Trial 124 finished with value: 0.9884574109692965 and parameters: {'layer1': 361, 'layer2': 146, 'layer3': 360, 'activation': 'identity', 'solver': 'adam', 'lr': 0.005813985026528818}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:43:19<6:40:36, 6009.00s/it]

[I 2026-02-21 08:54:08,175] Trial 125 finished with value: 0.9845981377851871 and parameters: {'layer1': 68, 'layer2': 200, 'layer3': 323, 'activation': 'identity', 'solver': 'adam', 'lr': 1.7250476521972942e-05}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:43:41<6:40:36, 6009.00s/it]

[I 2026-02-21 08:54:29,908] Trial 126 finished with value: 0.9897844884326871 and parameters: {'layer1': 376, 'layer2': 132, 'layer3': 414, 'activation': 'relu', 'solver': 'adam', 'lr': 0.004334613737154064}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:44:01<6:40:36, 6009.00s/it]

[I 2026-02-21 08:54:49,954] Trial 127 finished with value: 0.9880920438844049 and parameters: {'layer1': 324, 'layer2': 135, 'layer3': 433, 'activation': 'relu', 'solver': 'adam', 'lr': 0.004498006957398021}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:44:19<6:40:36, 6009.00s/it]

[I 2026-02-21 08:55:08,493] Trial 128 finished with value: 0.9881055674815415 and parameters: {'layer1': 372, 'layer2': 81, 'layer3': 412, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0024423069694967767}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:44:35<6:40:36, 6009.00s/it]

[I 2026-02-21 08:55:24,314] Trial 129 finished with value: 0.9845981377851871 and parameters: {'layer1': 341, 'layer2': 158, 'layer3': 457, 'activation': 'relu', 'solver': 'adam', 'lr': 8.73669841632141e-05}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:44:52<6:40:36, 6009.00s/it]

[I 2026-02-21 08:55:41,757] Trial 130 finished with value: 0.9891899250887081 and parameters: {'layer1': 226, 'layer2': 114, 'layer3': 424, 'activation': 'relu', 'solver': 'adam', 'lr': 0.003014743839796637}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:45:17<6:40:36, 6009.00s/it]

[I 2026-02-21 08:56:06,303] Trial 131 finished with value: 0.9892778324825304 and parameters: {'layer1': 394, 'layer2': 177, 'layer3': 373, 'activation': 'relu', 'solver': 'adam', 'lr': 0.007103576273994172}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:45:38<6:40:36, 6009.00s/it]

[I 2026-02-21 08:56:27,677] Trial 132 finished with value: 0.9901277654033487 and parameters: {'layer1': 410, 'layer2': 123, 'layer3': 396, 'activation': 'identity', 'solver': 'adam', 'lr': 0.008774634253673651}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:45:52<6:40:36, 6009.00s/it]

[I 2026-02-21 08:56:40,858] Trial 133 finished with value: 0.9901260849615365 and parameters: {'layer1': 45, 'layer2': 126, 'layer3': 393, 'activation': 'relu', 'solver': 'adam', 'lr': 0.009909884831096923}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:46:05<6:40:36, 6009.00s/it]

[I 2026-02-21 08:56:53,954] Trial 134 finished with value: 0.9893731611697072 and parameters: {'layer1': 46, 'layer2': 123, 'layer3': 383, 'activation': 'relu', 'solver': 'adam', 'lr': 0.008634148832170853}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:46:16<6:40:36, 6009.00s/it]

[I 2026-02-21 08:57:05,126] Trial 135 finished with value: 0.9884573678554238 and parameters: {'layer1': 25, 'layer2': 108, 'layer3': 395, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0097866504979428}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:46:38<6:40:36, 6009.00s/it]

[I 2026-02-21 08:57:27,372] Trial 136 finished with value: 0.9896181577937269 and parameters: {'layer1': 412, 'layer2': 91, 'layer3': 408, 'activation': 'relu', 'solver': 'adam', 'lr': 0.006008293404851563}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:46:45<6:40:36, 6009.00s/it]

[I 2026-02-21 08:57:34,840] Trial 137 finished with value: 0.9845981377851871 and parameters: {'layer1': 58, 'layer2': 128, 'layer3': 401, 'activation': 'relu', 'solver': 'sgd', 'lr': 0.0038349168378668495}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:46:56<6:40:36, 6009.00s/it]

[I 2026-02-21 08:57:45,570] Trial 138 finished with value: 0.9893731611697072 and parameters: {'layer1': 32, 'layer2': 62, 'layer3': 446, 'activation': 'relu', 'solver': 'adam', 'lr': 0.006743924572972336}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:47:06<6:40:36, 6009.00s/it]

[I 2026-02-21 08:57:54,935] Trial 139 finished with value: 0.9845981377851871 and parameters: {'layer1': 110, 'layer2': 101, 'layer3': 418, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.007999637605961379}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:47:18<6:40:36, 6009.00s/it]

[I 2026-02-21 08:58:07,825] Trial 140 finished with value: 0.9893731611697072 and parameters: {'layer1': 88, 'layer2': 141, 'layer3': 389, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0052564977133811985}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:47:41<6:40:36, 6009.00s/it]

[I 2026-02-21 08:58:30,090] Trial 141 finished with value: 0.9884353208550666 and parameters: {'layer1': 380, 'layer2': 117, 'layer3': 435, 'activation': 'identity', 'solver': 'adam', 'lr': 0.004739712801298146}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:47:59<6:40:36, 6009.00s/it]

[I 2026-02-21 08:58:48,668] Trial 142 finished with value: 0.9845981377851871 and parameters: {'layer1': 431, 'layer2': 81, 'layer3': 414, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.009985316214121165}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:48:16<6:40:36, 6009.00s/it]

[I 2026-02-21 08:59:05,157] Trial 143 finished with value: 0.98776229051088 and parameters: {'layer1': 265, 'layer2': 136, 'layer3': 452, 'activation': 'relu', 'solver': 'adam', 'lr': 0.006587387801211751}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:48:27<6:40:36, 6009.00s/it]

[I 2026-02-21 08:59:15,956] Trial 144 finished with value: 0.9894349217127278 and parameters: {'layer1': 45, 'layer2': 51, 'layer3': 424, 'activation': 'relu', 'solver': 'adam', 'lr': 0.008283264522751929}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:48:46<6:40:36, 6009.00s/it]

[I 2026-02-21 08:59:35,109] Trial 145 finished with value: 0.9891899250887081 and parameters: {'layer1': 307, 'layer2': 70, 'layer3': 500, 'activation': 'identity', 'solver': 'adam', 'lr': 0.005464610814766729}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:49:09<6:40:36, 6009.00s/it]

[I 2026-02-21 08:59:58,390] Trial 146 finished with value: 0.9892917135085337 and parameters: {'layer1': 451, 'layer2': 155, 'layer3': 441, 'activation': 'relu', 'solver': 'adam', 'lr': 0.003319021349535726}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:49:20<6:40:36, 6009.00s/it]

[I 2026-02-21 09:00:09,296] Trial 147 finished with value: 0.9884620657923483 and parameters: {'layer1': 67, 'layer2': 89, 'layer3': 467, 'activation': 'identity', 'solver': 'adam', 'lr': 0.004121261788976253}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:49:30<6:40:36, 6009.00s/it]

[I 2026-02-21 09:00:19,619] Trial 148 finished with value: 0.9890426695458885 and parameters: {'layer1': 15, 'layer2': 110, 'layer3': 378, 'activation': 'relu', 'solver': 'adam', 'lr': 0.006645270667984218}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:49:52<6:40:36, 6009.00s/it]

[I 2026-02-21 09:00:41,693] Trial 149 finished with value: 0.9881048292312478 and parameters: {'layer1': 416, 'layer2': 247, 'layer3': 408, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00833028495330625}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:50:16<6:40:36, 6009.00s/it]

[I 2026-02-21 09:01:04,873] Trial 150 finished with value: 0.9890265461092133 and parameters: {'layer1': 407, 'layer2': 98, 'layer3': 344, 'activation': 'identity', 'solver': 'adam', 'lr': 0.009968360652368266}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:50:41<6:40:36, 6009.00s/it]

[I 2026-02-21 09:01:30,094] Trial 151 finished with value: 0.9893731611697072 and parameters: {'layer1': 400, 'layer2': 167, 'layer3': 364, 'activation': 'identity', 'solver': 'adam', 'lr': 0.007410238954139424}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:51:04<6:40:36, 6009.00s/it]

[I 2026-02-21 09:01:52,902] Trial 152 finished with value: 0.9890298841990456 and parameters: {'layer1': 336, 'layer2': 127, 'layer3': 395, 'activation': 'identity', 'solver': 'adam', 'lr': 0.005231925319831412}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:51:24<6:40:36, 6009.00s/it]

[I 2026-02-21 09:02:13,613] Trial 153 finished with value: 0.9888466481180463 and parameters: {'layer1': 381, 'layer2': 145, 'layer3': 386, 'activation': 'identity', 'solver': 'adam', 'lr': 0.005952077764930916}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:51:38<6:40:36, 6009.00s/it]

[I 2026-02-21 09:02:27,638] Trial 154 finished with value: 0.9895599469966514 and parameters: {'layer1': 99, 'layer2': 211, 'layer3': 430, 'activation': 'identity', 'solver': 'adam', 'lr': 0.007966596587953682}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:51:59<6:40:36, 6009.00s/it]

[I 2026-02-21 09:02:48,836] Trial 155 finished with value: 0.9884573678554238 and parameters: {'layer1': 252, 'layer2': 119, 'layer3': 365, 'activation': 'identity', 'solver': 'adam', 'lr': 0.004374249729288735}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:52:16<6:40:36, 6009.00s/it]

[I 2026-02-21 09:03:04,906] Trial 156 finished with value: 0.9874703091363095 and parameters: {'layer1': 290, 'layer2': 152, 'layer3': 375, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0066024586301852446}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:52:31<6:40:36, 6009.00s/it]

[I 2026-02-21 09:03:20,316] Trial 157 finished with value: 0.9884353208550666 and parameters: {'layer1': 207, 'layer2': 134, 'layer3': 405, 'activation': 'relu', 'solver': 'adam', 'lr': 0.008470643484068424}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:52:42<6:40:36, 6009.00s/it]

[I 2026-02-21 09:03:31,022] Trial 158 finished with value: 0.9845981377851871 and parameters: {'layer1': 394, 'layer2': 33, 'layer3': 458, 'activation': 'identity', 'solver': 'sgd', 'lr': 0.0048843540814855375}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:52:56<6:40:36, 6009.00s/it]

[I 2026-02-21 09:03:45,007] Trial 159 finished with value: 0.9904033649229476 and parameters: {'layer1': 74, 'layer2': 195, 'layer3': 474, 'activation': 'relu', 'solver': 'adam', 'lr': 0.003938501777200299}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:53:09<6:40:36, 6009.00s/it]

[I 2026-02-21 09:03:57,958] Trial 160 finished with value: 0.9881140908847623 and parameters: {'layer1': 72, 'layer2': 270, 'layer3': 473, 'activation': 'relu', 'solver': 'adam', 'lr': 0.003484190231815987}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:53:22<6:40:36, 6009.00s/it]

[I 2026-02-21 09:04:10,880] Trial 161 finished with value: 0.9887397242616915 and parameters: {'layer1': 37, 'layer2': 195, 'layer3': 487, 'activation': 'relu', 'solver': 'adam', 'lr': 0.006026231320071032}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:53:34<6:40:36, 6009.00s/it]

[I 2026-02-21 09:04:23,535] Trial 162 finished with value: 0.9890519311994028 and parameters: {'layer1': 51, 'layer2': 219, 'layer3': 478, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0041191677690768265}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:53:44<6:40:36, 6009.00s/it]

[I 2026-02-21 09:04:33,190] Trial 163 finished with value: 0.9845981377851871 and parameters: {'layer1': 90, 'layer2': 183, 'layer3': 448, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00013248435527393854}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:53:58<6:40:36, 6009.00s/it]

[I 2026-02-21 09:04:47,483] Trial 164 finished with value: 0.9894828565439765 and parameters: {'layer1': 121, 'layer2': 104, 'layer3': 421, 'activation': 'relu', 'solver': 'adam', 'lr': 0.009985304576421912}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:54:14<6:40:36, 6009.00s/it]

[I 2026-02-21 09:05:03,246] Trial 165 finished with value: 0.9845981377851871 and parameters: {'layer1': 359, 'layer2': 161, 'layer3': 465, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.007428246811233847}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:54:28<6:40:36, 6009.00s/it]

[I 2026-02-21 09:05:17,341] Trial 166 finished with value: 0.9884353208550666 and parameters: {'layer1': 142, 'layer2': 174, 'layer3': 439, 'activation': 'relu', 'solver': 'adam', 'lr': 0.002912959291672446}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:54:37<6:40:36, 6009.00s/it]

[I 2026-02-21 09:05:26,717] Trial 167 finished with value: 0.9845981377851871 and parameters: {'layer1': 76, 'layer2': 73, 'layer3': 398, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.005366620468050305}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:54:50<6:40:36, 6009.00s/it]

[I 2026-02-21 09:05:39,404] Trial 168 finished with value: 0.9887086973426138 and parameters: {'layer1': 62, 'layer2': 144, 'layer3': 355, 'activation': 'identity', 'solver': 'adam', 'lr': 0.007430318830333031}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:55:12<6:40:36, 6009.00s/it]

[I 2026-02-21 09:06:01,710] Trial 169 finished with value: 0.9877215955096268 and parameters: {'layer1': 440, 'layer2': 84, 'layer3': 384, 'activation': 'relu', 'solver': 'adam', 'lr': 0.004510120191296391}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:55:28<6:40:36, 6009.00s/it]

[I 2026-02-21 09:06:16,881] Trial 170 finished with value: 0.9845981377851871 and parameters: {'layer1': 372, 'layer2': 208, 'layer3': 431, 'activation': 'relu', 'solver': 'adam', 'lr': 5.875370715479899e-05}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:55:48<6:40:36, 6009.00s/it]

[I 2026-02-21 09:06:37,255] Trial 171 finished with value: 0.9884353208550666 and parameters: {'layer1': 414, 'layer2': 96, 'layer3': 412, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00564500000705169}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:56:09<6:40:36, 6009.00s/it]

[I 2026-02-21 09:06:58,248] Trial 172 finished with value: 0.9884353208550666 and parameters: {'layer1': 432, 'layer2': 88, 'layer3': 408, 'activation': 'relu', 'solver': 'adam', 'lr': 0.006315398536291442}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:56:29<6:40:36, 6009.00s/it]

[I 2026-02-21 09:07:18,606] Trial 173 finished with value: 0.9884353208550666 and parameters: {'layer1': 403, 'layer2': 64, 'layer3': 393, 'activation': 'relu', 'solver': 'adam', 'lr': 0.008407060656997893}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:56:53<6:40:36, 6009.00s/it]

[I 2026-02-21 09:07:42,440] Trial 174 finished with value: 0.9893952081700645 and parameters: {'layer1': 421, 'layer2': 114, 'layer3': 419, 'activation': 'relu', 'solver': 'adam', 'lr': 0.006292514712772061}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:57:15<6:40:36, 6009.00s/it]

[I 2026-02-21 09:08:04,651] Trial 175 finished with value: 0.9884353208550666 and parameters: {'layer1': 483, 'layer2': 124, 'layer3': 453, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0038094213205933296}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:57:39<6:40:36, 6009.00s/it]

[I 2026-02-21 09:08:28,793] Trial 176 finished with value: 0.9888061660438856 and parameters: {'layer1': 460, 'layer2': 78, 'layer3': 400, 'activation': 'identity', 'solver': 'adam', 'lr': 0.007145998248520539}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:58:03<6:40:36, 6009.00s/it]

[I 2026-02-21 09:08:52,325] Trial 177 finished with value: 0.9888449676762343 and parameters: {'layer1': 389, 'layer2': 229, 'layer3': 372, 'activation': 'relu', 'solver': 'adam', 'lr': 0.004905921508402933}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:58:17<6:40:36, 6009.00s/it]

[I 2026-02-21 09:09:06,331] Trial 178 finished with value: 0.9845981377851871 and parameters: {'layer1': 104, 'layer2': 47, 'layer3': 441, 'activation': 'relu', 'solver': 'adam', 'lr': 1.1842836922823287e-06}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:58:39<6:40:36, 6009.00s/it]

[I 2026-02-21 09:09:28,062] Trial 179 finished with value: 0.9880920438844049 and parameters: {'layer1': 407, 'layer2': 133, 'layer3': 480, 'activation': 'identity', 'solver': 'adam', 'lr': 0.008598584605069123}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:58:50<6:40:36, 6009.00s/it]

[I 2026-02-21 09:09:39,150] Trial 180 finished with value: 0.989188244646896 and parameters: {'layer1': 20, 'layer2': 91, 'layer3': 492, 'activation': 'relu', 'solver': 'adam', 'lr': 0.005841120215427974}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:59:03<6:40:36, 6009.00s/it]

[I 2026-02-21 09:09:52,839] Trial 181 finished with value: 0.9886803174790864 and parameters: {'layer1': 100, 'layer2': 215, 'layer3': 433, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0083716223916285}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:59:18<6:40:36, 6009.00s/it]

[I 2026-02-21 09:10:07,814] Trial 182 finished with value: 0.9890298841990456 and parameters: {'layer1': 83, 'layer2': 204, 'layer3': 421, 'activation': 'identity', 'solver': 'adam', 'lr': 0.007270132761841147}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:59:31<6:40:36, 6009.00s/it]

[I 2026-02-21 09:10:20,629] Trial 183 finished with value: 0.9894378733721931 and parameters: {'layer1': 110, 'layer2': 196, 'layer3': 429, 'activation': 'identity', 'solver': 'adam', 'lr': 0.00841023594087793}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:59:46<6:40:36, 6009.00s/it]

[I 2026-02-21 09:10:35,041] Trial 184 finished with value: 0.9884620657923483 and parameters: {'layer1': 130, 'layer2': 185, 'layer3': 409, 'activation': 'identity', 'solver': 'adam', 'lr': 0.006602527190846615}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [21:59:57<6:40:36, 6009.00s/it]

[I 2026-02-21 09:10:46,570] Trial 185 finished with value: 0.9884353208550666 and parameters: {'layer1': 91, 'layer2': 108, 'layer3': 392, 'activation': 'identity', 'solver': 'adam', 'lr': 0.005227042625597209}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [22:00:19<6:40:36, 6009.00s/it]

[I 2026-02-21 09:11:08,494] Trial 186 finished with value: 0.9890298841990456 and parameters: {'layer1': 412, 'layer2': 101, 'layer3': 460, 'activation': 'identity', 'solver': 'adam', 'lr': 0.008899221806646294}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [22:00:28<6:40:36, 6009.00s/it]

[I 2026-02-21 09:11:17,445] Trial 187 finished with value: 0.9845981377851871 and parameters: {'layer1': 164, 'layer2': 213, 'layer3': 445, 'activation': 'relu', 'solver': 'sgd', 'lr': 0.004003148709872005}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [22:00:40<6:40:36, 6009.00s/it]

[I 2026-02-21 09:11:29,487] Trial 188 finished with value: 0.9880920438844049 and parameters: {'layer1': 97, 'layer2': 58, 'layer3': 381, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00998715239528227}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [22:00:54<6:40:36, 6009.00s/it]

[I 2026-02-21 09:11:43,721] Trial 189 finished with value: 0.9901140282664695 and parameters: {'layer1': 37, 'layer2': 123, 'layer3': 403, 'activation': 'identity', 'solver': 'adam', 'lr': 0.007095325633159935}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [22:01:06<6:40:36, 6009.00s/it]

[I 2026-02-21 09:11:55,657] Trial 190 finished with value: 0.9888466481180463 and parameters: {'layer1': 32, 'layer2': 122, 'layer3': 410, 'activation': 'relu', 'solver': 'adam', 'lr': 0.005915208655035014}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [22:01:18<6:40:36, 6009.00s/it]

[I 2026-02-21 09:12:07,130] Trial 191 finished with value: 0.9884628890732239 and parameters: {'layer1': 43, 'layer2': 136, 'layer3': 424, 'activation': 'identity', 'solver': 'adam', 'lr': 0.007220085938278085}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [22:01:32<6:40:36, 6009.00s/it]

[I 2026-02-21 09:12:21,403] Trial 192 finished with value: 0.9901818893673354 and parameters: {'layer1': 57, 'layer2': 114, 'layer3': 399, 'activation': 'identity', 'solver': 'adam', 'lr': 0.009963687558170831}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [22:01:46<6:40:36, 6009.00s/it]

[I 2026-02-21 09:12:34,862] Trial 193 finished with value: 0.9892166700259898 and parameters: {'layer1': 61, 'layer2': 118, 'layer3': 399, 'activation': 'identity', 'solver': 'adam', 'lr': 0.006807127570764617}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [22:01:56<6:40:36, 6009.00s/it]

[I 2026-02-21 09:12:45,591] Trial 194 finished with value: 0.9884574109692965 and parameters: {'layer1': 25, 'layer2': 110, 'layer3': 383, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0046924388597457635}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [22:02:10<6:40:36, 6009.00s/it]

[I 2026-02-21 09:12:59,228] Trial 195 finished with value: 0.9890910371258105 and parameters: {'layer1': 56, 'layer2': 150, 'layer3': 370, 'activation': 'identity', 'solver': 'adam', 'lr': 0.009743955979703595}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [22:02:21<6:40:36, 6009.00s/it]

[I 2026-02-21 09:13:10,063] Trial 196 finished with value: 0.9880920438844049 and parameters: {'layer1': 49, 'layer2': 93, 'layer3': 403, 'activation': 'identity', 'solver': 'adam', 'lr': 0.00581232739824566}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [22:02:33<6:40:36, 6009.00s/it]

[I 2026-02-21 09:13:21,890] Trial 197 finished with value: 0.9880648724802885 and parameters: {'layer1': 40, 'layer2': 133, 'layer3': 416, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0033244258321091756}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  71%|███████▏  | 10/14 [22:02:47<6:40:36, 6009.00s/it]

[I 2026-02-21 09:13:35,986] Trial 198 finished with value: 0.9893952081700645 and parameters: {'layer1': 74, 'layer2': 122, 'layer3': 392, 'activation': 'identity', 'solver': 'adam', 'lr': 0.00785523521601796}. Best is trial 43 with value: 0.9905634058126103.

Best trial: 43. Best value: 0.990563: 100%|██████████| 200/200 [52:54<00:00, 15.87s/it]

[I 2026-02-21 09:13:51,249] Trial 199 finished with value: 0.9845981377851871 and parameters: {'layer1': 377, 'layer2': 81, 'layer3': 471, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.009873997600911252}. Best is trial 43 with value: 0.9905634058126103.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:03:02<4:17:04, 5141.53s/it][I 2026-02-21 09:13:51,561] A new study created in memory with name: no-name-9ffa4635-f1e0-48fd-bcfc-39735ce17a2e

  → Best model saved.

[Exact Paper MLP] Pseudomonas_Aeruginosa | Ciprofloxacin

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:03:22<4:17:04, 5141.53s/it]

[I 2026-02-21 09:14:11,731] Trial 0 finished with value: 0.6600307762939683 and parameters: {'layer1': 356, 'layer2': 459, 'layer3': 295, 'activation': 'relu', 'solver': 'sgd', 'lr': 6.204440128291407e-05}. Best is trial 0 with value: 0.6600307762939683.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:03:37<4:17:04, 5141.53s/it]

[I 2026-02-21 09:14:26,106] Trial 1 finished with value: 0.6606151110514127 and parameters: {'layer1': 69, 'layer2': 103, 'layer3': 70, 'activation': 'tanh', 'solver': 'sgd', 'lr': 8.282154191763612e-06}. Best is trial 1 with value: 0.6606151110514127.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:03:49<4:17:04, 5141.53s/it]

[I 2026-02-21 09:14:38,663] Trial 2 finished with value: 0.6602766638401436 and parameters: {'layer1': 325, 'layer2': 260, 'layer3': 112, 'activation': 'relu', 'solver': 'sgd', 'lr': 0.00030004777529939425}. Best is trial 1 with value: 0.6606151110514127.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:04:00<4:17:04, 5141.53s/it]

[I 2026-02-21 09:14:48,993] Trial 3 finished with value: 0.657755702219714 and parameters: {'layer1': 272, 'layer2': 460, 'layer3': 205, 'activation': 'relu', 'solver': 'sgd', 'lr': 5.726053327886556e-06}. Best is trial 1 with value: 0.6606151110514127.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:04:15<4:17:04, 5141.53s/it]

[I 2026-02-21 09:15:04,045] Trial 4 finished with value: 0.8590519838446994 and parameters: {'layer1': 98, 'layer2': 116, 'layer3': 431, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0017483980045396533}. Best is trial 4 with value: 0.8590519838446994.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:04:31<4:17:04, 5141.53s/it]

[I 2026-02-21 09:15:20,811] Trial 5 finished with value: 0.8510983902349756 and parameters: {'layer1': 183, 'layer2': 483, 'layer3': 380, 'activation': 'relu', 'solver': 'adam', 'lr': 0.009939914542836712}. Best is trial 4 with value: 0.8590519838446994.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:04:42<4:17:04, 5141.53s/it]

[I 2026-02-21 09:15:31,482] Trial 6 finished with value: 0.8155772208149157 and parameters: {'layer1': 155, 'layer2': 465, 'layer3': 279, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.005293080937379599}. Best is trial 4 with value: 0.8590519838446994.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:04:52<4:17:04, 5141.53s/it]

[I 2026-02-21 09:15:41,449] Trial 7 finished with value: 0.8155772208149157 and parameters: {'layer1': 490, 'layer2': 139, 'layer3': 410, 'activation': 'logistic', 'solver': 'sgd', 'lr': 0.005808299951055448}. Best is trial 4 with value: 0.8590519838446994.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:05:13<4:17:04, 5141.53s/it]

[I 2026-02-21 09:16:02,448] Trial 8 finished with value: 0.8546708646012695 and parameters: {'layer1': 391, 'layer2': 190, 'layer3': 387, 'activation': 'identity', 'solver': 'adam', 'lr': 0.00016534614254727924}. Best is trial 4 with value: 0.8590519838446994.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:05:50<4:17:04, 5141.53s/it]

[I 2026-02-21 09:16:39,282] Trial 9 finished with value: 0.8565715940366907 and parameters: {'layer1': 372, 'layer2': 473, 'layer3': 118, 'activation': 'tanh', 'solver': 'adam', 'lr': 2.8185262199446564e-05}. Best is trial 4 with value: 0.8590519838446994.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:05:57<4:17:04, 5141.53s/it]

[I 2026-02-21 09:16:45,991] Trial 10 finished with value: 0.8155772208149157 and parameters: {'layer1': 13, 'layer2': 10, 'layer3': 499, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.000857602833810164}. Best is trial 4 with value: 0.8590519838446994.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:06:14<4:17:04, 5141.53s/it]

[I 2026-02-21 09:17:03,122] Trial 11 finished with value: 0.8177906176395924 and parameters: {'layer1': 460, 'layer2': 320, 'layer3': 172, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.0393268881747497e-06}. Best is trial 4 with value: 0.8590519838446994.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:06:34<4:17:04, 5141.53s/it]

[I 2026-02-21 09:17:22,886] Trial 12 finished with value: 0.8376296882219426 and parameters: {'layer1': 203, 'layer2': 354, 'layer3': 58, 'activation': 'tanh', 'solver': 'adam', 'lr': 3.0705172969680725e-05}. Best is trial 4 with value: 0.8590519838446994.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:06:44<4:17:04, 5141.53s/it]

[I 2026-02-21 09:17:33,004] Trial 13 finished with value: 0.8533679811614835 and parameters: {'layer1': 122, 'layer2': 36, 'layer3': 494, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0008926792147787792}. Best is trial 4 with value: 0.8590519838446994.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:07:02<4:17:04, 5141.53s/it]

[I 2026-02-21 09:17:51,074] Trial 14 finished with value: 0.8272697411579314 and parameters: {'layer1': 264, 'layer2': 216, 'layer3': 161, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.8886949759500306e-05}. Best is trial 4 with value: 0.8590519838446994.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:07:29<4:17:04, 5141.53s/it]

[I 2026-02-21 09:18:18,001] Trial 15 finished with value: 0.8567372502047078 and parameters: {'layer1': 417, 'layer2': 367, 'layer3': 323, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.001483191821136927}. Best is trial 4 with value: 0.8590519838446994.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:07:59<4:17:04, 5141.53s/it]

[I 2026-02-21 09:18:48,030] Trial 16 finished with value: 0.8576684495134386 and parameters: {'layer1': 420, 'layer2': 377, 'layer3': 329, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.001681515649081359}. Best is trial 4 with value: 0.8590519838446994.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:08:22<4:17:04, 5141.53s/it]

[I 2026-02-21 09:19:11,194] Trial 17 finished with value: 0.8522638501381923 and parameters: {'layer1': 308, 'layer2': 303, 'layer3': 455, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.002160353938005404}. Best is trial 4 with value: 0.8590519838446994.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:08:41<4:17:04, 5141.53s/it]

[I 2026-02-21 09:19:30,724] Trial 18 finished with value: 0.8559485581803079 and parameters: {'layer1': 90, 'layer2': 402, 'layer3': 337, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.00039938968759810193}. Best is trial 4 with value: 0.8590519838446994.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:09:04<4:17:04, 5141.53s/it]

[I 2026-02-21 09:19:53,152] Trial 19 finished with value: 0.8606631961405842 and parameters: {'layer1': 218, 'layer2': 115, 'layer3': 237, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0029465830541553083}. Best is trial 19 with value: 0.8606631961405842.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:09:20<4:17:04, 5141.53s/it]

[I 2026-02-21 09:20:09,808] Trial 20 finished with value: 0.8302879606592966 and parameters: {'layer1': 222, 'layer2': 86, 'layer3': 233, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0005082906688076328}. Best is trial 19 with value: 0.8606631961405842.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:09:32<4:17:04, 5141.53s/it]

[I 2026-02-21 09:20:21,597] Trial 21 finished with value: 0.8408214546619888 and parameters: {'layer1': 16, 'layer2': 145, 'layer3': 344, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0025249670779572894}. Best is trial 19 with value: 0.8606631961405842.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:09:46<4:17:04, 5141.53s/it]

[I 2026-02-21 09:20:35,827] Trial 22 finished with value: 0.839353998976852 and parameters: {'layer1': 136, 'layer2': 196, 'layer3': 431, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.003284240985095686}. Best is trial 19 with value: 0.8606631961405842.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:10:06<4:17:04, 5141.53s/it]

[I 2026-02-21 09:20:55,618] Trial 23 finished with value: 0.8584469762169642 and parameters: {'layer1': 235, 'layer2': 65, 'layer3': 244, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0010972893277520954}. Best is trial 19 with value: 0.8606631961405842.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:10:22<4:17:04, 5141.53s/it]

[I 2026-02-21 09:21:11,834] Trial 24 finished with value: 0.8548835695159338 and parameters: {'layer1': 238, 'layer2': 67, 'layer3': 234, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0001911541148428805}. Best is trial 19 with value: 0.8606631961405842.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:10:41<4:17:04, 5141.53s/it]

[I 2026-02-21 09:21:30,126] Trial 25 finished with value: 0.8548752578763809 and parameters: {'layer1': 182, 'layer2': 131, 'layer3': 264, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0007841236561245036}. Best is trial 19 with value: 0.8606631961405842.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:10:47<4:17:04, 5141.53s/it]

[I 2026-02-21 09:21:36,535] Trial 26 finished with value: 0.8155772208149157 and parameters: {'layer1': 67, 'layer2': 49, 'layer3': 204, 'activation': 'logistic', 'solver': 'sgd', 'lr': 0.009243694965143823}. Best is trial 19 with value: 0.8606631961405842.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:10:58<4:17:04, 5141.53s/it]

[I 2026-02-21 09:21:47,498] Trial 27 finished with value: 0.8155772208149157 and parameters: {'layer1': 274, 'layer2': 167, 'layer3': 11, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0038455913235803485}. Best is trial 19 with value: 0.8606631961405842.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:11:06<4:17:04, 5141.53s/it]

[I 2026-02-21 09:21:55,709] Trial 28 finished with value: 0.8155772208149157 and parameters: {'layer1': 109, 'layer2': 103, 'layer3': 169, 'activation': 'logistic', 'solver': 'adam', 'lr': 9.829673109970991e-05}. Best is trial 19 with value: 0.8606631961405842.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:11:15<4:17:04, 5141.53s/it]

[I 2026-02-21 09:22:04,478] Trial 29 finished with value: 0.8155772208149157 and parameters: {'layer1': 309, 'layer2': 248, 'layer3': 300, 'activation': 'identity', 'solver': 'sgd', 'lr': 0.001330713312365957}. Best is trial 19 with value: 0.8606631961405842.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:11:34<4:17:04, 5141.53s/it]

[I 2026-02-21 09:22:23,035] Trial 30 finished with value: 0.8524347856463578 and parameters: {'layer1': 155, 'layer2': 18, 'layer3': 243, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00023158209922756085}. Best is trial 19 with value: 0.8606631961405842.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:11:57<4:17:04, 5141.53s/it]

[I 2026-02-21 09:22:46,240] Trial 31 finished with value: 0.8569262935290414 and parameters: {'layer1': 351, 'layer2': 421, 'layer3': 309, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0015684467047676536}. Best is trial 19 with value: 0.8606631961405842.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:12:29<4:17:04, 5141.53s/it]

[I 2026-02-21 09:23:18,453] Trial 32 finished with value: 0.8580726096289897 and parameters: {'layer1': 424, 'layer2': 77, 'layer3': 362, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0005643538164903834}. Best is trial 19 with value: 0.8606631961405842.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:12:41<4:17:04, 5141.53s/it]

[I 2026-02-21 09:23:30,101] Trial 33 finished with value: 0.8287315954876755 and parameters: {'layer1': 45, 'layer2': 110, 'layer3': 368, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.00047313931680009004}. Best is trial 19 with value: 0.8606631961405842.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:12:49<4:17:04, 5141.53s/it]

[I 2026-02-21 09:23:38,092] Trial 34 finished with value: 0.8155772208149157 and parameters: {'layer1': 243, 'layer2': 72, 'layer3': 447, 'activation': 'logistic', 'solver': 'sgd', 'lr': 0.0007190981587973506}. Best is trial 19 with value: 0.8606631961405842.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:13:09<4:17:04, 5141.53s/it]

[I 2026-02-21 09:23:58,107] Trial 35 finished with value: 0.8565533259603579 and parameters: {'layer1': 299, 'layer2': 114, 'layer3': 209, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0047190911141948315}. Best is trial 19 with value: 0.8606631961405842.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:13:18<4:17:04, 5141.53s/it]

[I 2026-02-21 09:24:07,050] Trial 36 finished with value: 0.8155772208149157 and parameters: {'layer1': 210, 'layer2': 51, 'layer3': 276, 'activation': 'logistic', 'solver': 'sgd', 'lr': 0.00011749109135355332}. Best is trial 19 with value: 0.8606631961405842.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:13:29<4:17:04, 5141.53s/it]

[I 2026-02-21 09:24:18,838] Trial 37 finished with value: 0.8155772208149157 and parameters: {'layer1': 338, 'layer2': 86, 'layer3': 362, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0002915705263128403}. Best is trial 19 with value: 0.8606631961405842.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:13:44<4:17:04, 5141.53s/it]

[I 2026-02-21 09:24:33,744] Trial 38 finished with value: 0.8583561267109922 and parameters: {'layer1': 189, 'layer2': 250, 'layer3': 395, 'activation': 'relu', 'solver': 'adam', 'lr': 0.007051111112288948}. Best is trial 19 with value: 0.8606631961405842.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:13:52<4:17:04, 5141.53s/it]

[I 2026-02-21 09:24:41,274] Trial 39 finished with value: 0.8155772208149157 and parameters: {'layer1': 187, 'layer2': 269, 'layer3': 396, 'activation': 'relu', 'solver': 'sgd', 'lr': 0.00695545369523671}. Best is trial 19 with value: 0.8606631961405842.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:14:09<4:17:04, 5141.53s/it]

[I 2026-02-21 09:24:58,140] Trial 40 finished with value: 0.861243457605007 and parameters: {'layer1': 170, 'layer2': 238, 'layer3': 475, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0032021887503236586}. Best is trial 40 with value: 0.861243457605007.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:14:25<4:17:04, 5141.53s/it]

[I 2026-02-21 09:25:14,622] Trial 41 finished with value: 0.8554105066047338 and parameters: {'layer1': 159, 'layer2': 236, 'layer3': 461, 'activation': 'relu', 'solver': 'adam', 'lr': 0.003427572027405803}. Best is trial 40 with value: 0.861243457605007.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:14:44<4:17:04, 5141.53s/it]

[I 2026-02-21 09:25:33,047] Trial 42 finished with value: 0.8525038016091742 and parameters: {'layer1': 170, 'layer2': 172, 'layer3': 417, 'activation': 'relu', 'solver': 'adam', 'lr': 0.007268400040908685}. Best is trial 40 with value: 0.861243457605007.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:14:58<4:17:04, 5141.53s/it]

[I 2026-02-21 09:25:47,816] Trial 43 finished with value: 0.8573684006516885 and parameters: {'layer1': 136, 'layer2': 289, 'layer3': 475, 'activation': 'relu', 'solver': 'adam', 'lr': 0.002547309744261885}. Best is trial 40 with value: 0.861243457605007.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:15:14<4:17:04, 5141.53s/it]

[I 2026-02-21 09:26:02,868] Trial 44 finished with value: 0.8566532892525013 and parameters: {'layer1': 218, 'layer2': 209, 'layer3': 429, 'activation': 'relu', 'solver': 'adam', 'lr': 0.009875059299952376}. Best is trial 40 with value: 0.861243457605007.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:15:29<4:17:04, 5141.53s/it]

[I 2026-02-21 09:26:18,179] Trial 45 finished with value: 0.8541816926880177 and parameters: {'layer1': 191, 'layer2': 160, 'layer3': 131, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0048393763371976555}. Best is trial 40 with value: 0.861243457605007.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:15:41<4:17:04, 5141.53s/it]

[I 2026-02-21 09:26:30,642] Trial 46 finished with value: 0.8547655207193152 and parameters: {'layer1': 98, 'layer2': 329, 'layer3': 399, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0012341244697390177}. Best is trial 40 with value: 0.861243457605007.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:15:59<4:17:04, 5141.53s/it]

[I 2026-02-21 09:26:48,363] Trial 47 finished with value: 0.8463635122522989 and parameters: {'layer1': 279, 'layer2': 230, 'layer3': 476, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.002151540335138878}. Best is trial 40 with value: 0.861243457605007.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:16:16<4:17:04, 5141.53s/it]

[I 2026-02-21 09:27:05,177] Trial 48 finished with value: 0.8551287267423253 and parameters: {'layer1': 243, 'layer2': 131, 'layer3': 206, 'activation': 'relu', 'solver': 'adam', 'lr': 0.001063596190292793}. Best is trial 40 with value: 0.861243457605007.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:16:26<4:17:04, 5141.53s/it]

[I 2026-02-21 09:27:15,258] Trial 49 finished with value: 0.816603847733916 and parameters: {'layer1': 129, 'layer2': 189, 'layer3': 285, 'activation': 'identity', 'solver': 'adam', 'lr': 1.1397765610467076e-06}. Best is trial 40 with value: 0.861243457605007.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:16:33<4:17:04, 5141.53s/it]

[I 2026-02-21 09:27:22,096] Trial 50 finished with value: 0.8155772208149157 and parameters: {'layer1': 78, 'layer2': 266, 'layer3': 496, 'activation': 'tanh', 'solver': 'sgd', 'lr': 0.0053365812490162035}. Best is trial 40 with value: 0.861243457605007.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:16:50<4:17:04, 5141.53s/it]

[I 2026-02-21 09:27:39,376] Trial 51 finished with value: 0.8234151105537496 and parameters: {'layer1': 493, 'layer2': 23, 'layer3': 372, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0005662901076669521}. Best is trial 40 with value: 0.861243457605007.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:17:17<4:17:04, 5141.53s/it]

[I 2026-02-21 09:28:06,598] Trial 52 finished with value: 0.8554864188164363 and parameters: {'layer1': 451, 'layer2': 89, 'layer3': 436, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0019589483330564833}. Best is trial 40 with value: 0.861243457605007.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:17:33<4:17:04, 5141.53s/it]

[I 2026-02-21 09:28:22,364] Trial 53 finished with value: 0.8571391389677283 and parameters: {'layer1': 222, 'layer2': 58, 'layer3': 409, 'activation': 'relu', 'solver': 'adam', 'lr': 0.003168732769510356}. Best is trial 40 with value: 0.861243457605007.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:17:42<4:17:04, 5141.53s/it]

[I 2026-02-21 09:28:31,601] Trial 54 finished with value: 0.8155772208149157 and parameters: {'layer1': 149, 'layer2': 117, 'layer3': 250, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.00035535698937045034}. Best is trial 40 with value: 0.861243457605007.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:18:03<4:17:04, 5141.53s/it]

[I 2026-02-21 09:28:52,300] Trial 55 finished with value: 0.8582840020503186 and parameters: {'layer1': 201, 'layer2': 147, 'layer3': 352, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0010242084796047999}. Best is trial 40 with value: 0.861243457605007.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:18:21<4:17:04, 5141.53s/it]

[I 2026-02-21 09:29:09,867] Trial 56 finished with value: 0.8506102830563271 and parameters: {'layer1': 257, 'layer2': 151, 'layer3': 473, 'activation': 'identity', 'solver': 'adam', 'lr': 0.002825521827026852}. Best is trial 40 with value: 0.861243457605007.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:18:43<4:17:04, 5141.53s/it]

[I 2026-02-21 09:29:32,206] Trial 57 finished with value: 0.8574410065044142 and parameters: {'layer1': 196, 'layer2': 182, 'layer3': 318, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0010330812685419898}. Best is trial 40 with value: 0.861243457605007.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:18:53<4:17:04, 5141.53s/it]

[I 2026-02-21 09:29:42,051] Trial 58 finished with value: 0.8155772208149157 and parameters: {'layer1': 170, 'layer2': 215, 'layer3': 348, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.006915426246739663}. Best is trial 40 with value: 0.861243457605007.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:19:04<4:17:04, 5141.53s/it]

[I 2026-02-21 09:29:52,923] Trial 59 finished with value: 0.8155772208149157 and parameters: {'layer1': 233, 'layer2': 139, 'layer3': 381, 'activation': 'logistic', 'solver': 'adam', 'lr': 5.6172206870639166e-05}. Best is trial 40 with value: 0.861243457605007.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:19:13<4:17:04, 5141.53s/it]

[I 2026-02-21 09:30:02,229] Trial 60 finished with value: 0.8155772208149157 and parameters: {'layer1': 115, 'layer2': 298, 'layer3': 226, 'activation': 'relu', 'solver': 'adam', 'lr': 1.088492771060679e-05}. Best is trial 40 with value: 0.861243457605007.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:19:33<4:17:04, 5141.53s/it]

[I 2026-02-21 09:30:22,523] Trial 61 finished with value: 0.862031756607591 and parameters: {'layer1': 204, 'layer2': 38, 'layer3': 411, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0007696414840311039}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:19:53<4:17:04, 5141.53s/it]

[I 2026-02-21 09:30:42,835] Trial 62 finished with value: 0.8546077848014424 and parameters: {'layer1': 207, 'layer2': 34, 'layer3': 186, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0018083829190603368}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:20:04<4:17:04, 5141.53s/it]

[I 2026-02-21 09:30:53,352] Trial 63 finished with value: 0.8255085789039989 and parameters: {'layer1': 172, 'layer2': 92, 'layer3': 419, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.004083040048677309}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:20:27<4:17:04, 5141.53s/it]

[I 2026-02-21 09:31:16,529] Trial 64 finished with value: 0.8577043844785985 and parameters: {'layer1': 228, 'layer2': 126, 'layer3': 444, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0007837584830510452}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:20:50<4:17:04, 5141.53s/it]

[I 2026-02-21 09:31:39,579] Trial 65 finished with value: 0.8594099663525443 and parameters: {'layer1': 291, 'layer2': 49, 'layer3': 264, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0014239587137808748}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:21:14<4:17:04, 5141.53s/it]

[I 2026-02-21 09:32:03,816] Trial 66 finished with value: 0.8565469803506419 and parameters: {'layer1': 298, 'layer2': 41, 'layer3': 261, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0014698609660888228}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:21:35<4:17:04, 5141.53s/it]

[I 2026-02-21 09:32:24,764] Trial 67 finished with value: 0.8504764729511098 and parameters: {'layer1': 278, 'layer2': 68, 'layer3': 152, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.002344425388928712}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:22:00<4:17:04, 5141.53s/it]

[I 2026-02-21 09:32:49,322] Trial 68 finished with value: 0.8602740057520795 and parameters: {'layer1': 249, 'layer2': 495, 'layer3': 89, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0006911107462252912}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:22:10<4:17:04, 5141.53s/it]

[I 2026-02-21 09:32:59,107] Trial 69 finished with value: 0.8155772208149157 and parameters: {'layer1': 246, 'layer2': 425, 'layer3': 45, 'activation': 'logistic', 'solver': 'sgd', 'lr': 0.0006697338014513901}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:22:24<4:17:04, 5141.53s/it]

[I 2026-02-21 09:33:13,284] Trial 70 finished with value: 0.8264004757026668 and parameters: {'layer1': 263, 'layer2': 495, 'layer3': 85, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.00040739634838168155}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:22:35<4:17:04, 5141.53s/it]

[I 2026-02-21 09:33:24,681] Trial 71 finished with value: 0.8155772208149157 and parameters: {'layer1': 293, 'layer2': 10, 'layer3': 133, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.001415772088520835}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:23:02<4:17:04, 5141.53s/it]

[I 2026-02-21 09:33:51,025] Trial 72 finished with value: 0.8486175236191983 and parameters: {'layer1': 316, 'layer2': 343, 'layer3': 106, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.003922989711636619}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:23:09<4:17:04, 5141.53s/it]

[I 2026-02-21 09:33:58,531] Trial 73 finished with value: 0.8155772208149157 and parameters: {'layer1': 45, 'layer2': 29, 'layer3': 186, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0019894400526125943}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:23:25<4:17:04, 5141.53s/it]

[I 2026-02-21 09:34:13,926] Trial 74 finished with value: 0.8561765833411261 and parameters: {'layer1': 255, 'layer2': 51, 'layer3': 40, 'activation': 'relu', 'solver': 'adam', 'lr': 0.006249102115956104}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:23:39<4:17:04, 5141.53s/it]

[I 2026-02-21 09:34:28,106] Trial 75 finished with value: 0.8548948544317504 and parameters: {'layer1': 215, 'layer2': 95, 'layer3': 466, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0027838450888764865}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:23:59<4:17:04, 5141.53s/it]

[I 2026-02-21 09:34:48,244] Trial 76 finished with value: 0.8540691649070531 and parameters: {'layer1': 180, 'layer2': 283, 'layer3': 294, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.000917988903740747}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:24:32<4:17:04, 5141.53s/it]

[I 2026-02-21 09:35:21,101] Trial 77 finished with value: 0.857529914679979 and parameters: {'layer1': 375, 'layer2': 379, 'layer3': 487, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.000300155103594563}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:24:49<4:17:04, 5141.53s/it]

[I 2026-02-21 09:35:38,379] Trial 78 finished with value: 0.8524846214268871 and parameters: {'layer1': 143, 'layer2': 239, 'layer3': 454, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0006375511915417019}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:24:58<4:17:04, 5141.53s/it]

[I 2026-02-21 09:35:46,920] Trial 79 finished with value: 0.8163044594498123 and parameters: {'layer1': 269, 'layer2': 311, 'layer3': 397, 'activation': 'tanh', 'solver': 'sgd', 'lr': 0.001182117827160712}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:25:09<4:17:04, 5141.53s/it]

[I 2026-02-21 09:35:57,896] Trial 80 finished with value: 0.8155772208149157 and parameters: {'layer1': 288, 'layer2': 77, 'layer3': 224, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0001485822863836005}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:25:28<4:17:04, 5141.53s/it]

[I 2026-02-21 09:36:16,918] Trial 81 finished with value: 0.859420214909344 and parameters: {'layer1': 196, 'layer2': 105, 'layer3': 425, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.00089159960850036}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:25:46<4:17:04, 5141.53s/it]

[I 2026-02-21 09:36:35,754] Trial 82 finished with value: 0.8570605292001797 and parameters: {'layer1': 163, 'layer2': 108, 'layer3': 426, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0017028010237144222}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:26:08<4:17:04, 5141.53s/it]

[I 2026-02-21 09:36:56,934] Trial 83 finished with value: 0.849074542141014 and parameters: {'layer1': 232, 'layer2': 62, 'layer3': 407, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0005023514285080909}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:26:33<4:17:04, 5141.53s/it]

[I 2026-02-21 09:37:22,808] Trial 84 finished with value: 0.8535309971047047 and parameters: {'layer1': 334, 'layer2': 254, 'layer3': 442, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.000843037303822725}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:26:43<4:17:04, 5141.53s/it]

[I 2026-02-21 09:37:32,641] Trial 85 finished with value: 0.8155772208149157 and parameters: {'layer1': 188, 'layer2': 46, 'layer3': 270, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.00819106772584067}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:27:03<4:17:04, 5141.53s/it]

[I 2026-02-21 09:37:51,890] Trial 86 finished with value: 0.8484089707083244 and parameters: {'layer1': 203, 'layer2': 202, 'layer3': 11, 'activation': 'relu', 'solver': 'adam', 'lr': 0.005270326107844014}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:27:15<4:17:04, 5141.53s/it]

[I 2026-02-21 09:38:04,681] Trial 87 finished with value: 0.8246093363543429 and parameters: {'layer1': 247, 'layer2': 85, 'layer3': 387, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.004123805340962109}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:27:28<4:17:04, 5141.53s/it]

[I 2026-02-21 09:38:17,382] Trial 88 finished with value: 0.8205991121543779 and parameters: {'layer1': 217, 'layer2': 100, 'layer3': 456, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0030963242077163087}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:27:41<4:17:04, 5141.53s/it]

[I 2026-02-21 09:38:30,451] Trial 89 finished with value: 0.8528216441223565 and parameters: {'layer1': 183, 'layer2': 121, 'layer3': 486, 'activation': 'identity', 'solver': 'adam', 'lr': 0.00122400967211553}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:28:03<4:17:04, 5141.53s/it]

[I 2026-02-21 09:38:52,450] Trial 90 finished with value: 0.8511201143461726 and parameters: {'layer1': 225, 'layer2': 436, 'layer3': 240, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0024129609669491492}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:28:23<4:17:04, 5141.53s/it]

[I 2026-02-21 09:39:12,471] Trial 91 finished with value: 0.8573669802462416 and parameters: {'layer1': 198, 'layer2': 152, 'layer3': 358, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0011186707899985804}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:28:43<4:17:04, 5141.53s/it]

[I 2026-02-21 09:39:32,755] Trial 92 finished with value: 0.8582174301177599 and parameters: {'layer1': 208, 'layer2': 177, 'layer3': 342, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0009539648933248713}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:29:02<4:17:04, 5141.53s/it]

[I 2026-02-21 09:39:51,492] Trial 93 finished with value: 0.8564605878348897 and parameters: {'layer1': 197, 'layer2': 58, 'layer3': 329, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0015231531329578136}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:29:20<4:17:04, 5141.53s/it]

[I 2026-02-21 09:40:08,944] Trial 94 finished with value: 0.8480976013329421 and parameters: {'layer1': 177, 'layer2': 78, 'layer3': 414, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0018560615518008786}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:29:39<4:17:04, 5141.53s/it]

[I 2026-02-21 09:40:28,461] Trial 95 finished with value: 0.8579262013944036 and parameters: {'layer1': 157, 'layer2': 161, 'layer3': 430, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0007383215489953485}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:29:48<4:17:04, 5141.53s/it]

[I 2026-02-21 09:40:37,034] Trial 96 finished with value: 0.8155772208149157 and parameters: {'layer1': 256, 'layer2': 136, 'layer3': 384, 'activation': 'logistic', 'solver': 'sgd', 'lr': 0.0003756777269296688}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:30:08<4:17:04, 5141.53s/it]

[I 2026-02-21 09:40:57,431] Trial 97 finished with value: 0.8572544011716763 and parameters: {'layer1': 234, 'layer2': 226, 'layer3': 286, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0006292865848611329}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:30:16<4:17:04, 5141.53s/it]

[I 2026-02-21 09:41:05,545] Trial 98 finished with value: 0.8155772208149157 and parameters: {'layer1': 101, 'layer2': 21, 'layer3': 309, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0034208993321013332}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:30:25<4:17:04, 5141.53s/it]

[I 2026-02-21 09:41:14,321] Trial 99 finished with value: 0.8155772208149157 and parameters: {'layer1': 126, 'layer2': 113, 'layer3': 394, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0002386519651224203}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:30:48<4:17:04, 5141.53s/it]

[I 2026-02-21 09:41:37,408] Trial 100 finished with value: 0.858671696183308 and parameters: {'layer1': 246, 'layer2': 279, 'layer3': 372, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.002100077442300937}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:31:10<4:17:04, 5141.53s/it]

[I 2026-02-21 09:41:59,385] Trial 101 finished with value: 0.8577044435779679 and parameters: {'layer1': 240, 'layer2': 462, 'layer3': 374, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0022761254874398658}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:31:29<4:17:04, 5141.53s/it]

[I 2026-02-21 09:42:18,461] Trial 102 finished with value: 0.8553903073164605 and parameters: {'layer1': 211, 'layer2': 404, 'layer3': 353, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0014194848894790273}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:31:51<4:17:04, 5141.53s/it]

[I 2026-02-21 09:42:39,895] Trial 103 finished with value: 0.8605852630269683 and parameters: {'layer1': 223, 'layer2': 102, 'layer3': 419, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0009878107314206434}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:32:13<4:17:04, 5141.53s/it]

[I 2026-02-21 09:43:02,229] Trial 104 finished with value: 0.8547739465592569 and parameters: {'layer1': 280, 'layer2': 282, 'layer3': 422, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0018274993239631601}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:32:33<4:17:04, 5141.53s/it]

[I 2026-02-21 09:43:22,124] Trial 105 finished with value: 0.8484251735163824 and parameters: {'layer1': 266, 'layer2': 104, 'layer3': 438, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0004392178043018957}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:32:50<4:17:04, 5141.53s/it]

[I 2026-02-21 09:43:39,527] Trial 106 finished with value: 0.8321575596057093 and parameters: {'layer1': 247, 'layer2': 38, 'layer3': 406, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0027627125476592774}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:33:01<4:17:04, 5141.53s/it]

[I 2026-02-21 09:43:50,167] Trial 107 finished with value: 0.8166036242858177 and parameters: {'layer1': 218, 'layer2': 71, 'layer3': 464, 'activation': 'relu', 'solver': 'adam', 'lr': 3.1946010151023574e-06}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:33:20<4:17:04, 5141.53s/it]

[I 2026-02-21 09:44:09,298] Trial 108 finished with value: 0.8353305361810971 and parameters: {'layer1': 308, 'layer2': 444, 'layer3': 216, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.004296893416033859}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:33:41<4:17:04, 5141.53s/it]

[I 2026-02-21 09:44:30,485] Trial 109 finished with value: 0.856519558988855 and parameters: {'layer1': 224, 'layer2': 336, 'layer3': 258, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0008655165188183513}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:33:48<4:17:04, 5141.53s/it]

[I 2026-02-21 09:44:37,433] Trial 110 finished with value: 0.8155772208149157 and parameters: {'layer1': 61, 'layer2': 374, 'layer3': 187, 'activation': 'identity', 'solver': 'sgd', 'lr': 0.002120658716274749}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:34:08<4:17:04, 5141.53s/it]

[I 2026-02-21 09:44:57,809] Trial 111 finished with value: 0.8574896488086852 and parameters: {'layer1': 195, 'layer2': 127, 'layer3': 389, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0012357489438384504}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:34:28<4:17:04, 5141.53s/it]

[I 2026-02-21 09:45:17,292] Trial 112 finished with value: 0.8567018807614547 and parameters: {'layer1': 166, 'layer2': 140, 'layer3': 370, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0010532210183449857}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:34:51<4:17:04, 5141.53s/it]

[I 2026-02-21 09:45:40,024] Trial 113 finished with value: 0.8555194630360488 and parameters: {'layer1': 254, 'layer2': 94, 'layer3': 447, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.000537777405102177}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:35:01<4:17:04, 5141.53s/it]

[I 2026-02-21 09:45:50,307] Trial 114 finished with value: 0.8155772208149157 and parameters: {'layer1': 205, 'layer2': 263, 'layer3': 409, 'activation': 'logistic', 'solver': 'adam', 'lr': 6.144187999875953e-05}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:35:21<4:17:04, 5141.53s/it]

[I 2026-02-21 09:46:10,352] Trial 115 finished with value: 0.8581092574374244 and parameters: {'layer1': 189, 'layer2': 58, 'layer3': 377, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0014814288221924813}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:35:36<4:17:04, 5141.53s/it]

[I 2026-02-21 09:46:25,499] Trial 116 finished with value: 0.8509248461652428 and parameters: {'layer1': 147, 'layer2': 249, 'layer3': 334, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0009170218534810271}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:35:57<4:17:04, 5141.53s/it]

[I 2026-02-21 09:46:46,611] Trial 117 finished with value: 0.8556965238695854 and parameters: {'layer1': 231, 'layer2': 83, 'layer3': 398, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0007652533528760073}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:36:21<4:17:04, 5141.53s/it]

[I 2026-02-21 09:47:10,720] Trial 118 finished with value: 0.8552576118595407 and parameters: {'layer1': 238, 'layer2': 149, 'layer3': 421, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0016785186831446521}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:36:52<4:17:04, 5141.53s/it]

[I 2026-02-21 09:47:41,044] Trial 119 finished with value: 0.8584025222046254 and parameters: {'layer1': 285, 'layer2': 101, 'layer3': 90, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0035305299516298796}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:37:03<4:17:04, 5141.53s/it]

[I 2026-02-21 09:47:52,604] Trial 120 finished with value: 0.8155772208149157 and parameters: {'layer1': 288, 'layer2': 100, 'layer3': 98, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.006489309859175546}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:37:26<4:17:04, 5141.53s/it]

[I 2026-02-21 09:48:15,552] Trial 121 finished with value: 0.8594230234084297 and parameters: {'layer1': 274, 'layer2': 116, 'layer3': 146, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0036159697267872776}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:37:56<4:17:04, 5141.53s/it]

[I 2026-02-21 09:48:45,389] Trial 122 finished with value: 0.8564718529682374 and parameters: {'layer1': 320, 'layer2': 121, 'layer3': 71, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.002935127304953927}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:38:18<4:17:04, 5141.53s/it]

[I 2026-02-21 09:49:07,283] Trial 123 finished with value: 0.8580351602762717 and parameters: {'layer1': 277, 'layer2': 68, 'layer3': 155, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.003567923219476336}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:38:39<4:17:04, 5141.53s/it]

[I 2026-02-21 09:49:28,217] Trial 124 finished with value: 0.8392034793023834 and parameters: {'layer1': 296, 'layer2': 117, 'layer3': 127, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.005220901952049724}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:38:58<4:17:04, 5141.53s/it]

[I 2026-02-21 09:49:47,217] Trial 125 finished with value: 0.8570605931223767 and parameters: {'layer1': 266, 'layer2': 44, 'layer3': 248, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.002531934635000049}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:39:21<4:17:04, 5141.53s/it]

[I 2026-02-21 09:50:10,060] Trial 126 finished with value: 0.8550429353902784 and parameters: {'layer1': 254, 'layer2': 474, 'layer3': 71, 'activation': 'relu', 'solver': 'adam', 'lr': 0.004618708176256496}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:39:41<4:17:04, 5141.53s/it]

[I 2026-02-21 09:50:30,606] Trial 127 finished with value: 0.8522675934541575 and parameters: {'layer1': 278, 'layer2': 107, 'layer3': 89, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0036927745564970947}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:39:49<4:17:04, 5141.53s/it]

[I 2026-02-21 09:50:38,630] Trial 128 finished with value: 0.8155772208149157 and parameters: {'layer1': 25, 'layer2': 352, 'layer3': 107, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.00918083614586041}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:40:08<4:17:04, 5141.53s/it]

[I 2026-02-21 09:50:57,842] Trial 129 finished with value: 0.8511915947814996 and parameters: {'layer1': 263, 'layer2': 89, 'layer3': 82, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.002112973768735201}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:40:17<4:17:04, 5141.53s/it]

[I 2026-02-21 09:51:06,638] Trial 130 finished with value: 0.8155772208149157 and parameters: {'layer1': 333, 'layer2': 29, 'layer3': 143, 'activation': 'logistic', 'solver': 'sgd', 'lr': 0.0012526791969058582}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:40:28<4:17:04, 5141.53s/it]

[I 2026-02-21 09:51:17,822] Trial 131 finished with value: 0.8155772208149157 and parameters: {'layer1': 211, 'layer2': 162, 'layer3': 168, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.007796353769132756}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:40:51<4:17:04, 5141.53s/it]

[I 2026-02-21 09:51:40,216] Trial 132 finished with value: 0.8548108511295943 and parameters: {'layer1': 224, 'layer2': 136, 'layer3': 198, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0010731603013469603}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:41:04<4:17:04, 5141.53s/it]

[I 2026-02-21 09:51:53,527] Trial 133 finished with value: 0.8228939795652419 and parameters: {'layer1': 201, 'layer2': 274, 'layer3': 54, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.005874113667345239}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:41:30<4:17:04, 5141.53s/it]

[I 2026-02-21 09:52:19,412] Trial 134 finished with value: 0.8576964512819453 and parameters: {'layer1': 244, 'layer2': 128, 'layer3': 235, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0006413839312547222}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:41:39<4:17:04, 5141.53s/it]

[I 2026-02-21 09:52:28,584] Trial 135 finished with value: 0.8153010866926277 and parameters: {'layer1': 178, 'layer2': 108, 'layer3': 430, 'activation': 'relu', 'solver': 'adam', 'lr': 3.6980831315186125e-05}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:41:53<4:17:04, 5141.53s/it]

[I 2026-02-21 09:52:42,651] Trial 136 finished with value: 0.8221608688905384 and parameters: {'layer1': 285, 'layer2': 51, 'layer3': 33, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.003056011904956914}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:42:04<4:17:04, 5141.53s/it]

[I 2026-02-21 09:52:52,956] Trial 137 finished with value: 0.8513553759042611 and parameters: {'layer1': 86, 'layer2': 10, 'layer3': 122, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0016285473238380832}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:42:26<4:17:04, 5141.53s/it]

[I 2026-02-21 09:53:15,419] Trial 138 finished with value: 0.8579658351168732 and parameters: {'layer1': 307, 'layer2': 316, 'layer3': 362, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0019457300117264524}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:42:46<4:17:04, 5141.53s/it]

[I 2026-02-21 09:53:35,678] Trial 139 finished with value: 0.8567768586270835 and parameters: {'layer1': 218, 'layer2': 81, 'layer3': 406, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0013647776641446956}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:43:10<4:17:04, 5141.53s/it]

[I 2026-02-21 09:53:59,763] Trial 140 finished with value: 0.8473534562233261 and parameters: {'layer1': 231, 'layer2': 219, 'layer3': 416, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0023883563355939783}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:43:30<4:17:04, 5141.53s/it]

[I 2026-02-21 09:54:18,879] Trial 141 finished with value: 0.8546061128766859 and parameters: {'layer1': 187, 'layer2': 171, 'layer3': 379, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.000893186460361616}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:43:49<4:17:04, 5141.53s/it]

[I 2026-02-21 09:54:38,703] Trial 142 finished with value: 0.8530200647320498 and parameters: {'layer1': 207, 'layer2': 150, 'layer3': 347, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0010411730079322816}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:44:10<4:17:04, 5141.53s/it]

[I 2026-02-21 09:54:59,160] Trial 143 finished with value: 0.8556889925750717 and parameters: {'layer1': 195, 'layer2': 190, 'layer3': 343, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0007502495737181678}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:44:32<4:17:04, 5141.53s/it]

[I 2026-02-21 09:55:21,678] Trial 144 finished with value: 0.8558842110573197 and parameters: {'layer1': 210, 'layer2': 176, 'layer3': 274, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0005410832344058816}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:44:48<4:17:04, 5141.53s/it]

[I 2026-02-21 09:55:37,583] Trial 145 finished with value: 0.8553775297974872 and parameters: {'layer1': 251, 'layer2': 206, 'layer3': 388, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0008873549090127932}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:45:11<4:17:04, 5141.53s/it]

[I 2026-02-21 09:56:00,297] Trial 146 finished with value: 0.8579880283486452 and parameters: {'layer1': 241, 'layer2': 238, 'layer3': 320, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0013932177761325796}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:45:33<4:17:04, 5141.53s/it]

[I 2026-02-21 09:56:21,968] Trial 147 finished with value: 0.8564686322363733 and parameters: {'layer1': 271, 'layer2': 100, 'layer3': 305, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0010186854879969866}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:45:47<4:17:04, 5141.53s/it]

[I 2026-02-21 09:56:36,363] Trial 148 finished with value: 0.8567275688936885 and parameters: {'layer1': 170, 'layer2': 118, 'layer3': 439, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0017771019315272083}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:46:05<4:17:04, 5141.53s/it]

[I 2026-02-21 09:56:54,693] Trial 149 finished with value: 0.831339642045694 and parameters: {'layer1': 223, 'layer2': 301, 'layer3': 455, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.004532879535089261}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:46:23<4:17:04, 5141.53s/it]

[I 2026-02-21 09:57:12,551] Trial 150 finished with value: 0.8552505950523777 and parameters: {'layer1': 203, 'layer2': 142, 'layer3': 116, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0026441497168419844}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:46:41<4:17:04, 5141.53s/it]

[I 2026-02-21 09:57:29,967] Trial 151 finished with value: 0.8569324852921447 and parameters: {'layer1': 190, 'layer2': 60, 'layer3': 371, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0014460578455791572}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:47:01<4:17:04, 5141.53s/it]

[I 2026-02-21 09:57:50,375] Trial 152 finished with value: 0.8558620589301255 and parameters: {'layer1': 182, 'layer2': 61, 'layer3': 358, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0015841396972880372}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:47:21<4:17:04, 5141.53s/it]

[I 2026-02-21 09:58:10,040] Trial 153 finished with value: 0.8581378156374144 and parameters: {'layer1': 190, 'layer2': 73, 'layer3': 380, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0012210240753524717}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:47:40<4:17:04, 5141.53s/it]

[I 2026-02-21 09:58:29,269] Trial 154 finished with value: 0.8552064128478826 and parameters: {'layer1': 158, 'layer2': 73, 'layer3': 396, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0006436098116965059}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:48:00<4:17:04, 5141.53s/it]

[I 2026-02-21 09:58:48,930] Trial 155 finished with value: 0.855804255663806 and parameters: {'layer1': 214, 'layer2': 94, 'layer3': 403, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.001147014728784491}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:48:08<4:17:04, 5141.53s/it]

[I 2026-02-21 09:58:57,375] Trial 156 finished with value: 0.819084096849599 and parameters: {'layer1': 234, 'layer2': 111, 'layer3': 222, 'activation': 'relu', 'solver': 'sgd', 'lr': 0.002131601634825093}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:48:17<4:17:04, 5141.53s/it]

[I 2026-02-21 09:59:06,133] Trial 157 finished with value: 0.8155772208149157 and parameters: {'layer1': 137, 'layer2': 77, 'layer3': 335, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0033131947697278142}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:48:38<4:17:04, 5141.53s/it]

[I 2026-02-21 09:59:26,993] Trial 158 finished with value: 0.8586766413768144 and parameters: {'layer1': 197, 'layer2': 127, 'layer3': 485, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0007312698255440691}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:49:00<4:17:04, 5141.53s/it]

[I 2026-02-21 09:59:49,680] Trial 159 finished with value: 0.8578485097216337 and parameters: {'layer1': 205, 'layer2': 127, 'layer3': 449, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.00047921976467693334}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:49:22<4:17:04, 5141.53s/it]

[I 2026-02-21 10:00:11,417] Trial 160 finished with value: 0.8589890644668154 and parameters: {'layer1': 222, 'layer2': 134, 'layer3': 478, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0007293489586167769}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:49:45<4:17:04, 5141.53s/it]

[I 2026-02-21 10:00:34,272] Trial 161 finished with value: 0.8531745099245109 and parameters: {'layer1': 225, 'layer2': 133, 'layer3': 466, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0008238428882732197}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:50:07<4:17:04, 5141.53s/it]

[I 2026-02-21 10:00:56,390] Trial 162 finished with value: 0.8571825440017253 and parameters: {'layer1': 217, 'layer2': 146, 'layer3': 490, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0005980932427563528}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:50:31<4:17:04, 5141.53s/it]

[I 2026-02-21 10:01:20,512] Trial 163 finished with value: 0.84851655114125 and parameters: {'layer1': 260, 'layer2': 155, 'layer3': 478, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.00031900562978638003}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:50:59<4:17:04, 5141.53s/it]

[I 2026-02-21 10:01:48,181] Trial 164 finished with value: 0.8573094380241709 and parameters: {'layer1': 238, 'layer2': 120, 'layer3': 498, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0009263252449044525}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:51:22<4:17:04, 5141.53s/it]

[I 2026-02-21 10:02:11,626] Trial 165 finished with value: 0.8564118328645065 and parameters: {'layer1': 304, 'layer2': 105, 'layer3': 488, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0006841958188706457}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:51:47<4:17:04, 5141.53s/it]

[I 2026-02-21 10:02:36,515] Trial 166 finished with value: 0.85815168653722 and parameters: {'layer1': 195, 'layer2': 134, 'layer3': 478, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0004446283010879655}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:52:01<4:17:04, 5141.53s/it]

[I 2026-02-21 10:02:50,762] Trial 167 finished with value: 0.8509108864639554 and parameters: {'layer1': 174, 'layer2': 182, 'layer3': 470, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0007282627520749337}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:52:19<4:17:04, 5141.53s/it]

[I 2026-02-21 10:03:07,878] Trial 168 finished with value: 0.8546187925187582 and parameters: {'layer1': 201, 'layer2': 392, 'layer3': 429, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0010388839982992742}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:52:43<4:17:04, 5141.53s/it]

[I 2026-02-21 10:03:32,356] Trial 169 finished with value: 0.8594772245128315 and parameters: {'layer1': 248, 'layer2': 114, 'layer3': 96, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0012806653644998917}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:53:01<4:17:04, 5141.53s/it]

[I 2026-02-21 10:03:50,527] Trial 170 finished with value: 0.8512961260478304 and parameters: {'layer1': 249, 'layer2': 95, 'layer3': 92, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0019264505717233624}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:53:17<4:17:04, 5141.53s/it]

[I 2026-02-21 10:04:06,020] Trial 171 finished with value: 0.8279827707185655 and parameters: {'layer1': 228, 'layer2': 114, 'layer3': 77, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.000798884834654349}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:53:42<4:17:04, 5141.53s/it]

[I 2026-02-21 10:04:31,176] Trial 172 finished with value: 0.8581126478386452 and parameters: {'layer1': 269, 'layer2': 125, 'layer3': 100, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0012501452842522036}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:54:05<4:17:04, 5141.53s/it]

[I 2026-02-21 10:04:54,141] Trial 173 finished with value: 0.8560336769083456 and parameters: {'layer1': 289, 'layer2': 247, 'layer3': 254, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0009737878739935933}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:54:25<4:17:04, 5141.53s/it]

[I 2026-02-21 10:05:14,194] Trial 174 finished with value: 0.8606016902678754 and parameters: {'layer1': 213, 'layer2': 139, 'layer3': 66, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.002506702880011367}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:54:44<4:17:04, 5141.53s/it]

[I 2026-02-21 10:05:33,352] Trial 175 finished with value: 0.857281156190402 and parameters: {'layer1': 241, 'layer2': 140, 'layer3': 81, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.003021916410824965}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:55:05<4:17:04, 5141.53s/it]

[I 2026-02-21 10:05:54,751] Trial 176 finished with value: 0.8598559971513741 and parameters: {'layer1': 216, 'layer2': 87, 'layer3': 64, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0026784852534413616}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:55:28<4:17:04, 5141.53s/it]

[I 2026-02-21 10:06:17,154] Trial 177 finished with value: 0.8515747224981485 and parameters: {'layer1': 218, 'layer2': 88, 'layer3': 57, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.003945372047789649}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:55:49<4:17:04, 5141.53s/it]

[I 2026-02-21 10:06:38,621] Trial 178 finished with value: 0.8566793846051622 and parameters: {'layer1': 232, 'layer2': 103, 'layer3': 62, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0027233554457855146}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:56:04<4:17:04, 5141.53s/it]

[I 2026-02-21 10:06:53,406] Trial 179 finished with value: 0.8531141201395309 and parameters: {'layer1': 258, 'layer2': 34, 'layer3': 42, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0024590775277365455}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:56:13<4:17:04, 5141.53s/it]

[I 2026-02-21 10:07:01,998] Trial 180 finished with value: 0.8155772208149157 and parameters: {'layer1': 245, 'layer2': 116, 'layer3': 50, 'activation': 'logistic', 'solver': 'sgd', 'lr': 0.0035616057450035547}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:56:22<4:17:04, 5141.53s/it]

[I 2026-02-21 10:07:11,703] Trial 181 finished with value: 0.8155772208149157 and parameters: {'layer1': 212, 'layer2': 129, 'layer3': 26, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.00539805029053264}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:56:46<4:17:04, 5141.53s/it]

[I 2026-02-21 10:07:35,512] Trial 182 finished with value: 0.8570102825904975 and parameters: {'layer1': 225, 'layer2': 108, 'layer3': 63, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0020921603737824247}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:57:08<4:17:04, 5141.53s/it]

[I 2026-02-21 10:07:57,543] Trial 183 finished with value: 0.8597421733357562 and parameters: {'layer1': 182, 'layer2': 88, 'layer3': 94, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0016593120645776878}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:57:27<4:17:04, 5141.53s/it]

[I 2026-02-21 10:08:16,328] Trial 184 finished with value: 0.8481826090520223 and parameters: {'layer1': 182, 'layer2': 84, 'layer3': 107, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0017081346714001517}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:57:45<4:17:04, 5141.53s/it]

[I 2026-02-21 10:08:34,377] Trial 185 finished with value: 0.8598405825249129 and parameters: {'layer1': 197, 'layer2': 95, 'layer3': 74, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0024319281362583335}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:58:05<4:17:04, 5141.53s/it]

[I 2026-02-21 10:08:54,306] Trial 186 finished with value: 0.8471485975484578 and parameters: {'layer1': 273, 'layer2': 97, 'layer3': 92, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.002394703666670198}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:58:27<4:17:04, 5141.53s/it]

[I 2026-02-21 10:09:16,242] Trial 187 finished with value: 0.846219631899395 and parameters: {'layer1': 212, 'layer2': 89, 'layer3': 73, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0029127429722942215}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:58:38<4:17:04, 5141.53s/it]

[I 2026-02-21 10:09:27,481] Trial 188 finished with value: 0.8381107939331957 and parameters: {'layer1': 118, 'layer2': 49, 'layer3': 87, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0015161444061074958}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:59:00<4:17:04, 5141.53s/it]

[I 2026-02-21 10:09:49,122] Trial 189 finished with value: 0.8601076853568813 and parameters: {'layer1': 196, 'layer2': 100, 'layer3': 78, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0020196419574095045}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:59:17<4:17:04, 5141.53s/it]

[I 2026-02-21 10:10:06,357] Trial 190 finished with value: 0.8595310839388368 and parameters: {'layer1': 195, 'layer2': 111, 'layer3': 67, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0017248469372515719}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:59:34<4:17:04, 5141.53s/it]

[I 2026-02-21 10:10:23,346] Trial 191 finished with value: 0.8612582464709202 and parameters: {'layer1': 205, 'layer2': 113, 'layer3': 68, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0018648687905607512}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [22:59:55<4:17:04, 5141.53s/it]

[I 2026-02-21 10:10:43,893] Trial 192 finished with value: 0.8582666157541927 and parameters: {'layer1': 197, 'layer2': 118, 'layer3': 65, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.002036763603748634}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [23:00:12<4:17:04, 5141.53s/it]

[I 2026-02-21 10:11:01,436] Trial 193 finished with value: 0.8460529807120452 and parameters: {'layer1': 180, 'layer2': 109, 'layer3': 77, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.002523708201664081}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [23:00:29<4:17:04, 5141.53s/it]

[I 2026-02-21 10:11:18,438] Trial 194 finished with value: 0.8615798976707815 and parameters: {'layer1': 202, 'layer2': 121, 'layer3': 54, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0018138233397188225}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [23:00:45<4:17:04, 5141.53s/it]

[I 2026-02-21 10:11:34,540] Trial 195 finished with value: 0.85603083424802 and parameters: {'layer1': 202, 'layer2': 121, 'layer3': 67, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0016866864307461592}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [23:01:02<4:17:04, 5141.53s/it]

[I 2026-02-21 10:11:51,255] Trial 196 finished with value: 0.8438092304611512 and parameters: {'layer1': 186, 'layer2': 101, 'layer3': 51, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.001731817190257224}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [23:01:16<4:17:04, 5141.53s/it]

[I 2026-02-21 10:12:05,546] Trial 197 finished with value: 0.8561960323363701 and parameters: {'layer1': 170, 'layer2': 111, 'layer3': 60, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0013391875831922076}. Best is trial 61 with value: 0.862031756607591.

Training Exact MLP (Paper):  79%|███████▊  | 11/14 [23:01:35<4:17:04, 5141.53s/it]

[I 2026-02-21 10:12:24,776] Trial 198 finished with value: 0.8634647352900267 and parameters: {'layer1': 196, 'layer2': 127, 'layer3': 33, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.002186865948053513}. Best is trial 198 with value: 0.8634647352900267.

Best trial: 198. Best value: 0.863465: 100%|██████████| 200/200 [58:52<00:00, 17.66s/it]

[I 2026-02-21 10:12:43,855] Trial 199 finished with value: 0.8607467936694821 and parameters: {'layer1': 207, 'layer2': 93, 'layer3': 40, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0021843684101212637}. Best is trial 198 with value: 0.8634647352900267.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:01:55<2:35:04, 4652.21s/it][I 2026-02-21 10:12:44,558] A new study created in memory with name: no-name-caca5a0c-236b-4157-8810-b4a17d4a00c8

  → Best model saved.

[Exact Paper MLP] Pseudomonas_Aeruginosa | Imipenem

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:02:05<2:35:04, 4652.21s/it]

[I 2026-02-21 10:12:54,266] Trial 0 finished with value: 0.3457965704856461 and parameters: {'layer1': 281, 'layer2': 76, 'layer3': 395, 'activation': 'relu', 'solver': 'sgd', 'lr': 1.3831246456420251e-05}. Best is trial 0 with value: 0.3457965704856461.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:02:14<2:35:04, 4652.21s/it]

[I 2026-02-21 10:13:03,415] Trial 1 finished with value: 0.8171622401256972 and parameters: {'layer1': 311, 'layer2': 278, 'layer3': 219, 'activation': 'relu', 'solver': 'sgd', 'lr': 0.009356936075372435}. Best is trial 1 with value: 0.8171622401256972.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:02:31<2:35:04, 4652.21s/it]

[I 2026-02-21 10:13:20,099] Trial 2 finished with value: 0.8464354968442299 and parameters: {'layer1': 208, 'layer2': 496, 'layer3': 270, 'activation': 'identity', 'solver': 'adam', 'lr': 0.005709605313005134}. Best is trial 2 with value: 0.8464354968442299.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:02:47<2:35:04, 4652.21s/it]

[I 2026-02-21 10:13:36,386] Trial 3 finished with value: 0.8232100512652802 and parameters: {'layer1': 442, 'layer2': 418, 'layer3': 477, 'activation': 'relu', 'solver': 'sgd', 'lr': 0.00031731524204977295}. Best is trial 2 with value: 0.8464354968442299.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:03:03<2:35:04, 4652.21s/it]

[I 2026-02-21 10:13:52,353] Trial 4 finished with value: 0.8184879496639109 and parameters: {'layer1': 373, 'layer2': 53, 'layer3': 462, 'activation': 'relu', 'solver': 'adam', 'lr': 1.2034270825748457e-06}. Best is trial 2 with value: 0.8464354968442299.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:03:10<2:35:04, 4652.21s/it]

[I 2026-02-21 10:13:59,691] Trial 5 finished with value: 0.8184879496639109 and parameters: {'layer1': 122, 'layer2': 123, 'layer3': 10, 'activation': 'identity', 'solver': 'adam', 'lr': 4.46343478743166e-05}. Best is trial 2 with value: 0.8464354968442299.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:04:00<2:35:04, 4652.21s/it]

[I 2026-02-21 10:14:49,535] Trial 6 finished with value: 0.5037728050121146 and parameters: {'layer1': 366, 'layer2': 229, 'layer3': 338, 'activation': 'relu', 'solver': 'sgd', 'lr': 1.0507025213936888e-05}. Best is trial 2 with value: 0.8464354968442299.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:04:07<2:35:04, 4652.21s/it]

[I 2026-02-21 10:14:56,619] Trial 7 finished with value: 0.8178894787605937 and parameters: {'layer1': 122, 'layer2': 344, 'layer3': 451, 'activation': 'identity', 'solver': 'sgd', 'lr': 0.0006754183463346154}. Best is trial 2 with value: 0.8464354968442299.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:04:17<2:35:04, 4652.21s/it]

[I 2026-02-21 10:15:06,690] Trial 8 finished with value: 0.8184879496639109 and parameters: {'layer1': 205, 'layer2': 15, 'layer3': 199, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.0519448302646077e-05}. Best is trial 2 with value: 0.8464354968442299.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:04:26<2:35:04, 4652.21s/it]

[I 2026-02-21 10:15:15,187] Trial 9 finished with value: 0.8184879496639109 and parameters: {'layer1': 105, 'layer2': 368, 'layer3': 290, 'activation': 'identity', 'solver': 'adam', 'lr': 2.4620035248791206e-05}. Best is trial 2 with value: 0.8464354968442299.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:04:33<2:35:04, 4652.21s/it]

[I 2026-02-21 10:15:22,705] Trial 10 finished with value: 0.8171622401256972 and parameters: {'layer1': 10, 'layer2': 493, 'layer3': 124, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0052303520485123866}. Best is trial 2 with value: 0.8464354968442299.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:04:45<2:35:04, 4652.21s/it]

[I 2026-02-21 10:15:34,779] Trial 11 finished with value: 0.8171622401256972 and parameters: {'layer1': 493, 'layer2': 500, 'layer3': 358, 'activation': 'logistic', 'solver': 'sgd', 'lr': 0.00047578009532588816}. Best is trial 2 with value: 0.8464354968442299.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:05:16<2:35:04, 4652.21s/it]

[I 2026-02-21 10:16:05,528] Trial 12 finished with value: 0.8509354559345468 and parameters: {'layer1': 478, 'layer2': 417, 'layer3': 127, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0010976997547060712}. Best is trial 12 with value: 0.8509354559345468.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:05:33<2:35:04, 4652.21s/it]

[I 2026-02-21 10:16:22,305] Trial 13 finished with value: 0.8380967036721116 and parameters: {'layer1': 214, 'layer2': 427, 'layer3': 128, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0021045406080201895}. Best is trial 12 with value: 0.8509354559345468.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:05:47<2:35:04, 4652.21s/it]

[I 2026-02-21 10:16:36,839] Trial 14 finished with value: 0.8324322422038216 and parameters: {'layer1': 225, 'layer2': 410, 'layer3': 86, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0021743322115568777}. Best is trial 12 with value: 0.8509354559345468.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:06:16<2:35:04, 4652.21s/it]

[I 2026-02-21 10:17:05,546] Trial 15 finished with value: 0.8415392140171345 and parameters: {'layer1': 391, 'layer2': 292, 'layer3': 258, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0019001327190360962}. Best is trial 12 with value: 0.8509354559345468.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:06:39<2:35:04, 4652.21s/it]

[I 2026-02-21 10:17:28,413] Trial 16 finished with value: 0.8541718194706414 and parameters: {'layer1': 499, 'layer2': 181, 'layer3': 171, 'activation': 'identity', 'solver': 'adam', 'lr': 0.00018433606232877542}. Best is trial 16 with value: 0.8541718194706414.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:07:05<2:35:04, 4652.21s/it]

[I 2026-02-21 10:17:53,967] Trial 17 finished with value: 0.853641842514684 and parameters: {'layer1': 489, 'layer2': 189, 'layer3': 27, 'activation': 'identity', 'solver': 'adam', 'lr': 0.00013329756130196034}. Best is trial 16 with value: 0.8541718194706414.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:07:28<2:35:04, 4652.21s/it]

[I 2026-02-21 10:18:17,620] Trial 18 finished with value: 0.8514616586641907 and parameters: {'layer1': 428, 'layer2': 183, 'layer3': 20, 'activation': 'identity', 'solver': 'adam', 'lr': 0.00014898975111739336}. Best is trial 16 with value: 0.8541718194706414.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:07:57<2:35:04, 4652.21s/it]

[I 2026-02-21 10:18:45,898] Trial 19 finished with value: 0.8518805591870924 and parameters: {'layer1': 500, 'layer2': 163, 'layer3': 63, 'activation': 'identity', 'solver': 'adam', 'lr': 9.81909513518367e-05}. Best is trial 16 with value: 0.8541718194706414.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:08:09<2:35:04, 4652.21s/it]

[I 2026-02-21 10:18:58,547] Trial 20 finished with value: 0.8184879496639109 and parameters: {'layer1': 325, 'layer2': 224, 'layer3': 182, 'activation': 'identity', 'solver': 'adam', 'lr': 2.89806492624439e-06}. Best is trial 16 with value: 0.8541718194706414.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:08:39<2:35:04, 4652.21s/it]

[I 2026-02-21 10:19:28,377] Trial 21 finished with value: 0.8539658049354726 and parameters: {'layer1': 494, 'layer2': 156, 'layer3': 65, 'activation': 'identity', 'solver': 'adam', 'lr': 0.00011282217240842696}. Best is trial 16 with value: 0.8541718194706414.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:09:06<2:35:04, 4652.21s/it]

[I 2026-02-21 10:19:55,155] Trial 22 finished with value: 0.852473081321351 and parameters: {'layer1': 451, 'layer2': 115, 'layer3': 60, 'activation': 'identity', 'solver': 'adam', 'lr': 0.00014286747652055264}. Best is trial 16 with value: 0.8541718194706414.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:09:41<2:35:04, 4652.21s/it]

[I 2026-02-21 10:20:29,884] Trial 23 finished with value: 0.856302638710494 and parameters: {'layer1': 409, 'layer2': 177, 'layer3': 166, 'activation': 'identity', 'solver': 'adam', 'lr': 6.0577445111429234e-05}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:10:12<2:35:04, 4652.21s/it]

[I 2026-02-21 10:21:01,201] Trial 24 finished with value: 0.8544394261083035 and parameters: {'layer1': 404, 'layer2': 136, 'layer3': 165, 'activation': 'identity', 'solver': 'adam', 'lr': 7.01925784839746e-05}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:10:26<2:35:04, 4652.21s/it]

[I 2026-02-21 10:21:15,783] Trial 25 finished with value: 0.8171622401256972 and parameters: {'layer1': 409, 'layer2': 103, 'layer3': 166, 'activation': 'logistic', 'solver': 'adam', 'lr': 3.5873221909658794e-05}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:10:45<2:35:04, 4652.21s/it]

[I 2026-02-21 10:21:33,952] Trial 26 finished with value: 0.8508414796037316 and parameters: {'layer1': 341, 'layer2': 225, 'layer3': 218, 'activation': 'identity', 'solver': 'adam', 'lr': 0.00028489758324251764}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:11:17<2:35:04, 4652.21s/it]

[I 2026-02-21 10:22:06,206] Trial 27 finished with value: 0.8542679947424425 and parameters: {'layer1': 451, 'layer2': 145, 'layer3': 160, 'activation': 'identity', 'solver': 'adam', 'lr': 5.830390950527904e-05}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:11:52<2:35:04, 4652.21s/it]

[I 2026-02-21 10:22:41,273] Trial 28 finished with value: 0.8552778144312008 and parameters: {'layer1': 411, 'layer2': 134, 'layer3': 151, 'activation': 'identity', 'solver': 'adam', 'lr': 5.322745322128152e-05}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:12:09<2:35:04, 4652.21s/it]

[I 2026-02-21 10:22:58,745] Trial 29 finished with value: 0.8231624524443768 and parameters: {'layer1': 261, 'layer2': 69, 'layer3': 103, 'activation': 'identity', 'solver': 'sgd', 'lr': 1.703019638692536e-05}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:12:25<2:35:04, 4652.21s/it]

[I 2026-02-21 10:23:14,108] Trial 30 finished with value: 0.8184879496639109 and parameters: {'layer1': 279, 'layer2': 33, 'layer3': 228, 'activation': 'logistic', 'solver': 'adam', 'lr': 5.313084130126003e-06}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:12:56<2:35:04, 4652.21s/it]

[I 2026-02-21 10:23:45,569] Trial 31 finished with value: 0.8534406642336998 and parameters: {'layer1': 416, 'layer2': 137, 'layer3': 150, 'activation': 'identity', 'solver': 'adam', 'lr': 6.849707536094049e-05}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:13:25<2:35:04, 4652.21s/it]

[I 2026-02-21 10:24:14,538] Trial 32 finished with value: 0.8516059255665518 and parameters: {'layer1': 353, 'layer2': 84, 'layer3': 144, 'activation': 'identity', 'solver': 'adam', 'lr': 4.711309045062537e-05}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:13:56<2:35:04, 4652.21s/it]

[I 2026-02-21 10:24:45,492] Trial 33 finished with value: 0.8547475183639641 and parameters: {'layer1': 456, 'layer2': 264, 'layer3': 300, 'activation': 'identity', 'solver': 'adam', 'lr': 6.393884753586805e-05}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:14:11<2:35:04, 4652.21s/it]

[I 2026-02-21 10:24:59,936] Trial 34 finished with value: 0.8195143531348126 and parameters: {'layer1': 302, 'layer2': 264, 'layer3': 320, 'activation': 'identity', 'solver': 'sgd', 'lr': 2.7767949849414058e-05}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:14:24<2:35:04, 4652.21s/it]

[I 2026-02-21 10:25:13,335] Trial 35 finished with value: 0.8171622401256972 and parameters: {'layer1': 392, 'layer2': 304, 'layer3': 402, 'activation': 'relu', 'solver': 'adam', 'lr': 6.279051000413858e-06}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:14:48<2:35:04, 4652.21s/it]

[I 2026-02-21 10:25:37,369] Trial 36 finished with value: 0.8512141778813472 and parameters: {'layer1': 393, 'layer2': 205, 'layer3': 243, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0002747582723766618}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:15:03<2:35:04, 4652.21s/it]

[I 2026-02-21 10:25:52,377] Trial 37 finished with value: 0.8171622401256972 and parameters: {'layer1': 459, 'layer2': 257, 'layer3': 291, 'activation': 'relu', 'solver': 'adam', 'lr': 1.83710706539127e-05}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:15:16<2:35:04, 4652.21s/it]

[I 2026-02-21 10:26:04,957] Trial 38 finished with value: 0.8209153046724234 and parameters: {'layer1': 372, 'layer2': 99, 'layer3': 206, 'activation': 'identity', 'solver': 'sgd', 'lr': 7.698983840713121e-05}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:15:51<2:35:04, 4652.21s/it]

[I 2026-02-21 10:26:39,855] Trial 39 finished with value: 0.8526614593458293 and parameters: {'layer1': 433, 'layer2': 303, 'layer3': 280, 'activation': 'identity', 'solver': 'adam', 'lr': 3.4701020087390314e-05}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:16:02<2:35:04, 4652.21s/it]

[I 2026-02-21 10:26:51,076] Trial 40 finished with value: 0.8184879496639109 and parameters: {'layer1': 325, 'layer2': 238, 'layer3': 386, 'activation': 'relu', 'solver': 'sgd', 'lr': 0.0004824682521847701}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:16:36<2:35:04, 4652.21s/it]

[I 2026-02-21 10:27:25,403] Trial 41 finished with value: 0.8530935776184909 and parameters: {'layer1': 460, 'layer2': 142, 'layer3': 191, 'activation': 'identity', 'solver': 'adam', 'lr': 6.032096703324044e-05}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:17:14<2:35:04, 4652.21s/it]

[I 2026-02-21 10:28:03,506] Trial 42 finished with value: 0.8531971834553111 and parameters: {'layer1': 461, 'layer2': 56, 'layer3': 234, 'activation': 'identity', 'solver': 'adam', 'lr': 5.405562216530476e-05}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:17:27<2:35:04, 4652.21s/it]

[I 2026-02-21 10:28:16,814] Trial 43 finished with value: 0.8171622401256972 and parameters: {'layer1': 413, 'layer2': 134, 'layer3': 98, 'activation': 'identity', 'solver': 'adam', 'lr': 2.301985940038703e-05}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:17:41<2:35:04, 4652.21s/it]

[I 2026-02-21 10:28:30,286] Trial 44 finished with value: 0.8171622401256972 and parameters: {'layer1': 434, 'layer2': 161, 'layer3': 318, 'activation': 'identity', 'solver': 'adam', 'lr': 1.083346109210527e-05}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:18:05<2:35:04, 4652.21s/it]

[I 2026-02-21 10:28:54,327] Trial 45 finished with value: 0.8480813985400241 and parameters: {'layer1': 383, 'layer2': 90, 'layer3': 155, 'activation': 'identity', 'solver': 'adam', 'lr': 0.00022114028458036818}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:18:18<2:35:04, 4652.21s/it]

[I 2026-02-21 10:29:07,451] Trial 46 finished with value: 0.8171622401256972 and parameters: {'layer1': 351, 'layer2': 205, 'layer3': 196, 'activation': 'logistic', 'solver': 'adam', 'lr': 8.529155133240271e-05}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:18:28<2:35:04, 4652.21s/it]

[I 2026-02-21 10:29:17,302] Trial 47 finished with value: 0.8184879496639109 and parameters: {'layer1': 181, 'layer2': 334, 'layer3': 115, 'activation': 'identity', 'solver': 'adam', 'lr': 3.393871863385908e-05}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:18:42<2:35:04, 4652.21s/it]

[I 2026-02-21 10:29:31,062] Trial 48 finished with value: 0.8184879496639109 and parameters: {'layer1': 473, 'layer2': 117, 'layer3': 254, 'activation': 'identity', 'solver': 'adam', 'lr': 1.2984743935152757e-05}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:18:52<2:35:04, 4652.21s/it]

[I 2026-02-21 10:29:41,673] Trial 49 finished with value: 0.819910847691361 and parameters: {'layer1': 408, 'layer2': 204, 'layer3': 148, 'activation': 'identity', 'solver': 'sgd', 'lr': 0.00045369007223735187}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:19:00<2:35:04, 4652.21s/it]

[I 2026-02-21 10:29:49,421] Trial 50 finished with value: 0.8184879496639109 and parameters: {'layer1': 51, 'layer2': 174, 'layer3': 211, 'activation': 'tanh', 'solver': 'adam', 'lr': 4.77016329670677e-05}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:19:22<2:35:04, 4652.21s/it]

[I 2026-02-21 10:30:11,636] Trial 51 finished with value: 0.8492637149681656 and parameters: {'layer1': 445, 'layer2': 145, 'layer3': 181, 'activation': 'identity', 'solver': 'adam', 'lr': 0.00017678194563651081}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:19:48<2:35:04, 4652.21s/it]

[I 2026-02-21 10:30:37,775] Trial 52 finished with value: 0.8536797539281977 and parameters: {'layer1': 476, 'layer2': 188, 'layer3': 176, 'activation': 'identity', 'solver': 'adam', 'lr': 8.85604962290313e-05}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:20:12<2:35:04, 4652.21s/it]

[I 2026-02-21 10:31:01,073] Trial 53 finished with value: 0.8512741076903525 and parameters: {'layer1': 430, 'layer2': 242, 'layer3': 135, 'activation': 'identity', 'solver': 'adam', 'lr': 0.00018165304360784926}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:20:39<2:35:04, 4652.21s/it]

[I 2026-02-21 10:31:28,282] Trial 54 finished with value: 0.8525874868497814 and parameters: {'layer1': 477, 'layer2': 275, 'layer3': 162, 'activation': 'identity', 'solver': 'adam', 'lr': 0.00010986834175653036}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:21:00<2:35:04, 4652.21s/it]

[I 2026-02-21 10:31:48,901] Trial 55 finished with value: 0.8492941021215868 and parameters: {'layer1': 448, 'layer2': 127, 'layer3': 84, 'activation': 'identity', 'solver': 'adam', 'lr': 0.000893299358285917}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:21:30<2:35:04, 4652.21s/it]

[I 2026-02-21 10:32:19,308] Trial 56 finished with value: 0.852355243592636 and parameters: {'layer1': 372, 'layer2': 161, 'layer3': 115, 'activation': 'tanh', 'solver': 'adam', 'lr': 6.269812862275999e-05}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:21:45<2:35:04, 4652.21s/it]

[I 2026-02-21 10:32:34,373] Trial 57 finished with value: 0.8171622401256972 and parameters: {'layer1': 496, 'layer2': 206, 'layer3': 346, 'activation': 'relu', 'solver': 'adam', 'lr': 2.268394880402828e-05}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:21:59<2:35:04, 4652.21s/it]

[I 2026-02-21 10:32:48,592] Trial 58 finished with value: 0.8171622401256972 and parameters: {'layer1': 401, 'layer2': 176, 'layer3': 171, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0001139787639193348}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:22:11<2:35:04, 4652.21s/it]

[I 2026-02-21 10:33:00,809] Trial 59 finished with value: 0.8171622401256972 and parameters: {'layer1': 424, 'layer2': 36, 'layer3': 45, 'activation': 'identity', 'solver': 'adam', 'lr': 4.1006518228997225e-05}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:22:25<2:35:04, 4652.21s/it]

[I 2026-02-21 10:33:14,754] Trial 60 finished with value: 0.8171622401256972 and parameters: {'layer1': 482, 'layer2': 107, 'layer3': 298, 'activation': 'identity', 'solver': 'adam', 'lr': 7.240787700049774e-06}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:22:51<2:35:04, 4652.21s/it]

[I 2026-02-21 10:33:40,154] Trial 61 finished with value: 0.8493569954388127 and parameters: {'layer1': 466, 'layer2': 152, 'layer3': 138, 'activation': 'identity', 'solver': 'adam', 'lr': 0.00021787829400540137}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:23:13<2:35:04, 4652.21s/it]

[I 2026-02-21 10:34:02,074] Trial 62 finished with value: 0.8488295072520577 and parameters: {'layer1': 496, 'layer2': 219, 'layer3': 77, 'activation': 'identity', 'solver': 'adam', 'lr': 0.00037578549595057803}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:23:41<2:35:04, 4652.21s/it]

[I 2026-02-21 10:34:30,451] Trial 63 finished with value: 0.8497913714614238 and parameters: {'layer1': 445, 'layer2': 71, 'layer3': 269, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0001453513997253755}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:24:07<2:35:04, 4652.21s/it]

[I 2026-02-21 10:34:56,026] Trial 64 finished with value: 0.852647222890306 and parameters: {'layer1': 480, 'layer2': 170, 'layer3': 496, 'activation': 'identity', 'solver': 'adam', 'lr': 0.00010207957513096028}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:24:40<2:35:04, 4652.21s/it]

[I 2026-02-21 10:35:29,133] Trial 65 finished with value: 0.8545101891678689 and parameters: {'layer1': 499, 'layer2': 123, 'layer3': 33, 'activation': 'identity', 'solver': 'adam', 'lr': 6.82522294502701e-05}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:24:48<2:35:04, 4652.21s/it]

[I 2026-02-21 10:35:37,404] Trial 66 finished with value: 0.8171622401256972 and parameters: {'layer1': 162, 'layer2': 122, 'layer3': 33, 'activation': 'identity', 'solver': 'adam', 'lr': 2.8380253769669486e-05}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:25:01<2:35:04, 4652.21s/it]

[I 2026-02-21 10:35:50,196] Trial 67 finished with value: 0.8180959969769228 and parameters: {'layer1': 422, 'layer2': 94, 'layer3': 12, 'activation': 'identity', 'solver': 'sgd', 'lr': 7.094040320231468e-05}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:25:17<2:35:04, 4652.21s/it]

[I 2026-02-21 10:36:06,105] Trial 68 finished with value: 0.8188095968756534 and parameters: {'layer1': 452, 'layer2': 189, 'layer3': 103, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.1993329024049438e-06}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:25:51<2:35:04, 4652.21s/it]

[I 2026-02-21 10:36:40,364] Trial 69 finished with value: 0.8520445657953102 and parameters: {'layer1': 439, 'layer2': 328, 'layer3': 226, 'activation': 'identity', 'solver': 'adam', 'lr': 5.5930280433855745e-05}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:26:07<2:35:04, 4652.21s/it]

[I 2026-02-21 10:36:55,926] Trial 70 finished with value: 0.8171622401256972 and parameters: {'layer1': 388, 'layer2': 147, 'layer3': 123, 'activation': 'logistic', 'solver': 'adam', 'lr': 4.212495060143354e-05}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:26:35<2:35:04, 4652.21s/it]

[I 2026-02-21 10:37:24,805] Trial 71 finished with value: 0.8518202507687453 and parameters: {'layer1': 491, 'layer2': 128, 'layer3': 57, 'activation': 'identity', 'solver': 'adam', 'lr': 0.00012434181423411067}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:27:04<2:35:04, 4652.21s/it]

[I 2026-02-21 10:37:53,792] Trial 72 finished with value: 0.8506215225021805 and parameters: {'layer1': 468, 'layer2': 161, 'layer3': 73, 'activation': 'identity', 'solver': 'adam', 'lr': 8.95520536990351e-05}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:27:31<2:35:04, 4652.21s/it]

[I 2026-02-21 10:38:20,593] Trial 73 finished with value: 0.854526815586991 and parameters: {'layer1': 496, 'layer2': 192, 'layer3': 30, 'activation': 'identity', 'solver': 'adam', 'lr': 7.23041746846554e-05}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:27:57<2:35:04, 4652.21s/it]

[I 2026-02-21 10:38:46,226] Trial 74 finished with value: 0.83332985982874 and parameters: {'layer1': 500, 'layer2': 193, 'layer3': 44, 'activation': 'identity', 'solver': 'adam', 'lr': 3.149272573602971e-05}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:28:21<2:35:04, 4652.21s/it]

[I 2026-02-21 10:39:10,783] Trial 75 finished with value: 0.8443023563067656 and parameters: {'layer1': 459, 'layer2': 238, 'layer3': 189, 'activation': 'identity', 'solver': 'adam', 'lr': 0.008357218866897026}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:28:35<2:35:04, 4652.21s/it]

[I 2026-02-21 10:39:24,101] Trial 76 finished with value: 0.8171622401256972 and parameters: {'layer1': 362, 'layer2': 285, 'layer3': 312, 'activation': 'relu', 'solver': 'adam', 'lr': 1.6593553240605975e-05}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:28:47<2:35:04, 4652.21s/it]

[I 2026-02-21 10:39:36,832] Trial 77 finished with value: 0.8215583232192909 and parameters: {'layer1': 401, 'layer2': 109, 'layer3': 243, 'activation': 'identity', 'solver': 'sgd', 'lr': 6.994181241723854e-05}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:29:11<2:35:04, 4652.21s/it]

[I 2026-02-21 10:40:00,589] Trial 78 finished with value: 0.8535592860393105 and parameters: {'layer1': 423, 'layer2': 472, 'layer3': 94, 'activation': 'identity', 'solver': 'adam', 'lr': 0.00024283352016333645}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:29:36<2:35:04, 4652.21s/it]

[I 2026-02-21 10:40:25,767] Trial 79 finished with value: 0.8501861219501116 and parameters: {'layer1': 484, 'layer2': 220, 'layer3': 157, 'activation': 'identity', 'solver': 'adam', 'lr': 0.00016759864016856245}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:30:08<2:35:04, 4652.21s/it]

[I 2026-02-21 10:40:57,418] Trial 80 finished with value: 0.8539793186596281 and parameters: {'layer1': 231, 'layer2': 251, 'layer3': 205, 'activation': 'identity', 'solver': 'adam', 'lr': 4.2785743184798984e-05}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:30:36<2:35:04, 4652.21s/it]

[I 2026-02-21 10:41:24,894] Trial 81 finished with value: 0.8525818257075686 and parameters: {'layer1': 251, 'layer2': 249, 'layer3': 200, 'activation': 'identity', 'solver': 'adam', 'lr': 5.720752265907878e-05}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:31:01<2:35:04, 4652.21s/it]

[I 2026-02-21 10:41:50,707] Trial 82 finished with value: 0.8507521526387019 and parameters: {'layer1': 247, 'layer2': 178, 'layer3': 211, 'activation': 'identity', 'solver': 'adam', 'lr': 4.2129958619917234e-05}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:31:13<2:35:04, 4652.21s/it]

[I 2026-02-21 10:42:02,535] Trial 83 finished with value: 0.8184879496639109 and parameters: {'layer1': 285, 'layer2': 260, 'layer3': 169, 'activation': 'identity', 'solver': 'adam', 'lr': 2.1823429985638608e-05}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:31:36<2:35:04, 4652.21s/it]

[I 2026-02-21 10:42:25,607] Trial 84 finished with value: 0.8555294750585285 and parameters: {'layer1': 205, 'layer2': 137, 'layer3': 182, 'activation': 'identity', 'solver': 'adam', 'lr': 7.951546800871036e-05}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:31:56<2:35:04, 4652.21s/it]

[I 2026-02-21 10:42:45,021] Trial 85 finished with value: 0.8518278055267837 and parameters: {'layer1': 184, 'layer2': 135, 'layer3': 143, 'activation': 'identity', 'solver': 'adam', 'lr': 8.121600354276725e-05}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:32:16<2:35:04, 4652.21s/it]

[I 2026-02-21 10:43:05,290] Trial 86 finished with value: 0.8416717452822606 and parameters: {'layer1': 132, 'layer2': 145, 'layer3': 120, 'activation': 'identity', 'solver': 'adam', 'lr': 5.303454412352349e-05}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:32:45<2:35:04, 4652.21s/it]

[I 2026-02-21 10:43:34,293] Trial 87 finished with value: 0.8543951038911846 and parameters: {'layer1': 454, 'layer2': 81, 'layer3': 182, 'activation': 'identity', 'solver': 'adam', 'lr': 0.00012317844817041947}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:33:15<2:35:04, 4652.21s/it]

[I 2026-02-21 10:44:04,733] Trial 88 finished with value: 0.851785002304489 and parameters: {'layer1': 458, 'layer2': 53, 'layer3': 186, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.00013371825165982645}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:33:29<2:35:04, 4652.21s/it]

[I 2026-02-21 10:44:18,380] Trial 89 finished with value: 0.8184879496639107 and parameters: {'layer1': 435, 'layer2': 80, 'layer3': 258, 'activation': 'identity', 'solver': 'sgd', 'lr': 7.725469741316005e-05}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:33:39<2:35:04, 4652.21s/it]

[I 2026-02-21 10:44:27,855] Trial 90 finished with value: 0.8171622401256972 and parameters: {'layer1': 194, 'layer2': 96, 'layer3': 27, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.00010063472510283464}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:33:58<2:35:04, 4652.21s/it]

[I 2026-02-21 10:44:47,110] Trial 91 finished with value: 0.8506654529364507 and parameters: {'layer1': 472, 'layer2': 116, 'layer3': 160, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0003430801186610026}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:34:24<2:35:04, 4652.21s/it]

[I 2026-02-21 10:45:13,726] Trial 92 finished with value: 0.8474822922066625 and parameters: {'layer1': 484, 'layer2': 65, 'layer3': 176, 'activation': 'identity', 'solver': 'adam', 'lr': 0.00017966012061835994}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:34:53<2:35:04, 4652.21s/it]

[I 2026-02-21 10:45:42,408] Trial 93 finished with value: 0.8526243434094217 and parameters: {'layer1': 412, 'layer2': 136, 'layer3': 133, 'activation': 'identity', 'solver': 'adam', 'lr': 6.215722692211885e-05}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:35:35<2:35:04, 4652.21s/it]

[I 2026-02-21 10:46:24,243] Trial 94 finished with value: 0.8535886082016366 and parameters: {'layer1': 446, 'layer2': 168, 'layer3': 220, 'activation': 'identity', 'solver': 'adam', 'lr': 3.54677662866377e-05}. Best is trial 23 with value: 0.856302638710494.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:36:09<2:35:04, 4652.21s/it]

[I 2026-02-21 10:46:58,664] Trial 95 finished with value: 0.8565269889658783 and parameters: {'layer1': 380, 'layer2': 194, 'layer3': 106, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00012408711514263454}. Best is trial 95 with value: 0.8565269889658783.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:36:44<2:35:04, 4652.21s/it]

[I 2026-02-21 10:47:32,896] Trial 96 finished with value: 0.8515875862118234 and parameters: {'layer1': 381, 'layer2': 199, 'layer3': 48, 'activation': 'relu', 'solver': 'adam', 'lr': 9.570681827806677e-05}. Best is trial 95 with value: 0.8565269889658783.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:37:15<2:35:04, 4652.21s/it]

[I 2026-02-21 10:48:04,827] Trial 97 finished with value: 0.8542226072921306 and parameters: {'layer1': 325, 'layer2': 153, 'layer3': 151, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00011709704246557998}. Best is trial 95 with value: 0.8565269889658783.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:37:28<2:35:04, 4652.21s/it]

[I 2026-02-21 10:48:17,101] Trial 98 finished with value: 0.8184879496639109 and parameters: {'layer1': 402, 'layer2': 40, 'layer3': 13, 'activation': 'relu', 'solver': 'adam', 'lr': 4.8217394108559755e-05}. Best is trial 95 with value: 0.8565269889658783.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:37:44<2:35:04, 4652.21s/it]

[I 2026-02-21 10:48:33,828] Trial 99 finished with value: 0.8184879496639109 and parameters: {'layer1': 361, 'layer2': 126, 'layer3': 115, 'activation': 'relu', 'solver': 'adam', 'lr': 2.162880498687282e-06}. Best is trial 95 with value: 0.8565269889658783.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:38:21<2:35:04, 4652.21s/it]

[I 2026-02-21 10:49:10,067] Trial 100 finished with value: 0.8537530090621361 and parameters: {'layer1': 434, 'layer2': 211, 'layer3': 106, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00014397450187834444}. Best is trial 95 with value: 0.8565269889658783.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:38:50<2:35:04, 4652.21s/it]

[I 2026-02-21 10:49:39,521] Trial 101 finished with value: 0.8548411140921071 and parameters: {'layer1': 300, 'layer2': 147, 'layer3': 149, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00011825314685903648}. Best is trial 95 with value: 0.8565269889658783.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:39:09<2:35:04, 4652.21s/it]

[I 2026-02-21 10:49:58,367] Trial 102 finished with value: 0.8243657197805387 and parameters: {'layer1': 275, 'layer2': 106, 'layer3': 167, 'activation': 'relu', 'solver': 'adam', 'lr': 7.196668767610898e-05}. Best is trial 95 with value: 0.8565269889658783.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:39:20<2:35:04, 4652.21s/it]

[I 2026-02-21 10:50:09,427] Trial 103 finished with value: 0.8171622401256972 and parameters: {'layer1': 228, 'layer2': 184, 'layer3': 132, 'activation': 'relu', 'solver': 'adam', 'lr': 2.783575999846472e-05}. Best is trial 95 with value: 0.8565269889658783.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:39:40<2:35:04, 4652.21s/it]

[I 2026-02-21 10:50:29,065] Trial 104 finished with value: 0.8569273668956685 and parameters: {'layer1': 214, 'layer2': 158, 'layer3': 370, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00021723780770326634}. Best is trial 104 with value: 0.8569273668956685.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:40:01<2:35:04, 4652.21s/it]

[I 2026-02-21 10:50:50,061] Trial 105 finished with value: 0.8539404432792711 and parameters: {'layer1': 200, 'layer2': 270, 'layer3': 367, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00023363701881680892}. Best is trial 104 with value: 0.8569273668956685.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:40:21<2:35:04, 4652.21s/it]

[I 2026-02-21 10:51:10,744] Trial 106 finished with value: 0.8541842693766469 and parameters: {'layer1': 214, 'layer2': 87, 'layer3': 429, 'activation': 'relu', 'solver': 'adam', 'lr': 0.000271068650678776}. Best is trial 104 with value: 0.8569273668956685.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:40:37<2:35:04, 4652.21s/it]

[I 2026-02-21 10:51:26,721] Trial 107 finished with value: 0.8498615920529214 and parameters: {'layer1': 171, 'layer2': 156, 'layer3': 440, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0005728713784037435}. Best is trial 104 with value: 0.8569273668956685.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:40:56<2:35:04, 4652.21s/it]

[I 2026-02-21 10:51:45,661] Trial 108 finished with value: 0.8524457708658547 and parameters: {'layer1': 148, 'layer2': 118, 'layer3': 409, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00019880926698259918}. Best is trial 104 with value: 0.8569273668956685.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:41:09<2:35:04, 4652.21s/it]

[I 2026-02-21 10:51:58,805] Trial 109 finished with value: 0.8172913275180488 and parameters: {'layer1': 211, 'layer2': 163, 'layer3': 356, 'activation': 'relu', 'solver': 'sgd', 'lr': 0.00016150712478774592}. Best is trial 104 with value: 0.8569273668956685.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:41:44<2:35:04, 4652.21s/it]

[I 2026-02-21 10:52:33,160] Trial 110 finished with value: 0.8556545318892743 and parameters: {'layer1': 375, 'layer2': 172, 'layer3': 37, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00012683809807791755}. Best is trial 104 with value: 0.8569273668956685.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:42:13<2:35:04, 4652.21s/it]

[I 2026-02-21 10:53:02,789] Trial 111 finished with value: 0.8581537286490232 and parameters: {'layer1': 376, 'layer2': 173, 'layer3': 33, 'activation': 'relu', 'solver': 'adam', 'lr': 0.000124108282165148}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:42:44<2:35:04, 4652.21s/it]

[I 2026-02-21 10:53:33,020] Trial 112 finished with value: 0.8513476661074592 and parameters: {'layer1': 334, 'layer2': 195, 'layer3': 34, 'activation': 'relu', 'solver': 'adam', 'lr': 8.697425251869933e-05}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:43:17<2:35:04, 4652.21s/it]

[I 2026-02-21 10:54:06,069] Trial 113 finished with value: 0.8546437863562373 and parameters: {'layer1': 347, 'layer2': 172, 'layer3': 54, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0001008351521035848}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:43:48<2:35:04, 4652.21s/it]

[I 2026-02-21 10:54:37,630] Trial 114 finished with value: 0.8574062746218614 and parameters: {'layer1': 311, 'layer2': 174, 'layer3': 55, 'activation': 'relu', 'solver': 'adam', 'lr': 0.000101098357478912}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:44:23<2:35:04, 4652.21s/it]

[I 2026-02-21 10:55:11,984] Trial 115 finished with value: 0.8547843220872429 and parameters: {'layer1': 338, 'layer2': 176, 'layer3': 55, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00010846287978260913}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:44:47<2:35:04, 4652.21s/it]

[I 2026-02-21 10:55:36,240] Trial 116 finished with value: 0.8570531977099872 and parameters: {'layer1': 297, 'layer2': 172, 'layer3': 66, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00030348890130227644}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:45:10<2:35:04, 4652.21s/it]

[I 2026-02-21 10:55:59,219] Trial 117 finished with value: 0.8548151807808463 and parameters: {'layer1': 296, 'layer2': 215, 'layer3': 71, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0004266154451485773}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:45:32<2:35:04, 4652.21s/it]

[I 2026-02-21 10:56:21,770] Trial 118 finished with value: 0.850547705840669 and parameters: {'layer1': 297, 'layer2': 182, 'layer3': 86, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00038510823797261167}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:45:55<2:35:04, 4652.21s/it]

[I 2026-02-21 10:56:44,731] Trial 119 finished with value: 0.8539374593566482 and parameters: {'layer1': 309, 'layer2': 212, 'layer3': 67, 'activation': 'relu', 'solver': 'adam', 'lr': 0.000676100609269461}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:46:17<2:35:04, 4652.21s/it]

[I 2026-02-21 10:57:05,962] Trial 120 finished with value: 0.8529734572432659 and parameters: {'layer1': 317, 'layer2': 228, 'layer3': 67, 'activation': 'relu', 'solver': 'adam', 'lr': 0.001194845315123654}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:46:40<2:35:04, 4652.21s/it]

[I 2026-02-21 10:57:28,993] Trial 121 finished with value: 0.8532248532209226 and parameters: {'layer1': 287, 'layer2': 175, 'layer3': 77, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0003256006716108129}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:47:01<2:35:04, 4652.21s/it]

[I 2026-02-21 10:57:50,623] Trial 122 finished with value: 0.8558375377056191 and parameters: {'layer1': 266, 'layer2': 152, 'layer3': 45, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0002762302652411058}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:47:26<2:35:04, 4652.21s/it]

[I 2026-02-21 10:58:15,238] Trial 123 finished with value: 0.8553907178348817 and parameters: {'layer1': 271, 'layer2': 152, 'layer3': 43, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0002593637531142781}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:47:47<2:35:04, 4652.21s/it]

[I 2026-02-21 10:58:36,004] Trial 124 finished with value: 0.8528126240429053 and parameters: {'layer1': 261, 'layer2': 158, 'layer3': 16, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0004303391291946556}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:48:09<2:35:04, 4652.21s/it]

[I 2026-02-21 10:58:58,679] Trial 125 finished with value: 0.8533136730622308 and parameters: {'layer1': 262, 'layer2': 147, 'layer3': 43, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00028025910869347375}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:48:36<2:35:04, 4652.21s/it]

[I 2026-02-21 10:59:25,780] Trial 126 finished with value: 0.8544917963685922 and parameters: {'layer1': 237, 'layer2': 166, 'layer3': 90, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0002144167212655489}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:48:57<2:35:04, 4652.21s/it]

[I 2026-02-21 10:59:46,584] Trial 127 finished with value: 0.8556977816066681 and parameters: {'layer1': 274, 'layer2': 133, 'layer3': 40, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0005131626524683965}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:49:17<2:35:04, 4652.21s/it]

[I 2026-02-21 11:00:05,946] Trial 128 finished with value: 0.8536355646990929 and parameters: {'layer1': 276, 'layer2': 138, 'layer3': 25, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0007258310807352336}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:49:37<2:35:04, 4652.21s/it]

[I 2026-02-21 11:00:26,474] Trial 129 finished with value: 0.855975135000703 and parameters: {'layer1': 268, 'layer2': 151, 'layer3': 39, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0005394185897842292}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:49:57<2:35:04, 4652.21s/it]

[I 2026-02-21 11:00:46,533] Trial 130 finished with value: 0.851910425417576 and parameters: {'layer1': 269, 'layer2': 184, 'layer3': 41, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0005011745322606083}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:50:17<2:35:04, 4652.21s/it]

[I 2026-02-21 11:01:05,947] Trial 131 finished with value: 0.8515942188266064 and parameters: {'layer1': 240, 'layer2': 154, 'layer3': 50, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0005629425784493594}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:50:40<2:35:04, 4652.21s/it]

[I 2026-02-21 11:01:29,650] Trial 132 finished with value: 0.8554777007293936 and parameters: {'layer1': 306, 'layer2': 130, 'layer3': 37, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0002983353916970166}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:51:00<2:35:04, 4652.21s/it]

[I 2026-02-21 11:01:49,323] Trial 133 finished with value: 0.852078867231732 and parameters: {'layer1': 288, 'layer2': 130, 'layer3': 61, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0010873623716502576}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:51:22<2:35:04, 4652.21s/it]

[I 2026-02-21 11:02:11,695] Trial 134 finished with value: 0.8520914506323756 and parameters: {'layer1': 254, 'layer2': 138, 'layer3': 36, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00033329437665192556}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:51:46<2:35:04, 4652.21s/it]

[I 2026-02-21 11:02:35,818] Trial 135 finished with value: 0.8536184716523835 and parameters: {'layer1': 221, 'layer2': 170, 'layer3': 22, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0002660907251560122}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:51:58<2:35:04, 4652.21s/it]

[I 2026-02-21 11:02:47,352] Trial 136 finished with value: 0.8180313276792012 and parameters: {'layer1': 377, 'layer2': 153, 'layer3': 59, 'activation': 'relu', 'solver': 'sgd', 'lr': 0.000310634389043155}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:52:26<2:35:04, 4652.21s/it]

[I 2026-02-21 11:03:15,531] Trial 137 finished with value: 0.8540426887815714 and parameters: {'layer1': 367, 'layer2': 165, 'layer3': 82, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00019583108261451117}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:52:45<2:35:04, 4652.21s/it]

[I 2026-02-21 11:03:34,486] Trial 138 finished with value: 0.8497015406613337 and parameters: {'layer1': 272, 'layer2': 114, 'layer3': 20, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0007869694686022281}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:53:18<2:35:04, 4652.21s/it]

[I 2026-02-21 11:04:07,689] Trial 139 finished with value: 0.85782492235445 and parameters: {'layer1': 320, 'layer2': 142, 'layer3': 10, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00015240158528743777}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:53:49<2:35:04, 4652.21s/it]

[I 2026-02-21 11:04:38,643] Trial 140 finished with value: 0.8540127649900043 and parameters: {'layer1': 313, 'layer2': 197, 'layer3': 38, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00014907176818390876}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:54:20<2:35:04, 4652.21s/it]

[I 2026-02-21 11:05:09,658] Trial 141 finished with value: 0.8523474434309302 and parameters: {'layer1': 391, 'layer2': 143, 'layer3': 28, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00023548428802994852}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:54:39<2:35:04, 4652.21s/it]

[I 2026-02-21 11:05:28,774] Trial 142 finished with value: 0.8533124462946088 and parameters: {'layer1': 322, 'layer2': 129, 'layer3': 49, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0005845091178821464}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:55:08<2:35:04, 4652.21s/it]

[I 2026-02-21 11:05:56,887] Trial 143 finished with value: 0.8572060068360724 and parameters: {'layer1': 307, 'layer2': 155, 'layer3': 13, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00016942655184971995}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:55:35<2:35:04, 4652.21s/it]

[I 2026-02-21 11:06:24,668] Trial 144 finished with value: 0.8536802291164414 and parameters: {'layer1': 309, 'layer2': 160, 'layer3': 14, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00018409809770763595}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:56:05<2:35:04, 4652.21s/it]

[I 2026-02-21 11:06:54,500] Trial 145 finished with value: 0.8532975501314054 and parameters: {'layer1': 292, 'layer2': 185, 'layer3': 11, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0001436123914093749}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:56:25<2:35:04, 4652.21s/it]

[I 2026-02-21 11:07:14,812] Trial 146 finished with value: 0.8518831174920539 and parameters: {'layer1': 281, 'layer2': 387, 'layer3': 40, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00040054786391107144}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:56:49<2:35:04, 4652.21s/it]

[I 2026-02-21 11:07:38,332] Trial 147 finished with value: 0.8554294527743652 and parameters: {'layer1': 305, 'layer2': 147, 'layer3': 26, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00025305424654528495}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:57:18<2:35:04, 4652.21s/it]

[I 2026-02-21 11:08:07,199] Trial 148 finished with value: 0.8575840489843098 and parameters: {'layer1': 343, 'layer2': 142, 'layer3': 26, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00020747500665824152}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:57:45<2:35:04, 4652.21s/it]

[I 2026-02-21 11:08:34,412] Trial 149 finished with value: 0.8536541588484887 and parameters: {'layer1': 331, 'layer2': 124, 'layer3': 19, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00017847025060978517}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:58:12<2:35:04, 4652.21s/it]

[I 2026-02-21 11:09:01,036] Trial 150 finished with value: 0.8528362516302943 and parameters: {'layer1': 362, 'layer2': 140, 'layer3': 54, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.00013227511849216815}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:58:42<2:35:04, 4652.21s/it]

[I 2026-02-21 11:09:30,910] Trial 151 finished with value: 0.8528004829907667 and parameters: {'layer1': 344, 'layer2': 168, 'layer3': 28, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00021479980345359313}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:59:03<2:35:04, 4652.21s/it]

[I 2026-02-21 11:09:52,595] Trial 152 finished with value: 0.8550563384516476 and parameters: {'layer1': 307, 'layer2': 149, 'layer3': 31, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0003026093320208788}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [23:59:35<2:35:04, 4652.21s/it]

[I 2026-02-21 11:10:23,981] Trial 153 finished with value: 0.8520435728876846 and parameters: {'layer1': 327, 'layer2': 177, 'layer3': 10, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00015523983248917782}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [24:00:04<2:35:04, 4652.21s/it]

[I 2026-02-21 11:10:53,516] Trial 154 finished with value: 0.8527070029358296 and parameters: {'layer1': 356, 'layer2': 133, 'layer3': 23, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00022623284802894073}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [24:00:34<2:35:04, 4652.21s/it]

[I 2026-02-21 11:11:23,273] Trial 155 finished with value: 0.8569290593374479 and parameters: {'layer1': 302, 'layer2': 104, 'layer3': 64, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00016528784962880654}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [24:00:46<2:35:04, 4652.21s/it]

[I 2026-02-21 11:11:35,381] Trial 156 finished with value: 0.8171622401256972 and parameters: {'layer1': 320, 'layer2': 101, 'layer3': 64, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.00016736576918904681}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [24:01:14<2:35:04, 4652.21s/it]

[I 2026-02-21 11:12:03,216] Trial 157 finished with value: 0.8560795530241109 and parameters: {'layer1': 244, 'layer2': 119, 'layer3': 48, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00012689838179301904}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [24:01:42<2:35:04, 4652.21s/it]

[I 2026-02-21 11:12:31,589] Trial 158 finished with value: 0.8553764856425066 and parameters: {'layer1': 239, 'layer2': 110, 'layer3': 77, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00012886676217922213}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [24:02:00<2:35:04, 4652.21s/it]

[I 2026-02-21 11:12:49,802] Trial 159 finished with value: 0.8252931715262927 and parameters: {'layer1': 248, 'layer2': 117, 'layer3': 49, 'activation': 'relu', 'solver': 'adam', 'lr': 9.077207811181688e-05}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [24:02:21<2:35:04, 4652.21s/it]

[I 2026-02-21 11:13:10,346] Trial 160 finished with value: 0.6645567016326087 and parameters: {'layer1': 260, 'layer2': 158, 'layer3': 68, 'activation': 'relu', 'solver': 'sgd', 'lr': 0.00010729579050208715}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [24:02:53<2:35:04, 4652.21s/it]

[I 2026-02-21 11:13:42,024] Trial 161 finished with value: 0.8547612901252408 and parameters: {'layer1': 295, 'layer2': 131, 'layer3': 38, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00019086552176117918}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [24:03:23<2:35:04, 4652.21s/it]

[I 2026-02-21 11:14:12,455] Trial 162 finished with value: 0.8560778334601722 and parameters: {'layer1': 338, 'layer2': 121, 'layer3': 54, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0001504942150012804}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [24:03:52<2:35:04, 4652.21s/it]

[I 2026-02-21 11:14:41,608] Trial 163 finished with value: 0.8558214930114254 and parameters: {'layer1': 343, 'layer2': 97, 'layer3': 56, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00012666838087536285}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [24:04:23<2:35:04, 4652.21s/it]

[I 2026-02-21 11:15:12,236] Trial 164 finished with value: 0.8560371383580524 and parameters: {'layer1': 338, 'layer2': 93, 'layer3': 60, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0001531433119669678}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [24:04:52<2:35:04, 4652.21s/it]

[I 2026-02-21 11:15:41,632] Trial 165 finished with value: 0.8535104211161253 and parameters: {'layer1': 341, 'layer2': 103, 'layer3': 58, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0001550117268329185}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [24:05:21<2:35:04, 4652.21s/it]

[I 2026-02-21 11:16:10,045] Trial 166 finished with value: 0.855472157986392 and parameters: {'layer1': 349, 'layer2': 93, 'layer3': 73, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00016667805220887052}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [24:05:56<2:35:04, 4652.21s/it]

[I 2026-02-21 11:16:45,458] Trial 167 finished with value: 0.8578278213632184 and parameters: {'layer1': 331, 'layer2': 88, 'layer3': 48, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00012263464551194795}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [24:06:21<2:35:04, 4652.21s/it]

[I 2026-02-21 11:17:10,364] Trial 168 finished with value: 0.83343585290052 and parameters: {'layer1': 335, 'layer2': 67, 'layer3': 52, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00011109623812097848}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [24:06:49<2:35:04, 4652.21s/it]

[I 2026-02-21 11:17:38,220] Trial 169 finished with value: 0.8533643018215594 and parameters: {'layer1': 318, 'layer2': 78, 'layer3': 470, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00013437963407255228}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [24:07:21<2:35:04, 4652.21s/it]

[I 2026-02-21 11:18:10,308] Trial 170 finished with value: 0.8528261630240811 and parameters: {'layer1': 353, 'layer2': 88, 'layer3': 105, 'activation': 'relu', 'solver': 'adam', 'lr': 9.107240244015616e-05}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [24:07:48<2:35:04, 4652.21s/it]

[I 2026-02-21 11:18:37,442] Trial 171 finished with value: 0.8563984312386511 and parameters: {'layer1': 331, 'layer2': 99, 'layer3': 60, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00019130595506112487}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [24:08:14<2:35:04, 4652.21s/it]

[I 2026-02-21 11:19:03,816] Trial 172 finished with value: 0.8562725628027043 and parameters: {'layer1': 333, 'layer2': 106, 'layer3': 62, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00020128614887569957}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [24:08:42<2:35:04, 4652.21s/it]

[I 2026-02-21 11:19:31,772] Trial 173 finished with value: 0.8548944775287548 and parameters: {'layer1': 327, 'layer2': 109, 'layer3': 82, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00020065836560083855}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [24:09:13<2:35:04, 4652.21s/it]

[I 2026-02-21 11:20:02,166] Trial 174 finished with value: 0.8577799068448005 and parameters: {'layer1': 334, 'layer2': 75, 'layer3': 96, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00016522521383886994}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [24:09:39<2:35:04, 4652.21s/it]

[I 2026-02-21 11:20:28,189] Trial 175 finished with value: 0.8545785497603162 and parameters: {'layer1': 334, 'layer2': 55, 'layer3': 91, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0001676510654051975}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [24:10:07<2:35:04, 4652.21s/it]

[I 2026-02-21 11:20:56,188] Trial 176 finished with value: 0.8541084205386879 and parameters: {'layer1': 318, 'layer2': 74, 'layer3': 67, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00020007734785159692}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [24:10:40<2:35:04, 4652.21s/it]

[I 2026-02-21 11:21:29,791] Trial 177 finished with value: 0.8548671222901734 and parameters: {'layer1': 356, 'layer2': 91, 'layer3': 63, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00015636419864028403}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [24:11:15<2:35:04, 4652.21s/it]

[I 2026-02-21 11:22:04,216] Trial 178 finished with value: 0.8545521503973962 and parameters: {'layer1': 330, 'layer2': 103, 'layer3': 78, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00010531723148562975}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [24:11:39<2:35:04, 4652.21s/it]

[I 2026-02-21 11:22:28,798] Trial 179 finished with value: 0.8550861442042347 and parameters: {'layer1': 343, 'layer2': 119, 'layer3': 100, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00022936466895240028}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [24:12:12<2:35:04, 4652.21s/it]

[I 2026-02-21 11:23:01,648] Trial 180 finished with value: 0.8564352583253759 and parameters: {'layer1': 367, 'layer2': 61, 'layer3': 48, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00013899598543449444}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [24:12:42<2:35:04, 4652.21s/it]

[I 2026-02-21 11:23:31,002] Trial 181 finished with value: 0.8411504853027238 and parameters: {'layer1': 369, 'layer2': 44, 'layer3': 54, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00011709048910659662}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [24:13:16<2:35:04, 4652.21s/it]

[I 2026-02-21 11:24:04,870] Trial 182 finished with value: 0.8562946933260432 and parameters: {'layer1': 386, 'layer2': 79, 'layer3': 67, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00015424800822615923}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [24:13:49<2:35:04, 4652.21s/it]

[I 2026-02-21 11:24:38,490] Trial 183 finished with value: 0.8558493381868718 and parameters: {'layer1': 388, 'layer2': 61, 'layer3': 74, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00015235703157964894}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [24:14:17<2:35:04, 4652.21s/it]

[I 2026-02-21 11:25:06,189] Trial 184 finished with value: 0.8511598617337655 and parameters: {'layer1': 397, 'layer2': 82, 'layer3': 65, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0001340257221088582}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [24:14:48<2:35:04, 4652.21s/it]

[I 2026-02-21 11:25:37,536] Trial 185 finished with value: 0.8561234532978756 and parameters: {'layer1': 382, 'layer2': 47, 'layer3': 87, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00019058939689454724}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [24:15:17<2:35:04, 4652.21s/it]

[I 2026-02-21 11:26:06,536] Trial 186 finished with value: 0.8503554555174743 and parameters: {'layer1': 381, 'layer2': 20, 'layer3': 86, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00019582951498720103}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [24:15:29<2:35:04, 4652.21s/it]

[I 2026-02-21 11:26:18,555] Trial 187 finished with value: 0.8171622401256972 and parameters: {'layer1': 370, 'layer2': 48, 'layer3': 96, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0002257976381162159}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [24:15:48<2:35:04, 4652.21s/it]

[I 2026-02-21 11:26:37,685] Trial 188 finished with value: 0.8247668870039855 and parameters: {'layer1': 360, 'layer2': 22, 'layer3': 89, 'activation': 'relu', 'solver': 'adam', 'lr': 9.665446282597527e-05}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [24:16:06<2:35:04, 4652.21s/it]

[I 2026-02-21 11:26:55,826] Trial 189 finished with value: 0.852258588351184 and parameters: {'layer1': 382, 'layer2': 54, 'layer3': 46, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0032488205064488654}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [24:16:34<2:35:04, 4652.21s/it]

[I 2026-02-21 11:27:22,905] Trial 190 finished with value: 0.8534653591296338 and parameters: {'layer1': 313, 'layer2': 67, 'layer3': 115, 'activation': 'relu', 'solver': 'adam', 'lr': 0.000180217623851583}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [24:17:02<2:35:04, 4652.21s/it]

[I 2026-02-21 11:27:51,773] Trial 191 finished with value: 0.8539908623916654 and parameters: {'layer1': 350, 'layer2': 82, 'layer3': 61, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00014361438886660238}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [24:17:29<2:35:04, 4652.21s/it]

[I 2026-02-21 11:28:18,177] Trial 192 finished with value: 0.8410228711831916 and parameters: {'layer1': 339, 'layer2': 31, 'layer3': 77, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00011417331452202071}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [24:17:59<2:35:04, 4652.21s/it]

[I 2026-02-21 11:28:48,480] Trial 193 finished with value: 0.8551174495078214 and parameters: {'layer1': 322, 'layer2': 74, 'layer3': 51, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0001663214457043976}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [24:18:29<2:35:04, 4652.21s/it]

[I 2026-02-21 11:29:18,260] Trial 194 finished with value: 0.8536511361482171 and parameters: {'layer1': 409, 'layer2': 95, 'layer3': 66, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0002483438638573885}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [24:18:59<2:35:04, 4652.21s/it]

[I 2026-02-21 11:29:48,097] Trial 195 finished with value: 0.8503307769722518 and parameters: {'layer1': 374, 'layer2': 87, 'layer3': 22, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0001444243813793546}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [24:19:14<2:35:04, 4652.21s/it]

[I 2026-02-21 11:30:02,919] Trial 196 finished with value: 0.8171622401256972 and parameters: {'layer1': 331, 'layer2': 111, 'layer3': 71, 'activation': 'relu', 'solver': 'sgd', 'lr': 0.0002124183454812209}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [24:19:51<2:35:04, 4652.21s/it]

[I 2026-02-21 11:30:40,269] Trial 197 finished with value: 0.8545155657043608 and parameters: {'layer1': 363, 'layer2': 71, 'layer3': 31, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00012579491141226484}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  86%|████████▌ | 12/14 [24:20:12<2:35:04, 4652.21s/it]

[I 2026-02-21 11:31:01,338] Trial 198 finished with value: 0.8266159417535139 and parameters: {'layer1': 300, 'layer2': 100, 'layer3': 49, 'activation': 'relu', 'solver': 'adam', 'lr': 8.106589301811021e-05}. Best is trial 111 with value: 0.8581537286490232.

Best trial: 111. Best value: 0.858154: 100%|██████████| 200/200 [1:18:47<00:00, 23.64s/it]

[I 2026-02-21 11:31:32,057] Trial 199 finished with value: 0.8537444934756111 and parameters: {'layer1': 350, 'layer2': 119, 'layer3': 59, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0001804000002073632}. Best is trial 111 with value: 0.8581537286490232.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:20:44<1:17:55, 4675.27s/it][I 2026-02-21 11:31:32,914] A new study created in memory with name: no-name-80f85212-bbfa-4112-8d5b-d8fcd4ae2b6f

  → Best model saved.

[Exact Paper MLP] Pseudomonas_Aeruginosa | Meropenem

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:20:57<1:17:55, 4675.27s/it]

[I 2026-02-21 11:31:46,357] Trial 0 finished with value: 0.8740472889214308 and parameters: {'layer1': 81, 'layer2': 136, 'layer3': 202, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0005279127353110463}. Best is trial 0 with value: 0.8740472889214308.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:21:06<1:17:55, 4675.27s/it]

[I 2026-02-21 11:31:55,020] Trial 1 finished with value: 0.8458290816039972 and parameters: {'layer1': 311, 'layer2': 125, 'layer3': 127, 'activation': 'relu', 'solver': 'sgd', 'lr': 0.007233666924236216}. Best is trial 0 with value: 0.8740472889214308.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:21:16<1:17:55, 4675.27s/it]

[I 2026-02-21 11:32:05,290] Trial 2 finished with value: 0.6808332587134375 and parameters: {'layer1': 382, 'layer2': 71, 'layer3': 418, 'activation': 'logistic', 'solver': 'sgd', 'lr': 2.833203100520006e-05}. Best is trial 0 with value: 0.8740472889214308.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:21:24<1:17:55, 4675.27s/it]

[I 2026-02-21 11:32:13,446] Trial 3 finished with value: 0.8458290816039972 and parameters: {'layer1': 319, 'layer2': 379, 'layer3': 17, 'activation': 'relu', 'solver': 'sgd', 'lr': 4.494834854290793e-05}. Best is trial 0 with value: 0.8740472889214308.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:21:34<1:17:55, 4675.27s/it]

[I 2026-02-21 11:32:23,218] Trial 4 finished with value: 0.8458290816039972 and parameters: {'layer1': 308, 'layer2': 207, 'layer3': 457, 'activation': 'identity', 'solver': 'sgd', 'lr': 0.000158889095519953}. Best is trial 0 with value: 0.8740472889214308.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:21:41<1:17:55, 4675.27s/it]

[I 2026-02-21 11:32:30,350] Trial 5 finished with value: 0.8458290816039972 and parameters: {'layer1': 116, 'layer2': 439, 'layer3': 204, 'activation': 'identity', 'solver': 'sgd', 'lr': 0.0007456101725501141}. Best is trial 0 with value: 0.8740472889214308.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:21:49<1:17:55, 4675.27s/it]

[I 2026-02-21 11:32:38,195] Trial 6 finished with value: 0.8458290816039972 and parameters: {'layer1': 229, 'layer2': 143, 'layer3': 392, 'activation': 'logistic', 'solver': 'sgd', 'lr': 0.0021961878239856055}. Best is trial 0 with value: 0.8740472889214308.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:22:00<1:17:55, 4675.27s/it]

[I 2026-02-21 11:32:49,151] Trial 7 finished with value: 0.8458290816039972 and parameters: {'layer1': 488, 'layer2': 372, 'layer3': 444, 'activation': 'logistic', 'solver': 'sgd', 'lr': 4.692110423824911e-05}. Best is trial 0 with value: 0.8740472889214308.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:22:07<1:17:55, 4675.27s/it]

[I 2026-02-21 11:32:56,649] Trial 8 finished with value: 0.8458290816039972 and parameters: {'layer1': 20, 'layer2': 335, 'layer3': 362, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.006628475124034262}. Best is trial 0 with value: 0.8740472889214308.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:22:16<1:17:55, 4675.27s/it]

[I 2026-02-21 11:33:05,677] Trial 9 finished with value: 0.6808332587134375 and parameters: {'layer1': 284, 'layer2': 489, 'layer3': 139, 'activation': 'relu', 'solver': 'sgd', 'lr': 5.962691214491084e-06}. Best is trial 0 with value: 0.8740472889214308.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:22:26<1:17:55, 4675.27s/it]

[I 2026-02-21 11:33:15,052] Trial 10 finished with value: 0.8458290816039972 and parameters: {'layer1': 149, 'layer2': 34, 'layer3': 276, 'activation': 'tanh', 'solver': 'adam', 'lr': 1.8189629170922878e-06}. Best is trial 0 with value: 0.8740472889214308.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:22:39<1:17:55, 4675.27s/it]

[I 2026-02-21 11:33:28,653] Trial 11 finished with value: 0.874804966260365 and parameters: {'layer1': 38, 'layer2': 156, 'layer3': 90, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0005247209686443054}. Best is trial 11 with value: 0.874804966260365.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:22:52<1:17:55, 4675.27s/it]

[I 2026-02-21 11:33:41,102] Trial 12 finished with value: 0.8698259615003984 and parameters: {'layer1': 31, 'layer2': 244, 'layer3': 20, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0003286984953171821}. Best is trial 11 with value: 0.874804966260365.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:23:05<1:17:55, 4675.27s/it]

[I 2026-02-21 11:33:53,861] Trial 13 finished with value: 0.8696978295970572 and parameters: {'layer1': 114, 'layer2': 163, 'layer3': 103, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0008529005549067598}. Best is trial 11 with value: 0.874804966260365.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:23:24<1:17:55, 4675.27s/it]

[I 2026-02-21 11:34:13,155] Trial 14 finished with value: 0.8739048763165955 and parameters: {'layer1': 188, 'layer2': 296, 'layer3': 274, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0014980250822374298}. Best is trial 11 with value: 0.874804966260365.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:23:38<1:17:55, 4675.27s/it]

[I 2026-02-21 11:34:27,567] Trial 15 finished with value: 0.8719931901596396 and parameters: {'layer1': 81, 'layer2': 96, 'layer3': 203, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00027844085859127997}. Best is trial 11 with value: 0.874804966260365.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:23:47<1:17:55, 4675.27s/it]

[I 2026-02-21 11:34:36,176] Trial 16 finished with value: 0.8471561500729321 and parameters: {'layer1': 71, 'layer2': 201, 'layer3': 82, 'activation': 'relu', 'solver': 'adam', 'lr': 1.0248817567200711e-05}. Best is trial 11 with value: 0.874804966260365.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:24:03<1:17:55, 4675.27s/it]

[I 2026-02-21 11:34:51,918] Trial 17 finished with value: 0.854676875379694 and parameters: {'layer1': 187, 'layer2': 17, 'layer3': 200, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.002857628584265249}. Best is trial 11 with value: 0.874804966260365.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:24:20<1:17:55, 4675.27s/it]

[I 2026-02-21 11:35:09,425] Trial 18 finished with value: 0.872308992908678 and parameters: {'layer1': 49, 'layer2': 275, 'layer3': 340, 'activation': 'identity', 'solver': 'adam', 'lr': 0.00011734312690577226}. Best is trial 11 with value: 0.874804966260365.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:24:32<1:17:55, 4675.27s/it]

[I 2026-02-21 11:35:21,075] Trial 19 finished with value: 0.8562864956218839 and parameters: {'layer1': 13, 'layer2': 214, 'layer3': 73, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00032001951941821205}. Best is trial 11 with value: 0.874804966260365.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:24:46<1:17:55, 4675.27s/it]

[I 2026-02-21 11:35:35,247] Trial 20 finished with value: 0.8758138815869092 and parameters: {'layer1': 159, 'layer2': 78, 'layer3': 164, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0008111521736932722}. Best is trial 20 with value: 0.8758138815869092.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:25:01<1:17:55, 4675.27s/it]

[I 2026-02-21 11:35:50,106] Trial 21 finished with value: 0.8703744621376066 and parameters: {'layer1': 132, 'layer2': 72, 'layer3': 163, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0005809109982806341}. Best is trial 20 with value: 0.8758138815869092.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:25:16<1:17:55, 4675.27s/it]

[I 2026-02-21 11:36:05,760] Trial 22 finished with value: 0.8687226270073545 and parameters: {'layer1': 177, 'layer2': 162, 'layer3': 254, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0013818706127066273}. Best is trial 20 with value: 0.8758138815869092.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:25:31<1:17:55, 4675.27s/it]

[I 2026-02-21 11:36:20,764] Trial 23 finished with value: 0.8705825330450118 and parameters: {'layer1': 80, 'layer2': 114, 'layer3': 160, 'activation': 'relu', 'solver': 'adam', 'lr': 0.003142482767295924}. Best is trial 20 with value: 0.8758138815869092.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:25:49<1:17:55, 4675.27s/it]

[I 2026-02-21 11:36:38,540] Trial 24 finished with value: 0.8696462246172032 and parameters: {'layer1': 232, 'layer2': 61, 'layer3': 61, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00021243824110504127}. Best is trial 20 with value: 0.8758138815869092.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:26:04<1:17:55, 4675.27s/it]

[I 2026-02-21 11:36:53,486] Trial 25 finished with value: 0.8748821261367012 and parameters: {'layer1': 100, 'layer2': 175, 'layer3': 498, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0005758021953210715}. Best is trial 20 with value: 0.8758138815869092.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:26:21<1:17:55, 4675.27s/it]

[I 2026-02-21 11:37:10,762] Trial 26 finished with value: 0.8720107083839149 and parameters: {'layer1': 148, 'layer2': 184, 'layer3': 309, 'activation': 'tanh', 'solver': 'adam', 'lr': 9.586970850827127e-05}. Best is trial 20 with value: 0.8758138815869092.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:26:33<1:17:55, 4675.27s/it]

[I 2026-02-21 11:37:22,817] Trial 27 finished with value: 0.8720010905363906 and parameters: {'layer1': 107, 'layer2': 239, 'layer3': 490, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0011356326988945314}. Best is trial 20 with value: 0.8758138815869092.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:26:44<1:17:55, 4675.27s/it]

[I 2026-02-21 11:37:33,127] Trial 28 finished with value: 0.8458290816039972 and parameters: {'layer1': 219, 'layer2': 79, 'layer3': 242, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.00448034407117912}. Best is trial 20 with value: 0.8758138815869092.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:26:58<1:17:55, 4675.27s/it]

[I 2026-02-21 11:37:47,014] Trial 29 finished with value: 0.8693212637530774 and parameters: {'layer1': 48, 'layer2': 142, 'layer3': 117, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0004626856213721735}. Best is trial 20 with value: 0.8758138815869092.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:27:06<1:17:55, 4675.27s/it]

[I 2026-02-21 11:37:55,410] Trial 30 finished with value: 0.8458290816039972 and parameters: {'layer1': 166, 'layer2': 37, 'layer3': 45, 'activation': 'relu', 'solver': 'adam', 'lr': 7.029900341164011e-05}. Best is trial 20 with value: 0.8758138815869092.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:27:21<1:17:55, 4675.27s/it]

[I 2026-02-21 11:38:09,937] Trial 31 finished with value: 0.8735283821418847 and parameters: {'layer1': 86, 'layer2': 119, 'layer3': 189, 'activation': 'relu', 'solver': 'adam', 'lr': 0.009764742706260326}. Best is trial 20 with value: 0.8758138815869092.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:27:33<1:17:55, 4675.27s/it]

[I 2026-02-21 11:38:22,532] Trial 32 finished with value: 0.8698855806640008 and parameters: {'layer1': 56, 'layer2': 172, 'layer3': 228, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0006813623557350411}. Best is trial 20 with value: 0.8758138815869092.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:27:55<1:17:55, 4675.27s/it]

[I 2026-02-21 11:38:44,577] Trial 33 finished with value: 0.8680134649618273 and parameters: {'layer1': 381, 'layer2': 108, 'layer3': 146, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0018182732342230403}. Best is trial 20 with value: 0.8758138815869092.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:28:15<1:17:55, 4675.27s/it]

[I 2026-02-21 11:39:03,919] Trial 34 finished with value: 0.8711352670208212 and parameters: {'layer1': 90, 'layer2': 139, 'layer3': 175, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0001735954384613239}. Best is trial 20 with value: 0.8758138815869092.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:28:22<1:17:55, 4675.27s/it]

[I 2026-02-21 11:39:11,832] Trial 35 finished with value: 0.8458290816039972 and parameters: {'layer1': 130, 'layer2': 221, 'layer3': 99, 'activation': 'logistic', 'solver': 'sgd', 'lr': 0.00044372224217846914}. Best is trial 20 with value: 0.8758138815869092.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:28:35<1:17:55, 4675.27s/it]

[I 2026-02-21 11:39:24,478] Trial 36 finished with value: 0.8689440401774009 and parameters: {'layer1': 51, 'layer2': 90, 'layer3': 307, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0011803125997858386}. Best is trial 20 with value: 0.8758138815869092.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:28:52<1:17:55, 4675.27s/it]

[I 2026-02-21 11:39:41,833] Trial 37 finished with value: 0.6839445958903483 and parameters: {'layer1': 105, 'layer2': 189, 'layer3': 223, 'activation': 'relu', 'solver': 'sgd', 'lr': 2.501586577311116e-05}. Best is trial 20 with value: 0.8758138815869092.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:29:09<1:17:55, 4675.27s/it]

[I 2026-02-21 11:39:58,265] Trial 38 finished with value: 0.8733140467148901 and parameters: {'layer1': 259, 'layer2': 60, 'layer3': 394, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0007670566610332588}. Best is trial 20 with value: 0.8758138815869092.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:29:17<1:17:55, 4675.27s/it]

[I 2026-02-21 11:40:06,743] Trial 39 finished with value: 0.8458290816039972 and parameters: {'layer1': 209, 'layer2': 270, 'layer3': 126, 'activation': 'logistic', 'solver': 'sgd', 'lr': 0.005463758310946288}. Best is trial 20 with value: 0.8758138815869092.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:29:37<1:17:55, 4675.27s/it]

[I 2026-02-21 11:40:26,639] Trial 40 finished with value: 0.8737258500698026 and parameters: {'layer1': 339, 'layer2': 136, 'layer3': 433, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0001346866216287303}. Best is trial 20 with value: 0.8758138815869092.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:29:52<1:17:55, 4675.27s/it]

[I 2026-02-21 11:40:41,335] Trial 41 finished with value: 0.8757860234077108 and parameters: {'layer1': 184, 'layer2': 327, 'layer3': 497, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0015271886365414854}. Best is trial 20 with value: 0.8758138815869092.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:30:06<1:17:55, 4675.27s/it]

[I 2026-02-21 11:40:55,245] Trial 42 finished with value: 0.8690449018747998 and parameters: {'layer1': 159, 'layer2': 340, 'layer3': 482, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0036595356918741047}. Best is trial 20 with value: 0.8758138815869092.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:30:36<1:17:55, 4675.27s/it]

[I 2026-02-21 11:41:25,108] Trial 43 finished with value: 0.8730537762826183 and parameters: {'layer1': 494, 'layer2': 409, 'layer3': 476, 'activation': 'relu', 'solver': 'adam', 'lr': 0.002161484044428682}. Best is trial 20 with value: 0.8758138815869092.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:30:55<1:17:55, 4675.27s/it]

[I 2026-02-21 11:41:44,716] Trial 44 finished with value: 0.8692943716200372 and parameters: {'layer1': 132, 'layer2': 313, 'layer3': 453, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0004295989142295138}. Best is trial 20 with value: 0.8758138815869092.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:31:08<1:17:55, 4675.27s/it]

[I 2026-02-21 11:41:57,435] Trial 45 finished with value: 0.8726699486242826 and parameters: {'layer1': 28, 'layer2': 340, 'layer3': 403, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0009036495418488677}. Best is trial 20 with value: 0.8758138815869092.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:31:21<1:17:55, 4675.27s/it]

[I 2026-02-21 11:42:10,310] Trial 46 finished with value: 0.8468046618643477 and parameters: {'layer1': 199, 'layer2': 483, 'layer3': 361, 'activation': 'relu', 'solver': 'sgd', 'lr': 0.00023142238163585994}. Best is trial 20 with value: 0.8758138815869092.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:31:33<1:17:55, 4675.27s/it]

[I 2026-02-21 11:42:21,909] Trial 47 finished with value: 0.8691952300844484 and parameters: {'layer1': 105, 'layer2': 156, 'layer3': 498, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0005966553493407654}. Best is trial 20 with value: 0.8758138815869092.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:31:52<1:17:55, 4675.27s/it]

[I 2026-02-21 11:42:41,578] Trial 48 finished with value: 0.8714575247692883 and parameters: {'layer1': 263, 'layer2': 241, 'layer3': 438, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0023609020354300554}. Best is trial 20 with value: 0.8758138815869092.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:32:00<1:17:55, 4675.27s/it]

[I 2026-02-21 11:42:48,916] Trial 49 finished with value: 0.8458290816039972 and parameters: {'layer1': 67, 'layer2': 366, 'layer3': 30, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0010710607338969907}. Best is trial 20 with value: 0.8758138815869092.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:32:26<1:17:55, 4675.27s/it]

[I 2026-02-21 11:43:15,095] Trial 50 finished with value: 0.5115508038461007 and parameters: {'layer1': 146, 'layer2': 47, 'layer3': 96, 'activation': 'tanh', 'solver': 'sgd', 'lr': 1.2108051169907425e-06}. Best is trial 20 with value: 0.8758138815869092.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:32:42<1:17:55, 4675.27s/it]

[I 2026-02-21 11:43:31,233] Trial 51 finished with value: 0.872348304808557 and parameters: {'layer1': 193, 'layer2': 300, 'layer3': 290, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0016952865944324786}. Best is trial 20 with value: 0.8758138815869092.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:32:59<1:17:55, 4675.27s/it]

[I 2026-02-21 11:43:48,001] Trial 52 finished with value: 0.8709424969888664 and parameters: {'layer1': 178, 'layer2': 288, 'layer3': 222, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0003450751590610251}. Best is trial 20 with value: 0.8758138815869092.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:33:17<1:17:55, 4675.27s/it]

[I 2026-02-21 11:44:06,052] Trial 53 finished with value: 0.8744976487367181 and parameters: {'layer1': 232, 'layer2': 319, 'layer3': 270, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00149763001448464}. Best is trial 20 with value: 0.8758138815869092.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:33:35<1:17:55, 4675.27s/it]

[I 2026-02-21 11:44:23,980] Trial 54 finished with value: 0.8725582146574897 and parameters: {'layer1': 291, 'layer2': 317, 'layer3': 414, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0005857322023039695}. Best is trial 20 with value: 0.8758138815869092.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:33:59<1:17:55, 4675.27s/it]

[I 2026-02-21 11:44:48,106] Trial 55 finished with value: 0.871729400515953 and parameters: {'layer1': 446, 'layer2': 404, 'layer3': 469, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0015156041137960525}. Best is trial 20 with value: 0.8758138815869092.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:34:18<1:17:55, 4675.27s/it]

[I 2026-02-21 11:45:07,692] Trial 56 finished with value: 0.8685265144913658 and parameters: {'layer1': 237, 'layer2': 263, 'layer3': 182, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0008963261284022884}. Best is trial 20 with value: 0.8758138815869092.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:34:29<1:17:55, 4675.27s/it]

[I 2026-02-21 11:45:18,317] Trial 57 finished with value: 0.8719946762490636 and parameters: {'layer1': 14, 'layer2': 102, 'layer3': 372, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0033471833895893947}. Best is trial 20 with value: 0.8758138815869092.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:34:45<1:17:55, 4675.27s/it]

[I 2026-02-21 11:45:34,625] Trial 58 finished with value: 0.8735503478600848 and parameters: {'layer1': 121, 'layer2': 361, 'layer3': 145, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0002603090110536338}. Best is trial 20 with value: 0.8758138815869092.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:35:02<1:17:55, 4675.27s/it]

[I 2026-02-21 11:45:51,698] Trial 59 finished with value: 0.8741106674285503 and parameters: {'layer1': 162, 'layer2': 221, 'layer3': 273, 'activation': 'identity', 'solver': 'adam', 'lr': 8.750208279314889e-05}. Best is trial 20 with value: 0.8758138815869092.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:35:14<1:17:55, 4675.27s/it]

[I 2026-02-21 11:46:03,271] Trial 60 finished with value: 0.8458290816039972 and parameters: {'layer1': 242, 'layer2': 222, 'layer3': 334, 'activation': 'identity', 'solver': 'adam', 'lr': 3.074234938016869e-05}. Best is trial 20 with value: 0.8758138815869092.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:35:35<1:17:55, 4675.27s/it]

[I 2026-02-21 11:46:24,087] Trial 61 finished with value: 0.8701615074870658 and parameters: {'layer1': 173, 'layer2': 200, 'layer3': 275, 'activation': 'identity', 'solver': 'adam', 'lr': 7.739048087159831e-05}. Best is trial 20 with value: 0.8758138815869092.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:35:55<1:17:55, 4675.27s/it]

[I 2026-02-21 11:46:44,227] Trial 62 finished with value: 0.8680374270203808 and parameters: {'layer1': 210, 'layer2': 180, 'layer3': 237, 'activation': 'identity', 'solver': 'adam', 'lr': 5.665067394145205e-05}. Best is trial 20 with value: 0.8758138815869092.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:36:09<1:17:55, 4675.27s/it]

[I 2026-02-21 11:46:58,284] Trial 63 finished with value: 0.8747497173379013 and parameters: {'layer1': 154, 'layer2': 162, 'layer3': 257, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0003614152011455924}. Best is trial 20 with value: 0.8758138815869092.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:36:25<1:17:55, 4675.27s/it]

[I 2026-02-21 11:47:13,992] Trial 64 finished with value: 0.8720111571136103 and parameters: {'layer1': 154, 'layer2': 156, 'layer3': 261, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0001693283834548521}. Best is trial 20 with value: 0.8758138815869092.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:36:40<1:17:55, 4675.27s/it]

[I 2026-02-21 11:47:29,606] Trial 65 finished with value: 0.8705134061893153 and parameters: {'layer1': 189, 'layer2': 251, 'layer3': 301, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0003480909168960279}. Best is trial 20 with value: 0.8758138815869092.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:36:50<1:17:55, 4675.27s/it]

[I 2026-02-21 11:47:39,407] Trial 66 finished with value: 0.8471561500729321 and parameters: {'layer1': 139, 'layer2': 228, 'layer3': 204, 'activation': 'identity', 'solver': 'adam', 'lr': 3.574634862095895e-05}. Best is trial 20 with value: 0.8758138815869092.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:37:08<1:17:55, 4675.27s/it]

[I 2026-02-21 11:47:57,693] Trial 67 finished with value: 0.8705299599332385 and parameters: {'layer1': 224, 'layer2': 284, 'layer3': 326, 'activation': 'identity', 'solver': 'adam', 'lr': 0.00011565374098705592}. Best is trial 20 with value: 0.8758138815869092.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:37:16<1:17:55, 4675.27s/it]

[I 2026-02-21 11:48:05,838] Trial 68 finished with value: 0.8458290816039972 and parameters: {'layer1': 96, 'layer2': 205, 'layer3': 53, 'activation': 'identity', 'solver': 'adam', 'lr': 1.3987506577172981e-05}. Best is trial 20 with value: 0.8758138815869092.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:37:31<1:17:55, 4675.27s/it]

[I 2026-02-21 11:48:20,494] Trial 69 finished with value: 0.8741631474535818 and parameters: {'layer1': 124, 'layer2': 124, 'layer3': 256, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0004536601801285488}. Best is trial 20 with value: 0.8758138815869092.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:37:44<1:17:55, 4675.27s/it]

[I 2026-02-21 11:48:32,980] Trial 70 finished with value: 0.8730068781345077 and parameters: {'layer1': 117, 'layer2': 128, 'layer3': 248, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0004907559821507501}. Best is trial 20 with value: 0.8758138815869092.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:38:00<1:17:55, 4675.27s/it]

[I 2026-02-21 11:48:49,231] Trial 71 finished with value: 0.8751980798757566 and parameters: {'layer1': 168, 'layer2': 86, 'layer3': 261, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0010997739225430537}. Best is trial 20 with value: 0.8758138815869092.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:38:12<1:17:55, 4675.27s/it]

[I 2026-02-21 11:49:01,596] Trial 72 finished with value: 0.8708978490576603 and parameters: {'layer1': 69, 'layer2': 86, 'layer3': 292, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0013136674586650071}. Best is trial 20 with value: 0.8758138815869092.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:38:27<1:17:55, 4675.27s/it]

[I 2026-02-21 11:49:15,907] Trial 73 finished with value: 0.8722292655390035 and parameters: {'layer1': 205, 'layer2': 118, 'layer3': 261, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0007277608920289803}. Best is trial 20 with value: 0.8758138815869092.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:38:35<1:17:55, 4675.27s/it]

[I 2026-02-21 11:49:24,205] Trial 74 finished with value: 0.8458290816039972 and parameters: {'layer1': 175, 'layer2': 64, 'layer3': 12, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.00252549009087214}. Best is trial 20 with value: 0.8758138815869092.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:38:49<1:17:55, 4675.27s/it]

[I 2026-02-21 11:49:38,226] Trial 75 finished with value: 0.8738705190137797 and parameters: {'layer1': 35, 'layer2': 100, 'layer3': 212, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0009430506011227137}. Best is trial 20 with value: 0.8758138815869092.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:38:56<1:17:55, 4675.27s/it]

[I 2026-02-21 11:49:45,508] Trial 76 finished with value: 0.8468525591639773 and parameters: {'layer1': 143, 'layer2': 25, 'layer3': 166, 'activation': 'tanh', 'solver': 'sgd', 'lr': 0.0018342230417513709}. Best is trial 20 with value: 0.8758138815869092.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:39:12<1:17:55, 4675.27s/it]

[I 2026-02-21 11:50:01,260] Trial 77 finished with value: 0.8742039873302083 and parameters: {'layer1': 123, 'layer2': 166, 'layer3': 324, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0004000074580966834}. Best is trial 20 with value: 0.8758138815869092.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:39:24<1:17:55, 4675.27s/it]

[I 2026-02-21 11:50:12,983] Trial 78 finished with value: 0.8471561500729321 and parameters: {'layer1': 277, 'layer2': 174, 'layer3': 469, 'activation': 'tanh', 'solver': 'adam', 'lr': 3.486682923310525e-06}. Best is trial 20 with value: 0.8758138815869092.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:39:45<1:17:55, 4675.27s/it]

[I 2026-02-21 11:50:34,455] Trial 79 finished with value: 0.872508189238058 and parameters: {'layer1': 159, 'layer2': 152, 'layer3': 319, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0011602312289209504}. Best is trial 20 with value: 0.8758138815869092.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:40:03<1:17:55, 4675.27s/it]

[I 2026-02-21 11:50:52,435] Trial 80 finished with value: 0.8696307791474815 and parameters: {'layer1': 250, 'layer2': 192, 'layer3': 351, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0002965045269805398}. Best is trial 20 with value: 0.8758138815869092.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:40:15<1:17:55, 4675.27s/it]

[I 2026-02-21 11:51:04,753] Trial 81 finished with value: 0.8735234894131285 and parameters: {'layer1': 128, 'layer2': 129, 'layer3': 231, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.00042528704531926857}. Best is trial 20 with value: 0.8758138815869092.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:40:28<1:17:55, 4675.27s/it]

[I 2026-02-21 11:51:17,232] Trial 82 finished with value: 0.8717938114381216 and parameters: {'layer1': 100, 'layer2': 169, 'layer3': 254, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0005758467537573808}. Best is trial 20 with value: 0.8758138815869092.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:40:44<1:17:55, 4675.27s/it]

[I 2026-02-21 11:51:33,111] Trial 83 finished with value: 0.8774898576829614 and parameters: {'layer1': 112, 'layer2': 77, 'layer3': 81, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.00020865167546455627}. Best is trial 83 with value: 0.8774898576829614.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:41:02<1:17:55, 4675.27s/it]

[I 2026-02-21 11:51:51,679] Trial 84 finished with value: 0.8712691748038276 and parameters: {'layer1': 86, 'layer2': 50, 'layer3': 127, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.00019841388102910938}. Best is trial 83 with value: 0.8774898576829614.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:41:16<1:17:55, 4675.27s/it]

[I 2026-02-21 11:52:05,641] Trial 85 finished with value: 0.871424572900948 and parameters: {'layer1': 184, 'layer2': 80, 'layer3': 111, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.000732355659071394}. Best is trial 83 with value: 0.8774898576829614.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:41:28<1:17:55, 4675.27s/it]

[I 2026-02-21 11:52:17,604] Trial 86 finished with value: 0.8584667325803922 and parameters: {'layer1': 109, 'layer2': 11, 'layer3': 93, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00033887686502317933}. Best is trial 83 with value: 0.8774898576829614.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:41:40<1:17:55, 4675.27s/it]

[I 2026-02-21 11:52:29,264] Trial 87 finished with value: 0.846246792548024 and parameters: {'layer1': 221, 'layer2': 354, 'layer3': 68, 'activation': 'relu', 'solver': 'sgd', 'lr': 0.00021393441497338377}. Best is trial 83 with value: 0.8774898576829614.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:41:53<1:17:55, 4675.27s/it]

[I 2026-02-21 11:52:42,585] Trial 88 finished with value: 0.8689292877132194 and parameters: {'layer1': 74, 'layer2': 315, 'layer3': 499, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0009780143468365188}. Best is trial 83 with value: 0.8774898576829614.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:42:08<1:17:55, 4675.27s/it]

[I 2026-02-21 11:52:57,711] Trial 89 finished with value: 0.8626718149634923 and parameters: {'layer1': 140, 'layer2': 73, 'layer3': 82, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0001408758404464241}. Best is trial 83 with value: 0.8774898576829614.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:42:19<1:17:55, 4675.27s/it]

[I 2026-02-21 11:53:08,575] Trial 90 finished with value: 0.8699557461271749 and parameters: {'layer1': 60, 'layer2': 386, 'layer3': 42, 'activation': 'relu', 'solver': 'adam', 'lr': 0.004671059951367369}. Best is trial 83 with value: 0.8774898576829614.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:42:33<1:17:55, 4675.27s/it]

[I 2026-02-21 11:53:22,112] Trial 91 finished with value: 0.8743478299887556 and parameters: {'layer1': 120, 'layer2': 147, 'layer3': 192, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.00041165890719189547}. Best is trial 83 with value: 0.8774898576829614.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:42:46<1:17:55, 4675.27s/it]

[I 2026-02-21 11:53:35,321] Trial 92 finished with value: 0.8721212321358307 and parameters: {'layer1': 167, 'layer2': 151, 'layer3': 287, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0006578905147685829}. Best is trial 83 with value: 0.8774898576829614.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:43:02<1:17:55, 4675.27s/it]

[I 2026-02-21 11:53:51,436] Trial 93 finished with value: 0.8720356923491988 and parameters: {'layer1': 115, 'layer2': 109, 'layer3': 190, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.002005120216505042}. Best is trial 83 with value: 0.8774898576829614.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:43:19<1:17:55, 4675.27s/it]

[I 2026-02-21 11:54:08,517] Trial 94 finished with value: 0.876036149676174 and parameters: {'layer1': 155, 'layer2': 147, 'layer3': 153, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0002671917274108292}. Best is trial 83 with value: 0.8774898576829614.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:43:36<1:17:55, 4675.27s/it]

[I 2026-02-21 11:54:25,316] Trial 95 finished with value: 0.8663301628351106 and parameters: {'layer1': 147, 'layer2': 140, 'layer3': 156, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0013210984422721882}. Best is trial 83 with value: 0.8774898576829614.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:43:51<1:17:55, 4675.27s/it]

[I 2026-02-21 11:54:40,122] Trial 96 finished with value: 0.8733733261840128 and parameters: {'layer1': 40, 'layer2': 89, 'layer3': 215, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0002725111730773548}. Best is trial 83 with value: 0.8774898576829614.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:44:08<1:17:55, 4675.27s/it]

[I 2026-02-21 11:54:57,402] Trial 97 finished with value: 0.8730083140871757 and parameters: {'layer1': 197, 'layer2': 333, 'layer3': 121, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0005256251974397088}. Best is trial 83 with value: 0.8774898576829614.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:44:24<1:17:55, 4675.27s/it]

[I 2026-02-21 11:55:13,289] Trial 98 finished with value: 0.8696750071952642 and parameters: {'layer1': 181, 'layer2': 36, 'layer3': 137, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0007837264306332539}. Best is trial 83 with value: 0.8774898576829614.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:44:33<1:17:55, 4675.27s/it]

[I 2026-02-21 11:55:21,947] Trial 99 finished with value: 0.8477756146031619 and parameters: {'layer1': 155, 'layer2': 108, 'layer3': 175, 'activation': 'tanh', 'solver': 'sgd', 'lr': 0.00025484873275609545}. Best is trial 83 with value: 0.8774898576829614.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:44:49<1:17:55, 4675.27s/it]

[I 2026-02-21 11:55:38,215] Trial 100 finished with value: 0.8709091792072169 and parameters: {'layer1': 136, 'layer2': 52, 'layer3': 150, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0003549509734660526}. Best is trial 83 with value: 0.8774898576829614.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:45:03<1:17:55, 4675.27s/it]

[I 2026-02-21 11:55:52,815] Trial 101 finished with value: 0.8717577714167926 and parameters: {'layer1': 89, 'layer2': 147, 'layer3': 486, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0001809714447552316}. Best is trial 83 with value: 0.8774898576829614.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:45:18<1:17:55, 4675.27s/it]

[I 2026-02-21 11:56:07,716] Trial 102 finished with value: 0.8721741699450352 and parameters: {'layer1': 165, 'layer2': 164, 'layer3': 190, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0003983477264354764}. Best is trial 83 with value: 0.8774898576829614.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:45:32<1:17:55, 4675.27s/it]

[I 2026-02-21 11:56:21,423] Trial 103 finished with value: 0.8750449628066661 and parameters: {'layer1': 123, 'layer2': 180, 'layer3': 447, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0016387505889896578}. Best is trial 83 with value: 0.8774898576829614.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:45:46<1:17:55, 4675.27s/it]

[I 2026-02-21 11:56:35,122] Trial 104 finished with value: 0.8683086390889094 and parameters: {'layer1': 100, 'layer2': 190, 'layer3': 422, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0015378352742863662}. Best is trial 83 with value: 0.8774898576829614.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:45:59<1:17:55, 4675.27s/it]

[I 2026-02-21 11:56:48,705] Trial 105 finished with value: 0.8692891327410264 and parameters: {'layer1': 150, 'layer2': 136, 'layer3': 471, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0011050081747353746}. Best is trial 83 with value: 0.8774898576829614.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:46:16<1:17:55, 4675.27s/it]

[I 2026-02-21 11:57:05,076] Trial 106 finished with value: 0.871026736677662 and parameters: {'layer1': 170, 'layer2': 177, 'layer3': 453, 'activation': 'relu', 'solver': 'adam', 'lr': 0.002620307785561574}. Best is trial 83 with value: 0.8774898576829614.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:46:30<1:17:55, 4675.27s/it]

[I 2026-02-21 11:57:19,322] Trial 107 finished with value: 0.8740935630405071 and parameters: {'layer1': 133, 'layer2': 120, 'layer3': 461, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0006172670595710278}. Best is trial 83 with value: 0.8774898576829614.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:46:49<1:17:55, 4675.27s/it]

[I 2026-02-21 11:57:38,153] Trial 108 finished with value: 0.8698277455148256 and parameters: {'layer1': 330, 'layer2': 159, 'layer3': 110, 'activation': 'relu', 'solver': 'adam', 'lr': 0.003919538956571524}. Best is trial 83 with value: 0.8774898576829614.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:47:06<1:17:55, 4675.27s/it]

[I 2026-02-21 11:57:55,667] Trial 109 finished with value: 0.8697655278800436 and parameters: {'layer1': 214, 'layer2': 210, 'layer3': 491, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0008677534177345013}. Best is trial 83 with value: 0.8774898576829614.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:47:21<1:17:55, 4675.27s/it]

[I 2026-02-21 11:58:10,398] Trial 110 finished with value: 0.8760776693219251 and parameters: {'layer1': 111, 'layer2': 325, 'layer3': 136, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.000492377904546388}. Best is trial 83 with value: 0.8774898576829614.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:47:37<1:17:55, 4675.27s/it]

[I 2026-02-21 11:58:26,009] Trial 111 finished with value: 0.8706336030608176 and parameters: {'layer1': 111, 'layer2': 333, 'layer3': 137, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0005353918363997055}. Best is trial 83 with value: 0.8774898576829614.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:47:54<1:17:55, 4675.27s/it]

[I 2026-02-21 11:58:43,091] Trial 112 finished with value: 0.8719792299973621 and parameters: {'layer1': 122, 'layer2': 298, 'layer3': 164, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0014962927689349964}. Best is trial 83 with value: 0.8774898576829614.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:48:08<1:17:55, 4675.27s/it]

[I 2026-02-21 11:58:57,414] Trial 113 finished with value: 0.8720411095288101 and parameters: {'layer1': 92, 'layer2': 98, 'layer3': 132, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.00023847886598801364}. Best is trial 83 with value: 0.8774898576829614.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:48:23<1:17:55, 4675.27s/it]

[I 2026-02-21 11:59:12,355] Trial 114 finished with value: 0.8750127492348397 and parameters: {'layer1': 79, 'layer2': 346, 'layer3': 83, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0021599055887449653}. Best is trial 83 with value: 0.8774898576829614.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:48:37<1:17:55, 4675.27s/it]

[I 2026-02-21 11:59:26,222] Trial 115 finished with value: 0.868114987878838 and parameters: {'layer1': 64, 'layer2': 349, 'layer3': 87, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.0029165819724809618}. Best is trial 83 with value: 0.8774898576829614.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:48:51<1:17:55, 4675.27s/it]

[I 2026-02-21 11:59:40,560] Trial 116 finished with value: 0.8750896559661108 and parameters: {'layer1': 79, 'layer2': 378, 'layer3': 69, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.002165915154164643}. Best is trial 83 with value: 0.8774898576829614.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:49:02<1:17:55, 4675.27s/it]

[I 2026-02-21 11:59:51,318] Trial 117 finished with value: 0.8583196993450792 and parameters: {'layer1': 24, 'layer2': 365, 'layer3': 79, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.001962579963993231}. Best is trial 83 with value: 0.8774898576829614.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:49:12<1:17:55, 4675.27s/it]

[I 2026-02-21 12:00:01,688] Trial 118 finished with value: 0.8595582789855166 and parameters: {'layer1': 83, 'layer2': 383, 'layer3': 55, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.002475208235645913}. Best is trial 83 with value: 0.8774898576829614.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:49:20<1:17:55, 4675.27s/it]

[I 2026-02-21 12:00:09,780] Trial 119 finished with value: 0.8458290816039972 and parameters: {'layer1': 54, 'layer2': 408, 'layer3': 106, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.005811109238670053}. Best is trial 83 with value: 0.8774898576829614.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:49:27<1:17:55, 4675.27s/it]

[I 2026-02-21 12:00:16,631] Trial 120 finished with value: 0.8458290816039972 and parameters: {'layer1': 103, 'layer2': 390, 'layer3': 29, 'activation': 'tanh', 'solver': 'sgd', 'lr': 0.0012341525268695886}. Best is trial 83 with value: 0.8774898576829614.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:49:44<1:17:55, 4675.27s/it]

[I 2026-02-21 12:00:33,609] Trial 121 finished with value: 0.8699825024777705 and parameters: {'layer1': 77, 'layer2': 372, 'layer3': 61, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0016096964835196328}. Best is trial 83 with value: 0.8774898576829614.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:50:01<1:17:55, 4675.27s/it]

[I 2026-02-21 12:00:50,476] Trial 122 finished with value: 0.8728943628266019 and parameters: {'layer1': 133, 'layer2': 322, 'layer3': 93, 'activation': 'relu', 'solver': 'adam', 'lr': 0.002207219896256596}. Best is trial 83 with value: 0.8774898576829614.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:50:11<1:17:55, 4675.27s/it]

[I 2026-02-21 12:01:00,790] Trial 123 finished with value: 0.8707665613353628 and parameters: {'layer1': 46, 'layer2': 349, 'layer3': 75, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0010140681860469247}. Best is trial 83 with value: 0.8774898576829614.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:50:28<1:17:55, 4675.27s/it]

[I 2026-02-21 12:01:17,706] Trial 124 finished with value: 0.8740774987436687 and parameters: {'layer1': 154, 'layer2': 445, 'layer3': 70, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0007973772695453968}. Best is trial 83 with value: 0.8774898576829614.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:50:45<1:17:55, 4675.27s/it]

[I 2026-02-21 12:01:34,779] Trial 125 finished with value: 0.8750380491323753 and parameters: {'layer1': 188, 'layer2': 324, 'layer3': 480, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0033458630735534226}. Best is trial 83 with value: 0.8774898576829614.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:51:00<1:17:55, 4675.27s/it]

[I 2026-02-21 12:01:49,303] Trial 126 finished with value: 0.8714297513234284 and parameters: {'layer1': 76, 'layer2': 306, 'layer3': 478, 'activation': 'relu', 'solver': 'adam', 'lr': 0.003259020926047135}. Best is trial 83 with value: 0.8774898576829614.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:51:11<1:17:55, 4675.27s/it]

[I 2026-02-21 12:02:00,739] Trial 127 finished with value: 0.8458290816039972 and parameters: {'layer1': 186, 'layer2': 324, 'layer3': 441, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.004966203253362262}. Best is trial 83 with value: 0.8774898576829614.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:51:22<1:17:55, 4675.27s/it]

[I 2026-02-21 12:02:11,166] Trial 128 finished with value: 0.8458290816039972 and parameters: {'layer1': 199, 'layer2': 72, 'layer3': 491, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0076769333730265475}. Best is trial 83 with value: 0.8774898576829614.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:51:35<1:17:55, 4675.27s/it]

[I 2026-02-21 12:02:24,056] Trial 129 finished with value: 0.8716696057390714 and parameters: {'layer1': 94, 'layer2': 273, 'layer3': 36, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0037024592830849127}. Best is trial 83 with value: 0.8774898576829614.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:51:49<1:17:55, 4675.27s/it]

[I 2026-02-21 12:02:38,661] Trial 130 finished with value: 0.8679888470043302 and parameters: {'layer1': 144, 'layer2': 399, 'layer3': 480, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0018275644681019902}. Best is trial 83 with value: 0.8774898576829614.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:52:06<1:17:55, 4675.27s/it]

[I 2026-02-21 12:02:55,683] Trial 131 finished with value: 0.8694207298017904 and parameters: {'layer1': 176, 'layer2': 289, 'layer3': 244, 'activation': 'relu', 'solver': 'adam', 'lr': 0.001304333584773061}. Best is trial 83 with value: 0.8774898576829614.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:52:20<1:17:55, 4675.27s/it]

[I 2026-02-21 12:03:09,666] Trial 132 finished with value: 0.8705997198171191 and parameters: {'layer1': 113, 'layer2': 329, 'layer3': 500, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0006600702398062622}. Best is trial 83 with value: 0.8774898576829614.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:52:38<1:17:55, 4675.27s/it]

[I 2026-02-21 12:03:27,101] Trial 133 finished with value: 0.8731120292169164 and parameters: {'layer1': 230, 'layer2': 309, 'layer3': 118, 'activation': 'relu', 'solver': 'adam', 'lr': 0.002164105999974405}. Best is trial 83 with value: 0.8774898576829614.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:52:55<1:17:55, 4675.27s/it]

[I 2026-02-21 12:03:44,743] Trial 134 finished with value: 0.8694559529300736 and parameters: {'layer1': 188, 'layer2': 354, 'layer3': 461, 'activation': 'relu', 'solver': 'adam', 'lr': 0.002900103317571315}. Best is trial 83 with value: 0.8774898576829614.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:53:12<1:17:55, 4675.27s/it]

[I 2026-02-21 12:04:00,941] Trial 135 finished with value: 0.868913709932573 and parameters: {'layer1': 160, 'layer2': 343, 'layer3': 271, 'activation': 'relu', 'solver': 'adam', 'lr': 0.000995172009639006}. Best is trial 83 with value: 0.8774898576829614.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:53:27<1:17:55, 4675.27s/it]

[I 2026-02-21 12:04:16,175] Trial 136 finished with value: 0.8730675623365662 and parameters: {'layer1': 168, 'layer2': 260, 'layer3': 101, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0003154778839869562}. Best is trial 83 with value: 0.8774898576829614.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:53:42<1:17:55, 4675.27s/it]

[I 2026-02-21 12:04:31,724] Trial 137 finished with value: 0.8709353264600823 and parameters: {'layer1': 128, 'layer2': 419, 'layer3': 51, 'activation': 'relu', 'solver': 'adam', 'lr': 0.00048322066170007296}. Best is trial 83 with value: 0.8774898576829614.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:53:51<1:17:55, 4675.27s/it]

[I 2026-02-21 12:04:40,139] Trial 138 finished with value: 0.8458290816039972 and parameters: {'layer1': 106, 'layer2': 199, 'layer3': 377, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.00013899233330288993}. Best is trial 83 with value: 0.8774898576829614.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:54:08<1:17:55, 4675.27s/it]

[I 2026-02-21 12:04:57,696] Trial 139 finished with value: 0.8707170923481649 and parameters: {'layer1': 205, 'layer2': 183, 'layer3': 452, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0015093096914221614}. Best is trial 83 with value: 0.8774898576829614.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:54:16<1:17:55, 4675.27s/it]

[I 2026-02-21 12:05:05,757] Trial 140 finished with value: 0.8458290816039972 and parameters: {'layer1': 11, 'layer2': 59, 'layer3': 87, 'activation': 'relu', 'solver': 'sgd', 'lr': 0.0007698998696553556}. Best is trial 83 with value: 0.8774898576829614.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:54:29<1:17:55, 4675.27s/it]

[I 2026-02-21 12:05:18,591] Trial 141 finished with value: 0.8721237780950718 and parameters: {'layer1': 117, 'layer2': 146, 'layer3': 171, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0005100794138785522}. Best is trial 83 with value: 0.8774898576829614.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:54:44<1:17:55, 4675.27s/it]

[I 2026-02-21 12:05:33,535] Trial 142 finished with value: 0.8722361485844494 and parameters: {'layer1': 136, 'layer2': 84, 'layer3': 156, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.00040400945917603605}. Best is trial 83 with value: 0.8774898576829614.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:55:03<1:17:55, 4675.27s/it]

[I 2026-02-21 12:05:51,848] Trial 143 finished with value: 0.8729558927591903 and parameters: {'layer1': 148, 'layer2': 336, 'layer3': 181, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0002964590657199809}. Best is trial 83 with value: 0.8774898576829614.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:55:17<1:17:55, 4675.27s/it]

[I 2026-02-21 12:06:05,898] Trial 144 finished with value: 0.8750393722448655 and parameters: {'layer1': 125, 'layer2': 128, 'layer3': 65, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.000375184860535243}. Best is trial 83 with value: 0.8774898576829614.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:55:39<1:17:55, 4675.27s/it]

[I 2026-02-21 12:06:28,820] Trial 145 finished with value: 0.8711533565215047 and parameters: {'layer1': 408, 'layer2': 133, 'layer3': 44, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0006312252439965662}. Best is trial 83 with value: 0.8774898576829614.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:55:57<1:17:55, 4675.27s/it]

[I 2026-02-21 12:06:45,999] Trial 146 finished with value: 0.8733320853698437 and parameters: {'layer1': 83, 'layer2': 171, 'layer3': 66, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0002097073066649553}. Best is trial 83 with value: 0.8774898576829614.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:56:08<1:17:55, 4675.27s/it]

[I 2026-02-21 12:06:57,299] Trial 147 finished with value: 0.8689971970270591 and parameters: {'layer1': 68, 'layer2': 115, 'layer3': 267, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0012112521236545375}. Best is trial 83 with value: 0.8774898576829614.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:56:22<1:17:55, 4675.27s/it]

[I 2026-02-21 12:07:10,985] Trial 148 finished with value: 0.8716818526226862 and parameters: {'layer1': 96, 'layer2': 375, 'layer3': 61, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0017953530308742571}. Best is trial 83 with value: 0.8774898576829614.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:56:37<1:17:55, 4675.27s/it]

[I 2026-02-21 12:07:25,854] Trial 149 finished with value: 0.8777402466961522 and parameters: {'layer1': 159, 'layer2': 96, 'layer3': 233, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0003560854770638108}. Best is trial 149 with value: 0.8777402466961522.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:56:52<1:17:55, 4675.27s/it]

[I 2026-02-21 12:07:40,936] Trial 150 finished with value: 0.8708343580361578 and parameters: {'layer1': 159, 'layer2': 94, 'layer3': 488, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.00028750899928155677}. Best is trial 149 with value: 0.8777402466961522.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:57:07<1:17:55, 4675.27s/it]

[I 2026-02-21 12:07:56,081] Trial 151 finished with value: 0.8734093359078731 and parameters: {'layer1': 128, 'layer2': 106, 'layer3': 239, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.00037284894714281877}. Best is trial 149 with value: 0.8777402466961522.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:57:23<1:17:55, 4675.27s/it]

[I 2026-02-21 12:08:12,739] Trial 152 finished with value: 0.8737393336241215 and parameters: {'layer1': 175, 'layer2': 76, 'layer3': 78, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0005742356787022131}. Best is trial 149 with value: 0.8777402466961522.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:57:38<1:17:55, 4675.27s/it]

[I 2026-02-21 12:08:27,685] Trial 153 finished with value: 0.8679319310509331 and parameters: {'layer1': 140, 'layer2': 67, 'layer3': 285, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0004746608684641319}. Best is trial 149 with value: 0.8777402466961522.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:57:54<1:17:55, 4675.27s/it]

[I 2026-02-21 12:08:43,557] Trial 154 finished with value: 0.8709044644055789 and parameters: {'layer1': 193, 'layer2': 161, 'layer3': 231, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0008918458711982788}. Best is trial 149 with value: 0.8777402466961522.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:58:04<1:17:55, 4675.27s/it]

[I 2026-02-21 12:08:53,528] Trial 155 finished with value: 0.8458290816039972 and parameters: {'layer1': 153, 'layer2': 317, 'layer3': 206, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.004188133815325089}. Best is trial 149 with value: 0.8777402466961522.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:58:17<1:17:55, 4675.27s/it]

[I 2026-02-21 12:09:06,520] Trial 156 finished with value: 0.8741257917015736 and parameters: {'layer1': 109, 'layer2': 129, 'layer3': 144, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0023841831464780756}. Best is trial 149 with value: 0.8777402466961522.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:58:35<1:17:55, 4675.27s/it]

[I 2026-02-21 12:09:24,473] Trial 157 finished with value: 0.8709995626271704 and parameters: {'layer1': 169, 'layer2': 94, 'layer3': 89, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.00025978695223647985}. Best is trial 149 with value: 0.8777402466961522.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:58:57<1:17:55, 4675.27s/it]

[I 2026-02-21 12:09:46,176] Trial 158 finished with value: 0.8726340266900248 and parameters: {'layer1': 266, 'layer2': 360, 'layer3': 101, 'activation': 'relu', 'solver': 'adam', 'lr': 0.0001630976458944768}. Best is trial 149 with value: 0.8777402466961522.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:59:14<1:17:55, 4675.27s/it]

[I 2026-02-21 12:10:03,207] Trial 159 finished with value: 0.8704404255144927 and parameters: {'layer1': 243, 'layer2': 43, 'layer3': 306, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0010927946525404759}. Best is trial 149 with value: 0.8777402466961522.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:59:26<1:17:55, 4675.27s/it]

[I 2026-02-21 12:10:14,860] Trial 160 finished with value: 0.8719978334926614 and parameters: {'layer1': 145, 'layer2': 121, 'layer3': 425, 'activation': 'identity', 'solver': 'adam', 'lr': 0.0003356122122301495}. Best is trial 149 with value: 0.8777402466961522.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:59:40<1:17:55, 4675.27s/it]

[I 2026-02-21 12:10:29,217] Trial 161 finished with value: 0.8687047955381381 and parameters: {'layer1': 120, 'layer2': 156, 'layer3': 153, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0003883240898775881}. Best is trial 149 with value: 0.8777402466961522.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [24:59:53<1:17:55, 4675.27s/it]

[I 2026-02-21 12:10:42,161] Trial 162 finished with value: 0.8746218724082034 and parameters: {'layer1': 121, 'layer2': 139, 'layer3': 215, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0004265520828507183}. Best is trial 149 with value: 0.8777402466961522.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [25:00:09<1:17:55, 4675.27s/it]

[I 2026-02-21 12:10:58,016] Trial 163 finished with value: 0.8706551972115004 and parameters: {'layer1': 99, 'layer2': 83, 'layer3': 214, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0004607820391886557}. Best is trial 149 with value: 0.8777402466961522.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [25:00:21<1:17:55, 4675.27s/it]

[I 2026-02-21 12:11:10,504] Trial 164 finished with value: 0.8714711256857388 and parameters: {'layer1': 130, 'layer2': 140, 'layer3': 250, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0007123883423918425}. Best is trial 149 with value: 0.8777402466961522.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [25:00:38<1:17:55, 4675.27s/it]

[I 2026-02-21 12:11:27,412] Trial 165 finished with value: 0.871739747128462 and parameters: {'layer1': 299, 'layer2': 113, 'layer3': 472, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.000548914505842231}. Best is trial 149 with value: 0.8777402466961522.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [25:00:55<1:17:55, 4675.27s/it]

[I 2026-02-21 12:11:44,716] Trial 166 finished with value: 0.8757306592463829 and parameters: {'layer1': 178, 'layer2': 326, 'layer3': 227, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0014042053598038713}. Best is trial 149 with value: 0.8777402466961522.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [25:01:11<1:17:55, 4675.27s/it]

[I 2026-02-21 12:12:00,809] Trial 167 finished with value: 0.8767914732248278 and parameters: {'layer1': 180, 'layer2': 308, 'layer3': 198, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.00021201229060451642}. Best is trial 149 with value: 0.8777402466961522.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [25:01:27<1:17:55, 4675.27s/it]

[I 2026-02-21 12:12:16,120] Trial 168 finished with value: 0.8748516882739208 and parameters: {'layer1': 163, 'layer2': 302, 'layer3': 200, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.000221321298612305}. Best is trial 149 with value: 0.8777402466961522.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [25:01:37<1:17:55, 4675.27s/it]

[I 2026-02-21 12:12:26,119] Trial 169 finished with value: 0.8489893733668312 and parameters: {'layer1': 185, 'layer2': 296, 'layer3': 197, 'activation': 'tanh', 'solver': 'sgd', 'lr': 0.00010226517531593572}. Best is trial 149 with value: 0.8777402466961522.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [25:01:54<1:17:55, 4675.27s/it]

[I 2026-02-21 12:12:43,446] Trial 170 finished with value: 0.8739682330334253 and parameters: {'layer1': 177, 'layer2': 282, 'layer3': 178, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.00020860730206454927}. Best is trial 149 with value: 0.8777402466961522.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [25:02:10<1:17:55, 4675.27s/it]

[I 2026-02-21 12:12:59,628] Trial 171 finished with value: 0.8708923205553104 and parameters: {'layer1': 162, 'layer2': 306, 'layer3': 227, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0002497550472274629}. Best is trial 149 with value: 0.8777402466961522.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [25:02:28<1:17:55, 4675.27s/it]

[I 2026-02-21 12:13:17,030] Trial 172 finished with value: 0.8703500961183768 and parameters: {'layer1': 198, 'layer2': 340, 'layer3': 222, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0001708892125416057}. Best is trial 149 with value: 0.8777402466961522.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [25:02:46<1:17:55, 4675.27s/it]

[I 2026-02-21 12:13:34,909] Trial 173 finished with value: 0.8718239253165116 and parameters: {'layer1': 166, 'layer2': 324, 'layer3': 203, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.00012272800720431314}. Best is trial 149 with value: 0.8777402466961522.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [25:03:00<1:17:55, 4675.27s/it]

[I 2026-02-21 12:13:49,680] Trial 174 finished with value: 0.8711973306234706 and parameters: {'layer1': 180, 'layer2': 328, 'layer3': 168, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0003190907308429865}. Best is trial 149 with value: 0.8777402466961522.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [25:03:17<1:17:55, 4675.27s/it]

[I 2026-02-21 12:14:06,491] Trial 175 finished with value: 0.8708840234287788 and parameters: {'layer1': 156, 'layer2': 311, 'layer3': 500, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0002454582040109637}. Best is trial 149 with value: 0.8777402466961522.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [25:03:35<1:17:55, 4675.27s/it]

[I 2026-02-21 12:14:24,219] Trial 176 finished with value: 0.8737718065352057 and parameters: {'layer1': 141, 'layer2': 345, 'layer3': 124, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.00020138302392940638}. Best is trial 149 with value: 0.8777402466961522.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [25:03:51<1:17:55, 4675.27s/it]

[I 2026-02-21 12:14:40,475] Trial 177 finished with value: 0.861168043477757 and parameters: {'layer1': 171, 'layer2': 303, 'layer3': 71, 'activation': 'logistic', 'solver': 'adam', 'lr': 0.001716223583996668}. Best is trial 149 with value: 0.8777402466961522.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [25:04:04<1:17:55, 4675.27s/it]

[I 2026-02-21 12:14:53,794] Trial 178 finished with value: 0.8523807715633589 and parameters: {'layer1': 148, 'layer2': 290, 'layer3': 235, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0029437989584715323}. Best is trial 149 with value: 0.8777402466961522.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [25:04:20<1:17:55, 4675.27s/it]

[I 2026-02-21 12:15:09,215] Trial 179 finished with value: 0.8635901511752303 and parameters: {'layer1': 41, 'layer2': 315, 'layer3': 244, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.002081912267626923}. Best is trial 149 with value: 0.8777402466961522.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [25:04:37<1:17:55, 4675.27s/it]

[I 2026-02-21 12:15:26,328] Trial 180 finished with value: 0.876092464696978 and parameters: {'layer1': 158, 'layer2': 59, 'layer3': 54, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0014614927520461964}. Best is trial 149 with value: 0.8777402466961522.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [25:04:54<1:17:55, 4675.27s/it]

[I 2026-02-21 12:15:43,269] Trial 181 finished with value: 0.876882168826182 and parameters: {'layer1': 162, 'layer2': 334, 'layer3': 55, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0013786968833183878}. Best is trial 149 with value: 0.8777402466961522.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [25:05:11<1:17:55, 4675.27s/it]

[I 2026-02-21 12:16:00,646] Trial 182 finished with value: 0.8768607786623199 and parameters: {'layer1': 187, 'layer2': 64, 'layer3': 22, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0013560940665425917}. Best is trial 149 with value: 0.8777402466961522.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [25:05:26<1:17:55, 4675.27s/it]

[I 2026-02-21 12:16:14,880] Trial 183 finished with value: 0.8710734708253055 and parameters: {'layer1': 188, 'layer2': 56, 'layer3': 21, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0014111651826406067}. Best is trial 149 with value: 0.8777402466961522.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [25:05:39<1:17:55, 4675.27s/it]

[I 2026-02-21 12:16:27,849] Trial 184 finished with value: 0.8573477269359066 and parameters: {'layer1': 207, 'layer2': 28, 'layer3': 48, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0012911570682821432}. Best is trial 149 with value: 0.8777402466961522.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [25:05:55<1:17:55, 4675.27s/it]

[I 2026-02-21 12:16:44,466] Trial 185 finished with value: 0.8738965429687748 and parameters: {'layer1': 181, 'layer2': 72, 'layer3': 38, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0016668288827366659}. Best is trial 149 with value: 0.8777402466961522.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [25:06:12<1:17:55, 4675.27s/it]

[I 2026-02-21 12:17:01,298] Trial 186 finished with value: 0.8732190582274182 and parameters: {'layer1': 160, 'layer2': 64, 'layer3': 63, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0010242051256972398}. Best is trial 149 with value: 0.8777402466961522.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [25:06:21<1:17:55, 4675.27s/it]

[I 2026-02-21 12:17:10,711] Trial 187 finished with value: 0.8458290816039972 and parameters: {'layer1': 193, 'layer2': 340, 'layer3': 28, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.00246181669249106}. Best is trial 149 with value: 0.8777402466961522.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [25:06:38<1:17:55, 4675.27s/it]

[I 2026-02-21 12:17:27,030] Trial 188 finished with value: 0.8572746557360332 and parameters: {'layer1': 176, 'layer2': 331, 'layer3': 20, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0019231820879236485}. Best is trial 149 with value: 0.8777402466961522.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [25:06:55<1:17:55, 4675.27s/it]

[I 2026-02-21 12:17:44,097] Trial 189 finished with value: 0.8763443078253609 and parameters: {'layer1': 167, 'layer2': 44, 'layer3': 56, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0014308747746578133}. Best is trial 149 with value: 0.8777402466961522.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [25:07:10<1:17:55, 4675.27s/it]

[I 2026-02-21 12:17:59,716] Trial 190 finished with value: 0.8744303691438937 and parameters: {'layer1': 87, 'layer2': 43, 'layer3': 55, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.001362184760737415}. Best is trial 149 with value: 0.8777402466961522.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [25:07:26<1:17:55, 4675.27s/it]

[I 2026-02-21 12:18:15,088] Trial 191 finished with value: 0.8736617514263079 and parameters: {'layer1': 168, 'layer2': 53, 'layer3': 57, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0011916397693481232}. Best is trial 149 with value: 0.8777402466961522.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [25:07:43<1:17:55, 4675.27s/it]

[I 2026-02-21 12:18:32,375] Trial 192 finished with value: 0.8744935097896841 and parameters: {'layer1': 162, 'layer2': 82, 'layer3': 48, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0008729032253621622}. Best is trial 149 with value: 0.8777402466961522.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [25:07:59<1:17:55, 4675.27s/it]

[I 2026-02-21 12:18:48,767] Trial 193 finished with value: 0.8717075648040534 and parameters: {'layer1': 149, 'layer2': 62, 'layer3': 81, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0016754380271846669}. Best is trial 149 with value: 0.8777402466961522.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [25:08:17<1:17:55, 4675.27s/it]

[I 2026-02-21 12:19:06,610] Trial 194 finished with value: 0.880614722040528 and parameters: {'layer1': 183, 'layer2': 90, 'layer3': 41, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0015241314707192242}. Best is trial 194 with value: 0.880614722040528.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [25:08:35<1:17:55, 4675.27s/it]

[I 2026-02-21 12:19:24,795] Trial 195 finished with value: 0.8766075369797102 and parameters: {'layer1': 199, 'layer2': 91, 'layer3': 35, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.00147041688146441}. Best is trial 194 with value: 0.880614722040528.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [25:08:54<1:17:55, 4675.27s/it]

[I 2026-02-21 12:19:42,862] Trial 196 finished with value: 0.866993498954219 and parameters: {'layer1': 215, 'layer2': 92, 'layer3': 30, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0015041826202764146}. Best is trial 194 with value: 0.880614722040528.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [25:09:02<1:17:55, 4675.27s/it]

[I 2026-02-21 12:19:51,491] Trial 197 finished with value: 0.8458290816039972 and parameters: {'layer1': 200, 'layer2': 104, 'layer3': 17, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0022168653808976022}. Best is trial 194 with value: 0.880614722040528.

Training Exact MLP (Paper):  93%|█████████▎| 13/14 [25:09:19<1:17:55, 4675.27s/it]

[I 2026-02-21 12:20:08,335] Trial 198 finished with value: 0.8795401862262393 and parameters: {'layer1': 183, 'layer2': 79, 'layer3': 41, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.001134156719262036}. Best is trial 194 with value: 0.880614722040528.

Best trial: 194. Best value: 0.880615: 100%|██████████| 200/200 [48:51<00:00, 14.66s/it]

[I 2026-02-21 12:20:24,240] Trial 199 finished with value: 0.8730403024329446 and parameters: {'layer1': 186, 'layer2': 78, 'layer3': 32, 'activation': 'tanh', 'solver': 'adam', 'lr': 0.0011663769010312644}. Best is trial 194 with value: 0.880614722040528.

Training Exact MLP (Paper): 100%|██████████| 14/14 [25:09:35<00:00, 6469.71s/it]

  → Best model saved.

                   Species               Antibiotic  WF1_test
5         Escherichia_Coli  Piperacillin-Tazobactam  0.898360
6         Escherichia_Coli                 Cefepime  0.756065
4         Escherichia_Coli              Ceftriaxone  0.705170
3         Escherichia_Coli            Ciprofloxacin  0.590427
9    Klebsiella_Pneumoniae                 Imipenem  0.983929
10   Klebsiella_Pneumoniae                Meropenem  0.983929
8    Klebsiella_Pneumoniae              Ceftriaxone  0.788307
7    Klebsiella_Pneumoniae            Ciprofloxacin  0.740450
13  Pseudomonas_Aeruginosa                Meropenem  0.843685
11  Pseudomonas_Aeruginosa            Ciprofloxacin  0.815084
12  Pseudomonas_Aeruginosa                 Imipenem  0.815084
1    Staphylococcus_Aureus              Clindamycin  0.790639
0    Staphylococcus_Aureus                Oxacillin  0.709946
2    Staphylococcus_Aureus             Fusidic acid  0.043464

In [37]:
scores_summary = []

for file in os.listdir(MODEL_DIR):
    if file.endswith(".pt"):
        
        path = os.path.join(MODEL_DIR, file)
        checkpoint = torch.load(path, map_location="cpu")
        
        # Extract species and antibiotic from filename
        name = file.replace("_best_model.pt", "")
        species, antibiotic = name.split("_", 1)
        
        scores_summary.append({
            "Species": species,
            "Antibiotic": antibiotic,
            "Best_Training_WF1": checkpoint["score"],
            "Layer1": checkpoint["params"]["layer1"],
            "Layer2": checkpoint["params"]["layer2"],
            "Layer3": checkpoint["params"]["layer3"],
            "Activation": checkpoint["params"]["activation"],
            "Solver": checkpoint["params"]["solver"],
            "LR": checkpoint["params"]["lr"],
        })

scores_df = pd.DataFrame(scores_summary).sort_values(
    ["Species", "Best_Training_WF1"],
    ascending=[True, False]
)

scores_df

,Species,Antibiotic,Best_Training_WF1,Layer1,Layer2,Layer3,Activation,Solver,LR
3,Escherichia,Coli_Piperacillin-Tazobactam,1.000000,98,255,357,relu,adam,0.004922
10,Escherichia,Coli_Cefepime,0.757513,227,455,32,tanh,adam,0.000026
4,Escherichia,Coli_Ceftriaxone,0.705466,430,370,343,logistic,adam,0.002801
13,Escherichia,Coli_Ciprofloxacin,0.611404,359,468,153,relu,adam,0.000013
0,Klebsiella,Pneumoniae_Imipenem,0.984597,244,491,320,tanh,adam,0.000797
6,Klebsiella,Pneumoniae_Meropenem,0.984597,19,83,455,relu,adam,0.006371
9,Klebsiella,Pneumoniae_Ceftriaxone,0.788941,500,404,477,tanh,adam,0.000017
5,Klebsiella,Pneumoniae_Ciprofloxacin,0.740450,351,492,485,identity,adam,0.000035
11,Pseudomonas,Aeruginosa_Meropenem,0.845829,183,90,41,tanh,adam,0.001524
2,Pseudomonas,Aeruginosa_Imipenem,0.817162,376,173,33,relu,adam,0.000124
8,Pseudomonas,Aeruginosa_Ciprofloxacin,0.815577,196,127,33,tanh,adam,0.002187
1,Staphylococcus,Aureus_Fusidic acid,0.905066,131,262,197,identity,adam,0.006988
7,Staphylococcus,Aureus_Clindamycin,0.792606,407,421,472,relu,adam,0.000030
12,Staphylococcus,Aureus_Oxacillin,0.711014,244,254,266,relu,adam,0.000012

In [39]:
mean_train_species = (
    scores_df
    .groupby("Species")["Best_Training_WF1"]
    .mean()
    .reset_index()
    .rename(columns={"Best_Training_WF1": "Mean_WF1_train"})
    .sort_values("Mean_WF1_train", ascending=False)
)

mean_train_species

          Species  Mean_WF1_train
1      Klebsiella        0.874646
2     Pseudomonas        0.826189
3  Staphylococcus        0.802895
0     Escherichia        0.768596

# 5.3 Evaluation of the Trained Models on the Test Set

In this section, we load the previously saved optimized MLP models 
(one per species and antibiotic) and evaluate them on the held-out test set.

We compute the Weighted F1-score (WF1) for each binary classifier
on the corresponding test subset.

In [17]:
paper_single_results = []
MODEL_DIR = os.path.join(PROJECT_ROOT, "saved_models", "benchmark1_mlp_optuna_exact")
os.makedirs(MODEL_DIR, exist_ok=True)

for species, ab_list in species_antibiotics.items():

    df_sp = species_datasets[species]
    test_idx  = global_splits[species]["test_idx"]

    wf1_list = []
    acc_list = []
    hl_list = []

    for ab in ab_list:

        model_path = os.path.join(MODEL_DIR, f"{species}_{ab}_best_model.pt")
        checkpoint = torch.load(model_path, map_location=device)

        params = checkpoint["params"]

        model = MLPBinary(
            input_dim=X.shape[1],
            layer1=params["layer1"],
            layer2=params["layer2"],
            layer3=params["layer3"],
            activation=params["activation"]
        ).to(device)

        model.load_state_dict(checkpoint["model_state_dict"])
        model.eval()

        X_test = torch.tensor(X[test_idx], dtype=torch.float32).to(device)
        y_test = df_sp.loc[test_idx, ab].astype(int).values

        with torch.no_grad():
            logits = model(X_test)
            preds = (torch.sigmoid(logits) > 0.5).cpu().numpy().ravel()

        wf1_ab = f1_score(y_test, preds, average="weighted")
        acc_ab = accuracy_score(y_test, preds)
        hl_ab  = hamming_loss(y_test, preds)

        wf1_list.append(wf1_ab)
        acc_list.append(acc_ab)
        hl_list.append(hl_ab)

    paper_single_results.append({
        "Bacteria": species,
        "ACC": np.mean(acc_list),
        "HL": np.mean(hl_list),
        "WF1": np.mean(wf1_list)
    })

paper_single_df = pd.DataFrame(paper_single_results).sort_values("Bacteria")
paper_single_df

                 Bacteria       ACC        HL       WF1
1        Escherichia_Coli  0.810215  0.189785  0.737506
2   Klebsiella_Pneumoniae  0.913685  0.086315  0.874154
3  Pseudomonas_Aeruginosa  0.880531  0.119469  0.824618
0   Staphylococcus_Aureus  0.579120  0.420880  0.514683

In [19]:
from sklearn.metrics import f1_score, accuracy_score, hamming_loss

detailed_results = []
summary_results = []

for species, ab_list in species_antibiotics.items():

    print(f"\n================ {species} ================")

    df_sp = species_datasets[species]
    test_idx = global_splits[species]["test_idx"]

    wf1_list = []
    acc_list = []
    hl_list = []

    for ab in ab_list:

        model_path = os.path.join(MODEL_DIR, f"{species}_{ab}_best_model.pt")
        checkpoint = torch.load(model_path, map_location=device)

        params = checkpoint["params"]

        model = MLPBinary(
            input_dim=X.shape[1],
            layer1=params["layer1"],
            layer2=params["layer2"],
            layer3=params["layer3"],
            activation=params["activation"]
        ).to(device)

        model.load_state_dict(checkpoint["model_state_dict"])
        model.eval()

        # Test data
        X_test = torch.tensor(X[test_idx], dtype=torch.float32).to(device)
        y_test = df_sp.loc[test_idx, ab].astype(int).values

        with torch.no_grad():
            logits = model(X_test)
            preds = (torch.sigmoid(logits) > 0.5).cpu().numpy().ravel()

        # Métricas binarias por antibiótico
        wf1 = f1_score(y_test, preds, average="weighted")
        acc = accuracy_score(y_test, preds)
        hl  = hamming_loss(y_test, preds)

        wf1_list.append(wf1)
        acc_list.append(acc)
        hl_list.append(hl)

        detailed_results.append({
            "Species": species,
            "Antibiotic": ab,
            "ACC": acc,
            "HL": hl,
            "WF1": wf1
        })

        print(f"{ab}")
        print(f"  ACC:  {acc:.4f}")
        print(f"  HL:   {hl:.4f}")
        print(f"  WF1:  {wf1:.4f}")

    # Media entre antibióticos (exactamente como el paper)
    summary_results.append({
        "Species": species,
        "Mean_ACC": np.mean(acc_list),
        "Mean_HL": np.mean(hl_list),
        "Mean_WF1": np.mean(wf1_list)
    })

    print("\n→ Media por especie")
    print(f"  ACC:  {np.mean(acc_list):.4f}")
    print(f"  HL:   {np.mean(hl_list):.4f}")
    print(f"  WF1:  {np.mean(wf1_list):.4f}")

================ Staphylococcus_Aureus ================
Oxacillin
  ACC:  0.7992
  HL:   0.2008
  WF1:  0.7099
Clindamycin
  ACC:  0.8567
  HL:   0.1433
  WF1:  0.7906
Fusidic acid
  ACC:  0.0815
  HL:   0.9185
  WF1:  0.0435

→ Media por especie
  ACC:  0.5791
  HL:   0.4209
  WF1:  0.5147

================ Escherichia_Coli ================
Ciprofloxacin
  ACC:  0.7086
  HL:   0.2914
  WF1:  0.5904
Ceftriaxone
  ACC:  0.7957
  HL:   0.2043
  WF1:  0.7052
Piperacillin-Tazobactam
  ACC:  0.9043
  HL:   0.0957
  WF1:  0.8984
Cefepime
  ACC:  0.8323
  HL:   0.1677
  WF1:  0.7561

→ Media por especie
  ACC:  0.8102
  HL:   0.1898
  WF1:  0.7375

================ Klebsiella_Pneumoniae ================
Ciprofloxacin
  ACC:  0.8211
  HL:   0.1789
  WF1:  0.7405
Ceftriaxone
  ACC:  0.8551
  HL:   0.1449
  WF1:  0.7883
Imipenem
  ACC:  0.9893
  HL:   0.0107
  WF1:  0.9839
Meropenem
  ACC:  0.9893
  HL:   0.0107
  WF1:  0.9839

→ Media por especie
  ACC:  0.9137
  HL:   0.0863
  WF1:  0.8742

================ Pseudomonas_Aeruginosa ================
Ciprofloxacin
  ACC:  0.8739
  HL:   0.1261
  WF1:  0.8151
Imipenem
  ACC:  0.8739
  HL:   0.1261
  WF1:  0.8151
Meropenem
  ACC:  0.8938
  HL:   0.1062
  WF1:  0.8437

→ Media por especie
  ACC:  0.8805
  HL:   0.1195
  WF1:  0.8246

In [20]:
detailed_df = pd.DataFrame(detailed_results)
summary_df = pd.DataFrame(summary_results)

print("\n===== RESULTADOS POR ANTIBIÓTICO =====")
display(detailed_df.sort_values(["Species", "WF1"], ascending=[True, False]))

print("\n===== RESULTADOS FINALES POR ESPECIE (Table 7 style) =====")
display(summary_df.sort_values("Mean_WF1", ascending=False))

===== RESULTADOS POR ANTIBIÓTICO =====

,Species,Antibiotic,ACC,HL,WF1
5,Escherichia_Coli,Piperacillin-Tazobactam,0.904301,0.095699,0.898360
6,Escherichia_Coli,Cefepime,0.832258,0.167742,0.756065
4,Escherichia_Coli,Ceftriaxone,0.795699,0.204301,0.705170
3,Escherichia_Coli,Ciprofloxacin,0.708602,0.291398,0.590427
9,Klebsiella_Pneumoniae,Imipenem,0.989267,0.010733,0.983929
10,Klebsiella_Pneumoniae,Meropenem,0.989267,0.010733,0.983929
8,Klebsiella_Pneumoniae,Ceftriaxone,0.855098,0.144902,0.788307
7,Klebsiella_Pneumoniae,Ciprofloxacin,0.821109,0.178891,0.740450
13,Pseudomonas_Aeruginosa,Meropenem,0.893805,0.106195,0.843685
11,Pseudomonas_Aeruginosa,Ciprofloxacin,0.873894,0.126106,0.815084
12,Pseudomonas_Aeruginosa,Imipenem,0.873894,0.126106,0.815084
1,Staphylococcus_Aureus,Clindamycin,0.856742,0.143258,0.790639
0,Staphylococcus_Aureus,Oxacillin,0.799157,0.200843,0.709946
2,Staphylococcus_Aureus,Fusidic acid,0.081461,0.918539,0.043464

===== RESULTADOS FINALES POR ESPECIE (Table 7 style) =====

                  Species  Mean_ACC   Mean_HL  Mean_WF1
2   Klebsiella_Pneumoniae  0.913685  0.086315  0.874154
3  Pseudomonas_Aeruginosa  0.880531  0.119469  0.824618
1        Escherichia_Coli  0.810215  0.189785  0.737506
0   Staphylococcus_Aureus  0.579120  0.420880  0.514683

# 6. Label Power Set (LPS) – Multiclass Implementation in PyTorch

In this section we replicate the multi-label experiment described in the paper
using the Label Power Set (LPS) strategy.

The idea is:

1. Each resistance pattern (e.g., "0101") is treated as a single multiclass label.
2. We train a multiclass neural network.
3. After prediction, we transform LPS predictions back into multilabel format.
4. We compute WF1, ACC and HL exactly as described in the paper.

Important:
- We use the SAME global stratified train/test split defined earlier.
- Bayesian optimization is performed using Optuna.
- Early stopping is applied during training.

## 6.1 Multiclass MLP Architecture (LPS)

We define a PyTorch multiclass neural network that outputs:

    n_patterns neurons

where n_patterns = number of valid resistance combinations for that species.

In [21]:
class MLPLPS(nn.Module):
    def __init__(self, input_dim, n_classes, layer1, layer2, layer3, activation):
        super().__init__()

        activations = {
            "relu": nn.ReLU(),
            "tanh": nn.Tanh(),
            "logistic": nn.Sigmoid(),
            "identity": nn.Identity()
        }

        act = activations[activation]

        self.model = nn.Sequential(
            nn.Linear(input_dim, layer1),
            act,
            nn.Linear(layer1, layer2),
            act,
            nn.Linear(layer2, layer3),
            act,
            nn.Linear(layer3, n_classes)
        )

    def forward(self, x):
        return self.model(x)

## 6.2 Converting LPS Predictions Back to Multilabel

After predicting a multiclass label (e.g. class index 3),
we transform it back to the original resistance pattern string,
and then to a list of binary labels.

This ensures fair comparison with the single-label benchmark.

In [22]:
def lps_index_to_multilabel(pred_indices, class_to_pattern):
    multilabel_preds = []

    for idx in pred_indices:
        pattern = class_to_pattern[idx]
        multilabel_preds.append([int(x) for x in pattern])

    return np.array(multilabel_preds)

## 6.3 Evaluation Metrics (Paper-consistent)

Steps:
1. Transform LPS predictions to multilabel.
2. Compute WF1 independently for each antibiotic.
3. Average across antibiotics.

In [23]:
def evaluate_lps(y_true_patterns, y_pred_indices, class_to_pattern, ab_list):

    y_true_multi = np.array([[int(x) for x in p] for p in y_true_patterns])
    y_pred_multi = lps_index_to_multilabel(y_pred_indices, class_to_pattern)

    wf1_list = []
    acc_list = []
    hl_list = []

    for j in range(len(ab_list)):
        y_true_ab = y_true_multi[:, j]
        y_pred_ab = y_pred_multi[:, j]

        wf1 = f1_score(y_true_ab, y_pred_ab, average="weighted")
        acc = accuracy_score(y_true_ab, y_pred_ab)
        hl  = hamming_loss(y_true_ab, y_pred_ab)

        wf1_list.append(wf1)
        acc_list.append(acc)
        hl_list.append(hl)

    return {
        "WF1": np.mean(wf1_list),
        "ACC": np.mean(acc_list),
        "HL": np.mean(hl_list)
    }

## 6.4 Bayesian Optimization with Early Stopping

We optimize:

- layer sizes
- activation
- learning rate
- weight decay

Objective metric: WF1 (paper primary metric)

In [30]:
from tqdm.auto import tqdm

def objective_lps(trial, X_train, y_train, X_val, y_val, n_classes, class_to_pattern, ab_list):

    layer1 = trial.suggest_int("layer1", 50, 500)
    layer2 = trial.suggest_int("layer2", 50, 500)
    layer3 = trial.suggest_int("layer3", 50, 500)
    activation = trial.suggest_categorical("activation", ["relu", "tanh"])
    lr = trial.suggest_float("lr", 1e-5, 1e-2, log=True)
    wd = trial.suggest_float("weight_decay", 1e-6, 1e-2, log=True)

    model = MLPLPS(X_train.shape[1], n_classes,
                   layer1, layer2, layer3, activation).to(device)

    optimizer = torch.optim.Adam(model.parameters(), lr=lr, weight_decay=wd)
    criterion = nn.CrossEntropyLoss()

    X_train_t = torch.tensor(X_train, dtype=torch.float32).to(device)
    y_train_t = torch.tensor(y_train, dtype=torch.long).to(device)
    X_val_t = torch.tensor(X_val, dtype=torch.float32).to(device)

    best_val = 0
    patience = 15
    counter = 0

    for epoch in range(200):

        model.train()
        optimizer.zero_grad()

        logits = model(X_train_t)
        loss = criterion(logits, y_train_t)

        loss.backward()
        optimizer.step()

        model.eval()
        with torch.no_grad():
            val_logits = model(X_val_t)
            preds = torch.argmax(val_logits, dim=1).cpu().numpy()
            
        y_val_patterns = [class_to_pattern[i] for i in y_val]
        metrics = evaluate_lps(
            y_val_patterns,
            preds,
            class_to_pattern,
            ab_list
        )

        if metrics["WF1"] > best_val:
            best_val = metrics["WF1"]
            counter = 0
        else:
            counter += 1
            if counter >= patience:
                break

    return best_val

## 6.5 Training Final LPS Model per Species

For each bacterial species:

1. Encode patterns into class indices.
2. Perform internal validation split.
3. Run Optuna Bayesian optimization.
4. Retrain best model on full training set.
5. Evaluate on test set.

In [ ]:
from sklearn.model_selection import StratifiedKFold, train_test_split

lps_results = []

N_TRIALS = 200
N_FOLDS = 5
LPS_MODEL_DIR = "../models_lps"
os.makedirs(LPS_MODEL_DIR, exist_ok=True)

for species, ab_list in species_antibiotics.items():

    print(f"\n\n==============================")
    print(f"   LPS TRAINING → {species}")
    print(f"==============================\n")

    df_species = species_datasets[species]
    train_idx = global_splits[species]["train_idx"]
    test_idx = global_splits[species]["test_idx"]

    df_train = df_species.loc[train_idx]
    df_test  = df_species.loc[test_idx]

    X_train = X[train_idx]
    X_test  = X[test_idx]

    patterns = df_train["pattern"].unique()
    pattern_to_class = {p:i for i,p in enumerate(patterns)}
    class_to_pattern = {i:p for p,i in pattern_to_class.items()}

    y_train = df_train["pattern"].map(pattern_to_class).values
    y_test_patterns = df_test["pattern"].values

    skf = StratifiedKFold(n_splits=N_FOLDS, shuffle=True, random_state=42)

    def objective_cv(trial):

        layer1 = trial.suggest_int("layer1", 50, 500)
        layer2 = trial.suggest_int("layer2", 50, 500)
        layer3 = trial.suggest_int("layer3", 50, 500)
        activation = trial.suggest_categorical("activation", ["relu", "tanh"])
        lr = trial.suggest_float("lr", 1e-5, 1e-2, log=True)
        wd = trial.suggest_float("weight_decay", 1e-6, 1e-2, log=True)

        fold_scores = []

        for train_fold_idx, val_fold_idx in skf.split(X_train, y_train):

            X_tr = X_train[train_fold_idx]
            y_tr = y_train[train_fold_idx]
            X_val = X_train[val_fold_idx]
            y_val = y_train[val_fold_idx]

            model = MLPLPS(
                X_train.shape[1],
                len(pattern_to_class),
                layer1, layer2, layer3,
                activation
            ).to(device)

            optimizer = torch.optim.Adam(model.parameters(), lr=lr, weight_decay=wd)
            criterion = nn.CrossEntropyLoss()

            X_tr_t = torch.tensor(X_tr, dtype=torch.float32).to(device)
            y_tr_t = torch.tensor(y_tr, dtype=torch.long).to(device)
            X_val_t = torch.tensor(X_val, dtype=torch.float32).to(device)

            best_val = 0
            patience = 15
            counter = 0

            for epoch in range(200):

                model.train()
                optimizer.zero_grad()
                logits = model(X_tr_t)
                loss = criterion(logits, y_tr_t)
                loss.backward()
                optimizer.step()

                model.eval()
                with torch.no_grad():
                    val_logits = model(X_val_t)
                    preds = torch.argmax(val_logits, dim=1).cpu().numpy()

                y_val_patterns = [class_to_pattern[i] for i in y_val]

                metrics = evaluate_lps(
                    y_val_patterns,
                    preds,
                    class_to_pattern,
                    ab_list
                )

                val_wf1 = metrics["WF1"]

                if val_wf1 > best_val:
                    best_val = val_wf1
                    counter = 0
                else:
                    counter += 1
                    if counter >= patience:
                        break

            fold_scores.append(best_val)

        return np.mean(fold_scores)

    study = optuna.create_study(direction="maximize")

    with tqdm(total=N_TRIALS, desc=f"{species} - Optuna 5CV") as pbar:

        def callback(study, trial):
            pbar.update(1)
            pbar.set_postfix(best_WF1=round(study.best_value, 4))

        study.optimize(
            objective_cv,
            n_trials=N_TRIALS,
            callbacks=[callback]
        )

    best_val_wf1 = study.best_value
    best_params = study.best_params

    print("\nBest CV WF1:", round(best_val_wf1, 4))
    print("Best params:", best_params)

    # ===== Retrain best model with VALIDATION-based early stopping =====

    final_model = MLPLPS(
        X_train.shape[1],
        len(pattern_to_class),
        best_params["layer1"],
        best_params["layer2"],
        best_params["layer3"],
        best_params["activation"]
    ).to(device)

    optimizer = torch.optim.Adam(
        final_model.parameters(),
        lr=best_params["lr"],
        weight_decay=best_params["weight_decay"]
    )

    criterion = nn.CrossEntropyLoss()

    # Split train into train_final / val_final
    X_train_final, X_val_final, y_train_final, y_val_final = train_test_split(
        X_train,
        y_train,
        test_size=0.1,
        stratify=y_train,
        random_state=42
    )

    X_train_final_t = torch.tensor(X_train_final, dtype=torch.float32).to(device)
    y_train_final_t = torch.tensor(y_train_final, dtype=torch.long).to(device)
    X_val_final_t = torch.tensor(X_val_final, dtype=torch.float32).to(device)

    best_state = None
    best_val_score = -np.inf
    patience = 20
    patience_counter = 0

    print("\nFinal training with validation-based early stopping...")

    for epoch in tqdm(range(500), desc=f"{species} - Final retrain"):

        final_model.train()
        optimizer.zero_grad()
        logits = final_model(X_train_final_t)
        loss = criterion(logits, y_train_final_t)
        loss.backward()
        optimizer.step()

        final_model.eval()
        with torch.no_grad():
            val_logits = final_model(X_val_final_t)
            val_preds = torch.argmax(val_logits, dim=1).cpu().numpy()

        y_val_patterns = [class_to_pattern[i] for i in y_val_final]

        metrics = evaluate_lps(
            y_val_patterns,
            val_preds,
            class_to_pattern,
            ab_list
        )

        val_wf1 = metrics["WF1"]

        if val_wf1 > best_val_score:
            best_val_score = val_wf1
            best_state = final_model.state_dict()
            patience_counter = 0
        else:
            patience_counter += 1

        if patience_counter >= patience:
            break

    final_model.load_state_dict(best_state)

    print("Best validation WF1 (retrain):", round(best_val_score, 4))

    # ===== Test evaluation =====

    X_test_t  = torch.tensor(X_test, dtype=torch.float32).to(device)

    final_model.eval()
    with torch.no_grad():
        test_logits = final_model(X_test_t)
        test_preds = torch.argmax(test_logits, dim=1).cpu().numpy()

    metrics = evaluate_lps(
        y_test_patterns,
        test_preds,
        class_to_pattern,
        ab_list
    )

    print("\nTEST RESULTS")
    print("WF1:", round(metrics["WF1"], 4))
    print("ACC:", round(metrics["ACC"], 4))
    print("HL :", round(metrics["HL"], 4))

    model_path = os.path.join(LPS_MODEL_DIR, f"{species}_lps_best_model.pth")

    torch.save({
        "model_state_dict": final_model.state_dict(),
        "best_params": best_params,
        "validation_WF1": best_val_wf1,
        "retrain_validation_WF1": best_val_score,
        "test_WF1": metrics["WF1"],
        "test_ACC": metrics["ACC"],
        "test_HL": metrics["HL"],
        "pattern_to_class": pattern_to_class,
        "class_to_pattern": class_to_pattern,
        "species": species,
        "antibiotics": ab_list
    }, model_path)

    print(f"\nModel saved to: {model_path}")

    lps_results.append({
        "Species": species,
        "Validation_WF1": best_val_wf1,
        "Retrain_Validation_WF1": best_val_score,
        "Test_WF1": metrics["WF1"],
        "Test_ACC": metrics["ACC"],
        "Test_HL": metrics["HL"]
    })

lps_results_df = pd.DataFrame(lps_results)
lps_results_df

[I 2026-02-21 19:22:00,128] A new study created in memory with name: no-name-3802a4ad-d748-4848-9cb4-b9bf1ae13be8

==============================
   LPS TRAINING → Staphylococcus_Aureus
==============================

Staphylococcus_Aureus - Optuna 5CV:   0%|          | 0/200 [00:00<?, ?it/s][I 2026-02-21 19:22:02,272] Trial 0 finished with value: 0.8016455484651599 and parameters: {'layer1': 55, 'layer2': 204, 'layer3': 254, 'activation': 'relu', 'lr': 0.00044260462213580574, 'weight_decay': 0.0006323461445216271}. Best is trial 0 with value: 0.8016455484651599.
Staphylococcus_Aureus - Optuna 5CV:   0%|          | 1/200 [00:02<07:06,  2.14s/it, best_WF1=0.802][I 2026-02-21 19:22:07,302] Trial 1 finished with value: 0.8016455484651599 and parameters: {'layer1': 494, 'layer2': 423, 'layer3': 395, 'activation': 'relu', 'lr': 0.00010083273147567263, 'weight_decay': 1.684144343197247e-05}. Best is trial 0 with value: 0.8016455484651599.
Staphylococcus_Aureus - Optuna 5CV:   1%|          | 2/200 [00:07<12:40,  3.84s/it, best_WF1=0.802][I 2026-02-21 19:22:13,582] Trial 2 finished with value: 0.8054212644811422 and parameters: {'layer1': 362, 'layer2': 393, 'layer3': 251, 'activation': 'relu', 'lr': 1.8145247196902203e-05, 'weight_decay': 6.238582021866491e-05}. Best is trial 2 with value: 0.8054212644811422.
Staphylococcus_Aureus - Optuna 5CV:   2%|▏         | 3/200 [00:13<16:16,  4.95s/it, best_WF1=0.805][I 2026-02-21 19:22:17,434] Trial 3 finished with value: 0.8032667943391507 and parameters: {'layer1': 170, 'layer2': 361, 'layer3': 440, 'activation': 'tanh', 'lr': 1.3689966789987662e-05, 'weight_decay': 3.145622971927115e-05}. Best is trial 2 with value: 0.8054212644811422.
Staphylococcus_Aureus - Optuna 5CV:   2%|▏         | 4/200 [00:17<14:45,  4.52s/it, best_WF1=0.805][I 2026-02-21 19:22:20,324] Trial 4 finished with value: 0.8016455484651599 and parameters: {'layer1': 209, 'layer2': 163, 'layer3': 85, 'activation': 'tanh', 'lr': 0.0009489488101223363, 'weight_decay': 0.0008252271870034415}. Best is trial 2 with value: 0.8054212644811422.
Staphylococcus_Aureus - Optuna 5CV:   2%|▎         | 5/200 [00:20<12:46,  3.93s/it, best_WF1=0.805][I 2026-02-21 19:22:23,746] Trial 5 finished with value: 0.8016455484651599 and parameters: {'layer1': 278, 'layer2': 363, 'layer3': 444, 'activation': 'relu', 'lr': 0.0005448859686088486, 'weight_decay': 0.0011894959080066187}. Best is trial 2 with value: 0.8054212644811422.
Staphylococcus_Aureus - Optuna 5CV:   3%|▎         | 6/200 [00:23<12:09,  3.76s/it, best_WF1=0.805][I 2026-02-21 19:22:27,469] Trial 6 finished with value: 0.8016455484651599 and parameters: {'layer1': 382, 'layer2': 241, 'layer3': 276, 'activation': 'tanh', 'lr': 0.0013565793329220193, 'weight_decay': 5.439669242949951e-06}. Best is trial 2 with value: 0.8054212644811422.
Staphylococcus_Aureus - Optuna 5CV:   4%|▎         | 7/200 [00:27<12:03,  3.75s/it, best_WF1=0.805][I 2026-02-21 19:22:30,644] Trial 7 finished with value: 0.8021394484938427 and parameters: {'layer1': 225, 'layer2': 202, 'layer3': 467, 'activation': 'tanh', 'lr': 7.437340528113481e-05, 'weight_decay': 2.4465432339382917e-06}. Best is trial 2 with value: 0.8054212644811422.
Staphylococcus_Aureus - Optuna 5CV:   4%|▍         | 8/200 [00:30<11:24,  3.56s/it, best_WF1=0.805][I 2026-02-21 19:22:37,428] Trial 8 finished with value: 0.8152189392603774 and parameters: {'layer1': 359, 'layer2': 353, 'layer3': 214, 'activation': 'tanh', 'lr': 0.001767737982092195, 'weight_decay': 1.4811922226641342e-05}. Best is trial 8 with value: 0.8152189392603774.
Staphylococcus_Aureus - Optuna 5CV:   4%|▍         | 9/200 [00:37<14:33,  4.57s/it, best_WF1=0.815][I 2026-02-21 19:22:40,319] Trial 9 finished with value: 0.8016455484651599 and parameters: {'layer1': 169, 'layer2': 210, 'layer3': 284, 'activation': 'relu', 'lr': 0.0001535530542155915, 'weight_decay': 0.0005189739552598536}. Best is trial 8 with value: 0.8152189392603774.
Staphylococcus_Aureus - Optuna 5CV:   5%|▌         | 10/200 [00:40<12:49,  4.05s/it, best_WF1=0.815][I 2026-02-21 19:22:44,567] Trial 10 finished with value: 0.8016455484651599 and parameters: {'layer1': 492, 'layer2': 77, 'layer3': 84, 'activation': 'tanh', 'lr': 0.005765820448180207, 'weight_decay': 0.007627536328703025}. Best is trial 8 with value: 0.8152189392603774.
Staphylococcus_Aureus - Optuna 5CV:   6%|▌         | 11/200 [00:44<12:57,  4.11s/it, best_WF1=0.815][I 2026-02-21 19:22:51,086] Trial 11 finished with value: 0.8038676303479761 and parameters: {'layer1': 359, 'layer2': 462, 'layer3': 183, 'activation': 'relu', 'lr': 1.1576950851981659e-05, 'weight_decay': 8.295442459991246e-05}. Best is trial 8 with value: 0.8152189392603774.
Staphylococcus_Aureus - Optuna 5CV:   6%|▌         | 12/200 [00:50<15:10,  4.84s/it, best_WF1=0.815][I 2026-02-21 19:22:54,937] Trial 12 finished with value: 0.8016455484651599 and parameters: {'layer1': 370, 'layer2': 324, 'layer3': 190, 'activation': 'relu', 'lr': 0.005352346196992417, 'weight_decay': 1.2713107708447718e-05}. Best is trial 8 with value: 0.8152189392603774.
Staphylococcus_Aureus - Optuna 5CV:   6%|▋         | 13/200 [00:54<14:09,  4.54s/it, best_WF1=0.815][I 2026-02-21 19:22:59,041] Trial 13 finished with value: 0.8016455484651599 and parameters: {'layer1': 421, 'layer2': 303, 'layer3': 326, 'activation': 'tanh', 'lr': 0.0018857146423290558, 'weight_decay': 9.210939675437098e-05}. Best is trial 8 with value: 0.8152189392603774.
Staphylococcus_Aureus - Optuna 5CV:   7%|▋         | 14/200 [00:58<13:40,  4.41s/it, best_WF1=0.815][I 2026-02-21 19:23:03,063] Trial 14 finished with value: 0.8028925349640954 and parameters: {'layer1': 312, 'layer2': 493, 'layer3': 177, 'activation': 'tanh', 'lr': 3.349574676154513e-05, 'weight_decay': 2.788394840030426e-06}. Best is trial 8 with value: 0.8152189392603774.
Staphylococcus_Aureus - Optuna 5CV:   8%|▊         | 15/200 [01:02<13:14,  4.29s/it, best_WF1=0.815][I 2026-02-21 19:23:06,676] Trial 15 finished with value: 0.8016455484651599 and parameters: {'layer1': 303, 'layer2': 399, 'layer3': 362, 'activation': 'relu', 'lr': 0.00262893750771144, 'weight_decay': 1.1613856042684447e-06}. Best is trial 8 with value: 0.8152189392603774.
Staphylococcus_Aureus - Optuna 5CV:   8%|▊         | 16/200 [01:06<12:32,  4.09s/it, best_WF1=0.815][I 2026-02-21 19:23:11,287] Trial 16 finished with value: 0.8020994488693279 and parameters: {'layer1': 436, 'layer2': 426, 'layer3': 143, 'activation': 'tanh', 'lr': 4.201680948065722e-05, 'weight_decay': 0.00018555556316141025}. Best is trial 8 with value: 0.8152189392603774.
Staphylococcus_Aureus - Optuna 5CV:   8%|▊         | 17/200 [01:11<12:56,  4.25s/it, best_WF1=0.815][I 2026-02-21 19:23:14,910] Trial 17 finished with value: 0.8024002795540313 and parameters: {'layer1': 338, 'layer2': 277, 'layer3': 214, 'activation': 'relu', 'lr': 0.00021782109470776253, 'weight_decay': 3.5369320436098506e-05}. Best is trial 8 with value: 0.8152189392603774.
Staphylococcus_Aureus - Optuna 5CV:   9%|▉         | 18/200 [01:14<12:18,  4.06s/it, best_WF1=0.815][I 2026-02-21 19:23:19,108] Trial 18 finished with value: 0.8016455484651599 and parameters: {'layer1': 423, 'layer2': 340, 'layer3': 124, 'activation': 'relu', 'lr': 0.0007503664997033096, 'weight_decay': 0.00021336664147562234}. Best is trial 8 with value: 0.8152189392603774.
Staphylococcus_Aureus - Optuna 5CV:  10%|▉         | 19/200 [01:18<12:22,  4.10s/it, best_WF1=0.815][I 2026-02-21 19:23:22,374] Trial 19 finished with value: 0.8016455484651599 and parameters: {'layer1': 254, 'layer2': 398, 'layer3': 236, 'activation': 'tanh', 'lr': 0.009518756409699538, 'weight_decay': 1.0459886963157125e-05}. Best is trial 8 with value: 0.8152189392603774.
Staphylococcus_Aureus - Optuna 5CV:  10%|█         | 20/200 [01:22<11:32,  3.85s/it, best_WF1=0.815][I 2026-02-21 19:23:25,335] Trial 20 finished with value: 0.8016455484651599 and parameters: {'layer1': 72, 'layer2': 127, 'layer3': 322, 'activation': 'tanh', 'lr': 2.464023301740046e-05, 'weight_decay': 3.792103436003158e-05}. Best is trial 8 with value: 0.8152189392603774.
Staphylococcus_Aureus - Optuna 5CV:  10%|█         | 21/200 [01:25<10:41,  3.58s/it, best_WF1=0.815][I 2026-02-21 19:23:32,230] Trial 21 finished with value: 0.8030882316054176 and parameters: {'layer1': 359, 'layer2': 495, 'layer3': 158, 'activation': 'relu', 'lr': 1.0350136430859803e-05, 'weight_decay': 8.35897363148052e-05}. Best is trial 8 with value: 0.8152189392603774.
Staphylococcus_Aureus - Optuna 5CV:  11%|█         | 22/200 [01:32<13:34,  4.58s/it, best_WF1=0.815][I 2026-02-21 19:23:37,359] Trial 22 finished with value: 0.8022687372325861 and parameters: {'layer1': 397, 'layer2': 475, 'layer3': 226, 'activation': 'relu', 'lr': 1.8855359598745476e-05, 'weight_decay': 0.00017197123426681307}. Best is trial 8 with value: 0.8152189392603774.
Staphylococcus_Aureus - Optuna 5CV:  12%|█▏        | 23/200 [01:37<13:59,  4.74s/it, best_WF1=0.815][I 2026-02-21 19:23:41,775] Trial 23 finished with value: 0.8021673134161913 and parameters: {'layer1': 338, 'layer2': 455, 'layer3': 305, 'activation': 'relu', 'lr': 4.2165575282977946e-05, 'weight_decay': 4.603141370549685e-05}. Best is trial 8 with value: 0.8152189392603774.
Staphylococcus_Aureus - Optuna 5CV:  12%|█▏        | 24/200 [01:41<13:37,  4.64s/it, best_WF1=0.815][I 2026-02-21 19:23:45,898] Trial 24 finished with value: 0.8022338610089094 and parameters: {'layer1': 298, 'layer2': 382, 'layer3': 113, 'activation': 'relu', 'lr': 6.496609269334561e-05, 'weight_decay': 7.1004268730297505e-06}. Best is trial 8 with value: 0.8152189392603774.
Staphylococcus_Aureus - Optuna 5CV:  12%|█▎        | 25/200 [01:45<13:05,  4.49s/it, best_WF1=0.815][I 2026-02-21 19:23:50,364] Trial 25 finished with value: 0.8016455484651599 and parameters: {'layer1': 462, 'layer2': 432, 'layer3': 206, 'activation': 'relu', 'lr': 0.0002286773074632018, 'weight_decay': 0.002283697000590983}. Best is trial 8 with value: 0.8152189392603774.
Staphylococcus_Aureus - Optuna 5CV:  13%|█▎        | 26/200 [01:50<12:59,  4.48s/it, best_WF1=0.815][I 2026-02-21 19:23:55,482] Trial 26 finished with value: 0.8021441673216912 and parameters: {'layer1': 336, 'layer2': 457, 'layer3': 245, 'activation': 'relu', 'lr': 1.0677878903085544e-05, 'weight_decay': 2.120814349643891e-05}. Best is trial 8 with value: 0.8152189392603774.
Staphylococcus_Aureus - Optuna 5CV:  14%|█▎        | 27/200 [01:55<13:28,  4.67s/it, best_WF1=0.815][I 2026-02-21 19:24:01,020] Trial 27 finished with value: 0.8017474336301745 and parameters: {'layer1': 391, 'layer2': 303, 'layer3': 175, 'activation': 'relu', 'lr': 2.1597893933048434e-05, 'weight_decay': 0.0003397658093989288}. Best is trial 8 with value: 0.8152189392603774.
Staphylococcus_Aureus - Optuna 5CV:  14%|█▍        | 28/200 [02:00<14:08,  4.93s/it, best_WF1=0.815][I 2026-02-21 19:24:05,213] Trial 28 finished with value: 0.8016455484651599 and parameters: {'layer1': 453, 'layer2': 349, 'layer3': 50, 'activation': 'tanh', 'lr': 0.0029576632954885452, 'weight_decay': 6.7722626483555e-05}. Best is trial 8 with value: 0.8152189392603774.
Staphylococcus_Aureus - Optuna 5CV:  14%|█▍        | 29/200 [02:05<13:25,  4.71s/it, best_WF1=0.815][I 2026-02-21 19:24:09,698] Trial 29 finished with value: 0.8016455484651599 and parameters: {'layer1': 408, 'layer2': 393, 'layer3': 258, 'activation': 'relu', 'lr': 0.00010431473906234102, 'weight_decay': 0.00012286565070449305}. Best is trial 8 with value: 0.8152189392603774.
Staphylococcus_Aureus - Optuna 5CV:  15%|█▌        | 30/200 [02:09<13:09,  4.64s/it, best_WF1=0.815][I 2026-02-21 19:24:13,098] Trial 30 finished with value: 0.8016455484651599 and parameters: {'layer1': 246, 'layer2': 453, 'layer3': 360, 'activation': 'relu', 'lr': 0.00041609877527619014, 'weight_decay': 0.00030430114453634127}. Best is trial 8 with value: 0.8152189392603774.
Staphylococcus_Aureus - Optuna 5CV:  16%|█▌        | 31/200 [02:12<12:01,  4.27s/it, best_WF1=0.815][I 2026-02-21 19:24:16,490] Trial 31 finished with value: 0.8024004233639246 and parameters: {'layer1': 121, 'layer2': 371, 'layer3': 428, 'activation': 'tanh', 'lr': 1.5090131151423244e-05, 'weight_decay': 2.4845378000150143e-05}. Best is trial 8 with value: 0.8152189392603774.
Staphylococcus_Aureus - Optuna 5CV:  16%|█▌        | 32/200 [02:16<11:13,  4.01s/it, best_WF1=0.815][I 2026-02-21 19:24:20,446] Trial 32 finished with value: 0.8020182011748188 and parameters: {'layer1': 165, 'layer2': 412, 'layer3': 490, 'activation': 'tanh', 'lr': 1.367500804190579e-05, 'weight_decay': 5.429692076907593e-05}. Best is trial 8 with value: 0.8152189392603774.
Staphylococcus_Aureus - Optuna 5CV:  16%|█▋        | 33/200 [02:20<11:06,  3.99s/it, best_WF1=0.815][I 2026-02-21 19:24:24,056] Trial 33 finished with value: 0.8026300298679635 and parameters: {'layer1': 193, 'layer2': 330, 'layer3': 385, 'activation': 'tanh', 'lr': 2.9071820004950253e-05, 'weight_decay': 2.6051256167895414e-05}. Best is trial 8 with value: 0.8152189392603774.
Staphylococcus_Aureus - Optuna 5CV:  17%|█▋        | 34/200 [02:23<10:43,  3.88s/it, best_WF1=0.815][I 2026-02-21 19:24:26,939] Trial 34 finished with value: 0.8017480818896596 and parameters: {'layer1': 117, 'layer2': 271, 'layer3': 200, 'activation': 'tanh', 'lr': 4.9823361912077896e-05, 'weight_decay': 1.531556585138502e-05}. Best is trial 8 with value: 0.8152189392603774.
Staphylococcus_Aureus - Optuna 5CV:  18%|█▊        | 35/200 [02:26<09:50,  3.58s/it, best_WF1=0.815][I 2026-02-21 19:24:31,602] Trial 35 finished with value: 0.8023237279716865 and parameters: {'layer1': 356, 'layer2': 368, 'layer3': 278, 'activation': 'tanh', 'lr': 1.697832853772275e-05, 'weight_decay': 7.570231519317131e-06}. Best is trial 8 with value: 0.8152189392603774.
Staphylococcus_Aureus - Optuna 5CV:  18%|█▊        | 36/200 [02:31<10:40,  3.90s/it, best_WF1=0.815][I 2026-02-21 19:24:35,170] Trial 36 finished with value: 0.8016455484651599 and parameters: {'layer1': 274, 'layer2': 438, 'layer3': 298, 'activation': 'tanh', 'lr': 0.00010488168089912938, 'weight_decay': 3.7680916388628703e-06}. Best is trial 8 with value: 0.8152189392603774.
Staphylococcus_Aureus - Optuna 5CV:  18%|█▊        | 37/200 [02:35<10:19,  3.80s/it, best_WF1=0.815][I 2026-02-21 19:24:38,662] Trial 37 finished with value: 0.8016455484651599 and parameters: {'layer1': 322, 'layer2': 349, 'layer3': 247, 'activation': 'relu', 'lr': 0.0011445441946444335, 'weight_decay': 0.00011765855639805545}. Best is trial 8 with value: 0.8152189392603774.
Staphylococcus_Aureus - Optuna 5CV:  19%|█▉        | 38/200 [02:38<10:00,  3.71s/it, best_WF1=0.815][I 2026-02-21 19:24:41,895] Trial 38 finished with value: 0.8016455484651599 and parameters: {'layer1': 268, 'layer2': 308, 'layer3': 144, 'activation': 'tanh', 'lr': 0.0005112673242413884, 'weight_decay': 0.000741751702940284}. Best is trial 8 with value: 0.8152189392603774.
Staphylococcus_Aureus - Optuna 5CV:  20%|█▉        | 39/200 [02:41<09:34,  3.57s/it, best_WF1=0.815][I 2026-02-21 19:24:46,258] Trial 39 finished with value: 0.8019942999296173 and parameters: {'layer1': 232, 'layer2': 424, 'layer3': 265, 'activation': 'tanh', 'lr': 1.0140176806133969e-05, 'weight_decay': 1.610350325935702e-05}. Best is trial 8 with value: 0.8152189392603774.
Staphylococcus_Aureus - Optuna 5CV:  20%|██        | 40/200 [02:46<10:08,  3.81s/it, best_WF1=0.815][I 2026-02-21 19:24:50,638] Trial 40 finished with value: 0.8024900039658981 and parameters: {'layer1': 372, 'layer2': 268, 'layer3': 415, 'activation': 'relu', 'lr': 2.8802896147099635e-05, 'weight_decay': 0.002269388769945822}. Best is trial 8 with value: 0.8152189392603774.
Staphylococcus_Aureus - Optuna 5CV:  20%|██        | 41/200 [02:50<10:32,  3.98s/it, best_WF1=0.815][I 2026-02-21 19:24:57,634] Trial 41 finished with value: 0.804761913752202 and parameters: {'layer1': 361, 'layer2': 500, 'layer3': 154, 'activation': 'relu', 'lr': 1.1800923514454263e-05, 'weight_decay': 6.589844601067652e-05}. Best is trial 8 with value: 0.8152189392603774.
Staphylococcus_Aureus - Optuna 5CV:  21%|██        | 42/200 [02:57<12:51,  4.88s/it, best_WF1=0.815][I 2026-02-21 19:25:04,595] Trial 42 finished with value: 0.8049418516423813 and parameters: {'layer1': 383, 'layer2': 475, 'layer3': 174, 'activation': 'relu', 'lr': 1.6232144543636432e-05, 'weight_decay': 5.9441280437796075e-05}. Best is trial 8 with value: 0.8152189392603774.
Staphylococcus_Aureus - Optuna 5CV:  22%|██▏       | 43/200 [03:04<14:24,  5.51s/it, best_WF1=0.815][I 2026-02-21 19:25:11,113] Trial 43 finished with value: 0.8040203748798789 and parameters: {'layer1': 389, 'layer2': 469, 'layer3': 103, 'activation': 'relu', 'lr': 1.5236615772352531e-05, 'weight_decay': 5.875809768776652e-05}. Best is trial 8 with value: 0.8152189392603774.
Staphylococcus_Aureus - Optuna 5CV:  22%|██▏       | 44/200 [03:10<15:06,  5.81s/it, best_WF1=0.815][I 2026-02-21 19:25:18,923] Trial 44 finished with value: 0.8037152495079875 and parameters: {'layer1': 385, 'layer2': 492, 'layer3': 98, 'activation': 'relu', 'lr': 1.9473829853811307e-05, 'weight_decay': 5.506716881514139e-05}. Best is trial 8 with value: 0.8152189392603774.
Staphylococcus_Aureus - Optuna 5CV:  22%|██▎       | 45/200 [03:18<16:33,  6.41s/it, best_WF1=0.815][I 2026-02-21 19:25:25,035] Trial 45 finished with value: 0.8037944402851572 and parameters: {'layer1': 486, 'layer2': 474, 'layer3': 125, 'activation': 'relu', 'lr': 5.178833961039912e-05, 'weight_decay': 3.290009171971144e-05}. Best is trial 8 with value: 0.8152189392603774.
Staphylococcus_Aureus - Optuna 5CV:  23%|██▎       | 46/200 [03:24<16:13,  6.32s/it, best_WF1=0.815][I 2026-02-21 19:25:31,935] Trial 46 finished with value: 0.8042346899783489 and parameters: {'layer1': 408, 'layer2': 478, 'layer3': 152, 'activation': 'relu', 'lr': 1.478359062880763e-05, 'weight_decay': 1.0222371518169022e-05}. Best is trial 8 with value: 0.8152189392603774.
Staphylococcus_Aureus - Optuna 5CV:  24%|██▎       | 47/200 [03:31<16:33,  6.49s/it, best_WF1=0.815][I 2026-02-21 19:25:36,805] Trial 47 finished with value: 0.8016455484651599 and parameters: {'layer1': 445, 'layer2': 483, 'layer3': 156, 'activation': 'relu', 'lr': 7.612307916044314e-05, 'weight_decay': 4.169683800875972e-06}. Best is trial 8 with value: 0.8152189392603774.
Staphylococcus_Aureus - Optuna 5CV:  24%|██▍       | 48/200 [03:36<15:13,  6.01s/it, best_WF1=0.815][I 2026-02-21 19:25:43,310] Trial 48 finished with value: 0.8046490018671989 and parameters: {'layer1': 420, 'layer2': 445, 'layer3': 69, 'activation': 'relu', 'lr': 3.215873805370628e-05, 'weight_decay': 9.588750275826325e-06}. Best is trial 8 with value: 0.8152189392603774.
Staphylococcus_Aureus - Optuna 5CV:  24%|██▍       | 49/200 [03:43<15:29,  6.16s/it, best_WF1=0.815][I 2026-02-21 19:25:47,879] Trial 49 finished with value: 0.8016455484651599 and parameters: {'layer1': 473, 'layer2': 443, 'layer3': 83, 'activation': 'relu', 'lr': 0.0007951391860958985, 'weight_decay': 6.357541343606742e-06}. Best is trial 8 with value: 0.8152189392603774.
Staphylococcus_Aureus - Optuna 5CV:  25%|██▌       | 50/200 [03:47<14:12,  5.68s/it, best_WF1=0.815][I 2026-02-21 19:25:53,381] Trial 50 finished with value: 0.8016455484651599 and parameters: {'layer1': 427, 'layer2': 417, 'layer3': 57, 'activation': 'relu', 'lr': 3.4620142565867e-05, 'weight_decay': 2.140957875372746e-06}. Best is trial 8 with value: 0.8152189392603774.
Staphylococcus_Aureus - Optuna 5CV:  26%|██▌       | 51/200 [03:53<13:58,  5.63s/it, best_WF1=0.815][I 2026-02-21 19:25:59,134] Trial 51 finished with value: 0.8018417551776889 and parameters: {'layer1': 404, 'layer2': 499, 'layer3': 178, 'activation': 'relu', 'lr': 2.388749113711232e-05, 'weight_decay': 9.499254789531168e-06}. Best is trial 8 with value: 0.8152189392603774.